require( "ui/uieditor/widgets/motd/motd_bannerimagetext" )
require( "ui/uieditor/widgets/motd/motd_bannerrender" )

CoD.MOTD_BannerImageInternal = InheritFrom( LUI.UIElement )
CoD.MOTD_BannerImageInternal.__defaultWidth = 328
CoD.MOTD_BannerImageInternal.__defaultHeight = 160
CoD.MOTD_BannerImageInternal.new = function ( f1_arg0, f1_arg1, f1_arg2, f1_arg3, f1_arg4, f1_arg5, f1_arg6, f1_arg7, f1_arg8, f1_arg9 )
	local self = LUI.UIElement.new( f1_arg2, f1_arg3, f1_arg4, f1_arg5, f1_arg6, f1_arg7, f1_arg8, f1_arg9 )
	self:setClass( CoD.MOTD_BannerImageInternal )
	self.id = "MOTD_BannerImageInternal"
	self.soundSet = "default"
	self.anyChildUsesUpdateState = true
	f1_arg0:addElementToPendingUpdateStateList( self )
	
	local FrameSelected = LUI.UIImage.new( 0, 1, -10, 10, 0, 1, -10, 10 )
	FrameSelected:setImage( RegisterImage( "uie_ui_menu_store_focus_frame" ) )
	FrameSelected:setMaterial( LUI.UIImage.GetCachedMaterial( "uie_nineslice_add" ) )
	FrameSelected:setShaderVector( 0, 0, 0, 0, 0 )
	FrameSelected:setupNineSliceShader( 28, 28 )
	self:addElement( FrameSelected )
	self.FrameSelected = FrameSelected
	
	local TiledBacking = LUI.UIImage.new( 0, 1, 0, 0, 0, 1, 0, 0 )
	TiledBacking:setAlpha( 0.5 )
	TiledBacking:setImage( RegisterImage( "uie_ui_menu_specialist_hub_repeat_bg" ) )
	TiledBacking:setMaterial( LUI.UIImage.GetCachedMaterial( 0x6CBE95C250C6D15 ) )
	TiledBacking:setShaderVector( 0, 0, 0, 0, 0 )
	TiledBacking:setupNineSliceShader( 196, 88 )
	self:addElement( TiledBacking )
	self.TiledBacking = TiledBacking
	
	local TiledGrid = LUI.UIImage.new( 0, 1, 1, -1, 0, 1, 1, -1 )
	TiledGrid:setScale( 1.01, 1.01 )
	TiledGrid:setImage( RegisterImage( "uie_ui_menu_store_bg_grid" ) )
	TiledGrid:setMaterial( LUI.UIImage.GetCachedMaterial( 0x6CBE95C250C6D15 ) )
	TiledGrid:setShaderVector( 0, 0, 0, 0, 0 )
	TiledGrid:setupNineSliceShader( 64, 64 )
	self:addElement( TiledGrid )
	self.TiledGrid = TiledGrid
	
	local MOTDBannerRender = CoD.MOTD_BannerRender.new( f1_arg0, f1_arg1, 0, 0, 0, 328, 0, 0, 0, 160 )
	self:addElement( MOTDBannerRender )
	self.MOTDBannerRender = MOTDBannerRender
	
	local MOTDBannerImageText = CoD.MOTD_BannerImageText.new( f1_arg0, f1_arg1, 0, 1, 0, 0, 1, 1, -26, 2 )
	self:addElement( MOTDBannerImageText )
	self.MOTDBannerImageText = MOTDBannerImageText
	
	local ItemFrame = LUI.UIImage.new( 0, 1, -1, 1, 0, 1, -1, 1 )
	ItemFrame:setImage( RegisterImage( "uie_ui_menu_store_common_frame" ) )
	ItemFrame:setMaterial( LUI.UIImage.GetCachedMaterial( "uie_nineslice_add" ) )
	ItemFrame:setShaderVector( 0, 0, 0, 0, 0 )
	ItemFrame:setupNineSliceShader( 12, 12 )
	self:addElement( ItemFrame )
	self.ItemFrame = ItemFrame
	
	local ItemFrameAdd = LUI.UIImage.new( 0, 1, -1, 1, 0, 1, -1, 1 )
	ItemFrameAdd:setAlpha( 0 )
	ItemFrameAdd:setImage( RegisterImage( "uie_ui_menu_store_common_frame" ) )
	ItemFrameAdd:setMaterial( LUI.UIImage.GetCachedMaterial( "uie_nineslice_add" ) )
	ItemFrameAdd:setShaderVector( 0, 0, 0, 0, 0 )
	ItemFrameAdd:setupNineSliceShader( 12, 12 )
	self:addElement( ItemFrameAdd )
	self.ItemFrameAdd = ItemFrameAdd
	
	local LockedIcon = LUI.UIImage.new( 0.5, 0.5, -64, 64, 0.5, 0.5, -64, 64 )
	LockedIcon:setAlpha( 0 )
	LockedIcon:setScale( 0.4, 0.4 )
	LockedIcon:setImage( RegisterImage( "uie_ui_icon_global_lock" ) )
	self:addElement( LockedIcon )
	self.LockedIcon = LockedIcon
	
	local FrameSelectedInnerGlow = LUI.UIImage.new( 0, 1, -10, 10, 0, 1, -10, 10 )
	FrameSelectedInnerGlow:setAlpha( 0 )
	FrameSelectedInnerGlow:setImage( RegisterImage( "uie_ui_menu_store_focus_frame" ) )
	FrameSelectedInnerGlow:setMaterial( LUI.UIImage.GetCachedMaterial( "uie_nineslice_add" ) )
	FrameSelectedInnerGlow:setShaderVector( 0, 0, 0, 0, 0 )
	FrameSelectedInnerGlow:setupNineSliceShader( 28, 28 )
	self:addElement( FrameSelectedInnerGlow )
	self.FrameSelectedInnerGlow = FrameSelectedInnerGlow
	
	local FrameSelectedCorner = LUI.UIImage.new( 0, 1, -8, 8, 0, 1, -8, 8 )
	FrameSelectedCorner:setImage( RegisterImage( 0x793C73633F620BB ) )
	FrameSelectedCorner:setMaterial( LUI.UIImage.GetCachedMaterial( "uie_nineslice_add" ) )
	FrameSelectedCorner:setShaderVector( 0, 0, 0, 0, 0 )
	FrameSelectedCorner:setupNineSliceShader( 44, 44 )
	self:addElement( FrameSelectedCorner )
	self.FrameSelectedCorner = FrameSelectedCorner
	
	self.MOTDBannerRender:linkToElementModel( self, nil, false, function ( model )
		MOTDBannerRender:setModel( model, f1_arg1 )
	end )
	self.MOTDBannerImageText:linkToElementModel( self, "title", true, function ( model )
		local f3_local0 = model:get()
		if f3_local0 ~= nil then
			MOTDBannerImageText.Title:setText( f3_local0 )
		end
	end )
	self:mergeStateConditions( {
		{
			stateName = "DefaultPC",
			condition = function ( menu, element, event )
				return IsPC()
			end
		}
	} )
	LUI.OverrideFunction_CallOriginalSecond( self, "close", self.__onClose )
	
	if PostLoadFunc then
		PostLoadFunc( self, f1_arg1, f1_arg0 )
	end
	
	return self
end

CoD.MOTD_BannerImageInternal.__resetProperties = function ( f5_arg0 )
	f5_arg0.FrameSelectedCorner:completeAnimation()
	f5_arg0.ItemFrameAdd:completeAnimation()
	f5_arg0.LockedIcon:completeAnimation()
	f5_arg0.FrameSelectedInnerGlow:completeAnimation()
	f5_arg0.TiledGrid:completeAnimation()
	f5_arg0.TiledBacking:completeAnimation()
	f5_arg0.FrameSelected:completeAnimation()
	f5_arg0.MOTDBannerImageText:completeAnimation()
	f5_arg0.ItemFrame:completeAnimation()
	f5_arg0.FrameSelectedCorner:setAlpha( 1 )
	f5_arg0.FrameSelectedCorner:setScale( 1, 1 )
	f5_arg0.ItemFrameAdd:setAlpha( 0 )
	f5_arg0.LockedIcon:setAlpha( 0 )
	f5_arg0.FrameSelectedInnerGlow:setAlpha( 0 )
	f5_arg0.TiledGrid:setAlpha( 1 )
	f5_arg0.TiledBacking:setAlpha( 0.5 )
	f5_arg0.FrameSelected:setAlpha( 1 )
	f5_arg0.MOTDBannerImageText:setAlpha( 1 )
	f5_arg0.ItemFrame:setAlpha( 1 )
end

CoD.MOTD_BannerImageInternal.__clipsPerState = {
	DefaultState = {
		DefaultClip = function ( f6_arg0, f6_arg1 )
			f6_arg0:__resetProperties()
			f6_arg0:setupElementClipCounter( 7 )
			f6_arg0.FrameSelected:completeAnimation()
			f6_arg0.FrameSelected:setAlpha( 0 )
			f6_arg0.clipFinished( f6_arg0.FrameSelected )
			f6_arg0.TiledBacking:completeAnimation()
			f6_arg0.TiledBacking:setAlpha( 0.5 )
			f6_arg0.clipFinished( f6_arg0.TiledBacking )
			f6_arg0.TiledGrid:completeAnimation()
			f6_arg0.TiledGrid:setAlpha( 0 )
			f6_arg0.clipFinished( f6_arg0.TiledGrid )
			f6_arg0.ItemFrameAdd:completeAnimation()
			f6_arg0.ItemFrameAdd:setAlpha( 0 )
			f6_arg0.clipFinished( f6_arg0.ItemFrameAdd )
			f6_arg0.LockedIcon:completeAnimation()
			f6_arg0.LockedIcon:setAlpha( 0 )
			f6_arg0.clipFinished( f6_arg0.LockedIcon )
			f6_arg0.FrameSelectedInnerGlow:completeAnimation()
			f6_arg0.FrameSelectedInnerGlow:setAlpha( 0 )
			f6_arg0.clipFinished( f6_arg0.FrameSelectedInnerGlow )
			f6_arg0.FrameSelectedCorner:completeAnimation()
			f6_arg0.FrameSelectedCorner:setAlpha( 0 )
			f6_arg0.FrameSelectedCorner:setScale( 1.05, 1.08 )
			f6_arg0.clipFinished( f6_arg0.FrameSelectedCorner )
		end,
		Focus = function ( f7_arg0, f7_arg1 )
			f7_arg0:__resetProperties()
			f7_arg0:setupElementClipCounter( 9 )
			f7_arg0.FrameSelected:completeAnimation()
			f7_arg0.FrameSelected:setAlpha( 1 )
			f7_arg0.clipFinished( f7_arg0.FrameSelected )
			f7_arg0.TiledBacking:completeAnimation()
			f7_arg0.TiledBacking:setAlpha( 0.5 )
			f7_arg0.clipFinished( f7_arg0.TiledBacking )
			f7_arg0.TiledGrid:completeAnimation()
			f7_arg0.TiledGrid:setAlpha( 0 )
			f7_arg0.clipFinished( f7_arg0.TiledGrid )
			f7_arg0.MOTDBannerImageText:completeAnimation()
			f7_arg0.MOTDBannerImageText:setAlpha( 1 )
			f7_arg0.clipFinished( f7_arg0.MOTDBannerImageText )
			f7_arg0.ItemFrame:completeAnimation()
			f7_arg0.ItemFrame:setAlpha( 1 )
			f7_arg0.clipFinished( f7_arg0.ItemFrame )
			f7_arg0.ItemFrameAdd:completeAnimation()
			f7_arg0.ItemFrameAdd:setAlpha( 1 )
			f7_arg0.clipFinished( f7_arg0.ItemFrameAdd )
			f7_arg0.LockedIcon:completeAnimation()
			f7_arg0.LockedIcon:setAlpha( 0 )
			f7_arg0.clipFinished( f7_arg0.LockedIcon )
			f7_arg0.FrameSelectedInnerGlow:completeAnimation()
			f7_arg0.FrameSelectedInnerGlow:setAlpha( 0.05 )
			f7_arg0.clipFinished( f7_arg0.FrameSelectedInnerGlow )
			f7_arg0.FrameSelectedCorner:completeAnimation()
			f7_arg0.FrameSelectedCorner:setAlpha( 1 )
			f7_arg0.FrameSelectedCorner:setScale( 1, 1 )
			f7_arg0.clipFinished( f7_arg0.FrameSelectedCorner )
		end,
		GainFocus = function ( f8_arg0, f8_arg1 )
			f8_arg0:__resetProperties()
			f8_arg0:setupElementClipCounter( 9 )
			local f8_local0 = function ( f9_arg0 )
				f8_arg0.FrameSelected:beginAnimation( 150, Enum[0xF50FFF429AB1890][0x5193EA7825DC097] )
				f8_arg0.FrameSelected:setAlpha( 1 )
				f8_arg0.FrameSelected:registerEventHandler( "interrupted_keyframe", f8_arg0.clipInterrupted )
				f8_arg0.FrameSelected:registerEventHandler( "transition_complete_keyframe", f8_arg0.clipFinished )
			end
			
			f8_arg0.FrameSelected:completeAnimation()
			f8_arg0.FrameSelected:setAlpha( 0 )
			f8_local0( f8_arg0.FrameSelected )
			f8_arg0.TiledBacking:completeAnimation()
			f8_arg0.TiledBacking:setAlpha( 0.5 )
			f8_arg0.clipFinished( f8_arg0.TiledBacking )
			f8_arg0.TiledGrid:completeAnimation()
			f8_arg0.TiledGrid:setAlpha( 0 )
			f8_arg0.clipFinished( f8_arg0.TiledGrid )
			f8_arg0.MOTDBannerImageText:completeAnimation()
			f8_arg0.MOTDBannerImageText:setAlpha( 1 )
			f8_arg0.clipFinished( f8_arg0.MOTDBannerImageText )
			f8_arg0.ItemFrame:completeAnimation()
			f8_arg0.ItemFrame:setAlpha( 1 )
			f8_arg0.clipFinished( f8_arg0.ItemFrame )
			local f8_local1 = function ( f10_arg0 )
				f8_arg0.ItemFrameAdd:beginAnimation( 150, Enum[0xF50FFF429AB1890][0x5193EA7825DC097] )
				f8_arg0.ItemFrameAdd:setAlpha( 1 )
				f8_arg0.ItemFrameAdd:registerEventHandler( "interrupted_keyframe", f8_arg0.clipInterrupted )
				f8_arg0.ItemFrameAdd:registerEventHandler( "transition_complete_keyframe", f8_arg0.clipFinished )
			end
			
			f8_arg0.ItemFrameAdd:completeAnimation()
			f8_arg0.ItemFrameAdd:setAlpha( 0 )
			f8_local1( f8_arg0.ItemFrameAdd )
			f8_arg0.LockedIcon:completeAnimation()
			f8_arg0.LockedIcon:setAlpha( 0 )
			f8_arg0.clipFinished( f8_arg0.LockedIcon )
			local f8_local2 = function ( f11_arg0 )
				f8_arg0.FrameSelectedInnerGlow:beginAnimation( 150, Enum[0xF50FFF429AB1890][0x5193EA7825DC097] )
				f8_arg0.FrameSelectedInnerGlow:setAlpha( 0.05 )
				f8_arg0.FrameSelectedInnerGlow:registerEventHandler( "interrupted_keyframe", f8_arg0.clipInterrupted )
				f8_arg0.FrameSelectedInnerGlow:registerEventHandler( "transition_complete_keyframe", f8_arg0.clipFinished )
			end
			
			f8_arg0.FrameSelectedInnerGlow:completeAnimation()
			f8_arg0.FrameSelectedInnerGlow:setAlpha( 0 )
			f8_local2( f8_arg0.FrameSelectedInnerGlow )
			local f8_local3 = function ( f12_arg0 )
				local f12_local0 = function ( f13_arg0 )
					f13_arg0:beginAnimation( 100, Enum[0xF50FFF429AB1890][0x53CEB9A0427197] )
					f13_arg0:setAlpha( 1 )
					f13_arg0:setScale( 1, 1 )
					f13_arg0:registerEventHandler( "transition_complete_keyframe", f8_arg0.clipFinished )
				end
				
				f8_arg0.FrameSelectedCorner:beginAnimation( 50 )
				f8_arg0.FrameSelectedCorner:setScale( 1.04, 1.06 )
				f8_arg0.FrameSelectedCorner:registerEventHandler( "interrupted_keyframe", f8_arg0.clipInterrupted )
				f8_arg0.FrameSelectedCorner:registerEventHandler( "transition_complete_keyframe", f12_local0 )
			end
			
			f8_arg0.FrameSelectedCorner:completeAnimation()
			f8_arg0.FrameSelectedCorner:setAlpha( 0 )
			f8_arg0.FrameSelectedCorner:setScale( 1.05, 1.08 )
			f8_local3( f8_arg0.FrameSelectedCorner )
		end,
		LoseFocus = function ( f14_arg0, f14_arg1 )
			f14_arg0:__resetProperties()
			f14_arg0:setupElementClipCounter( 9 )
			local f14_local0 = function ( f15_arg0 )
				f14_arg0.FrameSelected:beginAnimation( 150, Enum[0xF50FFF429AB1890][0x5193EA7825DC097] )
				f14_arg0.FrameSelected:setAlpha( 0 )
				f14_arg0.FrameSelected:registerEventHandler( "interrupted_keyframe", f14_arg0.clipInterrupted )
				f14_arg0.FrameSelected:registerEventHandler( "transition_complete_keyframe", f14_arg0.clipFinished )
			end
			
			f14_arg0.FrameSelected:completeAnimation()
			f14_arg0.FrameSelected:setAlpha( 1 )
			f14_local0( f14_arg0.FrameSelected )
			f14_arg0.TiledBacking:completeAnimation()
			f14_arg0.TiledBacking:setAlpha( 0.5 )
			f14_arg0.clipFinished( f14_arg0.TiledBacking )
			f14_arg0.TiledGrid:completeAnimation()
			f14_arg0.TiledGrid:setAlpha( 0 )
			f14_arg0.clipFinished( f14_arg0.TiledGrid )
			f14_arg0.MOTDBannerImageText:completeAnimation()
			f14_arg0.MOTDBannerImageText:setAlpha( 1 )
			f14_arg0.clipFinished( f14_arg0.MOTDBannerImageText )
			f14_arg0.ItemFrame:completeAnimation()
			f14_arg0.ItemFrame:setAlpha( 1 )
			f14_arg0.clipFinished( f14_arg0.ItemFrame )
			local f14_local1 = function ( f16_arg0 )
				f14_arg0.ItemFrameAdd:beginAnimation( 150, Enum[0xF50FFF429AB1890][0x5193EA7825DC097] )
				f14_arg0.ItemFrameAdd:setAlpha( 0 )
				f14_arg0.ItemFrameAdd:registerEventHandler( "interrupted_keyframe", f14_arg0.clipInterrupted )
				f14_arg0.ItemFrameAdd:registerEventHandler( "transition_complete_keyframe", f14_arg0.clipFinished )
			end
			
			f14_arg0.ItemFrameAdd:completeAnimation()
			f14_arg0.ItemFrameAdd:setAlpha( 1 )
			f14_local1( f14_arg0.ItemFrameAdd )
			f14_arg0.LockedIcon:completeAnimation()
			f14_arg0.LockedIcon:setAlpha( 0 )
			f14_arg0.clipFinished( f14_arg0.LockedIcon )
			local f14_local2 = function ( f17_arg0 )
				f14_arg0.FrameSelectedInnerGlow:beginAnimation( 150, Enum[0xF50FFF429AB1890][0x5193EA7825DC097] )
				f14_arg0.FrameSelectedInnerGlow:setAlpha( 0 )
				f14_arg0.FrameSelectedInnerGlow:registerEventHandler( "interrupted_keyframe", f14_arg0.clipInterrupted )
				f14_arg0.FrameSelectedInnerGlow:registerEventHandler( "transition_complete_keyframe", f14_arg0.clipFinished )
			end
			
			f14_arg0.FrameSelectedInnerGlow:completeAnimation()
			f14_arg0.FrameSelectedInnerGlow:setAlpha( 0.05 )
			f14_local2( f14_arg0.FrameSelectedInnerGlow )
			local f14_local3 = function ( f18_arg0 )
				local f18_local0 = function ( f19_arg0 )
					f19_arg0:beginAnimation( 50, Enum[0xF50FFF429AB1890][0x6F6186B702830BC] )
					f19_arg0:setScale( 1.05, 1.08 )
					f19_arg0:registerEventHandler( "transition_complete_keyframe", f14_arg0.clipFinished )
				end
				
				f14_arg0.FrameSelectedCorner:beginAnimation( 100 )
				f14_arg0.FrameSelectedCorner:setAlpha( 0 )
				f14_arg0.FrameSelectedCorner:setScale( 1.04, 1.06 )
				f14_arg0.FrameSelectedCorner:registerEventHandler( "interrupted_keyframe", f14_arg0.clipInterrupted )
				f14_arg0.FrameSelectedCorner:registerEventHandler( "transition_complete_keyframe", f18_local0 )
			end
			
			f14_arg0.FrameSelectedCorner:completeAnimation()
			f14_arg0.FrameSelectedCorner:setAlpha( 1 )
			f14_arg0.FrameSelectedCorner:setScale( 1, 1 )
			f14_local3( f14_arg0.FrameSelectedCorner )
		end
	},
	DefaultPC = {
		DefaultClip = function ( f20_arg0, f20_arg1 )
			f20_arg0:__resetProperties()
			f20_arg0:setupElementClipCounter( 7 )
			f20_arg0.FrameSelected:completeAnimation()
			f20_arg0.FrameSelected:setAlpha( 0 )
			f20_arg0.clipFinished( f20_arg0.FrameSelected )
			f20_arg0.TiledBacking:completeAnimation()
			f20_arg0.TiledBacking:setAlpha( 0.5 )
			f20_arg0.clipFinished( f20_arg0.TiledBacking )
			f20_arg0.TiledGrid:completeAnimation()
			f20_arg0.TiledGrid:setAlpha( 0 )
			f20_arg0.clipFinished( f20_arg0.TiledGrid )
			f20_arg0.ItemFrameAdd:completeAnimation()
			f20_arg0.ItemFrameAdd:setAlpha( 0 )
			f20_arg0.clipFinished( f20_arg0.ItemFrameAdd )
			f20_arg0.LockedIcon:completeAnimation()
			f20_arg0.LockedIcon:setAlpha( 0 )
			f20_arg0.clipFinished( f20_arg0.LockedIcon )
			f20_arg0.FrameSelectedInnerGlow:completeAnimation()
			f20_arg0.FrameSelectedInnerGlow:setAlpha( 0 )
			f20_arg0.clipFinished( f20_arg0.FrameSelectedInnerGlow )
			f20_arg0.FrameSelectedCorner:completeAnimation()
			f20_arg0.FrameSelectedCorner:setAlpha( 0 )
			f20_arg0.FrameSelectedCorner:setScale( 1.05, 1.08 )
			f20_arg0.clipFinished( f20_arg0.FrameSelectedCorner )
		end,
		Focus = function ( f21_arg0, f21_arg1 )
			f21_arg0:__resetProperties()
			f21_arg0:setupElementClipCounter( 9 )
			f21_arg0.FrameSelected:completeAnimation()
			f21_arg0.FrameSelected:setAlpha( 1 )
			f21_arg0.clipFinished( f21_arg0.FrameSelected )
			f21_arg0.TiledBacking:completeAnimation()
			f21_arg0.TiledBacking:setAlpha( 0.5 )
			f21_arg0.clipFinished( f21_arg0.TiledBacking )
			f21_arg0.TiledGrid:completeAnimation()
			f21_arg0.TiledGrid:setAlpha( 0 )
			f21_arg0.clipFinished( f21_arg0.TiledGrid )
			f21_arg0.MOTDBannerImageText:completeAnimation()
			f21_arg0.MOTDBannerImageText:setAlpha( 1 )
			f21_arg0.clipFinished( f21_arg0.MOTDBannerImageText )
			f21_arg0.ItemFrame:completeAnimation()
			f21_arg0.ItemFrame:setAlpha( 1 )
			f21_arg0.clipFinished( f21_arg0.ItemFrame )
			f21_arg0.ItemFrameAdd:completeAnimation()
			f21_arg0.ItemFrameAdd:setAlpha( 1 )
			f21_arg0.clipFinished( f21_arg0.ItemFrameAdd )
			f21_arg0.LockedIcon:completeAnimation()
			f21_arg0.LockedIcon:setAlpha( 0 )
			f21_arg0.clipFinished( f21_arg0.LockedIcon )
			f21_arg0.FrameSelectedInnerGlow:completeAnimation()
			f21_arg0.FrameSelectedInnerGlow:setAlpha( 0.05 )
			f21_arg0.clipFinished( f21_arg0.FrameSelectedInnerGlow )
			f21_arg0.FrameSelectedCorner:completeAnimation()
			f21_arg0.FrameSelectedCorner:setAlpha( 1 )
			f21_arg0.FrameSelectedCorner:setScale( 1, 1 )
			f21_arg0.clipFinished( f21_arg0.FrameSelectedCorner )
		end,
		GainFocus = function ( f22_arg0, f22_arg1 )
			f22_arg0:__resetProperties()
			f22_arg0:setupElementClipCounter( 9 )
			local f22_local0 = function ( f23_arg0 )
				f22_arg0.FrameSelected:beginAnimation( 150, Enum[0xF50FFF429AB1890][0x5193EA7825DC097] )
				f22_arg0.FrameSelected:setAlpha( 1 )
				f22_arg0.FrameSelected:registerEventHandler( "interrupted_keyframe", f22_arg0.clipInterrupted )
				f22_arg0.FrameSelected:registerEventHandler( "transition_complete_keyframe", f22_arg0.clipFinished )
			end
			
			f22_arg0.FrameSelected:completeAnimation()
			f22_arg0.FrameSelected:setAlpha( 0 )
			f22_local0( f22_arg0.FrameSelected )
			f22_arg0.TiledBacking:completeAnimation()
			f22_arg0.TiledBacking:setAlpha( 0.5 )
			f22_arg0.clipFinished( f22_arg0.TiledBacking )
			f22_arg0.TiledGrid:completeAnimation()
			f22_arg0.TiledGrid:setAlpha( 0 )
			f22_arg0.clipFinished( f22_arg0.TiledGrid )
			f22_arg0.MOTDBannerImageText:completeAnimation()
			f22_arg0.MOTDBannerImageText:setAlpha( 1 )
			f22_arg0.clipFinished( f22_arg0.MOTDBannerImageText )
			f22_arg0.ItemFrame:completeAnimation()
			f22_arg0.ItemFrame:setAlpha( 1 )
			f22_arg0.clipFinished( f22_arg0.ItemFrame )
			local f22_local1 = function ( f24_arg0 )
				f22_arg0.ItemFrameAdd:beginAnimation( 150, Enum[0xF50FFF429AB1890][0x5193EA7825DC097] )
				f22_arg0.ItemFrameAdd:setAlpha( 1 )
				f22_arg0.ItemFrameAdd:registerEventHandler( "interrupted_keyframe", f22_arg0.clipInterrupted )
				f22_arg0.ItemFrameAdd:registerEventHandler( "transition_complete_keyframe", f22_arg0.clipFinished )
			end
			
			f22_arg0.ItemFrameAdd:completeAnimation()
			f22_arg0.ItemFrameAdd:setAlpha( 0 )
			f22_local1( f22_arg0.ItemFrameAdd )
			f22_arg0.LockedIcon:completeAnimation()
			f22_arg0.LockedIcon:setAlpha( 0 )
			f22_arg0.clipFinished( f22_arg0.LockedIcon )
			local f22_local2 = function ( f25_arg0 )
				f22_arg0.FrameSelectedInnerGlow:beginAnimation( 150, Enum[0xF50FFF429AB1890][0x5193EA7825DC097] )
				f22_arg0.FrameSelectedInnerGlow:setAlpha( 0.05 )
				f22_arg0.FrameSelectedInnerGlow:registerEventHandler( "interrupted_keyframe", f22_arg0.clipInterrupted )
				f22_arg0.FrameSelectedInnerGlow:registerEventHandler( "transition_complete_keyframe", f22_arg0.clipFinished )
			end
			
			f22_arg0.FrameSelectedInnerGlow:completeAnimation()
			f22_arg0.FrameSelectedInnerGlow:setAlpha( 0 )
			f22_local2( f22_arg0.FrameSelectedInnerGlow )
			local f22_local3 = function ( f26_arg0 )
				local f26_local0 = function ( f27_arg0 )
					f27_arg0:beginAnimation( 100, Enum[0xF50FFF429AB1890][0x53CEB9A0427197] )
					f27_arg0:setAlpha( 1 )
					f27_arg0:setScale( 1, 1 )
					f27_arg0:registerEventHandler( "transition_complete_keyframe", f22_arg0.clipFinished )
				end
				
				f22_arg0.FrameSelectedCorner:beginAnimation( 50 )
				f22_arg0.FrameSelectedCorner:setScale( 1.04, 1.06 )
				f22_arg0.FrameSelectedCorner:registerEventHandler( "interrupted_keyframe", f22_arg0.clipInterrupted )
				f22_arg0.FrameSelectedCorner:registerEventHandler( "transition_complete_keyframe", f26_local0 )
			end
			
			f22_arg0.FrameSelectedCorner:completeAnimation()
			f22_arg0.FrameSelectedCorner:setAlpha( 0 )
			f22_arg0.FrameSelectedCorner:setScale( 1.05, 1.08 )
			f22_local3( f22_arg0.FrameSelectedCorner )
		end,
		LoseFocus = function ( f28_arg0, f28_arg1 )
			f28_arg0:__resetProperties()
			f28_arg0:setupElementClipCounter( 9 )
			local f28_local0 = function ( f29_arg0 )
				f28_arg0.FrameSelected:beginAnimation( 150, Enum[0xF50FFF429AB1890][0x5193EA7825DC097] )
				f28_arg0.FrameSelected:setAlpha( 0 )
				f28_arg0.FrameSelected:registerEventHandler( "interrupted_keyframe", f28_arg0.clipInterrupted )
				f28_arg0.FrameSelected:registerEventHandler( "transition_complete_keyframe", f28_arg0.clipFinished )
			end
			
			f28_arg0.FrameSelected:completeAnimation()
			f28_arg0.FrameSelected:setAlpha( 1 )
			f28_local0( f28_arg0.FrameSelected )
			f28_arg0.TiledBacking:completeAnimation()
			f28_arg0.TiledBacking:setAlpha( 0.5 )
			f28_arg0.clipFinished( f28_arg0.TiledBacking )
			f28_arg0.TiledGrid:completeAnimation()
			f28_arg0.TiledGrid:setAlpha( 0 )
			f28_arg0.clipFinished( f28_arg0.TiledGrid )
			f28_arg0.MOTDBannerImageText:completeAnimation()
			f28_arg0.MOTDBannerImageText:setAlpha( 1 )
			f28_arg0.clipFinished( f28_arg0.MOTDBannerImageText )
			f28_arg0.ItemFrame:completeAnimation()
			f28_arg0.ItemFrame:setAlpha( 1 )
			f28_arg0.clipFinished( f28_arg0.ItemFrame )
			local f28_local1 = function ( f30_arg0 )
				f28_arg0.ItemFrameAdd:beginAnimation( 150, Enum[0xF50FFF429AB1890][0x5193EA7825DC097] )
				f28_arg0.ItemFrameAdd:setAlpha( 0 )
				f28_arg0.ItemFrameAdd:registerEventHandler( "interrupted_keyframe", f28_arg0.clipInterrupted )
				f28_arg0.ItemFrameAdd:registerEventHandler( "transition_complete_keyframe", f28_arg0.clipFinished )
			end
			
			f28_arg0.ItemFrameAdd:completeAnimation()
			f28_arg0.ItemFrameAdd:setAlpha( 1 )
			f28_local1( f28_arg0.ItemFrameAdd )
			f28_arg0.LockedIcon:completeAnimation()
			f28_arg0.LockedIcon:setAlpha( 0 )
			f28_arg0.clipFinished( f28_arg0.LockedIcon )
			local f28_local2 = function ( f31_arg0 )
				f28_arg0.FrameSelectedInnerGlow:beginAnimation( 150, Enum[0xF50FFF429AB1890][0x5193EA7825DC097] )
				f28_arg0.FrameSelectedInnerGlow:setAlpha( 0 )
				f28_arg0.FrameSelectedInnerGlow:registerEventHandler( "interrupted_keyframe", f28_arg0.clipInterrupted )
				f28_arg0.FrameSelectedInnerGlow:registerEventHandler( "transition_complete_keyframe", f28_arg0.clipFinished )
			end
			
			f28_arg0.FrameSelectedInnerGlow:completeAnimation()
			f28_arg0.FrameSelectedInnerGlow:setAlpha( 0.05 )
			f28_local2( f28_arg0.FrameSelectedInnerGlow )
			local f28_local3 = function ( f32_arg0 )
				local f32_local0 = function ( f33_arg0 )
					f33_arg0:beginAnimation( 50, Enum[0xF50FFF429AB1890][0x6F6186B702830BC] )
					f33_arg0:setScale( 1.05, 1.08 )
					f33_arg0:registerEventHandler( "transition_complete_keyframe", f28_arg0.clipFinished )
				end
				
				f28_arg0.FrameSelectedCorner:beginAnimation( 100 )
				f28_arg0.FrameSelectedCorner:setAlpha( 0 )
				f28_arg0.FrameSelectedCorner:setScale( 1.04, 1.06 )
				f28_arg0.FrameSelectedCorner:registerEventHandler( "interrupted_keyframe", f28_arg0.clipInterrupted )
				f28_arg0.FrameSelectedCorner:registerEventHandler( "transition_complete_keyframe", f32_local0 )
			end
			
			f28_arg0.FrameSelectedCorner:completeAnimation()
			f28_arg0.FrameSelectedCorner:setAlpha( 1 )
			f28_arg0.FrameSelectedCorner:setScale( 1, 1 )
			f28_local3( f28_arg0.FrameSelectedCorner )
		end,
		Active = function ( f34_arg0, f34_arg1 )
			f34_arg0:__resetProperties()
			f34_arg0:setupElementClipCounter( 8 )
			f34_arg0.FrameSelected:completeAnimation()
			f34_arg0.FrameSelected:setAlpha( 1 )
			f34_arg0.clipFinished( f34_arg0.FrameSelected )
			f34_arg0.TiledBacking:completeAnimation()
			f34_arg0.TiledBacking:setAlpha( 0.5 )
			f34_arg0.clipFinished( f34_arg0.TiledBacking )
			f34_arg0.TiledGrid:completeAnimation()
			f34_arg0.TiledGrid:setAlpha( 0 )
			f34_arg0.clipFinished( f34_arg0.TiledGrid )
			f34_arg0.ItemFrame:completeAnimation()
			f34_arg0.ItemFrame:setAlpha( 1 )
			f34_arg0.clipFinished( f34_arg0.ItemFrame )
			f34_arg0.ItemFrameAdd:completeAnimation()
			f34_arg0.ItemFrameAdd:setAlpha( 1 )
			f34_arg0.clipFinished( f34_arg0.ItemFrameAdd )
			f34_arg0.LockedIcon:completeAnimation()
			f34_arg0.LockedIcon:setAlpha( 0 )
			f34_arg0.clipFinished( f34_arg0.LockedIcon )
			f34_arg0.FrameSelectedInnerGlow:completeAnimation()
			f34_arg0.FrameSelectedInnerGlow:setAlpha( 0.05 )
			f34_arg0.clipFinished( f34_arg0.FrameSelectedInnerGlow )
			f34_arg0.FrameSelectedCorner:completeAnimation()
			f34_arg0.FrameSelectedCorner:setAlpha( 1 )
			f34_arg0.FrameSelectedCorner:setScale( 1, 1 )
			f34_arg0.clipFinished( f34_arg0.FrameSelectedCorner )
		end
	}
}
CoD.MOTD_BannerImageInternal.__onClose = function ( f35_arg0 )
	f35_arg0.MOTDBannerRender:close()
	f35_arg0.MOTDBannerImageText:close()
end

