require( "ui/uieditor/widgets/craft/emblemeditor/emblemlayer" )
require( "ui/uieditor/widgets/craft/emblemeditor/emblemlayerarrows" )
require( "ui/uieditor/widgets/craft/emblemeditor/emblemlayerpositionwidget" )

CoD.EmblemLayerContainer = InheritFrom( LUI.UIElement )
CoD.EmblemLayerContainer.__defaultWidth = 172
CoD.EmblemLayerContainer.__defaultHeight = 172
CoD.EmblemLayerContainer.new = function ( f1_arg0, f1_arg1, f1_arg2, f1_arg3, f1_arg4, f1_arg5, f1_arg6, f1_arg7, f1_arg8, f1_arg9 )
	local self = LUI.UIElement.new( f1_arg2, f1_arg3, f1_arg4, f1_arg5, f1_arg6, f1_arg7, f1_arg8, f1_arg9 )
	self:setClass( CoD.EmblemLayerContainer )
	self.id = "EmblemLayerContainer"
	self.soundSet = "default"
	self.anyChildUsesUpdateState = true
	f1_arg0:addElementToPendingUpdateStateList( self )
	
	local Backing = LUI.UIImage.new( 0, 1, 0, 0, 0, 1, 0, 0 )
	Backing:setAlpha( 0.01 )
	Backing:setScale( 0.8, 0.8 )
	self:addElement( Backing )
	self.Backing = Backing
	
	local NoiseTiledBacking = LUI.UIImage.new( 0, 1, 0, 0, 0, 1, 0, 0 )
	NoiseTiledBacking:setAlpha( 0.4 )
	NoiseTiledBacking:setScale( 0.8, 0.8 )
	NoiseTiledBacking:setImage( RegisterImage( "uie_ui_menu_specialist_hub_repeat_bg" ) )
	NoiseTiledBacking:setMaterial( LUI.UIImage.GetCachedMaterial( 0x6CBE95C250C6D15 ) )
	NoiseTiledBacking:setShaderVector( 0, 0, 0, 0, 0 )
	NoiseTiledBacking:setupNineSliceShader( 196, 88 )
	self:addElement( NoiseTiledBacking )
	self.NoiseTiledBacking = NoiseTiledBacking
	
	local NoiseTiledBackingAdd = LUI.UIImage.new( 0, 1, 0, 0, 0, 1, 0, 0 )
	NoiseTiledBackingAdd:setAlpha( 0.35 )
	NoiseTiledBackingAdd:setScale( 0.8, 0.8 )
	NoiseTiledBackingAdd:setImage( RegisterImage( "uie_ui_menu_specialist_hub_repeat_bg" ) )
	NoiseTiledBackingAdd:setMaterial( LUI.UIImage.GetCachedMaterial( 0x7C9C02F608D0A75 ) )
	NoiseTiledBackingAdd:setShaderVector( 0, 0, 0, 0, 0 )
	NoiseTiledBackingAdd:setupNineSliceShader( 196, 88 )
	self:addElement( NoiseTiledBackingAdd )
	self.NoiseTiledBackingAdd = NoiseTiledBackingAdd
	
	local emblemLayer = CoD.EmblemLayer.new( f1_arg0, f1_arg1, 0, 1, 0, 0, 0, 1, 0, 0 )
	emblemLayer.layerIcon:setAlpha( 0.8 )
	emblemLayer:linkToElementModel( self, nil, false, function ( model )
		emblemLayer:setModel( model, f1_arg1 )
	end )
	self:addElement( emblemLayer )
	self.emblemLayer = emblemLayer
	
	local arrows = CoD.EmblemLayerArrows.new( f1_arg0, f1_arg1, 0, 1, 0, 0, 0, 1, 0, 0 )
	self:addElement( arrows )
	self.arrows = arrows
	
	local FrontendFrameSelected = LUI.UIImage.new( 0, 1, -4, 4, 0, 1, -4, 4 )
	FrontendFrameSelected:setAlpha( 0 )
	FrontendFrameSelected:setScale( 0.8, 0.8 )
	FrontendFrameSelected:setImage( RegisterImage( "uie_ui_menu_store_focus_frame" ) )
	FrontendFrameSelected:setMaterial( LUI.UIImage.GetCachedMaterial( "uie_nineslice_add" ) )
	FrontendFrameSelected:setShaderVector( 0, 0, 0, 0, 0 )
	FrontendFrameSelected:setupNineSliceShader( 12, 12 )
	self:addElement( FrontendFrameSelected )
	self.FrontendFrameSelected = FrontendFrameSelected
	
	local FrontendFrameSelectedGlow = LUI.UIImage.new( 0, 1, -8, 8, 0, 1, -8, 8 )
	FrontendFrameSelectedGlow:setAlpha( 0 )
	FrontendFrameSelectedGlow:setScale( 0.8, 0.8 )
	FrontendFrameSelectedGlow:setImage( RegisterImage( "uie_ui_menu_store_focus_frame" ) )
	FrontendFrameSelectedGlow:setMaterial( LUI.UIImage.GetCachedMaterial( "uie_nineslice_add" ) )
	FrontendFrameSelectedGlow:setShaderVector( 0, 0, 0, 0, 0 )
	FrontendFrameSelectedGlow:setupNineSliceShader( 28, 28 )
	self:addElement( FrontendFrameSelectedGlow )
	self.FrontendFrameSelectedGlow = FrontendFrameSelectedGlow
	
	local FrontendFocusPip = LUI.UIImage.new( 0, 1, -6, 6, 0, 1, -6, 6 )
	FrontendFocusPip:setAlpha( 0 )
	FrontendFocusPip:setScale( 1.06, 1.06 )
	FrontendFocusPip:setImage( RegisterImage( 0x793C73633F620BB ) )
	FrontendFocusPip:setMaterial( LUI.UIImage.GetCachedMaterial( "uie_nineslice_add" ) )
	FrontendFocusPip:setShaderVector( 0, 0, 0, 0, 0 )
	FrontendFocusPip:setupNineSliceShader( 40, 40 )
	self:addElement( FrontendFocusPip )
	self.FrontendFocusPip = FrontendFocusPip
	
	local FrontendFrame = LUI.UIImage.new( 0, 1, -1, 1, 0, 1, -1, 1 )
	FrontendFrame:setAlpha( 0.2 )
	FrontendFrame:setScale( 0.8, 0.8 )
	FrontendFrame:setImage( RegisterImage( "uie_ui_menu_store_common_frame" ) )
	FrontendFrame:setMaterial( LUI.UIImage.GetCachedMaterial( "uie_nineslice_add" ) )
	FrontendFrame:setShaderVector( 0, 0, 0, 0, 0 )
	FrontendFrame:setupNineSliceShader( 12, 12 )
	self:addElement( FrontendFrame )
	self.FrontendFrame = FrontendFrame
	
	local EmblemLayerPositionWidget = CoD.EmblemLayerPositionWidget.new( f1_arg0, f1_arg1, 0, 0, 0, 173, 0, 0, 166, 256 )
	EmblemLayerPositionWidget:mergeStateConditions( {
		{
			stateName = "LowerText",
			condition = function ( menu, element, event )
				local f3_local0
				if not IsMouseOrKeyboard( f1_arg1 ) then
					f3_local0 = CoD.CraftUtility.IsOverLayer( self, f1_arg1, self )
				else
					f3_local0 = false
				end
				return f3_local0
			end
		}
	} )
	EmblemLayerPositionWidget:appendEventHandler( "input_source_changed", function ( f4_arg0, f4_arg1 )
		f4_arg1.menu = f4_arg1.menu or f1_arg0
		f1_arg0:updateElementState( EmblemLayerPositionWidget, f4_arg1 )
	end )
	local f1_local11 = EmblemLayerPositionWidget
	local f1_local12 = EmblemLayerPositionWidget.subscribeToModel
	local f1_local13 = Engine.GetModelForController( f1_arg1 )
	f1_local12( f1_local11, f1_local13.LastInput, function ( f5_arg0 )
		f1_arg0:updateElementState( EmblemLayerPositionWidget, {
			name = "model_validation",
			menu = f1_arg0,
			controller = f1_arg1,
			modelValue = f5_arg0:get(),
			modelName = "LastInput"
		} )
	end, false )
	f1_local11 = EmblemLayerPositionWidget
	f1_local12 = EmblemLayerPositionWidget.subscribeToModel
	f1_local13 = DataSources.EmblemProperties.getModel( f1_arg1 )
	f1_local12( f1_local11, f1_local13.selectedLayerIndex, function ( f6_arg0 )
		f1_arg0:updateElementState( EmblemLayerPositionWidget, {
			name = "model_validation",
			menu = f1_arg0,
			controller = f1_arg1,
			modelValue = f6_arg0:get(),
			modelName = "selectedLayerIndex"
		} )
	end, false )
	EmblemLayerPositionWidget:linkToElementModel( self, nil, false, function ( model )
		EmblemLayerPositionWidget:setModel( model, f1_arg1 )
	end )
	self:addElement( EmblemLayerPositionWidget )
	self.EmblemLayerPositionWidget = EmblemLayerPositionWidget
	
	LUI.OverrideFunction_CallOriginalSecond( self, "close", self.__onClose )
	
	if PostLoadFunc then
		PostLoadFunc( self, f1_arg1, f1_arg0 )
	end
	
	return self
end

CoD.EmblemLayerContainer.__resetProperties = function ( f8_arg0 )
	f8_arg0.emblemLayer:completeAnimation()
	f8_arg0.FrontendFrame:completeAnimation()
	f8_arg0.FrontendFocusPip:completeAnimation()
	f8_arg0.FrontendFrameSelectedGlow:completeAnimation()
	f8_arg0.FrontendFrameSelected:completeAnimation()
	f8_arg0.NoiseTiledBackingAdd:completeAnimation()
	f8_arg0.NoiseTiledBacking:completeAnimation()
	f8_arg0.Backing:completeAnimation()
	f8_arg0.arrows:completeAnimation()
	f8_arg0.EmblemLayerPositionWidget:completeAnimation()
	f8_arg0.emblemLayer:setAlpha( 1 )
	f8_arg0.emblemLayer:setScale( 1, 1 )
	f8_arg0.emblemLayer.layerIcon:setAlpha( 0.8 )
	f8_arg0.FrontendFrame:setAlpha( 0.2 )
	f8_arg0.FrontendFrame:setScale( 0.8, 0.8 )
	f8_arg0.FrontendFocusPip:setAlpha( 0 )
	f8_arg0.FrontendFocusPip:setScale( 1.06, 1.06 )
	f8_arg0.FrontendFrameSelectedGlow:setAlpha( 0 )
	f8_arg0.FrontendFrameSelectedGlow:setScale( 0.8, 0.8 )
	f8_arg0.FrontendFrameSelected:setAlpha( 0 )
	f8_arg0.FrontendFrameSelected:setScale( 0.8, 0.8 )
	f8_arg0.NoiseTiledBackingAdd:setAlpha( 0.35 )
	f8_arg0.NoiseTiledBackingAdd:setScale( 0.8, 0.8 )
	f8_arg0.NoiseTiledBacking:setAlpha( 0.4 )
	f8_arg0.NoiseTiledBacking:setScale( 0.8, 0.8 )
	f8_arg0.Backing:setAlpha( 0.01 )
	f8_arg0.Backing:setScale( 0.8, 0.8 )
	f8_arg0.arrows:setAlpha( 1 )
	f8_arg0.arrows:setZoom( 0 )
	f8_arg0.EmblemLayerPositionWidget:setLeftRight( 0, 0, 0, 173 )
	f8_arg0.EmblemLayerPositionWidget:setTopBottom( 0, 0, 166, 256 )
	f8_arg0.EmblemLayerPositionWidget:setAlpha( 1 )
end

CoD.EmblemLayerContainer.__clipsPerState = {
	DefaultState = {
		DefaultClip = function ( f9_arg0, f9_arg1 )
			f9_arg0:__resetProperties()
			f9_arg0:setupElementClipCounter( 1 )
			f9_arg0.emblemLayer:completeAnimation()
			f9_arg0.emblemLayer:setScale( 0.8, 0.8 )
			f9_arg0.clipFinished( f9_arg0.emblemLayer )
		end,
		Focus = function ( f10_arg0, f10_arg1 )
			f10_arg0:__resetProperties()
			f10_arg0:setupElementClipCounter( 8 )
			f10_arg0.Backing:completeAnimation()
			f10_arg0.Backing:setAlpha( 0.02 )
			f10_arg0.Backing:setScale( 1, 1 )
			f10_arg0.clipFinished( f10_arg0.Backing )
			f10_arg0.NoiseTiledBacking:completeAnimation()
			f10_arg0.NoiseTiledBacking:setScale( 1, 1 )
			f10_arg0.clipFinished( f10_arg0.NoiseTiledBacking )
			f10_arg0.NoiseTiledBackingAdd:completeAnimation()
			f10_arg0.NoiseTiledBackingAdd:setAlpha( 0.65 )
			f10_arg0.NoiseTiledBackingAdd:setScale( 1, 1 )
			f10_arg0.clipFinished( f10_arg0.NoiseTiledBackingAdd )
			f10_arg0.emblemLayer:completeAnimation()
			f10_arg0.emblemLayer.layerIcon:completeAnimation()
			f10_arg0.emblemLayer.layerIcon:setAlpha( 1 )
			f10_arg0.clipFinished( f10_arg0.emblemLayer )
			f10_arg0.FrontendFrameSelected:completeAnimation()
			f10_arg0.FrontendFrameSelected:setAlpha( 1 )
			f10_arg0.FrontendFrameSelected:setScale( 1, 1 )
			f10_arg0.clipFinished( f10_arg0.FrontendFrameSelected )
			f10_arg0.FrontendFrameSelectedGlow:completeAnimation()
			f10_arg0.FrontendFrameSelectedGlow:setAlpha( 0.05 )
			f10_arg0.FrontendFrameSelectedGlow:setScale( 1, 1 )
			f10_arg0.clipFinished( f10_arg0.FrontendFrameSelectedGlow )
			f10_arg0.FrontendFocusPip:completeAnimation()
			f10_arg0.FrontendFocusPip:setAlpha( 0.3 )
			f10_arg0.FrontendFocusPip:setScale( 1, 1 )
			f10_arg0.clipFinished( f10_arg0.FrontendFocusPip )
			f10_arg0.FrontendFrame:completeAnimation()
			f10_arg0.FrontendFrame:setScale( 1, 1 )
			f10_arg0.clipFinished( f10_arg0.FrontendFrame )
		end,
		GainFocus = function ( f11_arg0, f11_arg1 )
			f11_arg0:__resetProperties()
			f11_arg0:setupElementClipCounter( 8 )
			local f11_local0 = function ( f12_arg0 )
				f11_arg0.Backing:beginAnimation( 150 )
				f11_arg0.Backing:setAlpha( 0.02 )
				f11_arg0.Backing:setScale( 1, 1 )
				f11_arg0.Backing:registerEventHandler( "interrupted_keyframe", f11_arg0.clipInterrupted )
				f11_arg0.Backing:registerEventHandler( "transition_complete_keyframe", f11_arg0.clipFinished )
			end
			
			f11_arg0.Backing:completeAnimation()
			f11_arg0.Backing:setAlpha( 0.01 )
			f11_arg0.Backing:setScale( 0.8, 0.8 )
			f11_local0( f11_arg0.Backing )
			local f11_local1 = function ( f13_arg0 )
				f11_arg0.NoiseTiledBacking:beginAnimation( 150 )
				f11_arg0.NoiseTiledBacking:setScale( 1, 1 )
				f11_arg0.NoiseTiledBacking:registerEventHandler( "interrupted_keyframe", f11_arg0.clipInterrupted )
				f11_arg0.NoiseTiledBacking:registerEventHandler( "transition_complete_keyframe", f11_arg0.clipFinished )
			end
			
			f11_arg0.NoiseTiledBacking:completeAnimation()
			f11_arg0.NoiseTiledBacking:setScale( 0.8, 0.8 )
			f11_local1( f11_arg0.NoiseTiledBacking )
			local f11_local2 = function ( f14_arg0 )
				f11_arg0.NoiseTiledBackingAdd:beginAnimation( 150 )
				f11_arg0.NoiseTiledBackingAdd:setAlpha( 0.65 )
				f11_arg0.NoiseTiledBackingAdd:setScale( 1, 1 )
				f11_arg0.NoiseTiledBackingAdd:registerEventHandler( "interrupted_keyframe", f11_arg0.clipInterrupted )
				f11_arg0.NoiseTiledBackingAdd:registerEventHandler( "transition_complete_keyframe", f11_arg0.clipFinished )
			end
			
			f11_arg0.NoiseTiledBackingAdd:completeAnimation()
			f11_arg0.NoiseTiledBackingAdd:setAlpha( 0.35 )
			f11_arg0.NoiseTiledBackingAdd:setScale( 0.8, 0.8 )
			f11_local2( f11_arg0.NoiseTiledBackingAdd )
			local f11_local3 = function ( f15_arg0 )
				f11_arg0.emblemLayer:beginAnimation( 150 )
				f11_arg0.emblemLayer.layerIcon:beginAnimation( 150 )
				f11_arg0.emblemLayer:setScale( 1, 1 )
				f11_arg0.emblemLayer.layerIcon:setAlpha( 1 )
				f11_arg0.emblemLayer:registerEventHandler( "interrupted_keyframe", f11_arg0.clipInterrupted )
				f11_arg0.emblemLayer:registerEventHandler( "transition_complete_keyframe", f11_arg0.clipFinished )
			end
			
			f11_arg0.emblemLayer:completeAnimation()
			f11_arg0.emblemLayer.layerIcon:completeAnimation()
			f11_arg0.emblemLayer:setScale( 0.8, 0.8 )
			f11_arg0.emblemLayer.layerIcon:setAlpha( 0.8 )
			f11_local3( f11_arg0.emblemLayer )
			local f11_local4 = function ( f16_arg0 )
				f11_arg0.FrontendFrameSelected:beginAnimation( 150, Enum[0xF50FFF429AB1890][0x5193EA7825DC097] )
				f11_arg0.FrontendFrameSelected:setAlpha( 1 )
				f11_arg0.FrontendFrameSelected:setScale( 1, 1 )
				f11_arg0.FrontendFrameSelected:registerEventHandler( "interrupted_keyframe", f11_arg0.clipInterrupted )
				f11_arg0.FrontendFrameSelected:registerEventHandler( "transition_complete_keyframe", f11_arg0.clipFinished )
			end
			
			f11_arg0.FrontendFrameSelected:completeAnimation()
			f11_arg0.FrontendFrameSelected:setAlpha( 0 )
			f11_arg0.FrontendFrameSelected:setScale( 0.8, 0.8 )
			f11_local4( f11_arg0.FrontendFrameSelected )
			local f11_local5 = function ( f17_arg0 )
				f11_arg0.FrontendFrameSelectedGlow:beginAnimation( 150 )
				f11_arg0.FrontendFrameSelectedGlow:setAlpha( 0.05 )
				f11_arg0.FrontendFrameSelectedGlow:setScale( 1, 1 )
				f11_arg0.FrontendFrameSelectedGlow:registerEventHandler( "interrupted_keyframe", f11_arg0.clipInterrupted )
				f11_arg0.FrontendFrameSelectedGlow:registerEventHandler( "transition_complete_keyframe", f11_arg0.clipFinished )
			end
			
			f11_arg0.FrontendFrameSelectedGlow:completeAnimation()
			f11_arg0.FrontendFrameSelectedGlow:setAlpha( 0 )
			f11_arg0.FrontendFrameSelectedGlow:setScale( 0.8, 0.8 )
			f11_local5( f11_arg0.FrontendFrameSelectedGlow )
			local f11_local6 = function ( f18_arg0 )
				f11_arg0.FrontendFocusPip:beginAnimation( 150, Enum[0xF50FFF429AB1890][0x53CEB9A0427197] )
				f11_arg0.FrontendFocusPip:setAlpha( 0.3 )
				f11_arg0.FrontendFocusPip:setScale( 1, 1 )
				f11_arg0.FrontendFocusPip:registerEventHandler( "interrupted_keyframe", f11_arg0.clipInterrupted )
				f11_arg0.FrontendFocusPip:registerEventHandler( "transition_complete_keyframe", f11_arg0.clipFinished )
			end
			
			f11_arg0.FrontendFocusPip:completeAnimation()
			f11_arg0.FrontendFocusPip:setAlpha( 0 )
			f11_arg0.FrontendFocusPip:setScale( 1.06, 1.06 )
			f11_local6( f11_arg0.FrontendFocusPip )
			local f11_local7 = function ( f19_arg0 )
				f11_arg0.FrontendFrame:beginAnimation( 150 )
				f11_arg0.FrontendFrame:setScale( 1, 1 )
				f11_arg0.FrontendFrame:registerEventHandler( "interrupted_keyframe", f11_arg0.clipInterrupted )
				f11_arg0.FrontendFrame:registerEventHandler( "transition_complete_keyframe", f11_arg0.clipFinished )
			end
			
			f11_arg0.FrontendFrame:completeAnimation()
			f11_arg0.FrontendFrame:setScale( 0.8, 0.8 )
			f11_local7( f11_arg0.FrontendFrame )
		end,
		LoseFocus = function ( f20_arg0, f20_arg1 )
			f20_arg0:__resetProperties()
			f20_arg0:setupElementClipCounter( 8 )
			local f20_local0 = function ( f21_arg0 )
				f20_arg0.Backing:beginAnimation( 150 )
				f20_arg0.Backing:setAlpha( 0.01 )
				f20_arg0.Backing:setScale( 0.8, 0.8 )
				f20_arg0.Backing:registerEventHandler( "interrupted_keyframe", f20_arg0.clipInterrupted )
				f20_arg0.Backing:registerEventHandler( "transition_complete_keyframe", f20_arg0.clipFinished )
			end
			
			f20_arg0.Backing:completeAnimation()
			f20_arg0.Backing:setAlpha( 0.02 )
			f20_arg0.Backing:setScale( 1, 1 )
			f20_local0( f20_arg0.Backing )
			local f20_local1 = function ( f22_arg0 )
				f20_arg0.NoiseTiledBacking:beginAnimation( 150 )
				f20_arg0.NoiseTiledBacking:setScale( 0.8, 0.8 )
				f20_arg0.NoiseTiledBacking:registerEventHandler( "interrupted_keyframe", f20_arg0.clipInterrupted )
				f20_arg0.NoiseTiledBacking:registerEventHandler( "transition_complete_keyframe", f20_arg0.clipFinished )
			end
			
			f20_arg0.NoiseTiledBacking:completeAnimation()
			f20_arg0.NoiseTiledBacking:setScale( 1, 1 )
			f20_local1( f20_arg0.NoiseTiledBacking )
			local f20_local2 = function ( f23_arg0 )
				f20_arg0.NoiseTiledBackingAdd:beginAnimation( 150 )
				f20_arg0.NoiseTiledBackingAdd:setAlpha( 0.35 )
				f20_arg0.NoiseTiledBackingAdd:setScale( 0.8, 0.8 )
				f20_arg0.NoiseTiledBackingAdd:registerEventHandler( "interrupted_keyframe", f20_arg0.clipInterrupted )
				f20_arg0.NoiseTiledBackingAdd:registerEventHandler( "transition_complete_keyframe", f20_arg0.clipFinished )
			end
			
			f20_arg0.NoiseTiledBackingAdd:completeAnimation()
			f20_arg0.NoiseTiledBackingAdd:setAlpha( 0.65 )
			f20_arg0.NoiseTiledBackingAdd:setScale( 1, 1 )
			f20_local2( f20_arg0.NoiseTiledBackingAdd )
			local f20_local3 = function ( f24_arg0 )
				f20_arg0.emblemLayer:beginAnimation( 150 )
				f20_arg0.emblemLayer.layerIcon:beginAnimation( 150 )
				f20_arg0.emblemLayer:setScale( 0.8, 0.8 )
				f20_arg0.emblemLayer.layerIcon:setAlpha( 0.8 )
				f20_arg0.emblemLayer:registerEventHandler( "interrupted_keyframe", f20_arg0.clipInterrupted )
				f20_arg0.emblemLayer:registerEventHandler( "transition_complete_keyframe", f20_arg0.clipFinished )
			end
			
			f20_arg0.emblemLayer:completeAnimation()
			f20_arg0.emblemLayer.layerIcon:completeAnimation()
			f20_arg0.emblemLayer:setScale( 1, 1 )
			f20_arg0.emblemLayer.layerIcon:setAlpha( 1 )
			f20_local3( f20_arg0.emblemLayer )
			local f20_local4 = function ( f25_arg0 )
				f20_arg0.FrontendFrameSelected:beginAnimation( 150, Enum[0xF50FFF429AB1890][0x5193EA7825DC097] )
				f20_arg0.FrontendFrameSelected:setAlpha( 0 )
				f20_arg0.FrontendFrameSelected:setScale( 0.8, 0.8 )
				f20_arg0.FrontendFrameSelected:registerEventHandler( "interrupted_keyframe", f20_arg0.clipInterrupted )
				f20_arg0.FrontendFrameSelected:registerEventHandler( "transition_complete_keyframe", f20_arg0.clipFinished )
			end
			
			f20_arg0.FrontendFrameSelected:completeAnimation()
			f20_arg0.FrontendFrameSelected:setAlpha( 1 )
			f20_arg0.FrontendFrameSelected:setScale( 1, 1 )
			f20_local4( f20_arg0.FrontendFrameSelected )
			local f20_local5 = function ( f26_arg0 )
				f20_arg0.FrontendFrameSelectedGlow:beginAnimation( 150 )
				f20_arg0.FrontendFrameSelectedGlow:setAlpha( 0 )
				f20_arg0.FrontendFrameSelectedGlow:setScale( 0.8, 0.8 )
				f20_arg0.FrontendFrameSelectedGlow:registerEventHandler( "interrupted_keyframe", f20_arg0.clipInterrupted )
				f20_arg0.FrontendFrameSelectedGlow:registerEventHandler( "transition_complete_keyframe", f20_arg0.clipFinished )
			end
			
			f20_arg0.FrontendFrameSelectedGlow:completeAnimation()
			f20_arg0.FrontendFrameSelectedGlow:setAlpha( 0.05 )
			f20_arg0.FrontendFrameSelectedGlow:setScale( 1, 1 )
			f20_local5( f20_arg0.FrontendFrameSelectedGlow )
			local f20_local6 = function ( f27_arg0 )
				f20_arg0.FrontendFocusPip:beginAnimation( 150, Enum[0xF50FFF429AB1890][0x6F6186B702830BC] )
				f20_arg0.FrontendFocusPip:setAlpha( 0 )
				f20_arg0.FrontendFocusPip:setScale( 1.06, 1.06 )
				f20_arg0.FrontendFocusPip:registerEventHandler( "interrupted_keyframe", f20_arg0.clipInterrupted )
				f20_arg0.FrontendFocusPip:registerEventHandler( "transition_complete_keyframe", f20_arg0.clipFinished )
			end
			
			f20_arg0.FrontendFocusPip:completeAnimation()
			f20_arg0.FrontendFocusPip:setAlpha( 0.3 )
			f20_arg0.FrontendFocusPip:setScale( 1, 1 )
			f20_local6( f20_arg0.FrontendFocusPip )
			local f20_local7 = function ( f28_arg0 )
				f20_arg0.FrontendFrame:beginAnimation( 150 )
				f20_arg0.FrontendFrame:setScale( 0.8, 0.8 )
				f20_arg0.FrontendFrame:registerEventHandler( "interrupted_keyframe", f20_arg0.clipInterrupted )
				f20_arg0.FrontendFrame:registerEventHandler( "transition_complete_keyframe", f20_arg0.clipFinished )
			end
			
			f20_arg0.FrontendFrame:completeAnimation()
			f20_arg0.FrontendFrame:setScale( 1, 1 )
			f20_local7( f20_arg0.FrontendFrame )
		end,
		Active = function ( f29_arg0, f29_arg1 )
			f29_arg0:__resetProperties()
			f29_arg0:setupElementClipCounter( 8 )
			f29_arg0.Backing:completeAnimation()
			f29_arg0.Backing:setAlpha( 0.02 )
			f29_arg0.Backing:setScale( 1, 1 )
			f29_arg0.clipFinished( f29_arg0.Backing )
			f29_arg0.NoiseTiledBacking:completeAnimation()
			f29_arg0.NoiseTiledBacking:setScale( 1, 1 )
			f29_arg0.clipFinished( f29_arg0.NoiseTiledBacking )
			f29_arg0.NoiseTiledBackingAdd:completeAnimation()
			f29_arg0.NoiseTiledBackingAdd:setAlpha( 0.65 )
			f29_arg0.NoiseTiledBackingAdd:setScale( 1, 1 )
			f29_arg0.clipFinished( f29_arg0.NoiseTiledBackingAdd )
			f29_arg0.arrows:completeAnimation()
			f29_arg0.arrows:setZoom( 50 )
			f29_arg0.clipFinished( f29_arg0.arrows )
			f29_arg0.FrontendFrameSelected:completeAnimation()
			f29_arg0.FrontendFrameSelected:setAlpha( 1 )
			f29_arg0.FrontendFrameSelected:setScale( 1, 1 )
			f29_arg0.clipFinished( f29_arg0.FrontendFrameSelected )
			f29_arg0.FrontendFrameSelectedGlow:completeAnimation()
			f29_arg0.FrontendFrameSelectedGlow:setAlpha( 0.05 )
			f29_arg0.FrontendFrameSelectedGlow:setScale( 1, 1 )
			f29_arg0.clipFinished( f29_arg0.FrontendFrameSelectedGlow )
			f29_arg0.FrontendFocusPip:completeAnimation()
			f29_arg0.FrontendFocusPip:setAlpha( 0.3 )
			f29_arg0.FrontendFocusPip:setScale( 1, 1 )
			f29_arg0.clipFinished( f29_arg0.FrontendFocusPip )
			f29_arg0.FrontendFrame:completeAnimation()
			f29_arg0.FrontendFrame:setScale( 1, 1 )
			f29_arg0.clipFinished( f29_arg0.FrontendFrame )
		end,
		GainActive = function ( f30_arg0, f30_arg1 )
			f30_arg0:__resetProperties()
			f30_arg0:setupElementClipCounter( 9 )
			local f30_local0 = function ( f31_arg0 )
				f30_arg0.Backing:beginAnimation( 150 )
				f30_arg0.Backing:setAlpha( 0.02 )
				f30_arg0.Backing:setScale( 1, 1 )
				f30_arg0.Backing:registerEventHandler( "interrupted_keyframe", f30_arg0.clipInterrupted )
				f30_arg0.Backing:registerEventHandler( "transition_complete_keyframe", f30_arg0.clipFinished )
			end
			
			f30_arg0.Backing:completeAnimation()
			f30_arg0.Backing:setAlpha( 0.01 )
			f30_arg0.Backing:setScale( 0.8, 0.8 )
			f30_local0( f30_arg0.Backing )
			local f30_local1 = function ( f32_arg0 )
				f30_arg0.NoiseTiledBacking:beginAnimation( 150 )
				f30_arg0.NoiseTiledBacking:setScale( 1, 1 )
				f30_arg0.NoiseTiledBacking:registerEventHandler( "interrupted_keyframe", f30_arg0.clipInterrupted )
				f30_arg0.NoiseTiledBacking:registerEventHandler( "transition_complete_keyframe", f30_arg0.clipFinished )
			end
			
			f30_arg0.NoiseTiledBacking:completeAnimation()
			f30_arg0.NoiseTiledBacking:setScale( 0.8, 0.8 )
			f30_local1( f30_arg0.NoiseTiledBacking )
			local f30_local2 = function ( f33_arg0 )
				f30_arg0.NoiseTiledBackingAdd:beginAnimation( 150 )
				f30_arg0.NoiseTiledBackingAdd:setAlpha( 0.65 )
				f30_arg0.NoiseTiledBackingAdd:setScale( 1, 1 )
				f30_arg0.NoiseTiledBackingAdd:registerEventHandler( "interrupted_keyframe", f30_arg0.clipInterrupted )
				f30_arg0.NoiseTiledBackingAdd:registerEventHandler( "transition_complete_keyframe", f30_arg0.clipFinished )
			end
			
			f30_arg0.NoiseTiledBackingAdd:completeAnimation()
			f30_arg0.NoiseTiledBackingAdd:setAlpha( 0.35 )
			f30_arg0.NoiseTiledBackingAdd:setScale( 0.8, 0.8 )
			f30_local2( f30_arg0.NoiseTiledBackingAdd )
			local f30_local3 = function ( f34_arg0 )
				f30_arg0.emblemLayer:beginAnimation( 150 )
				f30_arg0.emblemLayer:setScale( 1, 1 )
				f30_arg0.emblemLayer:registerEventHandler( "interrupted_keyframe", f30_arg0.clipInterrupted )
				f30_arg0.emblemLayer:registerEventHandler( "transition_complete_keyframe", f30_arg0.clipFinished )
			end
			
			f30_arg0.emblemLayer:completeAnimation()
			f30_arg0.emblemLayer:setScale( 0.8, 0.8 )
			f30_local3( f30_arg0.emblemLayer )
			local f30_local4 = function ( f35_arg0 )
				f30_arg0.arrows:beginAnimation( 150 )
				f30_arg0.arrows:setZoom( 50 )
				f30_arg0.arrows:registerEventHandler( "interrupted_keyframe", f30_arg0.clipInterrupted )
				f30_arg0.arrows:registerEventHandler( "transition_complete_keyframe", f30_arg0.clipFinished )
			end
			
			f30_arg0.arrows:completeAnimation()
			f30_arg0.arrows:setZoom( 0 )
			f30_local4( f30_arg0.arrows )
			local f30_local5 = function ( f36_arg0 )
				f30_arg0.FrontendFrameSelected:beginAnimation( 150 )
				f30_arg0.FrontendFrameSelected:setAlpha( 1 )
				f30_arg0.FrontendFrameSelected:setScale( 1, 1 )
				f30_arg0.FrontendFrameSelected:registerEventHandler( "interrupted_keyframe", f30_arg0.clipInterrupted )
				f30_arg0.FrontendFrameSelected:registerEventHandler( "transition_complete_keyframe", f30_arg0.clipFinished )
			end
			
			f30_arg0.FrontendFrameSelected:completeAnimation()
			f30_arg0.FrontendFrameSelected:setAlpha( 0 )
			f30_arg0.FrontendFrameSelected:setScale( 0.8, 0.8 )
			f30_local5( f30_arg0.FrontendFrameSelected )
			local f30_local6 = function ( f37_arg0 )
				f30_arg0.FrontendFrameSelectedGlow:beginAnimation( 150 )
				f30_arg0.FrontendFrameSelectedGlow:setAlpha( 0.05 )
				f30_arg0.FrontendFrameSelectedGlow:setScale( 1, 1 )
				f30_arg0.FrontendFrameSelectedGlow:registerEventHandler( "interrupted_keyframe", f30_arg0.clipInterrupted )
				f30_arg0.FrontendFrameSelectedGlow:registerEventHandler( "transition_complete_keyframe", f30_arg0.clipFinished )
			end
			
			f30_arg0.FrontendFrameSelectedGlow:completeAnimation()
			f30_arg0.FrontendFrameSelectedGlow:setAlpha( 0 )
			f30_arg0.FrontendFrameSelectedGlow:setScale( 0.8, 0.8 )
			f30_local6( f30_arg0.FrontendFrameSelectedGlow )
			local f30_local7 = function ( f38_arg0 )
				f30_arg0.FrontendFocusPip:beginAnimation( 150 )
				f30_arg0.FrontendFocusPip:setAlpha( 0.3 )
				f30_arg0.FrontendFocusPip:setScale( 1, 1 )
				f30_arg0.FrontendFocusPip:registerEventHandler( "interrupted_keyframe", f30_arg0.clipInterrupted )
				f30_arg0.FrontendFocusPip:registerEventHandler( "transition_complete_keyframe", f30_arg0.clipFinished )
			end
			
			f30_arg0.FrontendFocusPip:completeAnimation()
			f30_arg0.FrontendFocusPip:setAlpha( 0 )
			f30_arg0.FrontendFocusPip:setScale( 1.06, 1.06 )
			f30_local7( f30_arg0.FrontendFocusPip )
			local f30_local8 = function ( f39_arg0 )
				f30_arg0.FrontendFrame:beginAnimation( 150 )
				f30_arg0.FrontendFrame:setScale( 1, 1 )
				f30_arg0.FrontendFrame:registerEventHandler( "interrupted_keyframe", f30_arg0.clipInterrupted )
				f30_arg0.FrontendFrame:registerEventHandler( "transition_complete_keyframe", f30_arg0.clipFinished )
			end
			
			f30_arg0.FrontendFrame:completeAnimation()
			f30_arg0.FrontendFrame:setScale( 0.8, 0.8 )
			f30_local8( f30_arg0.FrontendFrame )
		end,
		LoseActive = function ( f40_arg0, f40_arg1 )
			f40_arg0:__resetProperties()
			f40_arg0:setupElementClipCounter( 9 )
			local f40_local0 = function ( f41_arg0 )
				f40_arg0.Backing:beginAnimation( 150 )
				f40_arg0.Backing:setAlpha( 0.01 )
				f40_arg0.Backing:setScale( 0.8, 0.8 )
				f40_arg0.Backing:registerEventHandler( "interrupted_keyframe", f40_arg0.clipInterrupted )
				f40_arg0.Backing:registerEventHandler( "transition_complete_keyframe", f40_arg0.clipFinished )
			end
			
			f40_arg0.Backing:completeAnimation()
			f40_arg0.Backing:setAlpha( 0.02 )
			f40_arg0.Backing:setScale( 1, 1 )
			f40_local0( f40_arg0.Backing )
			local f40_local1 = function ( f42_arg0 )
				f40_arg0.NoiseTiledBacking:beginAnimation( 150 )
				f40_arg0.NoiseTiledBacking:setScale( 0.8, 0.8 )
				f40_arg0.NoiseTiledBacking:registerEventHandler( "interrupted_keyframe", f40_arg0.clipInterrupted )
				f40_arg0.NoiseTiledBacking:registerEventHandler( "transition_complete_keyframe", f40_arg0.clipFinished )
			end
			
			f40_arg0.NoiseTiledBacking:completeAnimation()
			f40_arg0.NoiseTiledBacking:setScale( 1, 1 )
			f40_local1( f40_arg0.NoiseTiledBacking )
			local f40_local2 = function ( f43_arg0 )
				f40_arg0.NoiseTiledBackingAdd:beginAnimation( 150 )
				f40_arg0.NoiseTiledBackingAdd:setAlpha( 0.35 )
				f40_arg0.NoiseTiledBackingAdd:setScale( 0.8, 0.8 )
				f40_arg0.NoiseTiledBackingAdd:registerEventHandler( "interrupted_keyframe", f40_arg0.clipInterrupted )
				f40_arg0.NoiseTiledBackingAdd:registerEventHandler( "transition_complete_keyframe", f40_arg0.clipFinished )
			end
			
			f40_arg0.NoiseTiledBackingAdd:completeAnimation()
			f40_arg0.NoiseTiledBackingAdd:setAlpha( 0.65 )
			f40_arg0.NoiseTiledBackingAdd:setScale( 1, 1 )
			f40_local2( f40_arg0.NoiseTiledBackingAdd )
			local f40_local3 = function ( f44_arg0 )
				f40_arg0.emblemLayer:beginAnimation( 150 )
				f40_arg0.emblemLayer:setScale( 0.8, 0.8 )
				f40_arg0.emblemLayer:registerEventHandler( "interrupted_keyframe", f40_arg0.clipInterrupted )
				f40_arg0.emblemLayer:registerEventHandler( "transition_complete_keyframe", f40_arg0.clipFinished )
			end
			
			f40_arg0.emblemLayer:completeAnimation()
			f40_arg0.emblemLayer:setScale( 1, 1 )
			f40_local3( f40_arg0.emblemLayer )
			local f40_local4 = function ( f45_arg0 )
				f40_arg0.arrows:beginAnimation( 150 )
				f40_arg0.arrows:setZoom( 0 )
				f40_arg0.arrows:registerEventHandler( "interrupted_keyframe", f40_arg0.clipInterrupted )
				f40_arg0.arrows:registerEventHandler( "transition_complete_keyframe", f40_arg0.clipFinished )
			end
			
			f40_arg0.arrows:completeAnimation()
			f40_arg0.arrows:setZoom( 50 )
			f40_local4( f40_arg0.arrows )
			local f40_local5 = function ( f46_arg0 )
				f40_arg0.FrontendFrameSelected:beginAnimation( 150 )
				f40_arg0.FrontendFrameSelected:setAlpha( 0 )
				f40_arg0.FrontendFrameSelected:setScale( 0.8, 0.8 )
				f40_arg0.FrontendFrameSelected:registerEventHandler( "interrupted_keyframe", f40_arg0.clipInterrupted )
				f40_arg0.FrontendFrameSelected:registerEventHandler( "transition_complete_keyframe", f40_arg0.clipFinished )
			end
			
			f40_arg0.FrontendFrameSelected:completeAnimation()
			f40_arg0.FrontendFrameSelected:setAlpha( 1 )
			f40_arg0.FrontendFrameSelected:setScale( 1, 1 )
			f40_local5( f40_arg0.FrontendFrameSelected )
			local f40_local6 = function ( f47_arg0 )
				f40_arg0.FrontendFrameSelectedGlow:beginAnimation( 150 )
				f40_arg0.FrontendFrameSelectedGlow:setAlpha( 0 )
				f40_arg0.FrontendFrameSelectedGlow:setScale( 0.8, 0.8 )
				f40_arg0.FrontendFrameSelectedGlow:registerEventHandler( "interrupted_keyframe", f40_arg0.clipInterrupted )
				f40_arg0.FrontendFrameSelectedGlow:registerEventHandler( "transition_complete_keyframe", f40_arg0.clipFinished )
			end
			
			f40_arg0.FrontendFrameSelectedGlow:completeAnimation()
			f40_arg0.FrontendFrameSelectedGlow:setAlpha( 0.05 )
			f40_arg0.FrontendFrameSelectedGlow:setScale( 1, 1 )
			f40_local6( f40_arg0.FrontendFrameSelectedGlow )
			local f40_local7 = function ( f48_arg0 )
				f40_arg0.FrontendFocusPip:beginAnimation( 150 )
				f40_arg0.FrontendFocusPip:setAlpha( 0 )
				f40_arg0.FrontendFocusPip:setScale( 1.06, 1.06 )
				f40_arg0.FrontendFocusPip:registerEventHandler( "interrupted_keyframe", f40_arg0.clipInterrupted )
				f40_arg0.FrontendFocusPip:registerEventHandler( "transition_complete_keyframe", f40_arg0.clipFinished )
			end
			
			f40_arg0.FrontendFocusPip:completeAnimation()
			f40_arg0.FrontendFocusPip:setAlpha( 0.3 )
			f40_arg0.FrontendFocusPip:setScale( 1, 1 )
			f40_local7( f40_arg0.FrontendFocusPip )
			local f40_local8 = function ( f49_arg0 )
				f40_arg0.FrontendFrame:beginAnimation( 150 )
				f40_arg0.FrontendFrame:setScale( 0.8, 0.8 )
				f40_arg0.FrontendFrame:registerEventHandler( "interrupted_keyframe", f40_arg0.clipInterrupted )
				f40_arg0.FrontendFrame:registerEventHandler( "transition_complete_keyframe", f40_arg0.clipFinished )
			end
			
			f40_arg0.FrontendFrame:completeAnimation()
			f40_arg0.FrontendFrame:setScale( 1, 1 )
			f40_local8( f40_arg0.FrontendFrame )
		end
	},
	EditMode_Selected = {
		DefaultClip = function ( f50_arg0, f50_arg1 )
			f50_arg0:__resetProperties()
			f50_arg0:setupElementClipCounter( 2 )
			f50_arg0.NoiseTiledBackingAdd:completeAnimation()
			f50_arg0.NoiseTiledBackingAdd:setAlpha( 0.9 )
			f50_arg0.clipFinished( f50_arg0.NoiseTiledBackingAdd )
			f50_arg0.emblemLayer:completeAnimation()
			f50_arg0.emblemLayer.layerIcon:completeAnimation()
			f50_arg0.emblemLayer:setAlpha( 0.5 )
			f50_arg0.emblemLayer:setScale( 0.8, 0.8 )
			f50_arg0.emblemLayer.layerIcon:setAlpha( 1 )
			f50_arg0.clipFinished( f50_arg0.emblemLayer )
		end
	},
	Hidden = {
		DefaultClip = function ( f51_arg0, f51_arg1 )
			f51_arg0:__resetProperties()
			f51_arg0:setupElementClipCounter( 10 )
			f51_arg0.Backing:completeAnimation()
			f51_arg0.Backing:setAlpha( 0 )
			f51_arg0.clipFinished( f51_arg0.Backing )
			f51_arg0.NoiseTiledBacking:completeAnimation()
			f51_arg0.NoiseTiledBacking:setAlpha( 0 )
			f51_arg0.clipFinished( f51_arg0.NoiseTiledBacking )
			f51_arg0.NoiseTiledBackingAdd:completeAnimation()
			f51_arg0.NoiseTiledBackingAdd:setAlpha( 0 )
			f51_arg0.clipFinished( f51_arg0.NoiseTiledBackingAdd )
			f51_arg0.emblemLayer:completeAnimation()
			f51_arg0.emblemLayer:setAlpha( 0 )
			f51_arg0.clipFinished( f51_arg0.emblemLayer )
			f51_arg0.arrows:completeAnimation()
			f51_arg0.arrows:setAlpha( 0 )
			f51_arg0.clipFinished( f51_arg0.arrows )
			f51_arg0.FrontendFrameSelected:completeAnimation()
			f51_arg0.FrontendFrameSelected:setAlpha( 0 )
			f51_arg0.clipFinished( f51_arg0.FrontendFrameSelected )
			f51_arg0.FrontendFrameSelectedGlow:completeAnimation()
			f51_arg0.FrontendFrameSelectedGlow:setAlpha( 0 )
			f51_arg0.clipFinished( f51_arg0.FrontendFrameSelectedGlow )
			f51_arg0.FrontendFocusPip:completeAnimation()
			f51_arg0.FrontendFocusPip:setAlpha( 0 )
			f51_arg0.clipFinished( f51_arg0.FrontendFocusPip )
			f51_arg0.FrontendFrame:completeAnimation()
			f51_arg0.FrontendFrame:setAlpha( 0 )
			f51_arg0.clipFinished( f51_arg0.FrontendFrame )
			f51_arg0.EmblemLayerPositionWidget:completeAnimation()
			f51_arg0.EmblemLayerPositionWidget:setAlpha( 0 )
			f51_arg0.clipFinished( f51_arg0.EmblemLayerPositionWidget )
		end
	},
	DefaultStateKBM = {
		DefaultClip = function ( f52_arg0, f52_arg1 )
			f52_arg0:__resetProperties()
			f52_arg0:setupElementClipCounter( 2 )
			f52_arg0.emblemLayer:completeAnimation()
			f52_arg0.emblemLayer:setScale( 0.8, 0.8 )
			f52_arg0.clipFinished( f52_arg0.emblemLayer )
			f52_arg0.EmblemLayerPositionWidget:completeAnimation()
			f52_arg0.EmblemLayerPositionWidget:setLeftRight( 0, 0, 18, 155 )
			f52_arg0.EmblemLayerPositionWidget:setTopBottom( 0, 0, 155, 245 )
			f52_arg0.clipFinished( f52_arg0.EmblemLayerPositionWidget )
		end,
		Focus = function ( f53_arg0, f53_arg1 )
			f53_arg0:__resetProperties()
			f53_arg0:setupElementClipCounter( 9 )
			f53_arg0.Backing:completeAnimation()
			f53_arg0.Backing:setAlpha( 0.02 )
			f53_arg0.Backing:setScale( 0.9, 0.9 )
			f53_arg0.clipFinished( f53_arg0.Backing )
			f53_arg0.NoiseTiledBacking:completeAnimation()
			f53_arg0.NoiseTiledBacking:setScale( 0.9, 0.9 )
			f53_arg0.clipFinished( f53_arg0.NoiseTiledBacking )
			f53_arg0.NoiseTiledBackingAdd:completeAnimation()
			f53_arg0.NoiseTiledBackingAdd:setAlpha( 0.65 )
			f53_arg0.NoiseTiledBackingAdd:setScale( 0.9, 0.9 )
			f53_arg0.clipFinished( f53_arg0.NoiseTiledBackingAdd )
			f53_arg0.emblemLayer:completeAnimation()
			f53_arg0.emblemLayer.layerIcon:completeAnimation()
			f53_arg0.emblemLayer:setScale( 0.9, 0.9 )
			f53_arg0.emblemLayer.layerIcon:setAlpha( 1 )
			f53_arg0.clipFinished( f53_arg0.emblemLayer )
			f53_arg0.FrontendFrameSelected:completeAnimation()
			f53_arg0.FrontendFrameSelected:setAlpha( 1 )
			f53_arg0.FrontendFrameSelected:setScale( 0.9, 0.9 )
			f53_arg0.clipFinished( f53_arg0.FrontendFrameSelected )
			f53_arg0.FrontendFrameSelectedGlow:completeAnimation()
			f53_arg0.FrontendFrameSelectedGlow:setAlpha( 0.05 )
			f53_arg0.FrontendFrameSelectedGlow:setScale( 0.9, 0.9 )
			f53_arg0.clipFinished( f53_arg0.FrontendFrameSelectedGlow )
			f53_arg0.FrontendFocusPip:completeAnimation()
			f53_arg0.FrontendFocusPip:setAlpha( 0.3 )
			f53_arg0.FrontendFocusPip:setScale( 0.9, 0.9 )
			f53_arg0.clipFinished( f53_arg0.FrontendFocusPip )
			f53_arg0.FrontendFrame:completeAnimation()
			f53_arg0.FrontendFrame:setScale( 0.9, 0.9 )
			f53_arg0.clipFinished( f53_arg0.FrontendFrame )
			f53_arg0.EmblemLayerPositionWidget:completeAnimation()
			f53_arg0.EmblemLayerPositionWidget:setLeftRight( 0, 0, 10, 164 )
			f53_arg0.EmblemLayerPositionWidget:setTopBottom( 0, 0, 164, 254 )
			f53_arg0.clipFinished( f53_arg0.EmblemLayerPositionWidget )
		end,
		GainFocus = function ( f54_arg0, f54_arg1 )
			f54_arg0:__resetProperties()
			f54_arg0:setupElementClipCounter( 9 )
			local f54_local0 = function ( f55_arg0 )
				f54_arg0.Backing:beginAnimation( 150 )
				f54_arg0.Backing:setAlpha( 0.02 )
				f54_arg0.Backing:setScale( 0.9, 0.9 )
				f54_arg0.Backing:registerEventHandler( "interrupted_keyframe", f54_arg0.clipInterrupted )
				f54_arg0.Backing:registerEventHandler( "transition_complete_keyframe", f54_arg0.clipFinished )
			end
			
			f54_arg0.Backing:completeAnimation()
			f54_arg0.Backing:setAlpha( 0.01 )
			f54_arg0.Backing:setScale( 0.8, 0.8 )
			f54_local0( f54_arg0.Backing )
			local f54_local1 = function ( f56_arg0 )
				f54_arg0.NoiseTiledBacking:beginAnimation( 150 )
				f54_arg0.NoiseTiledBacking:setScale( 0.9, 0.9 )
				f54_arg0.NoiseTiledBacking:registerEventHandler( "interrupted_keyframe", f54_arg0.clipInterrupted )
				f54_arg0.NoiseTiledBacking:registerEventHandler( "transition_complete_keyframe", f54_arg0.clipFinished )
			end
			
			f54_arg0.NoiseTiledBacking:completeAnimation()
			f54_arg0.NoiseTiledBacking:setScale( 0.8, 0.8 )
			f54_local1( f54_arg0.NoiseTiledBacking )
			local f54_local2 = function ( f57_arg0 )
				f54_arg0.NoiseTiledBackingAdd:beginAnimation( 150 )
				f54_arg0.NoiseTiledBackingAdd:setAlpha( 0.65 )
				f54_arg0.NoiseTiledBackingAdd:setScale( 0.9, 0.9 )
				f54_arg0.NoiseTiledBackingAdd:registerEventHandler( "interrupted_keyframe", f54_arg0.clipInterrupted )
				f54_arg0.NoiseTiledBackingAdd:registerEventHandler( "transition_complete_keyframe", f54_arg0.clipFinished )
			end
			
			f54_arg0.NoiseTiledBackingAdd:completeAnimation()
			f54_arg0.NoiseTiledBackingAdd:setAlpha( 0.35 )
			f54_arg0.NoiseTiledBackingAdd:setScale( 0.8, 0.8 )
			f54_local2( f54_arg0.NoiseTiledBackingAdd )
			local f54_local3 = function ( f58_arg0 )
				f54_arg0.emblemLayer:beginAnimation( 150 )
				f54_arg0.emblemLayer.layerIcon:beginAnimation( 150 )
				f54_arg0.emblemLayer:setScale( 0.9, 0.9 )
				f54_arg0.emblemLayer.layerIcon:setAlpha( 1 )
				f54_arg0.emblemLayer:registerEventHandler( "interrupted_keyframe", f54_arg0.clipInterrupted )
				f54_arg0.emblemLayer:registerEventHandler( "transition_complete_keyframe", f54_arg0.clipFinished )
			end
			
			f54_arg0.emblemLayer:completeAnimation()
			f54_arg0.emblemLayer.layerIcon:completeAnimation()
			f54_arg0.emblemLayer:setScale( 0.8, 0.8 )
			f54_arg0.emblemLayer.layerIcon:setAlpha( 0.8 )
			f54_local3( f54_arg0.emblemLayer )
			local f54_local4 = function ( f59_arg0 )
				f54_arg0.FrontendFrameSelected:beginAnimation( 150, Enum[0xF50FFF429AB1890][0x5193EA7825DC097] )
				f54_arg0.FrontendFrameSelected:setAlpha( 1 )
				f54_arg0.FrontendFrameSelected:setScale( 0.9, 0.9 )
				f54_arg0.FrontendFrameSelected:registerEventHandler( "interrupted_keyframe", f54_arg0.clipInterrupted )
				f54_arg0.FrontendFrameSelected:registerEventHandler( "transition_complete_keyframe", f54_arg0.clipFinished )
			end
			
			f54_arg0.FrontendFrameSelected:completeAnimation()
			f54_arg0.FrontendFrameSelected:setAlpha( 0 )
			f54_arg0.FrontendFrameSelected:setScale( 0.8, 0.8 )
			f54_local4( f54_arg0.FrontendFrameSelected )
			local f54_local5 = function ( f60_arg0 )
				f54_arg0.FrontendFrameSelectedGlow:beginAnimation( 150 )
				f54_arg0.FrontendFrameSelectedGlow:setAlpha( 0.05 )
				f54_arg0.FrontendFrameSelectedGlow:setScale( 0.9, 0.9 )
				f54_arg0.FrontendFrameSelectedGlow:registerEventHandler( "interrupted_keyframe", f54_arg0.clipInterrupted )
				f54_arg0.FrontendFrameSelectedGlow:registerEventHandler( "transition_complete_keyframe", f54_arg0.clipFinished )
			end
			
			f54_arg0.FrontendFrameSelectedGlow:completeAnimation()
			f54_arg0.FrontendFrameSelectedGlow:setAlpha( 0 )
			f54_arg0.FrontendFrameSelectedGlow:setScale( 0.8, 0.8 )
			f54_local5( f54_arg0.FrontendFrameSelectedGlow )
			local f54_local6 = function ( f61_arg0 )
				f54_arg0.FrontendFocusPip:beginAnimation( 150, Enum[0xF50FFF429AB1890][0x53CEB9A0427197] )
				f54_arg0.FrontendFocusPip:setAlpha( 0.3 )
				f54_arg0.FrontendFocusPip:setScale( 0.9, 0.9 )
				f54_arg0.FrontendFocusPip:registerEventHandler( "interrupted_keyframe", f54_arg0.clipInterrupted )
				f54_arg0.FrontendFocusPip:registerEventHandler( "transition_complete_keyframe", f54_arg0.clipFinished )
			end
			
			f54_arg0.FrontendFocusPip:completeAnimation()
			f54_arg0.FrontendFocusPip:setAlpha( 0 )
			f54_arg0.FrontendFocusPip:setScale( 1.06, 1.06 )
			f54_local6( f54_arg0.FrontendFocusPip )
			local f54_local7 = function ( f62_arg0 )
				f54_arg0.FrontendFrame:beginAnimation( 150 )
				f54_arg0.FrontendFrame:setScale( 0.9, 0.9 )
				f54_arg0.FrontendFrame:registerEventHandler( "interrupted_keyframe", f54_arg0.clipInterrupted )
				f54_arg0.FrontendFrame:registerEventHandler( "transition_complete_keyframe", f54_arg0.clipFinished )
			end
			
			f54_arg0.FrontendFrame:completeAnimation()
			f54_arg0.FrontendFrame:setScale( 0.8, 0.8 )
			f54_local7( f54_arg0.FrontendFrame )
			local f54_local8 = function ( f63_arg0 )
				f54_arg0.EmblemLayerPositionWidget:beginAnimation( 150 )
				f54_arg0.EmblemLayerPositionWidget:setLeftRight( 0, 0, 10, 164 )
				f54_arg0.EmblemLayerPositionWidget:setTopBottom( 0, 0, 164, 254 )
				f54_arg0.EmblemLayerPositionWidget:registerEventHandler( "interrupted_keyframe", f54_arg0.clipInterrupted )
				f54_arg0.EmblemLayerPositionWidget:registerEventHandler( "transition_complete_keyframe", f54_arg0.clipFinished )
			end
			
			f54_arg0.EmblemLayerPositionWidget:completeAnimation()
			f54_arg0.EmblemLayerPositionWidget:setLeftRight( 0, 0, 18, 155 )
			f54_arg0.EmblemLayerPositionWidget:setTopBottom( 0, 0, 155, 245 )
			f54_local8( f54_arg0.EmblemLayerPositionWidget )
		end,
		LoseFocus = function ( f64_arg0, f64_arg1 )
			f64_arg0:__resetProperties()
			f64_arg0:setupElementClipCounter( 9 )
			local f64_local0 = function ( f65_arg0 )
				f64_arg0.Backing:beginAnimation( 150 )
				f64_arg0.Backing:setAlpha( 0.01 )
				f64_arg0.Backing:setScale( 0.8, 0.8 )
				f64_arg0.Backing:registerEventHandler( "interrupted_keyframe", f64_arg0.clipInterrupted )
				f64_arg0.Backing:registerEventHandler( "transition_complete_keyframe", f64_arg0.clipFinished )
			end
			
			f64_arg0.Backing:completeAnimation()
			f64_arg0.Backing:setAlpha( 0.02 )
			f64_arg0.Backing:setScale( 0.9, 0.9 )
			f64_local0( f64_arg0.Backing )
			local f64_local1 = function ( f66_arg0 )
				f64_arg0.NoiseTiledBacking:beginAnimation( 150 )
				f64_arg0.NoiseTiledBacking:setScale( 0.8, 0.8 )
				f64_arg0.NoiseTiledBacking:registerEventHandler( "interrupted_keyframe", f64_arg0.clipInterrupted )
				f64_arg0.NoiseTiledBacking:registerEventHandler( "transition_complete_keyframe", f64_arg0.clipFinished )
			end
			
			f64_arg0.NoiseTiledBacking:completeAnimation()
			f64_arg0.NoiseTiledBacking:setScale( 0.9, 0.9 )
			f64_local1( f64_arg0.NoiseTiledBacking )
			local f64_local2 = function ( f67_arg0 )
				f64_arg0.NoiseTiledBackingAdd:beginAnimation( 150 )
				f64_arg0.NoiseTiledBackingAdd:setAlpha( 0.35 )
				f64_arg0.NoiseTiledBackingAdd:setScale( 0.8, 0.8 )
				f64_arg0.NoiseTiledBackingAdd:registerEventHandler( "interrupted_keyframe", f64_arg0.clipInterrupted )
				f64_arg0.NoiseTiledBackingAdd:registerEventHandler( "transition_complete_keyframe", f64_arg0.clipFinished )
			end
			
			f64_arg0.NoiseTiledBackingAdd:completeAnimation()
			f64_arg0.NoiseTiledBackingAdd:setAlpha( 0.65 )
			f64_arg0.NoiseTiledBackingAdd:setScale( 0.9, 0.9 )
			f64_local2( f64_arg0.NoiseTiledBackingAdd )
			local f64_local3 = function ( f68_arg0 )
				f64_arg0.emblemLayer:beginAnimation( 150 )
				f64_arg0.emblemLayer.layerIcon:beginAnimation( 150 )
				f64_arg0.emblemLayer:setScale( 0.8, 0.8 )
				f64_arg0.emblemLayer.layerIcon:setAlpha( 0.8 )
				f64_arg0.emblemLayer:registerEventHandler( "interrupted_keyframe", f64_arg0.clipInterrupted )
				f64_arg0.emblemLayer:registerEventHandler( "transition_complete_keyframe", f64_arg0.clipFinished )
			end
			
			f64_arg0.emblemLayer:completeAnimation()
			f64_arg0.emblemLayer.layerIcon:completeAnimation()
			f64_arg0.emblemLayer:setScale( 0.9, 0.9 )
			f64_arg0.emblemLayer.layerIcon:setAlpha( 1 )
			f64_local3( f64_arg0.emblemLayer )
			local f64_local4 = function ( f69_arg0 )
				f64_arg0.FrontendFrameSelected:beginAnimation( 150, Enum[0xF50FFF429AB1890][0x5193EA7825DC097] )
				f64_arg0.FrontendFrameSelected:setAlpha( 0 )
				f64_arg0.FrontendFrameSelected:setScale( 0.8, 0.8 )
				f64_arg0.FrontendFrameSelected:registerEventHandler( "interrupted_keyframe", f64_arg0.clipInterrupted )
				f64_arg0.FrontendFrameSelected:registerEventHandler( "transition_complete_keyframe", f64_arg0.clipFinished )
			end
			
			f64_arg0.FrontendFrameSelected:completeAnimation()
			f64_arg0.FrontendFrameSelected:setAlpha( 1 )
			f64_arg0.FrontendFrameSelected:setScale( 0.9, 0.9 )
			f64_local4( f64_arg0.FrontendFrameSelected )
			local f64_local5 = function ( f70_arg0 )
				f64_arg0.FrontendFrameSelectedGlow:beginAnimation( 150 )
				f64_arg0.FrontendFrameSelectedGlow:setAlpha( 0 )
				f64_arg0.FrontendFrameSelectedGlow:setScale( 0.8, 0.8 )
				f64_arg0.FrontendFrameSelectedGlow:registerEventHandler( "interrupted_keyframe", f64_arg0.clipInterrupted )
				f64_arg0.FrontendFrameSelectedGlow:registerEventHandler( "transition_complete_keyframe", f64_arg0.clipFinished )
			end
			
			f64_arg0.FrontendFrameSelectedGlow:completeAnimation()
			f64_arg0.FrontendFrameSelectedGlow:setAlpha( 0.05 )
			f64_arg0.FrontendFrameSelectedGlow:setScale( 0.9, 0.9 )
			f64_local5( f64_arg0.FrontendFrameSelectedGlow )
			local f64_local6 = function ( f71_arg0 )
				f64_arg0.FrontendFocusPip:beginAnimation( 150, Enum[0xF50FFF429AB1890][0x6F6186B702830BC] )
				f64_arg0.FrontendFocusPip:setAlpha( 0 )
				f64_arg0.FrontendFocusPip:setScale( 1.06, 1.06 )
				f64_arg0.FrontendFocusPip:registerEventHandler( "interrupted_keyframe", f64_arg0.clipInterrupted )
				f64_arg0.FrontendFocusPip:registerEventHandler( "transition_complete_keyframe", f64_arg0.clipFinished )
			end
			
			f64_arg0.FrontendFocusPip:completeAnimation()
			f64_arg0.FrontendFocusPip:setAlpha( 0.3 )
			f64_arg0.FrontendFocusPip:setScale( 0.9, 0.9 )
			f64_local6( f64_arg0.FrontendFocusPip )
			local f64_local7 = function ( f72_arg0 )
				f64_arg0.FrontendFrame:beginAnimation( 150 )
				f64_arg0.FrontendFrame:setScale( 0.8, 0.8 )
				f64_arg0.FrontendFrame:registerEventHandler( "interrupted_keyframe", f64_arg0.clipInterrupted )
				f64_arg0.FrontendFrame:registerEventHandler( "transition_complete_keyframe", f64_arg0.clipFinished )
			end
			
			f64_arg0.FrontendFrame:completeAnimation()
			f64_arg0.FrontendFrame:setScale( 0.9, 0.9 )
			f64_local7( f64_arg0.FrontendFrame )
			local f64_local8 = function ( f73_arg0 )
				f64_arg0.EmblemLayerPositionWidget:beginAnimation( 150 )
				f64_arg0.EmblemLayerPositionWidget:setLeftRight( 0, 0, 18, 155 )
				f64_arg0.EmblemLayerPositionWidget:setTopBottom( 0, 0, 155, 245 )
				f64_arg0.EmblemLayerPositionWidget:registerEventHandler( "interrupted_keyframe", f64_arg0.clipInterrupted )
				f64_arg0.EmblemLayerPositionWidget:registerEventHandler( "transition_complete_keyframe", f64_arg0.clipFinished )
			end
			
			f64_arg0.EmblemLayerPositionWidget:completeAnimation()
			f64_arg0.EmblemLayerPositionWidget:setLeftRight( 0, 0, 10, 164 )
			f64_arg0.EmblemLayerPositionWidget:setTopBottom( 0, 0, 164, 254 )
			f64_local8( f64_arg0.EmblemLayerPositionWidget )
		end,
		Active = function ( f74_arg0, f74_arg1 )
			f74_arg0:__resetProperties()
			f74_arg0:setupElementClipCounter( 10 )
			f74_arg0.Backing:completeAnimation()
			f74_arg0.Backing:setAlpha( 0.02 )
			f74_arg0.Backing:setScale( 0.8, 0.8 )
			f74_arg0.clipFinished( f74_arg0.Backing )
			f74_arg0.NoiseTiledBacking:completeAnimation()
			f74_arg0.NoiseTiledBacking:setScale( 0.8, 0.8 )
			f74_arg0.clipFinished( f74_arg0.NoiseTiledBacking )
			f74_arg0.NoiseTiledBackingAdd:completeAnimation()
			f74_arg0.NoiseTiledBackingAdd:setAlpha( 0.65 )
			f74_arg0.NoiseTiledBackingAdd:setScale( 0.8, 0.8 )
			f74_arg0.clipFinished( f74_arg0.NoiseTiledBackingAdd )
			f74_arg0.emblemLayer:completeAnimation()
			f74_arg0.emblemLayer.layerIcon:completeAnimation()
			f74_arg0.emblemLayer:setScale( 0.8, 0.8 )
			f74_arg0.emblemLayer.layerIcon:setAlpha( 1 )
			f74_arg0.clipFinished( f74_arg0.emblemLayer )
			f74_arg0.arrows:completeAnimation()
			f74_arg0.arrows:setZoom( 50 )
			f74_arg0.clipFinished( f74_arg0.arrows )
			f74_arg0.FrontendFrameSelected:completeAnimation()
			f74_arg0.FrontendFrameSelected:setAlpha( 1 )
			f74_arg0.FrontendFrameSelected:setScale( 0.8, 0.8 )
			f74_arg0.clipFinished( f74_arg0.FrontendFrameSelected )
			f74_arg0.FrontendFrameSelectedGlow:completeAnimation()
			f74_arg0.FrontendFrameSelectedGlow:setAlpha( 0.05 )
			f74_arg0.FrontendFrameSelectedGlow:setScale( 0.8, 0.8 )
			f74_arg0.clipFinished( f74_arg0.FrontendFrameSelectedGlow )
			f74_arg0.FrontendFocusPip:completeAnimation()
			f74_arg0.FrontendFocusPip:setAlpha( 0 )
			f74_arg0.FrontendFocusPip:setScale( 1.06, 1.06 )
			f74_arg0.clipFinished( f74_arg0.FrontendFocusPip )
			f74_arg0.FrontendFrame:completeAnimation()
			f74_arg0.FrontendFrame:setScale( 0.8, 0.8 )
			f74_arg0.clipFinished( f74_arg0.FrontendFrame )
			f74_arg0.EmblemLayerPositionWidget:completeAnimation()
			f74_arg0.EmblemLayerPositionWidget:setLeftRight( 0, 0, 18, 155 )
			f74_arg0.EmblemLayerPositionWidget:setTopBottom( 0, 0, 155, 245 )
			f74_arg0.clipFinished( f74_arg0.EmblemLayerPositionWidget )
		end,
		ActiveAndFocus = function ( f75_arg0, f75_arg1 )
			f75_arg0:__resetProperties()
			f75_arg0:setupElementClipCounter( 9 )
			f75_arg0.Backing:completeAnimation()
			f75_arg0.Backing:setAlpha( 0.02 )
			f75_arg0.Backing:setScale( 0.9, 0.9 )
			f75_arg0.clipFinished( f75_arg0.Backing )
			f75_arg0.NoiseTiledBacking:completeAnimation()
			f75_arg0.NoiseTiledBacking:setScale( 0.9, 0.9 )
			f75_arg0.clipFinished( f75_arg0.NoiseTiledBacking )
			f75_arg0.NoiseTiledBackingAdd:completeAnimation()
			f75_arg0.NoiseTiledBackingAdd:setAlpha( 0.65 )
			f75_arg0.NoiseTiledBackingAdd:setScale( 0.9, 0.9 )
			f75_arg0.clipFinished( f75_arg0.NoiseTiledBackingAdd )
			f75_arg0.emblemLayer:completeAnimation()
			f75_arg0.emblemLayer.layerIcon:completeAnimation()
			f75_arg0.emblemLayer:setScale( 0.9, 0.9 )
			f75_arg0.emblemLayer.layerIcon:setAlpha( 1 )
			f75_arg0.clipFinished( f75_arg0.emblemLayer )
			f75_arg0.FrontendFrameSelected:completeAnimation()
			f75_arg0.FrontendFrameSelected:setAlpha( 1 )
			f75_arg0.FrontendFrameSelected:setScale( 0.9, 0.9 )
			f75_arg0.clipFinished( f75_arg0.FrontendFrameSelected )
			f75_arg0.FrontendFrameSelectedGlow:completeAnimation()
			f75_arg0.FrontendFrameSelectedGlow:setAlpha( 0.05 )
			f75_arg0.FrontendFrameSelectedGlow:setScale( 0.9, 0.9 )
			f75_arg0.clipFinished( f75_arg0.FrontendFrameSelectedGlow )
			f75_arg0.FrontendFocusPip:completeAnimation()
			f75_arg0.FrontendFocusPip:setAlpha( 0.3 )
			f75_arg0.FrontendFocusPip:setScale( 0.9, 0.9 )
			f75_arg0.clipFinished( f75_arg0.FrontendFocusPip )
			f75_arg0.FrontendFrame:completeAnimation()
			f75_arg0.FrontendFrame:setScale( 0.9, 0.9 )
			f75_arg0.clipFinished( f75_arg0.FrontendFrame )
			f75_arg0.EmblemLayerPositionWidget:completeAnimation()
			f75_arg0.EmblemLayerPositionWidget:setLeftRight( 0, 0, 10, 164 )
			f75_arg0.EmblemLayerPositionWidget:setTopBottom( 0, 0, 164, 254 )
			f75_arg0.clipFinished( f75_arg0.EmblemLayerPositionWidget )
		end,
		ActiveToActiveAndFocus = function ( f76_arg0, f76_arg1 )
			f76_arg0:__resetProperties()
			f76_arg0:setupElementClipCounter( 10 )
			local f76_local0 = function ( f77_arg0 )
				f76_arg0.Backing:beginAnimation( 150 )
				f76_arg0.Backing:setScale( 0.9, 0.9 )
				f76_arg0.Backing:registerEventHandler( "interrupted_keyframe", f76_arg0.clipInterrupted )
				f76_arg0.Backing:registerEventHandler( "transition_complete_keyframe", f76_arg0.clipFinished )
			end
			
			f76_arg0.Backing:completeAnimation()
			f76_arg0.Backing:setAlpha( 0.02 )
			f76_arg0.Backing:setScale( 0.8, 0.8 )
			f76_local0( f76_arg0.Backing )
			local f76_local1 = function ( f78_arg0 )
				f76_arg0.NoiseTiledBacking:beginAnimation( 150 )
				f76_arg0.NoiseTiledBacking:setScale( 0.9, 0.9 )
				f76_arg0.NoiseTiledBacking:registerEventHandler( "interrupted_keyframe", f76_arg0.clipInterrupted )
				f76_arg0.NoiseTiledBacking:registerEventHandler( "transition_complete_keyframe", f76_arg0.clipFinished )
			end
			
			f76_arg0.NoiseTiledBacking:completeAnimation()
			f76_arg0.NoiseTiledBacking:setScale( 0.8, 0.8 )
			f76_local1( f76_arg0.NoiseTiledBacking )
			local f76_local2 = function ( f79_arg0 )
				f76_arg0.NoiseTiledBackingAdd:beginAnimation( 150 )
				f76_arg0.NoiseTiledBackingAdd:setScale( 0.9, 0.9 )
				f76_arg0.NoiseTiledBackingAdd:registerEventHandler( "interrupted_keyframe", f76_arg0.clipInterrupted )
				f76_arg0.NoiseTiledBackingAdd:registerEventHandler( "transition_complete_keyframe", f76_arg0.clipFinished )
			end
			
			f76_arg0.NoiseTiledBackingAdd:completeAnimation()
			f76_arg0.NoiseTiledBackingAdd:setAlpha( 0.65 )
			f76_arg0.NoiseTiledBackingAdd:setScale( 0.8, 0.8 )
			f76_local2( f76_arg0.NoiseTiledBackingAdd )
			local f76_local3 = function ( f80_arg0 )
				f76_arg0.emblemLayer:beginAnimation( 150 )
				f76_arg0.emblemLayer:setScale( 0.9, 0.9 )
				f76_arg0.emblemLayer:registerEventHandler( "interrupted_keyframe", f76_arg0.clipInterrupted )
				f76_arg0.emblemLayer:registerEventHandler( "transition_complete_keyframe", f76_arg0.clipFinished )
			end
			
			f76_arg0.emblemLayer:completeAnimation()
			f76_arg0.emblemLayer.layerIcon:completeAnimation()
			f76_arg0.emblemLayer:setScale( 0.8, 0.8 )
			f76_arg0.emblemLayer.layerIcon:setAlpha( 1 )
			f76_local3( f76_arg0.emblemLayer )
			local f76_local4 = function ( f81_arg0 )
				f76_arg0.arrows:beginAnimation( 150 )
				f76_arg0.arrows:setZoom( 0 )
				f76_arg0.arrows:registerEventHandler( "interrupted_keyframe", f76_arg0.clipInterrupted )
				f76_arg0.arrows:registerEventHandler( "transition_complete_keyframe", f76_arg0.clipFinished )
			end
			
			f76_arg0.arrows:completeAnimation()
			f76_arg0.arrows:setZoom( 50 )
			f76_local4( f76_arg0.arrows )
			local f76_local5 = function ( f82_arg0 )
				f76_arg0.FrontendFrameSelected:beginAnimation( 150 )
				f76_arg0.FrontendFrameSelected:setScale( 0.9, 0.9 )
				f76_arg0.FrontendFrameSelected:registerEventHandler( "interrupted_keyframe", f76_arg0.clipInterrupted )
				f76_arg0.FrontendFrameSelected:registerEventHandler( "transition_complete_keyframe", f76_arg0.clipFinished )
			end
			
			f76_arg0.FrontendFrameSelected:completeAnimation()
			f76_arg0.FrontendFrameSelected:setAlpha( 1 )
			f76_arg0.FrontendFrameSelected:setScale( 0.8, 0.8 )
			f76_local5( f76_arg0.FrontendFrameSelected )
			local f76_local6 = function ( f83_arg0 )
				f76_arg0.FrontendFrameSelectedGlow:beginAnimation( 150 )
				f76_arg0.FrontendFrameSelectedGlow:setScale( 0.9, 0.9 )
				f76_arg0.FrontendFrameSelectedGlow:registerEventHandler( "interrupted_keyframe", f76_arg0.clipInterrupted )
				f76_arg0.FrontendFrameSelectedGlow:registerEventHandler( "transition_complete_keyframe", f76_arg0.clipFinished )
			end
			
			f76_arg0.FrontendFrameSelectedGlow:completeAnimation()
			f76_arg0.FrontendFrameSelectedGlow:setAlpha( 0.05 )
			f76_arg0.FrontendFrameSelectedGlow:setScale( 0.8, 0.8 )
			f76_local6( f76_arg0.FrontendFrameSelectedGlow )
			local f76_local7 = function ( f84_arg0 )
				f76_arg0.FrontendFocusPip:beginAnimation( 150 )
				f76_arg0.FrontendFocusPip:setAlpha( 0.3 )
				f76_arg0.FrontendFocusPip:setScale( 0.9, 0.9 )
				f76_arg0.FrontendFocusPip:registerEventHandler( "interrupted_keyframe", f76_arg0.clipInterrupted )
				f76_arg0.FrontendFocusPip:registerEventHandler( "transition_complete_keyframe", f76_arg0.clipFinished )
			end
			
			f76_arg0.FrontendFocusPip:completeAnimation()
			f76_arg0.FrontendFocusPip:setAlpha( 0 )
			f76_arg0.FrontendFocusPip:setScale( 1.06, 1.06 )
			f76_local7( f76_arg0.FrontendFocusPip )
			local f76_local8 = function ( f85_arg0 )
				f76_arg0.FrontendFrame:beginAnimation( 150 )
				f76_arg0.FrontendFrame:setScale( 0.9, 0.9 )
				f76_arg0.FrontendFrame:registerEventHandler( "interrupted_keyframe", f76_arg0.clipInterrupted )
				f76_arg0.FrontendFrame:registerEventHandler( "transition_complete_keyframe", f76_arg0.clipFinished )
			end
			
			f76_arg0.FrontendFrame:completeAnimation()
			f76_arg0.FrontendFrame:setScale( 0.8, 0.8 )
			f76_local8( f76_arg0.FrontendFrame )
			local f76_local9 = function ( f86_arg0 )
				f76_arg0.EmblemLayerPositionWidget:beginAnimation( 150 )
				f76_arg0.EmblemLayerPositionWidget:setLeftRight( 0, 0, 10, 164 )
				f76_arg0.EmblemLayerPositionWidget:setTopBottom( 0, 0, 164, 254 )
				f76_arg0.EmblemLayerPositionWidget:registerEventHandler( "interrupted_keyframe", f76_arg0.clipInterrupted )
				f76_arg0.EmblemLayerPositionWidget:registerEventHandler( "transition_complete_keyframe", f76_arg0.clipFinished )
			end
			
			f76_arg0.EmblemLayerPositionWidget:completeAnimation()
			f76_arg0.EmblemLayerPositionWidget:setLeftRight( 0, 0, 18, 155 )
			f76_arg0.EmblemLayerPositionWidget:setTopBottom( 0, 0, 155, 245 )
			f76_local9( f76_arg0.EmblemLayerPositionWidget )
		end,
		ActiveAndFocusToActive = function ( f87_arg0, f87_arg1 )
			f87_arg0:__resetProperties()
			f87_arg0:setupElementClipCounter( 10 )
			local f87_local0 = function ( f88_arg0 )
				f87_arg0.Backing:beginAnimation( 150 )
				f87_arg0.Backing:setScale( 0.8, 0.8 )
				f87_arg0.Backing:registerEventHandler( "interrupted_keyframe", f87_arg0.clipInterrupted )
				f87_arg0.Backing:registerEventHandler( "transition_complete_keyframe", f87_arg0.clipFinished )
			end
			
			f87_arg0.Backing:completeAnimation()
			f87_arg0.Backing:setAlpha( 0.02 )
			f87_arg0.Backing:setScale( 0.9, 0.9 )
			f87_local0( f87_arg0.Backing )
			local f87_local1 = function ( f89_arg0 )
				f87_arg0.NoiseTiledBacking:beginAnimation( 150 )
				f87_arg0.NoiseTiledBacking:setScale( 0.8, 0.8 )
				f87_arg0.NoiseTiledBacking:registerEventHandler( "interrupted_keyframe", f87_arg0.clipInterrupted )
				f87_arg0.NoiseTiledBacking:registerEventHandler( "transition_complete_keyframe", f87_arg0.clipFinished )
			end
			
			f87_arg0.NoiseTiledBacking:completeAnimation()
			f87_arg0.NoiseTiledBacking:setScale( 0.9, 0.9 )
			f87_local1( f87_arg0.NoiseTiledBacking )
			local f87_local2 = function ( f90_arg0 )
				f87_arg0.NoiseTiledBackingAdd:beginAnimation( 150 )
				f87_arg0.NoiseTiledBackingAdd:setScale( 0.8, 0.8 )
				f87_arg0.NoiseTiledBackingAdd:registerEventHandler( "interrupted_keyframe", f87_arg0.clipInterrupted )
				f87_arg0.NoiseTiledBackingAdd:registerEventHandler( "transition_complete_keyframe", f87_arg0.clipFinished )
			end
			
			f87_arg0.NoiseTiledBackingAdd:completeAnimation()
			f87_arg0.NoiseTiledBackingAdd:setAlpha( 0.65 )
			f87_arg0.NoiseTiledBackingAdd:setScale( 0.9, 0.9 )
			f87_local2( f87_arg0.NoiseTiledBackingAdd )
			local f87_local3 = function ( f91_arg0 )
				f87_arg0.emblemLayer:beginAnimation( 150 )
				f87_arg0.emblemLayer:setScale( 0.8, 0.8 )
				f87_arg0.emblemLayer:registerEventHandler( "interrupted_keyframe", f87_arg0.clipInterrupted )
				f87_arg0.emblemLayer:registerEventHandler( "transition_complete_keyframe", f87_arg0.clipFinished )
			end
			
			f87_arg0.emblemLayer:completeAnimation()
			f87_arg0.emblemLayer.layerIcon:completeAnimation()
			f87_arg0.emblemLayer:setScale( 0.9, 0.9 )
			f87_arg0.emblemLayer.layerIcon:setAlpha( 1 )
			f87_local3( f87_arg0.emblemLayer )
			local f87_local4 = function ( f92_arg0 )
				f87_arg0.arrows:beginAnimation( 150 )
				f87_arg0.arrows:setZoom( 50 )
				f87_arg0.arrows:registerEventHandler( "interrupted_keyframe", f87_arg0.clipInterrupted )
				f87_arg0.arrows:registerEventHandler( "transition_complete_keyframe", f87_arg0.clipFinished )
			end
			
			f87_arg0.arrows:completeAnimation()
			f87_arg0.arrows:setZoom( 0 )
			f87_local4( f87_arg0.arrows )
			local f87_local5 = function ( f93_arg0 )
				f87_arg0.FrontendFrameSelected:beginAnimation( 150 )
				f87_arg0.FrontendFrameSelected:setScale( 0.8, 0.8 )
				f87_arg0.FrontendFrameSelected:registerEventHandler( "interrupted_keyframe", f87_arg0.clipInterrupted )
				f87_arg0.FrontendFrameSelected:registerEventHandler( "transition_complete_keyframe", f87_arg0.clipFinished )
			end
			
			f87_arg0.FrontendFrameSelected:completeAnimation()
			f87_arg0.FrontendFrameSelected:setAlpha( 1 )
			f87_arg0.FrontendFrameSelected:setScale( 0.9, 0.9 )
			f87_local5( f87_arg0.FrontendFrameSelected )
			local f87_local6 = function ( f94_arg0 )
				f87_arg0.FrontendFrameSelectedGlow:beginAnimation( 150 )
				f87_arg0.FrontendFrameSelectedGlow:setScale( 0.8, 0.8 )
				f87_arg0.FrontendFrameSelectedGlow:registerEventHandler( "interrupted_keyframe", f87_arg0.clipInterrupted )
				f87_arg0.FrontendFrameSelectedGlow:registerEventHandler( "transition_complete_keyframe", f87_arg0.clipFinished )
			end
			
			f87_arg0.FrontendFrameSelectedGlow:completeAnimation()
			f87_arg0.FrontendFrameSelectedGlow:setAlpha( 0.05 )
			f87_arg0.FrontendFrameSelectedGlow:setScale( 0.9, 0.9 )
			f87_local6( f87_arg0.FrontendFrameSelectedGlow )
			local f87_local7 = function ( f95_arg0 )
				f87_arg0.FrontendFocusPip:beginAnimation( 150 )
				f87_arg0.FrontendFocusPip:setAlpha( 0 )
				f87_arg0.FrontendFocusPip:setScale( 1.06, 1.06 )
				f87_arg0.FrontendFocusPip:registerEventHandler( "interrupted_keyframe", f87_arg0.clipInterrupted )
				f87_arg0.FrontendFocusPip:registerEventHandler( "transition_complete_keyframe", f87_arg0.clipFinished )
			end
			
			f87_arg0.FrontendFocusPip:completeAnimation()
			f87_arg0.FrontendFocusPip:setAlpha( 0.3 )
			f87_arg0.FrontendFocusPip:setScale( 0.9, 0.9 )
			f87_local7( f87_arg0.FrontendFocusPip )
			local f87_local8 = function ( f96_arg0 )
				f87_arg0.FrontendFrame:beginAnimation( 150 )
				f87_arg0.FrontendFrame:setScale( 0.8, 0.8 )
				f87_arg0.FrontendFrame:registerEventHandler( "interrupted_keyframe", f87_arg0.clipInterrupted )
				f87_arg0.FrontendFrame:registerEventHandler( "transition_complete_keyframe", f87_arg0.clipFinished )
			end
			
			f87_arg0.FrontendFrame:completeAnimation()
			f87_arg0.FrontendFrame:setScale( 0.9, 0.9 )
			f87_local8( f87_arg0.FrontendFrame )
			local f87_local9 = function ( f97_arg0 )
				f87_arg0.EmblemLayerPositionWidget:beginAnimation( 150 )
				f87_arg0.EmblemLayerPositionWidget:setLeftRight( 0, 0, 18, 155 )
				f87_arg0.EmblemLayerPositionWidget:setTopBottom( 0, 0, 155, 245 )
				f87_arg0.EmblemLayerPositionWidget:registerEventHandler( "interrupted_keyframe", f87_arg0.clipInterrupted )
				f87_arg0.EmblemLayerPositionWidget:registerEventHandler( "transition_complete_keyframe", f87_arg0.clipFinished )
			end
			
			f87_arg0.EmblemLayerPositionWidget:completeAnimation()
			f87_arg0.EmblemLayerPositionWidget:setLeftRight( 0, 0, 10, 164 )
			f87_arg0.EmblemLayerPositionWidget:setTopBottom( 0, 0, 164, 254 )
			f87_local9( f87_arg0.EmblemLayerPositionWidget )
		end
	}
}
if not CoD.isPC then
	CoD.EmblemLayerContainer.__clipsPerState.DefaultStateKBM.Focus = nil
	CoD.EmblemLayerContainer.__clipsPerState.DefaultStateKBM.GainFocus = nil
	CoD.EmblemLayerContainer.__clipsPerState.DefaultStateKBM.LoseFocus = nil
	CoD.EmblemLayerContainer.__clipsPerState.DefaultStateKBM.Active = nil
	CoD.EmblemLayerContainer.__clipsPerState.DefaultStateKBM.ActiveToActiveAndFocus = nil
end
CoD.EmblemLayerContainer.__onClose = function ( f98_arg0 )
	f98_arg0.emblemLayer:close()
	f98_arg0.arrows:close()
	f98_arg0.EmblemLayerPositionWidget:close()
end

