require( "ui/uieditor/widgets/pc/bnetstore/pc_bnetstore_giftbutton_texts" )

CoD.PC_BnetStore_GiftButton = InheritFrom( LUI.UIElement )
CoD.PC_BnetStore_GiftButton.__defaultWidth = 500
CoD.PC_BnetStore_GiftButton.__defaultHeight = 45
CoD.PC_BnetStore_GiftButton.new = function ( f1_arg0, f1_arg1, f1_arg2, f1_arg3, f1_arg4, f1_arg5, f1_arg6, f1_arg7, f1_arg8, f1_arg9 )
	local self = LUI.UIElement.new( f1_arg2, f1_arg3, f1_arg4, f1_arg5, f1_arg6, f1_arg7, f1_arg8, f1_arg9 )
	self:setClass( CoD.PC_BnetStore_GiftButton )
	self.id = "PC_BnetStore_GiftButton"
	self.soundSet = "default"
	self.anyChildUsesUpdateState = true
	f1_arg0:addElementToPendingUpdateStateList( self )
	
	local ButtonBG = LUI.UIImage.new( 0, 1, 0, 0, 0, 1, 0, 0 )
	ButtonBG:setRGB( 0.12, 0.12, 0.12 )
	self:addElement( ButtonBG )
	self.ButtonBG = ButtonBG
	
	local LineTop = LUI.UIImage.new( 0, 1, 1, -1, 0, 0, 0, 1 )
	LineTop:setAlpha( 0.08 )
	self:addElement( LineTop )
	self.LineTop = LineTop
	
	local LineTopLeft = LUI.UIImage.new( 0, 0, 0, 1, 0, 0, 0, 10 )
	LineTopLeft:setAlpha( 0.08 )
	self:addElement( LineTopLeft )
	self.LineTopLeft = LineTopLeft
	
	local LineTopRight = LUI.UIImage.new( 1, 1, -1, 0, 0, 0, 0, 10 )
	LineTopRight:setAlpha( 0.08 )
	self:addElement( LineTopRight )
	self.LineTopRight = LineTopRight
	
	local LineBtm = LUI.UIImage.new( 0, 1, 1, -1, 1, 1, -1, 0 )
	LineBtm:setAlpha( 0.08 )
	self:addElement( LineBtm )
	self.LineBtm = LineBtm
	
	local DotBR = LUI.UIImage.new( 1, 1, -1, 0, 1, 1, -1, 0 )
	DotBR:setAlpha( 0.8 )
	self:addElement( DotBR )
	self.DotBR = DotBR
	
	local DotBL = LUI.UIImage.new( 0, 0, 0, 1, 1, 1, -1, 0 )
	DotBL:setAlpha( 0.8 )
	self:addElement( DotBL )
	self.DotBL = DotBL
	
	local DotTR = LUI.UIImage.new( 1, 1, -1, 0, 0, 0, 14, 15 )
	DotTR:setAlpha( 0.8 )
	self:addElement( DotTR )
	self.DotTR = DotTR
	
	local DotTL = LUI.UIImage.new( 0, 0, 0, 1, 0, 0, 14, 15 )
	DotTL:setAlpha( 0.8 )
	self:addElement( DotTL )
	self.DotTL = DotTL
	
	local ButtonTitle = CoD.PC_BnetStore_GiftButton_Texts.new( f1_arg0, f1_arg1, 0.5, 0.5, -225, 225, 0.5, 0.5, -12, 12 )
	ButtonTitle:mergeStateConditions( {
		{
			stateName = "InSale",
			condition = function ( menu, element, event )
				return IsSelfInState( self, "InSale" )
			end
		}
	} )
	ButtonTitle.GiftSalePrice:setText( Engine[0xF9F1239CFD921FE]( "store/gift" ) )
	ButtonTitle.GiftPrice:setText( Engine[0xF9F1239CFD921FE]( "store/gift" ) )
	self:addElement( ButtonTitle )
	self.ButtonTitle = ButtonTitle
	
	LUI.OverrideFunction_CallOriginalFirst( self, "setState", function ( element, controller, f3_arg2, f3_arg3, f3_arg4 )
		UpdateElementState( self, "ButtonTitle", controller )
	end )
	LUI.OverrideFunction_CallOriginalSecond( self, "close", self.__onClose )
	
	if PostLoadFunc then
		PostLoadFunc( self, f1_arg1, f1_arg0 )
	end
	
	return self
end

CoD.PC_BnetStore_GiftButton.__resetProperties = function ( f4_arg0 )
	f4_arg0.ButtonTitle:completeAnimation()
	f4_arg0.ButtonBG:completeAnimation()
	f4_arg0.LineTop:completeAnimation()
	f4_arg0.LineTopRight:completeAnimation()
	f4_arg0.LineTopLeft:completeAnimation()
	f4_arg0.LineBtm:completeAnimation()
	f4_arg0.DotBL:completeAnimation()
	f4_arg0.DotBR:completeAnimation()
	f4_arg0.DotTL:completeAnimation()
	f4_arg0.DotTR:completeAnimation()
	f4_arg0.ButtonTitle:setAlpha( 1 )
	f4_arg0.ButtonBG:setRGB( 0.12, 0.12, 0.12 )
	f4_arg0.ButtonBG:setAlpha( 1 )
	f4_arg0.LineTop:setAlpha( 0.08 )
	f4_arg0.LineTopRight:setTopBottom( 0, 0, 0, 10 )
	f4_arg0.LineTopRight:setAlpha( 0.08 )
	f4_arg0.LineTopLeft:setTopBottom( 0, 0, 0, 10 )
	f4_arg0.LineTopLeft:setAlpha( 0.08 )
	f4_arg0.LineBtm:setAlpha( 0.08 )
	f4_arg0.DotBL:setAlpha( 0.8 )
	f4_arg0.DotBR:setAlpha( 0.8 )
	f4_arg0.DotTL:setTopBottom( 0, 0, 14, 15 )
	f4_arg0.DotTL:setAlpha( 0.8 )
	f4_arg0.DotTR:setTopBottom( 0, 0, 14, 15 )
	f4_arg0.DotTR:setAlpha( 0.8 )
end

CoD.PC_BnetStore_GiftButton.__clipsPerState = {
	DefaultState = {
		DefaultClip = function ( f5_arg0, f5_arg1 )
			f5_arg0:__resetProperties()
			f5_arg0:setupElementClipCounter( 1 )
			f5_arg0.ButtonTitle:completeAnimation()
			f5_arg0.ButtonTitle:setAlpha( 1 )
			f5_arg0.ButtonTitle:playClip( "DefaultClip" )
			f5_arg0.clipFinished( f5_arg0.ButtonTitle )
		end,
		Focus = function ( f6_arg0, f6_arg1 )
			f6_arg0:__resetProperties()
			f6_arg0:setupElementClipCounter( 10 )
			f6_arg0.ButtonBG:completeAnimation()
			f6_arg0.ButtonBG:setRGB( 0.16, 0.16, 0.16 )
			f6_arg0.clipFinished( f6_arg0.ButtonBG )
			f6_arg0.LineTop:completeAnimation()
			f6_arg0.LineTop:setAlpha( 0.15 )
			f6_arg0.clipFinished( f6_arg0.LineTop )
			f6_arg0.LineTopLeft:completeAnimation()
			f6_arg0.LineTopLeft:setTopBottom( 0, 0, 0, 17 )
			f6_arg0.LineTopLeft:setAlpha( 0.15 )
			f6_arg0.clipFinished( f6_arg0.LineTopLeft )
			f6_arg0.LineTopRight:completeAnimation()
			f6_arg0.LineTopRight:setTopBottom( 0, 0, 0, 17 )
			f6_arg0.LineTopRight:setAlpha( 0.15 )
			f6_arg0.clipFinished( f6_arg0.LineTopRight )
			f6_arg0.LineBtm:completeAnimation()
			f6_arg0.LineBtm:setAlpha( 0.15 )
			f6_arg0.clipFinished( f6_arg0.LineBtm )
			f6_arg0.DotBR:completeAnimation()
			f6_arg0.DotBR:setAlpha( 1 )
			f6_arg0.clipFinished( f6_arg0.DotBR )
			f6_arg0.DotBL:completeAnimation()
			f6_arg0.DotBL:setAlpha( 1 )
			f6_arg0.clipFinished( f6_arg0.DotBL )
			f6_arg0.DotTR:completeAnimation()
			f6_arg0.DotTR:setTopBottom( 0, 0, 21, 22 )
			f6_arg0.clipFinished( f6_arg0.DotTR )
			f6_arg0.DotTL:completeAnimation()
			f6_arg0.DotTL:setTopBottom( 0, 0, 21, 22 )
			f6_arg0.clipFinished( f6_arg0.DotTL )
			f6_arg0.ButtonTitle:completeAnimation()
			f6_arg0.ButtonTitle:setAlpha( 1 )
			f6_arg0.ButtonTitle:playClip( "DefaultClip" )
			f6_arg0.clipFinished( f6_arg0.ButtonTitle )
		end,
		GainFocus = function ( f7_arg0, f7_arg1 )
			f7_arg0:__resetProperties()
			f7_arg0:setupElementClipCounter( 10 )
			local f7_local0 = function ( f8_arg0 )
				f7_arg0.ButtonBG:beginAnimation( 100 )
				f7_arg0.ButtonBG:setRGB( 0.16, 0.16, 0.16 )
				f7_arg0.ButtonBG:registerEventHandler( "interrupted_keyframe", f7_arg0.clipInterrupted )
				f7_arg0.ButtonBG:registerEventHandler( "transition_complete_keyframe", f7_arg0.clipFinished )
			end
			
			f7_arg0.ButtonBG:completeAnimation()
			f7_arg0.ButtonBG:setRGB( 0.12, 0.12, 0.12 )
			f7_local0( f7_arg0.ButtonBG )
			local f7_local1 = function ( f9_arg0 )
				f7_arg0.LineTop:beginAnimation( 100 )
				f7_arg0.LineTop:setAlpha( 0.15 )
				f7_arg0.LineTop:registerEventHandler( "interrupted_keyframe", f7_arg0.clipInterrupted )
				f7_arg0.LineTop:registerEventHandler( "transition_complete_keyframe", f7_arg0.clipFinished )
			end
			
			f7_arg0.LineTop:completeAnimation()
			f7_arg0.LineTop:setAlpha( 0.08 )
			f7_local1( f7_arg0.LineTop )
			local f7_local2 = function ( f10_arg0 )
				f7_arg0.LineTopLeft:beginAnimation( 100 )
				f7_arg0.LineTopLeft:setTopBottom( 0, 0, 0, 17 )
				f7_arg0.LineTopLeft:setAlpha( 0.15 )
				f7_arg0.LineTopLeft:registerEventHandler( "interrupted_keyframe", f7_arg0.clipInterrupted )
				f7_arg0.LineTopLeft:registerEventHandler( "transition_complete_keyframe", f7_arg0.clipFinished )
			end
			
			f7_arg0.LineTopLeft:completeAnimation()
			f7_arg0.LineTopLeft:setTopBottom( 0, 0, 0, 10 )
			f7_arg0.LineTopLeft:setAlpha( 0.08 )
			f7_local2( f7_arg0.LineTopLeft )
			local f7_local3 = function ( f11_arg0 )
				f7_arg0.LineTopRight:beginAnimation( 100 )
				f7_arg0.LineTopRight:setTopBottom( 0, 0, 0, 17 )
				f7_arg0.LineTopRight:setAlpha( 0.15 )
				f7_arg0.LineTopRight:registerEventHandler( "interrupted_keyframe", f7_arg0.clipInterrupted )
				f7_arg0.LineTopRight:registerEventHandler( "transition_complete_keyframe", f7_arg0.clipFinished )
			end
			
			f7_arg0.LineTopRight:completeAnimation()
			f7_arg0.LineTopRight:setTopBottom( 0, 0, 0, 10 )
			f7_arg0.LineTopRight:setAlpha( 0.08 )
			f7_local3( f7_arg0.LineTopRight )
			local f7_local4 = function ( f12_arg0 )
				f7_arg0.LineBtm:beginAnimation( 100 )
				f7_arg0.LineBtm:setAlpha( 0.15 )
				f7_arg0.LineBtm:registerEventHandler( "interrupted_keyframe", f7_arg0.clipInterrupted )
				f7_arg0.LineBtm:registerEventHandler( "transition_complete_keyframe", f7_arg0.clipFinished )
			end
			
			f7_arg0.LineBtm:completeAnimation()
			f7_arg0.LineBtm:setAlpha( 0.08 )
			f7_local4( f7_arg0.LineBtm )
			local f7_local5 = function ( f13_arg0 )
				f7_arg0.DotBR:beginAnimation( 100 )
				f7_arg0.DotBR:setAlpha( 1 )
				f7_arg0.DotBR:registerEventHandler( "interrupted_keyframe", f7_arg0.clipInterrupted )
				f7_arg0.DotBR:registerEventHandler( "transition_complete_keyframe", f7_arg0.clipFinished )
			end
			
			f7_arg0.DotBR:completeAnimation()
			f7_arg0.DotBR:setAlpha( 0.8 )
			f7_local5( f7_arg0.DotBR )
			local f7_local6 = function ( f14_arg0 )
				f7_arg0.DotBL:beginAnimation( 100 )
				f7_arg0.DotBL:setAlpha( 1 )
				f7_arg0.DotBL:registerEventHandler( "interrupted_keyframe", f7_arg0.clipInterrupted )
				f7_arg0.DotBL:registerEventHandler( "transition_complete_keyframe", f7_arg0.clipFinished )
			end
			
			f7_arg0.DotBL:completeAnimation()
			f7_arg0.DotBL:setAlpha( 0.8 )
			f7_local6( f7_arg0.DotBL )
			local f7_local7 = function ( f15_arg0 )
				f7_arg0.DotTR:beginAnimation( 100 )
				f7_arg0.DotTR:setTopBottom( 0, 0, 21, 22 )
				f7_arg0.DotTR:registerEventHandler( "interrupted_keyframe", f7_arg0.clipInterrupted )
				f7_arg0.DotTR:registerEventHandler( "transition_complete_keyframe", f7_arg0.clipFinished )
			end
			
			f7_arg0.DotTR:completeAnimation()
			f7_arg0.DotTR:setTopBottom( 0, 0, 14, 15 )
			f7_local7( f7_arg0.DotTR )
			local f7_local8 = function ( f16_arg0 )
				f7_arg0.DotTL:beginAnimation( 100 )
				f7_arg0.DotTL:setTopBottom( 0, 0, 21, 22 )
				f7_arg0.DotTL:registerEventHandler( "interrupted_keyframe", f7_arg0.clipInterrupted )
				f7_arg0.DotTL:registerEventHandler( "transition_complete_keyframe", f7_arg0.clipFinished )
			end
			
			f7_arg0.DotTL:completeAnimation()
			f7_arg0.DotTL:setTopBottom( 0, 0, 14, 15 )
			f7_local8( f7_arg0.DotTL )
			f7_arg0.ButtonTitle:completeAnimation()
			f7_arg0.ButtonTitle:setAlpha( 1 )
			f7_arg0.ButtonTitle:playClip( "DefaultClip" )
			f7_arg0.clipFinished( f7_arg0.ButtonTitle )
		end,
		LoseFocus = function ( f17_arg0, f17_arg1 )
			f17_arg0:__resetProperties()
			f17_arg0:setupElementClipCounter( 10 )
			local f17_local0 = function ( f18_arg0 )
				f17_arg0.ButtonBG:beginAnimation( 100 )
				f17_arg0.ButtonBG:setRGB( 0.12, 0.12, 0.12 )
				f17_arg0.ButtonBG:registerEventHandler( "interrupted_keyframe", f17_arg0.clipInterrupted )
				f17_arg0.ButtonBG:registerEventHandler( "transition_complete_keyframe", f17_arg0.clipFinished )
			end
			
			f17_arg0.ButtonBG:completeAnimation()
			f17_arg0.ButtonBG:setRGB( 0.16, 0.16, 0.16 )
			f17_local0( f17_arg0.ButtonBG )
			local f17_local1 = function ( f19_arg0 )
				f17_arg0.LineTop:beginAnimation( 100 )
				f17_arg0.LineTop:setAlpha( 0.08 )
				f17_arg0.LineTop:registerEventHandler( "interrupted_keyframe", f17_arg0.clipInterrupted )
				f17_arg0.LineTop:registerEventHandler( "transition_complete_keyframe", f17_arg0.clipFinished )
			end
			
			f17_arg0.LineTop:completeAnimation()
			f17_arg0.LineTop:setAlpha( 0.15 )
			f17_local1( f17_arg0.LineTop )
			local f17_local2 = function ( f20_arg0 )
				f17_arg0.LineTopLeft:beginAnimation( 100 )
				f17_arg0.LineTopLeft:setTopBottom( 0, 0, 0, 10 )
				f17_arg0.LineTopLeft:setAlpha( 0.08 )
				f17_arg0.LineTopLeft:registerEventHandler( "interrupted_keyframe", f17_arg0.clipInterrupted )
				f17_arg0.LineTopLeft:registerEventHandler( "transition_complete_keyframe", f17_arg0.clipFinished )
			end
			
			f17_arg0.LineTopLeft:completeAnimation()
			f17_arg0.LineTopLeft:setTopBottom( 0, 0, 0, 17 )
			f17_arg0.LineTopLeft:setAlpha( 0.15 )
			f17_local2( f17_arg0.LineTopLeft )
			local f17_local3 = function ( f21_arg0 )
				f17_arg0.LineTopRight:beginAnimation( 100 )
				f17_arg0.LineTopRight:setTopBottom( 0, 0, 0, 10 )
				f17_arg0.LineTopRight:setAlpha( 0.08 )
				f17_arg0.LineTopRight:registerEventHandler( "interrupted_keyframe", f17_arg0.clipInterrupted )
				f17_arg0.LineTopRight:registerEventHandler( "transition_complete_keyframe", f17_arg0.clipFinished )
			end
			
			f17_arg0.LineTopRight:completeAnimation()
			f17_arg0.LineTopRight:setTopBottom( 0, 0, 0, 17 )
			f17_arg0.LineTopRight:setAlpha( 0.15 )
			f17_local3( f17_arg0.LineTopRight )
			local f17_local4 = function ( f22_arg0 )
				f17_arg0.LineBtm:beginAnimation( 100 )
				f17_arg0.LineBtm:setAlpha( 0.08 )
				f17_arg0.LineBtm:registerEventHandler( "interrupted_keyframe", f17_arg0.clipInterrupted )
				f17_arg0.LineBtm:registerEventHandler( "transition_complete_keyframe", f17_arg0.clipFinished )
			end
			
			f17_arg0.LineBtm:completeAnimation()
			f17_arg0.LineBtm:setAlpha( 0.15 )
			f17_local4( f17_arg0.LineBtm )
			local f17_local5 = function ( f23_arg0 )
				f17_arg0.DotBR:beginAnimation( 100 )
				f17_arg0.DotBR:setAlpha( 0.8 )
				f17_arg0.DotBR:registerEventHandler( "interrupted_keyframe", f17_arg0.clipInterrupted )
				f17_arg0.DotBR:registerEventHandler( "transition_complete_keyframe", f17_arg0.clipFinished )
			end
			
			f17_arg0.DotBR:completeAnimation()
			f17_arg0.DotBR:setAlpha( 1 )
			f17_local5( f17_arg0.DotBR )
			local f17_local6 = function ( f24_arg0 )
				f17_arg0.DotBL:beginAnimation( 100 )
				f17_arg0.DotBL:setAlpha( 0.8 )
				f17_arg0.DotBL:registerEventHandler( "interrupted_keyframe", f17_arg0.clipInterrupted )
				f17_arg0.DotBL:registerEventHandler( "transition_complete_keyframe", f17_arg0.clipFinished )
			end
			
			f17_arg0.DotBL:completeAnimation()
			f17_arg0.DotBL:setAlpha( 1 )
			f17_local6( f17_arg0.DotBL )
			local f17_local7 = function ( f25_arg0 )
				f17_arg0.DotTR:beginAnimation( 100 )
				f17_arg0.DotTR:setTopBottom( 0, 0, 14, 15 )
				f17_arg0.DotTR:registerEventHandler( "interrupted_keyframe", f17_arg0.clipInterrupted )
				f17_arg0.DotTR:registerEventHandler( "transition_complete_keyframe", f17_arg0.clipFinished )
			end
			
			f17_arg0.DotTR:completeAnimation()
			f17_arg0.DotTR:setTopBottom( 0, 0, 21, 22 )
			f17_local7( f17_arg0.DotTR )
			local f17_local8 = function ( f26_arg0 )
				f17_arg0.DotTL:beginAnimation( 100 )
				f17_arg0.DotTL:setTopBottom( 0, 0, 14, 15 )
				f17_arg0.DotTL:registerEventHandler( "interrupted_keyframe", f17_arg0.clipInterrupted )
				f17_arg0.DotTL:registerEventHandler( "transition_complete_keyframe", f17_arg0.clipFinished )
			end
			
			f17_arg0.DotTL:completeAnimation()
			f17_arg0.DotTL:setTopBottom( 0, 0, 21, 22 )
			f17_local8( f17_arg0.DotTL )
			f17_arg0.ButtonTitle:completeAnimation()
			f17_arg0.ButtonTitle:setAlpha( 1 )
			f17_arg0.ButtonTitle:playClip( "DefaultClip" )
			f17_arg0.clipFinished( f17_arg0.ButtonTitle )
		end
	},
	Disabled = {
		DefaultClip = function ( f27_arg0, f27_arg1 )
			f27_arg0:__resetProperties()
			f27_arg0:setupElementClipCounter( 10 )
			f27_arg0.ButtonBG:completeAnimation()
			f27_arg0.ButtonBG:setRGB( 0.09, 0.09, 0.09 )
			f27_arg0.clipFinished( f27_arg0.ButtonBG )
			f27_arg0.LineTop:completeAnimation()
			f27_arg0.LineTop:setAlpha( 0.02 )
			f27_arg0.clipFinished( f27_arg0.LineTop )
			f27_arg0.LineTopLeft:completeAnimation()
			f27_arg0.LineTopLeft:setAlpha( 0.02 )
			f27_arg0.clipFinished( f27_arg0.LineTopLeft )
			f27_arg0.LineTopRight:completeAnimation()
			f27_arg0.LineTopRight:setAlpha( 0.02 )
			f27_arg0.clipFinished( f27_arg0.LineTopRight )
			f27_arg0.LineBtm:completeAnimation()
			f27_arg0.LineBtm:setAlpha( 0.02 )
			f27_arg0.clipFinished( f27_arg0.LineBtm )
			f27_arg0.DotBR:completeAnimation()
			f27_arg0.DotBR:setAlpha( 0.3 )
			f27_arg0.clipFinished( f27_arg0.DotBR )
			f27_arg0.DotBL:completeAnimation()
			f27_arg0.DotBL:setAlpha( 0.3 )
			f27_arg0.clipFinished( f27_arg0.DotBL )
			f27_arg0.DotTR:completeAnimation()
			f27_arg0.DotTR:setAlpha( 0.3 )
			f27_arg0.clipFinished( f27_arg0.DotTR )
			f27_arg0.DotTL:completeAnimation()
			f27_arg0.DotTL:setAlpha( 0.3 )
			f27_arg0.clipFinished( f27_arg0.DotTL )
			f27_arg0.ButtonTitle:completeAnimation()
			f27_arg0.ButtonTitle:setAlpha( 0.03 )
			f27_arg0.ButtonTitle:playClip( "Disabled" )
			f27_arg0.clipFinished( f27_arg0.ButtonTitle )
		end
	},
	InSale = {
		DefaultClip = function ( f28_arg0, f28_arg1 )
			f28_arg0:__resetProperties()
			f28_arg0:setupElementClipCounter( 0 )
		end,
		Focus = function ( f29_arg0, f29_arg1 )
			f29_arg0:__resetProperties()
			f29_arg0:setupElementClipCounter( 10 )
			f29_arg0.ButtonBG:completeAnimation()
			f29_arg0.ButtonBG:setRGB( 0.16, 0.16, 0.16 )
			f29_arg0.clipFinished( f29_arg0.ButtonBG )
			f29_arg0.LineTop:completeAnimation()
			f29_arg0.LineTop:setAlpha( 0.15 )
			f29_arg0.clipFinished( f29_arg0.LineTop )
			f29_arg0.LineTopLeft:completeAnimation()
			f29_arg0.LineTopLeft:setTopBottom( 0, 0, 0, 17 )
			f29_arg0.LineTopLeft:setAlpha( 0.15 )
			f29_arg0.clipFinished( f29_arg0.LineTopLeft )
			f29_arg0.LineTopRight:completeAnimation()
			f29_arg0.LineTopRight:setTopBottom( 0, 0, 0, 17 )
			f29_arg0.LineTopRight:setAlpha( 0.15 )
			f29_arg0.clipFinished( f29_arg0.LineTopRight )
			f29_arg0.LineBtm:completeAnimation()
			f29_arg0.LineBtm:setAlpha( 0.15 )
			f29_arg0.clipFinished( f29_arg0.LineBtm )
			f29_arg0.DotBR:completeAnimation()
			f29_arg0.DotBR:setAlpha( 1 )
			f29_arg0.clipFinished( f29_arg0.DotBR )
			f29_arg0.DotBL:completeAnimation()
			f29_arg0.DotBL:setAlpha( 1 )
			f29_arg0.clipFinished( f29_arg0.DotBL )
			f29_arg0.DotTR:completeAnimation()
			f29_arg0.DotTR:setTopBottom( 0, 0, 21, 22 )
			f29_arg0.clipFinished( f29_arg0.DotTR )
			f29_arg0.DotTL:completeAnimation()
			f29_arg0.DotTL:setTopBottom( 0, 0, 21, 22 )
			f29_arg0.clipFinished( f29_arg0.DotTL )
			f29_arg0.ButtonTitle:completeAnimation()
			f29_arg0.ButtonTitle:setAlpha( 1 )
			f29_arg0.ButtonTitle:playClip( "DefaultClip" )
			f29_arg0.clipFinished( f29_arg0.ButtonTitle )
		end,
		GainFocus = function ( f30_arg0, f30_arg1 )
			f30_arg0:__resetProperties()
			f30_arg0:setupElementClipCounter( 10 )
			local f30_local0 = function ( f31_arg0 )
				f30_arg0.ButtonBG:beginAnimation( 100 )
				f30_arg0.ButtonBG:setRGB( 0.16, 0.16, 0.16 )
				f30_arg0.ButtonBG:registerEventHandler( "interrupted_keyframe", f30_arg0.clipInterrupted )
				f30_arg0.ButtonBG:registerEventHandler( "transition_complete_keyframe", f30_arg0.clipFinished )
			end
			
			f30_arg0.ButtonBG:completeAnimation()
			f30_arg0.ButtonBG:setRGB( 0.12, 0.12, 0.12 )
			f30_local0( f30_arg0.ButtonBG )
			local f30_local1 = function ( f32_arg0 )
				f30_arg0.LineTop:beginAnimation( 100 )
				f30_arg0.LineTop:setAlpha( 0.15 )
				f30_arg0.LineTop:registerEventHandler( "interrupted_keyframe", f30_arg0.clipInterrupted )
				f30_arg0.LineTop:registerEventHandler( "transition_complete_keyframe", f30_arg0.clipFinished )
			end
			
			f30_arg0.LineTop:completeAnimation()
			f30_arg0.LineTop:setAlpha( 0.08 )
			f30_local1( f30_arg0.LineTop )
			local f30_local2 = function ( f33_arg0 )
				f30_arg0.LineTopLeft:beginAnimation( 100 )
				f30_arg0.LineTopLeft:setTopBottom( 0, 0, 0, 17 )
				f30_arg0.LineTopLeft:setAlpha( 0.15 )
				f30_arg0.LineTopLeft:registerEventHandler( "interrupted_keyframe", f30_arg0.clipInterrupted )
				f30_arg0.LineTopLeft:registerEventHandler( "transition_complete_keyframe", f30_arg0.clipFinished )
			end
			
			f30_arg0.LineTopLeft:completeAnimation()
			f30_arg0.LineTopLeft:setTopBottom( 0, 0, 0, 10 )
			f30_arg0.LineTopLeft:setAlpha( 0.08 )
			f30_local2( f30_arg0.LineTopLeft )
			local f30_local3 = function ( f34_arg0 )
				f30_arg0.LineTopRight:beginAnimation( 100 )
				f30_arg0.LineTopRight:setTopBottom( 0, 0, 0, 17 )
				f30_arg0.LineTopRight:setAlpha( 0.15 )
				f30_arg0.LineTopRight:registerEventHandler( "interrupted_keyframe", f30_arg0.clipInterrupted )
				f30_arg0.LineTopRight:registerEventHandler( "transition_complete_keyframe", f30_arg0.clipFinished )
			end
			
			f30_arg0.LineTopRight:completeAnimation()
			f30_arg0.LineTopRight:setTopBottom( 0, 0, 0, 10 )
			f30_arg0.LineTopRight:setAlpha( 0.08 )
			f30_local3( f30_arg0.LineTopRight )
			local f30_local4 = function ( f35_arg0 )
				f30_arg0.LineBtm:beginAnimation( 100 )
				f30_arg0.LineBtm:setAlpha( 0.15 )
				f30_arg0.LineBtm:registerEventHandler( "interrupted_keyframe", f30_arg0.clipInterrupted )
				f30_arg0.LineBtm:registerEventHandler( "transition_complete_keyframe", f30_arg0.clipFinished )
			end
			
			f30_arg0.LineBtm:completeAnimation()
			f30_arg0.LineBtm:setAlpha( 0.08 )
			f30_local4( f30_arg0.LineBtm )
			local f30_local5 = function ( f36_arg0 )
				f30_arg0.DotBR:beginAnimation( 100 )
				f30_arg0.DotBR:setAlpha( 1 )
				f30_arg0.DotBR:registerEventHandler( "interrupted_keyframe", f30_arg0.clipInterrupted )
				f30_arg0.DotBR:registerEventHandler( "transition_complete_keyframe", f30_arg0.clipFinished )
			end
			
			f30_arg0.DotBR:completeAnimation()
			f30_arg0.DotBR:setAlpha( 0.8 )
			f30_local5( f30_arg0.DotBR )
			local f30_local6 = function ( f37_arg0 )
				f30_arg0.DotBL:beginAnimation( 100 )
				f30_arg0.DotBL:setAlpha( 1 )
				f30_arg0.DotBL:registerEventHandler( "interrupted_keyframe", f30_arg0.clipInterrupted )
				f30_arg0.DotBL:registerEventHandler( "transition_complete_keyframe", f30_arg0.clipFinished )
			end
			
			f30_arg0.DotBL:completeAnimation()
			f30_arg0.DotBL:setAlpha( 0.8 )
			f30_local6( f30_arg0.DotBL )
			local f30_local7 = function ( f38_arg0 )
				f30_arg0.DotTR:beginAnimation( 100 )
				f30_arg0.DotTR:setTopBottom( 0, 0, 21, 22 )
				f30_arg0.DotTR:registerEventHandler( "interrupted_keyframe", f30_arg0.clipInterrupted )
				f30_arg0.DotTR:registerEventHandler( "transition_complete_keyframe", f30_arg0.clipFinished )
			end
			
			f30_arg0.DotTR:completeAnimation()
			f30_arg0.DotTR:setTopBottom( 0, 0, 14, 15 )
			f30_local7( f30_arg0.DotTR )
			local f30_local8 = function ( f39_arg0 )
				f30_arg0.DotTL:beginAnimation( 100 )
				f30_arg0.DotTL:setTopBottom( 0, 0, 21, 22 )
				f30_arg0.DotTL:registerEventHandler( "interrupted_keyframe", f30_arg0.clipInterrupted )
				f30_arg0.DotTL:registerEventHandler( "transition_complete_keyframe", f30_arg0.clipFinished )
			end
			
			f30_arg0.DotTL:completeAnimation()
			f30_arg0.DotTL:setTopBottom( 0, 0, 14, 15 )
			f30_local8( f30_arg0.DotTL )
			f30_arg0.ButtonTitle:completeAnimation()
			f30_arg0.ButtonTitle:setAlpha( 1 )
			f30_arg0.ButtonTitle:playClip( "DefaultClip" )
			f30_arg0.clipFinished( f30_arg0.ButtonTitle )
		end,
		LoseFocus = function ( f40_arg0, f40_arg1 )
			f40_arg0:__resetProperties()
			f40_arg0:setupElementClipCounter( 10 )
			local f40_local0 = function ( f41_arg0 )
				f40_arg0.ButtonBG:beginAnimation( 100 )
				f40_arg0.ButtonBG:setRGB( 0.12, 0.12, 0.12 )
				f40_arg0.ButtonBG:registerEventHandler( "interrupted_keyframe", f40_arg0.clipInterrupted )
				f40_arg0.ButtonBG:registerEventHandler( "transition_complete_keyframe", f40_arg0.clipFinished )
			end
			
			f40_arg0.ButtonBG:completeAnimation()
			f40_arg0.ButtonBG:setRGB( 0.16, 0.16, 0.16 )
			f40_local0( f40_arg0.ButtonBG )
			local f40_local1 = function ( f42_arg0 )
				f40_arg0.LineTop:beginAnimation( 100 )
				f40_arg0.LineTop:setAlpha( 0.08 )
				f40_arg0.LineTop:registerEventHandler( "interrupted_keyframe", f40_arg0.clipInterrupted )
				f40_arg0.LineTop:registerEventHandler( "transition_complete_keyframe", f40_arg0.clipFinished )
			end
			
			f40_arg0.LineTop:completeAnimation()
			f40_arg0.LineTop:setAlpha( 0.15 )
			f40_local1( f40_arg0.LineTop )
			local f40_local2 = function ( f43_arg0 )
				f40_arg0.LineTopLeft:beginAnimation( 100 )
				f40_arg0.LineTopLeft:setTopBottom( 0, 0, 0, 10 )
				f40_arg0.LineTopLeft:setAlpha( 0.08 )
				f40_arg0.LineTopLeft:registerEventHandler( "interrupted_keyframe", f40_arg0.clipInterrupted )
				f40_arg0.LineTopLeft:registerEventHandler( "transition_complete_keyframe", f40_arg0.clipFinished )
			end
			
			f40_arg0.LineTopLeft:completeAnimation()
			f40_arg0.LineTopLeft:setTopBottom( 0, 0, 0, 17 )
			f40_arg0.LineTopLeft:setAlpha( 0.15 )
			f40_local2( f40_arg0.LineTopLeft )
			local f40_local3 = function ( f44_arg0 )
				f40_arg0.LineTopRight:beginAnimation( 100 )
				f40_arg0.LineTopRight:setTopBottom( 0, 0, 0, 10 )
				f40_arg0.LineTopRight:setAlpha( 0.08 )
				f40_arg0.LineTopRight:registerEventHandler( "interrupted_keyframe", f40_arg0.clipInterrupted )
				f40_arg0.LineTopRight:registerEventHandler( "transition_complete_keyframe", f40_arg0.clipFinished )
			end
			
			f40_arg0.LineTopRight:completeAnimation()
			f40_arg0.LineTopRight:setTopBottom( 0, 0, 0, 17 )
			f40_arg0.LineTopRight:setAlpha( 0.15 )
			f40_local3( f40_arg0.LineTopRight )
			local f40_local4 = function ( f45_arg0 )
				f40_arg0.LineBtm:beginAnimation( 100 )
				f40_arg0.LineBtm:setAlpha( 0.08 )
				f40_arg0.LineBtm:registerEventHandler( "interrupted_keyframe", f40_arg0.clipInterrupted )
				f40_arg0.LineBtm:registerEventHandler( "transition_complete_keyframe", f40_arg0.clipFinished )
			end
			
			f40_arg0.LineBtm:completeAnimation()
			f40_arg0.LineBtm:setAlpha( 0.15 )
			f40_local4( f40_arg0.LineBtm )
			local f40_local5 = function ( f46_arg0 )
				f40_arg0.DotBR:beginAnimation( 100 )
				f40_arg0.DotBR:setAlpha( 0.8 )
				f40_arg0.DotBR:registerEventHandler( "interrupted_keyframe", f40_arg0.clipInterrupted )
				f40_arg0.DotBR:registerEventHandler( "transition_complete_keyframe", f40_arg0.clipFinished )
			end
			
			f40_arg0.DotBR:completeAnimation()
			f40_arg0.DotBR:setAlpha( 1 )
			f40_local5( f40_arg0.DotBR )
			local f40_local6 = function ( f47_arg0 )
				f40_arg0.DotBL:beginAnimation( 100 )
				f40_arg0.DotBL:setAlpha( 0.8 )
				f40_arg0.DotBL:registerEventHandler( "interrupted_keyframe", f40_arg0.clipInterrupted )
				f40_arg0.DotBL:registerEventHandler( "transition_complete_keyframe", f40_arg0.clipFinished )
			end
			
			f40_arg0.DotBL:completeAnimation()
			f40_arg0.DotBL:setAlpha( 1 )
			f40_local6( f40_arg0.DotBL )
			local f40_local7 = function ( f48_arg0 )
				f40_arg0.DotTR:beginAnimation( 100 )
				f40_arg0.DotTR:setTopBottom( 0, 0, 14, 15 )
				f40_arg0.DotTR:registerEventHandler( "interrupted_keyframe", f40_arg0.clipInterrupted )
				f40_arg0.DotTR:registerEventHandler( "transition_complete_keyframe", f40_arg0.clipFinished )
			end
			
			f40_arg0.DotTR:completeAnimation()
			f40_arg0.DotTR:setTopBottom( 0, 0, 21, 22 )
			f40_local7( f40_arg0.DotTR )
			local f40_local8 = function ( f49_arg0 )
				f40_arg0.DotTL:beginAnimation( 100 )
				f40_arg0.DotTL:setTopBottom( 0, 0, 14, 15 )
				f40_arg0.DotTL:registerEventHandler( "interrupted_keyframe", f40_arg0.clipInterrupted )
				f40_arg0.DotTL:registerEventHandler( "transition_complete_keyframe", f40_arg0.clipFinished )
			end
			
			f40_arg0.DotTL:completeAnimation()
			f40_arg0.DotTL:setTopBottom( 0, 0, 21, 22 )
			f40_local8( f40_arg0.DotTL )
			f40_arg0.ButtonTitle:completeAnimation()
			f40_arg0.ButtonTitle:setAlpha( 1 )
			f40_arg0.ButtonTitle:playClip( "DefaultClip" )
			f40_arg0.clipFinished( f40_arg0.ButtonTitle )
		end
	},
	Hidden = {
		DefaultClip = function ( f50_arg0, f50_arg1 )
			f50_arg0:__resetProperties()
			f50_arg0:setupElementClipCounter( 10 )
			f50_arg0.ButtonBG:completeAnimation()
			f50_arg0.ButtonBG:setAlpha( 0 )
			f50_arg0.clipFinished( f50_arg0.ButtonBG )
			f50_arg0.LineTop:completeAnimation()
			f50_arg0.LineTop:setAlpha( 0 )
			f50_arg0.clipFinished( f50_arg0.LineTop )
			f50_arg0.LineTopLeft:completeAnimation()
			f50_arg0.LineTopLeft:setAlpha( 0 )
			f50_arg0.clipFinished( f50_arg0.LineTopLeft )
			f50_arg0.LineTopRight:completeAnimation()
			f50_arg0.LineTopRight:setAlpha( 0 )
			f50_arg0.clipFinished( f50_arg0.LineTopRight )
			f50_arg0.LineBtm:completeAnimation()
			f50_arg0.LineBtm:setAlpha( 0 )
			f50_arg0.clipFinished( f50_arg0.LineBtm )
			f50_arg0.DotBR:completeAnimation()
			f50_arg0.DotBR:setAlpha( 0 )
			f50_arg0.clipFinished( f50_arg0.DotBR )
			f50_arg0.DotBL:completeAnimation()
			f50_arg0.DotBL:setAlpha( 0 )
			f50_arg0.clipFinished( f50_arg0.DotBL )
			f50_arg0.DotTR:completeAnimation()
			f50_arg0.DotTR:setAlpha( 0 )
			f50_arg0.clipFinished( f50_arg0.DotTR )
			f50_arg0.DotTL:completeAnimation()
			f50_arg0.DotTL:setAlpha( 0 )
			f50_arg0.clipFinished( f50_arg0.DotTL )
			f50_arg0.ButtonTitle:completeAnimation()
			f50_arg0.ButtonTitle:setAlpha( 0 )
			f50_arg0.clipFinished( f50_arg0.ButtonTitle )
		end
	}
}
CoD.PC_BnetStore_GiftButton.__onClose = function ( f51_arg0 )
	f51_arg0.ButtonTitle:close()
end

