require( "ui/uieditor/widgets/blackmarket/bm_lock" )
require( "ui/uieditor/widgets/cac/customizeclassadd" )
require( "ui/uieditor/widgets/cac/mark2bonusexpbadge" )
require( "ui/uieditor/widgets/cac/menuchooseclass/itemwidgets/itemhinttextbreadcrumb" )
require( "ui/uieditor/widgets/cac/restricteditemwarning" )
require( "ui/uieditor/widgets/cac/weaponvariants/weaponvariantpip" )
require( "ui/uieditor/widgets/commonbuttonoutline" )
require( "ui/uieditor/widgets/zmfrontend/armory/armory_attachmentpipcontainer" )

CoD.ZMAttachmentSlot = InheritFrom( LUI.UIElement )
CoD.ZMAttachmentSlot.__defaultWidth = 292
CoD.ZMAttachmentSlot.__defaultHeight = 146
CoD.ZMAttachmentSlot.new = function ( f1_arg0, f1_arg1, f1_arg2, f1_arg3, f1_arg4, f1_arg5, f1_arg6, f1_arg7, f1_arg8, f1_arg9 )
	local self = LUI.UIElement.new( f1_arg2, f1_arg3, f1_arg4, f1_arg5, f1_arg6, f1_arg7, f1_arg8, f1_arg9 )
	self:setClass( CoD.ZMAttachmentSlot )
	self.id = "ZMAttachmentSlot"
	self.soundSet = "FrontendMain"
	self.onlyChildrenFocusable = true
	self.anyChildUsesUpdateState = true
	f1_arg0:addElementToPendingUpdateStateList( self )
	
	local CustomizeClassAdd = CoD.CustomizeClassAdd.new( f1_arg0, f1_arg1, 0, 0, 0, 148, 0, 0, 0, 112 )
	CustomizeClassAdd:setAlpha( 0 )
	self:addElement( CustomizeClassAdd )
	self.CustomizeClassAdd = CustomizeClassAdd
	
	local backgroundBlurDisabled = LUI.UIImage.new( 0.21, 0.79, 0, 0, 0, 0, 28, 84 )
	backgroundBlurDisabled:setRGB( 0, 0, 0 )
	backgroundBlurDisabled:setAlpha( 0 )
	backgroundBlurDisabled:setMaterial( LUI.UIImage.GetCachedMaterial( 0xE2354BE557C4C7A ) )
	backgroundBlurDisabled:setShaderVector( 0, 0, 0, 0, 0 )
	self:addElement( backgroundBlurDisabled )
	self.backgroundBlurDisabled = backgroundBlurDisabled
	
	local backgroundBlur = LUI.UIImage.new( 0.04, 0.96, 0, 0, 0, 0, 7, 106 )
	backgroundBlur:setRGB( 0, 0, 0 )
	backgroundBlur:setAlpha( 0 )
	backgroundBlur:setZoom( 3 )
	backgroundBlur:setMaterial( LUI.UIImage.GetCachedMaterial( 0xE2354BE557C4C7A ) )
	backgroundBlur:setShaderVector( 0, 0, 0, 0, 0 )
	self:addElement( backgroundBlur )
	self.backgroundBlur = backgroundBlur
	
	local ButtonDisabled = LUI.UIImage.new( 0, 0, 29, 119, 0, 0, 25, 87 )
	ButtonDisabled:setAlpha( 0 )
	ButtonDisabled:setImage( RegisterImage( "uie_ui_menu_cac_attachment_button_disabled" ) )
	self:addElement( ButtonDisabled )
	self.ButtonDisabled = ButtonDisabled
	
	local Box = LUI.UIImage.new( 0, 0, 0, 292, 0, 0, 0, 148 )
	Box:setAlpha( 0.99 )
	Box:setImage( RegisterImage( "uie_ui_menu_zombies_cac_special_weapon_slot_box" ) )
	self:addElement( Box )
	self.Box = Box
	
	local Colorize = LUI.UIImage.new( 0, 0, 12, 280, 0, 0, 14, 133 )
	Colorize:setRGB( 1, 0, 0 )
	Colorize:setAlpha( 0 )
	self:addElement( Colorize )
	self.Colorize = Colorize
	
	local Brackets = LUI.UIImage.new( 0, 0, 0, 292, 0, 0, 0, 148 )
	Brackets:setRGB( ColorSet.T8__BEIGE__HEADER.r, ColorSet.T8__BEIGE__HEADER.g, ColorSet.T8__BEIGE__HEADER.b )
	Brackets:setAlpha( 0.5 )
	Brackets:setImage( RegisterImage( "uie_ui_menu_zombies_cac_special_weapon_slot_brackets" ) )
	self:addElement( Brackets )
	self.Brackets = Brackets
	
	local Brackets2 = LUI.UIImage.new( 0, 0, 0, 292, 0, 0, 0, 148 )
	Brackets2:setRGB( ColorSet.T8__BIEGE.r, ColorSet.T8__BIEGE.g, ColorSet.T8__BIEGE.b )
	Brackets2:setImage( RegisterImage( "uie_ui_menu_zombies_cac_special_weapon_slot_brackets" ) )
	Brackets2:setMaterial( LUI.UIImage.GetCachedMaterial( "uie_clock_normal" ) )
	Brackets2:setShaderVector( 0, 0.5, 0.5, 0, 0 )
	Brackets2:setShaderVector( 1, 0.5, 0, 0, 0 )
	Brackets2:setShaderVector( 2, 0.5, 0, 0, 0 )
	Brackets2:setShaderVector( 3, 0, 0, 0, 0 )
	Brackets2:setShaderVector( 4, 0, 0, 0, 0 )
	self:addElement( Brackets2 )
	self.Brackets2 = Brackets2
	
	local LightFocus = LUI.UIImage.new( 0, 0, 0, 292, 0, 0, 0, 148 )
	LightFocus:setRGB( 1, 0, 0 )
	LightFocus:setAlpha( 0 )
	LightFocus:setImage( RegisterImage( "uie_ui_menu_zombies_cac_special_weapon_slot_light_focus" ) )
	self:addElement( LightFocus )
	self.LightFocus = LightFocus
	
	local Dots = LUI.UIImage.new( 0, 0, 0, 292, 0, 0, 0, 148 )
	Dots:setRGB( 0.84, 0.1, 0.1 )
	Dots:setAlpha( 0.3 )
	Dots:setImage( RegisterImage( "uie_ui_menu_zombies_cac_special_weapon_slot_dots" ) )
	self:addElement( Dots )
	self.Dots = Dots
	
	local Outline = LUI.UIImage.new( 0, 0, 0, 292, 0, 0, 0, 148 )
	Outline:setRGB( 0.84, 0.1, 0.1 )
	Outline:setAlpha( 0 )
	Outline:setImage( RegisterImage( "uie_ui_menu_zombies_cac_special_weapon_slot_outline" ) )
	self:addElement( Outline )
	self.Outline = Outline
	
	local Corners = LUI.UIImage.new( 0, 0, 0, 292, 0, 0, 0, 148 )
	Corners:setRGB( 0.84, 0.1, 0.1 )
	Corners:setAlpha( 0 )
	Corners:setScale( 1, 0.99 )
	Corners:setImage( RegisterImage( "uie_ui_menu_zombies_cac_special_weapon_slot_corners" ) )
	self:addElement( Corners )
	self.Corners = Corners
	
	local EquippedMarkerTick = LUI.UIImage.new( 0, 0, 128, 288, 0, 0, -2, 158 )
	EquippedMarkerTick:setAlpha( 0 )
	EquippedMarkerTick:setZoom( 4 )
	EquippedMarkerTick:setImage( RegisterImage( "uie_ui_menu_zombies_cac_elixir_slot_check" ) )
	self:addElement( EquippedMarkerTick )
	self.EquippedMarkerTick = EquippedMarkerTick
	
	local AttachmentImage = LUI.UIFixedAspectRatioImage.new( 0.5, 0.5, -58, 58, 0.5, 0.5, -45, 22 )
	AttachmentImage:setZoom( 3 )
	self:addElement( AttachmentImage )
	self.AttachmentImage = AttachmentImage
	
	local ArmoryAttachmentPipContainer = CoD.Armory_AttachmentPipContainer.new( f1_arg0, f1_arg1, 0.5, 0.5, -43.5, 43.5, 0, 0, 13, 25 )
	ArmoryAttachmentPipContainer:mergeStateConditions( {
		{
			stateName = "FourSlotsHideOptic",
			condition = function ( menu, element, event )
				return AlwaysFalse()
			end
		},
		{
			stateName = "HideOptic",
			condition = function ( menu, element, event )
				return AlwaysFalse()
			end
		}
	} )
	ArmoryAttachmentPipContainer:linkToElementModel( ArmoryAttachmentPipContainer, "showAttachmentPips", true, function ( model )
		f1_arg0:updateElementState( ArmoryAttachmentPipContainer, {
			name = "model_validation",
			menu = f1_arg0,
			controller = f1_arg1,
			modelValue = model:get(),
			modelName = "showAttachmentPips"
		} )
	end )
	ArmoryAttachmentPipContainer:linkToElementModel( self, nil, false, function ( model )
		ArmoryAttachmentPipContainer:setModel( model, f1_arg1 )
	end )
	self:addElement( ArmoryAttachmentPipContainer )
	self.ArmoryAttachmentPipContainer = ArmoryAttachmentPipContainer
	
	local LockedIcon = LUI.UIImage.new( 0.5, 0.5, -24, 24, 0.5, 0.5, -39, 9 )
	LockedIcon:setAlpha( 0 )
	LockedIcon:setScale( 0.6, 0.6 )
	LockedIcon:setImage( RegisterImage( "uie_icon_locks_lock_01" ) )
	self:addElement( LockedIcon )
	self.LockedIcon = LockedIcon
	
	local BMLock = CoD.BM_Lock.new( f1_arg0, f1_arg1, 0.5, 0.5, -24, 24, 0.5, 0.5, -39, 9 )
	BMLock:setAlpha( 0 )
	BMLock:setScale( 0.6, 0.6 )
	self:addElement( BMLock )
	self.BMLock = BMLock
	
	local ItemHintTextBreadcrumb = CoD.ItemHintTextBreadcrumb.new( f1_arg0, f1_arg1, 0.5, 0.5, -146, 146, 1, 1, 20, 54 )
	ItemHintTextBreadcrumb:setAlpha( 0 )
	ItemHintTextBreadcrumb.textCenterAlign:setText( Engine[0xF9F1239CFD921FE]( 0xDEEE55C412CA473 ) )
	self:addElement( ItemHintTextBreadcrumb )
	self.ItemHintTextBreadcrumb = ItemHintTextBreadcrumb
	
	local AttachmentName = LUI.UIText.new( -0, 0.94, 14, 4, 1, 1, -32, -14 )
	AttachmentName:setRGB( ColorSet.T8__OFF__WHITE.r, ColorSet.T8__OFF__WHITE.g, ColorSet.T8__OFF__WHITE.b )
	AttachmentName:setText( LocalizeToUpperString( "null/empty" ) )
	AttachmentName:setTTF( "ttmussels_demibold" )
	AttachmentName:setLetterSpacing( 1 )
	AttachmentName:setAlignment( Enum.LUIAlignment[0xFEEB12BCB0D7041] )
	AttachmentName:setAlignment( Enum.LUIAlignment[0x70510683C22104B] )
	AttachmentName:setBackingType( 2 )
	AttachmentName:setBackingColor( 0.08, 0.08, 0.08 )
	AttachmentName:setBackingAlpha( 0.8 )
	AttachmentName:setBackingXPadding( 3 )
	self:addElement( AttachmentName )
	self.AttachmentName = AttachmentName
	
	local CommonButtonOutline = CoD.CommonButtonOutline.new( f1_arg0, f1_arg1, 0, 1, 7, -7, 0, 1, 10, -10 )
	CommonButtonOutline.Lines:setAlpha( 0 )
	CommonButtonOutline:linkToElementModel( self, nil, false, function ( model )
		CommonButtonOutline:setModel( model, f1_arg1 )
	end )
	self:addElement( CommonButtonOutline )
	self.CommonButtonOutline = CommonButtonOutline
	
	local RestrictionIcon = CoD.RestrictedItemWarning.new( f1_arg0, f1_arg1, 0.5, 0.5, -30, 30, 0.5, 0.5, -29, 21 )
	RestrictionIcon:linkToElementModel( self, nil, false, function ( model )
		RestrictionIcon:setModel( model, f1_arg1 )
	end )
	self:addElement( RestrictionIcon )
	self.RestrictionIcon = RestrictionIcon
	
	local SignatureBonusExp = CoD.Mark2BonusExpBadge.new( f1_arg0, f1_arg1, 0, 0, 16, 276, 0, 0, 96, 114 )
	SignatureBonusExp:linkToElementModel( self, nil, false, function ( model )
		SignatureBonusExp:setModel( model, f1_arg1 )
	end )
	self:addElement( SignatureBonusExp )
	self.SignatureBonusExp = SignatureBonusExp
	
	local VariantList = LUI.GridLayout.new( f1_arg0, f1_arg1, false, 0, 0, 5, 0, nil, nil, false, false, false, false )
	VariantList:setLeftRight( 0, 0, 6, 169 )
	VariantList:setTopBottom( 0, 0, 140, 156 )
	VariantList:setWidgetType( CoD.WeaponVariantPip )
	VariantList:setHorizontalCount( 8 )
	VariantList:setSpacing( 5 )
	VariantList:setAlignment( Enum.LUIAlignment[0x830CFD395E6AA0A] )
	VariantList:linkToElementModel( self, "variantList", true, function ( model )
		local f9_local0 = model:get()
		if f9_local0 ~= nil then
			VariantList:setDataSource( f9_local0 )
		end
	end )
	self:addElement( VariantList )
	self.VariantList = VariantList
	
	CommonButtonOutline.id = "CommonButtonOutline"
	VariantList.id = "VariantList"
	self.__defaultFocus = CommonButtonOutline
	LUI.OverrideFunction_CallOriginalSecond( self, "close", self.__onClose )
	
	if PostLoadFunc then
		PostLoadFunc( self, f1_arg1, f1_arg0 )
	end
	
	return self
end

CoD.ZMAttachmentSlot.__resetProperties = function ( f10_arg0 )
	f10_arg0.AttachmentImage:completeAnimation()
	f10_arg0.AttachmentName:completeAnimation()
	f10_arg0.Corners:completeAnimation()
	f10_arg0.CustomizeClassAdd:completeAnimation()
	f10_arg0.Dots:completeAnimation()
	f10_arg0.Outline:completeAnimation()
	f10_arg0.Brackets2:completeAnimation()
	f10_arg0.LightFocus:completeAnimation()
	f10_arg0.Colorize:completeAnimation()
	f10_arg0.ItemHintTextBreadcrumb:completeAnimation()
	f10_arg0.backgroundBlur:completeAnimation()
	f10_arg0.BMLock:completeAnimation()
	f10_arg0.VariantList:completeAnimation()
	f10_arg0.LockedIcon:completeAnimation()
	f10_arg0.EquippedMarkerTick:completeAnimation()
	f10_arg0.AttachmentImage:setRGB( 1, 1, 1 )
	f10_arg0.AttachmentImage:setAlpha( 1 )
	f10_arg0.AttachmentImage:setZoom( 3 )
	f10_arg0.AttachmentName:setRGB( ColorSet.T8__OFF__WHITE.r, ColorSet.T8__OFF__WHITE.g, ColorSet.T8__OFF__WHITE.b )
	f10_arg0.AttachmentName:setAlpha( 1 )
	f10_arg0.AttachmentName:setZoom( 0 )
	f10_arg0.Corners:setAlpha( 0 )
	f10_arg0.Corners:setScale( 1, 0.99 )
	f10_arg0.Dots:setRGB( 0.84, 0.1, 0.1 )
	f10_arg0.Dots:setAlpha( 0.3 )
	f10_arg0.Outline:setAlpha( 0 )
	f10_arg0.Brackets2:setMaterial( LUI.UIImage.GetCachedMaterial( "uie_clock_normal" ) )
	f10_arg0.Brackets2:setShaderVector( 0, 0.5, 0.5, 0, 0 )
	f10_arg0.Brackets2:setShaderVector( 1, 0.5, 0, 0, 0 )
	f10_arg0.Brackets2:setShaderVector( 2, 0.5, 0, 0, 0 )
	f10_arg0.Brackets2:setShaderVector( 3, 0, 0, 0, 0 )
	f10_arg0.Brackets2:setShaderVector( 4, 0, 0, 0, 0 )
	f10_arg0.LightFocus:setRGB( 1, 0, 0 )
	f10_arg0.LightFocus:setAlpha( 0 )
	f10_arg0.Colorize:setRGB( 1, 0, 0 )
	f10_arg0.Colorize:setAlpha( 0 )
	f10_arg0.ItemHintTextBreadcrumb:setAlpha( 0 )
	f10_arg0.backgroundBlur:setAlpha( 0 )
	f10_arg0.backgroundBlur:setZoom( 3 )
	f10_arg0.BMLock:setAlpha( 0 )
	f10_arg0.VariantList:setAlpha( 1 )
	f10_arg0.LockedIcon:setAlpha( 0 )
	f10_arg0.EquippedMarkerTick:setAlpha( 0 )
end

CoD.ZMAttachmentSlot.__clipsPerState = {
	DefaultState = {
		DefaultClip = function ( f11_arg0, f11_arg1 )
			f11_arg0:__resetProperties()
			f11_arg0:setupElementClipCounter( 3 )
			f11_arg0.Corners:completeAnimation()
			f11_arg0.Corners:setAlpha( 0 )
			f11_arg0.Corners:setScale( 1, 0.99 )
			f11_arg0.clipFinished( f11_arg0.Corners )
			f11_arg0.AttachmentImage:completeAnimation()
			f11_arg0.AttachmentImage:setAlpha( 1 )
			f11_arg0.clipFinished( f11_arg0.AttachmentImage )
			f11_arg0.AttachmentName:completeAnimation()
			f11_arg0.AttachmentName:setRGB( 0.58, 0.58, 0.58 )
			f11_arg0.clipFinished( f11_arg0.AttachmentName )
		end,
		ChildFocus = function ( f12_arg0, f12_arg1 )
			f12_arg0:__resetProperties()
			f12_arg0:setupElementClipCounter( 9 )
			f12_arg0.CustomizeClassAdd:completeAnimation()
			f12_arg0.CustomizeClassAdd:playClip( "ClassAddFocus" )
			f12_arg0.clipFinished( f12_arg0.CustomizeClassAdd )
			f12_arg0.Colorize:completeAnimation()
			f12_arg0.Colorize:setAlpha( 0.02 )
			f12_arg0.clipFinished( f12_arg0.Colorize )
			f12_arg0.Brackets2:completeAnimation()
			f12_arg0.Brackets2:setMaterial( LUI.UIImage.GetCachedMaterial( "uie_clock_normal" ) )
			f12_arg0.Brackets2:setShaderVector( 0, 1, 0, 0, 0 )
			f12_arg0.Brackets2:setShaderVector( 1, 0.5, 0, 0, 0 )
			f12_arg0.Brackets2:setShaderVector( 2, 0.5, 0, 0, 0 )
			f12_arg0.Brackets2:setShaderVector( 3, 0, 0, 0, 0 )
			f12_arg0.Brackets2:setShaderVector( 4, 0, 0, 0, 0 )
			f12_arg0.clipFinished( f12_arg0.Brackets2 )
			f12_arg0.LightFocus:completeAnimation()
			f12_arg0.LightFocus:setRGB( 1, 0, 0 )
			f12_arg0.LightFocus:setAlpha( 0.1 )
			f12_arg0.clipFinished( f12_arg0.LightFocus )
			f12_arg0.Dots:completeAnimation()
			f12_arg0.Dots:setRGB( 1, 0, 0 )
			f12_arg0.Dots:setAlpha( 1 )
			f12_arg0.clipFinished( f12_arg0.Dots )
			f12_arg0.Outline:completeAnimation()
			f12_arg0.Outline:setAlpha( 0.2 )
			f12_arg0.clipFinished( f12_arg0.Outline )
			f12_arg0.Corners:completeAnimation()
			f12_arg0.Corners:setAlpha( 1 )
			f12_arg0.Corners:setScale( 1, 1 )
			f12_arg0.clipFinished( f12_arg0.Corners )
			f12_arg0.ItemHintTextBreadcrumb:completeAnimation()
			f12_arg0.ItemHintTextBreadcrumb:setAlpha( 1 )
			f12_arg0.clipFinished( f12_arg0.ItemHintTextBreadcrumb )
			f12_arg0.AttachmentName:completeAnimation()
			f12_arg0.AttachmentName:setRGB( 1, 0, 0 )
			f12_arg0.clipFinished( f12_arg0.AttachmentName )
		end,
		GainChildFocus = function ( f13_arg0, f13_arg1 )
			f13_arg0:__resetProperties()
			f13_arg0:setupElementClipCounter( 10 )
			local f13_local0 = function ( f14_arg0 )
				f13_arg0.CustomizeClassAdd:playClip( "DefaultClip" )
				f13_arg0.CustomizeClassAdd:beginAnimation( 200 )
				f13_arg0.CustomizeClassAdd:registerEventHandler( "interrupted_keyframe", f13_arg0.clipInterrupted )
				f13_arg0.CustomizeClassAdd:registerEventHandler( "transition_complete_keyframe", function ( element, event )
					element:playClip( "ClassAddFocus" )
					f13_arg0.clipFinished( element, event )
				end )
			end
			
			f13_arg0.CustomizeClassAdd:completeAnimation()
			f13_local0( f13_arg0.CustomizeClassAdd )
			local f13_local1 = function ( f16_arg0 )
				f13_arg0.Colorize:beginAnimation( 200 )
				f13_arg0.Colorize:setAlpha( 0.02 )
				f13_arg0.Colorize:registerEventHandler( "interrupted_keyframe", f13_arg0.clipInterrupted )
				f13_arg0.Colorize:registerEventHandler( "transition_complete_keyframe", f13_arg0.clipFinished )
			end
			
			f13_arg0.Colorize:completeAnimation()
			f13_arg0.Colorize:setAlpha( 0 )
			f13_local1( f13_arg0.Colorize )
			local f13_local2 = function ( f17_arg0 )
				f13_arg0.Brackets2:beginAnimation( 200 )
				f13_arg0.Brackets2:setShaderVector( 0, 1, 0, 0, 0 )
				f13_arg0.Brackets2:registerEventHandler( "interrupted_keyframe", f13_arg0.clipInterrupted )
				f13_arg0.Brackets2:registerEventHandler( "transition_complete_keyframe", f13_arg0.clipFinished )
			end
			
			f13_arg0.Brackets2:completeAnimation()
			f13_arg0.Brackets2:setMaterial( LUI.UIImage.GetCachedMaterial( "uie_clock_normal" ) )
			f13_arg0.Brackets2:setShaderVector( 0, 0.5, 0.5, 0, 0 )
			f13_arg0.Brackets2:setShaderVector( 1, 0.5, 0, 0, 0 )
			f13_arg0.Brackets2:setShaderVector( 2, 0.5, 0, 0, 0 )
			f13_arg0.Brackets2:setShaderVector( 3, 0, 0, 0, 0 )
			f13_arg0.Brackets2:setShaderVector( 4, 0, 0, 0, 0 )
			f13_local2( f13_arg0.Brackets2 )
			local f13_local3 = function ( f18_arg0 )
				f13_arg0.LightFocus:beginAnimation( 200 )
				f13_arg0.LightFocus:setAlpha( 0.1 )
				f13_arg0.LightFocus:registerEventHandler( "interrupted_keyframe", f13_arg0.clipInterrupted )
				f13_arg0.LightFocus:registerEventHandler( "transition_complete_keyframe", f13_arg0.clipFinished )
			end
			
			f13_arg0.LightFocus:completeAnimation()
			f13_arg0.LightFocus:setAlpha( 0 )
			f13_local3( f13_arg0.LightFocus )
			local f13_local4 = function ( f19_arg0 )
				f13_arg0.Dots:beginAnimation( 200 )
				f13_arg0.Dots:setRGB( 1, 0, 0 )
				f13_arg0.Dots:setAlpha( 1 )
				f13_arg0.Dots:registerEventHandler( "interrupted_keyframe", f13_arg0.clipInterrupted )
				f13_arg0.Dots:registerEventHandler( "transition_complete_keyframe", f13_arg0.clipFinished )
			end
			
			f13_arg0.Dots:completeAnimation()
			f13_arg0.Dots:setRGB( 0.84, 0.1, 0.1 )
			f13_arg0.Dots:setAlpha( 0.3 )
			f13_local4( f13_arg0.Dots )
			local f13_local5 = function ( f20_arg0 )
				f13_arg0.Outline:beginAnimation( 200 )
				f13_arg0.Outline:setAlpha( 0.2 )
				f13_arg0.Outline:registerEventHandler( "interrupted_keyframe", f13_arg0.clipInterrupted )
				f13_arg0.Outline:registerEventHandler( "transition_complete_keyframe", f13_arg0.clipFinished )
			end
			
			f13_arg0.Outline:completeAnimation()
			f13_arg0.Outline:setAlpha( 0 )
			f13_local5( f13_arg0.Outline )
			local f13_local6 = function ( f21_arg0 )
				f13_arg0.Corners:beginAnimation( 200 )
				f13_arg0.Corners:setAlpha( 1 )
				f13_arg0.Corners:setScale( 1, 1 )
				f13_arg0.Corners:registerEventHandler( "interrupted_keyframe", f13_arg0.clipInterrupted )
				f13_arg0.Corners:registerEventHandler( "transition_complete_keyframe", f13_arg0.clipFinished )
			end
			
			f13_arg0.Corners:completeAnimation()
			f13_arg0.Corners:setAlpha( 0 )
			f13_arg0.Corners:setScale( 1, 0.99 )
			f13_local6( f13_arg0.Corners )
			f13_arg0.AttachmentImage:completeAnimation()
			f13_arg0.AttachmentImage:setAlpha( 1 )
			f13_arg0.clipFinished( f13_arg0.AttachmentImage )
			local f13_local7 = function ( f22_arg0 )
				f13_arg0.ItemHintTextBreadcrumb:beginAnimation( 200 )
				f13_arg0.ItemHintTextBreadcrumb:setAlpha( 1 )
				f13_arg0.ItemHintTextBreadcrumb:registerEventHandler( "interrupted_keyframe", f13_arg0.clipInterrupted )
				f13_arg0.ItemHintTextBreadcrumb:registerEventHandler( "transition_complete_keyframe", f13_arg0.clipFinished )
			end
			
			f13_arg0.ItemHintTextBreadcrumb:completeAnimation()
			f13_arg0.ItemHintTextBreadcrumb:setAlpha( 0 )
			f13_local7( f13_arg0.ItemHintTextBreadcrumb )
			local f13_local8 = function ( f23_arg0 )
				f13_arg0.AttachmentName:beginAnimation( 200 )
				f13_arg0.AttachmentName:setRGB( 1, 0, 0 )
				f13_arg0.AttachmentName:registerEventHandler( "interrupted_keyframe", f13_arg0.clipInterrupted )
				f13_arg0.AttachmentName:registerEventHandler( "transition_complete_keyframe", f13_arg0.clipFinished )
			end
			
			f13_arg0.AttachmentName:completeAnimation()
			f13_arg0.AttachmentName:setRGB( 0.58, 0.58, 0.58 )
			f13_local8( f13_arg0.AttachmentName )
		end,
		LoseChildFocus = function ( f24_arg0, f24_arg1 )
			f24_arg0:__resetProperties()
			f24_arg0:setupElementClipCounter( 10 )
			local f24_local0 = function ( f25_arg0 )
				f24_arg0.CustomizeClassAdd:playClip( "ClassAddFocus" )
				f24_arg0.CustomizeClassAdd:beginAnimation( 200 )
				f24_arg0.CustomizeClassAdd:registerEventHandler( "interrupted_keyframe", f24_arg0.clipInterrupted )
				f24_arg0.CustomizeClassAdd:registerEventHandler( "transition_complete_keyframe", function ( element, event )
					element:playClip( "DefaultClip" )
					f24_arg0.clipFinished( element, event )
				end )
			end
			
			f24_arg0.CustomizeClassAdd:completeAnimation()
			f24_local0( f24_arg0.CustomizeClassAdd )
			local f24_local1 = function ( f27_arg0 )
				f24_arg0.Colorize:beginAnimation( 200 )
				f24_arg0.Colorize:setAlpha( 0 )
				f24_arg0.Colorize:registerEventHandler( "interrupted_keyframe", f24_arg0.clipInterrupted )
				f24_arg0.Colorize:registerEventHandler( "transition_complete_keyframe", f24_arg0.clipFinished )
			end
			
			f24_arg0.Colorize:completeAnimation()
			f24_arg0.Colorize:setAlpha( 0.02 )
			f24_local1( f24_arg0.Colorize )
			local f24_local2 = function ( f28_arg0 )
				f24_arg0.Brackets2:beginAnimation( 200 )
				f24_arg0.Brackets2:setShaderVector( 0, 0.5, 0.5, 0, 0 )
				f24_arg0.Brackets2:registerEventHandler( "interrupted_keyframe", f24_arg0.clipInterrupted )
				f24_arg0.Brackets2:registerEventHandler( "transition_complete_keyframe", f24_arg0.clipFinished )
			end
			
			f24_arg0.Brackets2:completeAnimation()
			f24_arg0.Brackets2:setMaterial( LUI.UIImage.GetCachedMaterial( "uie_clock_normal" ) )
			f24_arg0.Brackets2:setShaderVector( 0, 1, 0, 0, 0 )
			f24_arg0.Brackets2:setShaderVector( 1, 0.5, 0, 0, 0 )
			f24_arg0.Brackets2:setShaderVector( 2, 0.5, 0, 0, 0 )
			f24_arg0.Brackets2:setShaderVector( 3, 0, 0, 0, 0 )
			f24_arg0.Brackets2:setShaderVector( 4, 0, 0, 0, 0 )
			f24_local2( f24_arg0.Brackets2 )
			local f24_local3 = function ( f29_arg0 )
				f24_arg0.LightFocus:beginAnimation( 200 )
				f24_arg0.LightFocus:setAlpha( 0 )
				f24_arg0.LightFocus:registerEventHandler( "interrupted_keyframe", f24_arg0.clipInterrupted )
				f24_arg0.LightFocus:registerEventHandler( "transition_complete_keyframe", f24_arg0.clipFinished )
			end
			
			f24_arg0.LightFocus:completeAnimation()
			f24_arg0.LightFocus:setAlpha( 0.1 )
			f24_local3( f24_arg0.LightFocus )
			local f24_local4 = function ( f30_arg0 )
				f24_arg0.Dots:beginAnimation( 200 )
				f24_arg0.Dots:setRGB( 0.84, 0.1, 0.1 )
				f24_arg0.Dots:setAlpha( 0.3 )
				f24_arg0.Dots:registerEventHandler( "interrupted_keyframe", f24_arg0.clipInterrupted )
				f24_arg0.Dots:registerEventHandler( "transition_complete_keyframe", f24_arg0.clipFinished )
			end
			
			f24_arg0.Dots:completeAnimation()
			f24_arg0.Dots:setRGB( 1, 0, 0 )
			f24_arg0.Dots:setAlpha( 1 )
			f24_local4( f24_arg0.Dots )
			local f24_local5 = function ( f31_arg0 )
				f24_arg0.Outline:beginAnimation( 200 )
				f24_arg0.Outline:setAlpha( 0 )
				f24_arg0.Outline:registerEventHandler( "interrupted_keyframe", f24_arg0.clipInterrupted )
				f24_arg0.Outline:registerEventHandler( "transition_complete_keyframe", f24_arg0.clipFinished )
			end
			
			f24_arg0.Outline:completeAnimation()
			f24_arg0.Outline:setAlpha( 0.2 )
			f24_local5( f24_arg0.Outline )
			local f24_local6 = function ( f32_arg0 )
				f24_arg0.Corners:beginAnimation( 200 )
				f24_arg0.Corners:setAlpha( 0 )
				f24_arg0.Corners:setScale( 1, 0.99 )
				f24_arg0.Corners:registerEventHandler( "interrupted_keyframe", f24_arg0.clipInterrupted )
				f24_arg0.Corners:registerEventHandler( "transition_complete_keyframe", f24_arg0.clipFinished )
			end
			
			f24_arg0.Corners:completeAnimation()
			f24_arg0.Corners:setAlpha( 1 )
			f24_arg0.Corners:setScale( 1, 1 )
			f24_local6( f24_arg0.Corners )
			f24_arg0.AttachmentImage:completeAnimation()
			f24_arg0.AttachmentImage:setAlpha( 1 )
			f24_arg0.clipFinished( f24_arg0.AttachmentImage )
			local f24_local7 = function ( f33_arg0 )
				f24_arg0.ItemHintTextBreadcrumb:beginAnimation( 200 )
				f24_arg0.ItemHintTextBreadcrumb:setAlpha( 0 )
				f24_arg0.ItemHintTextBreadcrumb:registerEventHandler( "interrupted_keyframe", f24_arg0.clipInterrupted )
				f24_arg0.ItemHintTextBreadcrumb:registerEventHandler( "transition_complete_keyframe", f24_arg0.clipFinished )
			end
			
			f24_arg0.ItemHintTextBreadcrumb:completeAnimation()
			f24_arg0.ItemHintTextBreadcrumb:setAlpha( 1 )
			f24_local7( f24_arg0.ItemHintTextBreadcrumb )
			local f24_local8 = function ( f34_arg0 )
				f24_arg0.AttachmentName:beginAnimation( 200 )
				f24_arg0.AttachmentName:setRGB( 0.58, 0.58, 0.58 )
				f24_arg0.AttachmentName:registerEventHandler( "interrupted_keyframe", f24_arg0.clipInterrupted )
				f24_arg0.AttachmentName:registerEventHandler( "transition_complete_keyframe", f24_arg0.clipFinished )
			end
			
			f24_arg0.AttachmentName:completeAnimation()
			f24_arg0.AttachmentName:setRGB( 1, 0, 0 )
			f24_local8( f24_arg0.AttachmentName )
		end
	},
	LootNotOwned = {
		DefaultClip = function ( f35_arg0, f35_arg1 )
			f35_arg0:__resetProperties()
			f35_arg0:setupElementClipCounter( 4 )
			f35_arg0.backgroundBlur:completeAnimation()
			f35_arg0.backgroundBlur:setAlpha( 0 )
			f35_arg0.clipFinished( f35_arg0.backgroundBlur )
			f35_arg0.AttachmentImage:completeAnimation()
			f35_arg0.AttachmentImage:setRGB( 0.39, 0.39, 0.39 )
			f35_arg0.AttachmentImage:setAlpha( 0 )
			f35_arg0.AttachmentImage:setZoom( 5 )
			f35_arg0.clipFinished( f35_arg0.AttachmentImage )
			f35_arg0.BMLock:completeAnimation()
			f35_arg0.BMLock:setAlpha( 0.02 )
			f35_arg0.clipFinished( f35_arg0.BMLock )
			f35_arg0.VariantList:completeAnimation()
			f35_arg0.VariantList:setAlpha( 0 )
			f35_arg0.clipFinished( f35_arg0.VariantList )
		end,
		ChildFocus = function ( f36_arg0, f36_arg1 )
			f36_arg0:__resetProperties()
			f36_arg0:setupElementClipCounter( 4 )
			f36_arg0.backgroundBlur:completeAnimation()
			f36_arg0.backgroundBlur:setAlpha( 0 )
			f36_arg0.clipFinished( f36_arg0.backgroundBlur )
			f36_arg0.AttachmentImage:completeAnimation()
			f36_arg0.AttachmentImage:setRGB( 0.39, 0.39, 0.39 )
			f36_arg0.AttachmentImage:setAlpha( 0 )
			f36_arg0.AttachmentImage:setZoom( 5 )
			f36_arg0.clipFinished( f36_arg0.AttachmentImage )
			local f36_local0 = function ( f37_arg0 )
				f36_arg0.BMLock:beginAnimation( 200 )
				f36_arg0.BMLock:setAlpha( 0.1 )
				f36_arg0.BMLock:registerEventHandler( "interrupted_keyframe", f36_arg0.clipInterrupted )
				f36_arg0.BMLock:registerEventHandler( "transition_complete_keyframe", f36_arg0.clipFinished )
			end
			
			f36_arg0.BMLock:completeAnimation()
			f36_arg0.BMLock:setAlpha( 0.02 )
			f36_local0( f36_arg0.BMLock )
			f36_arg0.VariantList:completeAnimation()
			f36_arg0.VariantList:setAlpha( 0 )
			f36_arg0.clipFinished( f36_arg0.VariantList )
		end,
		LoseChildFocus = function ( f38_arg0, f38_arg1 )
			f38_arg0:__resetProperties()
			f38_arg0:setupElementClipCounter( 4 )
			f38_arg0.backgroundBlur:completeAnimation()
			f38_arg0.backgroundBlur:setAlpha( 0 )
			f38_arg0.clipFinished( f38_arg0.backgroundBlur )
			f38_arg0.AttachmentImage:completeAnimation()
			f38_arg0.AttachmentImage:setRGB( 0.39, 0.39, 0.39 )
			f38_arg0.AttachmentImage:setAlpha( 0 )
			f38_arg0.AttachmentImage:setZoom( 5 )
			f38_arg0.clipFinished( f38_arg0.AttachmentImage )
			local f38_local0 = function ( f39_arg0 )
				f38_arg0.BMLock:beginAnimation( 200 )
				f38_arg0.BMLock:setAlpha( 0.02 )
				f38_arg0.BMLock:registerEventHandler( "interrupted_keyframe", f38_arg0.clipInterrupted )
				f38_arg0.BMLock:registerEventHandler( "transition_complete_keyframe", f38_arg0.clipFinished )
			end
			
			f38_arg0.BMLock:completeAnimation()
			f38_arg0.BMLock:setAlpha( 0.1 )
			f38_local0( f38_arg0.BMLock )
			f38_arg0.VariantList:completeAnimation()
			f38_arg0.VariantList:setAlpha( 0 )
			f38_arg0.clipFinished( f38_arg0.VariantList )
		end,
		GainChildFocus = function ( f40_arg0, f40_arg1 )
			f40_arg0:__resetProperties()
			f40_arg0:setupElementClipCounter( 4 )
			f40_arg0.backgroundBlur:completeAnimation()
			f40_arg0.backgroundBlur:setAlpha( 0 )
			f40_arg0.clipFinished( f40_arg0.backgroundBlur )
			f40_arg0.AttachmentImage:completeAnimation()
			f40_arg0.AttachmentImage:setRGB( 0.39, 0.39, 0.39 )
			f40_arg0.AttachmentImage:setAlpha( 0 )
			f40_arg0.AttachmentImage:setZoom( 5 )
			f40_arg0.clipFinished( f40_arg0.AttachmentImage )
			f40_arg0.BMLock:completeAnimation()
			f40_arg0.BMLock:setAlpha( 0.02 )
			f40_arg0.clipFinished( f40_arg0.BMLock )
			f40_arg0.VariantList:completeAnimation()
			f40_arg0.VariantList:setAlpha( 0 )
			f40_arg0.clipFinished( f40_arg0.VariantList )
		end
	},
	NotAvailable = {
		DefaultClip = function ( f41_arg0, f41_arg1 )
			f41_arg0:__resetProperties()
			f41_arg0:setupElementClipCounter( 4 )
			f41_arg0.backgroundBlur:completeAnimation()
			f41_arg0.backgroundBlur:setZoom( 5 )
			f41_arg0.clipFinished( f41_arg0.backgroundBlur )
			f41_arg0.AttachmentImage:completeAnimation()
			f41_arg0.AttachmentImage:setRGB( 0.59, 0.59, 0.59 )
			f41_arg0.AttachmentImage:setAlpha( 0.5 )
			f41_arg0.AttachmentImage:setZoom( 5 )
			f41_arg0.clipFinished( f41_arg0.AttachmentImage )
			f41_arg0.AttachmentName:completeAnimation()
			f41_arg0.AttachmentName:setRGB( 0.39, 0.39, 0.39 )
			f41_arg0.AttachmentName:setAlpha( 0.5 )
			f41_arg0.AttachmentName:setZoom( 5 )
			f41_arg0.clipFinished( f41_arg0.AttachmentName )
			f41_arg0.VariantList:completeAnimation()
			f41_arg0.VariantList:setAlpha( 0 )
			f41_arg0.clipFinished( f41_arg0.VariantList )
		end,
		ChildFocus = function ( f42_arg0, f42_arg1 )
			f42_arg0:__resetProperties()
			f42_arg0:setupElementClipCounter( 4 )
			f42_arg0.backgroundBlur:completeAnimation()
			f42_arg0.backgroundBlur:setZoom( 5 )
			f42_arg0.clipFinished( f42_arg0.backgroundBlur )
			f42_arg0.AttachmentImage:completeAnimation()
			f42_arg0.AttachmentImage:setRGB( 0.59, 0.59, 0.59 )
			f42_arg0.AttachmentImage:setAlpha( 0.5 )
			f42_arg0.AttachmentImage:setZoom( 5 )
			f42_arg0.clipFinished( f42_arg0.AttachmentImage )
			f42_arg0.AttachmentName:completeAnimation()
			f42_arg0.AttachmentName:setRGB( 0.39, 0.39, 0.39 )
			f42_arg0.AttachmentName:setAlpha( 0.5 )
			f42_arg0.AttachmentName:setZoom( 5 )
			f42_arg0.clipFinished( f42_arg0.AttachmentName )
			f42_arg0.VariantList:completeAnimation()
			f42_arg0.VariantList:setAlpha( 0 )
			f42_arg0.clipFinished( f42_arg0.VariantList )
		end
	},
	Locked = {
		DefaultClip = function ( f43_arg0, f43_arg1 )
			f43_arg0:__resetProperties()
			f43_arg0:setupElementClipCounter( 4 )
			f43_arg0.backgroundBlur:completeAnimation()
			f43_arg0.backgroundBlur:setAlpha( 0 )
			f43_arg0.clipFinished( f43_arg0.backgroundBlur )
			f43_arg0.AttachmentImage:completeAnimation()
			f43_arg0.AttachmentImage:setRGB( 0.39, 0.39, 0.39 )
			f43_arg0.AttachmentImage:setAlpha( 0 )
			f43_arg0.AttachmentImage:setZoom( 5 )
			f43_arg0.clipFinished( f43_arg0.AttachmentImage )
			f43_arg0.LockedIcon:completeAnimation()
			f43_arg0.LockedIcon:setAlpha( 0.02 )
			f43_arg0.clipFinished( f43_arg0.LockedIcon )
			f43_arg0.VariantList:completeAnimation()
			f43_arg0.VariantList:setAlpha( 0 )
			f43_arg0.clipFinished( f43_arg0.VariantList )
		end,
		ChildFocus = function ( f44_arg0, f44_arg1 )
			f44_arg0:__resetProperties()
			f44_arg0:setupElementClipCounter( 4 )
			f44_arg0.backgroundBlur:completeAnimation()
			f44_arg0.backgroundBlur:setAlpha( 0 )
			f44_arg0.clipFinished( f44_arg0.backgroundBlur )
			f44_arg0.AttachmentImage:completeAnimation()
			f44_arg0.AttachmentImage:setRGB( 0.39, 0.39, 0.39 )
			f44_arg0.AttachmentImage:setAlpha( 0 )
			f44_arg0.AttachmentImage:setZoom( 5 )
			f44_arg0.clipFinished( f44_arg0.AttachmentImage )
			local f44_local0 = function ( f45_arg0 )
				f44_arg0.LockedIcon:beginAnimation( 200 )
				f44_arg0.LockedIcon:setAlpha( 0.1 )
				f44_arg0.LockedIcon:registerEventHandler( "interrupted_keyframe", f44_arg0.clipInterrupted )
				f44_arg0.LockedIcon:registerEventHandler( "transition_complete_keyframe", f44_arg0.clipFinished )
			end
			
			f44_arg0.LockedIcon:completeAnimation()
			f44_arg0.LockedIcon:setAlpha( 0.02 )
			f44_local0( f44_arg0.LockedIcon )
			f44_arg0.VariantList:completeAnimation()
			f44_arg0.VariantList:setAlpha( 0 )
			f44_arg0.clipFinished( f44_arg0.VariantList )
		end,
		LoseChildFocus = function ( f46_arg0, f46_arg1 )
			f46_arg0:__resetProperties()
			f46_arg0:setupElementClipCounter( 4 )
			f46_arg0.backgroundBlur:completeAnimation()
			f46_arg0.backgroundBlur:setAlpha( 0 )
			f46_arg0.clipFinished( f46_arg0.backgroundBlur )
			f46_arg0.AttachmentImage:completeAnimation()
			f46_arg0.AttachmentImage:setRGB( 0.39, 0.39, 0.39 )
			f46_arg0.AttachmentImage:setAlpha( 0 )
			f46_arg0.AttachmentImage:setZoom( 5 )
			f46_arg0.clipFinished( f46_arg0.AttachmentImage )
			local f46_local0 = function ( f47_arg0 )
				f46_arg0.LockedIcon:beginAnimation( 200 )
				f46_arg0.LockedIcon:setAlpha( 0.02 )
				f46_arg0.LockedIcon:registerEventHandler( "interrupted_keyframe", f46_arg0.clipInterrupted )
				f46_arg0.LockedIcon:registerEventHandler( "transition_complete_keyframe", f46_arg0.clipFinished )
			end
			
			f46_arg0.LockedIcon:completeAnimation()
			f46_arg0.LockedIcon:setAlpha( 0.1 )
			f46_local0( f46_arg0.LockedIcon )
			f46_arg0.VariantList:completeAnimation()
			f46_arg0.VariantList:setAlpha( 0 )
			f46_arg0.clipFinished( f46_arg0.VariantList )
		end,
		GainChildFocus = function ( f48_arg0, f48_arg1 )
			f48_arg0:__resetProperties()
			f48_arg0:setupElementClipCounter( 4 )
			f48_arg0.backgroundBlur:completeAnimation()
			f48_arg0.backgroundBlur:setAlpha( 0 )
			f48_arg0.clipFinished( f48_arg0.backgroundBlur )
			f48_arg0.AttachmentImage:completeAnimation()
			f48_arg0.AttachmentImage:setRGB( 0.39, 0.39, 0.39 )
			f48_arg0.AttachmentImage:setAlpha( 0 )
			f48_arg0.AttachmentImage:setZoom( 5 )
			f48_arg0.clipFinished( f48_arg0.AttachmentImage )
			f48_arg0.LockedIcon:completeAnimation()
			f48_arg0.LockedIcon:setAlpha( 0.02 )
			f48_arg0.clipFinished( f48_arg0.LockedIcon )
			f48_arg0.VariantList:completeAnimation()
			f48_arg0.VariantList:setAlpha( 0 )
			f48_arg0.clipFinished( f48_arg0.VariantList )
		end
	},
	Equipped = {
		DefaultClip = function ( f49_arg0, f49_arg1 )
			f49_arg0:__resetProperties()
			f49_arg0:setupElementClipCounter( 5 )
			f49_arg0.Colorize:completeAnimation()
			f49_arg0.Colorize:setRGB( ColorSet.T8__BIEGE.r, ColorSet.T8__BIEGE.g, ColorSet.T8__BIEGE.b )
			f49_arg0.Colorize:setAlpha( 0.02 )
			f49_arg0.clipFinished( f49_arg0.Colorize )
			f49_arg0.Brackets2:completeAnimation()
			f49_arg0.Brackets2:setMaterial( LUI.UIImage.GetCachedMaterial( "uie_clock_normal" ) )
			f49_arg0.Brackets2:setShaderVector( 0, 1, 0, 0, 0 )
			f49_arg0.Brackets2:setShaderVector( 1, 0.5, 0, 0, 0 )
			f49_arg0.Brackets2:setShaderVector( 2, 0.5, 0, 0, 0 )
			f49_arg0.Brackets2:setShaderVector( 3, 0, 0, 0, 0 )
			f49_arg0.Brackets2:setShaderVector( 4, 0, 0, 0, 0 )
			f49_arg0.clipFinished( f49_arg0.Brackets2 )
			f49_arg0.LightFocus:completeAnimation()
			f49_arg0.LightFocus:setRGB( ColorSet.T8__BIEGE.r, ColorSet.T8__BIEGE.g, ColorSet.T8__BIEGE.b )
			f49_arg0.LightFocus:setAlpha( 0.2 )
			f49_arg0.clipFinished( f49_arg0.LightFocus )
			f49_arg0.EquippedMarkerTick:completeAnimation()
			f49_arg0.EquippedMarkerTick:setAlpha( 1 )
			f49_arg0.clipFinished( f49_arg0.EquippedMarkerTick )
			f49_arg0.AttachmentName:completeAnimation()
			f49_arg0.AttachmentName:setRGB( 1, 1, 1 )
			f49_arg0.clipFinished( f49_arg0.AttachmentName )
		end,
		ChildFocus = function ( f50_arg0, f50_arg1 )
			f50_arg0:__resetProperties()
			f50_arg0:setupElementClipCounter( 9 )
			f50_arg0.CustomizeClassAdd:completeAnimation()
			f50_arg0.CustomizeClassAdd:playClip( "DefaultClip" )
			f50_arg0.clipFinished( f50_arg0.CustomizeClassAdd )
			f50_arg0.Colorize:completeAnimation()
			f50_arg0.Colorize:setAlpha( 0.02 )
			f50_arg0.clipFinished( f50_arg0.Colorize )
			f50_arg0.Brackets2:completeAnimation()
			f50_arg0.Brackets2:setMaterial( LUI.UIImage.GetCachedMaterial( "uie_clock_normal" ) )
			f50_arg0.Brackets2:setShaderVector( 0, 1, 0, 0, 0 )
			f50_arg0.Brackets2:setShaderVector( 1, 0.5, 0, 0, 0 )
			f50_arg0.Brackets2:setShaderVector( 2, 0.5, 0, 0, 0 )
			f50_arg0.Brackets2:setShaderVector( 3, 0, 0, 0, 0 )
			f50_arg0.Brackets2:setShaderVector( 4, 0, 0, 0, 0 )
			f50_arg0.clipFinished( f50_arg0.Brackets2 )
			f50_arg0.LightFocus:completeAnimation()
			f50_arg0.LightFocus:setAlpha( 0.2 )
			f50_arg0.clipFinished( f50_arg0.LightFocus )
			f50_arg0.Dots:completeAnimation()
			f50_arg0.Dots:setAlpha( 1 )
			f50_arg0.clipFinished( f50_arg0.Dots )
			f50_arg0.Outline:completeAnimation()
			f50_arg0.Outline:setAlpha( 0.2 )
			f50_arg0.clipFinished( f50_arg0.Outline )
			f50_arg0.Corners:completeAnimation()
			f50_arg0.Corners:setAlpha( 1 )
			f50_arg0.Corners:setScale( 1, 1 )
			f50_arg0.clipFinished( f50_arg0.Corners )
			f50_arg0.EquippedMarkerTick:completeAnimation()
			f50_arg0.EquippedMarkerTick:setAlpha( 1 )
			f50_arg0.clipFinished( f50_arg0.EquippedMarkerTick )
			f50_arg0.AttachmentName:completeAnimation()
			f50_arg0.AttachmentName:setRGB( 1, 0, 0 )
			f50_arg0.clipFinished( f50_arg0.AttachmentName )
		end,
		GainChildFocus = function ( f51_arg0, f51_arg1 )
			f51_arg0:__resetProperties()
			f51_arg0:setupElementClipCounter( 10 )
			f51_arg0.CustomizeClassAdd:completeAnimation()
			f51_arg0.CustomizeClassAdd:playClip( "DefaultClip" )
			f51_arg0.clipFinished( f51_arg0.CustomizeClassAdd )
			local f51_local0 = function ( f52_arg0 )
				f51_arg0.Colorize:beginAnimation( 200 )
				f51_arg0.Colorize:setRGB( 1, 0, 0 )
				f51_arg0.Colorize:registerEventHandler( "interrupted_keyframe", f51_arg0.clipInterrupted )
				f51_arg0.Colorize:registerEventHandler( "transition_complete_keyframe", f51_arg0.clipFinished )
			end
			
			f51_arg0.Colorize:completeAnimation()
			f51_arg0.Colorize:setRGB( ColorSet.T8__BIEGE.r, ColorSet.T8__BIEGE.g, ColorSet.T8__BIEGE.b )
			f51_arg0.Colorize:setAlpha( 0.02 )
			f51_local0( f51_arg0.Colorize )
			f51_arg0.Brackets2:completeAnimation()
			f51_arg0.Brackets2:setMaterial( LUI.UIImage.GetCachedMaterial( "uie_clock_normal" ) )
			f51_arg0.Brackets2:setShaderVector( 0, 1, 0, 0, 0 )
			f51_arg0.Brackets2:setShaderVector( 1, 0.5, 0, 0, 0 )
			f51_arg0.Brackets2:setShaderVector( 2, 0.5, 0, 0, 0 )
			f51_arg0.Brackets2:setShaderVector( 3, 0, 0, 0, 0 )
			f51_arg0.Brackets2:setShaderVector( 4, 0, 0, 0, 0 )
			f51_arg0.clipFinished( f51_arg0.Brackets2 )
			local f51_local1 = function ( f53_arg0 )
				f51_arg0.LightFocus:beginAnimation( 200 )
				f51_arg0.LightFocus:setRGB( 1, 0, 0 )
				f51_arg0.LightFocus:registerEventHandler( "interrupted_keyframe", f51_arg0.clipInterrupted )
				f51_arg0.LightFocus:registerEventHandler( "transition_complete_keyframe", f51_arg0.clipFinished )
			end
			
			f51_arg0.LightFocus:completeAnimation()
			f51_arg0.LightFocus:setRGB( ColorSet.T8__BIEGE.r, ColorSet.T8__BIEGE.g, ColorSet.T8__BIEGE.b )
			f51_arg0.LightFocus:setAlpha( 0.2 )
			f51_local1( f51_arg0.LightFocus )
			local f51_local2 = function ( f54_arg0 )
				f51_arg0.Dots:beginAnimation( 200 )
				f51_arg0.Dots:setAlpha( 1 )
				f51_arg0.Dots:registerEventHandler( "interrupted_keyframe", f51_arg0.clipInterrupted )
				f51_arg0.Dots:registerEventHandler( "transition_complete_keyframe", f51_arg0.clipFinished )
			end
			
			f51_arg0.Dots:completeAnimation()
			f51_arg0.Dots:setAlpha( 0.3 )
			f51_local2( f51_arg0.Dots )
			local f51_local3 = function ( f55_arg0 )
				f51_arg0.Outline:beginAnimation( 200 )
				f51_arg0.Outline:setAlpha( 0.2 )
				f51_arg0.Outline:registerEventHandler( "interrupted_keyframe", f51_arg0.clipInterrupted )
				f51_arg0.Outline:registerEventHandler( "transition_complete_keyframe", f51_arg0.clipFinished )
			end
			
			f51_arg0.Outline:completeAnimation()
			f51_arg0.Outline:setAlpha( 0 )
			f51_local3( f51_arg0.Outline )
			local f51_local4 = function ( f56_arg0 )
				f51_arg0.Corners:beginAnimation( 200 )
				f51_arg0.Corners:setAlpha( 1 )
				f51_arg0.Corners:setScale( 1, 1 )
				f51_arg0.Corners:registerEventHandler( "interrupted_keyframe", f51_arg0.clipInterrupted )
				f51_arg0.Corners:registerEventHandler( "transition_complete_keyframe", f51_arg0.clipFinished )
			end
			
			f51_arg0.Corners:completeAnimation()
			f51_arg0.Corners:setAlpha( 0 )
			f51_arg0.Corners:setScale( 1, 0.99 )
			f51_local4( f51_arg0.Corners )
			f51_arg0.EquippedMarkerTick:completeAnimation()
			f51_arg0.EquippedMarkerTick:setAlpha( 1 )
			f51_arg0.clipFinished( f51_arg0.EquippedMarkerTick )
			local f51_local5 = function ( f57_arg0 )
				f51_arg0.ItemHintTextBreadcrumb:beginAnimation( 200 )
				f51_arg0.ItemHintTextBreadcrumb:registerEventHandler( "interrupted_keyframe", f51_arg0.clipInterrupted )
				f51_arg0.ItemHintTextBreadcrumb:registerEventHandler( "transition_complete_keyframe", f51_arg0.clipFinished )
			end
			
			f51_arg0.ItemHintTextBreadcrumb:completeAnimation()
			f51_arg0.ItemHintTextBreadcrumb:setAlpha( 1 )
			f51_local5( f51_arg0.ItemHintTextBreadcrumb )
			local f51_local6 = function ( f58_arg0 )
				f51_arg0.AttachmentName:beginAnimation( 200 )
				f51_arg0.AttachmentName:setRGB( 1, 0, 0 )
				f51_arg0.AttachmentName:registerEventHandler( "interrupted_keyframe", f51_arg0.clipInterrupted )
				f51_arg0.AttachmentName:registerEventHandler( "transition_complete_keyframe", f51_arg0.clipFinished )
			end
			
			f51_arg0.AttachmentName:completeAnimation()
			f51_arg0.AttachmentName:setRGB( 1, 1, 1 )
			f51_local6( f51_arg0.AttachmentName )
		end,
		LoseChildFocus = function ( f59_arg0, f59_arg1 )
			f59_arg0:__resetProperties()
			f59_arg0:setupElementClipCounter( 10 )
			f59_arg0.CustomizeClassAdd:completeAnimation()
			f59_arg0.CustomizeClassAdd:playClip( "DefaultClip" )
			f59_arg0.clipFinished( f59_arg0.CustomizeClassAdd )
			local f59_local0 = function ( f60_arg0 )
				f59_arg0.Colorize:beginAnimation( 200 )
				f59_arg0.Colorize:setRGB( ColorSet.T8__BIEGE.r, ColorSet.T8__BIEGE.g, ColorSet.T8__BIEGE.b )
				f59_arg0.Colorize:registerEventHandler( "interrupted_keyframe", f59_arg0.clipInterrupted )
				f59_arg0.Colorize:registerEventHandler( "transition_complete_keyframe", f59_arg0.clipFinished )
			end
			
			f59_arg0.Colorize:completeAnimation()
			f59_arg0.Colorize:setRGB( 1, 0, 0 )
			f59_arg0.Colorize:setAlpha( 0.02 )
			f59_local0( f59_arg0.Colorize )
			f59_arg0.Brackets2:completeAnimation()
			f59_arg0.Brackets2:setMaterial( LUI.UIImage.GetCachedMaterial( "uie_clock_normal" ) )
			f59_arg0.Brackets2:setShaderVector( 0, 1, 0, 0, 0 )
			f59_arg0.Brackets2:setShaderVector( 1, 0.5, 0, 0, 0 )
			f59_arg0.Brackets2:setShaderVector( 2, 0.5, 0, 0, 0 )
			f59_arg0.Brackets2:setShaderVector( 3, 0, 0, 0, 0 )
			f59_arg0.Brackets2:setShaderVector( 4, 0, 0, 0, 0 )
			f59_arg0.clipFinished( f59_arg0.Brackets2 )
			local f59_local1 = function ( f61_arg0 )
				f59_arg0.LightFocus:beginAnimation( 200 )
				f59_arg0.LightFocus:setRGB( ColorSet.T8__BIEGE.r, ColorSet.T8__BIEGE.g, ColorSet.T8__BIEGE.b )
				f59_arg0.LightFocus:registerEventHandler( "interrupted_keyframe", f59_arg0.clipInterrupted )
				f59_arg0.LightFocus:registerEventHandler( "transition_complete_keyframe", f59_arg0.clipFinished )
			end
			
			f59_arg0.LightFocus:completeAnimation()
			f59_arg0.LightFocus:setRGB( 1, 0, 0 )
			f59_arg0.LightFocus:setAlpha( 0.2 )
			f59_local1( f59_arg0.LightFocus )
			local f59_local2 = function ( f62_arg0 )
				f59_arg0.Dots:beginAnimation( 200 )
				f59_arg0.Dots:setAlpha( 0.3 )
				f59_arg0.Dots:registerEventHandler( "interrupted_keyframe", f59_arg0.clipInterrupted )
				f59_arg0.Dots:registerEventHandler( "transition_complete_keyframe", f59_arg0.clipFinished )
			end
			
			f59_arg0.Dots:completeAnimation()
			f59_arg0.Dots:setAlpha( 1 )
			f59_local2( f59_arg0.Dots )
			local f59_local3 = function ( f63_arg0 )
				f59_arg0.Outline:beginAnimation( 200 )
				f59_arg0.Outline:setAlpha( 0 )
				f59_arg0.Outline:registerEventHandler( "interrupted_keyframe", f59_arg0.clipInterrupted )
				f59_arg0.Outline:registerEventHandler( "transition_complete_keyframe", f59_arg0.clipFinished )
			end
			
			f59_arg0.Outline:completeAnimation()
			f59_arg0.Outline:setAlpha( 0.2 )
			f59_local3( f59_arg0.Outline )
			local f59_local4 = function ( f64_arg0 )
				f59_arg0.Corners:beginAnimation( 200 )
				f59_arg0.Corners:setAlpha( 0 )
				f59_arg0.Corners:setScale( 1, 0.99 )
				f59_arg0.Corners:registerEventHandler( "interrupted_keyframe", f59_arg0.clipInterrupted )
				f59_arg0.Corners:registerEventHandler( "transition_complete_keyframe", f59_arg0.clipFinished )
			end
			
			f59_arg0.Corners:completeAnimation()
			f59_arg0.Corners:setAlpha( 1 )
			f59_arg0.Corners:setScale( 1, 1 )
			f59_local4( f59_arg0.Corners )
			f59_arg0.EquippedMarkerTick:completeAnimation()
			f59_arg0.EquippedMarkerTick:setAlpha( 1 )
			f59_arg0.clipFinished( f59_arg0.EquippedMarkerTick )
			local f59_local5 = function ( f65_arg0 )
				f59_arg0.ItemHintTextBreadcrumb:beginAnimation( 200 )
				f59_arg0.ItemHintTextBreadcrumb:setAlpha( 0 )
				f59_arg0.ItemHintTextBreadcrumb:registerEventHandler( "interrupted_keyframe", f59_arg0.clipInterrupted )
				f59_arg0.ItemHintTextBreadcrumb:registerEventHandler( "transition_complete_keyframe", f59_arg0.clipFinished )
			end
			
			f59_arg0.ItemHintTextBreadcrumb:completeAnimation()
			f59_arg0.ItemHintTextBreadcrumb:setAlpha( 1 )
			f59_local5( f59_arg0.ItemHintTextBreadcrumb )
			local f59_local6 = function ( f66_arg0 )
				f59_arg0.AttachmentName:beginAnimation( 200 )
				f59_arg0.AttachmentName:setRGB( 1, 1, 1 )
				f59_arg0.AttachmentName:registerEventHandler( "interrupted_keyframe", f59_arg0.clipInterrupted )
				f59_arg0.AttachmentName:registerEventHandler( "transition_complete_keyframe", f59_arg0.clipFinished )
			end
			
			f59_arg0.AttachmentName:completeAnimation()
			f59_arg0.AttachmentName:setRGB( 1, 0, 0 )
			f59_local6( f59_arg0.AttachmentName )
		end
	}
}
CoD.ZMAttachmentSlot.__onClose = function ( f67_arg0 )
	f67_arg0.CustomizeClassAdd:close()
	f67_arg0.ArmoryAttachmentPipContainer:close()
	f67_arg0.BMLock:close()
	f67_arg0.ItemHintTextBreadcrumb:close()
	f67_arg0.CommonButtonOutline:close()
	f67_arg0.RestrictionIcon:close()
	f67_arg0.SignatureBonusExp:close()
	f67_arg0.VariantList:close()
end

