require( "ui/uieditor/widgets/cac/cac_lock" )
require( "ui/uieditor/widgets/commonbuttonoutline" )
require( "ui/uieditor/widgets/startmenu/startmenu_identity_subtitle" )
require( "ui/uieditor/widgets/startmenu/startmenu_imagecontainer" )
require( "ui/uieditor/widgets/store/storecommontextbacking" )

CoD.PC_StartMenu_Button_LG_Internal = InheritFrom( LUI.UIElement )
CoD.PC_StartMenu_Button_LG_Internal.__defaultWidth = 420
CoD.PC_StartMenu_Button_LG_Internal.__defaultHeight = 117
CoD.PC_StartMenu_Button_LG_Internal.new = function ( f1_arg0, f1_arg1, f1_arg2, f1_arg3, f1_arg4, f1_arg5, f1_arg6, f1_arg7, f1_arg8, f1_arg9 )
	local self = LUI.UIElement.new( f1_arg2, f1_arg3, f1_arg4, f1_arg5, f1_arg6, f1_arg7, f1_arg8, f1_arg9 )
	CoD.BaseUtility.InitControllerModel( f1_arg1, "clanTagText" )
	self:setClass( CoD.PC_StartMenu_Button_LG_Internal )
	self.id = "PC_StartMenu_Button_LG_Internal"
	self.soundSet = "default"
	self.onlyChildrenFocusable = true
	self.anyChildUsesUpdateState = true
	f1_arg0:addElementToPendingUpdateStateList( self )
	
	local Background = LUI.UIImage.new( 0, 1, 0, 0, 0, 1, 0, 0 )
	Background:setRGB( 0.92, 0.92, 0.92 )
	Background:setAlpha( 0.04 )
	self:addElement( Background )
	self.Background = Background
	
	local NoiseTiledBacking = LUI.UIImage.new( 0, 1, 0, 0, 0, 1, 0, 0 )
	NoiseTiledBacking:setAlpha( 0.5 )
	NoiseTiledBacking:setImage( RegisterImage( 0x34839E8065B1E53 ) )
	NoiseTiledBacking:setMaterial( LUI.UIImage.GetCachedMaterial( 0x6CBE95C250C6D15 ) )
	NoiseTiledBacking:setShaderVector( 0, 0, 0, 0, 0 )
	NoiseTiledBacking:setupNineSliceShader( 196, 88 )
	self:addElement( NoiseTiledBacking )
	self.NoiseTiledBacking = NoiseTiledBacking
	
	local NoiseTiledBackingAdd = LUI.UIImage.new( 0, 1, 0, 0, 0, 1, 0, 0 )
	NoiseTiledBackingAdd:setAlpha( 0.2 )
	NoiseTiledBackingAdd:setImage( RegisterImage( 0x34839E8065B1E53 ) )
	NoiseTiledBackingAdd:setMaterial( LUI.UIImage.GetCachedMaterial( 0x7C9C02F608D0A75 ) )
	NoiseTiledBackingAdd:setShaderVector( 0, 0, 0, 0, 0 )
	NoiseTiledBackingAdd:setupNineSliceShader( 196, 88 )
	self:addElement( NoiseTiledBackingAdd )
	self.NoiseTiledBackingAdd = NoiseTiledBackingAdd
	
	local ImageContainer = CoD.StartMenu_ImageContainer.new( f1_arg0, f1_arg1, 0, 1, 0, 0, 0, 1, 0, 0 )
	ImageContainer:setAlpha( 0 )
	self:addElement( ImageContainer )
	self.ImageContainer = ImageContainer
	
	local StartMenuButtonFrame = LUI.UIFrame.new( f1_arg0, f1_arg1, 0, 0, false )
	StartMenuButtonFrame:setLeftRight( 0, 1, 0, 0 )
	StartMenuButtonFrame:setTopBottom( 0, 1, 0, 0 )
	self:addElement( StartMenuButtonFrame )
	self.StartMenuButtonFrame = StartMenuButtonFrame
	
	local LockBackground = LUI.UIImage.new( 0, 1, 0, 0, 0, 1, 0, 0 )
	LockBackground:setRGB( 0, 0, 0 )
	LockBackground:setAlpha( 0 )
	self:addElement( LockBackground )
	self.LockBackground = LockBackground
	
	local DotTiledBacking = CoD.StoreCommonTextBacking.new( f1_arg0, f1_arg1, 0, 1, 0, 0, 0.5, 0.5, -26, 22 )
	DotTiledBacking:setAlpha( 0.2 )
	self:addElement( DotTiledBacking )
	self.DotTiledBacking = DotTiledBacking
	
	local TitleBgTexture = LUI.UIImage.new( 0, 1, 0, 0, 0.5, 0.5, -26.5, 22.5 )
	TitleBgTexture:setAlpha( 0.5 )
	TitleBgTexture:setImage( RegisterImage( 0x34839E8065B1E53 ) )
	TitleBgTexture:setMaterial( LUI.UIImage.GetCachedMaterial( 0x6CBE95C250C6D15 ) )
	TitleBgTexture:setShaderVector( 0, 0, 0, 0, 0 )
	TitleBgTexture:setupNineSliceShader( 196, 88 )
	self:addElement( TitleBgTexture )
	self.TitleBgTexture = TitleBgTexture
	
	local TitleBg = LUI.UIImage.new( 0, 1, 0, 0, 0.5, 0.5, -26.5, 22.5 )
	TitleBg:setRGB( 0, 0, 0 )
	TitleBg:setAlpha( 0.05 )
	self:addElement( TitleBg )
	self.TitleBg = TitleBg
	
	local lockedIcon = CoD.cac_lock.new( f1_arg0, f1_arg1, 0.5, 0.5, -24, 24, 0.5, 0.5, -26, 22 )
	lockedIcon:setScale( 1.5, 1.5 )
	lockedIcon.lockedIcon:setAlpha( 0.5 )
	self:addElement( lockedIcon )
	self.lockedIcon = lockedIcon
	
	local ButtonStateText = LUI.UIText.new( 0, 1, 0, 0, 0.5, 0.5, -18.5, 18.5 )
	ButtonStateText:setAlpha( 0.5 )
	ButtonStateText:setText( Engine[0xF9F1239CFD921FE]( 0x496C6F3083248E7 ) )
	ButtonStateText:setTTF( "ttmussels_regular" )
	ButtonStateText:setLetterSpacing( 4 )
	ButtonStateText:setAlignment( Enum.LUIAlignment[0xFEEB12BCB0D7041] )
	self:addElement( ButtonStateText )
	self.ButtonStateText = ButtonStateText
	
	local NameEntryBG = LUI.UIImage.new( 0.5, 0.5, -82.5, 82.5, 0.5, 0.5, -17, 33 )
	NameEntryBG:setRGB( 0.06, 0.06, 0.06 )
	NameEntryBG:setAlpha( 0.5 )
	self:addElement( NameEntryBG )
	self.NameEntryBG = NameEntryBG
	
	local NameEntryBorder = LUI.UIImage.new( 0.5, 0.5, -82.5, 82.5, 0.5, 0.5, -17, 33 )
	NameEntryBorder:setRGB( 0.57, 0.57, 0.57 )
	NameEntryBorder:setAlpha( 0 )
	NameEntryBorder:setImage( RegisterImage( 0xF1E3082B39E99BB ) )
	NameEntryBorder:setMaterial( LUI.UIImage.GetCachedMaterial( 0x44484DDFAF5C093 ) )
	NameEntryBorder:setShaderVector( 0, 0, 0, 0, 0 )
	NameEntryBorder:setupNineSliceShader( 6, 6 )
	self:addElement( NameEntryBorder )
	self.NameEntryBorder = NameEntryBorder
	
	local NameEntrySelected = LUI.UIImage.new( 0.5, 0.5, -82.5, 82.5, 0.5, 0.5, -19, 35 )
	NameEntrySelected:setAlpha( 0 )
	NameEntrySelected:setImage( RegisterImage( 0xCB07CCC28498CB2 ) )
	NameEntrySelected:setMaterial( LUI.UIImage.GetCachedMaterial( 0xFD777557404A7B3 ) )
	NameEntrySelected:setShaderVector( 0, 0, 0, 0, 0 )
	NameEntrySelected:setupNineSliceShader( 6, 6 )
	self:addElement( NameEntrySelected )
	self.NameEntrySelected = NameEntrySelected
	
	local ClanText = LUI.UIText.new( 0.5, 0.5, -79, 79, 0.5, 0.5, -21, 33 )
	ClanText:setTTF( "notosans_regular" )
	ClanText:setAlignment( Enum.LUIAlignment[0xFEEB12BCB0D7041] )
	ClanText:setAlignment( Enum.LUIAlignment[0xF41D595A2B0EDF3] )
	ClanText:subscribeToGlobalModel( f1_arg1, "PerController", "identityBadge.clantag", function ( model )
		local f2_local0 = model:get()
		if f2_local0 ~= nil then
			ClanText:setText( f2_local0 )
		end
	end )
	self:addElement( ClanText )
	self.ClanText = ClanText
	
	local TextBox = LUI.UIText.new( 0.5, 0.5, -79, 79, 0.5, 0.5, -21, 33 )
	TextBox:setAlpha( 0 )
	TextBox:setText( "" )
	TextBox:setTTF( "notosans_regular" )
	TextBox:setAlignment( Enum.LUIAlignment[0xFEEB12BCB0D7041] )
	self:addElement( TextBox )
	self.TextBox = TextBox
	
	local BracketL = LUI.UIFixedAspectRatioImage.new( 0.5, 0.5, -130, -30, 0.5, 0.5, -42, 58 )
	BracketL:setImage( RegisterImage( 0x8F14609D5578644 ) )
	BracketL:setMaterial( LUI.UIImage.GetCachedMaterial( 0xF755127C95CF5B6 ) )
	BracketL:setShaderVector( 0, 1, 0, 0, 0 )
	self:addElement( BracketL )
	self.BracketL = BracketL
	
	local BracketL2 = LUI.UIFixedAspectRatioImage.new( 0.5, 0.5, -130, -30, 0.5, 0.5, -42, 58 )
	BracketL2:setRGB( 1, 0.88, 0.71 )
	BracketL2:setImage( RegisterImage( 0x8F14609D5578644 ) )
	BracketL2:setMaterial( LUI.UIImage.GetCachedMaterial( 0x1CC85D0A86303B0 ) )
	BracketL2:setShaderVector( 0, 1.3, 0, 0, 0 )
	self:addElement( BracketL2 )
	self.BracketL2 = BracketL2
	
	local BracketR = LUI.UIFixedAspectRatioImage.new( 0.5, 0.5, 30, 130, 0.5, 0.5, -42, 58 )
	BracketR:setYRot( 180 )
	BracketR:setImage( RegisterImage( 0x8F14609D5578644 ) )
	BracketR:setMaterial( LUI.UIImage.GetCachedMaterial( 0xF755127C95CF5B6 ) )
	BracketR:setShaderVector( 0, 1, 0, 0, 0 )
	self:addElement( BracketR )
	self.BracketR = BracketR
	
	local BracketR2 = LUI.UIFixedAspectRatioImage.new( 0.5, 0.5, 30, 130, 0.5, 0.5, -42, 58 )
	BracketR2:setRGB( 1, 0.88, 0.71 )
	BracketR2:setYRot( 180 )
	BracketR2:setImage( RegisterImage( 0x8F14609D5578644 ) )
	BracketR2:setMaterial( LUI.UIImage.GetCachedMaterial( 0x1CC85D0A86303B0 ) )
	BracketR2:setShaderVector( 0, 1.3, 0, 0, 0 )
	self:addElement( BracketR2 )
	self.BracketR2 = BracketR2
	
	local ButtonTitle = CoD.StartMenu_Identity_SubTitle.new( f1_arg0, f1_arg1, 0, 1, 6, -6, 0, 0, 0.5, 39.5 )
	ButtonTitle:setRGB( 0.92, 0.92, 0.92 )
	ButtonTitle.SubtitleText:setText( LocalizeToUpperString( 0x87AD82563AAAC53 ) )
	self:addElement( ButtonTitle )
	self.ButtonTitle = ButtonTitle
	
	local ButtonOutline = CoD.CommonButtonOutline.new( f1_arg0, f1_arg1, 0, 1, 0, 0, 0, 1, 0, 0 )
	self:addElement( ButtonOutline )
	self.ButtonOutline = ButtonOutline
	
	self:mergeStateConditions( {
		{
			stateName = "Disabled",
			condition = function ( menu, element, event )
				return IsGameTrial()
			end
		}
	} )
	StartMenuButtonFrame.id = "StartMenuButtonFrame"
	ButtonOutline.id = "ButtonOutline"
	self.__defaultFocus = ButtonOutline
	LUI.OverrideFunction_CallOriginalSecond( self, "close", self.__onClose )
	if PreLoadFunc then
		PreLoadFunc( self, f1_arg1, f1_arg0 )
	end
	local f1_local23 = self
	if IsPC() and not IsGameTrial() then
		CoD.PCUtility.SetEditBoxMaxChar( self, 4 )
		CoD.PCUtility.SetEditBoxScrollingSteps( self, 5, 325, 60 )
		CoD.PCUtility.MakeEditBoxRealTime( self, "clanTagText" )
		CoD.PCUtility.SetupEditClanTagWithControllerModelAndCallback( self, f1_arg1, f1_arg0, "clanTagText" )
		SetElementProperty( self.ButtonOutline, "__giveInputFocusToParent", 1 )
	end
	DisableModelStringReplacement( TextBox )
	return self
end

CoD.PC_StartMenu_Button_LG_Internal.__resetProperties = function ( f4_arg0 )
	f4_arg0.lockedIcon:completeAnimation()
	f4_arg0.ImageContainer:completeAnimation()
	f4_arg0.LockBackground:completeAnimation()
	f4_arg0.ButtonStateText:completeAnimation()
	f4_arg0.TitleBgTexture:completeAnimation()
	f4_arg0.TitleBg:completeAnimation()
	f4_arg0.DotTiledBacking:completeAnimation()
	f4_arg0.BracketR:completeAnimation()
	f4_arg0.BracketL:completeAnimation()
	f4_arg0.NameEntryBG:completeAnimation()
	f4_arg0.BracketR2:completeAnimation()
	f4_arg0.BracketL2:completeAnimation()
	f4_arg0.TextBox:completeAnimation()
	f4_arg0.NoiseTiledBackingAdd:completeAnimation()
	f4_arg0.NameEntrySelected:completeAnimation()
	f4_arg0.NameEntryBorder:completeAnimation()
	f4_arg0.ClanText:completeAnimation()
	f4_arg0.lockedIcon:setAlpha( 1 )
	f4_arg0.ImageContainer.ImageContainer:setAlpha( 1 )
	f4_arg0.LockBackground:setAlpha( 0 )
	f4_arg0.ButtonStateText:setAlpha( 0.5 )
	f4_arg0.TitleBgTexture:setAlpha( 0.5 )
	f4_arg0.TitleBg:setAlpha( 0.05 )
	f4_arg0.DotTiledBacking:setAlpha( 0.2 )
	f4_arg0.BracketR:setLeftRight( 0.5, 0.5, 30, 130 )
	f4_arg0.BracketR:setAlpha( 1 )
	f4_arg0.BracketL:setLeftRight( 0.5, 0.5, -130, -30 )
	f4_arg0.BracketL:setAlpha( 1 )
	f4_arg0.NameEntryBG:setLeftRight( 0.5, 0.5, -82.5, 82.5 )
	f4_arg0.NameEntryBG:setAlpha( 0.5 )
	f4_arg0.BracketR2:setLeftRight( 0.5, 0.5, 30, 130 )
	f4_arg0.BracketR2:setAlpha( 1 )
	f4_arg0.BracketL2:setLeftRight( 0.5, 0.5, -130, -30 )
	f4_arg0.BracketL2:setRGB( 1, 0.88, 0.71 )
	f4_arg0.BracketL2:setAlpha( 1 )
	f4_arg0.TextBox:setAlpha( 0 )
	f4_arg0.NoiseTiledBackingAdd:setAlpha( 0.2 )
	f4_arg0.NameEntrySelected:setLeftRight( 0.5, 0.5, -82.5, 82.5 )
	f4_arg0.NameEntrySelected:setAlpha( 0 )
	f4_arg0.NameEntryBorder:setLeftRight( 0.5, 0.5, -82.5, 82.5 )
	f4_arg0.ClanText:setAlpha( 1 )
end

CoD.PC_StartMenu_Button_LG_Internal.__clipsPerState = {
	DefaultState = {
		DefaultClip = function ( f5_arg0, f5_arg1 )
			f5_arg0:__resetProperties()
			f5_arg0:setupElementClipCounter( 13 )
			f5_arg0.ImageContainer:completeAnimation()
			f5_arg0.ImageContainer.ImageContainer:completeAnimation()
			f5_arg0.ImageContainer.ImageContainer:setAlpha( 0.79 )
			f5_arg0.clipFinished( f5_arg0.ImageContainer )
			f5_arg0.LockBackground:completeAnimation()
			f5_arg0.LockBackground:setAlpha( 0.05 )
			f5_arg0.clipFinished( f5_arg0.LockBackground )
			f5_arg0.DotTiledBacking:completeAnimation()
			f5_arg0.DotTiledBacking:setAlpha( 0 )
			f5_arg0.clipFinished( f5_arg0.DotTiledBacking )
			f5_arg0.TitleBgTexture:completeAnimation()
			f5_arg0.TitleBgTexture:setAlpha( 0 )
			f5_arg0.clipFinished( f5_arg0.TitleBgTexture )
			f5_arg0.TitleBg:completeAnimation()
			f5_arg0.TitleBg:setAlpha( 0 )
			f5_arg0.clipFinished( f5_arg0.TitleBg )
			f5_arg0.lockedIcon:completeAnimation()
			f5_arg0.lockedIcon:setAlpha( 0 )
			f5_arg0.clipFinished( f5_arg0.lockedIcon )
			f5_arg0.ButtonStateText:completeAnimation()
			f5_arg0.ButtonStateText:setAlpha( 0 )
			f5_arg0.clipFinished( f5_arg0.ButtonStateText )
			f5_arg0.NameEntryBG:completeAnimation()
			f5_arg0.NameEntryBG:setAlpha( 0.5 )
			f5_arg0.clipFinished( f5_arg0.NameEntryBG )
			f5_arg0.TextBox:completeAnimation()
			f5_arg0.TextBox:setAlpha( 0 )
			f5_arg0.clipFinished( f5_arg0.TextBox )
			f5_arg0.BracketL:completeAnimation()
			f5_arg0.BracketL:setAlpha( 1 )
			f5_arg0.clipFinished( f5_arg0.BracketL )
			f5_arg0.BracketL2:completeAnimation()
			f5_arg0.BracketL2:setAlpha( 0 )
			f5_arg0.clipFinished( f5_arg0.BracketL2 )
			f5_arg0.BracketR:completeAnimation()
			f5_arg0.BracketR:setAlpha( 1 )
			f5_arg0.clipFinished( f5_arg0.BracketR )
			f5_arg0.BracketR2:completeAnimation()
			f5_arg0.BracketR2:setAlpha( 0 )
			f5_arg0.clipFinished( f5_arg0.BracketR2 )
		end,
		ChildFocus = function ( f6_arg0, f6_arg1 )
			f6_arg0:__resetProperties()
			f6_arg0:setupElementClipCounter( 13 )
			f6_arg0.NoiseTiledBackingAdd:completeAnimation()
			f6_arg0.NoiseTiledBackingAdd:setAlpha( 0.5 )
			f6_arg0.clipFinished( f6_arg0.NoiseTiledBackingAdd )
			f6_arg0.DotTiledBacking:completeAnimation()
			f6_arg0.DotTiledBacking:setAlpha( 0 )
			f6_arg0.clipFinished( f6_arg0.DotTiledBacking )
			f6_arg0.TitleBgTexture:completeAnimation()
			f6_arg0.TitleBgTexture:setAlpha( 0 )
			f6_arg0.clipFinished( f6_arg0.TitleBgTexture )
			f6_arg0.TitleBg:completeAnimation()
			f6_arg0.TitleBg:setAlpha( 0 )
			f6_arg0.clipFinished( f6_arg0.TitleBg )
			f6_arg0.lockedIcon:completeAnimation()
			f6_arg0.lockedIcon:setAlpha( 0 )
			f6_arg0.clipFinished( f6_arg0.lockedIcon )
			f6_arg0.ButtonStateText:completeAnimation()
			f6_arg0.ButtonStateText:setAlpha( 0 )
			f6_arg0.clipFinished( f6_arg0.ButtonStateText )
			f6_arg0.NameEntryBG:completeAnimation()
			f6_arg0.NameEntryBG:setLeftRight( 0.5, 0.5, -90, 90 )
			f6_arg0.NameEntryBG:setAlpha( 0.95 )
			f6_arg0.clipFinished( f6_arg0.NameEntryBG )
			f6_arg0.NameEntryBorder:completeAnimation()
			f6_arg0.NameEntryBorder:setLeftRight( 0.5, 0.5, -90, 90 )
			f6_arg0.clipFinished( f6_arg0.NameEntryBorder )
			f6_arg0.NameEntrySelected:completeAnimation()
			f6_arg0.NameEntrySelected:setLeftRight( 0.5, 0.5, -90, 90 )
			f6_arg0.clipFinished( f6_arg0.NameEntrySelected )
			f6_arg0.BracketL:completeAnimation()
			f6_arg0.BracketL:setLeftRight( 0.5, 0.5, -137, -37 )
			f6_arg0.BracketL:setAlpha( 1 )
			f6_arg0.clipFinished( f6_arg0.BracketL )
			f6_arg0.BracketL2:completeAnimation()
			f6_arg0.BracketL2:setLeftRight( 0.5, 0.5, -137, -37 )
			f6_arg0.BracketL2:setRGB( 1, 0.88, 0.71 )
			f6_arg0.BracketL2:setAlpha( 1 )
			f6_arg0.clipFinished( f6_arg0.BracketL2 )
			f6_arg0.BracketR:completeAnimation()
			f6_arg0.BracketR:setLeftRight( 0.5, 0.5, 37, 137 )
			f6_arg0.BracketR:setAlpha( 1 )
			f6_arg0.clipFinished( f6_arg0.BracketR )
			f6_arg0.BracketR2:completeAnimation()
			f6_arg0.BracketR2:setLeftRight( 0.5, 0.5, 37, 137 )
			f6_arg0.BracketR2:setAlpha( 1 )
			f6_arg0.clipFinished( f6_arg0.BracketR2 )
		end,
		GainChildFocus = function ( f7_arg0, f7_arg1 )
			f7_arg0:__resetProperties()
			f7_arg0:setupElementClipCounter( 15 )
			local f7_local0 = function ( f8_arg0 )
				f7_arg0.NoiseTiledBackingAdd:beginAnimation( 150 )
				f7_arg0.NoiseTiledBackingAdd:setAlpha( 0.5 )
				f7_arg0.NoiseTiledBackingAdd:registerEventHandler( "interrupted_keyframe", f7_arg0.clipInterrupted )
				f7_arg0.NoiseTiledBackingAdd:registerEventHandler( "transition_complete_keyframe", f7_arg0.clipFinished )
			end
			
			f7_arg0.NoiseTiledBackingAdd:completeAnimation()
			f7_arg0.NoiseTiledBackingAdd:setAlpha( 0.2 )
			f7_local0( f7_arg0.NoiseTiledBackingAdd )
			local f7_local1 = function ( f9_arg0 )
				f7_arg0.ImageContainer:beginAnimation( 150 )
				f7_arg0.ImageContainer.ImageContainer:beginAnimation( 150 )
				f7_arg0.ImageContainer.ImageContainer:setAlpha( 1 )
				f7_arg0.ImageContainer:registerEventHandler( "interrupted_keyframe", f7_arg0.clipInterrupted )
				f7_arg0.ImageContainer:registerEventHandler( "transition_complete_keyframe", f7_arg0.clipFinished )
			end
			
			f7_arg0.ImageContainer:completeAnimation()
			f7_arg0.ImageContainer.ImageContainer:completeAnimation()
			f7_arg0.ImageContainer.ImageContainer:setAlpha( 0.79 )
			f7_local1( f7_arg0.ImageContainer )
			local f7_local2 = function ( f10_arg0 )
				f7_arg0.LockBackground:beginAnimation( 150 )
				f7_arg0.LockBackground:setAlpha( 0 )
				f7_arg0.LockBackground:registerEventHandler( "interrupted_keyframe", f7_arg0.clipInterrupted )
				f7_arg0.LockBackground:registerEventHandler( "transition_complete_keyframe", f7_arg0.clipFinished )
			end
			
			f7_arg0.LockBackground:completeAnimation()
			f7_arg0.LockBackground:setAlpha( 0.05 )
			f7_local2( f7_arg0.LockBackground )
			f7_arg0.DotTiledBacking:completeAnimation()
			f7_arg0.DotTiledBacking:setAlpha( 0 )
			f7_arg0.clipFinished( f7_arg0.DotTiledBacking )
			f7_arg0.TitleBgTexture:completeAnimation()
			f7_arg0.TitleBgTexture:setAlpha( 0 )
			f7_arg0.clipFinished( f7_arg0.TitleBgTexture )
			f7_arg0.TitleBg:completeAnimation()
			f7_arg0.TitleBg:setAlpha( 0 )
			f7_arg0.clipFinished( f7_arg0.TitleBg )
			f7_arg0.lockedIcon:completeAnimation()
			f7_arg0.lockedIcon:setAlpha( 0 )
			f7_arg0.clipFinished( f7_arg0.lockedIcon )
			f7_arg0.ButtonStateText:completeAnimation()
			f7_arg0.ButtonStateText:setAlpha( 0 )
			f7_arg0.clipFinished( f7_arg0.ButtonStateText )
			local f7_local3 = function ( f11_arg0 )
				f7_arg0.NameEntryBG:beginAnimation( 150 )
				f7_arg0.NameEntryBG:setLeftRight( 0.5, 0.5, -90, 90 )
				f7_arg0.NameEntryBG:setAlpha( 0.95 )
				f7_arg0.NameEntryBG:registerEventHandler( "interrupted_keyframe", f7_arg0.clipInterrupted )
				f7_arg0.NameEntryBG:registerEventHandler( "transition_complete_keyframe", f7_arg0.clipFinished )
			end
			
			f7_arg0.NameEntryBG:completeAnimation()
			f7_arg0.NameEntryBG:setLeftRight( 0.5, 0.5, -82.5, 82.5 )
			f7_arg0.NameEntryBG:setAlpha( 0.5 )
			f7_local3( f7_arg0.NameEntryBG )
			local f7_local4 = function ( f12_arg0 )
				f7_arg0.NameEntryBorder:beginAnimation( 150 )
				f7_arg0.NameEntryBorder:setLeftRight( 0.5, 0.5, -90, 90 )
				f7_arg0.NameEntryBorder:registerEventHandler( "interrupted_keyframe", f7_arg0.clipInterrupted )
				f7_arg0.NameEntryBorder:registerEventHandler( "transition_complete_keyframe", f7_arg0.clipFinished )
			end
			
			f7_arg0.NameEntryBorder:completeAnimation()
			f7_arg0.NameEntryBorder:setLeftRight( 0.5, 0.5, -82.5, 82.5 )
			f7_local4( f7_arg0.NameEntryBorder )
			local f7_local5 = function ( f13_arg0 )
				f7_arg0.NameEntrySelected:beginAnimation( 150 )
				f7_arg0.NameEntrySelected:setLeftRight( 0.5, 0.5, -90, 90 )
				f7_arg0.NameEntrySelected:registerEventHandler( "interrupted_keyframe", f7_arg0.clipInterrupted )
				f7_arg0.NameEntrySelected:registerEventHandler( "transition_complete_keyframe", f7_arg0.clipFinished )
			end
			
			f7_arg0.NameEntrySelected:completeAnimation()
			f7_arg0.NameEntrySelected:setLeftRight( 0.5, 0.5, -82.5, 82.5 )
			f7_local5( f7_arg0.NameEntrySelected )
			local f7_local6 = function ( f14_arg0 )
				f7_arg0.BracketL:beginAnimation( 150 )
				f7_arg0.BracketL:setLeftRight( 0.5, 0.5, -137, -37 )
				f7_arg0.BracketL:registerEventHandler( "interrupted_keyframe", f7_arg0.clipInterrupted )
				f7_arg0.BracketL:registerEventHandler( "transition_complete_keyframe", f7_arg0.clipFinished )
			end
			
			f7_arg0.BracketL:completeAnimation()
			f7_arg0.BracketL:setLeftRight( 0.5, 0.5, -130, -30 )
			f7_arg0.BracketL:setAlpha( 1 )
			f7_local6( f7_arg0.BracketL )
			local f7_local7 = function ( f15_arg0 )
				f7_arg0.BracketL2:beginAnimation( 150 )
				f7_arg0.BracketL2:setLeftRight( 0.5, 0.5, -137, -37 )
				f7_arg0.BracketL2:setAlpha( 1 )
				f7_arg0.BracketL2:registerEventHandler( "interrupted_keyframe", f7_arg0.clipInterrupted )
				f7_arg0.BracketL2:registerEventHandler( "transition_complete_keyframe", f7_arg0.clipFinished )
			end
			
			f7_arg0.BracketL2:completeAnimation()
			f7_arg0.BracketL2:setLeftRight( 0.5, 0.5, -130, -30 )
			f7_arg0.BracketL2:setAlpha( 0 )
			f7_local7( f7_arg0.BracketL2 )
			local f7_local8 = function ( f16_arg0 )
				f7_arg0.BracketR:beginAnimation( 150 )
				f7_arg0.BracketR:setLeftRight( 0.5, 0.5, 37, 137 )
				f7_arg0.BracketR:registerEventHandler( "interrupted_keyframe", f7_arg0.clipInterrupted )
				f7_arg0.BracketR:registerEventHandler( "transition_complete_keyframe", f7_arg0.clipFinished )
			end
			
			f7_arg0.BracketR:completeAnimation()
			f7_arg0.BracketR:setLeftRight( 0.5, 0.5, 30, 130 )
			f7_arg0.BracketR:setAlpha( 1 )
			f7_local8( f7_arg0.BracketR )
			local f7_local9 = function ( f17_arg0 )
				f7_arg0.BracketR2:beginAnimation( 150 )
				f7_arg0.BracketR2:setLeftRight( 0.5, 0.5, 37, 137 )
				f7_arg0.BracketR2:setAlpha( 1 )
				f7_arg0.BracketR2:registerEventHandler( "interrupted_keyframe", f7_arg0.clipInterrupted )
				f7_arg0.BracketR2:registerEventHandler( "transition_complete_keyframe", f7_arg0.clipFinished )
			end
			
			f7_arg0.BracketR2:completeAnimation()
			f7_arg0.BracketR2:setLeftRight( 0.5, 0.5, 30, 130 )
			f7_arg0.BracketR2:setAlpha( 0 )
			f7_local9( f7_arg0.BracketR2 )
		end,
		LoseChildFocus = function ( f18_arg0, f18_arg1 )
			f18_arg0:__resetProperties()
			f18_arg0:setupElementClipCounter( 15 )
			local f18_local0 = function ( f19_arg0 )
				f18_arg0.NoiseTiledBackingAdd:beginAnimation( 150 )
				f18_arg0.NoiseTiledBackingAdd:setAlpha( 0.2 )
				f18_arg0.NoiseTiledBackingAdd:registerEventHandler( "interrupted_keyframe", f18_arg0.clipInterrupted )
				f18_arg0.NoiseTiledBackingAdd:registerEventHandler( "transition_complete_keyframe", f18_arg0.clipFinished )
			end
			
			f18_arg0.NoiseTiledBackingAdd:completeAnimation()
			f18_arg0.NoiseTiledBackingAdd:setAlpha( 0.5 )
			f18_local0( f18_arg0.NoiseTiledBackingAdd )
			local f18_local1 = function ( f20_arg0 )
				f18_arg0.ImageContainer:beginAnimation( 150 )
				f18_arg0.ImageContainer.ImageContainer:beginAnimation( 150 )
				f18_arg0.ImageContainer.ImageContainer:setAlpha( 0.79 )
				f18_arg0.ImageContainer:registerEventHandler( "interrupted_keyframe", f18_arg0.clipInterrupted )
				f18_arg0.ImageContainer:registerEventHandler( "transition_complete_keyframe", f18_arg0.clipFinished )
			end
			
			f18_arg0.ImageContainer:completeAnimation()
			f18_arg0.ImageContainer.ImageContainer:completeAnimation()
			f18_arg0.ImageContainer.ImageContainer:setAlpha( 1 )
			f18_local1( f18_arg0.ImageContainer )
			local f18_local2 = function ( f21_arg0 )
				f18_arg0.LockBackground:beginAnimation( 150 )
				f18_arg0.LockBackground:setAlpha( 0.05 )
				f18_arg0.LockBackground:registerEventHandler( "interrupted_keyframe", f18_arg0.clipInterrupted )
				f18_arg0.LockBackground:registerEventHandler( "transition_complete_keyframe", f18_arg0.clipFinished )
			end
			
			f18_arg0.LockBackground:completeAnimation()
			f18_arg0.LockBackground:setAlpha( 0 )
			f18_local2( f18_arg0.LockBackground )
			f18_arg0.DotTiledBacking:completeAnimation()
			f18_arg0.DotTiledBacking:setAlpha( 0 )
			f18_arg0.clipFinished( f18_arg0.DotTiledBacking )
			f18_arg0.TitleBgTexture:completeAnimation()
			f18_arg0.TitleBgTexture:setAlpha( 0 )
			f18_arg0.clipFinished( f18_arg0.TitleBgTexture )
			f18_arg0.TitleBg:completeAnimation()
			f18_arg0.TitleBg:setAlpha( 0 )
			f18_arg0.clipFinished( f18_arg0.TitleBg )
			f18_arg0.lockedIcon:completeAnimation()
			f18_arg0.lockedIcon:setAlpha( 0 )
			f18_arg0.clipFinished( f18_arg0.lockedIcon )
			f18_arg0.ButtonStateText:completeAnimation()
			f18_arg0.ButtonStateText:setAlpha( 0 )
			f18_arg0.clipFinished( f18_arg0.ButtonStateText )
			local f18_local3 = function ( f22_arg0 )
				f18_arg0.NameEntryBG:beginAnimation( 150 )
				f18_arg0.NameEntryBG:setAlpha( 0.5 )
				f18_arg0.NameEntryBG:registerEventHandler( "interrupted_keyframe", f18_arg0.clipInterrupted )
				f18_arg0.NameEntryBG:registerEventHandler( "transition_complete_keyframe", f18_arg0.clipFinished )
			end
			
			f18_arg0.NameEntryBG:completeAnimation()
			f18_arg0.NameEntryBG:setLeftRight( 0.5, 0.5, -90, 90 )
			f18_arg0.NameEntryBG:setAlpha( 0.95 )
			f18_local3( f18_arg0.NameEntryBG )
			local f18_local4 = function ( f23_arg0 )
				f18_arg0.NameEntryBorder:beginAnimation( 150 )
				f18_arg0.NameEntryBorder:setLeftRight( 0.5, 0.5, -82.5, 82.5 )
				f18_arg0.NameEntryBorder:registerEventHandler( "interrupted_keyframe", f18_arg0.clipInterrupted )
				f18_arg0.NameEntryBorder:registerEventHandler( "transition_complete_keyframe", f18_arg0.clipFinished )
			end
			
			f18_arg0.NameEntryBorder:completeAnimation()
			f18_arg0.NameEntryBorder:setLeftRight( 0.5, 0.5, -90, 90 )
			f18_local4( f18_arg0.NameEntryBorder )
			local f18_local5 = function ( f24_arg0 )
				f18_arg0.NameEntrySelected:beginAnimation( 150 )
				f18_arg0.NameEntrySelected:setLeftRight( 0.5, 0.5, -82.5, 82.5 )
				f18_arg0.NameEntrySelected:registerEventHandler( "interrupted_keyframe", f18_arg0.clipInterrupted )
				f18_arg0.NameEntrySelected:registerEventHandler( "transition_complete_keyframe", f18_arg0.clipFinished )
			end
			
			f18_arg0.NameEntrySelected:completeAnimation()
			f18_arg0.NameEntrySelected:setLeftRight( 0.5, 0.5, -90, 90 )
			f18_local5( f18_arg0.NameEntrySelected )
			local f18_local6 = function ( f25_arg0 )
				f18_arg0.BracketL:beginAnimation( 150 )
				f18_arg0.BracketL:setLeftRight( 0.5, 0.5, -130, -30 )
				f18_arg0.BracketL:registerEventHandler( "interrupted_keyframe", f18_arg0.clipInterrupted )
				f18_arg0.BracketL:registerEventHandler( "transition_complete_keyframe", f18_arg0.clipFinished )
			end
			
			f18_arg0.BracketL:completeAnimation()
			f18_arg0.BracketL:setLeftRight( 0.5, 0.5, -137, -37 )
			f18_arg0.BracketL:setAlpha( 1 )
			f18_local6( f18_arg0.BracketL )
			local f18_local7 = function ( f26_arg0 )
				f18_arg0.BracketL2:beginAnimation( 150 )
				f18_arg0.BracketL2:setLeftRight( 0.5, 0.5, -130, -30 )
				f18_arg0.BracketL2:setAlpha( 0 )
				f18_arg0.BracketL2:registerEventHandler( "interrupted_keyframe", f18_arg0.clipInterrupted )
				f18_arg0.BracketL2:registerEventHandler( "transition_complete_keyframe", f18_arg0.clipFinished )
			end
			
			f18_arg0.BracketL2:completeAnimation()
			f18_arg0.BracketL2:setLeftRight( 0.5, 0.5, -137, -37 )
			f18_arg0.BracketL2:setAlpha( 1 )
			f18_local7( f18_arg0.BracketL2 )
			local f18_local8 = function ( f27_arg0 )
				f18_arg0.BracketR:beginAnimation( 150 )
				f18_arg0.BracketR:setLeftRight( 0.5, 0.5, 30, 130 )
				f18_arg0.BracketR:registerEventHandler( "interrupted_keyframe", f18_arg0.clipInterrupted )
				f18_arg0.BracketR:registerEventHandler( "transition_complete_keyframe", f18_arg0.clipFinished )
			end
			
			f18_arg0.BracketR:completeAnimation()
			f18_arg0.BracketR:setLeftRight( 0.5, 0.5, 37, 137 )
			f18_arg0.BracketR:setAlpha( 1 )
			f18_local8( f18_arg0.BracketR )
			local f18_local9 = function ( f28_arg0 )
				f18_arg0.BracketR2:beginAnimation( 150 )
				f18_arg0.BracketR2:setLeftRight( 0.5, 0.5, 30, 130 )
				f18_arg0.BracketR2:setAlpha( 0 )
				f18_arg0.BracketR2:registerEventHandler( "interrupted_keyframe", f18_arg0.clipInterrupted )
				f18_arg0.BracketR2:registerEventHandler( "transition_complete_keyframe", f18_arg0.clipFinished )
			end
			
			f18_arg0.BracketR2:completeAnimation()
			f18_arg0.BracketR2:setLeftRight( 0.5, 0.5, 37, 137 )
			f18_arg0.BracketR2:setAlpha( 1 )
			f18_local9( f18_arg0.BracketR2 )
		end,
		Active = function ( f29_arg0, f29_arg1 )
			f29_arg0:__resetProperties()
			f29_arg0:setupElementClipCounter( 12 )
			f29_arg0.NoiseTiledBackingAdd:completeAnimation()
			f29_arg0.NoiseTiledBackingAdd:setAlpha( 0.5 )
			f29_arg0.clipFinished( f29_arg0.NoiseTiledBackingAdd )
			f29_arg0.DotTiledBacking:completeAnimation()
			f29_arg0.DotTiledBacking:setAlpha( 0 )
			f29_arg0.clipFinished( f29_arg0.DotTiledBacking )
			f29_arg0.TitleBgTexture:completeAnimation()
			f29_arg0.TitleBgTexture:setAlpha( 0 )
			f29_arg0.clipFinished( f29_arg0.TitleBgTexture )
			f29_arg0.TitleBg:completeAnimation()
			f29_arg0.TitleBg:setAlpha( 0 )
			f29_arg0.clipFinished( f29_arg0.TitleBg )
			f29_arg0.lockedIcon:completeAnimation()
			f29_arg0.lockedIcon:setAlpha( 0 )
			f29_arg0.clipFinished( f29_arg0.lockedIcon )
			f29_arg0.ButtonStateText:completeAnimation()
			f29_arg0.ButtonStateText:setAlpha( 0 )
			f29_arg0.clipFinished( f29_arg0.ButtonStateText )
			f29_arg0.NameEntryBG:completeAnimation()
			f29_arg0.NameEntryBG:setAlpha( 0.95 )
			f29_arg0.clipFinished( f29_arg0.NameEntryBG )
			local f29_local0 = function ( f30_arg0 )
				f29_arg0.NameEntrySelected:beginAnimation( 80 )
				f29_arg0.NameEntrySelected:setAlpha( 0.8 )
				f29_arg0.NameEntrySelected:registerEventHandler( "interrupted_keyframe", f29_arg0.clipInterrupted )
				f29_arg0.NameEntrySelected:registerEventHandler( "transition_complete_keyframe", f29_arg0.clipFinished )
			end
			
			f29_arg0.NameEntrySelected:completeAnimation()
			f29_arg0.NameEntrySelected:setAlpha( 0 )
			f29_local0( f29_arg0.NameEntrySelected )
			local f29_local1 = function ( f31_arg0 )
				f29_arg0.BracketL:beginAnimation( 30 )
				f29_arg0.BracketL:setLeftRight( 0.5, 0.5, -130, -30 )
				f29_arg0.BracketL:registerEventHandler( "interrupted_keyframe", f29_arg0.clipInterrupted )
				f29_arg0.BracketL:registerEventHandler( "transition_complete_keyframe", f29_arg0.clipFinished )
			end
			
			f29_arg0.BracketL:completeAnimation()
			f29_arg0.BracketL:setLeftRight( 0.5, 0.5, -137, -37 )
			f29_arg0.BracketL:setAlpha( 1 )
			f29_local1( f29_arg0.BracketL )
			local f29_local2 = function ( f32_arg0 )
				f29_arg0.BracketL2:beginAnimation( 30 )
				f29_arg0.BracketL2:setLeftRight( 0.5, 0.5, -130, -30 )
				f29_arg0.BracketL2:registerEventHandler( "interrupted_keyframe", f29_arg0.clipInterrupted )
				f29_arg0.BracketL2:registerEventHandler( "transition_complete_keyframe", f29_arg0.clipFinished )
			end
			
			f29_arg0.BracketL2:completeAnimation()
			f29_arg0.BracketL2:setLeftRight( 0.5, 0.5, -137, -37 )
			f29_arg0.BracketL2:setRGB( 1, 0.88, 0.71 )
			f29_arg0.BracketL2:setAlpha( 1 )
			f29_local2( f29_arg0.BracketL2 )
			local f29_local3 = function ( f33_arg0 )
				f29_arg0.BracketR:beginAnimation( 30 )
				f29_arg0.BracketR:setLeftRight( 0.5, 0.5, 30, 130 )
				f29_arg0.BracketR:registerEventHandler( "interrupted_keyframe", f29_arg0.clipInterrupted )
				f29_arg0.BracketR:registerEventHandler( "transition_complete_keyframe", f29_arg0.clipFinished )
			end
			
			f29_arg0.BracketR:completeAnimation()
			f29_arg0.BracketR:setLeftRight( 0.5, 0.5, 37, 137 )
			f29_arg0.BracketR:setAlpha( 1 )
			f29_local3( f29_arg0.BracketR )
			local f29_local4 = function ( f34_arg0 )
				f29_arg0.BracketR2:beginAnimation( 30 )
				f29_arg0.BracketR2:setLeftRight( 0.5, 0.5, 30, 130 )
				f29_arg0.BracketR2:registerEventHandler( "interrupted_keyframe", f29_arg0.clipInterrupted )
				f29_arg0.BracketR2:registerEventHandler( "transition_complete_keyframe", f29_arg0.clipFinished )
			end
			
			f29_arg0.BracketR2:completeAnimation()
			f29_arg0.BracketR2:setLeftRight( 0.5, 0.5, 37, 137 )
			f29_arg0.BracketR2:setAlpha( 1 )
			f29_local4( f29_arg0.BracketR2 )
		end,
		InputFocus = function ( f35_arg0, f35_arg1 )
			f35_arg0:__resetProperties()
			f35_arg0:setupElementClipCounter( 15 )
			f35_arg0.NoiseTiledBackingAdd:completeAnimation()
			f35_arg0.NoiseTiledBackingAdd:setAlpha( 0.5 )
			f35_arg0.clipFinished( f35_arg0.NoiseTiledBackingAdd )
			f35_arg0.DotTiledBacking:completeAnimation()
			f35_arg0.DotTiledBacking:setAlpha( 0 )
			f35_arg0.clipFinished( f35_arg0.DotTiledBacking )
			f35_arg0.TitleBgTexture:completeAnimation()
			f35_arg0.TitleBgTexture:setAlpha( 0 )
			f35_arg0.clipFinished( f35_arg0.TitleBgTexture )
			f35_arg0.TitleBg:completeAnimation()
			f35_arg0.TitleBg:setAlpha( 0 )
			f35_arg0.clipFinished( f35_arg0.TitleBg )
			f35_arg0.lockedIcon:completeAnimation()
			f35_arg0.lockedIcon:setAlpha( 0 )
			f35_arg0.clipFinished( f35_arg0.lockedIcon )
			f35_arg0.ButtonStateText:completeAnimation()
			f35_arg0.ButtonStateText:setAlpha( 0 )
			f35_arg0.clipFinished( f35_arg0.ButtonStateText )
			f35_arg0.NameEntryBG:completeAnimation()
			f35_arg0.NameEntryBG:setLeftRight( 0.5, 0.5, -90, 90 )
			f35_arg0.NameEntryBG:setAlpha( 0.95 )
			f35_arg0.clipFinished( f35_arg0.NameEntryBG )
			f35_arg0.NameEntryBorder:completeAnimation()
			f35_arg0.NameEntryBorder:setLeftRight( 0.5, 0.5, -90, 90 )
			f35_arg0.clipFinished( f35_arg0.NameEntryBorder )
			f35_arg0.NameEntrySelected:completeAnimation()
			f35_arg0.NameEntrySelected:setLeftRight( 0.5, 0.5, -90, 90 )
			f35_arg0.clipFinished( f35_arg0.NameEntrySelected )
			f35_arg0.ClanText:completeAnimation()
			f35_arg0.ClanText:setAlpha( 0 )
			f35_arg0.clipFinished( f35_arg0.ClanText )
			f35_arg0.TextBox:completeAnimation()
			f35_arg0.TextBox:setAlpha( 1 )
			f35_arg0.clipFinished( f35_arg0.TextBox )
			f35_arg0.BracketL:completeAnimation()
			f35_arg0.BracketL:setLeftRight( 0.5, 0.5, -137, -37 )
			f35_arg0.BracketL:setAlpha( 1 )
			f35_arg0.clipFinished( f35_arg0.BracketL )
			f35_arg0.BracketL2:completeAnimation()
			f35_arg0.BracketL2:setLeftRight( 0.5, 0.5, -137, -37 )
			f35_arg0.BracketL2:setRGB( 1, 0.88, 0.71 )
			f35_arg0.BracketL2:setAlpha( 1 )
			f35_arg0.clipFinished( f35_arg0.BracketL2 )
			f35_arg0.BracketR:completeAnimation()
			f35_arg0.BracketR:setLeftRight( 0.5, 0.5, 37, 137 )
			f35_arg0.BracketR:setAlpha( 1 )
			f35_arg0.clipFinished( f35_arg0.BracketR )
			f35_arg0.BracketR2:completeAnimation()
			f35_arg0.BracketR2:setLeftRight( 0.5, 0.5, 37, 137 )
			f35_arg0.BracketR2:setAlpha( 1 )
			f35_arg0.clipFinished( f35_arg0.BracketR2 )
		end
	},
	Disabled = {
		DefaultClip = function ( f36_arg0, f36_arg1 )
			f36_arg0:__resetProperties()
			f36_arg0:setupElementClipCounter( 13 )
			f36_arg0.ImageContainer:completeAnimation()
			f36_arg0.ImageContainer.ImageContainer:completeAnimation()
			f36_arg0.ImageContainer.ImageContainer:setAlpha( 0.79 )
			f36_arg0.clipFinished( f36_arg0.ImageContainer )
			f36_arg0.LockBackground:completeAnimation()
			f36_arg0.LockBackground:setAlpha( 0.05 )
			f36_arg0.clipFinished( f36_arg0.LockBackground )
			f36_arg0.DotTiledBacking:completeAnimation()
			f36_arg0.DotTiledBacking:setAlpha( 0 )
			f36_arg0.clipFinished( f36_arg0.DotTiledBacking )
			f36_arg0.TitleBgTexture:completeAnimation()
			f36_arg0.TitleBgTexture:setAlpha( 0 )
			f36_arg0.clipFinished( f36_arg0.TitleBgTexture )
			f36_arg0.TitleBg:completeAnimation()
			f36_arg0.TitleBg:setAlpha( 0 )
			f36_arg0.clipFinished( f36_arg0.TitleBg )
			f36_arg0.lockedIcon:completeAnimation()
			f36_arg0.lockedIcon:setAlpha( 0.5 )
			f36_arg0.clipFinished( f36_arg0.lockedIcon )
			f36_arg0.ButtonStateText:completeAnimation()
			f36_arg0.ButtonStateText:setAlpha( 0 )
			f36_arg0.clipFinished( f36_arg0.ButtonStateText )
			f36_arg0.NameEntryBG:completeAnimation()
			f36_arg0.NameEntryBG:setAlpha( 0.5 )
			f36_arg0.clipFinished( f36_arg0.NameEntryBG )
			f36_arg0.TextBox:completeAnimation()
			f36_arg0.TextBox:setAlpha( 0 )
			f36_arg0.clipFinished( f36_arg0.TextBox )
			f36_arg0.BracketL:completeAnimation()
			f36_arg0.BracketL:setAlpha( 1 )
			f36_arg0.clipFinished( f36_arg0.BracketL )
			f36_arg0.BracketL2:completeAnimation()
			f36_arg0.BracketL2:setAlpha( 0 )
			f36_arg0.clipFinished( f36_arg0.BracketL2 )
			f36_arg0.BracketR:completeAnimation()
			f36_arg0.BracketR:setAlpha( 1 )
			f36_arg0.clipFinished( f36_arg0.BracketR )
			f36_arg0.BracketR2:completeAnimation()
			f36_arg0.BracketR2:setAlpha( 0 )
			f36_arg0.clipFinished( f36_arg0.BracketR2 )
		end
	}
}
CoD.PC_StartMenu_Button_LG_Internal.__onClose = function ( f37_arg0 )
	f37_arg0.ImageContainer:close()
	f37_arg0.StartMenuButtonFrame:close()
	f37_arg0.DotTiledBacking:close()
	f37_arg0.lockedIcon:close()
	f37_arg0.ClanText:close()
	f37_arg0.TextBox:close()
	f37_arg0.ButtonTitle:close()
	f37_arg0.ButtonOutline:close()
end

