require( "ui/uieditor/widgets/lobby/common/fe_buttonfocus" )
require( "ui/uieditor/widgets/lobby/common/fe_buttonidle" )
require( "ui/uieditor/widgets/lobby/common/fe_buttonpanelshadercontainer" )

CoD.CACGenericButton = InheritFrom( LUI.UIElement )
CoD.CACGenericButton.__defaultWidth = 1122
CoD.CACGenericButton.__defaultHeight = 48
CoD.CACGenericButton.new = function ( f1_arg0, f1_arg1, f1_arg2, f1_arg3, f1_arg4, f1_arg5, f1_arg6, f1_arg7, f1_arg8, f1_arg9 )
	local self = LUI.UIElement.new( f1_arg2, f1_arg3, f1_arg4, f1_arg5, f1_arg6, f1_arg7, f1_arg8, f1_arg9 )
	self:setClass( CoD.CACGenericButton )
	self.id = "CACGenericButton"
	self.soundSet = "default"
	self.anyChildUsesUpdateState = true
	f1_arg0:addElementToPendingUpdateStateList( self )
	
	local FEButtonPanelShaderContainer = CoD.FE_ButtonPanelShaderContainer.new( f1_arg0, f1_arg1, 0, 1, 0, 0, 0.5, 0.5, -21, 21 )
	FEButtonPanelShaderContainer:setRGB( 0.5, 0.5, 0.5 )
	FEButtonPanelShaderContainer:setAlpha( 0 )
	FEButtonPanelShaderContainer:setZoom( -10 )
	self:addElement( FEButtonPanelShaderContainer )
	self.FEButtonPanelShaderContainer = FEButtonPanelShaderContainer
	
	local FEButtonIdle = CoD.FE_ButtonIdle.new( f1_arg0, f1_arg1, 0, 1, 0, 0, 0.5, 0.5, -21, 21 )
	FEButtonIdle:setAlpha( 0 )
	self:addElement( FEButtonIdle )
	self.FEButtonIdle = FEButtonIdle
	
	local FEButtonFocus = CoD.FE_ButtonFocus.new( f1_arg0, f1_arg1, 0, 1, 0, 0, 0.5, 0.5, -21, 21 )
	FEButtonFocus:setAlpha( 0 )
	FEButtonFocus.Image:setShaderVector( 0, 0.02, 0.3, 0.38, 0.2 )
	self:addElement( FEButtonFocus )
	self.FEButtonFocus = FEButtonFocus
	
	local Glow = LUI.UIImage.new( 0, 1, -3, 3, 0, 1, -22, 22 )
	Glow:setRGB( 0.88, 1, 0.04 )
	Glow:setAlpha( 0 )
	Glow:setImage( RegisterImage( 0x713A30DFAEF8964 ) )
	Glow:setMaterial( LUI.UIImage.GetCachedMaterial( "ui_add" ) )
	self:addElement( Glow )
	self.Glow = Glow
	
	local btnDisplayText = LUI.UIText.new( 0, 0, 18, 816, 0, 0, 10, 40 )
	btnDisplayText:setRGB( 0.79, 0.79, 0.79 )
	btnDisplayText:setAlpha( 0 )
	btnDisplayText:setTTF( "ttmussels_demibold" )
	btnDisplayText:setLetterSpacing( 1 )
	btnDisplayText:setAlignment( Enum.LUIAlignment[0x58C8A85F2048829] )
	btnDisplayText:setAlignment( Enum.LUIAlignment[0xF41D595A2B0EDF3] )
	btnDisplayText:linkToElementModel( self, "displayText", true, function ( model )
		local f2_local0 = model:get()
		if f2_local0 ~= nil then
			btnDisplayText:setText( Engine[0xF9F1239CFD921FE]( f2_local0 ) )
		end
	end )
	LUI.OverrideFunction_CallOriginalFirst( btnDisplayText, "setText", function ( element, controller )
		ScaleWidgetToLabel( self, element, 2 )
	end )
	self:addElement( btnDisplayText )
	self.btnDisplayText = btnDisplayText
	
	local btnDisplayTextStroke = LUI.UIText.new( 0, 0, 18, 816, 0, 0, 10, 40 )
	btnDisplayTextStroke:setRGB( 0, 0, 0 )
	btnDisplayTextStroke:setAlpha( 0 )
	btnDisplayTextStroke:setTTF( "ttmussels_demibold" )
	btnDisplayTextStroke:setMaterial( LUI.UIImage.GetCachedMaterial( 0xAE166D9BA8C6907 ) )
	btnDisplayTextStroke:setShaderVector( 0, 0.08, 0, 0, 0 )
	btnDisplayTextStroke:setShaderVector( 1, 0, 0, 0, 0 )
	btnDisplayTextStroke:setShaderVector( 2, 1, 0, 0, 0 )
	btnDisplayTextStroke:setLetterSpacing( 1 )
	btnDisplayTextStroke:setAlignment( Enum.LUIAlignment[0x58C8A85F2048829] )
	btnDisplayTextStroke:setAlignment( Enum.LUIAlignment[0xF41D595A2B0EDF3] )
	btnDisplayTextStroke:linkToElementModel( self, "displayText", true, function ( model )
		local f4_local0 = model:get()
		if f4_local0 ~= nil then
			btnDisplayTextStroke:setText( Engine[0xF9F1239CFD921FE]( f4_local0 ) )
		end
	end )
	LUI.OverrideFunction_CallOriginalFirst( btnDisplayTextStroke, "setText", function ( element, controller )
		TrimLabelIfLanguageReversed( self, element )
	end )
	self:addElement( btnDisplayTextStroke )
	self.btnDisplayTextStroke = btnDisplayTextStroke
	
	local Arrow = LUI.UIImage.new( 0, 0, 4, 16, 0, 0, 18, 30 )
	Arrow:setAlpha( 0 )
	Arrow:setZoom( 10 )
	Arrow:setImage( RegisterImage( 0x3842361F4104287 ) )
	Arrow:setMaterial( LUI.UIImage.GetCachedMaterial( "ui_add" ) )
	self:addElement( Arrow )
	self.Arrow = Arrow
	
	local Glow2 = LUI.UIImage.new( 0, 1, -3, 3, 0, 1, -22, 22 )
	Glow2:setAlpha( 0 )
	Glow2:setImage( RegisterImage( 0x713A30DFAEF8964 ) )
	Glow2:setMaterial( LUI.UIImage.GetCachedMaterial( "ui_add" ) )
	self:addElement( Glow2 )
	self.Glow2 = Glow2
	
	local Image = LUI.UIImage.new( 0, 0, 10, 37, 0.5, 0.5, -15, 12 )
	Image:linkToElementModel( self, "image", true, function ( model )
		local f6_local0 = model:get()
		if f6_local0 ~= nil then
			Image:setImage( RegisterImage( f6_local0 ) )
		end
	end )
	self:addElement( Image )
	self.Image = Image
	
	self:mergeStateConditions( {
		{
			stateName = "ImageVisible",
			condition = function ( menu, element, event )
				return not CoD.ModelUtility.IsSelfModelPathNil( element, f1_arg1, "image" )
			end
		},
		{
			stateName = "Disabled",
			condition = function ( menu, element, event )
				return IsDisabled( element, f1_arg1 )
			end
		}
	} )
	self:linkToElementModel( self, "image", true, function ( model )
		f1_arg0:updateElementState( self, {
			name = "model_validation",
			menu = f1_arg0,
			controller = f1_arg1,
			modelValue = model:get(),
			modelName = "image"
		} )
	end )
	self:linkToElementModel( self, "disabled", true, function ( model )
		f1_arg0:updateElementState( self, {
			name = "model_validation",
			menu = f1_arg0,
			controller = f1_arg1,
			modelValue = model:get(),
			modelName = "disabled"
		} )
	end )
	LUI.OverrideFunction_CallOriginalSecond( self, "close", self.__onClose )
	
	if PostLoadFunc then
		PostLoadFunc( self, f1_arg1, f1_arg0 )
	end
	
	return self
end

CoD.CACGenericButton.__resetProperties = function ( f11_arg0 )
	f11_arg0.btnDisplayText:completeAnimation()
	f11_arg0.FEButtonFocus:completeAnimation()
	f11_arg0.FEButtonIdle:completeAnimation()
	f11_arg0.Image:completeAnimation()
	f11_arg0.FEButtonPanelShaderContainer:completeAnimation()
	f11_arg0.btnDisplayTextStroke:completeAnimation()
	f11_arg0.Glow:completeAnimation()
	f11_arg0.Arrow:completeAnimation()
	f11_arg0.Glow2:completeAnimation()
	f11_arg0.btnDisplayText:setRGB( 0.79, 0.79, 0.79 )
	f11_arg0.btnDisplayText:setAlpha( 0 )
	f11_arg0.btnDisplayText:setZoom( 0 )
	f11_arg0.FEButtonFocus:setLeftRight( 0, 1, 0, 0 )
	f11_arg0.FEButtonFocus:setTopBottom( 0.5, 0.5, -21, 21 )
	f11_arg0.FEButtonFocus:setAlpha( 0 )
	f11_arg0.FEButtonFocus:setZoom( 0 )
	f11_arg0.FEButtonIdle:setAlpha( 0 )
	f11_arg0.FEButtonIdle:setZoom( 0 )
	f11_arg0.Image:setRGB( 1, 1, 1 )
	f11_arg0.Image:setAlpha( 1 )
	f11_arg0.FEButtonPanelShaderContainer:setRGB( 0.5, 0.5, 0.5 )
	f11_arg0.FEButtonPanelShaderContainer:setAlpha( 0 )
	f11_arg0.FEButtonPanelShaderContainer:setZoom( -10 )
	f11_arg0.btnDisplayTextStroke:setAlpha( 0 )
	f11_arg0.btnDisplayTextStroke:setZoom( 0 )
	f11_arg0.Glow:setLeftRight( 0, 1, -3, 3 )
	f11_arg0.Glow:setTopBottom( 0, 1, -22, 22 )
	f11_arg0.Glow:setAlpha( 0 )
	f11_arg0.Arrow:setLeftRight( 0, 0, 4, 16 )
	f11_arg0.Arrow:setTopBottom( 0, 0, 18, 30 )
	f11_arg0.Arrow:setAlpha( 0 )
	f11_arg0.Glow2:setAlpha( 0 )
end

CoD.CACGenericButton.__clipsPerState = {
	DefaultState = {
		DefaultClip = function ( f12_arg0, f12_arg1 )
			f12_arg0:__resetProperties()
			f12_arg0:setupElementClipCounter( 4 )
			f12_arg0.FEButtonIdle:completeAnimation()
			f12_arg0.FEButtonIdle:setAlpha( 1 )
			f12_arg0.clipFinished( f12_arg0.FEButtonIdle )
			f12_arg0.FEButtonFocus:completeAnimation()
			f12_arg0.FEButtonFocus:setLeftRight( 0, 1, 0, 0 )
			f12_arg0.FEButtonFocus:setTopBottom( 0.5, 0.5, -1, 3 )
			f12_arg0.clipFinished( f12_arg0.FEButtonFocus )
			f12_arg0.btnDisplayText:completeAnimation()
			f12_arg0.btnDisplayText:setAlpha( 1 )
			f12_arg0.clipFinished( f12_arg0.btnDisplayText )
			f12_arg0.Image:completeAnimation()
			f12_arg0.Image:setAlpha( 0 )
			f12_arg0.clipFinished( f12_arg0.Image )
		end,
		Focus = function ( f13_arg0, f13_arg1 )
			f13_arg0:__resetProperties()
			f13_arg0:setupElementClipCounter( 9 )
			f13_arg0.FEButtonPanelShaderContainer:completeAnimation()
			f13_arg0.FEButtonPanelShaderContainer:setZoom( 0 )
			f13_arg0.clipFinished( f13_arg0.FEButtonPanelShaderContainer )
			f13_arg0.FEButtonIdle:completeAnimation()
			f13_arg0.FEButtonIdle:setZoom( 10 )
			f13_arg0.clipFinished( f13_arg0.FEButtonIdle )
			f13_arg0.FEButtonFocus:completeAnimation()
			f13_arg0.FEButtonFocus:setAlpha( 1 )
			f13_arg0.FEButtonFocus:setZoom( 10 )
			f13_arg0.clipFinished( f13_arg0.FEButtonFocus )
			f13_arg0.Glow:completeAnimation()
			f13_arg0.Glow:setAlpha( 0.45 )
			f13_arg0.clipFinished( f13_arg0.Glow )
			f13_arg0.btnDisplayText:completeAnimation()
			f13_arg0.btnDisplayText:setZoom( 10 )
			f13_arg0.clipFinished( f13_arg0.btnDisplayText )
			f13_arg0.btnDisplayTextStroke:completeAnimation()
			f13_arg0.btnDisplayTextStroke:setAlpha( 1 )
			f13_arg0.btnDisplayTextStroke:setZoom( 10 )
			f13_arg0.clipFinished( f13_arg0.btnDisplayTextStroke )
			f13_arg0.Arrow:completeAnimation()
			f13_arg0.Arrow:setLeftRight( 0, 0, -30, -18 )
			f13_arg0.Arrow:setTopBottom( 0, 0, 18, 30 )
			f13_arg0.Arrow:setAlpha( 1 )
			f13_arg0.clipFinished( f13_arg0.Arrow )
			f13_arg0.Glow2:completeAnimation()
			f13_arg0.Glow2:setAlpha( 1 )
			f13_arg0.clipFinished( f13_arg0.Glow2 )
			f13_arg0.Image:completeAnimation()
			f13_arg0.Image:setAlpha( 0 )
			f13_arg0.clipFinished( f13_arg0.Image )
		end,
		LoseFocus = function ( f14_arg0, f14_arg1 )
			f14_arg0:__resetProperties()
			f14_arg0:setupElementClipCounter( 9 )
			local f14_local0 = function ( f15_arg0 )
				f14_arg0.FEButtonPanelShaderContainer:beginAnimation( 50 )
				f14_arg0.FEButtonPanelShaderContainer:setZoom( -10 )
				f14_arg0.FEButtonPanelShaderContainer:registerEventHandler( "interrupted_keyframe", f14_arg0.clipInterrupted )
				f14_arg0.FEButtonPanelShaderContainer:registerEventHandler( "transition_complete_keyframe", f14_arg0.clipFinished )
			end
			
			f14_arg0.FEButtonPanelShaderContainer:completeAnimation()
			f14_arg0.FEButtonPanelShaderContainer:setRGB( 0.5, 0.5, 0.5 )
			f14_arg0.FEButtonPanelShaderContainer:setAlpha( 0 )
			f14_arg0.FEButtonPanelShaderContainer:setZoom( 0 )
			f14_local0( f14_arg0.FEButtonPanelShaderContainer )
			local f14_local1 = function ( f16_arg0 )
				f14_arg0.FEButtonIdle:beginAnimation( 50 )
				f14_arg0.FEButtonIdle:setAlpha( 1 )
				f14_arg0.FEButtonIdle:setZoom( 0 )
				f14_arg0.FEButtonIdle:registerEventHandler( "interrupted_keyframe", f14_arg0.clipInterrupted )
				f14_arg0.FEButtonIdle:registerEventHandler( "transition_complete_keyframe", f14_arg0.clipFinished )
			end
			
			f14_arg0.FEButtonIdle:completeAnimation()
			f14_arg0.FEButtonIdle:setAlpha( 0 )
			f14_arg0.FEButtonIdle:setZoom( 10 )
			f14_local1( f14_arg0.FEButtonIdle )
			local f14_local2 = function ( f17_arg0 )
				f14_arg0.FEButtonFocus:beginAnimation( 50 )
				f14_arg0.FEButtonFocus:setAlpha( 0 )
				f14_arg0.FEButtonFocus:setZoom( 0 )
				f14_arg0.FEButtonFocus:registerEventHandler( "interrupted_keyframe", f14_arg0.clipInterrupted )
				f14_arg0.FEButtonFocus:registerEventHandler( "transition_complete_keyframe", f14_arg0.clipFinished )
			end
			
			f14_arg0.FEButtonFocus:completeAnimation()
			f14_arg0.FEButtonFocus:setLeftRight( 0, 1, 0, 0 )
			f14_arg0.FEButtonFocus:setTopBottom( 0.5, 0.5, -21, 21 )
			f14_arg0.FEButtonFocus:setAlpha( 1 )
			f14_arg0.FEButtonFocus:setZoom( 10 )
			f14_local2( f14_arg0.FEButtonFocus )
			local f14_local3 = function ( f18_arg0 )
				f14_arg0.Glow:beginAnimation( 50 )
				f14_arg0.Glow:setAlpha( 0 )
				f14_arg0.Glow:registerEventHandler( "interrupted_keyframe", f14_arg0.clipInterrupted )
				f14_arg0.Glow:registerEventHandler( "transition_complete_keyframe", f14_arg0.clipFinished )
			end
			
			f14_arg0.Glow:completeAnimation()
			f14_arg0.Glow:setAlpha( 0.45 )
			f14_local3( f14_arg0.Glow )
			local f14_local4 = function ( f19_arg0 )
				f14_arg0.btnDisplayText:beginAnimation( 50 )
				f14_arg0.btnDisplayText:setAlpha( 1 )
				f14_arg0.btnDisplayText:setZoom( 0 )
				f14_arg0.btnDisplayText:registerEventHandler( "interrupted_keyframe", f14_arg0.clipInterrupted )
				f14_arg0.btnDisplayText:registerEventHandler( "transition_complete_keyframe", f14_arg0.clipFinished )
			end
			
			f14_arg0.btnDisplayText:completeAnimation()
			f14_arg0.btnDisplayText:setAlpha( 0 )
			f14_arg0.btnDisplayText:setZoom( 10 )
			f14_local4( f14_arg0.btnDisplayText )
			local f14_local5 = function ( f20_arg0 )
				f14_arg0.btnDisplayTextStroke:beginAnimation( 50 )
				f14_arg0.btnDisplayTextStroke:setAlpha( 0 )
				f14_arg0.btnDisplayTextStroke:setZoom( 0 )
				f14_arg0.btnDisplayTextStroke:registerEventHandler( "interrupted_keyframe", f14_arg0.clipInterrupted )
				f14_arg0.btnDisplayTextStroke:registerEventHandler( "transition_complete_keyframe", f14_arg0.clipFinished )
			end
			
			f14_arg0.btnDisplayTextStroke:completeAnimation()
			f14_arg0.btnDisplayTextStroke:setAlpha( 1 )
			f14_arg0.btnDisplayTextStroke:setZoom( 10 )
			f14_local5( f14_arg0.btnDisplayTextStroke )
			local f14_local6 = function ( f21_arg0 )
				f14_arg0.Arrow:beginAnimation( 50 )
				f14_arg0.Arrow:setLeftRight( 0, 0, 4, 16 )
				f14_arg0.Arrow:setAlpha( 0 )
				f14_arg0.Arrow:registerEventHandler( "interrupted_keyframe", f14_arg0.clipInterrupted )
				f14_arg0.Arrow:registerEventHandler( "transition_complete_keyframe", f14_arg0.clipFinished )
			end
			
			f14_arg0.Arrow:completeAnimation()
			f14_arg0.Arrow:setLeftRight( 0, 0, -30, -18 )
			f14_arg0.Arrow:setTopBottom( 0, 0, 18, 30 )
			f14_arg0.Arrow:setAlpha( 1 )
			f14_local6( f14_arg0.Arrow )
			local f14_local7 = function ( f22_arg0 )
				f14_arg0.Glow2:beginAnimation( 50 )
				f14_arg0.Glow2:setAlpha( 0 )
				f14_arg0.Glow2:registerEventHandler( "interrupted_keyframe", f14_arg0.clipInterrupted )
				f14_arg0.Glow2:registerEventHandler( "transition_complete_keyframe", f14_arg0.clipFinished )
			end
			
			f14_arg0.Glow2:completeAnimation()
			f14_arg0.Glow2:setAlpha( 1 )
			f14_local7( f14_arg0.Glow2 )
			f14_arg0.Image:completeAnimation()
			f14_arg0.Image:setAlpha( 0 )
			f14_arg0.clipFinished( f14_arg0.Image )
		end,
		GainFocus = function ( f23_arg0, f23_arg1 )
			f23_arg0:__resetProperties()
			f23_arg0:setupElementClipCounter( 9 )
			local f23_local0 = function ( f24_arg0 )
				f23_arg0.FEButtonPanelShaderContainer:beginAnimation( 50 )
				f23_arg0.FEButtonPanelShaderContainer:setZoom( 0 )
				f23_arg0.FEButtonPanelShaderContainer:registerEventHandler( "interrupted_keyframe", f23_arg0.clipInterrupted )
				f23_arg0.FEButtonPanelShaderContainer:registerEventHandler( "transition_complete_keyframe", f23_arg0.clipFinished )
			end
			
			f23_arg0.FEButtonPanelShaderContainer:completeAnimation()
			f23_arg0.FEButtonPanelShaderContainer:setRGB( 0.5, 0.5, 0.5 )
			f23_arg0.FEButtonPanelShaderContainer:setAlpha( 0 )
			f23_arg0.FEButtonPanelShaderContainer:setZoom( -10 )
			f23_local0( f23_arg0.FEButtonPanelShaderContainer )
			local f23_local1 = function ( f25_arg0 )
				f23_arg0.FEButtonIdle:beginAnimation( 50 )
				f23_arg0.FEButtonIdle:setAlpha( 0 )
				f23_arg0.FEButtonIdle:setZoom( 10 )
				f23_arg0.FEButtonIdle:registerEventHandler( "interrupted_keyframe", f23_arg0.clipInterrupted )
				f23_arg0.FEButtonIdle:registerEventHandler( "transition_complete_keyframe", f23_arg0.clipFinished )
			end
			
			f23_arg0.FEButtonIdle:completeAnimation()
			f23_arg0.FEButtonIdle:setAlpha( 1 )
			f23_arg0.FEButtonIdle:setZoom( 0 )
			f23_local1( f23_arg0.FEButtonIdle )
			local f23_local2 = function ( f26_arg0 )
				f23_arg0.FEButtonFocus:beginAnimation( 50 )
				f23_arg0.FEButtonFocus:setAlpha( 1 )
				f23_arg0.FEButtonFocus:setZoom( 10 )
				f23_arg0.FEButtonFocus:registerEventHandler( "interrupted_keyframe", f23_arg0.clipInterrupted )
				f23_arg0.FEButtonFocus:registerEventHandler( "transition_complete_keyframe", f23_arg0.clipFinished )
			end
			
			f23_arg0.FEButtonFocus:completeAnimation()
			f23_arg0.FEButtonFocus:setLeftRight( 0, 1, 0, 0 )
			f23_arg0.FEButtonFocus:setTopBottom( 0.5, 0.5, -21, 21 )
			f23_arg0.FEButtonFocus:setAlpha( 0 )
			f23_arg0.FEButtonFocus:setZoom( 0 )
			f23_local2( f23_arg0.FEButtonFocus )
			local f23_local3 = function ( f27_arg0 )
				f23_arg0.Glow:beginAnimation( 50 )
				f23_arg0.Glow:setAlpha( 0.45 )
				f23_arg0.Glow:registerEventHandler( "interrupted_keyframe", f23_arg0.clipInterrupted )
				f23_arg0.Glow:registerEventHandler( "transition_complete_keyframe", f23_arg0.clipFinished )
			end
			
			f23_arg0.Glow:completeAnimation()
			f23_arg0.Glow:setAlpha( 0 )
			f23_local3( f23_arg0.Glow )
			local f23_local4 = function ( f28_arg0 )
				f23_arg0.btnDisplayText:beginAnimation( 50 )
				f23_arg0.btnDisplayText:setAlpha( 0 )
				f23_arg0.btnDisplayText:setZoom( 10 )
				f23_arg0.btnDisplayText:registerEventHandler( "interrupted_keyframe", f23_arg0.clipInterrupted )
				f23_arg0.btnDisplayText:registerEventHandler( "transition_complete_keyframe", f23_arg0.clipFinished )
			end
			
			f23_arg0.btnDisplayText:completeAnimation()
			f23_arg0.btnDisplayText:setAlpha( 1 )
			f23_arg0.btnDisplayText:setZoom( 0 )
			f23_local4( f23_arg0.btnDisplayText )
			local f23_local5 = function ( f29_arg0 )
				f23_arg0.btnDisplayTextStroke:beginAnimation( 50 )
				f23_arg0.btnDisplayTextStroke:setAlpha( 1 )
				f23_arg0.btnDisplayTextStroke:setZoom( 10 )
				f23_arg0.btnDisplayTextStroke:registerEventHandler( "interrupted_keyframe", f23_arg0.clipInterrupted )
				f23_arg0.btnDisplayTextStroke:registerEventHandler( "transition_complete_keyframe", f23_arg0.clipFinished )
			end
			
			f23_arg0.btnDisplayTextStroke:completeAnimation()
			f23_arg0.btnDisplayTextStroke:setAlpha( 0 )
			f23_arg0.btnDisplayTextStroke:setZoom( 0 )
			f23_local5( f23_arg0.btnDisplayTextStroke )
			local f23_local6 = function ( f30_arg0 )
				f23_arg0.Arrow:beginAnimation( 50 )
				f23_arg0.Arrow:setLeftRight( 0, 0, -30, -18 )
				f23_arg0.Arrow:setAlpha( 1 )
				f23_arg0.Arrow:registerEventHandler( "interrupted_keyframe", f23_arg0.clipInterrupted )
				f23_arg0.Arrow:registerEventHandler( "transition_complete_keyframe", f23_arg0.clipFinished )
			end
			
			f23_arg0.Arrow:completeAnimation()
			f23_arg0.Arrow:setLeftRight( 0, 0, 4, 16 )
			f23_arg0.Arrow:setTopBottom( 0, 0, 18, 30 )
			f23_arg0.Arrow:setAlpha( 0 )
			f23_local6( f23_arg0.Arrow )
			local f23_local7 = function ( f31_arg0 )
				f23_arg0.Glow2:beginAnimation( 50 )
				f23_arg0.Glow2:setAlpha( 1 )
				f23_arg0.Glow2:registerEventHandler( "interrupted_keyframe", f23_arg0.clipInterrupted )
				f23_arg0.Glow2:registerEventHandler( "transition_complete_keyframe", f23_arg0.clipFinished )
			end
			
			f23_arg0.Glow2:completeAnimation()
			f23_arg0.Glow2:setAlpha( 0 )
			f23_local7( f23_arg0.Glow2 )
			f23_arg0.Image:completeAnimation()
			f23_arg0.Image:setAlpha( 0 )
			f23_arg0.clipFinished( f23_arg0.Image )
		end
	},
	ImageVisible = {
		DefaultClip = function ( f32_arg0, f32_arg1 )
			f32_arg0:__resetProperties()
			f32_arg0:setupElementClipCounter( 1 )
			f32_arg0.FEButtonFocus:completeAnimation()
			f32_arg0.FEButtonFocus:setLeftRight( 0, 1, 0, 0 )
			f32_arg0.FEButtonFocus:setTopBottom( 0.5, 0.5, -1, 3 )
			f32_arg0.clipFinished( f32_arg0.FEButtonFocus )
		end,
		Focus = function ( f33_arg0, f33_arg1 )
			f33_arg0:__resetProperties()
			f33_arg0:setupElementClipCounter( 7 )
			f33_arg0.FEButtonPanelShaderContainer:completeAnimation()
			f33_arg0.FEButtonPanelShaderContainer:setZoom( 0 )
			f33_arg0.clipFinished( f33_arg0.FEButtonPanelShaderContainer )
			f33_arg0.FEButtonIdle:completeAnimation()
			f33_arg0.FEButtonIdle:setZoom( 10 )
			f33_arg0.clipFinished( f33_arg0.FEButtonIdle )
			f33_arg0.FEButtonFocus:completeAnimation()
			f33_arg0.FEButtonFocus:setZoom( 10 )
			f33_arg0.clipFinished( f33_arg0.FEButtonFocus )
			f33_arg0.btnDisplayText:completeAnimation()
			f33_arg0.btnDisplayText:setZoom( 10 )
			f33_arg0.clipFinished( f33_arg0.btnDisplayText )
			f33_arg0.btnDisplayTextStroke:completeAnimation()
			f33_arg0.btnDisplayTextStroke:setZoom( 10 )
			f33_arg0.clipFinished( f33_arg0.btnDisplayTextStroke )
			f33_arg0.Arrow:completeAnimation()
			f33_arg0.Arrow:setLeftRight( 0, 0, -30, -18 )
			f33_arg0.Arrow:setTopBottom( 0, 0, 18, 30 )
			f33_arg0.clipFinished( f33_arg0.Arrow )
			f33_arg0.Image:completeAnimation()
			f33_arg0.Image:setRGB( ColorSet.T8__OCHRE.r, ColorSet.T8__OCHRE.g, ColorSet.T8__OCHRE.b )
			f33_arg0.clipFinished( f33_arg0.Image )
		end,
		LoseFocus = function ( f34_arg0, f34_arg1 )
			f34_arg0:__resetProperties()
			f34_arg0:setupElementClipCounter( 7 )
			f34_arg0.FEButtonPanelShaderContainer:completeAnimation()
			f34_arg0.FEButtonPanelShaderContainer:setZoom( 0 )
			f34_arg0.clipFinished( f34_arg0.FEButtonPanelShaderContainer )
			f34_arg0.FEButtonIdle:completeAnimation()
			f34_arg0.FEButtonIdle:setZoom( 10 )
			f34_arg0.clipFinished( f34_arg0.FEButtonIdle )
			f34_arg0.FEButtonFocus:completeAnimation()
			f34_arg0.FEButtonFocus:setZoom( 10 )
			f34_arg0.clipFinished( f34_arg0.FEButtonFocus )
			f34_arg0.btnDisplayText:completeAnimation()
			f34_arg0.btnDisplayText:setZoom( 10 )
			f34_arg0.clipFinished( f34_arg0.btnDisplayText )
			f34_arg0.btnDisplayTextStroke:completeAnimation()
			f34_arg0.btnDisplayTextStroke:setZoom( 10 )
			f34_arg0.clipFinished( f34_arg0.btnDisplayTextStroke )
			f34_arg0.Arrow:completeAnimation()
			f34_arg0.Arrow:setLeftRight( 0, 0, -30, -18 )
			f34_arg0.Arrow:setTopBottom( 0, 0, 18, 30 )
			f34_arg0.clipFinished( f34_arg0.Arrow )
			local f34_local0 = function ( f35_arg0 )
				f34_arg0.Image:beginAnimation( 50 )
				f34_arg0.Image:setRGB( 1, 1, 1 )
				f34_arg0.Image:registerEventHandler( "interrupted_keyframe", f34_arg0.clipInterrupted )
				f34_arg0.Image:registerEventHandler( "transition_complete_keyframe", f34_arg0.clipFinished )
			end
			
			f34_arg0.Image:completeAnimation()
			f34_arg0.Image:setRGB( ColorSet.T8__OCHRE.r, ColorSet.T8__OCHRE.g, ColorSet.T8__OCHRE.b )
			f34_local0( f34_arg0.Image )
		end,
		GainFocus = function ( f36_arg0, f36_arg1 )
			f36_arg0:__resetProperties()
			f36_arg0:setupElementClipCounter( 1 )
			local f36_local0 = function ( f37_arg0 )
				f36_arg0.Image:beginAnimation( 50 )
				f36_arg0.Image:setRGB( 0.87, 1, 0.04 )
				f36_arg0.Image:registerEventHandler( "interrupted_keyframe", f36_arg0.clipInterrupted )
				f36_arg0.Image:registerEventHandler( "transition_complete_keyframe", f36_arg0.clipFinished )
			end
			
			f36_arg0.Image:completeAnimation()
			f36_arg0.Image:setRGB( 1, 1, 1 )
			f36_local0( f36_arg0.Image )
		end
	},
	Disabled = {
		DefaultClip = function ( f38_arg0, f38_arg1 )
			f38_arg0:__resetProperties()
			f38_arg0:setupElementClipCounter( 5 )
			f38_arg0.FEButtonPanelShaderContainer:completeAnimation()
			f38_arg0.FEButtonPanelShaderContainer:setAlpha( 0.4 )
			f38_arg0.clipFinished( f38_arg0.FEButtonPanelShaderContainer )
			f38_arg0.FEButtonIdle:completeAnimation()
			f38_arg0.FEButtonIdle:setAlpha( 0.75 )
			f38_arg0.clipFinished( f38_arg0.FEButtonIdle )
			f38_arg0.FEButtonFocus:completeAnimation()
			f38_arg0.FEButtonFocus:setLeftRight( 0, 1, 0, 0 )
			f38_arg0.FEButtonFocus:setTopBottom( 0.5, 0.5, -1, 3 )
			f38_arg0.clipFinished( f38_arg0.FEButtonFocus )
			f38_arg0.btnDisplayText:completeAnimation()
			f38_arg0.btnDisplayText:setAlpha( 1 )
			f38_arg0.clipFinished( f38_arg0.btnDisplayText )
			f38_arg0.Image:completeAnimation()
			f38_arg0.Image:setAlpha( 0 )
			f38_arg0.clipFinished( f38_arg0.Image )
		end,
		Focus = function ( f39_arg0, f39_arg1 )
			f39_arg0:__resetProperties()
			f39_arg0:setupElementClipCounter( 9 )
			f39_arg0.FEButtonPanelShaderContainer:completeAnimation()
			f39_arg0.FEButtonPanelShaderContainer:setZoom( 0 )
			f39_arg0.clipFinished( f39_arg0.FEButtonPanelShaderContainer )
			f39_arg0.FEButtonIdle:completeAnimation()
			f39_arg0.FEButtonIdle:setZoom( 10 )
			f39_arg0.clipFinished( f39_arg0.FEButtonIdle )
			f39_arg0.FEButtonFocus:completeAnimation()
			f39_arg0.FEButtonFocus:setAlpha( 0.25 )
			f39_arg0.FEButtonFocus:setZoom( 10 )
			f39_arg0.clipFinished( f39_arg0.FEButtonFocus )
			f39_arg0.Glow:completeAnimation()
			f39_arg0.Glow:setAlpha( 0.1 )
			f39_arg0.clipFinished( f39_arg0.Glow )
			f39_arg0.btnDisplayText:completeAnimation()
			f39_arg0.btnDisplayText:setZoom( 10 )
			f39_arg0.clipFinished( f39_arg0.btnDisplayText )
			f39_arg0.btnDisplayTextStroke:completeAnimation()
			f39_arg0.btnDisplayTextStroke:setAlpha( 1 )
			f39_arg0.btnDisplayTextStroke:setZoom( 10 )
			f39_arg0.clipFinished( f39_arg0.btnDisplayTextStroke )
			f39_arg0.Arrow:completeAnimation()
			f39_arg0.Arrow:setLeftRight( 0, 0, -30, -18 )
			f39_arg0.Arrow:setTopBottom( 0, 0, 18, 30 )
			f39_arg0.Arrow:setAlpha( 1 )
			f39_arg0.clipFinished( f39_arg0.Arrow )
			f39_arg0.Glow2:completeAnimation()
			f39_arg0.Glow2:setAlpha( 0.25 )
			f39_arg0.clipFinished( f39_arg0.Glow2 )
			f39_arg0.Image:completeAnimation()
			f39_arg0.Image:setAlpha( 0 )
			f39_arg0.clipFinished( f39_arg0.Image )
		end,
		LoseFocus = function ( f40_arg0, f40_arg1 )
			f40_arg0:__resetProperties()
			f40_arg0:setupElementClipCounter( 9 )
			local f40_local0 = function ( f41_arg0 )
				f40_arg0.FEButtonPanelShaderContainer:beginAnimation( 50 )
				f40_arg0.FEButtonPanelShaderContainer:setZoom( -10 )
				f40_arg0.FEButtonPanelShaderContainer:registerEventHandler( "interrupted_keyframe", f40_arg0.clipInterrupted )
				f40_arg0.FEButtonPanelShaderContainer:registerEventHandler( "transition_complete_keyframe", f40_arg0.clipFinished )
			end
			
			f40_arg0.FEButtonPanelShaderContainer:completeAnimation()
			f40_arg0.FEButtonPanelShaderContainer:setRGB( 0.5, 0.5, 0.5 )
			f40_arg0.FEButtonPanelShaderContainer:setAlpha( 0 )
			f40_arg0.FEButtonPanelShaderContainer:setZoom( 0 )
			f40_local0( f40_arg0.FEButtonPanelShaderContainer )
			local f40_local1 = function ( f42_arg0 )
				f40_arg0.FEButtonIdle:beginAnimation( 50 )
				f40_arg0.FEButtonIdle:setZoom( 0 )
				f40_arg0.FEButtonIdle:registerEventHandler( "interrupted_keyframe", f40_arg0.clipInterrupted )
				f40_arg0.FEButtonIdle:registerEventHandler( "transition_complete_keyframe", f40_arg0.clipFinished )
			end
			
			f40_arg0.FEButtonIdle:completeAnimation()
			f40_arg0.FEButtonIdle:setAlpha( 0 )
			f40_arg0.FEButtonIdle:setZoom( 10 )
			f40_local1( f40_arg0.FEButtonIdle )
			local f40_local2 = function ( f43_arg0 )
				f40_arg0.FEButtonFocus:beginAnimation( 50 )
				f40_arg0.FEButtonFocus:setAlpha( 0 )
				f40_arg0.FEButtonFocus:setZoom( 0 )
				f40_arg0.FEButtonFocus:registerEventHandler( "interrupted_keyframe", f40_arg0.clipInterrupted )
				f40_arg0.FEButtonFocus:registerEventHandler( "transition_complete_keyframe", f40_arg0.clipFinished )
			end
			
			f40_arg0.FEButtonFocus:completeAnimation()
			f40_arg0.FEButtonFocus:setLeftRight( 0, 1, 0, 0 )
			f40_arg0.FEButtonFocus:setTopBottom( 0.5, 0.5, -21, 21 )
			f40_arg0.FEButtonFocus:setAlpha( 0.25 )
			f40_arg0.FEButtonFocus:setZoom( 10 )
			f40_local2( f40_arg0.FEButtonFocus )
			local f40_local3 = function ( f44_arg0 )
				f40_arg0.Glow:beginAnimation( 50 )
				f40_arg0.Glow:setAlpha( 0 )
				f40_arg0.Glow:registerEventHandler( "interrupted_keyframe", f40_arg0.clipInterrupted )
				f40_arg0.Glow:registerEventHandler( "transition_complete_keyframe", f40_arg0.clipFinished )
			end
			
			f40_arg0.Glow:completeAnimation()
			f40_arg0.Glow:setAlpha( 0.1 )
			f40_local3( f40_arg0.Glow )
			local f40_local4 = function ( f45_arg0 )
				f40_arg0.btnDisplayText:beginAnimation( 50 )
				f40_arg0.btnDisplayText:setAlpha( 0.5 )
				f40_arg0.btnDisplayText:setZoom( 0 )
				f40_arg0.btnDisplayText:registerEventHandler( "interrupted_keyframe", f40_arg0.clipInterrupted )
				f40_arg0.btnDisplayText:registerEventHandler( "transition_complete_keyframe", f40_arg0.clipFinished )
			end
			
			f40_arg0.btnDisplayText:completeAnimation()
			f40_arg0.btnDisplayText:setAlpha( 0 )
			f40_arg0.btnDisplayText:setZoom( 10 )
			f40_local4( f40_arg0.btnDisplayText )
			local f40_local5 = function ( f46_arg0 )
				f40_arg0.btnDisplayTextStroke:beginAnimation( 50 )
				f40_arg0.btnDisplayTextStroke:setAlpha( 0 )
				f40_arg0.btnDisplayTextStroke:setZoom( 0 )
				f40_arg0.btnDisplayTextStroke:registerEventHandler( "interrupted_keyframe", f40_arg0.clipInterrupted )
				f40_arg0.btnDisplayTextStroke:registerEventHandler( "transition_complete_keyframe", f40_arg0.clipFinished )
			end
			
			f40_arg0.btnDisplayTextStroke:completeAnimation()
			f40_arg0.btnDisplayTextStroke:setAlpha( 1 )
			f40_arg0.btnDisplayTextStroke:setZoom( 10 )
			f40_local5( f40_arg0.btnDisplayTextStroke )
			local f40_local6 = function ( f47_arg0 )
				f40_arg0.Arrow:beginAnimation( 50 )
				f40_arg0.Arrow:setLeftRight( 0, 0, 4, 16 )
				f40_arg0.Arrow:setAlpha( 0 )
				f40_arg0.Arrow:registerEventHandler( "interrupted_keyframe", f40_arg0.clipInterrupted )
				f40_arg0.Arrow:registerEventHandler( "transition_complete_keyframe", f40_arg0.clipFinished )
			end
			
			f40_arg0.Arrow:completeAnimation()
			f40_arg0.Arrow:setLeftRight( 0, 0, -30, -18 )
			f40_arg0.Arrow:setTopBottom( 0, 0, 18, 30 )
			f40_arg0.Arrow:setAlpha( 1 )
			f40_local6( f40_arg0.Arrow )
			local f40_local7 = function ( f48_arg0 )
				f40_arg0.Glow2:beginAnimation( 50 )
				f40_arg0.Glow2:setAlpha( 0 )
				f40_arg0.Glow2:registerEventHandler( "interrupted_keyframe", f40_arg0.clipInterrupted )
				f40_arg0.Glow2:registerEventHandler( "transition_complete_keyframe", f40_arg0.clipFinished )
			end
			
			f40_arg0.Glow2:completeAnimation()
			f40_arg0.Glow2:setAlpha( 0.25 )
			f40_local7( f40_arg0.Glow2 )
			f40_arg0.Image:completeAnimation()
			f40_arg0.Image:setAlpha( 0 )
			f40_arg0.clipFinished( f40_arg0.Image )
		end,
		GainFocus = function ( f49_arg0, f49_arg1 )
			f49_arg0:__resetProperties()
			f49_arg0:setupElementClipCounter( 9 )
			local f49_local0 = function ( f50_arg0 )
				f49_arg0.FEButtonPanelShaderContainer:beginAnimation( 50 )
				f49_arg0.FEButtonPanelShaderContainer:setZoom( 0 )
				f49_arg0.FEButtonPanelShaderContainer:registerEventHandler( "interrupted_keyframe", f49_arg0.clipInterrupted )
				f49_arg0.FEButtonPanelShaderContainer:registerEventHandler( "transition_complete_keyframe", f49_arg0.clipFinished )
			end
			
			f49_arg0.FEButtonPanelShaderContainer:completeAnimation()
			f49_arg0.FEButtonPanelShaderContainer:setRGB( 0.5, 0.5, 0.5 )
			f49_arg0.FEButtonPanelShaderContainer:setAlpha( 0 )
			f49_arg0.FEButtonPanelShaderContainer:setZoom( -10 )
			f49_local0( f49_arg0.FEButtonPanelShaderContainer )
			local f49_local1 = function ( f51_arg0 )
				f49_arg0.FEButtonIdle:beginAnimation( 50 )
				f49_arg0.FEButtonIdle:setZoom( 10 )
				f49_arg0.FEButtonIdle:registerEventHandler( "interrupted_keyframe", f49_arg0.clipInterrupted )
				f49_arg0.FEButtonIdle:registerEventHandler( "transition_complete_keyframe", f49_arg0.clipFinished )
			end
			
			f49_arg0.FEButtonIdle:completeAnimation()
			f49_arg0.FEButtonIdle:setAlpha( 0 )
			f49_arg0.FEButtonIdle:setZoom( 0 )
			f49_local1( f49_arg0.FEButtonIdle )
			local f49_local2 = function ( f52_arg0 )
				f49_arg0.FEButtonFocus:beginAnimation( 50 )
				f49_arg0.FEButtonFocus:setAlpha( 0.25 )
				f49_arg0.FEButtonFocus:setZoom( 10 )
				f49_arg0.FEButtonFocus:registerEventHandler( "interrupted_keyframe", f49_arg0.clipInterrupted )
				f49_arg0.FEButtonFocus:registerEventHandler( "transition_complete_keyframe", f49_arg0.clipFinished )
			end
			
			f49_arg0.FEButtonFocus:completeAnimation()
			f49_arg0.FEButtonFocus:setLeftRight( 0, 1, 0, 0 )
			f49_arg0.FEButtonFocus:setTopBottom( 0.5, 0.5, -21, 21 )
			f49_arg0.FEButtonFocus:setAlpha( 0 )
			f49_arg0.FEButtonFocus:setZoom( 0 )
			f49_local2( f49_arg0.FEButtonFocus )
			local f49_local3 = function ( f53_arg0 )
				f49_arg0.Glow:beginAnimation( 50 )
				f49_arg0.Glow:setAlpha( 0.1 )
				f49_arg0.Glow:registerEventHandler( "interrupted_keyframe", f49_arg0.clipInterrupted )
				f49_arg0.Glow:registerEventHandler( "transition_complete_keyframe", f49_arg0.clipFinished )
			end
			
			f49_arg0.Glow:completeAnimation()
			f49_arg0.Glow:setLeftRight( 0, 1, -3, 3 )
			f49_arg0.Glow:setTopBottom( 0, 1, -22, 22 )
			f49_arg0.Glow:setAlpha( 0 )
			f49_local3( f49_arg0.Glow )
			local f49_local4 = function ( f54_arg0 )
				f49_arg0.btnDisplayText:beginAnimation( 50 )
				f49_arg0.btnDisplayText:setAlpha( 0 )
				f49_arg0.btnDisplayText:setZoom( 10 )
				f49_arg0.btnDisplayText:registerEventHandler( "interrupted_keyframe", f49_arg0.clipInterrupted )
				f49_arg0.btnDisplayText:registerEventHandler( "transition_complete_keyframe", f49_arg0.clipFinished )
			end
			
			f49_arg0.btnDisplayText:completeAnimation()
			f49_arg0.btnDisplayText:setRGB( 0.79, 0.79, 0.79 )
			f49_arg0.btnDisplayText:setAlpha( 0.5 )
			f49_arg0.btnDisplayText:setZoom( 0 )
			f49_local4( f49_arg0.btnDisplayText )
			local f49_local5 = function ( f55_arg0 )
				f49_arg0.btnDisplayTextStroke:beginAnimation( 50 )
				f49_arg0.btnDisplayTextStroke:setAlpha( 1 )
				f49_arg0.btnDisplayTextStroke:setZoom( 10 )
				f49_arg0.btnDisplayTextStroke:registerEventHandler( "interrupted_keyframe", f49_arg0.clipInterrupted )
				f49_arg0.btnDisplayTextStroke:registerEventHandler( "transition_complete_keyframe", f49_arg0.clipFinished )
			end
			
			f49_arg0.btnDisplayTextStroke:completeAnimation()
			f49_arg0.btnDisplayTextStroke:setAlpha( 0 )
			f49_arg0.btnDisplayTextStroke:setZoom( 0 )
			f49_local5( f49_arg0.btnDisplayTextStroke )
			local f49_local6 = function ( f56_arg0 )
				f49_arg0.Arrow:beginAnimation( 50 )
				f49_arg0.Arrow:setLeftRight( 0, 0, -30, -18 )
				f49_arg0.Arrow:setAlpha( 1 )
				f49_arg0.Arrow:registerEventHandler( "interrupted_keyframe", f49_arg0.clipInterrupted )
				f49_arg0.Arrow:registerEventHandler( "transition_complete_keyframe", f49_arg0.clipFinished )
			end
			
			f49_arg0.Arrow:completeAnimation()
			f49_arg0.Arrow:setLeftRight( 0, 0, 4, 16 )
			f49_arg0.Arrow:setTopBottom( 0, 0, 18, 30 )
			f49_arg0.Arrow:setAlpha( 0 )
			f49_local6( f49_arg0.Arrow )
			local f49_local7 = function ( f57_arg0 )
				f49_arg0.Glow2:beginAnimation( 50 )
				f49_arg0.Glow2:setAlpha( 0.25 )
				f49_arg0.Glow2:registerEventHandler( "interrupted_keyframe", f49_arg0.clipInterrupted )
				f49_arg0.Glow2:registerEventHandler( "transition_complete_keyframe", f49_arg0.clipFinished )
			end
			
			f49_arg0.Glow2:completeAnimation()
			f49_arg0.Glow2:setAlpha( 0 )
			f49_local7( f49_arg0.Glow2 )
			f49_arg0.Image:completeAnimation()
			f49_arg0.Image:setAlpha( 0 )
			f49_arg0.clipFinished( f49_arg0.Image )
		end
	}
}
CoD.CACGenericButton.__onClose = function ( f58_arg0 )
	f58_arg0.FEButtonPanelShaderContainer:close()
	f58_arg0.FEButtonIdle:close()
	f58_arg0.FEButtonFocus:close()
	f58_arg0.btnDisplayText:close()
	f58_arg0.btnDisplayTextStroke:close()
	f58_arg0.Image:close()
end

