require( "ui/uieditor/widgets/mphudwidgets/waypoint_contestedarrowwidget" )

CoD.SDDemObjectiveNotification_BombPlanted = InheritFrom( LUI.UIElement )
CoD.SDDemObjectiveNotification_BombPlanted.__defaultWidth = 142
CoD.SDDemObjectiveNotification_BombPlanted.__defaultHeight = 60
CoD.SDDemObjectiveNotification_BombPlanted.new = function ( f1_arg0, f1_arg1, f1_arg2, f1_arg3, f1_arg4, f1_arg5, f1_arg6, f1_arg7, f1_arg8, f1_arg9 )
	local self = LUI.UIElement.new( f1_arg2, f1_arg3, f1_arg4, f1_arg5, f1_arg6, f1_arg7, f1_arg8, f1_arg9 )
	self:setClass( CoD.SDDemObjectiveNotification_BombPlanted )
	self.id = "SDDemObjectiveNotification_BombPlanted"
	self.soundSet = "default"
	self.anyChildUsesUpdateState = true
	f1_arg0:addElementToPendingUpdateStateList( self )
	
	local ArrowRight = CoD.Waypoint_ContestedArrowWidget.new( f1_arg0, f1_arg1, 1, 1, -49, -25, 0, 0, 18, 42 )
	ArrowRight:setScale( 0.8, 0.8 )
	ArrowRight:subscribeToGlobalModel( f1_arg1, "HUDItems", "colorBlindSensitiveEnemyColor", function ( model )
		local f2_local0 = model:get()
		if f2_local0 ~= nil then
			ArrowRight:setRGB( f2_local0 )
		end
	end )
	self:addElement( ArrowRight )
	self.ArrowRight = ArrowRight
	
	local ArrowLeft = CoD.Waypoint_ContestedArrowWidget.new( f1_arg0, f1_arg1, 0, 0, 25, 49, 0, 0, 18, 42 )
	ArrowLeft:setYRot( 180 )
	ArrowLeft:setScale( 0.8, 0.8 )
	ArrowLeft:subscribeToGlobalModel( f1_arg1, "HUDItems", "colorBlindSensitiveEnemyColor", function ( model )
		local f3_local0 = model:get()
		if f3_local0 ~= nil then
			ArrowLeft:setRGB( f3_local0 )
		end
	end )
	self:addElement( ArrowLeft )
	self.ArrowLeft = ArrowLeft
	
	local EnemyBombA = LUI.UIImage.new( 0.5, 0.5, -24, 24, 0, 0, 6, 54 )
	EnemyBombA:setImage( RegisterImage( "ui_icon_waypoint_bomb" ) )
	EnemyBombA:subscribeToGlobalModel( f1_arg1, "HUDItems", "colorBlindSensitiveEnemyColor", function ( model )
		local f4_local0 = model:get()
		if f4_local0 ~= nil then
			EnemyBombA:setRGB( f4_local0 )
		end
	end )
	self:addElement( EnemyBombA )
	self.EnemyBombA = EnemyBombA
	
	local EnemyBombB = LUI.UIImage.new( 0.5, 0.5, -24, 24, 0, 0, 6, 54 )
	EnemyBombB:setImage( RegisterImage( "ui_icon_waypoint_bomb" ) )
	EnemyBombB:subscribeToGlobalModel( f1_arg1, "HUDItems", "colorBlindSensitiveEnemyColor", function ( model )
		local f5_local0 = model:get()
		if f5_local0 ~= nil then
			EnemyBombB:setRGB( f5_local0 )
		end
	end )
	self:addElement( EnemyBombB )
	self.EnemyBombB = EnemyBombB
	
	local FriendlyBombA = LUI.UIImage.new( 0, 0, 15, 63, 0, 0, 6, 54 )
	FriendlyBombA:setAlpha( 0 )
	FriendlyBombA:setImage( RegisterImage( "ui_icon_waypoint_bomb" ) )
	FriendlyBombA:subscribeToGlobalModel( f1_arg1, "HUDItems", "colorBlindSensitiveFriendlyColor", function ( model )
		local f6_local0 = model:get()
		if f6_local0 ~= nil then
			FriendlyBombA:setRGB( f6_local0 )
		end
	end )
	self:addElement( FriendlyBombA )
	self.FriendlyBombA = FriendlyBombA
	
	local FriendlyBombB = LUI.UIImage.new( 1, 1, -63, -15, 0, 0, 6, 54 )
	FriendlyBombB:setAlpha( 0 )
	FriendlyBombB:setImage( RegisterImage( "ui_icon_waypoint_bomb" ) )
	FriendlyBombB:subscribeToGlobalModel( f1_arg1, "HUDItems", "colorBlindSensitiveFriendlyColor", function ( model )
		local f7_local0 = model:get()
		if f7_local0 ~= nil then
			FriendlyBombB:setRGB( f7_local0 )
		end
	end )
	self:addElement( FriendlyBombB )
	self.FriendlyBombB = FriendlyBombB
	
	local BombLabel = LUI.UIText.new( 0, 0, 55.5, 86.5, 0, 0, 12.5, 45.5 )
	BombLabel:setText( CoD.BaseUtility.AlreadyLocalized( "A" ) )
	BombLabel:setTTF( "ttmussels_demibold" )
	BombLabel:setMaterial( LUI.UIImage.GetCachedMaterial( 0x6250C6FCAC36BD4 ) )
	BombLabel:setShaderVector( 0, 0.25, 0, 0, 0 )
	BombLabel:setShaderVector( 1, 0, 0, 0, 1 )
	BombLabel:setAlignment( Enum.LUIAlignment[0xFEEB12BCB0D7041] )
	BombLabel:setAlignment( Enum.LUIAlignment[0xF41D595A2B0EDF3] )
	self:addElement( BombLabel )
	self.BombLabel = BombLabel
	
	LUI.OverrideFunction_CallOriginalSecond( self, "close", self.__onClose )
	
	if PostLoadFunc then
		PostLoadFunc( self, f1_arg1, f1_arg0 )
	end
	
	return self
end

CoD.SDDemObjectiveNotification_BombPlanted.__resetProperties = function ( f8_arg0 )
	f8_arg0.ArrowRight:completeAnimation()
	f8_arg0.ArrowLeft:completeAnimation()
	f8_arg0.EnemyBombA:completeAnimation()
	f8_arg0.EnemyBombB:completeAnimation()
	f8_arg0.FriendlyBombA:completeAnimation()
	f8_arg0.FriendlyBombB:completeAnimation()
	f8_arg0.BombLabel:completeAnimation()
	f8_arg0.ArrowRight:setAlpha( 1 )
	f8_arg0.ArrowLeft:setAlpha( 1 )
	f8_arg0.EnemyBombA:setAlpha( 1 )
	f8_arg0.EnemyBombB:setAlpha( 1 )
	f8_arg0.FriendlyBombA:setAlpha( 0 )
	f8_arg0.FriendlyBombB:setAlpha( 0 )
	f8_arg0.BombLabel:setLeftRight( 0, 0, 55.5, 86.5 )
	f8_arg0.BombLabel:setTopBottom( 0, 0, 12.5, 45.5 )
	f8_arg0.BombLabel:setAlpha( 1 )
	f8_arg0.BombLabel:setText( CoD.BaseUtility.AlreadyLocalized( "A" ) )
end

CoD.SDDemObjectiveNotification_BombPlanted.__clipsPerState = {
	DefaultState = {
		DefaultClip = function ( f9_arg0, f9_arg1 )
			f9_arg0:__resetProperties()
			f9_arg0:setupElementClipCounter( 7 )
			f9_arg0.ArrowRight:completeAnimation()
			f9_arg0.ArrowRight:setAlpha( 0 )
			f9_arg0.clipFinished( f9_arg0.ArrowRight )
			f9_arg0.ArrowLeft:completeAnimation()
			f9_arg0.ArrowLeft:setAlpha( 0 )
			f9_arg0.clipFinished( f9_arg0.ArrowLeft )
			f9_arg0.EnemyBombA:completeAnimation()
			f9_arg0.EnemyBombA:setAlpha( 0 )
			f9_arg0.clipFinished( f9_arg0.EnemyBombA )
			f9_arg0.EnemyBombB:completeAnimation()
			f9_arg0.EnemyBombB:setAlpha( 0 )
			f9_arg0.clipFinished( f9_arg0.EnemyBombB )
			f9_arg0.FriendlyBombA:completeAnimation()
			f9_arg0.FriendlyBombA:setAlpha( 0 )
			f9_arg0.clipFinished( f9_arg0.FriendlyBombA )
			f9_arg0.FriendlyBombB:completeAnimation()
			f9_arg0.FriendlyBombB:setAlpha( 0 )
			f9_arg0.clipFinished( f9_arg0.FriendlyBombB )
			f9_arg0.BombLabel:completeAnimation()
			f9_arg0.BombLabel:setAlpha( 0 )
			f9_arg0.clipFinished( f9_arg0.BombLabel )
		end,
		DisarmBombA = function ( f10_arg0, f10_arg1 )
			f10_arg0:__resetProperties()
			f10_arg0:setupElementClipCounter( 7 )
			local f10_local0 = function ( f11_arg0 )
				f10_arg0.ArrowRight:beginAnimation( 250 )
				f10_arg0.ArrowRight:setAlpha( 1 )
				f10_arg0.ArrowRight:registerEventHandler( "interrupted_keyframe", f10_arg0.clipInterrupted )
				f10_arg0.ArrowRight:registerEventHandler( "transition_complete_keyframe", f10_arg0.clipFinished )
			end
			
			f10_arg0.ArrowRight:completeAnimation()
			f10_arg0.ArrowRight:setAlpha( 0 )
			f10_local0( f10_arg0.ArrowRight )
			local f10_local1 = function ( f12_arg0 )
				f10_arg0.ArrowLeft:beginAnimation( 250 )
				f10_arg0.ArrowLeft:setAlpha( 1 )
				f10_arg0.ArrowLeft:registerEventHandler( "interrupted_keyframe", f10_arg0.clipInterrupted )
				f10_arg0.ArrowLeft:registerEventHandler( "transition_complete_keyframe", f10_arg0.clipFinished )
			end
			
			f10_arg0.ArrowLeft:completeAnimation()
			f10_arg0.ArrowLeft:setAlpha( 0 )
			f10_local1( f10_arg0.ArrowLeft )
			local f10_local2 = function ( f13_arg0 )
				f10_arg0.EnemyBombA:beginAnimation( 250 )
				f10_arg0.EnemyBombA:setAlpha( 1 )
				f10_arg0.EnemyBombA:registerEventHandler( "interrupted_keyframe", f10_arg0.clipInterrupted )
				f10_arg0.EnemyBombA:registerEventHandler( "transition_complete_keyframe", f10_arg0.clipFinished )
			end
			
			f10_arg0.EnemyBombA:completeAnimation()
			f10_arg0.EnemyBombA:setAlpha( 0 )
			f10_local2( f10_arg0.EnemyBombA )
			f10_arg0.EnemyBombB:completeAnimation()
			f10_arg0.EnemyBombB:setAlpha( 0 )
			f10_arg0.clipFinished( f10_arg0.EnemyBombB )
			f10_arg0.FriendlyBombA:completeAnimation()
			f10_arg0.FriendlyBombA:setAlpha( 0 )
			f10_arg0.clipFinished( f10_arg0.FriendlyBombA )
			f10_arg0.FriendlyBombB:completeAnimation()
			f10_arg0.FriendlyBombB:setAlpha( 0 )
			f10_arg0.clipFinished( f10_arg0.FriendlyBombB )
			local f10_local3 = function ( f14_arg0 )
				f10_arg0.BombLabel:beginAnimation( 250 )
				f10_arg0.BombLabel:setAlpha( 1 )
				f10_arg0.BombLabel:registerEventHandler( "interrupted_keyframe", f10_arg0.clipInterrupted )
				f10_arg0.BombLabel:registerEventHandler( "transition_complete_keyframe", f10_arg0.clipFinished )
			end
			
			f10_arg0.BombLabel:completeAnimation()
			f10_arg0.BombLabel:setLeftRight( 0, 0, 55.5, 86.5 )
			f10_arg0.BombLabel:setTopBottom( 0, 0, 12.5, 45.5 )
			f10_arg0.BombLabel:setAlpha( 0 )
			f10_arg0.BombLabel:setText( CoD.BaseUtility.AlreadyLocalized( "A" ) )
			f10_local3( f10_arg0.BombLabel )
		end,
		DisarmBombB = function ( f15_arg0, f15_arg1 )
			f15_arg0:__resetProperties()
			f15_arg0:setupElementClipCounter( 7 )
			local f15_local0 = function ( f16_arg0 )
				f15_arg0.ArrowRight:beginAnimation( 250 )
				f15_arg0.ArrowRight:setAlpha( 1 )
				f15_arg0.ArrowRight:registerEventHandler( "interrupted_keyframe", f15_arg0.clipInterrupted )
				f15_arg0.ArrowRight:registerEventHandler( "transition_complete_keyframe", f15_arg0.clipFinished )
			end
			
			f15_arg0.ArrowRight:completeAnimation()
			f15_arg0.ArrowRight:setAlpha( 0 )
			f15_local0( f15_arg0.ArrowRight )
			local f15_local1 = function ( f17_arg0 )
				f15_arg0.ArrowLeft:beginAnimation( 250 )
				f15_arg0.ArrowLeft:setAlpha( 1 )
				f15_arg0.ArrowLeft:registerEventHandler( "interrupted_keyframe", f15_arg0.clipInterrupted )
				f15_arg0.ArrowLeft:registerEventHandler( "transition_complete_keyframe", f15_arg0.clipFinished )
			end
			
			f15_arg0.ArrowLeft:completeAnimation()
			f15_arg0.ArrowLeft:setAlpha( 0 )
			f15_local1( f15_arg0.ArrowLeft )
			f15_arg0.EnemyBombA:completeAnimation()
			f15_arg0.EnemyBombA:setAlpha( 0 )
			f15_arg0.clipFinished( f15_arg0.EnemyBombA )
			local f15_local2 = function ( f18_arg0 )
				f15_arg0.EnemyBombB:beginAnimation( 250 )
				f15_arg0.EnemyBombB:setAlpha( 1 )
				f15_arg0.EnemyBombB:registerEventHandler( "interrupted_keyframe", f15_arg0.clipInterrupted )
				f15_arg0.EnemyBombB:registerEventHandler( "transition_complete_keyframe", f15_arg0.clipFinished )
			end
			
			f15_arg0.EnemyBombB:completeAnimation()
			f15_arg0.EnemyBombB:setAlpha( 0 )
			f15_local2( f15_arg0.EnemyBombB )
			f15_arg0.FriendlyBombA:completeAnimation()
			f15_arg0.FriendlyBombA:setAlpha( 0 )
			f15_arg0.clipFinished( f15_arg0.FriendlyBombA )
			f15_arg0.FriendlyBombB:completeAnimation()
			f15_arg0.FriendlyBombB:setAlpha( 0 )
			f15_arg0.clipFinished( f15_arg0.FriendlyBombB )
			local f15_local3 = function ( f19_arg0 )
				f15_arg0.BombLabel:beginAnimation( 250 )
				f15_arg0.BombLabel:setAlpha( 1 )
				f15_arg0.BombLabel:registerEventHandler( "interrupted_keyframe", f15_arg0.clipInterrupted )
				f15_arg0.BombLabel:registerEventHandler( "transition_complete_keyframe", f15_arg0.clipFinished )
			end
			
			f15_arg0.BombLabel:completeAnimation()
			f15_arg0.BombLabel:setLeftRight( 0, 0, 55.5, 86.5 )
			f15_arg0.BombLabel:setTopBottom( 0, 0, 12.5, 45.5 )
			f15_arg0.BombLabel:setAlpha( 0 )
			f15_arg0.BombLabel:setText( CoD.BaseUtility.AlreadyLocalized( "B" ) )
			f15_local3( f15_arg0.BombLabel )
		end,
		DefendBombA = function ( f20_arg0, f20_arg1 )
			f20_arg0:__resetProperties()
			f20_arg0:setupElementClipCounter( 7 )
			f20_arg0.ArrowRight:completeAnimation()
			f20_arg0.ArrowRight:setAlpha( 0 )
			f20_arg0.clipFinished( f20_arg0.ArrowRight )
			f20_arg0.ArrowLeft:completeAnimation()
			f20_arg0.ArrowLeft:setAlpha( 0 )
			f20_arg0.clipFinished( f20_arg0.ArrowLeft )
			f20_arg0.EnemyBombA:completeAnimation()
			f20_arg0.EnemyBombA:setAlpha( 0 )
			f20_arg0.clipFinished( f20_arg0.EnemyBombA )
			f20_arg0.EnemyBombB:completeAnimation()
			f20_arg0.EnemyBombB:setAlpha( 0 )
			f20_arg0.clipFinished( f20_arg0.EnemyBombB )
			local f20_local0 = function ( f21_arg0 )
				f20_arg0.FriendlyBombA:beginAnimation( 250 )
				f20_arg0.FriendlyBombA:setAlpha( 1 )
				f20_arg0.FriendlyBombA:registerEventHandler( "interrupted_keyframe", f20_arg0.clipInterrupted )
				f20_arg0.FriendlyBombA:registerEventHandler( "transition_complete_keyframe", f20_arg0.clipFinished )
			end
			
			f20_arg0.FriendlyBombA:completeAnimation()
			f20_arg0.FriendlyBombA:setAlpha( 0 )
			f20_local0( f20_arg0.FriendlyBombA )
			f20_arg0.FriendlyBombB:completeAnimation()
			f20_arg0.FriendlyBombB:setAlpha( 0 )
			f20_arg0.clipFinished( f20_arg0.FriendlyBombB )
			local f20_local1 = function ( f22_arg0 )
				f20_arg0.BombLabel:beginAnimation( 250 )
				f20_arg0.BombLabel:setAlpha( 1 )
				f20_arg0.BombLabel:registerEventHandler( "interrupted_keyframe", f20_arg0.clipInterrupted )
				f20_arg0.BombLabel:registerEventHandler( "transition_complete_keyframe", f20_arg0.clipFinished )
			end
			
			f20_arg0.BombLabel:completeAnimation()
			f20_arg0.BombLabel:setLeftRight( 0, 0, 23.5, 54.5 )
			f20_arg0.BombLabel:setTopBottom( 0, 0, 12.5, 45.5 )
			f20_arg0.BombLabel:setAlpha( 0 )
			f20_arg0.BombLabel:setText( CoD.BaseUtility.AlreadyLocalized( "A" ) )
			f20_local1( f20_arg0.BombLabel )
		end,
		DefendBombB = function ( f23_arg0, f23_arg1 )
			f23_arg0:__resetProperties()
			f23_arg0:setupElementClipCounter( 7 )
			f23_arg0.ArrowRight:completeAnimation()
			f23_arg0.ArrowRight:setAlpha( 0 )
			f23_arg0.clipFinished( f23_arg0.ArrowRight )
			f23_arg0.ArrowLeft:completeAnimation()
			f23_arg0.ArrowLeft:setAlpha( 0 )
			f23_arg0.clipFinished( f23_arg0.ArrowLeft )
			f23_arg0.EnemyBombA:completeAnimation()
			f23_arg0.EnemyBombA:setAlpha( 0 )
			f23_arg0.clipFinished( f23_arg0.EnemyBombA )
			f23_arg0.EnemyBombB:completeAnimation()
			f23_arg0.EnemyBombB:setAlpha( 0 )
			f23_arg0.clipFinished( f23_arg0.EnemyBombB )
			f23_arg0.FriendlyBombA:completeAnimation()
			f23_arg0.FriendlyBombA:setAlpha( 0 )
			f23_arg0.clipFinished( f23_arg0.FriendlyBombA )
			local f23_local0 = function ( f24_arg0 )
				f23_arg0.FriendlyBombB:beginAnimation( 250 )
				f23_arg0.FriendlyBombB:setAlpha( 1 )
				f23_arg0.FriendlyBombB:registerEventHandler( "interrupted_keyframe", f23_arg0.clipInterrupted )
				f23_arg0.FriendlyBombB:registerEventHandler( "transition_complete_keyframe", f23_arg0.clipFinished )
			end
			
			f23_arg0.FriendlyBombB:completeAnimation()
			f23_arg0.FriendlyBombB:setAlpha( 0 )
			f23_local0( f23_arg0.FriendlyBombB )
			local f23_local1 = function ( f25_arg0 )
				f23_arg0.BombLabel:beginAnimation( 250 )
				f23_arg0.BombLabel:setAlpha( 1 )
				f23_arg0.BombLabel:registerEventHandler( "interrupted_keyframe", f23_arg0.clipInterrupted )
				f23_arg0.BombLabel:registerEventHandler( "transition_complete_keyframe", f23_arg0.clipFinished )
			end
			
			f23_arg0.BombLabel:completeAnimation()
			f23_arg0.BombLabel:setLeftRight( 0, 0, 87.5, 118.5 )
			f23_arg0.BombLabel:setTopBottom( 0, 0, 12.5, 45.5 )
			f23_arg0.BombLabel:setAlpha( 0 )
			f23_arg0.BombLabel:setText( CoD.BaseUtility.AlreadyLocalized( "B" ) )
			f23_local1( f23_arg0.BombLabel )
		end
	},
	DisarmBombA = {
		DefaultClip = function ( f26_arg0, f26_arg1 )
			f26_arg0:__resetProperties()
			f26_arg0:setupElementClipCounter( 7 )
			f26_arg0.ArrowRight:completeAnimation()
			f26_arg0.ArrowRight:setAlpha( 1 )
			f26_arg0.clipFinished( f26_arg0.ArrowRight )
			f26_arg0.ArrowLeft:completeAnimation()
			f26_arg0.ArrowLeft:setAlpha( 1 )
			f26_arg0.clipFinished( f26_arg0.ArrowLeft )
			f26_arg0.EnemyBombA:completeAnimation()
			f26_arg0.EnemyBombA:setAlpha( 1 )
			f26_arg0.clipFinished( f26_arg0.EnemyBombA )
			f26_arg0.EnemyBombB:completeAnimation()
			f26_arg0.EnemyBombB:setAlpha( 0 )
			f26_arg0.clipFinished( f26_arg0.EnemyBombB )
			f26_arg0.FriendlyBombA:completeAnimation()
			f26_arg0.FriendlyBombA:setAlpha( 0 )
			f26_arg0.clipFinished( f26_arg0.FriendlyBombA )
			f26_arg0.FriendlyBombB:completeAnimation()
			f26_arg0.FriendlyBombB:setAlpha( 0 )
			f26_arg0.clipFinished( f26_arg0.FriendlyBombB )
			f26_arg0.BombLabel:completeAnimation()
			f26_arg0.BombLabel:setLeftRight( 0, 0, 55.5, 86.5 )
			f26_arg0.BombLabel:setTopBottom( 0, 0, 12.5, 45.5 )
			f26_arg0.BombLabel:setAlpha( 1 )
			f26_arg0.BombLabel:setText( CoD.BaseUtility.AlreadyLocalized( "A" ) )
			f26_arg0.clipFinished( f26_arg0.BombLabel )
		end,
		DefaultState = function ( f27_arg0, f27_arg1 )
			f27_arg0:__resetProperties()
			f27_arg0:setupElementClipCounter( 7 )
			local f27_local0 = function ( f28_arg0 )
				local f28_local0 = function ( f29_arg0 )
					f29_arg0:beginAnimation( 1750 )
					f29_arg0:registerEventHandler( "transition_complete_keyframe", f27_arg0.clipFinished )
				end
				
				f27_arg0.ArrowRight:beginAnimation( 250 )
				f27_arg0.ArrowRight:setAlpha( 0 )
				f27_arg0.ArrowRight:registerEventHandler( "interrupted_keyframe", f27_arg0.clipInterrupted )
				f27_arg0.ArrowRight:registerEventHandler( "transition_complete_keyframe", f28_local0 )
			end
			
			f27_arg0.ArrowRight:completeAnimation()
			f27_arg0.ArrowRight:setAlpha( 1 )
			f27_local0( f27_arg0.ArrowRight )
			local f27_local1 = function ( f30_arg0 )
				local f30_local0 = function ( f31_arg0 )
					f31_arg0:beginAnimation( 1750 )
					f31_arg0:registerEventHandler( "transition_complete_keyframe", f27_arg0.clipFinished )
				end
				
				f27_arg0.ArrowLeft:beginAnimation( 250 )
				f27_arg0.ArrowLeft:setAlpha( 0 )
				f27_arg0.ArrowLeft:registerEventHandler( "interrupted_keyframe", f27_arg0.clipInterrupted )
				f27_arg0.ArrowLeft:registerEventHandler( "transition_complete_keyframe", f30_local0 )
			end
			
			f27_arg0.ArrowLeft:completeAnimation()
			f27_arg0.ArrowLeft:setAlpha( 1 )
			f27_local1( f27_arg0.ArrowLeft )
			f27_arg0.EnemyBombA:completeAnimation()
			f27_arg0.EnemyBombA:setAlpha( 1 )
			f27_arg0.clipFinished( f27_arg0.EnemyBombA )
			f27_arg0.EnemyBombB:completeAnimation()
			f27_arg0.EnemyBombB:setAlpha( 0 )
			f27_arg0.clipFinished( f27_arg0.EnemyBombB )
			f27_arg0.FriendlyBombA:completeAnimation()
			f27_arg0.FriendlyBombA:setAlpha( 0 )
			f27_arg0.clipFinished( f27_arg0.FriendlyBombA )
			f27_arg0.FriendlyBombB:completeAnimation()
			f27_arg0.FriendlyBombB:setAlpha( 0 )
			f27_arg0.clipFinished( f27_arg0.FriendlyBombB )
			f27_arg0.BombLabel:completeAnimation()
			f27_arg0.BombLabel:setLeftRight( 0, 0, 55.5, 86.5 )
			f27_arg0.BombLabel:setTopBottom( 0, 0, 12.5, 45.5 )
			f27_arg0.BombLabel:setAlpha( 1 )
			f27_arg0.BombLabel:setText( CoD.BaseUtility.AlreadyLocalized( "A" ) )
			f27_arg0.clipFinished( f27_arg0.BombLabel )
		end
	},
	DisarmBombB = {
		DefaultClip = function ( f32_arg0, f32_arg1 )
			f32_arg0:__resetProperties()
			f32_arg0:setupElementClipCounter( 7 )
			f32_arg0.ArrowRight:completeAnimation()
			f32_arg0.ArrowRight:setAlpha( 1 )
			f32_arg0.clipFinished( f32_arg0.ArrowRight )
			f32_arg0.ArrowLeft:completeAnimation()
			f32_arg0.ArrowLeft:setAlpha( 1 )
			f32_arg0.clipFinished( f32_arg0.ArrowLeft )
			f32_arg0.EnemyBombA:completeAnimation()
			f32_arg0.EnemyBombA:setAlpha( 0 )
			f32_arg0.clipFinished( f32_arg0.EnemyBombA )
			f32_arg0.EnemyBombB:completeAnimation()
			f32_arg0.EnemyBombB:setAlpha( 1 )
			f32_arg0.clipFinished( f32_arg0.EnemyBombB )
			f32_arg0.FriendlyBombA:completeAnimation()
			f32_arg0.FriendlyBombA:setAlpha( 0 )
			f32_arg0.clipFinished( f32_arg0.FriendlyBombA )
			f32_arg0.FriendlyBombB:completeAnimation()
			f32_arg0.FriendlyBombB:setAlpha( 0 )
			f32_arg0.clipFinished( f32_arg0.FriendlyBombB )
			f32_arg0.BombLabel:completeAnimation()
			f32_arg0.BombLabel:setLeftRight( 0, 0, 55.5, 86.5 )
			f32_arg0.BombLabel:setTopBottom( 0, 0, 12.5, 45.5 )
			f32_arg0.BombLabel:setAlpha( 1 )
			f32_arg0.BombLabel:setText( CoD.BaseUtility.AlreadyLocalized( "B" ) )
			f32_arg0.clipFinished( f32_arg0.BombLabel )
		end,
		DefaultState = function ( f33_arg0, f33_arg1 )
			f33_arg0:__resetProperties()
			f33_arg0:setupElementClipCounter( 7 )
			local f33_local0 = function ( f34_arg0 )
				local f34_local0 = function ( f35_arg0 )
					f35_arg0:beginAnimation( 1750 )
					f35_arg0:registerEventHandler( "transition_complete_keyframe", f33_arg0.clipFinished )
				end
				
				f33_arg0.ArrowRight:beginAnimation( 250 )
				f33_arg0.ArrowRight:setAlpha( 0 )
				f33_arg0.ArrowRight:registerEventHandler( "interrupted_keyframe", f33_arg0.clipInterrupted )
				f33_arg0.ArrowRight:registerEventHandler( "transition_complete_keyframe", f34_local0 )
			end
			
			f33_arg0.ArrowRight:completeAnimation()
			f33_arg0.ArrowRight:setAlpha( 1 )
			f33_local0( f33_arg0.ArrowRight )
			local f33_local1 = function ( f36_arg0 )
				local f36_local0 = function ( f37_arg0 )
					f37_arg0:beginAnimation( 1750 )
					f37_arg0:registerEventHandler( "transition_complete_keyframe", f33_arg0.clipFinished )
				end
				
				f33_arg0.ArrowLeft:beginAnimation( 250 )
				f33_arg0.ArrowLeft:setAlpha( 0 )
				f33_arg0.ArrowLeft:registerEventHandler( "interrupted_keyframe", f33_arg0.clipInterrupted )
				f33_arg0.ArrowLeft:registerEventHandler( "transition_complete_keyframe", f36_local0 )
			end
			
			f33_arg0.ArrowLeft:completeAnimation()
			f33_arg0.ArrowLeft:setAlpha( 1 )
			f33_local1( f33_arg0.ArrowLeft )
			f33_arg0.EnemyBombA:completeAnimation()
			f33_arg0.EnemyBombA:setAlpha( 0 )
			f33_arg0.clipFinished( f33_arg0.EnemyBombA )
			f33_arg0.EnemyBombB:completeAnimation()
			f33_arg0.EnemyBombB:setAlpha( 1 )
			f33_arg0.clipFinished( f33_arg0.EnemyBombB )
			f33_arg0.FriendlyBombA:completeAnimation()
			f33_arg0.FriendlyBombA:setAlpha( 0 )
			f33_arg0.clipFinished( f33_arg0.FriendlyBombA )
			f33_arg0.FriendlyBombB:completeAnimation()
			f33_arg0.FriendlyBombB:setAlpha( 0 )
			f33_arg0.clipFinished( f33_arg0.FriendlyBombB )
			f33_arg0.BombLabel:completeAnimation()
			f33_arg0.BombLabel:setLeftRight( 0, 0, 55.5, 86.5 )
			f33_arg0.BombLabel:setTopBottom( 0, 0, 12.5, 45.5 )
			f33_arg0.BombLabel:setAlpha( 1 )
			f33_arg0.BombLabel:setText( CoD.BaseUtility.AlreadyLocalized( "B" ) )
			f33_arg0.clipFinished( f33_arg0.BombLabel )
		end
	},
	DefendBombA = {
		DefaultClip = function ( f38_arg0, f38_arg1 )
			f38_arg0:__resetProperties()
			f38_arg0:setupElementClipCounter( 7 )
			f38_arg0.ArrowRight:completeAnimation()
			f38_arg0.ArrowRight:setAlpha( 0 )
			f38_arg0.clipFinished( f38_arg0.ArrowRight )
			f38_arg0.ArrowLeft:completeAnimation()
			f38_arg0.ArrowLeft:setAlpha( 0 )
			f38_arg0.clipFinished( f38_arg0.ArrowLeft )
			f38_arg0.EnemyBombA:completeAnimation()
			f38_arg0.EnemyBombA:setAlpha( 0 )
			f38_arg0.clipFinished( f38_arg0.EnemyBombA )
			f38_arg0.EnemyBombB:completeAnimation()
			f38_arg0.EnemyBombB:setAlpha( 0 )
			f38_arg0.clipFinished( f38_arg0.EnemyBombB )
			f38_arg0.FriendlyBombA:completeAnimation()
			f38_arg0.FriendlyBombA:setAlpha( 1 )
			f38_arg0.clipFinished( f38_arg0.FriendlyBombA )
			f38_arg0.FriendlyBombB:completeAnimation()
			f38_arg0.FriendlyBombB:setAlpha( 0 )
			f38_arg0.clipFinished( f38_arg0.FriendlyBombB )
			f38_arg0.BombLabel:completeAnimation()
			f38_arg0.BombLabel:setLeftRight( 0, 0, 23.5, 54.5 )
			f38_arg0.BombLabel:setTopBottom( 0, 0, 12.5, 45.5 )
			f38_arg0.BombLabel:setAlpha( 1 )
			f38_arg0.BombLabel:setText( CoD.BaseUtility.AlreadyLocalized( "A" ) )
			f38_arg0.clipFinished( f38_arg0.BombLabel )
		end,
		DefaultState = function ( f39_arg0, f39_arg1 )
			f39_arg0:__resetProperties()
			f39_arg0:setupElementClipCounter( 7 )
			local f39_local0 = function ( f40_arg0 )
				f39_arg0.ArrowRight:beginAnimation( 2000 )
				f39_arg0.ArrowRight:registerEventHandler( "interrupted_keyframe", f39_arg0.clipInterrupted )
				f39_arg0.ArrowRight:registerEventHandler( "transition_complete_keyframe", f39_arg0.clipFinished )
			end
			
			f39_arg0.ArrowRight:completeAnimation()
			f39_arg0.ArrowRight:setAlpha( 0 )
			f39_local0( f39_arg0.ArrowRight )
			local f39_local1 = function ( f41_arg0 )
				f39_arg0.ArrowLeft:beginAnimation( 2000 )
				f39_arg0.ArrowLeft:registerEventHandler( "interrupted_keyframe", f39_arg0.clipInterrupted )
				f39_arg0.ArrowLeft:registerEventHandler( "transition_complete_keyframe", f39_arg0.clipFinished )
			end
			
			f39_arg0.ArrowLeft:completeAnimation()
			f39_arg0.ArrowLeft:setAlpha( 0 )
			f39_local1( f39_arg0.ArrowLeft )
			f39_arg0.EnemyBombA:completeAnimation()
			f39_arg0.EnemyBombA:setAlpha( 0 )
			f39_arg0.clipFinished( f39_arg0.EnemyBombA )
			f39_arg0.EnemyBombB:completeAnimation()
			f39_arg0.EnemyBombB:setAlpha( 0 )
			f39_arg0.clipFinished( f39_arg0.EnemyBombB )
			f39_arg0.FriendlyBombA:completeAnimation()
			f39_arg0.FriendlyBombA:setAlpha( 1 )
			f39_arg0.clipFinished( f39_arg0.FriendlyBombA )
			f39_arg0.FriendlyBombB:completeAnimation()
			f39_arg0.FriendlyBombB:setAlpha( 0 )
			f39_arg0.clipFinished( f39_arg0.FriendlyBombB )
			f39_arg0.BombLabel:completeAnimation()
			f39_arg0.BombLabel:setLeftRight( 0, 0, 23.5, 54.5 )
			f39_arg0.BombLabel:setTopBottom( 0, 0, 12.5, 45.5 )
			f39_arg0.BombLabel:setAlpha( 1 )
			f39_arg0.BombLabel:setText( CoD.BaseUtility.AlreadyLocalized( "A" ) )
			f39_arg0.clipFinished( f39_arg0.BombLabel )
		end
	},
	DefendBombB = {
		DefaultClip = function ( f42_arg0, f42_arg1 )
			f42_arg0:__resetProperties()
			f42_arg0:setupElementClipCounter( 7 )
			f42_arg0.ArrowRight:completeAnimation()
			f42_arg0.ArrowRight:setAlpha( 0 )
			f42_arg0.clipFinished( f42_arg0.ArrowRight )
			f42_arg0.ArrowLeft:completeAnimation()
			f42_arg0.ArrowLeft:setAlpha( 0 )
			f42_arg0.clipFinished( f42_arg0.ArrowLeft )
			f42_arg0.EnemyBombA:completeAnimation()
			f42_arg0.EnemyBombA:setAlpha( 0 )
			f42_arg0.clipFinished( f42_arg0.EnemyBombA )
			f42_arg0.EnemyBombB:completeAnimation()
			f42_arg0.EnemyBombB:setAlpha( 0 )
			f42_arg0.clipFinished( f42_arg0.EnemyBombB )
			f42_arg0.FriendlyBombA:completeAnimation()
			f42_arg0.FriendlyBombA:setAlpha( 0 )
			f42_arg0.clipFinished( f42_arg0.FriendlyBombA )
			f42_arg0.FriendlyBombB:completeAnimation()
			f42_arg0.FriendlyBombB:setAlpha( 1 )
			f42_arg0.clipFinished( f42_arg0.FriendlyBombB )
			f42_arg0.BombLabel:completeAnimation()
			f42_arg0.BombLabel:setLeftRight( 0, 0, 87.5, 118.5 )
			f42_arg0.BombLabel:setTopBottom( 0, 0, 12.5, 45.5 )
			f42_arg0.BombLabel:setAlpha( 1 )
			f42_arg0.BombLabel:setText( CoD.BaseUtility.AlreadyLocalized( "B" ) )
			f42_arg0.clipFinished( f42_arg0.BombLabel )
		end,
		DefaultState = function ( f43_arg0, f43_arg1 )
			f43_arg0:__resetProperties()
			f43_arg0:setupElementClipCounter( 7 )
			local f43_local0 = function ( f44_arg0 )
				f43_arg0.ArrowRight:beginAnimation( 2000 )
				f43_arg0.ArrowRight:registerEventHandler( "interrupted_keyframe", f43_arg0.clipInterrupted )
				f43_arg0.ArrowRight:registerEventHandler( "transition_complete_keyframe", f43_arg0.clipFinished )
			end
			
			f43_arg0.ArrowRight:completeAnimation()
			f43_arg0.ArrowRight:setAlpha( 0 )
			f43_local0( f43_arg0.ArrowRight )
			local f43_local1 = function ( f45_arg0 )
				f43_arg0.ArrowLeft:beginAnimation( 2000 )
				f43_arg0.ArrowLeft:registerEventHandler( "interrupted_keyframe", f43_arg0.clipInterrupted )
				f43_arg0.ArrowLeft:registerEventHandler( "transition_complete_keyframe", f43_arg0.clipFinished )
			end
			
			f43_arg0.ArrowLeft:completeAnimation()
			f43_arg0.ArrowLeft:setAlpha( 0 )
			f43_local1( f43_arg0.ArrowLeft )
			f43_arg0.EnemyBombA:completeAnimation()
			f43_arg0.EnemyBombA:setAlpha( 0 )
			f43_arg0.clipFinished( f43_arg0.EnemyBombA )
			f43_arg0.EnemyBombB:completeAnimation()
			f43_arg0.EnemyBombB:setAlpha( 0 )
			f43_arg0.clipFinished( f43_arg0.EnemyBombB )
			f43_arg0.FriendlyBombA:completeAnimation()
			f43_arg0.FriendlyBombA:setAlpha( 0 )
			f43_arg0.clipFinished( f43_arg0.FriendlyBombA )
			f43_arg0.FriendlyBombB:completeAnimation()
			f43_arg0.FriendlyBombB:setAlpha( 1 )
			f43_arg0.clipFinished( f43_arg0.FriendlyBombB )
			f43_arg0.BombLabel:completeAnimation()
			f43_arg0.BombLabel:setLeftRight( 0, 0, 87.5, 118.5 )
			f43_arg0.BombLabel:setTopBottom( 0, 0, 12.5, 45.5 )
			f43_arg0.BombLabel:setAlpha( 1 )
			f43_arg0.BombLabel:setText( CoD.BaseUtility.AlreadyLocalized( "B" ) )
			f43_arg0.clipFinished( f43_arg0.BombLabel )
		end
	}
}
CoD.SDDemObjectiveNotification_BombPlanted.__onClose = function ( f46_arg0 )
	f46_arg0.ArrowRight:close()
	f46_arg0.ArrowLeft:close()
	f46_arg0.EnemyBombA:close()
	f46_arg0.EnemyBombB:close()
	f46_arg0.FriendlyBombA:close()
	f46_arg0.FriendlyBombB:close()
end

