require( "ui/uieditor/widgets/callingcards/callingcards_framewidget" )
require( "ui/uieditor/widgets/genericpopups/gp_framebackgroundt" )
require( "ui/uieditor/widgets/genericpopups/kickerinternal" )
require( "ui/uieditor/widgets/genericpopups/loot_bonustoaststandard" )
require( "ui/uieditor/widgets/genericpopups/loot_toastframebackground" )
require( "ui/uieditor/widgets/genericpopups/toast_bonusoutline" )
require( "ui/uieditor/widgets/genericpopups/toast_container_blackmarket" )
require( "ui/uieditor/widgets/genericpopups/toast_container_clansteams" )
require( "ui/uieditor/widgets/genericpopups/toastcontentlarge" )
require( "ui/uieditor/widgets/horizontalscrollingtextbox_30pt" )
require( "ui/uieditor/widgets/startmenu/options/startmenuoptionsmainframe" )
require( "x64:8728c223b78048d" )

CoD.Toast_Container = InheritFrom( LUI.UIElement )
CoD.Toast_Container.__defaultWidth = 340
CoD.Toast_Container.__defaultHeight = 80
CoD.Toast_Container.new = function ( f1_arg0, f1_arg1, f1_arg2, f1_arg3, f1_arg4, f1_arg5, f1_arg6, f1_arg7, f1_arg8, f1_arg9 )
	local self = LUI.UIElement.new( f1_arg2, f1_arg3, f1_arg4, f1_arg5, f1_arg6, f1_arg7, f1_arg8, f1_arg9 )
	self:setClass( CoD.Toast_Container )
	self.id = "Toast_Container"
	self.soundSet = "ChooseDecal"
	self.onlyChildrenFocusable = true
	self.anyChildUsesUpdateState = true
	f1_arg0:addElementToPendingUpdateStateList( self )
	
	local Backing = LUI.UIImage.new( 0, 1, 0, 0, 0, 1, 0, 0 )
	Backing:setRGB( 0, 0, 0 )
	self:addElement( Backing )
	self.Backing = Backing
	
	local LOOTToastFrameBackground = CoD.LOOT_ToastFrameBackground.new( f1_arg0, f1_arg1, 0, 0, -30, 490, 0, 0, -30, 139 )
	LOOTToastFrameBackground:setAlpha( 0 )
	self:addElement( LOOTToastFrameBackground )
	self.LOOTToastFrameBackground = LOOTToastFrameBackground
	
	local ToastBonusOutline = CoD.Toast_BonusOutline.new( f1_arg0, f1_arg1, 0, 0, -3, 453, 0, 0, -114, 110 )
	ToastBonusOutline:setAlpha( 0 )
	self:addElement( ToastBonusOutline )
	self.ToastBonusOutline = ToastBonusOutline
	
	local EmblemDecal = LUI.UIImage.new( 0, 0, 165, 285, 0, 0, -112, 8 )
	EmblemDecal:setAlpha( 0 )
	self:addElement( EmblemDecal )
	self.EmblemDecal = EmblemDecal
	
	local FrameBackground = CoD.GP_FrameBackgroundt.new( f1_arg0, f1_arg1, 0, 1, -45, 43, 0, 1, -1, 5 )
	FrameBackground:setAlpha( 0 )
	self:addElement( FrameBackground )
	self.FrameBackground = FrameBackground
	
	local ContentIcon = LUI.UIImage.new( 0, 0, 5, 95, 0, 0, 3.5, 93.5 )
	ContentIcon:setAlpha( 0 )
	self:addElement( ContentIcon )
	self.ContentIcon = ContentIcon
	
	local KickerOld = LUI.UIText.new( 0, 0, 111, 414, 0, 0, 9, 39 )
	KickerOld:setRGB( 0.27, 0.76, 0.09 )
	KickerOld:setAlpha( 0 )
	KickerOld:setText( Engine[0xF9F1239CFD921FE]( "menu/new" ) )
	KickerOld:setTTF( "dinnext_regular" )
	KickerOld:setAlignment( Enum.LUIAlignment[0x58C8A85F2048829] )
	KickerOld:setAlignment( Enum.LUIAlignment[0xF41D595A2B0EDF3] )
	self:addElement( KickerOld )
	self.KickerOld = KickerOld
	
	local ToastHeaderWidget = CoD.horizontalScrollingTextBox_30pt.new( f1_arg0, f1_arg1, 0, 0, 111, 453, 0, 0, 29, 80 )
	ToastHeaderWidget:setRGB( 0.27, 0.76, 0.09 )
	ToastHeaderWidget:setAlpha( 0 )
	ToastHeaderWidget.textBox:setText( Engine[0xF9F1239CFD921FE]( 0xA447D9FA67960A3 ) )
	self:addElement( ToastHeaderWidget )
	self.ToastHeaderWidget = ToastHeaderWidget
	
	local Description = LUI.UIText.new( 0, 0, 0, 450, 0, 0, 50, 84 )
	Description:setRGB( 0.75, 0.12, 0.12 )
	Description:setAlpha( 0 )
	Description:setText( Engine[0xF9F1239CFD921FE]( "menu/new" ) )
	Description:setTTF( "dinnext_regular" )
	Description:setAlignment( Enum.LUIAlignment[0xFEEB12BCB0D7041] )
	Description:setAlignment( Enum.LUIAlignment[0xF41D595A2B0EDF3] )
	self:addElement( Description )
	self.Description = Description
	
	local CallingCardsFrameWidget = CoD.CallingCards_FrameWidget.new( f1_arg0, f1_arg1, 0.5, 0.5, 0, 0, 0.5, 0.5, -97, -97 )
	CallingCardsFrameWidget:setAlpha( 0 )
	CallingCardsFrameWidget.CardIconFrame:setScale( 0.62, 1 )
	CallingCardsFrameWidget:linkToElementModel( self, nil, false, function ( model )
		CallingCardsFrameWidget:setModel( model, f1_arg1 )
	end )
	self:addElement( CallingCardsFrameWidget )
	self.CallingCardsFrameWidget = CallingCardsFrameWidget
	
	local Frame = CoD.StartMenuOptionsMainFrame.new( f1_arg0, f1_arg1, 0, 1, 0, 0, 0, 1, 0, 0 )
	Frame:setRGB( ColorSet.T8__BIEGE.r, ColorSet.T8__BIEGE.g, ColorSet.T8__BIEGE.b )
	Frame:setAlpha( 0.08 )
	self:addElement( Frame )
	self.Frame = Frame
	
	local CornerBL = LUI.UIImage.new( 0, 0, 2, 3, 1, 1, -3, -2 )
	self:addElement( CornerBL )
	self.CornerBL = CornerBL
	
	local CornerTL = LUI.UIImage.new( 0, 0, 2, 3, 0, 0, 2, 3 )
	self:addElement( CornerTL )
	self.CornerTL = CornerTL
	
	local CornerBR = LUI.UIImage.new( 1, 1, -3, -2, 1, 1, -3, -2 )
	self:addElement( CornerBR )
	self.CornerBR = CornerBR
	
	local CornerTR = LUI.UIImage.new( 1, 1, -3, -2, 0, 0, 2, 3 )
	self:addElement( CornerTR )
	self.CornerTR = CornerTR
	
	local FrameButtom = LUI.UIImage.new( 0, 1, 0, 0, 1, 1, -32, 8 )
	FrameButtom:setRGB( ColorSet.T8__BIEGE.r, ColorSet.T8__BIEGE.g, ColorSet.T8__BIEGE.b )
	FrameButtom:setImage( RegisterImage( 0x311FBEA5499D031 ) )
	self:addElement( FrameButtom )
	self.FrameButtom = FrameButtom
	
	local DecoFrameR = LUI.UIImage.new( 0.85, 1, -2, -2, 0, 1, 2, 2 )
	DecoFrameR:setRGB( ColorSet.T8__BIEGE.r, ColorSet.T8__BIEGE.g, ColorSet.T8__BIEGE.b )
	DecoFrameR:setAlpha( 0.06 )
	DecoFrameR:setYRot( 180 )
	DecoFrameR:setImage( RegisterImage( 0x11FE337F0BDC517 ) )
	self:addElement( DecoFrameR )
	self.DecoFrameR = DecoFrameR
	
	local DecoFrameL = LUI.UIImage.new( 0, 0.15, 2, 2, 0, 1, 2, 2 )
	DecoFrameL:setRGB( ColorSet.T8__BIEGE.r, ColorSet.T8__BIEGE.g, ColorSet.T8__BIEGE.b )
	DecoFrameL:setAlpha( 0.06 )
	DecoFrameL:setImage( RegisterImage( 0x11FE337F0BDC517 ) )
	self:addElement( DecoFrameL )
	self.DecoFrameL = DecoFrameL
	
	local FooterText = LUI.UIText.new( 0.5, 0.5, -170, 170, 0, 0, 50, 71 )
	FooterText:setRGB( ColorSet.T8__OFF__GRAY.r, ColorSet.T8__OFF__GRAY.g, ColorSet.T8__OFF__GRAY.b )
	FooterText:setText( Engine[0xF9F1239CFD921FE]( "menu/new" ) )
	FooterText:setTTF( "ttmussels_regular" )
	FooterText:setAlignment( Enum.LUIAlignment[0xFEEB12BCB0D7041] )
	FooterText:setAlignment( Enum.LUIAlignment[0xF41D595A2B0EDF3] )
	self:addElement( FooterText )
	self.FooterText = FooterText
	
	local FunctionIcon = LUI.UIImage.new( 1, 1, -35, -2, 0, 0, 20, 53 )
	FunctionIcon:setAlpha( 0 )
	self:addElement( FunctionIcon )
	self.FunctionIcon = FunctionIcon
	
	local ContentIconInternal = CoD.kickerinternal.new( f1_arg0, f1_arg1, 0.5, 0.5, -170, 170, 0, 0, 10, 50 )
	ContentIconInternal:setRGB( ColorSet.T8__BIEGE.r, ColorSet.T8__BIEGE.g, ColorSet.T8__BIEGE.b )
	self:addElement( ContentIconInternal )
	self.ContentIconInternal = ContentIconInternal
	
	local ToastContainerBlackMarket = CoD.Toast_Container_BlackMarket.new( f1_arg0, f1_arg1, 0, 0, 0, 340, 0, 0, 0, 80 )
	ToastContainerBlackMarket:setAlpha( 0 )
	ToastContainerBlackMarket:linkToElementModel( self, "description", true, function ( model )
		local f3_local0 = model:get()
		if f3_local0 ~= nil then
			ToastContainerBlackMarket.FooterText:setText( CoD.BaseUtility.LocalizeIfXHash( f3_local0 ) )
		end
	end )
	ToastContainerBlackMarket:linkToElementModel( self, "kicker", true, function ( model )
		local f4_local0 = model:get()
		if f4_local0 ~= nil then
			ToastContainerBlackMarket.ContentIconInternal.NotifTextMain:setText( CoD.BaseUtility.LocalizeIfXHash( f4_local0 ) )
		end
	end )
	self:addElement( ToastContainerBlackMarket )
	self.ToastContainerBlackMarket = ToastContainerBlackMarket
	
	local ToastContainerClansTeams = CoD.Toast_Container_ClansTeams.new( f1_arg0, f1_arg1, 0, 0, 0, 340, 0, 0, 0, 80 )
	ToastContainerClansTeams:setAlpha( 0 )
	ToastContainerClansTeams:linkToElementModel( self, "description", true, function ( model )
		local f5_local0 = model:get()
		if f5_local0 ~= nil then
			ToastContainerClansTeams.NotifText.NotifText:setText( CoD.BaseUtility.LocalizeIfXHash( f5_local0 ) )
		end
	end )
	ToastContainerClansTeams:linkToElementModel( self, "kicker", true, function ( model )
		local f6_local0 = model:get()
		if f6_local0 ~= nil then
			ToastContainerClansTeams.NotifText.NotifTextMain:setText( CoD.BaseUtility.LocalizeIfXHash( f6_local0 ) )
		end
	end )
	self:addElement( ToastContainerClansTeams )
	self.ToastContainerClansTeams = ToastContainerClansTeams
	
	local LootBonusToastStandard = CoD.Loot_BonusToastStandard.new( f1_arg0, f1_arg1, 0, 0, 0, 400, 0, 0, -70, 80 )
	LootBonusToastStandard:setAlpha( 0 )
	self:addElement( LootBonusToastStandard )
	self.LootBonusToastStandard = LootBonusToastStandard
	
	local ToastContainerFactionReward = CoD.Toast_Container_FactionReward.new( f1_arg0, f1_arg1, 0, 0, 0, 340, 0, 0, 0, 80 )
	ToastContainerFactionReward:setAlpha( 0 )
	self:addElement( ToastContainerFactionReward )
	self.ToastContainerFactionReward = ToastContainerFactionReward
	
	local ToastContentLarge = CoD.ToastContentLarge.new( f1_arg0, f1_arg1, 0, 0, 0, 400, 0, 0, -70, 80 )
	ToastContentLarge:setAlpha( 0 )
	self:addElement( ToastContentLarge )
	self.ToastContentLarge = ToastContentLarge
	
	CallingCardsFrameWidget.id = "CallingCardsFrameWidget"
	LUI.OverrideFunction_CallOriginalSecond( self, "close", self.__onClose )
	
	if PostLoadFunc then
		PostLoadFunc( self, f1_arg1, f1_arg0 )
	end
	
	return self
end

CoD.Toast_Container.__resetProperties = function ( f7_arg0 )
	f7_arg0.ContentIcon:completeAnimation()
	f7_arg0.FunctionIcon:completeAnimation()
	f7_arg0.KickerOld:completeAnimation()
	f7_arg0.ToastHeaderWidget:completeAnimation()
	f7_arg0.Description:completeAnimation()
	f7_arg0.ToastBonusOutline:completeAnimation()
	f7_arg0.EmblemDecal:completeAnimation()
	f7_arg0.FrameBackground:completeAnimation()
	f7_arg0.LOOTToastFrameBackground:completeAnimation()
	f7_arg0.ContentIconInternal:completeAnimation()
	f7_arg0.FooterText:completeAnimation()
	f7_arg0.DecoFrameL:completeAnimation()
	f7_arg0.DecoFrameR:completeAnimation()
	f7_arg0.FrameButtom:completeAnimation()
	f7_arg0.CornerTR:completeAnimation()
	f7_arg0.CornerBR:completeAnimation()
	f7_arg0.CornerTL:completeAnimation()
	f7_arg0.CornerBL:completeAnimation()
	f7_arg0.Frame:completeAnimation()
	f7_arg0.CallingCardsFrameWidget:completeAnimation()
	f7_arg0.Backing:completeAnimation()
	f7_arg0.LootBonusToastStandard:completeAnimation()
	f7_arg0.ToastContainerBlackMarket:completeAnimation()
	f7_arg0.ToastContainerClansTeams:completeAnimation()
	f7_arg0.ToastContainerFactionReward:completeAnimation()
	f7_arg0.ToastContentLarge:completeAnimation()
	f7_arg0.ContentIcon:setLeftRight( 0, 0, 5, 95 )
	f7_arg0.ContentIcon:setTopBottom( 0, 0, 3.5, 93.5 )
	f7_arg0.ContentIcon:setAlpha( 0 )
	f7_arg0.FunctionIcon:setLeftRight( 1, 1, -35, -2 )
	f7_arg0.FunctionIcon:setTopBottom( 0, 0, 20, 53 )
	f7_arg0.FunctionIcon:setAlpha( 0 )
	f7_arg0.KickerOld:setLeftRight( 0, 0, 111, 414 )
	f7_arg0.KickerOld:setTopBottom( 0, 0, 9, 39 )
	f7_arg0.KickerOld:setRGB( 0.27, 0.76, 0.09 )
	f7_arg0.KickerOld:setAlpha( 0 )
	f7_arg0.KickerOld:setScale( 1, 1 )
	f7_arg0.KickerOld:setAlignment( Enum.LUIAlignment[0x58C8A85F2048829] )
	f7_arg0.ToastHeaderWidget:setLeftRight( 0, 0, 111, 453 )
	f7_arg0.ToastHeaderWidget:setTopBottom( 0, 0, 29, 80 )
	f7_arg0.ToastHeaderWidget:setAlpha( 0 )
	f7_arg0.ToastHeaderWidget.textBox:setAlpha( 1 )
	f7_arg0.Description:setLeftRight( 0, 0, 0, 450 )
	f7_arg0.Description:setTopBottom( 0, 0, 50, 84 )
	f7_arg0.Description:setRGB( 0.75, 0.12, 0.12 )
	f7_arg0.Description:setAlpha( 0 )
	f7_arg0.Description:setScale( 1, 1 )
	f7_arg0.ToastBonusOutline:setLeftRight( 0, 0, -3, 453 )
	f7_arg0.ToastBonusOutline:setTopBottom( 0, 0, -114, 110 )
	f7_arg0.ToastBonusOutline:setAlpha( 0 )
	f7_arg0.EmblemDecal:setLeftRight( 0, 0, 165, 285 )
	f7_arg0.EmblemDecal:setTopBottom( 0, 0, -112, 8 )
	f7_arg0.EmblemDecal:setAlpha( 0 )
	f7_arg0.FrameBackground:setTopBottom( 0, 1, -1, 5 )
	f7_arg0.FrameBackground:setAlpha( 0 )
	f7_arg0.LOOTToastFrameBackground:setLeftRight( 0, 0, -30, 490 )
	f7_arg0.LOOTToastFrameBackground:setTopBottom( 0, 0, -30, 139 )
	f7_arg0.LOOTToastFrameBackground:setAlpha( 0 )
	f7_arg0.ContentIconInternal:setAlpha( 1 )
	f7_arg0.FooterText:setAlpha( 1 )
	f7_arg0.DecoFrameL:setAlpha( 0.06 )
	f7_arg0.DecoFrameR:setAlpha( 0.06 )
	f7_arg0.FrameButtom:setTopBottom( 1, 1, -32, 8 )
	f7_arg0.FrameButtom:setAlpha( 1 )
	f7_arg0.CornerTR:setAlpha( 1 )
	f7_arg0.CornerBR:setAlpha( 1 )
	f7_arg0.CornerTL:setAlpha( 1 )
	f7_arg0.CornerBL:setAlpha( 1 )
	f7_arg0.Frame:setAlpha( 0.08 )
	f7_arg0.CallingCardsFrameWidget:setAlpha( 0 )
	f7_arg0.Backing:setAlpha( 1 )
	f7_arg0.LootBonusToastStandard:setAlpha( 0 )
	f7_arg0.ToastContainerBlackMarket:setAlpha( 0 )
	f7_arg0.ToastContainerClansTeams:setAlpha( 0 )
	f7_arg0.ToastContainerFactionReward:setAlpha( 0 )
	f7_arg0.ToastContentLarge:setAlpha( 0 )
end

CoD.Toast_Container.__clipsPerState = {
	DefaultState = {
		DefaultClip = function ( f8_arg0, f8_arg1 )
			f8_arg0:__resetProperties()
			f8_arg0:setupElementClipCounter( 4 )
			f8_arg0.ContentIcon:completeAnimation()
			f8_arg0.ContentIcon:setLeftRight( 0, 0, 2, 98 )
			f8_arg0.ContentIcon:setTopBottom( 0, 0, 2, 98 )
			f8_arg0.clipFinished( f8_arg0.ContentIcon )
			f8_arg0.KickerOld:completeAnimation()
			f8_arg0.KickerOld:setLeftRight( 0, 0, 111, 414 )
			f8_arg0.KickerOld:setTopBottom( 0, 0, 13, 43 )
			f8_arg0.KickerOld:setRGB( 0.32, 0.53, 0.49 )
			f8_arg0.clipFinished( f8_arg0.KickerOld )
			f8_arg0.ToastHeaderWidget:completeAnimation()
			f8_arg0.ToastHeaderWidget:setLeftRight( 0, 0, 110.5, 461.5 )
			f8_arg0.ToastHeaderWidget:setTopBottom( 0, 0, 35, 86 )
			f8_arg0.clipFinished( f8_arg0.ToastHeaderWidget )
			f8_arg0.FunctionIcon:completeAnimation()
			f8_arg0.FunctionIcon:setLeftRight( 1, 1, -35, -2 )
			f8_arg0.FunctionIcon:setTopBottom( 0, 0, 1, 34 )
			f8_arg0.clipFinished( f8_arg0.FunctionIcon )
		end
	},
	Content = {
		DefaultClip = function ( f9_arg0, f9_arg1 )
			f9_arg0:__resetProperties()
			f9_arg0:setupElementClipCounter( 4 )
			f9_arg0.ContentIcon:completeAnimation()
			f9_arg0.ContentIcon:setLeftRight( 0, 0, 2, 98 )
			f9_arg0.ContentIcon:setTopBottom( 0, 0, 2, 98 )
			f9_arg0.clipFinished( f9_arg0.ContentIcon )
			f9_arg0.KickerOld:completeAnimation()
			f9_arg0.KickerOld:setRGB( 0.6, 0.91, 0.84 )
			f9_arg0.clipFinished( f9_arg0.KickerOld )
			f9_arg0.ToastHeaderWidget:completeAnimation()
			f9_arg0.ToastHeaderWidget:setLeftRight( 0, 0, 110.5, 461.5 )
			f9_arg0.ToastHeaderWidget:setTopBottom( 0, 0, 35, 86 )
			f9_arg0.clipFinished( f9_arg0.ToastHeaderWidget )
			f9_arg0.FunctionIcon:completeAnimation()
			f9_arg0.FunctionIcon:setLeftRight( 1, 1, -36, -3 )
			f9_arg0.FunctionIcon:setTopBottom( 0, 0, 0, 33 )
			f9_arg0.clipFinished( f9_arg0.FunctionIcon )
		end
	},
	LootBonusDecal = {
		DefaultClip = function ( f10_arg0, f10_arg1 )
			f10_arg0:__resetProperties()
			f10_arg0:setupElementClipCounter( 9 )
			f10_arg0.LOOTToastFrameBackground:completeAnimation()
			f10_arg0.LOOTToastFrameBackground:setLeftRight( 0, 0, -30, 490 )
			f10_arg0.LOOTToastFrameBackground:setTopBottom( 0, 0, -115.5, 138.5 )
			f10_arg0.LOOTToastFrameBackground:setAlpha( 1 )
			f10_arg0.clipFinished( f10_arg0.LOOTToastFrameBackground )
			f10_arg0.ToastBonusOutline:completeAnimation()
			f10_arg0.ToastBonusOutline:setLeftRight( 0, 0, 0, 450 )
			f10_arg0.ToastBonusOutline:setTopBottom( 0, 0, -115.5, 109.5 )
			f10_arg0.clipFinished( f10_arg0.ToastBonusOutline )
			f10_arg0.EmblemDecal:completeAnimation()
			f10_arg0.EmblemDecal:setLeftRight( 0, 0, 177, 287 )
			f10_arg0.EmblemDecal:setTopBottom( 0, 0, -85, 25 )
			f10_arg0.EmblemDecal:setAlpha( 1 )
			f10_arg0.clipFinished( f10_arg0.EmblemDecal )
			f10_arg0.FrameBackground:completeAnimation()
			f10_arg0.FrameBackground:setAlpha( 0 )
			f10_arg0.clipFinished( f10_arg0.FrameBackground )
			f10_arg0.ContentIcon:completeAnimation()
			f10_arg0.ContentIcon:setLeftRight( 0, 0, 6.5, 81.5 )
			f10_arg0.ContentIcon:setTopBottom( 0, 0, 6.5, 81.5 )
			f10_arg0.ContentIcon:setAlpha( 0 )
			f10_arg0.clipFinished( f10_arg0.ContentIcon )
			f10_arg0.KickerOld:completeAnimation()
			f10_arg0.KickerOld:setLeftRight( 0, 0, 4, 455 )
			f10_arg0.KickerOld:setTopBottom( 0, 0, 26.5, 65.5 )
			f10_arg0.KickerOld:setScale( 1.1, 1.1 )
			f10_arg0.KickerOld:setAlignment( Enum.LUIAlignment[0xFEEB12BCB0D7041] )
			f10_arg0.clipFinished( f10_arg0.KickerOld )
			f10_arg0.ToastHeaderWidget:completeAnimation()
			f10_arg0.ToastHeaderWidget:setAlpha( 0 )
			f10_arg0.clipFinished( f10_arg0.ToastHeaderWidget )
			f10_arg0.Description:completeAnimation()
			f10_arg0.Description:setLeftRight( 0, 0, 5, 455 )
			f10_arg0.Description:setTopBottom( 0, 0, 59, 93 )
			f10_arg0.Description:setRGB( 0.6, 0.91, 0.84 )
			f10_arg0.Description:setAlpha( 1 )
			f10_arg0.Description:setScale( 0.9, 0.9 )
			f10_arg0.clipFinished( f10_arg0.Description )
			f10_arg0.FunctionIcon:completeAnimation()
			f10_arg0.FunctionIcon:setAlpha( 0 )
			f10_arg0.clipFinished( f10_arg0.FunctionIcon )
		end
	},
	RecentGameBookmarked = {
		DefaultClip = function ( f11_arg0, f11_arg1 )
			f11_arg0:__resetProperties()
			f11_arg0:setupElementClipCounter( 0 )
		end
	},
	Fileshare = {
		DefaultClip = function ( f12_arg0, f12_arg1 )
			f12_arg0:__resetProperties()
			f12_arg0:setupElementClipCounter( 0 )
		end
	},
	Invite = {
		DefaultClip = function ( f13_arg0, f13_arg1 )
			f13_arg0:__resetProperties()
			f13_arg0:setupElementClipCounter( 0 )
		end
	},
	MultipleInvites = {
		DefaultClip = function ( f14_arg0, f14_arg1 )
			f14_arg0:__resetProperties()
			f14_arg0:setupElementClipCounter( 4 )
			f14_arg0.FrameBackground:completeAnimation()
			f14_arg0.FrameBackground:setTopBottom( 0, 0.44, -1, 5 )
			f14_arg0.clipFinished( f14_arg0.FrameBackground )
			f14_arg0.ContentIcon:completeAnimation()
			f14_arg0.ContentIcon:setLeftRight( 0, 0, 3, 42 )
			f14_arg0.ContentIcon:setTopBottom( 0, 0, 3, 42 )
			f14_arg0.clipFinished( f14_arg0.ContentIcon )
			f14_arg0.KickerOld:completeAnimation()
			f14_arg0.KickerOld:setLeftRight( 0, 0, 46, 349 )
			f14_arg0.clipFinished( f14_arg0.KickerOld )
			f14_arg0.ToastHeaderWidget:completeAnimation()
			f14_arg0.ToastHeaderWidget.textBox:completeAnimation()
			f14_arg0.ToastHeaderWidget.textBox:setAlpha( 0 )
			f14_arg0.clipFinished( f14_arg0.ToastHeaderWidget )
		end
	},
	BreakVariantLink = {
		DefaultClip = function ( f15_arg0, f15_arg1 )
			f15_arg0:__resetProperties()
			f15_arg0:setupElementClipCounter( 0 )
		end
	},
	BlackMarketEquipped = {
		DefaultClip = function ( f16_arg0, f16_arg1 )
			f16_arg0:__resetProperties()
			f16_arg0:setupElementClipCounter( 6 )
			f16_arg0.LOOTToastFrameBackground:completeAnimation()
			f16_arg0.LOOTToastFrameBackground:setAlpha( 1 )
			f16_arg0.clipFinished( f16_arg0.LOOTToastFrameBackground )
			f16_arg0.FrameBackground:completeAnimation()
			f16_arg0.FrameBackground:setAlpha( 0 )
			f16_arg0.clipFinished( f16_arg0.FrameBackground )
			f16_arg0.ContentIcon:completeAnimation()
			f16_arg0.ContentIcon:setLeftRight( 0, 0, 2, 98 )
			f16_arg0.ContentIcon:setTopBottom( 0, 0, 0, 96 )
			f16_arg0.clipFinished( f16_arg0.ContentIcon )
			f16_arg0.KickerOld:completeAnimation()
			f16_arg0.KickerOld:setLeftRight( 0, 0, 110.5, 424.5 )
			f16_arg0.KickerOld:setTopBottom( 0, 0, 18, 48 )
			f16_arg0.KickerOld:setRGB( 0.6, 0.91, 0.84 )
			f16_arg0.clipFinished( f16_arg0.KickerOld )
			f16_arg0.ToastHeaderWidget:completeAnimation()
			f16_arg0.ToastHeaderWidget:setLeftRight( 0, 0, 110.5, 449.5 )
			f16_arg0.ToastHeaderWidget:setTopBottom( 0, 0, 36, 87 )
			f16_arg0.clipFinished( f16_arg0.ToastHeaderWidget )
			f16_arg0.FunctionIcon:completeAnimation()
			f16_arg0.FunctionIcon:setLeftRight( 1, 1, -36, -3 )
			f16_arg0.FunctionIcon:setTopBottom( 0, 0, 0, 33 )
			f16_arg0.clipFinished( f16_arg0.FunctionIcon )
		end
	},
	CraftSave = {
		DefaultClip = function ( f17_arg0, f17_arg1 )
			f17_arg0:__resetProperties()
			f17_arg0:setupElementClipCounter( 4 )
			f17_arg0.ContentIcon:completeAnimation()
			f17_arg0.ContentIcon:setLeftRight( 0, 0, 2, 98 )
			f17_arg0.ContentIcon:setTopBottom( 0, 0, 2, 98 )
			f17_arg0.clipFinished( f17_arg0.ContentIcon )
			f17_arg0.KickerOld:completeAnimation()
			f17_arg0.KickerOld:setLeftRight( 0, 0, 111, 414 )
			f17_arg0.KickerOld:setTopBottom( 0, 0, 13, 43 )
			f17_arg0.KickerOld:setRGB( 0.32, 0.53, 0.49 )
			f17_arg0.clipFinished( f17_arg0.KickerOld )
			f17_arg0.ToastHeaderWidget:completeAnimation()
			f17_arg0.ToastHeaderWidget:setLeftRight( 0, 0, 110.5, 461.5 )
			f17_arg0.ToastHeaderWidget:setTopBottom( 0, 0, 35, 86 )
			f17_arg0.clipFinished( f17_arg0.ToastHeaderWidget )
			f17_arg0.FunctionIcon:completeAnimation()
			f17_arg0.FunctionIcon:setLeftRight( 1, 1, -35, -2 )
			f17_arg0.FunctionIcon:setTopBottom( 0, 0, 1, 34 )
			f17_arg0.clipFinished( f17_arg0.FunctionIcon )
		end
	},
	LootBonusStandard = {
		DefaultClip = function ( f18_arg0, f18_arg1 )
			f18_arg0:__resetProperties()
			f18_arg0:setupElementClipCounter( 22 )
			f18_arg0.Backing:completeAnimation()
			f18_arg0.Backing:setAlpha( 0 )
			f18_arg0.clipFinished( f18_arg0.Backing )
			f18_arg0.LOOTToastFrameBackground:completeAnimation()
			f18_arg0.LOOTToastFrameBackground:setAlpha( 0 )
			f18_arg0.clipFinished( f18_arg0.LOOTToastFrameBackground )
			f18_arg0.ToastBonusOutline:completeAnimation()
			f18_arg0.ToastBonusOutline:setAlpha( 0 )
			f18_arg0.clipFinished( f18_arg0.ToastBonusOutline )
			f18_arg0.EmblemDecal:completeAnimation()
			f18_arg0.EmblemDecal:setAlpha( 0 )
			f18_arg0.clipFinished( f18_arg0.EmblemDecal )
			f18_arg0.FrameBackground:completeAnimation()
			f18_arg0.FrameBackground:setAlpha( 0 )
			f18_arg0.clipFinished( f18_arg0.FrameBackground )
			f18_arg0.ContentIcon:completeAnimation()
			f18_arg0.ContentIcon:setAlpha( 0 )
			f18_arg0.clipFinished( f18_arg0.ContentIcon )
			f18_arg0.KickerOld:completeAnimation()
			f18_arg0.KickerOld:setAlpha( 0 )
			f18_arg0.clipFinished( f18_arg0.KickerOld )
			f18_arg0.ToastHeaderWidget:completeAnimation()
			f18_arg0.ToastHeaderWidget:setAlpha( 0 )
			f18_arg0.clipFinished( f18_arg0.ToastHeaderWidget )
			f18_arg0.Description:completeAnimation()
			f18_arg0.Description:setAlpha( 0 )
			f18_arg0.clipFinished( f18_arg0.Description )
			f18_arg0.CallingCardsFrameWidget:completeAnimation()
			f18_arg0.CallingCardsFrameWidget:setAlpha( 0 )
			f18_arg0.clipFinished( f18_arg0.CallingCardsFrameWidget )
			f18_arg0.Frame:completeAnimation()
			f18_arg0.Frame:setAlpha( 0 )
			f18_arg0.clipFinished( f18_arg0.Frame )
			f18_arg0.CornerBL:completeAnimation()
			f18_arg0.CornerBL:setAlpha( 0 )
			f18_arg0.clipFinished( f18_arg0.CornerBL )
			f18_arg0.CornerTL:completeAnimation()
			f18_arg0.CornerTL:setAlpha( 0 )
			f18_arg0.clipFinished( f18_arg0.CornerTL )
			f18_arg0.CornerBR:completeAnimation()
			f18_arg0.CornerBR:setAlpha( 0 )
			f18_arg0.clipFinished( f18_arg0.CornerBR )
			f18_arg0.CornerTR:completeAnimation()
			f18_arg0.CornerTR:setAlpha( 0 )
			f18_arg0.clipFinished( f18_arg0.CornerTR )
			f18_arg0.FrameButtom:completeAnimation()
			f18_arg0.FrameButtom:setAlpha( 0 )
			f18_arg0.clipFinished( f18_arg0.FrameButtom )
			f18_arg0.DecoFrameR:completeAnimation()
			f18_arg0.DecoFrameR:setAlpha( 0 )
			f18_arg0.clipFinished( f18_arg0.DecoFrameR )
			f18_arg0.DecoFrameL:completeAnimation()
			f18_arg0.DecoFrameL:setAlpha( 0 )
			f18_arg0.clipFinished( f18_arg0.DecoFrameL )
			f18_arg0.FooterText:completeAnimation()
			f18_arg0.FooterText:setAlpha( 0 )
			f18_arg0.clipFinished( f18_arg0.FooterText )
			f18_arg0.FunctionIcon:completeAnimation()
			f18_arg0.FunctionIcon:setAlpha( 0 )
			f18_arg0.clipFinished( f18_arg0.FunctionIcon )
			f18_arg0.ContentIconInternal:completeAnimation()
			f18_arg0.ContentIconInternal:setAlpha( 0 )
			f18_arg0.clipFinished( f18_arg0.ContentIconInternal )
			f18_arg0.LootBonusToastStandard:completeAnimation()
			f18_arg0.LootBonusToastStandard:setAlpha( 1 )
			f18_arg0.clipFinished( f18_arg0.LootBonusToastStandard )
		end
	},
	LootBonusCallingCard = {
		DefaultClip = function ( f19_arg0, f19_arg1 )
			f19_arg0:__resetProperties()
			f19_arg0:setupElementClipCounter( 22 )
			f19_arg0.Backing:completeAnimation()
			f19_arg0.Backing:setAlpha( 0 )
			f19_arg0.clipFinished( f19_arg0.Backing )
			f19_arg0.LOOTToastFrameBackground:completeAnimation()
			f19_arg0.LOOTToastFrameBackground:setAlpha( 0 )
			f19_arg0.clipFinished( f19_arg0.LOOTToastFrameBackground )
			f19_arg0.ToastBonusOutline:completeAnimation()
			f19_arg0.ToastBonusOutline:setAlpha( 0 )
			f19_arg0.clipFinished( f19_arg0.ToastBonusOutline )
			f19_arg0.EmblemDecal:completeAnimation()
			f19_arg0.EmblemDecal:setAlpha( 0 )
			f19_arg0.clipFinished( f19_arg0.EmblemDecal )
			f19_arg0.FrameBackground:completeAnimation()
			f19_arg0.FrameBackground:setAlpha( 0 )
			f19_arg0.clipFinished( f19_arg0.FrameBackground )
			f19_arg0.ContentIcon:completeAnimation()
			f19_arg0.ContentIcon:setAlpha( 0 )
			f19_arg0.clipFinished( f19_arg0.ContentIcon )
			f19_arg0.KickerOld:completeAnimation()
			f19_arg0.KickerOld:setAlpha( 0 )
			f19_arg0.clipFinished( f19_arg0.KickerOld )
			f19_arg0.ToastHeaderWidget:completeAnimation()
			f19_arg0.ToastHeaderWidget:setAlpha( 0 )
			f19_arg0.clipFinished( f19_arg0.ToastHeaderWidget )
			f19_arg0.Description:completeAnimation()
			f19_arg0.Description:setAlpha( 0 )
			f19_arg0.clipFinished( f19_arg0.Description )
			f19_arg0.CallingCardsFrameWidget:completeAnimation()
			f19_arg0.CallingCardsFrameWidget:setAlpha( 0 )
			f19_arg0.clipFinished( f19_arg0.CallingCardsFrameWidget )
			f19_arg0.Frame:completeAnimation()
			f19_arg0.Frame:setAlpha( 0 )
			f19_arg0.clipFinished( f19_arg0.Frame )
			f19_arg0.CornerBL:completeAnimation()
			f19_arg0.CornerBL:setAlpha( 0 )
			f19_arg0.clipFinished( f19_arg0.CornerBL )
			f19_arg0.CornerTL:completeAnimation()
			f19_arg0.CornerTL:setAlpha( 0 )
			f19_arg0.clipFinished( f19_arg0.CornerTL )
			f19_arg0.CornerBR:completeAnimation()
			f19_arg0.CornerBR:setAlpha( 0 )
			f19_arg0.clipFinished( f19_arg0.CornerBR )
			f19_arg0.CornerTR:completeAnimation()
			f19_arg0.CornerTR:setAlpha( 0 )
			f19_arg0.clipFinished( f19_arg0.CornerTR )
			f19_arg0.FrameButtom:completeAnimation()
			f19_arg0.FrameButtom:setAlpha( 0 )
			f19_arg0.clipFinished( f19_arg0.FrameButtom )
			f19_arg0.DecoFrameR:completeAnimation()
			f19_arg0.DecoFrameR:setAlpha( 0 )
			f19_arg0.clipFinished( f19_arg0.DecoFrameR )
			f19_arg0.DecoFrameL:completeAnimation()
			f19_arg0.DecoFrameL:setAlpha( 0 )
			f19_arg0.clipFinished( f19_arg0.DecoFrameL )
			f19_arg0.FooterText:completeAnimation()
			f19_arg0.FooterText:setAlpha( 0 )
			f19_arg0.clipFinished( f19_arg0.FooterText )
			f19_arg0.FunctionIcon:completeAnimation()
			f19_arg0.FunctionIcon:setAlpha( 0 )
			f19_arg0.clipFinished( f19_arg0.FunctionIcon )
			f19_arg0.ContentIconInternal:completeAnimation()
			f19_arg0.ContentIconInternal:setAlpha( 0 )
			f19_arg0.clipFinished( f19_arg0.ContentIconInternal )
			f19_arg0.LootBonusToastStandard:completeAnimation()
			f19_arg0.LootBonusToastStandard:setAlpha( 1 )
			f19_arg0.clipFinished( f19_arg0.LootBonusToastStandard )
		end
	},
	BlackMarketLoot = {
		DefaultClip = function ( f20_arg0, f20_arg1 )
			f20_arg0:__resetProperties()
			f20_arg0:setupElementClipCounter( 12 )
			f20_arg0.Backing:completeAnimation()
			f20_arg0.Backing:setAlpha( 0 )
			f20_arg0.clipFinished( f20_arg0.Backing )
			f20_arg0.Frame:completeAnimation()
			f20_arg0.Frame:setAlpha( 0 )
			f20_arg0.clipFinished( f20_arg0.Frame )
			f20_arg0.CornerBL:completeAnimation()
			f20_arg0.CornerBL:setAlpha( 0 )
			f20_arg0.clipFinished( f20_arg0.CornerBL )
			f20_arg0.CornerTL:completeAnimation()
			f20_arg0.CornerTL:setAlpha( 0 )
			f20_arg0.clipFinished( f20_arg0.CornerTL )
			f20_arg0.CornerBR:completeAnimation()
			f20_arg0.CornerBR:setAlpha( 0 )
			f20_arg0.clipFinished( f20_arg0.CornerBR )
			f20_arg0.CornerTR:completeAnimation()
			f20_arg0.CornerTR:setAlpha( 0 )
			f20_arg0.clipFinished( f20_arg0.CornerTR )
			f20_arg0.FrameButtom:completeAnimation()
			f20_arg0.FrameButtom:setTopBottom( 1, 1, 8, 8 )
			f20_arg0.clipFinished( f20_arg0.FrameButtom )
			f20_arg0.DecoFrameR:completeAnimation()
			f20_arg0.DecoFrameR:setAlpha( 0 )
			f20_arg0.clipFinished( f20_arg0.DecoFrameR )
			f20_arg0.DecoFrameL:completeAnimation()
			f20_arg0.DecoFrameL:setAlpha( 0 )
			f20_arg0.clipFinished( f20_arg0.DecoFrameL )
			f20_arg0.FooterText:completeAnimation()
			f20_arg0.FooterText:setAlpha( 0 )
			f20_arg0.clipFinished( f20_arg0.FooterText )
			f20_arg0.ContentIconInternal:completeAnimation()
			f20_arg0.ContentIconInternal:setAlpha( 0 )
			f20_arg0.clipFinished( f20_arg0.ContentIconInternal )
			f20_arg0.ToastContainerBlackMarket:completeAnimation()
			f20_arg0.ToastContainerBlackMarket:setAlpha( 1 )
			f20_arg0.clipFinished( f20_arg0.ToastContainerBlackMarket )
		end
	},
	TrialClientsKicked = {
		DefaultClip = function ( f21_arg0, f21_arg1 )
			f21_arg0:__resetProperties()
			f21_arg0:setupElementClipCounter( 0 )
		end
	},
	ClansTeams = {
		DefaultClip = function ( f22_arg0, f22_arg1 )
			f22_arg0:__resetProperties()
			f22_arg0:setupElementClipCounter( 13 )
			f22_arg0.Backing:completeAnimation()
			f22_arg0.Backing:setAlpha( 0 )
			f22_arg0.clipFinished( f22_arg0.Backing )
			f22_arg0.Frame:completeAnimation()
			f22_arg0.Frame:setAlpha( 0 )
			f22_arg0.clipFinished( f22_arg0.Frame )
			f22_arg0.CornerBL:completeAnimation()
			f22_arg0.CornerBL:setAlpha( 0 )
			f22_arg0.clipFinished( f22_arg0.CornerBL )
			f22_arg0.CornerTL:completeAnimation()
			f22_arg0.CornerTL:setAlpha( 0 )
			f22_arg0.clipFinished( f22_arg0.CornerTL )
			f22_arg0.CornerBR:completeAnimation()
			f22_arg0.CornerBR:setAlpha( 0 )
			f22_arg0.clipFinished( f22_arg0.CornerBR )
			f22_arg0.CornerTR:completeAnimation()
			f22_arg0.CornerTR:setAlpha( 0 )
			f22_arg0.clipFinished( f22_arg0.CornerTR )
			f22_arg0.FrameButtom:completeAnimation()
			f22_arg0.FrameButtom:setTopBottom( 1, 1, 8, 8 )
			f22_arg0.clipFinished( f22_arg0.FrameButtom )
			f22_arg0.DecoFrameR:completeAnimation()
			f22_arg0.DecoFrameR:setAlpha( 0 )
			f22_arg0.clipFinished( f22_arg0.DecoFrameR )
			f22_arg0.DecoFrameL:completeAnimation()
			f22_arg0.DecoFrameL:setAlpha( 0 )
			f22_arg0.clipFinished( f22_arg0.DecoFrameL )
			f22_arg0.FooterText:completeAnimation()
			f22_arg0.FooterText:setAlpha( 0 )
			f22_arg0.clipFinished( f22_arg0.FooterText )
			f22_arg0.ContentIconInternal:completeAnimation()
			f22_arg0.ContentIconInternal:setAlpha( 0 )
			f22_arg0.clipFinished( f22_arg0.ContentIconInternal )
			f22_arg0.ToastContainerBlackMarket:completeAnimation()
			f22_arg0.ToastContainerBlackMarket:setAlpha( 0 )
			f22_arg0.clipFinished( f22_arg0.ToastContainerBlackMarket )
			f22_arg0.ToastContainerClansTeams:completeAnimation()
			f22_arg0.ToastContainerClansTeams:setAlpha( 1 )
			f22_arg0.clipFinished( f22_arg0.ToastContainerClansTeams )
		end
	},
	FactionReward = {
		DefaultClip = function ( f23_arg0, f23_arg1 )
			f23_arg0:__resetProperties()
			f23_arg0:setupElementClipCounter( 25 )
			f23_arg0.Backing:completeAnimation()
			f23_arg0.Backing:setAlpha( 0 )
			f23_arg0.clipFinished( f23_arg0.Backing )
			f23_arg0.LOOTToastFrameBackground:completeAnimation()
			f23_arg0.LOOTToastFrameBackground:setAlpha( 0 )
			f23_arg0.clipFinished( f23_arg0.LOOTToastFrameBackground )
			f23_arg0.ToastBonusOutline:completeAnimation()
			f23_arg0.ToastBonusOutline:setAlpha( 0 )
			f23_arg0.clipFinished( f23_arg0.ToastBonusOutline )
			f23_arg0.EmblemDecal:completeAnimation()
			f23_arg0.EmblemDecal:setAlpha( 0 )
			f23_arg0.clipFinished( f23_arg0.EmblemDecal )
			f23_arg0.FrameBackground:completeAnimation()
			f23_arg0.FrameBackground:setAlpha( 0 )
			f23_arg0.clipFinished( f23_arg0.FrameBackground )
			f23_arg0.ContentIcon:completeAnimation()
			f23_arg0.ContentIcon:setAlpha( 0 )
			f23_arg0.clipFinished( f23_arg0.ContentIcon )
			f23_arg0.KickerOld:completeAnimation()
			f23_arg0.KickerOld:setAlpha( 0 )
			f23_arg0.clipFinished( f23_arg0.KickerOld )
			f23_arg0.ToastHeaderWidget:completeAnimation()
			f23_arg0.ToastHeaderWidget:setAlpha( 0 )
			f23_arg0.clipFinished( f23_arg0.ToastHeaderWidget )
			f23_arg0.Description:completeAnimation()
			f23_arg0.Description:setAlpha( 0 )
			f23_arg0.clipFinished( f23_arg0.Description )
			f23_arg0.CallingCardsFrameWidget:completeAnimation()
			f23_arg0.CallingCardsFrameWidget:setAlpha( 0 )
			f23_arg0.clipFinished( f23_arg0.CallingCardsFrameWidget )
			f23_arg0.Frame:completeAnimation()
			f23_arg0.Frame:setAlpha( 0 )
			f23_arg0.clipFinished( f23_arg0.Frame )
			f23_arg0.CornerBL:completeAnimation()
			f23_arg0.CornerBL:setAlpha( 0 )
			f23_arg0.clipFinished( f23_arg0.CornerBL )
			f23_arg0.CornerTL:completeAnimation()
			f23_arg0.CornerTL:setAlpha( 0 )
			f23_arg0.clipFinished( f23_arg0.CornerTL )
			f23_arg0.CornerBR:completeAnimation()
			f23_arg0.CornerBR:setAlpha( 0 )
			f23_arg0.clipFinished( f23_arg0.CornerBR )
			f23_arg0.CornerTR:completeAnimation()
			f23_arg0.CornerTR:setAlpha( 0 )
			f23_arg0.clipFinished( f23_arg0.CornerTR )
			f23_arg0.FrameButtom:completeAnimation()
			f23_arg0.FrameButtom:setAlpha( 0 )
			f23_arg0.clipFinished( f23_arg0.FrameButtom )
			f23_arg0.DecoFrameR:completeAnimation()
			f23_arg0.DecoFrameR:setAlpha( 0 )
			f23_arg0.clipFinished( f23_arg0.DecoFrameR )
			f23_arg0.DecoFrameL:completeAnimation()
			f23_arg0.DecoFrameL:setAlpha( 0 )
			f23_arg0.clipFinished( f23_arg0.DecoFrameL )
			f23_arg0.FooterText:completeAnimation()
			f23_arg0.FooterText:setAlpha( 0 )
			f23_arg0.clipFinished( f23_arg0.FooterText )
			f23_arg0.FunctionIcon:completeAnimation()
			f23_arg0.FunctionIcon:setAlpha( 0 )
			f23_arg0.clipFinished( f23_arg0.FunctionIcon )
			f23_arg0.ContentIconInternal:completeAnimation()
			f23_arg0.ContentIconInternal:setAlpha( 0 )
			f23_arg0.clipFinished( f23_arg0.ContentIconInternal )
			f23_arg0.ToastContainerBlackMarket:completeAnimation()
			f23_arg0.ToastContainerBlackMarket:setAlpha( 0 )
			f23_arg0.clipFinished( f23_arg0.ToastContainerBlackMarket )
			f23_arg0.ToastContainerClansTeams:completeAnimation()
			f23_arg0.ToastContainerClansTeams:setAlpha( 0 )
			f23_arg0.clipFinished( f23_arg0.ToastContainerClansTeams )
			f23_arg0.LootBonusToastStandard:completeAnimation()
			f23_arg0.LootBonusToastStandard:setAlpha( 0 )
			f23_arg0.clipFinished( f23_arg0.LootBonusToastStandard )
			f23_arg0.ToastContainerFactionReward:completeAnimation()
			f23_arg0.ToastContainerFactionReward:setAlpha( 1 )
			f23_arg0.clipFinished( f23_arg0.ToastContainerFactionReward )
		end
	},
	ContentLarge = {
		DefaultClip = function ( f24_arg0, f24_arg1 )
			f24_arg0:__resetProperties()
			f24_arg0:setupElementClipCounter( 23 )
			f24_arg0.Backing:completeAnimation()
			f24_arg0.Backing:setAlpha( 0 )
			f24_arg0.clipFinished( f24_arg0.Backing )
			f24_arg0.LOOTToastFrameBackground:completeAnimation()
			f24_arg0.LOOTToastFrameBackground:setAlpha( 0 )
			f24_arg0.clipFinished( f24_arg0.LOOTToastFrameBackground )
			f24_arg0.ToastBonusOutline:completeAnimation()
			f24_arg0.ToastBonusOutline:setAlpha( 0 )
			f24_arg0.clipFinished( f24_arg0.ToastBonusOutline )
			f24_arg0.EmblemDecal:completeAnimation()
			f24_arg0.EmblemDecal:setAlpha( 0 )
			f24_arg0.clipFinished( f24_arg0.EmblemDecal )
			f24_arg0.FrameBackground:completeAnimation()
			f24_arg0.FrameBackground:setAlpha( 0 )
			f24_arg0.clipFinished( f24_arg0.FrameBackground )
			f24_arg0.ContentIcon:completeAnimation()
			f24_arg0.ContentIcon:setAlpha( 0 )
			f24_arg0.clipFinished( f24_arg0.ContentIcon )
			f24_arg0.KickerOld:completeAnimation()
			f24_arg0.KickerOld:setAlpha( 0 )
			f24_arg0.clipFinished( f24_arg0.KickerOld )
			f24_arg0.ToastHeaderWidget:completeAnimation()
			f24_arg0.ToastHeaderWidget:setAlpha( 0 )
			f24_arg0.clipFinished( f24_arg0.ToastHeaderWidget )
			f24_arg0.Description:completeAnimation()
			f24_arg0.Description:setAlpha( 0 )
			f24_arg0.clipFinished( f24_arg0.Description )
			f24_arg0.CallingCardsFrameWidget:completeAnimation()
			f24_arg0.CallingCardsFrameWidget:setAlpha( 0 )
			f24_arg0.clipFinished( f24_arg0.CallingCardsFrameWidget )
			f24_arg0.Frame:completeAnimation()
			f24_arg0.Frame:setAlpha( 0 )
			f24_arg0.clipFinished( f24_arg0.Frame )
			f24_arg0.CornerBL:completeAnimation()
			f24_arg0.CornerBL:setAlpha( 0 )
			f24_arg0.clipFinished( f24_arg0.CornerBL )
			f24_arg0.CornerTL:completeAnimation()
			f24_arg0.CornerTL:setAlpha( 0 )
			f24_arg0.clipFinished( f24_arg0.CornerTL )
			f24_arg0.CornerBR:completeAnimation()
			f24_arg0.CornerBR:setAlpha( 0 )
			f24_arg0.clipFinished( f24_arg0.CornerBR )
			f24_arg0.CornerTR:completeAnimation()
			f24_arg0.CornerTR:setAlpha( 0 )
			f24_arg0.clipFinished( f24_arg0.CornerTR )
			f24_arg0.FrameButtom:completeAnimation()
			f24_arg0.FrameButtom:setAlpha( 0 )
			f24_arg0.clipFinished( f24_arg0.FrameButtom )
			f24_arg0.DecoFrameR:completeAnimation()
			f24_arg0.DecoFrameR:setAlpha( 0 )
			f24_arg0.clipFinished( f24_arg0.DecoFrameR )
			f24_arg0.DecoFrameL:completeAnimation()
			f24_arg0.DecoFrameL:setAlpha( 0 )
			f24_arg0.clipFinished( f24_arg0.DecoFrameL )
			f24_arg0.FooterText:completeAnimation()
			f24_arg0.FooterText:setAlpha( 0 )
			f24_arg0.clipFinished( f24_arg0.FooterText )
			f24_arg0.FunctionIcon:completeAnimation()
			f24_arg0.FunctionIcon:setAlpha( 0 )
			f24_arg0.clipFinished( f24_arg0.FunctionIcon )
			f24_arg0.ContentIconInternal:completeAnimation()
			f24_arg0.ContentIconInternal:setAlpha( 0 )
			f24_arg0.clipFinished( f24_arg0.ContentIconInternal )
			f24_arg0.LootBonusToastStandard:completeAnimation()
			f24_arg0.LootBonusToastStandard:setAlpha( 0 )
			f24_arg0.clipFinished( f24_arg0.LootBonusToastStandard )
			f24_arg0.ToastContentLarge:completeAnimation()
			f24_arg0.ToastContentLarge:setAlpha( 1 )
			f24_arg0.clipFinished( f24_arg0.ToastContentLarge )
		end
	}
}
CoD.Toast_Container.__onClose = function ( f25_arg0 )
	f25_arg0.LOOTToastFrameBackground:close()
	f25_arg0.ToastBonusOutline:close()
	f25_arg0.FrameBackground:close()
	f25_arg0.ToastHeaderWidget:close()
	f25_arg0.CallingCardsFrameWidget:close()
	f25_arg0.Frame:close()
	f25_arg0.ContentIconInternal:close()
	f25_arg0.ToastContainerBlackMarket:close()
	f25_arg0.ToastContainerClansTeams:close()
	f25_arg0.LootBonusToastStandard:close()
	f25_arg0.ToastContainerFactionReward:close()
	f25_arg0.ToastContentLarge:close()
end

