require( "ui/uieditor/widgets/lobby/common/fe_buttonfocus" )
require( "ui/uieditor/widgets/lobby/common/fe_buttonidle" )
require( "ui/uieditor/widgets/lobby/common/fe_buttonpanelshadercontainer" )
require( "ui/uieditor/widgets/lobby/common/fe_helpitemslabel" )

CoD.FileshareOptionButton = InheritFrom( LUI.UIElement )
CoD.FileshareOptionButton.__defaultWidth = 420
CoD.FileshareOptionButton.__defaultHeight = 48
CoD.FileshareOptionButton.new = function ( f1_arg0, f1_arg1, f1_arg2, f1_arg3, f1_arg4, f1_arg5, f1_arg6, f1_arg7, f1_arg8, f1_arg9 )
	local self = LUI.UIElement.new( f1_arg2, f1_arg3, f1_arg4, f1_arg5, f1_arg6, f1_arg7, f1_arg8, f1_arg9 )
	self:setClass( CoD.FileshareOptionButton )
	self.id = "FileshareOptionButton"
	self.soundSet = "default"
	self.anyChildUsesUpdateState = true
	f1_arg0:addElementToPendingUpdateStateList( self )
	
	local FEButtonPanelShaderContainer = CoD.FE_ButtonPanelShaderContainer.new( f1_arg0, f1_arg1, 0, 1, -16, 12, 0.5, 0.5, -24, 24 )
	FEButtonPanelShaderContainer:setRGB( 0.5, 0.5, 0.5 )
	FEButtonPanelShaderContainer:setAlpha( 0 )
	self:addElement( FEButtonPanelShaderContainer )
	self.FEButtonPanelShaderContainer = FEButtonPanelShaderContainer
	
	local FEButtonIdle = CoD.FE_ButtonIdle.new( f1_arg0, f1_arg1, 0, 1, 0, 0, 0.5, 0.5, -21, 21 )
	FEButtonIdle:setAlpha( 0.8 )
	FEButtonIdle:setZoom( 10 )
	self:addElement( FEButtonIdle )
	self.FEButtonIdle = FEButtonIdle
	
	local FEButtonFocus = CoD.FE_ButtonFocus.new( f1_arg0, f1_arg1, 0, 1, 0, 0, 0.5, 0.5, -21, 21 )
	FEButtonFocus:setAlpha( 0 )
	FEButtonFocus:setZoom( 10 )
	FEButtonFocus.Image:setShaderVector( 0, 0.04, 0.3, 0.38, 0.2 )
	self:addElement( FEButtonFocus )
	self.FEButtonFocus = FEButtonFocus
	
	local Glow = LUI.UIImage.new( 0, 0, 69, 160, 0, 0, -173, 221 )
	Glow:setRGB( 0.88, 1, 0.04 )
	Glow:setAlpha( 0 )
	Glow:setZRot( 90 )
	Glow:setImage( RegisterImage( "uie_t7_cp_hud_enemytarget_glow" ) )
	Glow:setMaterial( LUI.UIImage.GetCachedMaterial( "ui_add" ) )
	self:addElement( Glow )
	self.Glow = Glow
	
	local btnDisplayText = LUI.UIText.new( 0, 0, 54, 426, 0, 0, 10, 40 )
	btnDisplayText:setRGB( 0.79, 0.79, 0.79 )
	btnDisplayText:setAlpha( 0 )
	btnDisplayText:setZoom( 10 )
	btnDisplayText:setTTF( "dinnext_regular" )
	btnDisplayText:setLetterSpacing( 1 )
	btnDisplayText:setAlignment( Enum.LUIAlignment[0x58C8A85F2048829] )
	btnDisplayText:setAlignment( Enum.LUIAlignment[0xF41D595A2B0EDF3] )
	LUI.OverrideFunction_CallOriginalFirst( btnDisplayText, "setText", function ( element, controller )
		ScaleWidgetToLabel( self, element, 5 )
	end )
	self:addElement( btnDisplayText )
	self.btnDisplayText = btnDisplayText
	
	local btnDisplayTextStroke = LUI.UIText.new( 0, 0, 54, 426, 0, 0, 10, 40 )
	btnDisplayTextStroke:setRGB( 0, 0, 0 )
	btnDisplayTextStroke:setAlpha( 0.7 )
	btnDisplayTextStroke:setZoom( 10 )
	btnDisplayTextStroke:setTTF( "dinnext_regular" )
	btnDisplayTextStroke:setMaterial( LUI.UIImage.GetCachedMaterial( 0xAE166D9BA8C6907 ) )
	btnDisplayTextStroke:setShaderVector( 0, 0.08, 0, 0, 0 )
	btnDisplayTextStroke:setShaderVector( 1, 0, 0, 0, 0 )
	btnDisplayTextStroke:setShaderVector( 2, 1, 0, 0, 0 )
	btnDisplayTextStroke:setLetterSpacing( 1 )
	btnDisplayTextStroke:setAlignment( Enum.LUIAlignment[0x58C8A85F2048829] )
	btnDisplayTextStroke:setAlignment( Enum.LUIAlignment[0xF41D595A2B0EDF3] )
	LUI.OverrideFunction_CallOriginalFirst( btnDisplayTextStroke, "setText", function ( element, controller )
		if not IsCurrentLanguageArabic() then
			TrimLabelIfLanguageReversed( self, element )
		end
	end )
	self:addElement( btnDisplayTextStroke )
	self.btnDisplayTextStroke = btnDisplayTextStroke
	
	local FEHelpItemsLabel0 = CoD.FE_HelpItemsLabel.new( f1_arg0, f1_arg1, 1, 1, 0, 30, 0.5, 0.5, -15, 15 )
	self:addElement( FEHelpItemsLabel0 )
	self.FEHelpItemsLabel0 = FEHelpItemsLabel0
	
	local Arrow = LUI.UIImage.new( 0, 0, -30, -18, 0, 0, 18, 30 )
	Arrow:setAlpha( 0 )
	Arrow:setZoom( 10 )
	Arrow:setImage( RegisterImage( "uie_t7_menu_frontend_buttonfocusarrow" ) )
	Arrow:setMaterial( LUI.UIImage.GetCachedMaterial( "ui_add" ) )
	self:addElement( Arrow )
	self.Arrow = Arrow
	
	local Glow2 = LUI.UIImage.new( 0, 1, -76, 100, 0, 0, -37, 87 )
	Glow2:setAlpha( 0 )
	Glow2:setImage( RegisterImage( "uie_t7_cp_hud_enemytarget_glow" ) )
	Glow2:setMaterial( LUI.UIImage.GetCachedMaterial( "ui_add" ) )
	self:addElement( Glow2 )
	self.Glow2 = Glow2
	
	local Image0 = LUI.UIImage.new( 0, 0, 8, 47, 0, 0, 9, 43 )
	self:addElement( Image0 )
	self.Image0 = Image0
	
	self.btnDisplayText:linkToElementModel( self, "displayText", true, function ( model )
		local f4_local0 = model:get()
		if f4_local0 ~= nil then
			btnDisplayText:setText( Engine[0xF9F1239CFD921FE]( f4_local0 ) )
		end
	end )
	self.btnDisplayTextStroke:linkToElementModel( self, "displayText", true, function ( model )
		local f5_local0 = model:get()
		if f5_local0 ~= nil then
			btnDisplayTextStroke:setText( Engine[0xF9F1239CFD921FE]( f5_local0 ) )
		end
	end )
	self.Image0:linkToElementModel( self, "displayImage", true, function ( model )
		local f6_local0 = model:get()
		if f6_local0 ~= nil then
			Image0:setImage( RegisterImage( f6_local0 ) )
		end
	end )
	self:mergeStateConditions( {
		{
			stateName = "Disabled",
			condition = function ( menu, element, event )
				return IsDisabled( element, f1_arg1 ) and not IsCurrentLanguageArabic()
			end
		},
		{
			stateName = "DefaultStateArabic",
			condition = function ( menu, element, event )
				local f8_local0
				if not IsDisabled( element, f1_arg1 ) then
					f8_local0 = IsCurrentLanguageArabic()
				else
					f8_local0 = false
				end
				return f8_local0
			end
		},
		{
			stateName = "DisabledArabic",
			condition = function ( menu, element, event )
				return IsDisabled( element, f1_arg1 ) and IsCurrentLanguageArabic()
			end
		}
	} )
	self:linkToElementModel( self, "disabled", true, function ( model )
		f1_arg0:updateElementState( self, {
			name = "model_validation",
			menu = f1_arg0,
			controller = f1_arg1,
			modelValue = model:get(),
			modelName = "disabled"
		} )
	end )
	LUI.OverrideFunction_CallOriginalSecond( self, "close", self.__onClose )
	
	if PostLoadFunc then
		PostLoadFunc( self, f1_arg1, f1_arg0 )
	end
	
	return self
end

CoD.FileshareOptionButton.__resetProperties = function ( f11_arg0 )
	f11_arg0.btnDisplayTextStroke:completeAnimation()
	f11_arg0.btnDisplayText:completeAnimation()
	f11_arg0.FEButtonFocus:completeAnimation()
	f11_arg0.FEButtonIdle:completeAnimation()
	f11_arg0.FEButtonPanelShaderContainer:completeAnimation()
	f11_arg0.Arrow:completeAnimation()
	f11_arg0.Glow:completeAnimation()
	f11_arg0.Glow2:completeAnimation()
	f11_arg0.btnDisplayTextStroke:setAlpha( 0.7 )
	f11_arg0.btnDisplayTextStroke:setZoom( 10 )
	f11_arg0.btnDisplayTextStroke:setAlignment( Enum.LUIAlignment[0x58C8A85F2048829] )
	f11_arg0.btnDisplayText:setAlpha( 0 )
	f11_arg0.btnDisplayText:setZoom( 10 )
	f11_arg0.btnDisplayText:setAlignment( Enum.LUIAlignment[0x58C8A85F2048829] )
	f11_arg0.FEButtonFocus:setLeftRight( 0, 1, 0, 0 )
	f11_arg0.FEButtonFocus:setTopBottom( 0.5, 0.5, -21, 21 )
	f11_arg0.FEButtonFocus:setAlpha( 0 )
	f11_arg0.FEButtonFocus:setZoom( 10 )
	f11_arg0.FEButtonIdle:setAlpha( 0.8 )
	f11_arg0.FEButtonIdle:setZoom( 10 )
	f11_arg0.FEButtonPanelShaderContainer:setRGB( 0.5, 0.5, 0.5 )
	f11_arg0.FEButtonPanelShaderContainer:setAlpha( 0 )
	f11_arg0.FEButtonPanelShaderContainer:setZoom( 0 )
	f11_arg0.Arrow:setLeftRight( 0, 0, -30, -18 )
	f11_arg0.Arrow:setTopBottom( 0, 0, 18, 30 )
	f11_arg0.Arrow:setAlpha( 0 )
	f11_arg0.Glow:setAlpha( 0 )
	f11_arg0.Glow2:setAlpha( 0 )
end

CoD.FileshareOptionButton.__clipsPerState = {
	DefaultState = {
		DefaultClip = function ( f12_arg0, f12_arg1 )
			f12_arg0:__resetProperties()
			f12_arg0:setupElementClipCounter( 6 )
			f12_arg0.FEButtonPanelShaderContainer:completeAnimation()
			f12_arg0.FEButtonPanelShaderContainer:setZoom( -10 )
			f12_arg0.clipFinished( f12_arg0.FEButtonPanelShaderContainer )
			f12_arg0.FEButtonIdle:completeAnimation()
			f12_arg0.FEButtonIdle:setAlpha( 1 )
			f12_arg0.FEButtonIdle:setZoom( 0 )
			f12_arg0.clipFinished( f12_arg0.FEButtonIdle )
			f12_arg0.FEButtonFocus:completeAnimation()
			f12_arg0.FEButtonFocus:setLeftRight( 0, 1, 0, 0 )
			f12_arg0.FEButtonFocus:setTopBottom( 0.5, 0.5, -1, 3 )
			f12_arg0.FEButtonFocus:setZoom( 0 )
			f12_arg0.clipFinished( f12_arg0.FEButtonFocus )
			f12_arg0.btnDisplayText:completeAnimation()
			f12_arg0.btnDisplayText:setAlpha( 1 )
			f12_arg0.btnDisplayText:setZoom( 0 )
			f12_arg0.clipFinished( f12_arg0.btnDisplayText )
			f12_arg0.btnDisplayTextStroke:completeAnimation()
			f12_arg0.btnDisplayTextStroke:setAlpha( 0 )
			f12_arg0.btnDisplayTextStroke:setZoom( 0 )
			f12_arg0.clipFinished( f12_arg0.btnDisplayTextStroke )
			f12_arg0.Arrow:completeAnimation()
			f12_arg0.Arrow:setLeftRight( 0, 0, 4, 16 )
			f12_arg0.Arrow:setTopBottom( 0, 0, 18, 30 )
			f12_arg0.clipFinished( f12_arg0.Arrow )
		end,
		Focus = function ( f13_arg0, f13_arg1 )
			f13_arg0:__resetProperties()
			f13_arg0:setupElementClipCounter( 7 )
			f13_arg0.FEButtonIdle:completeAnimation()
			f13_arg0.FEButtonIdle:setAlpha( 0 )
			f13_arg0.clipFinished( f13_arg0.FEButtonIdle )
			f13_arg0.FEButtonFocus:completeAnimation()
			f13_arg0.FEButtonFocus:setAlpha( 1 )
			f13_arg0.clipFinished( f13_arg0.FEButtonFocus )
			f13_arg0.Glow:completeAnimation()
			f13_arg0.Glow:setAlpha( 0.45 )
			f13_arg0.clipFinished( f13_arg0.Glow )
			f13_arg0.btnDisplayText:completeAnimation()
			f13_arg0.btnDisplayText:setZoom( -305 )
			f13_arg0.clipFinished( f13_arg0.btnDisplayText )
			f13_arg0.btnDisplayTextStroke:completeAnimation()
			f13_arg0.btnDisplayTextStroke:setAlpha( 1 )
			f13_arg0.clipFinished( f13_arg0.btnDisplayTextStroke )
			f13_arg0.Arrow:completeAnimation()
			f13_arg0.Arrow:setAlpha( 1 )
			f13_arg0.clipFinished( f13_arg0.Arrow )
			f13_arg0.Glow2:completeAnimation()
			f13_arg0.Glow2:setAlpha( 1 )
			f13_arg0.clipFinished( f13_arg0.Glow2 )
		end,
		LoseFocus = function ( f14_arg0, f14_arg1 )
			f14_arg0:__resetProperties()
			f14_arg0:setupElementClipCounter( 8 )
			local f14_local0 = function ( f15_arg0 )
				f14_arg0.FEButtonPanelShaderContainer:beginAnimation( 200 )
				f14_arg0.FEButtonPanelShaderContainer:setZoom( -10 )
				f14_arg0.FEButtonPanelShaderContainer:registerEventHandler( "interrupted_keyframe", f14_arg0.clipInterrupted )
				f14_arg0.FEButtonPanelShaderContainer:registerEventHandler( "transition_complete_keyframe", f14_arg0.clipFinished )
			end
			
			f14_arg0.FEButtonPanelShaderContainer:completeAnimation()
			f14_arg0.FEButtonPanelShaderContainer:setRGB( 0.5, 0.5, 0.5 )
			f14_arg0.FEButtonPanelShaderContainer:setAlpha( 0 )
			f14_arg0.FEButtonPanelShaderContainer:setZoom( 0 )
			f14_local0( f14_arg0.FEButtonPanelShaderContainer )
			local f14_local1 = function ( f16_arg0 )
				f14_arg0.FEButtonIdle:beginAnimation( 200 )
				f14_arg0.FEButtonIdle:setAlpha( 1 )
				f14_arg0.FEButtonIdle:setZoom( 0 )
				f14_arg0.FEButtonIdle:registerEventHandler( "interrupted_keyframe", f14_arg0.clipInterrupted )
				f14_arg0.FEButtonIdle:registerEventHandler( "transition_complete_keyframe", f14_arg0.clipFinished )
			end
			
			f14_arg0.FEButtonIdle:completeAnimation()
			f14_arg0.FEButtonIdle:setAlpha( 0 )
			f14_arg0.FEButtonIdle:setZoom( 10 )
			f14_local1( f14_arg0.FEButtonIdle )
			local f14_local2 = function ( f17_arg0 )
				f14_arg0.FEButtonFocus:beginAnimation( 200 )
				f14_arg0.FEButtonFocus:setTopBottom( 0.5, 0.5, -1, 3 )
				f14_arg0.FEButtonFocus:setAlpha( 0 )
				f14_arg0.FEButtonFocus:setZoom( 0 )
				f14_arg0.FEButtonFocus:registerEventHandler( "interrupted_keyframe", f14_arg0.clipInterrupted )
				f14_arg0.FEButtonFocus:registerEventHandler( "transition_complete_keyframe", f14_arg0.clipFinished )
			end
			
			f14_arg0.FEButtonFocus:completeAnimation()
			f14_arg0.FEButtonFocus:setLeftRight( 0, 1, 0, 0 )
			f14_arg0.FEButtonFocus:setTopBottom( 0.5, 0.5, -21, 21 )
			f14_arg0.FEButtonFocus:setAlpha( 1 )
			f14_arg0.FEButtonFocus:setZoom( 10 )
			f14_local2( f14_arg0.FEButtonFocus )
			local f14_local3 = function ( f18_arg0 )
				f14_arg0.Glow:beginAnimation( 520 )
				f14_arg0.Glow:setAlpha( 0 )
				f14_arg0.Glow:registerEventHandler( "interrupted_keyframe", f14_arg0.clipInterrupted )
				f14_arg0.Glow:registerEventHandler( "transition_complete_keyframe", f14_arg0.clipFinished )
			end
			
			f14_arg0.Glow:completeAnimation()
			f14_arg0.Glow:setAlpha( 0.45 )
			f14_local3( f14_arg0.Glow )
			local f14_local4 = function ( f19_arg0 )
				f14_arg0.btnDisplayText:beginAnimation( 200 )
				f14_arg0.btnDisplayText:setAlpha( 1 )
				f14_arg0.btnDisplayText:setZoom( 0 )
				f14_arg0.btnDisplayText:registerEventHandler( "interrupted_keyframe", f14_arg0.clipInterrupted )
				f14_arg0.btnDisplayText:registerEventHandler( "transition_complete_keyframe", f14_arg0.clipFinished )
			end
			
			f14_arg0.btnDisplayText:completeAnimation()
			f14_arg0.btnDisplayText:setAlpha( 0 )
			f14_arg0.btnDisplayText:setZoom( 10 )
			f14_local4( f14_arg0.btnDisplayText )
			local f14_local5 = function ( f20_arg0 )
				f14_arg0.btnDisplayTextStroke:beginAnimation( 200 )
				f14_arg0.btnDisplayTextStroke:setAlpha( 0 )
				f14_arg0.btnDisplayTextStroke:setZoom( 0 )
				f14_arg0.btnDisplayTextStroke:registerEventHandler( "interrupted_keyframe", f14_arg0.clipInterrupted )
				f14_arg0.btnDisplayTextStroke:registerEventHandler( "transition_complete_keyframe", f14_arg0.clipFinished )
			end
			
			f14_arg0.btnDisplayTextStroke:completeAnimation()
			f14_arg0.btnDisplayTextStroke:setAlpha( 1 )
			f14_arg0.btnDisplayTextStroke:setZoom( 10 )
			f14_local5( f14_arg0.btnDisplayTextStroke )
			local f14_local6 = function ( f21_arg0 )
				f14_arg0.Arrow:beginAnimation( 200 )
				f14_arg0.Arrow:setLeftRight( 0, 0, 4, 16 )
				f14_arg0.Arrow:setAlpha( 0 )
				f14_arg0.Arrow:registerEventHandler( "interrupted_keyframe", f14_arg0.clipInterrupted )
				f14_arg0.Arrow:registerEventHandler( "transition_complete_keyframe", f14_arg0.clipFinished )
			end
			
			f14_arg0.Arrow:completeAnimation()
			f14_arg0.Arrow:setLeftRight( 0, 0, -30, -18 )
			f14_arg0.Arrow:setTopBottom( 0, 0, 18, 30 )
			f14_arg0.Arrow:setAlpha( 1 )
			f14_local6( f14_arg0.Arrow )
			local f14_local7 = function ( f22_arg0 )
				f14_arg0.Glow2:beginAnimation( 300 )
				f14_arg0.Glow2:setAlpha( 0 )
				f14_arg0.Glow2:registerEventHandler( "interrupted_keyframe", f14_arg0.clipInterrupted )
				f14_arg0.Glow2:registerEventHandler( "transition_complete_keyframe", f14_arg0.clipFinished )
			end
			
			f14_arg0.Glow2:completeAnimation()
			f14_arg0.Glow2:setAlpha( 1 )
			f14_local7( f14_arg0.Glow2 )
		end,
		GainFocus = function ( f23_arg0, f23_arg1 )
			f23_arg0:__resetProperties()
			f23_arg0:setupElementClipCounter( 8 )
			local f23_local0 = function ( f24_arg0 )
				f23_arg0.FEButtonPanelShaderContainer:beginAnimation( 50 )
				f23_arg0.FEButtonPanelShaderContainer:setAlpha( 1 )
				f23_arg0.FEButtonPanelShaderContainer:setZoom( 0 )
				f23_arg0.FEButtonPanelShaderContainer:registerEventHandler( "interrupted_keyframe", f23_arg0.clipInterrupted )
				f23_arg0.FEButtonPanelShaderContainer:registerEventHandler( "transition_complete_keyframe", f23_arg0.clipFinished )
			end
			
			f23_arg0.FEButtonPanelShaderContainer:completeAnimation()
			f23_arg0.FEButtonPanelShaderContainer:setRGB( 0.5, 0.5, 0.5 )
			f23_arg0.FEButtonPanelShaderContainer:setAlpha( 0 )
			f23_arg0.FEButtonPanelShaderContainer:setZoom( -10 )
			f23_local0( f23_arg0.FEButtonPanelShaderContainer )
			local f23_local1 = function ( f25_arg0 )
				f23_arg0.FEButtonIdle:beginAnimation( 50 )
				f23_arg0.FEButtonIdle:setAlpha( 0 )
				f23_arg0.FEButtonIdle:setZoom( 10 )
				f23_arg0.FEButtonIdle:registerEventHandler( "interrupted_keyframe", f23_arg0.clipInterrupted )
				f23_arg0.FEButtonIdle:registerEventHandler( "transition_complete_keyframe", f23_arg0.clipFinished )
			end
			
			f23_arg0.FEButtonIdle:completeAnimation()
			f23_arg0.FEButtonIdle:setAlpha( 1 )
			f23_arg0.FEButtonIdle:setZoom( 0 )
			f23_local1( f23_arg0.FEButtonIdle )
			local f23_local2 = function ( f26_arg0 )
				f23_arg0.FEButtonFocus:beginAnimation( 50 )
				f23_arg0.FEButtonFocus:setAlpha( 1 )
				f23_arg0.FEButtonFocus:setZoom( 10 )
				f23_arg0.FEButtonFocus:registerEventHandler( "interrupted_keyframe", f23_arg0.clipInterrupted )
				f23_arg0.FEButtonFocus:registerEventHandler( "transition_complete_keyframe", f23_arg0.clipFinished )
			end
			
			f23_arg0.FEButtonFocus:completeAnimation()
			f23_arg0.FEButtonFocus:setLeftRight( 0, 1, 0, 0 )
			f23_arg0.FEButtonFocus:setTopBottom( 0.5, 0.5, -21, 21 )
			f23_arg0.FEButtonFocus:setAlpha( 0 )
			f23_arg0.FEButtonFocus:setZoom( 0 )
			f23_local2( f23_arg0.FEButtonFocus )
			local f23_local3 = function ( f27_arg0 )
				f23_arg0.Glow:beginAnimation( 50 )
				f23_arg0.Glow:setAlpha( 0.45 )
				f23_arg0.Glow:registerEventHandler( "interrupted_keyframe", f23_arg0.clipInterrupted )
				f23_arg0.Glow:registerEventHandler( "transition_complete_keyframe", f23_arg0.clipFinished )
			end
			
			f23_arg0.Glow:completeAnimation()
			f23_arg0.Glow:setAlpha( 0 )
			f23_local3( f23_arg0.Glow )
			local f23_local4 = function ( f28_arg0 )
				f23_arg0.btnDisplayText:beginAnimation( 50 )
				f23_arg0.btnDisplayText:setAlpha( 0 )
				f23_arg0.btnDisplayText:setZoom( 10 )
				f23_arg0.btnDisplayText:registerEventHandler( "interrupted_keyframe", f23_arg0.clipInterrupted )
				f23_arg0.btnDisplayText:registerEventHandler( "transition_complete_keyframe", f23_arg0.clipFinished )
			end
			
			f23_arg0.btnDisplayText:completeAnimation()
			f23_arg0.btnDisplayText:setAlpha( 1 )
			f23_arg0.btnDisplayText:setZoom( 0 )
			f23_local4( f23_arg0.btnDisplayText )
			local f23_local5 = function ( f29_arg0 )
				f23_arg0.btnDisplayTextStroke:beginAnimation( 50 )
				f23_arg0.btnDisplayTextStroke:setAlpha( 1 )
				f23_arg0.btnDisplayTextStroke:setZoom( 10 )
				f23_arg0.btnDisplayTextStroke:registerEventHandler( "interrupted_keyframe", f23_arg0.clipInterrupted )
				f23_arg0.btnDisplayTextStroke:registerEventHandler( "transition_complete_keyframe", f23_arg0.clipFinished )
			end
			
			f23_arg0.btnDisplayTextStroke:completeAnimation()
			f23_arg0.btnDisplayTextStroke:setAlpha( 0 )
			f23_arg0.btnDisplayTextStroke:setZoom( 0 )
			f23_local5( f23_arg0.btnDisplayTextStroke )
			local f23_local6 = function ( f30_arg0 )
				f23_arg0.Arrow:beginAnimation( 50 )
				f23_arg0.Arrow:setLeftRight( 0, 0, -30, -18 )
				f23_arg0.Arrow:setAlpha( 1 )
				f23_arg0.Arrow:registerEventHandler( "interrupted_keyframe", f23_arg0.clipInterrupted )
				f23_arg0.Arrow:registerEventHandler( "transition_complete_keyframe", f23_arg0.clipFinished )
			end
			
			f23_arg0.Arrow:completeAnimation()
			f23_arg0.Arrow:setLeftRight( 0, 0, 4, 16 )
			f23_arg0.Arrow:setTopBottom( 0, 0, 18, 30 )
			f23_arg0.Arrow:setAlpha( 0 )
			f23_local6( f23_arg0.Arrow )
			local f23_local7 = function ( f31_arg0 )
				f23_arg0.Glow2:beginAnimation( 50 )
				f23_arg0.Glow2:setAlpha( 1 )
				f23_arg0.Glow2:registerEventHandler( "interrupted_keyframe", f23_arg0.clipInterrupted )
				f23_arg0.Glow2:registerEventHandler( "transition_complete_keyframe", f23_arg0.clipFinished )
			end
			
			f23_arg0.Glow2:completeAnimation()
			f23_arg0.Glow2:setAlpha( 0 )
			f23_local7( f23_arg0.Glow2 )
		end
	},
	Disabled = {
		DefaultClip = function ( f32_arg0, f32_arg1 )
			f32_arg0:__resetProperties()
			f32_arg0:setupElementClipCounter( 6 )
			f32_arg0.FEButtonPanelShaderContainer:completeAnimation()
			f32_arg0.FEButtonPanelShaderContainer:setZoom( -10 )
			f32_arg0.clipFinished( f32_arg0.FEButtonPanelShaderContainer )
			f32_arg0.FEButtonIdle:completeAnimation()
			f32_arg0.FEButtonIdle:setAlpha( 0.3 )
			f32_arg0.FEButtonIdle:setZoom( 0 )
			f32_arg0.clipFinished( f32_arg0.FEButtonIdle )
			f32_arg0.FEButtonFocus:completeAnimation()
			f32_arg0.FEButtonFocus:setLeftRight( 0, 1, 0, 0 )
			f32_arg0.FEButtonFocus:setTopBottom( 0.5, 0.5, -1, 3 )
			f32_arg0.FEButtonFocus:setZoom( 0 )
			f32_arg0.clipFinished( f32_arg0.FEButtonFocus )
			f32_arg0.btnDisplayText:completeAnimation()
			f32_arg0.btnDisplayText:setAlpha( 0.1 )
			f32_arg0.btnDisplayText:setZoom( 0 )
			f32_arg0.clipFinished( f32_arg0.btnDisplayText )
			f32_arg0.btnDisplayTextStroke:completeAnimation()
			f32_arg0.btnDisplayTextStroke:setAlpha( 0 )
			f32_arg0.btnDisplayTextStroke:setZoom( 0 )
			f32_arg0.clipFinished( f32_arg0.btnDisplayTextStroke )
			f32_arg0.Arrow:completeAnimation()
			f32_arg0.Arrow:setLeftRight( 0, 0, 4, 16 )
			f32_arg0.Arrow:setTopBottom( 0, 0, 18, 30 )
			f32_arg0.clipFinished( f32_arg0.Arrow )
		end,
		LoseFocus = function ( f33_arg0, f33_arg1 )
			f33_arg0:__resetProperties()
			f33_arg0:setupElementClipCounter( 8 )
			local f33_local0 = function ( f34_arg0 )
				f33_arg0.FEButtonPanelShaderContainer:beginAnimation( 200 )
				f33_arg0.FEButtonPanelShaderContainer:setZoom( -10 )
				f33_arg0.FEButtonPanelShaderContainer:registerEventHandler( "interrupted_keyframe", f33_arg0.clipInterrupted )
				f33_arg0.FEButtonPanelShaderContainer:registerEventHandler( "transition_complete_keyframe", f33_arg0.clipFinished )
			end
			
			f33_arg0.FEButtonPanelShaderContainer:completeAnimation()
			f33_arg0.FEButtonPanelShaderContainer:setRGB( 0.5, 0.5, 0.5 )
			f33_arg0.FEButtonPanelShaderContainer:setAlpha( 0 )
			f33_arg0.FEButtonPanelShaderContainer:setZoom( 0 )
			f33_local0( f33_arg0.FEButtonPanelShaderContainer )
			local f33_local1 = function ( f35_arg0 )
				f33_arg0.FEButtonIdle:beginAnimation( 200 )
				f33_arg0.FEButtonIdle:setAlpha( 0.3 )
				f33_arg0.FEButtonIdle:setZoom( 0 )
				f33_arg0.FEButtonIdle:registerEventHandler( "interrupted_keyframe", f33_arg0.clipInterrupted )
				f33_arg0.FEButtonIdle:registerEventHandler( "transition_complete_keyframe", f33_arg0.clipFinished )
			end
			
			f33_arg0.FEButtonIdle:completeAnimation()
			f33_arg0.FEButtonIdle:setAlpha( 0.8 )
			f33_arg0.FEButtonIdle:setZoom( 10 )
			f33_local1( f33_arg0.FEButtonIdle )
			local f33_local2 = function ( f36_arg0 )
				f33_arg0.FEButtonFocus:beginAnimation( 200 )
				f33_arg0.FEButtonFocus:setTopBottom( 0.5, 0.5, -1, 3 )
				f33_arg0.FEButtonFocus:setZoom( 0 )
				f33_arg0.FEButtonFocus:registerEventHandler( "interrupted_keyframe", f33_arg0.clipInterrupted )
				f33_arg0.FEButtonFocus:registerEventHandler( "transition_complete_keyframe", f33_arg0.clipFinished )
			end
			
			f33_arg0.FEButtonFocus:completeAnimation()
			f33_arg0.FEButtonFocus:setLeftRight( 0, 1, 0, 0 )
			f33_arg0.FEButtonFocus:setTopBottom( 0.5, 0.5, -21, 21 )
			f33_arg0.FEButtonFocus:setAlpha( 0 )
			f33_arg0.FEButtonFocus:setZoom( 10 )
			f33_local2( f33_arg0.FEButtonFocus )
			local f33_local3 = function ( f37_arg0 )
				f33_arg0.Glow:beginAnimation( 520 )
				f33_arg0.Glow:registerEventHandler( "interrupted_keyframe", f33_arg0.clipInterrupted )
				f33_arg0.Glow:registerEventHandler( "transition_complete_keyframe", f33_arg0.clipFinished )
			end
			
			f33_arg0.Glow:completeAnimation()
			f33_arg0.Glow:setAlpha( 0 )
			f33_local3( f33_arg0.Glow )
			local f33_local4 = function ( f38_arg0 )
				f33_arg0.btnDisplayText:beginAnimation( 200 )
				f33_arg0.btnDisplayText:setAlpha( 0.1 )
				f33_arg0.btnDisplayText:setZoom( 0 )
				f33_arg0.btnDisplayText:registerEventHandler( "interrupted_keyframe", f33_arg0.clipInterrupted )
				f33_arg0.btnDisplayText:registerEventHandler( "transition_complete_keyframe", f33_arg0.clipFinished )
			end
			
			f33_arg0.btnDisplayText:completeAnimation()
			f33_arg0.btnDisplayText:setAlpha( 0 )
			f33_arg0.btnDisplayText:setZoom( 10 )
			f33_local4( f33_arg0.btnDisplayText )
			local f33_local5 = function ( f39_arg0 )
				f33_arg0.btnDisplayTextStroke:beginAnimation( 200 )
				f33_arg0.btnDisplayTextStroke:setAlpha( 0 )
				f33_arg0.btnDisplayTextStroke:setZoom( 0 )
				f33_arg0.btnDisplayTextStroke:registerEventHandler( "interrupted_keyframe", f33_arg0.clipInterrupted )
				f33_arg0.btnDisplayTextStroke:registerEventHandler( "transition_complete_keyframe", f33_arg0.clipFinished )
			end
			
			f33_arg0.btnDisplayTextStroke:completeAnimation()
			f33_arg0.btnDisplayTextStroke:setAlpha( 0.7 )
			f33_arg0.btnDisplayTextStroke:setZoom( 10 )
			f33_local5( f33_arg0.btnDisplayTextStroke )
			local f33_local6 = function ( f40_arg0 )
				f33_arg0.Arrow:beginAnimation( 200 )
				f33_arg0.Arrow:setLeftRight( 0, 0, 4, 16 )
				f33_arg0.Arrow:registerEventHandler( "interrupted_keyframe", f33_arg0.clipInterrupted )
				f33_arg0.Arrow:registerEventHandler( "transition_complete_keyframe", f33_arg0.clipFinished )
			end
			
			f33_arg0.Arrow:completeAnimation()
			f33_arg0.Arrow:setLeftRight( 0, 0, -30, -18 )
			f33_arg0.Arrow:setTopBottom( 0, 0, 18, 30 )
			f33_arg0.Arrow:setAlpha( 0 )
			f33_local6( f33_arg0.Arrow )
			local f33_local7 = function ( f41_arg0 )
				f33_arg0.Glow2:beginAnimation( 300 )
				f33_arg0.Glow2:registerEventHandler( "interrupted_keyframe", f33_arg0.clipInterrupted )
				f33_arg0.Glow2:registerEventHandler( "transition_complete_keyframe", f33_arg0.clipFinished )
			end
			
			f33_arg0.Glow2:completeAnimation()
			f33_arg0.Glow2:setAlpha( 0 )
			f33_local7( f33_arg0.Glow2 )
		end,
		GainFocus = function ( f42_arg0, f42_arg1 )
			f42_arg0:__resetProperties()
			f42_arg0:setupElementClipCounter( 8 )
			local f42_local0 = function ( f43_arg0 )
				f42_arg0.FEButtonPanelShaderContainer:beginAnimation( 50 )
				f42_arg0.FEButtonPanelShaderContainer:setZoom( 0 )
				f42_arg0.FEButtonPanelShaderContainer:registerEventHandler( "interrupted_keyframe", f42_arg0.clipInterrupted )
				f42_arg0.FEButtonPanelShaderContainer:registerEventHandler( "transition_complete_keyframe", f42_arg0.clipFinished )
			end
			
			f42_arg0.FEButtonPanelShaderContainer:completeAnimation()
			f42_arg0.FEButtonPanelShaderContainer:setRGB( 0.5, 0.5, 0.5 )
			f42_arg0.FEButtonPanelShaderContainer:setAlpha( 0 )
			f42_arg0.FEButtonPanelShaderContainer:setZoom( -10 )
			f42_local0( f42_arg0.FEButtonPanelShaderContainer )
			local f42_local1 = function ( f44_arg0 )
				f42_arg0.FEButtonIdle:beginAnimation( 50 )
				f42_arg0.FEButtonIdle:setAlpha( 0.8 )
				f42_arg0.FEButtonIdle:setZoom( 10 )
				f42_arg0.FEButtonIdle:registerEventHandler( "interrupted_keyframe", f42_arg0.clipInterrupted )
				f42_arg0.FEButtonIdle:registerEventHandler( "transition_complete_keyframe", f42_arg0.clipFinished )
			end
			
			f42_arg0.FEButtonIdle:completeAnimation()
			f42_arg0.FEButtonIdle:setAlpha( 0.3 )
			f42_arg0.FEButtonIdle:setZoom( 0 )
			f42_local1( f42_arg0.FEButtonIdle )
			local f42_local2 = function ( f45_arg0 )
				f42_arg0.FEButtonFocus:beginAnimation( 50 )
				f42_arg0.FEButtonFocus:setZoom( 10 )
				f42_arg0.FEButtonFocus:registerEventHandler( "interrupted_keyframe", f42_arg0.clipInterrupted )
				f42_arg0.FEButtonFocus:registerEventHandler( "transition_complete_keyframe", f42_arg0.clipFinished )
			end
			
			f42_arg0.FEButtonFocus:completeAnimation()
			f42_arg0.FEButtonFocus:setLeftRight( 0, 1, 0, 0 )
			f42_arg0.FEButtonFocus:setTopBottom( 0.5, 0.5, -21, 21 )
			f42_arg0.FEButtonFocus:setAlpha( 0 )
			f42_arg0.FEButtonFocus:setZoom( 0 )
			f42_local2( f42_arg0.FEButtonFocus )
			local f42_local3 = function ( f46_arg0 )
				f42_arg0.Glow:beginAnimation( 50 )
				f42_arg0.Glow:registerEventHandler( "interrupted_keyframe", f42_arg0.clipInterrupted )
				f42_arg0.Glow:registerEventHandler( "transition_complete_keyframe", f42_arg0.clipFinished )
			end
			
			f42_arg0.Glow:completeAnimation()
			f42_arg0.Glow:setAlpha( 0 )
			f42_local3( f42_arg0.Glow )
			local f42_local4 = function ( f47_arg0 )
				f42_arg0.btnDisplayText:beginAnimation( 50 )
				f42_arg0.btnDisplayText:setZoom( 10 )
				f42_arg0.btnDisplayText:registerEventHandler( "interrupted_keyframe", f42_arg0.clipInterrupted )
				f42_arg0.btnDisplayText:registerEventHandler( "transition_complete_keyframe", f42_arg0.clipFinished )
			end
			
			f42_arg0.btnDisplayText:completeAnimation()
			f42_arg0.btnDisplayText:setAlpha( 0 )
			f42_arg0.btnDisplayText:setZoom( 0 )
			f42_local4( f42_arg0.btnDisplayText )
			local f42_local5 = function ( f48_arg0 )
				f42_arg0.btnDisplayTextStroke:beginAnimation( 50 )
				f42_arg0.btnDisplayTextStroke:setAlpha( 0.7 )
				f42_arg0.btnDisplayTextStroke:setZoom( 10 )
				f42_arg0.btnDisplayTextStroke:registerEventHandler( "interrupted_keyframe", f42_arg0.clipInterrupted )
				f42_arg0.btnDisplayTextStroke:registerEventHandler( "transition_complete_keyframe", f42_arg0.clipFinished )
			end
			
			f42_arg0.btnDisplayTextStroke:completeAnimation()
			f42_arg0.btnDisplayTextStroke:setAlpha( 0 )
			f42_arg0.btnDisplayTextStroke:setZoom( 0 )
			f42_local5( f42_arg0.btnDisplayTextStroke )
			local f42_local6 = function ( f49_arg0 )
				f42_arg0.Arrow:beginAnimation( 50 )
				f42_arg0.Arrow:setLeftRight( 0, 0, -30, -18 )
				f42_arg0.Arrow:registerEventHandler( "interrupted_keyframe", f42_arg0.clipInterrupted )
				f42_arg0.Arrow:registerEventHandler( "transition_complete_keyframe", f42_arg0.clipFinished )
			end
			
			f42_arg0.Arrow:completeAnimation()
			f42_arg0.Arrow:setLeftRight( 0, 0, 4, 16 )
			f42_arg0.Arrow:setTopBottom( 0, 0, 18, 30 )
			f42_arg0.Arrow:setAlpha( 0 )
			f42_local6( f42_arg0.Arrow )
			local f42_local7 = function ( f50_arg0 )
				f42_arg0.Glow2:beginAnimation( 50 )
				f42_arg0.Glow2:registerEventHandler( "interrupted_keyframe", f42_arg0.clipInterrupted )
				f42_arg0.Glow2:registerEventHandler( "transition_complete_keyframe", f42_arg0.clipFinished )
			end
			
			f42_arg0.Glow2:completeAnimation()
			f42_arg0.Glow2:setAlpha( 0 )
			f42_local7( f42_arg0.Glow2 )
		end
	},
	DefaultStateArabic = {
		DefaultClip = function ( f51_arg0, f51_arg1 )
			f51_arg0:__resetProperties()
			f51_arg0:setupElementClipCounter( 6 )
			f51_arg0.FEButtonPanelShaderContainer:completeAnimation()
			f51_arg0.FEButtonPanelShaderContainer:setZoom( -10 )
			f51_arg0.clipFinished( f51_arg0.FEButtonPanelShaderContainer )
			f51_arg0.FEButtonIdle:completeAnimation()
			f51_arg0.FEButtonIdle:setAlpha( 1 )
			f51_arg0.FEButtonIdle:setZoom( 0 )
			f51_arg0.clipFinished( f51_arg0.FEButtonIdle )
			f51_arg0.FEButtonFocus:completeAnimation()
			f51_arg0.FEButtonFocus:setLeftRight( 0, 1, 0, 0 )
			f51_arg0.FEButtonFocus:setTopBottom( 0.5, 0.5, -1, 3 )
			f51_arg0.FEButtonFocus:setZoom( 0 )
			f51_arg0.clipFinished( f51_arg0.FEButtonFocus )
			f51_arg0.btnDisplayText:completeAnimation()
			f51_arg0.btnDisplayText:setAlpha( 1 )
			f51_arg0.btnDisplayText:setZoom( 0 )
			f51_arg0.btnDisplayText:setAlignment( Enum.LUIAlignment[0x830CFD395E6AA0A] )
			f51_arg0.clipFinished( f51_arg0.btnDisplayText )
			f51_arg0.btnDisplayTextStroke:completeAnimation()
			f51_arg0.btnDisplayTextStroke:setAlpha( 0 )
			f51_arg0.btnDisplayTextStroke:setZoom( 0 )
			f51_arg0.btnDisplayTextStroke:setAlignment( Enum.LUIAlignment[0x830CFD395E6AA0A] )
			f51_arg0.clipFinished( f51_arg0.btnDisplayTextStroke )
			f51_arg0.Arrow:completeAnimation()
			f51_arg0.Arrow:setLeftRight( 0, 0, 4, 16 )
			f51_arg0.Arrow:setTopBottom( 0, 0, 18, 30 )
			f51_arg0.clipFinished( f51_arg0.Arrow )
		end,
		Focus = function ( f52_arg0, f52_arg1 )
			f52_arg0:__resetProperties()
			f52_arg0:setupElementClipCounter( 8 )
			f52_arg0.FEButtonPanelShaderContainer:completeAnimation()
			f52_arg0.FEButtonPanelShaderContainer:setAlpha( 1 )
			f52_arg0.clipFinished( f52_arg0.FEButtonPanelShaderContainer )
			f52_arg0.FEButtonIdle:completeAnimation()
			f52_arg0.FEButtonIdle:setAlpha( 0 )
			f52_arg0.clipFinished( f52_arg0.FEButtonIdle )
			f52_arg0.FEButtonFocus:completeAnimation()
			f52_arg0.FEButtonFocus:setAlpha( 1 )
			f52_arg0.clipFinished( f52_arg0.FEButtonFocus )
			f52_arg0.Glow:completeAnimation()
			f52_arg0.Glow:setAlpha( 0.45 )
			f52_arg0.clipFinished( f52_arg0.Glow )
			f52_arg0.btnDisplayText:completeAnimation()
			f52_arg0.btnDisplayText:setZoom( -305 )
			f52_arg0.clipFinished( f52_arg0.btnDisplayText )
			f52_arg0.btnDisplayTextStroke:completeAnimation()
			f52_arg0.btnDisplayTextStroke:setAlpha( 1 )
			f52_arg0.clipFinished( f52_arg0.btnDisplayTextStroke )
			f52_arg0.Arrow:completeAnimation()
			f52_arg0.Arrow:setAlpha( 1 )
			f52_arg0.clipFinished( f52_arg0.Arrow )
			f52_arg0.Glow2:completeAnimation()
			f52_arg0.Glow2:setAlpha( 1 )
			f52_arg0.clipFinished( f52_arg0.Glow2 )
		end,
		LoseFocus = function ( f53_arg0, f53_arg1 )
			f53_arg0:__resetProperties()
			f53_arg0:setupElementClipCounter( 8 )
			local f53_local0 = function ( f54_arg0 )
				f53_arg0.FEButtonPanelShaderContainer:beginAnimation( 200 )
				f53_arg0.FEButtonPanelShaderContainer:setZoom( -10 )
				f53_arg0.FEButtonPanelShaderContainer:registerEventHandler( "interrupted_keyframe", f53_arg0.clipInterrupted )
				f53_arg0.FEButtonPanelShaderContainer:registerEventHandler( "transition_complete_keyframe", f53_arg0.clipFinished )
			end
			
			f53_arg0.FEButtonPanelShaderContainer:completeAnimation()
			f53_arg0.FEButtonPanelShaderContainer:setRGB( 0.5, 0.5, 0.5 )
			f53_arg0.FEButtonPanelShaderContainer:setAlpha( 1 )
			f53_arg0.FEButtonPanelShaderContainer:setZoom( 0 )
			f53_local0( f53_arg0.FEButtonPanelShaderContainer )
			local f53_local1 = function ( f55_arg0 )
				f53_arg0.FEButtonIdle:beginAnimation( 200 )
				f53_arg0.FEButtonIdle:setAlpha( 1 )
				f53_arg0.FEButtonIdle:setZoom( 0 )
				f53_arg0.FEButtonIdle:registerEventHandler( "interrupted_keyframe", f53_arg0.clipInterrupted )
				f53_arg0.FEButtonIdle:registerEventHandler( "transition_complete_keyframe", f53_arg0.clipFinished )
			end
			
			f53_arg0.FEButtonIdle:completeAnimation()
			f53_arg0.FEButtonIdle:setAlpha( 0 )
			f53_arg0.FEButtonIdle:setZoom( 10 )
			f53_local1( f53_arg0.FEButtonIdle )
			local f53_local2 = function ( f56_arg0 )
				f53_arg0.FEButtonFocus:beginAnimation( 200 )
				f53_arg0.FEButtonFocus:setTopBottom( 0.5, 0.5, -1, 3 )
				f53_arg0.FEButtonFocus:setAlpha( 0 )
				f53_arg0.FEButtonFocus:setZoom( 0 )
				f53_arg0.FEButtonFocus:registerEventHandler( "interrupted_keyframe", f53_arg0.clipInterrupted )
				f53_arg0.FEButtonFocus:registerEventHandler( "transition_complete_keyframe", f53_arg0.clipFinished )
			end
			
			f53_arg0.FEButtonFocus:completeAnimation()
			f53_arg0.FEButtonFocus:setLeftRight( 0, 1, 0, 0 )
			f53_arg0.FEButtonFocus:setTopBottom( 0.5, 0.5, -21, 21 )
			f53_arg0.FEButtonFocus:setAlpha( 1 )
			f53_arg0.FEButtonFocus:setZoom( 10 )
			f53_local2( f53_arg0.FEButtonFocus )
			local f53_local3 = function ( f57_arg0 )
				f53_arg0.Glow:beginAnimation( 520 )
				f53_arg0.Glow:setAlpha( 0 )
				f53_arg0.Glow:registerEventHandler( "interrupted_keyframe", f53_arg0.clipInterrupted )
				f53_arg0.Glow:registerEventHandler( "transition_complete_keyframe", f53_arg0.clipFinished )
			end
			
			f53_arg0.Glow:completeAnimation()
			f53_arg0.Glow:setAlpha( 0.45 )
			f53_local3( f53_arg0.Glow )
			local f53_local4 = function ( f58_arg0 )
				f53_arg0.btnDisplayText:beginAnimation( 200 )
				f53_arg0.btnDisplayText:setAlpha( 1 )
				f53_arg0.btnDisplayText:setZoom( 0 )
				f53_arg0.btnDisplayText:registerEventHandler( "interrupted_keyframe", f53_arg0.clipInterrupted )
				f53_arg0.btnDisplayText:registerEventHandler( "transition_complete_keyframe", f53_arg0.clipFinished )
			end
			
			f53_arg0.btnDisplayText:completeAnimation()
			f53_arg0.btnDisplayText:setAlpha( 0 )
			f53_arg0.btnDisplayText:setZoom( 10 )
			f53_local4( f53_arg0.btnDisplayText )
			local f53_local5 = function ( f59_arg0 )
				f53_arg0.btnDisplayTextStroke:beginAnimation( 200 )
				f53_arg0.btnDisplayTextStroke:setAlpha( 0 )
				f53_arg0.btnDisplayTextStroke:setZoom( 0 )
				f53_arg0.btnDisplayTextStroke:registerEventHandler( "interrupted_keyframe", f53_arg0.clipInterrupted )
				f53_arg0.btnDisplayTextStroke:registerEventHandler( "transition_complete_keyframe", f53_arg0.clipFinished )
			end
			
			f53_arg0.btnDisplayTextStroke:completeAnimation()
			f53_arg0.btnDisplayTextStroke:setAlpha( 1 )
			f53_arg0.btnDisplayTextStroke:setZoom( 10 )
			f53_local5( f53_arg0.btnDisplayTextStroke )
			local f53_local6 = function ( f60_arg0 )
				f53_arg0.Arrow:beginAnimation( 200 )
				f53_arg0.Arrow:setLeftRight( 0, 0, 4, 16 )
				f53_arg0.Arrow:setAlpha( 0 )
				f53_arg0.Arrow:registerEventHandler( "interrupted_keyframe", f53_arg0.clipInterrupted )
				f53_arg0.Arrow:registerEventHandler( "transition_complete_keyframe", f53_arg0.clipFinished )
			end
			
			f53_arg0.Arrow:completeAnimation()
			f53_arg0.Arrow:setLeftRight( 0, 0, -30, -18 )
			f53_arg0.Arrow:setTopBottom( 0, 0, 18, 30 )
			f53_arg0.Arrow:setAlpha( 1 )
			f53_local6( f53_arg0.Arrow )
			local f53_local7 = function ( f61_arg0 )
				f53_arg0.Glow2:beginAnimation( 300 )
				f53_arg0.Glow2:setAlpha( 0 )
				f53_arg0.Glow2:registerEventHandler( "interrupted_keyframe", f53_arg0.clipInterrupted )
				f53_arg0.Glow2:registerEventHandler( "transition_complete_keyframe", f53_arg0.clipFinished )
			end
			
			f53_arg0.Glow2:completeAnimation()
			f53_arg0.Glow2:setAlpha( 1 )
			f53_local7( f53_arg0.Glow2 )
		end,
		GainFocus = function ( f62_arg0, f62_arg1 )
			f62_arg0:__resetProperties()
			f62_arg0:setupElementClipCounter( 8 )
			local f62_local0 = function ( f63_arg0 )
				f62_arg0.FEButtonPanelShaderContainer:beginAnimation( 50 )
				f62_arg0.FEButtonPanelShaderContainer:setZoom( 0 )
				f62_arg0.FEButtonPanelShaderContainer:registerEventHandler( "interrupted_keyframe", f62_arg0.clipInterrupted )
				f62_arg0.FEButtonPanelShaderContainer:registerEventHandler( "transition_complete_keyframe", f62_arg0.clipFinished )
			end
			
			f62_arg0.FEButtonPanelShaderContainer:completeAnimation()
			f62_arg0.FEButtonPanelShaderContainer:setRGB( 0.5, 0.5, 0.5 )
			f62_arg0.FEButtonPanelShaderContainer:setAlpha( 1 )
			f62_arg0.FEButtonPanelShaderContainer:setZoom( -10 )
			f62_local0( f62_arg0.FEButtonPanelShaderContainer )
			local f62_local1 = function ( f64_arg0 )
				f62_arg0.FEButtonIdle:beginAnimation( 50 )
				f62_arg0.FEButtonIdle:setAlpha( 0 )
				f62_arg0.FEButtonIdle:setZoom( 10 )
				f62_arg0.FEButtonIdle:registerEventHandler( "interrupted_keyframe", f62_arg0.clipInterrupted )
				f62_arg0.FEButtonIdle:registerEventHandler( "transition_complete_keyframe", f62_arg0.clipFinished )
			end
			
			f62_arg0.FEButtonIdle:completeAnimation()
			f62_arg0.FEButtonIdle:setAlpha( 1 )
			f62_arg0.FEButtonIdle:setZoom( 0 )
			f62_local1( f62_arg0.FEButtonIdle )
			local f62_local2 = function ( f65_arg0 )
				f62_arg0.FEButtonFocus:beginAnimation( 50 )
				f62_arg0.FEButtonFocus:setAlpha( 1 )
				f62_arg0.FEButtonFocus:setZoom( 10 )
				f62_arg0.FEButtonFocus:registerEventHandler( "interrupted_keyframe", f62_arg0.clipInterrupted )
				f62_arg0.FEButtonFocus:registerEventHandler( "transition_complete_keyframe", f62_arg0.clipFinished )
			end
			
			f62_arg0.FEButtonFocus:completeAnimation()
			f62_arg0.FEButtonFocus:setLeftRight( 0, 1, 0, 0 )
			f62_arg0.FEButtonFocus:setTopBottom( 0.5, 0.5, -21, 21 )
			f62_arg0.FEButtonFocus:setAlpha( 0 )
			f62_arg0.FEButtonFocus:setZoom( 0 )
			f62_local2( f62_arg0.FEButtonFocus )
			local f62_local3 = function ( f66_arg0 )
				f62_arg0.Glow:beginAnimation( 50 )
				f62_arg0.Glow:setAlpha( 0.45 )
				f62_arg0.Glow:registerEventHandler( "interrupted_keyframe", f62_arg0.clipInterrupted )
				f62_arg0.Glow:registerEventHandler( "transition_complete_keyframe", f62_arg0.clipFinished )
			end
			
			f62_arg0.Glow:completeAnimation()
			f62_arg0.Glow:setAlpha( 0 )
			f62_local3( f62_arg0.Glow )
			local f62_local4 = function ( f67_arg0 )
				f62_arg0.btnDisplayText:beginAnimation( 50 )
				f62_arg0.btnDisplayText:setAlpha( 0 )
				f62_arg0.btnDisplayText:setZoom( 10 )
				f62_arg0.btnDisplayText:registerEventHandler( "interrupted_keyframe", f62_arg0.clipInterrupted )
				f62_arg0.btnDisplayText:registerEventHandler( "transition_complete_keyframe", f62_arg0.clipFinished )
			end
			
			f62_arg0.btnDisplayText:completeAnimation()
			f62_arg0.btnDisplayText:setAlpha( 1 )
			f62_arg0.btnDisplayText:setZoom( 0 )
			f62_local4( f62_arg0.btnDisplayText )
			local f62_local5 = function ( f68_arg0 )
				f62_arg0.btnDisplayTextStroke:beginAnimation( 50 )
				f62_arg0.btnDisplayTextStroke:setAlpha( 1 )
				f62_arg0.btnDisplayTextStroke:setZoom( 10 )
				f62_arg0.btnDisplayTextStroke:registerEventHandler( "interrupted_keyframe", f62_arg0.clipInterrupted )
				f62_arg0.btnDisplayTextStroke:registerEventHandler( "transition_complete_keyframe", f62_arg0.clipFinished )
			end
			
			f62_arg0.btnDisplayTextStroke:completeAnimation()
			f62_arg0.btnDisplayTextStroke:setAlpha( 0 )
			f62_arg0.btnDisplayTextStroke:setZoom( 0 )
			f62_local5( f62_arg0.btnDisplayTextStroke )
			local f62_local6 = function ( f69_arg0 )
				f62_arg0.Arrow:beginAnimation( 50 )
				f62_arg0.Arrow:setLeftRight( 0, 0, -30, -18 )
				f62_arg0.Arrow:setAlpha( 1 )
				f62_arg0.Arrow:registerEventHandler( "interrupted_keyframe", f62_arg0.clipInterrupted )
				f62_arg0.Arrow:registerEventHandler( "transition_complete_keyframe", f62_arg0.clipFinished )
			end
			
			f62_arg0.Arrow:completeAnimation()
			f62_arg0.Arrow:setLeftRight( 0, 0, 4, 16 )
			f62_arg0.Arrow:setTopBottom( 0, 0, 18, 30 )
			f62_arg0.Arrow:setAlpha( 0 )
			f62_local6( f62_arg0.Arrow )
			local f62_local7 = function ( f70_arg0 )
				f62_arg0.Glow2:beginAnimation( 50 )
				f62_arg0.Glow2:setAlpha( 1 )
				f62_arg0.Glow2:registerEventHandler( "interrupted_keyframe", f62_arg0.clipInterrupted )
				f62_arg0.Glow2:registerEventHandler( "transition_complete_keyframe", f62_arg0.clipFinished )
			end
			
			f62_arg0.Glow2:completeAnimation()
			f62_arg0.Glow2:setAlpha( 0 )
			f62_local7( f62_arg0.Glow2 )
		end
	},
	DisabledArabic = {
		DefaultClip = function ( f71_arg0, f71_arg1 )
			f71_arg0:__resetProperties()
			f71_arg0:setupElementClipCounter( 6 )
			f71_arg0.FEButtonPanelShaderContainer:completeAnimation()
			f71_arg0.FEButtonPanelShaderContainer:setZoom( -10 )
			f71_arg0.clipFinished( f71_arg0.FEButtonPanelShaderContainer )
			f71_arg0.FEButtonIdle:completeAnimation()
			f71_arg0.FEButtonIdle:setAlpha( 0.3 )
			f71_arg0.FEButtonIdle:setZoom( 0 )
			f71_arg0.clipFinished( f71_arg0.FEButtonIdle )
			f71_arg0.FEButtonFocus:completeAnimation()
			f71_arg0.FEButtonFocus:setLeftRight( 0, 1, 0, 0 )
			f71_arg0.FEButtonFocus:setTopBottom( 0.5, 0.5, -1, 3 )
			f71_arg0.FEButtonFocus:setZoom( 0 )
			f71_arg0.clipFinished( f71_arg0.FEButtonFocus )
			f71_arg0.btnDisplayText:completeAnimation()
			f71_arg0.btnDisplayText:setAlpha( 0.1 )
			f71_arg0.btnDisplayText:setZoom( 0 )
			f71_arg0.btnDisplayText:setAlignment( Enum.LUIAlignment[0x830CFD395E6AA0A] )
			f71_arg0.clipFinished( f71_arg0.btnDisplayText )
			f71_arg0.btnDisplayTextStroke:completeAnimation()
			f71_arg0.btnDisplayTextStroke:setAlpha( 0 )
			f71_arg0.btnDisplayTextStroke:setZoom( 0 )
			f71_arg0.btnDisplayTextStroke:setAlignment( Enum.LUIAlignment[0x830CFD395E6AA0A] )
			f71_arg0.clipFinished( f71_arg0.btnDisplayTextStroke )
			f71_arg0.Arrow:completeAnimation()
			f71_arg0.Arrow:setLeftRight( 0, 0, 4, 16 )
			f71_arg0.Arrow:setTopBottom( 0, 0, 18, 30 )
			f71_arg0.clipFinished( f71_arg0.Arrow )
		end,
		Focus = function ( f72_arg0, f72_arg1 )
			f72_arg0:__resetProperties()
			f72_arg0:setupElementClipCounter( 1 )
			f72_arg0.FEButtonPanelShaderContainer:completeAnimation()
			f72_arg0.FEButtonPanelShaderContainer:setAlpha( 1 )
			f72_arg0.clipFinished( f72_arg0.FEButtonPanelShaderContainer )
		end,
		LoseFocus = function ( f73_arg0, f73_arg1 )
			f73_arg0:__resetProperties()
			f73_arg0:setupElementClipCounter( 8 )
			local f73_local0 = function ( f74_arg0 )
				f73_arg0.FEButtonPanelShaderContainer:beginAnimation( 200 )
				f73_arg0.FEButtonPanelShaderContainer:setAlpha( 0.5 )
				f73_arg0.FEButtonPanelShaderContainer:setZoom( -10 )
				f73_arg0.FEButtonPanelShaderContainer:registerEventHandler( "interrupted_keyframe", f73_arg0.clipInterrupted )
				f73_arg0.FEButtonPanelShaderContainer:registerEventHandler( "transition_complete_keyframe", f73_arg0.clipFinished )
			end
			
			f73_arg0.FEButtonPanelShaderContainer:completeAnimation()
			f73_arg0.FEButtonPanelShaderContainer:setRGB( 0.5, 0.5, 0.5 )
			f73_arg0.FEButtonPanelShaderContainer:setAlpha( 1 )
			f73_arg0.FEButtonPanelShaderContainer:setZoom( 0 )
			f73_local0( f73_arg0.FEButtonPanelShaderContainer )
			local f73_local1 = function ( f75_arg0 )
				f73_arg0.FEButtonIdle:beginAnimation( 200 )
				f73_arg0.FEButtonIdle:setAlpha( 0.3 )
				f73_arg0.FEButtonIdle:setZoom( 0 )
				f73_arg0.FEButtonIdle:registerEventHandler( "interrupted_keyframe", f73_arg0.clipInterrupted )
				f73_arg0.FEButtonIdle:registerEventHandler( "transition_complete_keyframe", f73_arg0.clipFinished )
			end
			
			f73_arg0.FEButtonIdle:completeAnimation()
			f73_arg0.FEButtonIdle:setAlpha( 0.8 )
			f73_arg0.FEButtonIdle:setZoom( 10 )
			f73_local1( f73_arg0.FEButtonIdle )
			local f73_local2 = function ( f76_arg0 )
				f73_arg0.FEButtonFocus:beginAnimation( 200 )
				f73_arg0.FEButtonFocus:setTopBottom( 0.5, 0.5, -1, 3 )
				f73_arg0.FEButtonFocus:setZoom( 0 )
				f73_arg0.FEButtonFocus:registerEventHandler( "interrupted_keyframe", f73_arg0.clipInterrupted )
				f73_arg0.FEButtonFocus:registerEventHandler( "transition_complete_keyframe", f73_arg0.clipFinished )
			end
			
			f73_arg0.FEButtonFocus:completeAnimation()
			f73_arg0.FEButtonFocus:setLeftRight( 0, 1, 0, 0 )
			f73_arg0.FEButtonFocus:setTopBottom( 0.5, 0.5, -21, 21 )
			f73_arg0.FEButtonFocus:setAlpha( 0 )
			f73_arg0.FEButtonFocus:setZoom( 10 )
			f73_local2( f73_arg0.FEButtonFocus )
			local f73_local3 = function ( f77_arg0 )
				f73_arg0.Glow:beginAnimation( 520 )
				f73_arg0.Glow:registerEventHandler( "interrupted_keyframe", f73_arg0.clipInterrupted )
				f73_arg0.Glow:registerEventHandler( "transition_complete_keyframe", f73_arg0.clipFinished )
			end
			
			f73_arg0.Glow:completeAnimation()
			f73_arg0.Glow:setAlpha( 0 )
			f73_local3( f73_arg0.Glow )
			local f73_local4 = function ( f78_arg0 )
				f73_arg0.btnDisplayText:beginAnimation( 200 )
				f73_arg0.btnDisplayText:setAlpha( 0.1 )
				f73_arg0.btnDisplayText:setZoom( 0 )
				f73_arg0.btnDisplayText:registerEventHandler( "interrupted_keyframe", f73_arg0.clipInterrupted )
				f73_arg0.btnDisplayText:registerEventHandler( "transition_complete_keyframe", f73_arg0.clipFinished )
			end
			
			f73_arg0.btnDisplayText:completeAnimation()
			f73_arg0.btnDisplayText:setAlpha( 0 )
			f73_arg0.btnDisplayText:setZoom( 10 )
			f73_local4( f73_arg0.btnDisplayText )
			local f73_local5 = function ( f79_arg0 )
				f73_arg0.btnDisplayTextStroke:beginAnimation( 200 )
				f73_arg0.btnDisplayTextStroke:setAlpha( 0 )
				f73_arg0.btnDisplayTextStroke:setZoom( 0 )
				f73_arg0.btnDisplayTextStroke:registerEventHandler( "interrupted_keyframe", f73_arg0.clipInterrupted )
				f73_arg0.btnDisplayTextStroke:registerEventHandler( "transition_complete_keyframe", f73_arg0.clipFinished )
			end
			
			f73_arg0.btnDisplayTextStroke:completeAnimation()
			f73_arg0.btnDisplayTextStroke:setAlpha( 0.7 )
			f73_arg0.btnDisplayTextStroke:setZoom( 10 )
			f73_local5( f73_arg0.btnDisplayTextStroke )
			local f73_local6 = function ( f80_arg0 )
				f73_arg0.Arrow:beginAnimation( 200 )
				f73_arg0.Arrow:setLeftRight( 0, 0, 4, 16 )
				f73_arg0.Arrow:registerEventHandler( "interrupted_keyframe", f73_arg0.clipInterrupted )
				f73_arg0.Arrow:registerEventHandler( "transition_complete_keyframe", f73_arg0.clipFinished )
			end
			
			f73_arg0.Arrow:completeAnimation()
			f73_arg0.Arrow:setLeftRight( 0, 0, -30, -18 )
			f73_arg0.Arrow:setTopBottom( 0, 0, 18, 30 )
			f73_arg0.Arrow:setAlpha( 0 )
			f73_local6( f73_arg0.Arrow )
			local f73_local7 = function ( f81_arg0 )
				f73_arg0.Glow2:beginAnimation( 300 )
				f73_arg0.Glow2:registerEventHandler( "interrupted_keyframe", f73_arg0.clipInterrupted )
				f73_arg0.Glow2:registerEventHandler( "transition_complete_keyframe", f73_arg0.clipFinished )
			end
			
			f73_arg0.Glow2:completeAnimation()
			f73_arg0.Glow2:setAlpha( 0 )
			f73_local7( f73_arg0.Glow2 )
		end,
		GainFocus = function ( f82_arg0, f82_arg1 )
			f82_arg0:__resetProperties()
			f82_arg0:setupElementClipCounter( 8 )
			local f82_local0 = function ( f83_arg0 )
				f82_arg0.FEButtonPanelShaderContainer:beginAnimation( 50 )
				f82_arg0.FEButtonPanelShaderContainer:setAlpha( 1 )
				f82_arg0.FEButtonPanelShaderContainer:setZoom( 0 )
				f82_arg0.FEButtonPanelShaderContainer:registerEventHandler( "interrupted_keyframe", f82_arg0.clipInterrupted )
				f82_arg0.FEButtonPanelShaderContainer:registerEventHandler( "transition_complete_keyframe", f82_arg0.clipFinished )
			end
			
			f82_arg0.FEButtonPanelShaderContainer:completeAnimation()
			f82_arg0.FEButtonPanelShaderContainer:setRGB( 0.5, 0.5, 0.5 )
			f82_arg0.FEButtonPanelShaderContainer:setAlpha( 0.5 )
			f82_arg0.FEButtonPanelShaderContainer:setZoom( -10 )
			f82_local0( f82_arg0.FEButtonPanelShaderContainer )
			local f82_local1 = function ( f84_arg0 )
				f82_arg0.FEButtonIdle:beginAnimation( 50 )
				f82_arg0.FEButtonIdle:setAlpha( 0.8 )
				f82_arg0.FEButtonIdle:setZoom( 10 )
				f82_arg0.FEButtonIdle:registerEventHandler( "interrupted_keyframe", f82_arg0.clipInterrupted )
				f82_arg0.FEButtonIdle:registerEventHandler( "transition_complete_keyframe", f82_arg0.clipFinished )
			end
			
			f82_arg0.FEButtonIdle:completeAnimation()
			f82_arg0.FEButtonIdle:setAlpha( 0.3 )
			f82_arg0.FEButtonIdle:setZoom( 0 )
			f82_local1( f82_arg0.FEButtonIdle )
			local f82_local2 = function ( f85_arg0 )
				f82_arg0.FEButtonFocus:beginAnimation( 50 )
				f82_arg0.FEButtonFocus:setZoom( 10 )
				f82_arg0.FEButtonFocus:registerEventHandler( "interrupted_keyframe", f82_arg0.clipInterrupted )
				f82_arg0.FEButtonFocus:registerEventHandler( "transition_complete_keyframe", f82_arg0.clipFinished )
			end
			
			f82_arg0.FEButtonFocus:completeAnimation()
			f82_arg0.FEButtonFocus:setLeftRight( 0, 1, 0, 0 )
			f82_arg0.FEButtonFocus:setTopBottom( 0.5, 0.5, -21, 21 )
			f82_arg0.FEButtonFocus:setAlpha( 0 )
			f82_arg0.FEButtonFocus:setZoom( 0 )
			f82_local2( f82_arg0.FEButtonFocus )
			local f82_local3 = function ( f86_arg0 )
				f82_arg0.Glow:beginAnimation( 50 )
				f82_arg0.Glow:registerEventHandler( "interrupted_keyframe", f82_arg0.clipInterrupted )
				f82_arg0.Glow:registerEventHandler( "transition_complete_keyframe", f82_arg0.clipFinished )
			end
			
			f82_arg0.Glow:completeAnimation()
			f82_arg0.Glow:setAlpha( 0 )
			f82_local3( f82_arg0.Glow )
			local f82_local4 = function ( f87_arg0 )
				f82_arg0.btnDisplayText:beginAnimation( 50 )
				f82_arg0.btnDisplayText:setAlpha( 0 )
				f82_arg0.btnDisplayText:setZoom( 10 )
				f82_arg0.btnDisplayText:registerEventHandler( "interrupted_keyframe", f82_arg0.clipInterrupted )
				f82_arg0.btnDisplayText:registerEventHandler( "transition_complete_keyframe", f82_arg0.clipFinished )
			end
			
			f82_arg0.btnDisplayText:completeAnimation()
			f82_arg0.btnDisplayText:setAlpha( 0.1 )
			f82_arg0.btnDisplayText:setZoom( 0 )
			f82_local4( f82_arg0.btnDisplayText )
			local f82_local5 = function ( f88_arg0 )
				f82_arg0.btnDisplayTextStroke:beginAnimation( 50 )
				f82_arg0.btnDisplayTextStroke:setAlpha( 0.7 )
				f82_arg0.btnDisplayTextStroke:setZoom( 10 )
				f82_arg0.btnDisplayTextStroke:registerEventHandler( "interrupted_keyframe", f82_arg0.clipInterrupted )
				f82_arg0.btnDisplayTextStroke:registerEventHandler( "transition_complete_keyframe", f82_arg0.clipFinished )
			end
			
			f82_arg0.btnDisplayTextStroke:completeAnimation()
			f82_arg0.btnDisplayTextStroke:setAlpha( 0 )
			f82_arg0.btnDisplayTextStroke:setZoom( 0 )
			f82_local5( f82_arg0.btnDisplayTextStroke )
			local f82_local6 = function ( f89_arg0 )
				f82_arg0.Arrow:beginAnimation( 50 )
				f82_arg0.Arrow:setLeftRight( 0, 0, -30, -18 )
				f82_arg0.Arrow:registerEventHandler( "interrupted_keyframe", f82_arg0.clipInterrupted )
				f82_arg0.Arrow:registerEventHandler( "transition_complete_keyframe", f82_arg0.clipFinished )
			end
			
			f82_arg0.Arrow:completeAnimation()
			f82_arg0.Arrow:setLeftRight( 0, 0, 4, 16 )
			f82_arg0.Arrow:setTopBottom( 0, 0, 18, 30 )
			f82_arg0.Arrow:setAlpha( 0 )
			f82_local6( f82_arg0.Arrow )
			local f82_local7 = function ( f90_arg0 )
				f82_arg0.Glow2:beginAnimation( 50 )
				f82_arg0.Glow2:registerEventHandler( "interrupted_keyframe", f82_arg0.clipInterrupted )
				f82_arg0.Glow2:registerEventHandler( "transition_complete_keyframe", f82_arg0.clipFinished )
			end
			
			f82_arg0.Glow2:completeAnimation()
			f82_arg0.Glow2:setAlpha( 0 )
			f82_local7( f82_arg0.Glow2 )
		end
	}
}
CoD.FileshareOptionButton.__onClose = function ( f91_arg0 )
	f91_arg0.FEButtonPanelShaderContainer:close()
	f91_arg0.FEButtonIdle:close()
	f91_arg0.FEButtonFocus:close()
	f91_arg0.btnDisplayText:close()
	f91_arg0.btnDisplayTextStroke:close()
	f91_arg0.FEHelpItemsLabel0:close()
	f91_arg0.Image0:close()
end

