require( "ui/uieditor/widgets/common/commonfocusbrackets" )
require( "ui/uieditor/widgets/zmfrontend/laboratory/zm_laboratorydescriptiondivider" )

CoD.ZMButtonDifficultyInternal = InheritFrom( LUI.UIElement )
CoD.ZMButtonDifficultyInternal.__defaultWidth = 280
CoD.ZMButtonDifficultyInternal.__defaultHeight = 52
CoD.ZMButtonDifficultyInternal.new = function ( f1_arg0, f1_arg1, f1_arg2, f1_arg3, f1_arg4, f1_arg5, f1_arg6, f1_arg7, f1_arg8, f1_arg9 )
	local self = LUI.UIElement.new( f1_arg2, f1_arg3, f1_arg4, f1_arg5, f1_arg6, f1_arg7, f1_arg8, f1_arg9 )
	self:setClass( CoD.ZMButtonDifficultyInternal )
	self.id = "ZMButtonDifficultyInternal"
	self.soundSet = "FrontendMain"
	f1_arg0:addElementToPendingUpdateStateList( self )
	local ButtonBGPC = nil
	
	ButtonBGPC = LUI.UIImage.new( 0, 1, 0, 0, 0, 1, 0, 0 )
	ButtonBGPC:setRGB( 0.2, 0.2, 0.2 )
	ButtonBGPC:setAlpha( 0 )
	self:addElement( ButtonBGPC )
	self.ButtonBGPC = ButtonBGPC
	
	local BGGray = LUI.UIImage.new( 0, 1, 0, 0, 0, 1, 0, 0 )
	BGGray:setRGB( 0.2, 0.2, 0.2 )
	BGGray:setAlpha( 0.85 )
	self:addElement( BGGray )
	self.BGGray = BGGray
	
	local StoneTiledBacking = LUI.UIImage.new( 0, 1, 0, 0, 0, 1, 0, 0 )
	StoneTiledBacking:setAlpha( 0.8 )
	StoneTiledBacking:setImage( RegisterImage( 0x33757173B476ACD ) )
	StoneTiledBacking:setMaterial( LUI.UIImage.GetCachedMaterial( 0x6CBE95C250C6D15 ) )
	StoneTiledBacking:setShaderVector( 0, 0, 0, 0, 0 )
	StoneTiledBacking:setupNineSliceShader( 196, 88 )
	self:addElement( StoneTiledBacking )
	self.StoneTiledBacking = StoneTiledBacking
	
	local NoiseTiledBacking = LUI.UIImage.new( 0, 1, 0, 0, 0, 1, 0, 0 )
	NoiseTiledBacking:setAlpha( 0.3 )
	NoiseTiledBacking:setImage( RegisterImage( 0x34839E8065B1E53 ) )
	NoiseTiledBacking:setMaterial( LUI.UIImage.GetCachedMaterial( 0x6CBE95C250C6D15 ) )
	NoiseTiledBacking:setShaderVector( 0, 0, 0, 0, 0 )
	NoiseTiledBacking:setupNineSliceShader( 196, 88 )
	self:addElement( NoiseTiledBacking )
	self.NoiseTiledBacking = NoiseTiledBacking
	
	local FocusGlow = LUI.UIImage.new( 0, 1, -49, 49, 0, 1, -25, 25 )
	FocusGlow:setRGB( 0.89, 0.12, 0.12 )
	FocusGlow:setAlpha( 0 )
	FocusGlow:setImage( RegisterImage( 0xF78E8C6CBDEB253 ) )
	FocusGlow:setMaterial( LUI.UIImage.GetCachedMaterial( 0xDAB59B2CAE01851 ) )
	FocusGlow:setShaderVector( 0, 0, 0, 0.25, 0.25 )
	FocusGlow:setShaderVector( 1, 1.2, 0, 0, 0 )
	FocusGlow:setupNineSliceShader( 100, 100 )
	self:addElement( FocusGlow )
	self.FocusGlow = FocusGlow
	
	local FrameBorder = LUI.UIImage.new( 0, 1, -1, 1, 0, 1, -1, 1 )
	FrameBorder:setAlpha( 0.15 )
	FrameBorder:setImage( RegisterImage( 0x185E11D74ECA3D7 ) )
	FrameBorder:setMaterial( LUI.UIImage.GetCachedMaterial( 0xFD777557404A7B3 ) )
	FrameBorder:setShaderVector( 0, 0, 0, 0, 0 )
	FrameBorder:setupNineSliceShader( 12, 12 )
	self:addElement( FrameBorder )
	self.FrameBorder = FrameBorder
	
	local BGGlow = LUI.UIImage.new( 0, 1, 0, 0, 0, 1, 0, 0 )
	BGGlow:setRGB( 0.89, 0.12, 0.12 )
	BGGlow:setAlpha( 0 )
	BGGlow:setZRot( 180 )
	BGGlow:setImage( RegisterImage( 0xC270E906CDA1B2E ) )
	BGGlow:setMaterial( LUI.UIImage.GetCachedMaterial( 0x1CC85D0A86303B0 ) )
	BGGlow:setShaderVector( 0, 1.25, 0, 0, 0 )
	self:addElement( BGGlow )
	self.BGGlow = BGGlow
	
	local MetalFrame = LUI.UIImage.new( 0, 1, -2, 2, 0, 1, -2, 2 )
	MetalFrame:setImage( RegisterImage( 0xAED94B38E8B3347 ) )
	MetalFrame:setMaterial( LUI.UIImage.GetCachedMaterial( 0xFD777557404A7B3 ) )
	MetalFrame:setShaderVector( 0, 0, 0, 0, 0 )
	MetalFrame:setupNineSliceShader( 14, 14 )
	self:addElement( MetalFrame )
	self.MetalFrame = MetalFrame
	
	local TopOrnament = CoD.zm_LaboratoryDescriptionDivider.new( f1_arg0, f1_arg1, 0, 1, -0.5, -0.5, 0, 0, -12, 14 )
	TopOrnament.R:setScale( 0.6, 0.6 )
	TopOrnament.L:setScale( 0.6, 0.6 )
	self:addElement( TopOrnament )
	self.TopOrnament = TopOrnament
	
	local FocusBorder = LUI.UIImage.new( 0, 1, -4, 4, 0, 1, -3, 3 )
	FocusBorder:setRGB( 1, 0.7, 0.7 )
	FocusBorder:setAlpha( 0 )
	FocusBorder:setImage( RegisterImage( 0xCB07CCC28498CB2 ) )
	FocusBorder:setMaterial( LUI.UIImage.GetCachedMaterial( 0xFD777557404A7B3 ) )
	FocusBorder:setShaderVector( 0, 0, 0, 0, 0 )
	FocusBorder:setupNineSliceShader( 10, 10 )
	self:addElement( FocusBorder )
	self.FocusBorder = FocusBorder
	
	local FocusBrackets = CoD.CommonFocusBrackets.new( f1_arg0, f1_arg1, 0, 1, -20, 20, 0, 1, -20, 20 )
	FocusBrackets:setRGB( 1, 0.59, 0.59 )
	FocusBrackets:setAlpha( 0 )
	self:addElement( FocusBrackets )
	self.FocusBrackets = FocusBrackets
	
	local Image = LUI.UIImage.new( 0, 1, 0, 0, 0, 0.94, 12, 12 )
	Image:setRGB( 0.89, 0.94, 0.99 )
	Image:setAlpha( 0 )
	self:addElement( Image )
	self.Image = Image
	
	local ImageNotFocus = LUI.UIImage.new( 0, 1, 0, 0, 0, 1, 12, 0 )
	ImageNotFocus:setAlpha( 0 )
	ImageNotFocus:setMaterial( LUI.UIImage.GetCachedMaterial( 0x67D1E3A3D2D1BF ) )
	ImageNotFocus:setShaderVector( 0, 1, 0, 0, 0 )
	ImageNotFocus:linkToElementModel( self, "iconBackground", true, function ( model )
		local f2_local0 = model:get()
		if f2_local0 ~= nil then
			ImageNotFocus:setImage( RegisterImage( f2_local0 ) )
		end
	end )
	self:addElement( ImageNotFocus )
	self.ImageNotFocus = ImageNotFocus
	
	local ImageFocus = LUI.UIImage.new( 0, 1, 0, 0, 0, 1, 12, 0 )
	ImageFocus:setAlpha( 0 )
	self:addElement( ImageFocus )
	self.ImageFocus = ImageFocus
	
	local TextBacking = LUI.UIImage.new( 0, 1, 0, 0, 1, 1, -33, 0 )
	TextBacking:setRGB( 0.07, 0.07, 0.07 )
	TextBacking:setAlpha( 0 )
	self:addElement( TextBacking )
	self.TextBacking = TextBacking
	
	local lockImage = LUI.UIImage.new( 1, 1, -44, 6, 0, 0, -4, 46 )
	lockImage:setAlpha( 0 )
	lockImage:setScale( 0.6, 0.6 )
	lockImage:setImage( RegisterImage( 0xE1E7C490B2BA4FB ) )
	self:addElement( lockImage )
	self.lockImage = lockImage
	
	local LeaderActivityText = LUI.UIText.new( 0, 0, 9, 278, 1, 1, -46.5, -26.5 )
	LeaderActivityText:setRGB( 0.58, 0.58, 0.58 )
	LeaderActivityText:setText( Engine[0xF9F1239CFD921FE]( 0x93E719493E9E18F ) )
	LeaderActivityText:setTTF( "ttmussels_regular" )
	LeaderActivityText:setLetterSpacing( 3 )
	LeaderActivityText:setAlignment( Enum.LUIAlignment[0x58C8A85F2048829] )
	LeaderActivityText:setAlignment( Enum.LUIAlignment[0xF41D595A2B0EDF3] )
	LeaderActivityText:setBackingType( 2 )
	LeaderActivityText:setBackingColor( 0.08, 0.08, 0.08 )
	LeaderActivityText:setBackingAlpha( 0.8 )
	LeaderActivityText:setBackingXPadding( 3 )
	self:addElement( LeaderActivityText )
	self.LeaderActivityText = LeaderActivityText
	
	local Header = LUI.UIText.new( 0.01, 0.97, 7, 7, 1, 1, -26.5, -4.5 )
	Header:setRGB( 0.58, 0.58, 0.58 )
	Header:setText( LocalizeToUpperString( 0xA43B10D9DA121A ) )
	Header:setTTF( "ttmussels_regular" )
	Header:setMaterial( LUI.UIImage.GetCachedMaterial( 0x71E049B161CD00A ) )
	Header:setLetterSpacing( 3 )
	Header:setAlignment( Enum.LUIAlignment[0x58C8A85F2048829] )
	Header:setAlignment( Enum.LUIAlignment[0xF41D595A2B0EDF3] )
	Header:setBackingType( 2 )
	Header:setBackingColor( 0.08, 0.08, 0.08 )
	Header:setBackingAlpha( 0.8 )
	Header:setBackingXPadding( 3 )
	self:addElement( Header )
	self.Header = Header
	
	local MiddleText = LUI.UIText.new( 0.02, 0.98, 0, 0, 0.5, 0.5, -11, 11 )
	MiddleText:setRGB( 0.58, 0.58, 0.58 )
	MiddleText:setText( LocalizeToUpperString( 0xA43B10D9DA121A ) )
	MiddleText:setTTF( "ttmussels_regular" )
	MiddleText:setLetterSpacing( 3 )
	MiddleText:setAlignment( Enum.LUIAlignment[0xFEEB12BCB0D7041] )
	MiddleText:setAlignment( Enum.LUIAlignment[0x6ED4298C93DC5ED] )
	MiddleText:setBackingType( 2 )
	MiddleText:setBackingColor( 0.08, 0.08, 0.08 )
	MiddleText:setBackingAlpha( 0.8 )
	MiddleText:setBackingXPadding( 3 )
	self:addElement( MiddleText )
	self.MiddleText = MiddleText
	
	local circle = LUI.UIImage.new( 0.5, 0.5, -152, -92, 0.55, 0.55, -14, 46 )
	circle:setRGB( 0.19, 0.19, 0.19 )
	circle:setAlpha( 0 )
	circle:setZRot( 180 )
	circle:setScale( 1.05, 1.05 )
	circle:setMaterial( LUI.UIImage.GetCachedMaterial( 0x15B163CA03FCE8B ) )
	circle:setShaderVector( 0, 4.66, 0, 0, 0 )
	circle:setShaderVector( 1, 80, 80, 0, 0 )
	circle:setShaderVector( 2, 0, 0, 0, 0 )
	self:addElement( circle )
	self.circle = circle
	
	local timer = LUI.UIText.new( 0.5, 0.5, -160, -80, 0.55, 0.55, -10, 48 )
	timer:setRGB( 0, 0, 0 )
	timer:setAlpha( 0 )
	timer:setTTF( "ttmussels_demibold" )
	timer:setLetterSpacing( -6.3 )
	timer:setAlignment( Enum.LUIAlignment[0xFEEB12BCB0D7041] )
	timer:setAlignment( Enum.LUIAlignment[0xF41D595A2B0EDF3] )
	timer:subscribeToGlobalModel( f1_arg1, "LobbyRoot", "lobbyTimeRemaining", function ( model )
		local f3_local0 = model:get()
		if f3_local0 ~= nil then
			timer:setText( f3_local0 )
		end
	end )
	self:addElement( timer )
	self.timer = timer
	
	local CountdownText = LUI.UIText.new( 0.5, 0.5, -75, -20, 0.55, 0.55, 0, 33 )
	CountdownText:setRGB( 0.05, 0.05, 0.05 )
	CountdownText:setAlpha( 0 )
	CountdownText:setTTF( "ttmussels_regular" )
	CountdownText:setAlignment( Enum.LUIAlignment[0x58C8A85F2048829] )
	CountdownText:subscribeToGlobalModel( f1_arg1, "LobbyRoot", "lobbyStatus", function ( model )
		local f4_local0 = model:get()
		if f4_local0 ~= nil then
			CountdownText:setText( ToUpper( f4_local0 ) )
		end
	end )
	self:addElement( CountdownText )
	self.CountdownText = CountdownText
	
	LUI.OverrideFunction_CallOriginalSecond( self, "close", self.__onClose )
	
	if PostLoadFunc then
		PostLoadFunc( self, f1_arg1, f1_arg0 )
	end
	
	return self
end

CoD.ZMButtonDifficultyInternal.__resetProperties = function ( f5_arg0 )
	f5_arg0.Header:completeAnimation()
	f5_arg0.lockImage:completeAnimation()
	f5_arg0.MiddleText:completeAnimation()
	f5_arg0.Image:completeAnimation()
	f5_arg0.FocusBorder:completeAnimation()
	f5_arg0.FocusBrackets:completeAnimation()
	f5_arg0.FocusGlow:completeAnimation()
	f5_arg0.BGGlow:completeAnimation()
	f5_arg0.LeaderActivityText:completeAnimation()
	f5_arg0.ImageNotFocus:completeAnimation()
	f5_arg0.BGGray:completeAnimation()
	f5_arg0.FrameBorder:completeAnimation()
	f5_arg0.Header:setRGB( 0.58, 0.58, 0.58 )
	f5_arg0.Header:setAlpha( 1 )
	f5_arg0.lockImage:setAlpha( 0 )
	f5_arg0.lockImage:setScale( 0.6, 0.6 )
	f5_arg0.MiddleText:setRGB( 0.58, 0.58, 0.58 )
	f5_arg0.MiddleText:setAlpha( 1 )
	f5_arg0.Image:setAlpha( 0 )
	f5_arg0.FocusBorder:setAlpha( 0 )
	f5_arg0.FocusBrackets:setLeftRight( 0, 1, -20, 20 )
	f5_arg0.FocusBrackets:setTopBottom( 0, 1, -20, 20 )
	f5_arg0.FocusBrackets:setAlpha( 0 )
	f5_arg0.FocusGlow:setAlpha( 0 )
	f5_arg0.BGGlow:setAlpha( 0 )
	f5_arg0.LeaderActivityText:setRGB( 0.58, 0.58, 0.58 )
	f5_arg0.LeaderActivityText:setAlpha( 1 )
	f5_arg0.ImageNotFocus:setRGB( 1, 1, 1 )
	f5_arg0.ImageNotFocus:setMaterial( LUI.UIImage.GetCachedMaterial( 0x67D1E3A3D2D1BF ) )
	f5_arg0.ImageNotFocus:setShaderVector( 0, 1, 0, 0, 0 )
	f5_arg0.BGGray:setRGB( 0.2, 0.2, 0.2 )
	f5_arg0.FrameBorder:setAlpha( 0.15 )
end

CoD.ZMButtonDifficultyInternal.__clipsPerState = {
	DefaultState = {
		DefaultClip = function ( f6_arg0, f6_arg1 )
			f6_arg0:__resetProperties()
			f6_arg0:setupElementClipCounter( 1 )
			f6_arg0.Header:completeAnimation()
			f6_arg0.Header:setAlpha( 1 )
			f6_arg0.clipFinished( f6_arg0.Header )
		end,
		Focus = function ( f7_arg0, f7_arg1 )
			f7_arg0:__resetProperties()
			f7_arg0:setupElementClipCounter( 9 )
			f7_arg0.FocusGlow:completeAnimation()
			f7_arg0.FocusGlow:setAlpha( 1 )
			f7_arg0.clipFinished( f7_arg0.FocusGlow )
			f7_arg0.BGGlow:completeAnimation()
			f7_arg0.BGGlow:setAlpha( 0.66 )
			f7_arg0.clipFinished( f7_arg0.BGGlow )
			f7_arg0.FocusBorder:completeAnimation()
			f7_arg0.FocusBorder:setAlpha( 1 )
			f7_arg0.clipFinished( f7_arg0.FocusBorder )
			f7_arg0.FocusBrackets:completeAnimation()
			f7_arg0.FocusBrackets:setLeftRight( 0, 1, -10, 10 )
			f7_arg0.FocusBrackets:setTopBottom( 0, 1, -10, 10 )
			f7_arg0.FocusBrackets:setAlpha( 1 )
			f7_arg0.clipFinished( f7_arg0.FocusBrackets )
			f7_arg0.Image:completeAnimation()
			f7_arg0.Image:setAlpha( 0 )
			f7_arg0.clipFinished( f7_arg0.Image )
			f7_arg0.lockImage:completeAnimation()
			f7_arg0.lockImage:setScale( 1.2, 1.2 )
			f7_arg0.clipFinished( f7_arg0.lockImage )
			f7_arg0.LeaderActivityText:completeAnimation()
			f7_arg0.LeaderActivityText:setRGB( ColorSet.T8__BIEGE.r, ColorSet.T8__BIEGE.g, ColorSet.T8__BIEGE.b )
			f7_arg0.clipFinished( f7_arg0.LeaderActivityText )
			f7_arg0.Header:completeAnimation()
			f7_arg0.Header:setRGB( ColorSet.T8__BIEGE.r, ColorSet.T8__BIEGE.g, ColorSet.T8__BIEGE.b )
			f7_arg0.clipFinished( f7_arg0.Header )
			f7_arg0.MiddleText:completeAnimation()
			f7_arg0.MiddleText:setRGB( ColorSet.T8__BIEGE.r, ColorSet.T8__BIEGE.g, ColorSet.T8__BIEGE.b )
			f7_arg0.clipFinished( f7_arg0.MiddleText )
		end,
		GainFocus = function ( f8_arg0, f8_arg1 )
			f8_arg0:__resetProperties()
			f8_arg0:setupElementClipCounter( 9 )
			local f8_local0 = function ( f9_arg0 )
				f8_arg0.FocusGlow:beginAnimation( 200 )
				f8_arg0.FocusGlow:setAlpha( 1 )
				f8_arg0.FocusGlow:registerEventHandler( "interrupted_keyframe", f8_arg0.clipInterrupted )
				f8_arg0.FocusGlow:registerEventHandler( "transition_complete_keyframe", f8_arg0.clipFinished )
			end
			
			f8_arg0.FocusGlow:completeAnimation()
			f8_arg0.FocusGlow:setAlpha( 0 )
			f8_local0( f8_arg0.FocusGlow )
			local f8_local1 = function ( f10_arg0 )
				f8_arg0.BGGlow:beginAnimation( 200 )
				f8_arg0.BGGlow:setAlpha( 0.66 )
				f8_arg0.BGGlow:registerEventHandler( "interrupted_keyframe", f8_arg0.clipInterrupted )
				f8_arg0.BGGlow:registerEventHandler( "transition_complete_keyframe", f8_arg0.clipFinished )
			end
			
			f8_arg0.BGGlow:completeAnimation()
			f8_arg0.BGGlow:setAlpha( 0 )
			f8_local1( f8_arg0.BGGlow )
			local f8_local2 = function ( f11_arg0 )
				f8_arg0.FocusBorder:beginAnimation( 200 )
				f8_arg0.FocusBorder:setAlpha( 1 )
				f8_arg0.FocusBorder:registerEventHandler( "interrupted_keyframe", f8_arg0.clipInterrupted )
				f8_arg0.FocusBorder:registerEventHandler( "transition_complete_keyframe", f8_arg0.clipFinished )
			end
			
			f8_arg0.FocusBorder:completeAnimation()
			f8_arg0.FocusBorder:setAlpha( 0 )
			f8_local2( f8_arg0.FocusBorder )
			local f8_local3 = function ( f12_arg0 )
				local f12_local0 = function ( f13_arg0 )
					f13_arg0:beginAnimation( 50, Enum[0xF50FFF429AB1890][0x6F6186B702830BC] )
					f13_arg0:setLeftRight( 0, 1, -10, 10 )
					f13_arg0:setTopBottom( 0, 1, -10, 10 )
					f13_arg0:setAlpha( 1 )
					f13_arg0:registerEventHandler( "transition_complete_keyframe", f8_arg0.clipFinished )
				end
				
				f8_arg0.FocusBrackets:beginAnimation( 100 )
				f8_arg0.FocusBrackets:setLeftRight( 0, 1, -8, 8 )
				f8_arg0.FocusBrackets:setTopBottom( 0, 1, -8, 8 )
				f8_arg0.FocusBrackets:setAlpha( 0.75 )
				f8_arg0.FocusBrackets:registerEventHandler( "interrupted_keyframe", f8_arg0.clipInterrupted )
				f8_arg0.FocusBrackets:registerEventHandler( "transition_complete_keyframe", f12_local0 )
			end
			
			f8_arg0.FocusBrackets:completeAnimation()
			f8_arg0.FocusBrackets:setLeftRight( 0, 1, -20, 20 )
			f8_arg0.FocusBrackets:setTopBottom( 0, 1, -20, 20 )
			f8_arg0.FocusBrackets:setAlpha( 0 )
			f8_local3( f8_arg0.FocusBrackets )
			f8_arg0.Image:completeAnimation()
			f8_arg0.Image:setAlpha( 0 )
			f8_arg0.clipFinished( f8_arg0.Image )
			local f8_local4 = function ( f14_arg0 )
				f8_arg0.lockImage:beginAnimation( 200 )
				f8_arg0.lockImage:setScale( 1.2, 1.2 )
				f8_arg0.lockImage:registerEventHandler( "interrupted_keyframe", f8_arg0.clipInterrupted )
				f8_arg0.lockImage:registerEventHandler( "transition_complete_keyframe", f8_arg0.clipFinished )
			end
			
			f8_arg0.lockImage:completeAnimation()
			f8_arg0.lockImage:setScale( 0.6, 0.6 )
			f8_local4( f8_arg0.lockImage )
			local f8_local5 = function ( f15_arg0 )
				f8_arg0.LeaderActivityText:beginAnimation( 200 )
				f8_arg0.LeaderActivityText:setRGB( ColorSet.T8__BIEGE.r, ColorSet.T8__BIEGE.g, ColorSet.T8__BIEGE.b )
				f8_arg0.LeaderActivityText:registerEventHandler( "interrupted_keyframe", f8_arg0.clipInterrupted )
				f8_arg0.LeaderActivityText:registerEventHandler( "transition_complete_keyframe", f8_arg0.clipFinished )
			end
			
			f8_arg0.LeaderActivityText:completeAnimation()
			f8_arg0.LeaderActivityText:setRGB( 0.58, 0.58, 0.58 )
			f8_local5( f8_arg0.LeaderActivityText )
			local f8_local6 = function ( f16_arg0 )
				f8_arg0.Header:beginAnimation( 200 )
				f8_arg0.Header:setRGB( ColorSet.T8__BIEGE.r, ColorSet.T8__BIEGE.g, ColorSet.T8__BIEGE.b )
				f8_arg0.Header:registerEventHandler( "interrupted_keyframe", f8_arg0.clipInterrupted )
				f8_arg0.Header:registerEventHandler( "transition_complete_keyframe", f8_arg0.clipFinished )
			end
			
			f8_arg0.Header:completeAnimation()
			f8_arg0.Header:setRGB( 0.58, 0.58, 0.58 )
			f8_arg0.Header:setAlpha( 1 )
			f8_local6( f8_arg0.Header )
			local f8_local7 = function ( f17_arg0 )
				f8_arg0.MiddleText:beginAnimation( 200 )
				f8_arg0.MiddleText:setRGB( ColorSet.T8__BIEGE.r, ColorSet.T8__BIEGE.g, ColorSet.T8__BIEGE.b )
				f8_arg0.MiddleText:registerEventHandler( "interrupted_keyframe", f8_arg0.clipInterrupted )
				f8_arg0.MiddleText:registerEventHandler( "transition_complete_keyframe", f8_arg0.clipFinished )
			end
			
			f8_arg0.MiddleText:completeAnimation()
			f8_arg0.MiddleText:setRGB( 0.58, 0.58, 0.58 )
			f8_local7( f8_arg0.MiddleText )
		end,
		LoseFocus = function ( f18_arg0, f18_arg1 )
			f18_arg0:__resetProperties()
			f18_arg0:setupElementClipCounter( 9 )
			local f18_local0 = function ( f19_arg0 )
				f18_arg0.FocusGlow:beginAnimation( 200 )
				f18_arg0.FocusGlow:setAlpha( 0 )
				f18_arg0.FocusGlow:registerEventHandler( "interrupted_keyframe", f18_arg0.clipInterrupted )
				f18_arg0.FocusGlow:registerEventHandler( "transition_complete_keyframe", f18_arg0.clipFinished )
			end
			
			f18_arg0.FocusGlow:completeAnimation()
			f18_arg0.FocusGlow:setAlpha( 1 )
			f18_local0( f18_arg0.FocusGlow )
			local f18_local1 = function ( f20_arg0 )
				f18_arg0.BGGlow:beginAnimation( 200 )
				f18_arg0.BGGlow:setAlpha( 0 )
				f18_arg0.BGGlow:registerEventHandler( "interrupted_keyframe", f18_arg0.clipInterrupted )
				f18_arg0.BGGlow:registerEventHandler( "transition_complete_keyframe", f18_arg0.clipFinished )
			end
			
			f18_arg0.BGGlow:completeAnimation()
			f18_arg0.BGGlow:setAlpha( 0.66 )
			f18_local1( f18_arg0.BGGlow )
			local f18_local2 = function ( f21_arg0 )
				f18_arg0.FocusBorder:beginAnimation( 200 )
				f18_arg0.FocusBorder:setAlpha( 0 )
				f18_arg0.FocusBorder:registerEventHandler( "interrupted_keyframe", f18_arg0.clipInterrupted )
				f18_arg0.FocusBorder:registerEventHandler( "transition_complete_keyframe", f18_arg0.clipFinished )
			end
			
			f18_arg0.FocusBorder:completeAnimation()
			f18_arg0.FocusBorder:setAlpha( 1 )
			f18_local2( f18_arg0.FocusBorder )
			local f18_local3 = function ( f22_arg0 )
				f18_arg0.FocusBrackets:beginAnimation( 60 )
				f18_arg0.FocusBrackets:setAlpha( 0 )
				f18_arg0.FocusBrackets:registerEventHandler( "interrupted_keyframe", f18_arg0.clipInterrupted )
				f18_arg0.FocusBrackets:registerEventHandler( "transition_complete_keyframe", f18_arg0.clipFinished )
			end
			
			f18_arg0.FocusBrackets:completeAnimation()
			f18_arg0.FocusBrackets:setLeftRight( 0, 1, -10, 10 )
			f18_arg0.FocusBrackets:setTopBottom( 0, 1, -10, 10 )
			f18_arg0.FocusBrackets:setAlpha( 1 )
			f18_local3( f18_arg0.FocusBrackets )
			f18_arg0.Image:completeAnimation()
			f18_arg0.Image:setAlpha( 0 )
			f18_arg0.clipFinished( f18_arg0.Image )
			local f18_local4 = function ( f23_arg0 )
				f18_arg0.lockImage:beginAnimation( 200 )
				f18_arg0.lockImage:setScale( 0.6, 0.6 )
				f18_arg0.lockImage:registerEventHandler( "interrupted_keyframe", f18_arg0.clipInterrupted )
				f18_arg0.lockImage:registerEventHandler( "transition_complete_keyframe", f18_arg0.clipFinished )
			end
			
			f18_arg0.lockImage:completeAnimation()
			f18_arg0.lockImage:setScale( 1.2, 1.2 )
			f18_local4( f18_arg0.lockImage )
			local f18_local5 = function ( f24_arg0 )
				f18_arg0.LeaderActivityText:beginAnimation( 200 )
				f18_arg0.LeaderActivityText:setRGB( 0.58, 0.58, 0.58 )
				f18_arg0.LeaderActivityText:registerEventHandler( "interrupted_keyframe", f18_arg0.clipInterrupted )
				f18_arg0.LeaderActivityText:registerEventHandler( "transition_complete_keyframe", f18_arg0.clipFinished )
			end
			
			f18_arg0.LeaderActivityText:completeAnimation()
			f18_arg0.LeaderActivityText:setRGB( ColorSet.T8__BIEGE.r, ColorSet.T8__BIEGE.g, ColorSet.T8__BIEGE.b )
			f18_local5( f18_arg0.LeaderActivityText )
			local f18_local6 = function ( f25_arg0 )
				f18_arg0.Header:beginAnimation( 200 )
				f18_arg0.Header:setRGB( 0.58, 0.58, 0.58 )
				f18_arg0.Header:registerEventHandler( "interrupted_keyframe", f18_arg0.clipInterrupted )
				f18_arg0.Header:registerEventHandler( "transition_complete_keyframe", f18_arg0.clipFinished )
			end
			
			f18_arg0.Header:completeAnimation()
			f18_arg0.Header:setRGB( ColorSet.T8__BIEGE.r, ColorSet.T8__BIEGE.g, ColorSet.T8__BIEGE.b )
			f18_arg0.Header:setAlpha( 1 )
			f18_local6( f18_arg0.Header )
			local f18_local7 = function ( f26_arg0 )
				f18_arg0.MiddleText:beginAnimation( 200 )
				f18_arg0.MiddleText:setRGB( 0.58, 0.58, 0.58 )
				f18_arg0.MiddleText:registerEventHandler( "interrupted_keyframe", f18_arg0.clipInterrupted )
				f18_arg0.MiddleText:registerEventHandler( "transition_complete_keyframe", f18_arg0.clipFinished )
			end
			
			f18_arg0.MiddleText:completeAnimation()
			f18_arg0.MiddleText:setRGB( ColorSet.T8__BIEGE.r, ColorSet.T8__BIEGE.g, ColorSet.T8__BIEGE.b )
			f18_local7( f18_arg0.MiddleText )
		end
	},
	Locked = {
		DefaultClip = function ( f27_arg0, f27_arg1 )
			f27_arg0:__resetProperties()
			f27_arg0:setupElementClipCounter( 6 )
			f27_arg0.BGGray:completeAnimation()
			f27_arg0.BGGray:setRGB( 0.12, 0.12, 0.12 )
			f27_arg0.clipFinished( f27_arg0.BGGray )
			f27_arg0.ImageNotFocus:completeAnimation()
			f27_arg0.ImageNotFocus:setRGB( 0.44, 0.44, 0.44 )
			f27_arg0.ImageNotFocus:setMaterial( LUI.UIImage.GetCachedMaterial( 0x67D1E3A3D2D1BF ) )
			f27_arg0.ImageNotFocus:setShaderVector( 0, 0.5, 0, 0, 0 )
			f27_arg0.clipFinished( f27_arg0.ImageNotFocus )
			f27_arg0.lockImage:completeAnimation()
			f27_arg0.lockImage:setAlpha( 0.2 )
			f27_arg0.clipFinished( f27_arg0.lockImage )
			f27_arg0.LeaderActivityText:completeAnimation()
			f27_arg0.LeaderActivityText:setRGB( 0.39, 0.39, 0.39 )
			f27_arg0.LeaderActivityText:setAlpha( 1 )
			f27_arg0.clipFinished( f27_arg0.LeaderActivityText )
			f27_arg0.Header:completeAnimation()
			f27_arg0.Header:setRGB( 0.39, 0.39, 0.39 )
			f27_arg0.Header:setAlpha( 1 )
			f27_arg0.clipFinished( f27_arg0.Header )
			f27_arg0.MiddleText:completeAnimation()
			f27_arg0.MiddleText:setRGB( 0.39, 0.39, 0.39 )
			f27_arg0.MiddleText:setAlpha( 1 )
			f27_arg0.clipFinished( f27_arg0.MiddleText )
		end,
		Focus = function ( f28_arg0, f28_arg1 )
			f28_arg0:__resetProperties()
			f28_arg0:setupElementClipCounter( 8 )
			f28_arg0.FrameBorder:completeAnimation()
			f28_arg0.FrameBorder:setAlpha( 0.4 )
			f28_arg0.clipFinished( f28_arg0.FrameBorder )
			f28_arg0.BGGlow:completeAnimation()
			f28_arg0.BGGlow:setAlpha( 0.5 )
			f28_arg0.clipFinished( f28_arg0.BGGlow )
			f28_arg0.FocusBrackets:completeAnimation()
			f28_arg0.FocusBrackets:setLeftRight( 0, 1, -10, 10 )
			f28_arg0.FocusBrackets:setTopBottom( 0, 1, -10, 10 )
			f28_arg0.FocusBrackets:setAlpha( 1 )
			f28_arg0.clipFinished( f28_arg0.FocusBrackets )
			f28_arg0.ImageNotFocus:completeAnimation()
			f28_arg0.ImageNotFocus:setRGB( 0.44, 0.44, 0.44 )
			f28_arg0.ImageNotFocus:setMaterial( LUI.UIImage.GetCachedMaterial( 0x67D1E3A3D2D1BF ) )
			f28_arg0.ImageNotFocus:setShaderVector( 0, 0.5, 0, 0, 0 )
			f28_arg0.clipFinished( f28_arg0.ImageNotFocus )
			f28_arg0.lockImage:completeAnimation()
			f28_arg0.lockImage:setAlpha( 0.75 )
			f28_arg0.clipFinished( f28_arg0.lockImage )
			f28_arg0.LeaderActivityText:completeAnimation()
			f28_arg0.LeaderActivityText:setAlpha( 0.05 )
			f28_arg0.clipFinished( f28_arg0.LeaderActivityText )
			f28_arg0.Header:completeAnimation()
			f28_arg0.Header:setAlpha( 0.1 )
			f28_arg0.clipFinished( f28_arg0.Header )
			f28_arg0.MiddleText:completeAnimation()
			f28_arg0.MiddleText:setAlpha( 0.3 )
			f28_arg0.clipFinished( f28_arg0.MiddleText )
		end,
		GainFocus = function ( f29_arg0, f29_arg1 )
			f29_arg0:__resetProperties()
			f29_arg0:setupElementClipCounter( 6 )
			local f29_local0 = function ( f30_arg0 )
				f29_arg0.BGGlow:beginAnimation( 200 )
				f29_arg0.BGGlow:setAlpha( 0.5 )
				f29_arg0.BGGlow:registerEventHandler( "interrupted_keyframe", f29_arg0.clipInterrupted )
				f29_arg0.BGGlow:registerEventHandler( "transition_complete_keyframe", f29_arg0.clipFinished )
			end
			
			f29_arg0.BGGlow:completeAnimation()
			f29_arg0.BGGlow:setAlpha( 0 )
			f29_local0( f29_arg0.BGGlow )
			f29_arg0.ImageNotFocus:completeAnimation()
			f29_arg0.ImageNotFocus:setRGB( 0.44, 0.44, 0.44 )
			f29_arg0.ImageNotFocus:setMaterial( LUI.UIImage.GetCachedMaterial( 0x67D1E3A3D2D1BF ) )
			f29_arg0.ImageNotFocus:setShaderVector( 0, 0.5, 0, 0, 0 )
			f29_arg0.clipFinished( f29_arg0.ImageNotFocus )
			f29_arg0.lockImage:completeAnimation()
			f29_arg0.lockImage:setAlpha( 0.2 )
			f29_arg0.clipFinished( f29_arg0.lockImage )
			local f29_local1 = function ( f31_arg0 )
				f29_arg0.LeaderActivityText:beginAnimation( 200 )
				f29_arg0.LeaderActivityText:setAlpha( 0.1 )
				f29_arg0.LeaderActivityText:registerEventHandler( "interrupted_keyframe", f29_arg0.clipInterrupted )
				f29_arg0.LeaderActivityText:registerEventHandler( "transition_complete_keyframe", f29_arg0.clipFinished )
			end
			
			f29_arg0.LeaderActivityText:completeAnimation()
			f29_arg0.LeaderActivityText:setAlpha( 0.05 )
			f29_local1( f29_arg0.LeaderActivityText )
			local f29_local2 = function ( f32_arg0 )
				f29_arg0.Header:beginAnimation( 200 )
				f29_arg0.Header:setAlpha( 0.1 )
				f29_arg0.Header:registerEventHandler( "interrupted_keyframe", f29_arg0.clipInterrupted )
				f29_arg0.Header:registerEventHandler( "transition_complete_keyframe", f29_arg0.clipFinished )
			end
			
			f29_arg0.Header:completeAnimation()
			f29_arg0.Header:setAlpha( 0.05 )
			f29_local2( f29_arg0.Header )
			f29_arg0.MiddleText:completeAnimation()
			f29_arg0.MiddleText:setAlpha( 0.3 )
			f29_arg0.clipFinished( f29_arg0.MiddleText )
		end,
		LoseFocus = function ( f33_arg0, f33_arg1 )
			f33_arg0:__resetProperties()
			f33_arg0:setupElementClipCounter( 6 )
			local f33_local0 = function ( f34_arg0 )
				f33_arg0.BGGlow:beginAnimation( 200 )
				f33_arg0.BGGlow:setAlpha( 0 )
				f33_arg0.BGGlow:registerEventHandler( "interrupted_keyframe", f33_arg0.clipInterrupted )
				f33_arg0.BGGlow:registerEventHandler( "transition_complete_keyframe", f33_arg0.clipFinished )
			end
			
			f33_arg0.BGGlow:completeAnimation()
			f33_arg0.BGGlow:setAlpha( 0.5 )
			f33_local0( f33_arg0.BGGlow )
			f33_arg0.ImageNotFocus:completeAnimation()
			f33_arg0.ImageNotFocus:setRGB( 0.44, 0.44, 0.44 )
			f33_arg0.ImageNotFocus:setMaterial( LUI.UIImage.GetCachedMaterial( 0x67D1E3A3D2D1BF ) )
			f33_arg0.ImageNotFocus:setShaderVector( 0, 0.5, 0, 0, 0 )
			f33_arg0.clipFinished( f33_arg0.ImageNotFocus )
			f33_arg0.lockImage:completeAnimation()
			f33_arg0.lockImage:setAlpha( 0.2 )
			f33_arg0.clipFinished( f33_arg0.lockImage )
			local f33_local1 = function ( f35_arg0 )
				f33_arg0.LeaderActivityText:beginAnimation( 200 )
				f33_arg0.LeaderActivityText:setAlpha( 0.05 )
				f33_arg0.LeaderActivityText:registerEventHandler( "interrupted_keyframe", f33_arg0.clipInterrupted )
				f33_arg0.LeaderActivityText:registerEventHandler( "transition_complete_keyframe", f33_arg0.clipFinished )
			end
			
			f33_arg0.LeaderActivityText:completeAnimation()
			f33_arg0.LeaderActivityText:setAlpha( 0.1 )
			f33_local1( f33_arg0.LeaderActivityText )
			local f33_local2 = function ( f36_arg0 )
				f33_arg0.Header:beginAnimation( 200 )
				f33_arg0.Header:setAlpha( 0.05 )
				f33_arg0.Header:registerEventHandler( "interrupted_keyframe", f33_arg0.clipInterrupted )
				f33_arg0.Header:registerEventHandler( "transition_complete_keyframe", f33_arg0.clipFinished )
			end
			
			f33_arg0.Header:completeAnimation()
			f33_arg0.Header:setAlpha( 0.1 )
			f33_local2( f33_arg0.Header )
			f33_arg0.MiddleText:completeAnimation()
			f33_arg0.MiddleText:setAlpha( 0.3 )
			f33_arg0.clipFinished( f33_arg0.MiddleText )
		end
	},
	Disabled = {
		DefaultClip = function ( f37_arg0, f37_arg1 )
			f37_arg0:__resetProperties()
			f37_arg0:setupElementClipCounter( 3 )
			f37_arg0.lockImage:completeAnimation()
			f37_arg0.lockImage:setScale( 1.2, 1.2 )
			f37_arg0.clipFinished( f37_arg0.lockImage )
			f37_arg0.LeaderActivityText:completeAnimation()
			f37_arg0.LeaderActivityText:setAlpha( 0.05 )
			f37_arg0.clipFinished( f37_arg0.LeaderActivityText )
			f37_arg0.Header:completeAnimation()
			f37_arg0.Header:setAlpha( 0.05 )
			f37_arg0.clipFinished( f37_arg0.Header )
		end
	}
}
CoD.ZMButtonDifficultyInternal.__onClose = function ( f38_arg0 )
	f38_arg0.TopOrnament:close()
	f38_arg0.FocusBrackets:close()
	f38_arg0.ImageNotFocus:close()
	f38_arg0.timer:close()
	f38_arg0.CountdownText:close()
end

