require( "ui/uieditor/widgets/common/commonfocusbrackets" )
require( "ui/uieditor/widgets/common/CommonPixelBacking" )
require( "ui/uieditor/widgets/director/directorselectbuttonlines" )

CoD.Social_PartySettingsButtonInternal = InheritFrom( LUI.UIElement )
CoD.Social_PartySettingsButtonInternal.__defaultWidth = 301
CoD.Social_PartySettingsButtonInternal.__defaultHeight = 250
CoD.Social_PartySettingsButtonInternal.new = function ( f1_arg0, f1_arg1, f1_arg2, f1_arg3, f1_arg4, f1_arg5, f1_arg6, f1_arg7, f1_arg8, f1_arg9 )
	local self = LUI.UIElement.new( f1_arg2, f1_arg3, f1_arg4, f1_arg5, f1_arg6, f1_arg7, f1_arg8, f1_arg9 )
	self:setClass( CoD.Social_PartySettingsButtonInternal )
	self.id = "Social_PartySettingsButtonInternal"
	self.soundSet = "FrontendMain"
	f1_arg0:addElementToPendingUpdateStateList( self )
	
	local SceneBlur = LUI.UIImage.new( 0, 1, 0, 0, 0, 1, 0, 0 )
	SceneBlur:setRGB( 0, 0, 0 )
	SceneBlur:setMaterial( LUI.UIImage.GetCachedMaterial( 0xE2354BE557C4C7A ) )
	SceneBlur:setShaderVector( 0, 0, 0.4, 0, 0 )
	self:addElement( SceneBlur )
	self.SceneBlur = SceneBlur
	
	local NoiseTiledBacking = LUI.UIImage.new( 0, 1, 0, 0, 0, 1, 0, 0 )
	NoiseTiledBacking:setAlpha( 0.95 )
	NoiseTiledBacking:setImage( RegisterImage( 0x34839E8065B1E53 ) )
	NoiseTiledBacking:setMaterial( LUI.UIImage.GetCachedMaterial( 0x6CBE95C250C6D15 ) )
	NoiseTiledBacking:setShaderVector( 0, 0, 0, 0, 0 )
	NoiseTiledBacking:setupNineSliceShader( 196, 88 )
	self:addElement( NoiseTiledBacking )
	self.NoiseTiledBacking = NoiseTiledBacking
	
	local Tint = LUI.UIImage.new( 0, 1, 0, 0, 0, 1, 0, 0 )
	Tint:setRGB( 0, 0, 0 )
	Tint:setAlpha( 0.75 )
	self:addElement( Tint )
	self.Tint = Tint
	
	local FocusBrackets = CoD.CommonFocusBrackets.new( f1_arg0, f1_arg1, 0, 1, -20, 20, 0, 1, -20, 20 )
	FocusBrackets:setAlpha( 0 )
	self:addElement( FocusBrackets )
	self.FocusBrackets = FocusBrackets
	
	local FrontendFrameSelected = LUI.UIImage.new( 0, 1, -4, 4, 0, 1, -4, 4 )
	FrontendFrameSelected:setRGB( 0.8, 0.7, 0.09 )
	FrontendFrameSelected:setAlpha( 0 )
	FrontendFrameSelected:setImage( RegisterImage( 0xCB07CCC28498CB2 ) )
	FrontendFrameSelected:setMaterial( LUI.UIImage.GetCachedMaterial( 0xFD777557404A7B3 ) )
	FrontendFrameSelected:setShaderVector( 0, 0, 0, 0, 0 )
	FrontendFrameSelected:setupNineSliceShader( 10, 10 )
	self:addElement( FrontendFrameSelected )
	self.FrontendFrameSelected = FrontendFrameSelected
	
	local FocusGlow = LUI.UIImage.new( 0, 1, -130, 130, 0, 1, -158, 158 )
	FocusGlow:setAlpha( 0 )
	FocusGlow:setImage( RegisterImage( 0x223AD1B40A93955 ) )
	FocusGlow:setMaterial( LUI.UIImage.GetCachedMaterial( 0xDAB59B2CAE01851 ) )
	FocusGlow:setShaderVector( 0, 0, 0, 0.21, 0.09 )
	FocusGlow:setShaderVector( 1, 1.36, 0, 0, 0 )
	FocusGlow:setupNineSliceShader( 245, 185 )
	self:addElement( FocusGlow )
	self.FocusGlow = FocusGlow
	
	local FocusHighlight = LUI.UIImage.new( 0, 1, -52, 52, 0, 1, -42, 42 )
	FocusHighlight:setAlpha( 0 )
	FocusHighlight:setImage( RegisterImage( 0x3F09D20CA138B49 ) )
	FocusHighlight:setMaterial( LUI.UIImage.GetCachedMaterial( 0xDAB59B2CAE01851 ) )
	FocusHighlight:setShaderVector( 0, 0, 0, 0.27, 0.18 )
	FocusHighlight:setShaderVector( 1, 0.9, 0, 0, 0 )
	FocusHighlight:setupNineSliceShader( 135, 70 )
	self:addElement( FocusHighlight )
	self.FocusHighlight = FocusHighlight
	
	local DotTiledBacking = CoD.CommonPixelBacking.new( f1_arg0, f1_arg1, 0, 1, 4, -4, 0, 1, 4, -4 )
	DotTiledBacking:setRFTMaterial( LUI.UIImage.GetCachedMaterial( 0x4E6CE42E0799F57 ) )
	DotTiledBacking.NoiseBacking:setAlpha( 1 )
	DotTiledBacking.TiledShaderImage:setRGB( 0.22, 0.22, 0.22 )
	DotTiledBacking.TiledShaderImage:setAlpha( 0.15 )
	DotTiledBacking.TiledShaderImage:setupNineSliceShader( 36, 36 )
	self:addElement( DotTiledBacking )
	self.DotTiledBacking = DotTiledBacking
	
	local FrameBorder = LUI.UIImage.new( 0, 1, -1, 1, 0, 1, -1, 1 )
	FrameBorder:setAlpha( 0.1 )
	FrameBorder:setImage( RegisterImage( 0x185E11D74ECA3D7 ) )
	FrameBorder:setMaterial( LUI.UIImage.GetCachedMaterial( 0xFD777557404A7B3 ) )
	FrameBorder:setShaderVector( 0, 0, 0, 0, 0 )
	FrameBorder:setupNineSliceShader( 12, 12 )
	self:addElement( FrameBorder )
	self.FrameBorder = FrameBorder
	
	local PartyPrivacyLabel = LUI.UIText.new( 0, 1, 16, -16, 0.5, 0.5, -89, -71 )
	PartyPrivacyLabel:setRGB( ColorSet.T8__BIEGE.r, ColorSet.T8__BIEGE.g, ColorSet.T8__BIEGE.b )
	PartyPrivacyLabel.__String_Reference = function ()
		PartyPrivacyLabel:setText( ToUpper( CoD.SocialUtility.GetCurrentPartySettingString( f1_arg1, "party_privacyStatus", 0x59ECB59CCD0E44B ) ) )
	end
	
	PartyPrivacyLabel.__String_Reference()
	PartyPrivacyLabel:setTTF( "ttmussels_regular" )
	PartyPrivacyLabel:setMaterial( LUI.UIImage.GetCachedMaterial( 0x71E049B161CD00A ) )
	PartyPrivacyLabel:setLetterSpacing( 3 )
	PartyPrivacyLabel:setAlignment( Enum.LUIAlignment[0x58C8A85F2048829] )
	PartyPrivacyLabel:setAlignment( Enum.LUIAlignment[0xF41D595A2B0EDF3] )
	self:addElement( PartyPrivacyLabel )
	self.PartyPrivacyLabel = PartyPrivacyLabel
	
	local PartyPrivacyLabelFocus = LUI.UIText.new( 0, 1, 16, -16, 0.5, 0.5, -89, -71 )
	PartyPrivacyLabelFocus:setRGB( 0.28, 0.25, 0.24 )
	PartyPrivacyLabelFocus:setAlpha( 0 )
	PartyPrivacyLabelFocus.__String_Reference = function ()
		PartyPrivacyLabelFocus:setText( ToUpper( CoD.SocialUtility.GetCurrentPartySettingString( f1_arg1, "party_privacyStatus", 0x59ECB59CCD0E44B ) ) )
	end
	
	PartyPrivacyLabelFocus.__String_Reference()
	PartyPrivacyLabelFocus:setTTF( "ttmussels_regular" )
	PartyPrivacyLabelFocus:setMaterial( LUI.UIImage.GetCachedMaterial( 0xAE166D9BA8C6907 ) )
	PartyPrivacyLabelFocus:setShaderVector( 0, 0.13, 0, 0, 0 )
	PartyPrivacyLabelFocus:setShaderVector( 1, 0.34, 0, 0, 0 )
	PartyPrivacyLabelFocus:setShaderVector( 2, 1, 0, 0, 0 )
	PartyPrivacyLabelFocus:setLetterSpacing( 3 )
	PartyPrivacyLabelFocus:setAlignment( Enum.LUIAlignment[0x58C8A85F2048829] )
	PartyPrivacyLabelFocus:setAlignment( Enum.LUIAlignment[0xF41D595A2B0EDF3] )
	self:addElement( PartyPrivacyLabelFocus )
	self.PartyPrivacyLabelFocus = PartyPrivacyLabelFocus
	
	local PlayerLimitLabel = LUI.UIText.new( 0, 1, 16, -16, 0.5, 0.5, -29, -11 )
	PlayerLimitLabel:setRGB( ColorSet.T8__BIEGE.r, ColorSet.T8__BIEGE.g, ColorSet.T8__BIEGE.b )
	PlayerLimitLabel.__String_Reference = function ()
		PlayerLimitLabel:setText( ToUpper( CoD.SocialUtility.GetCurrentPlayerLimitString( 0xA37FF777F075DFF ) ) )
	end
	
	PlayerLimitLabel.__String_Reference()
	PlayerLimitLabel:setTTF( "ttmussels_regular" )
	PlayerLimitLabel:setMaterial( LUI.UIImage.GetCachedMaterial( 0x71E049B161CD00A ) )
	PlayerLimitLabel:setLetterSpacing( 3 )
	PlayerLimitLabel:setAlignment( Enum.LUIAlignment[0x58C8A85F2048829] )
	PlayerLimitLabel:setAlignment( Enum.LUIAlignment[0xF41D595A2B0EDF3] )
	self:addElement( PlayerLimitLabel )
	self.PlayerLimitLabel = PlayerLimitLabel
	
	local PlayerLimitLabelFocus = LUI.UIText.new( 0, 1, 16, -16, 0.5, 0.5, -29, -11 )
	PlayerLimitLabelFocus:setRGB( 0.28, 0.25, 0.24 )
	PlayerLimitLabelFocus:setAlpha( 0 )
	PlayerLimitLabelFocus.__String_Reference = function ()
		PlayerLimitLabelFocus:setText( ToUpper( CoD.SocialUtility.GetCurrentPlayerLimitString( 0xA37FF777F075DFF ) ) )
	end
	
	PlayerLimitLabelFocus.__String_Reference()
	PlayerLimitLabelFocus:setTTF( "ttmussels_regular" )
	PlayerLimitLabelFocus:setMaterial( LUI.UIImage.GetCachedMaterial( 0xAE166D9BA8C6907 ) )
	PlayerLimitLabelFocus:setShaderVector( 0, 0.13, 0, 0, 0 )
	PlayerLimitLabelFocus:setShaderVector( 1, 0.34, 0, 0, 0 )
	PlayerLimitLabelFocus:setShaderVector( 2, 1, 0, 0, 0 )
	PlayerLimitLabelFocus:setLetterSpacing( 3 )
	PlayerLimitLabelFocus:setAlignment( Enum.LUIAlignment[0x58C8A85F2048829] )
	PlayerLimitLabelFocus:setAlignment( Enum.LUIAlignment[0xF41D595A2B0EDF3] )
	self:addElement( PlayerLimitLabelFocus )
	self.PlayerLimitLabelFocus = PlayerLimitLabelFocus
	
	local VoiceChatLabel = LUI.UIText.new( 0, 1, 16, -16, 0.5, 0.5, 31, 49 )
	VoiceChatLabel:setRGB( ColorSet.T8__BIEGE.r, ColorSet.T8__BIEGE.g, ColorSet.T8__BIEGE.b )
	VoiceChatLabel.__String_Reference = function ()
		VoiceChatLabel:setText( ToUpper( CoD.SocialUtility.GetCurrentPartySettingString( f1_arg1, "voice_favored_channel", 0x96E95878764ABE7 ) ) )
	end
	
	VoiceChatLabel.__String_Reference()
	VoiceChatLabel:setTTF( "ttmussels_regular" )
	VoiceChatLabel:setMaterial( LUI.UIImage.GetCachedMaterial( 0x71E049B161CD00A ) )
	VoiceChatLabel:setLetterSpacing( 3 )
	VoiceChatLabel:setAlignment( Enum.LUIAlignment[0x58C8A85F2048829] )
	VoiceChatLabel:setAlignment( Enum.LUIAlignment[0xF41D595A2B0EDF3] )
	self:addElement( VoiceChatLabel )
	self.VoiceChatLabel = VoiceChatLabel
	
	local VoiceChatLabelFocus = LUI.UIText.new( 0, 1, 16, -16, 0.5, 0.5, 31, 49 )
	VoiceChatLabelFocus:setRGB( 0.28, 0.25, 0.24 )
	VoiceChatLabelFocus:setAlpha( 0 )
	VoiceChatLabelFocus.__String_Reference = function ()
		VoiceChatLabelFocus:setText( ToUpper( CoD.SocialUtility.GetCurrentPartySettingString( f1_arg1, "voice_favored_channel", 0x96E95878764ABE7 ) ) )
	end
	
	VoiceChatLabelFocus.__String_Reference()
	VoiceChatLabelFocus:setTTF( "ttmussels_regular" )
	VoiceChatLabelFocus:setMaterial( LUI.UIImage.GetCachedMaterial( 0xAE166D9BA8C6907 ) )
	VoiceChatLabelFocus:setShaderVector( 0, 0.13, 0, 0, 0 )
	VoiceChatLabelFocus:setShaderVector( 1, 0.34, 0, 0, 0 )
	VoiceChatLabelFocus:setShaderVector( 2, 1, 0, 0, 0 )
	VoiceChatLabelFocus:setLetterSpacing( 3 )
	VoiceChatLabelFocus:setAlignment( Enum.LUIAlignment[0x58C8A85F2048829] )
	VoiceChatLabelFocus:setAlignment( Enum.LUIAlignment[0xF41D595A2B0EDF3] )
	self:addElement( VoiceChatLabelFocus )
	self.VoiceChatLabelFocus = VoiceChatLabelFocus
	
	local lockImage = LUI.UIImage.new( 1, 1, -42, 8, 0.5, 0.5, -25, 25 )
	lockImage:setAlpha( 0 )
	lockImage:setScale( 0.6, 0.6 )
	lockImage:setImage( RegisterImage( 0xE1E7C490B2BA4FB ) )
	self:addElement( lockImage )
	self.lockImage = lockImage
	
	local Lines = CoD.DirectorSelectButtonLines.new( f1_arg0, f1_arg1, 0, 1, 0, 0, 0, 1, 1, -1 )
	Lines:setRGB( 0.64, 0.71, 0.78 )
	self:addElement( Lines )
	self.Lines = Lines
	
	local FocusBorder = LUI.UIImage.new( 0, 1, -4, 4, 0, 1, -4, 4 )
	FocusBorder:setRGB( 0.96, 0.94, 0.78 )
	FocusBorder:setAlpha( 0 )
	FocusBorder:setImage( RegisterImage( 0xCB07CCC28498CB2 ) )
	FocusBorder:setMaterial( LUI.UIImage.GetCachedMaterial( 0xFD777557404A7B3 ) )
	FocusBorder:setShaderVector( 0, 0, 0, 0, 0 )
	FocusBorder:setupNineSliceShader( 10, 10 )
	self:addElement( FocusBorder )
	self.FocusBorder = FocusBorder
	
	local f1_local19 = PartyPrivacyLabel
	local f1_local20 = PartyPrivacyLabel.subscribeToModel
	local f1_local21 = DataSources.LobbyRoot.getModel( f1_arg1 )
	f1_local20( f1_local19, f1_local21.partySettingsUpdate, PartyPrivacyLabel.__String_Reference )
	f1_local19 = PartyPrivacyLabelFocus
	f1_local20 = PartyPrivacyLabelFocus.subscribeToModel
	f1_local21 = DataSources.LobbyRoot.getModel( f1_arg1 )
	f1_local20( f1_local19, f1_local21.partySettingsUpdate, PartyPrivacyLabelFocus.__String_Reference )
	f1_local19 = PlayerLimitLabel
	f1_local20 = PlayerLimitLabel.subscribeToModel
	f1_local21 = DataSources.LobbyRoot.getModel( f1_arg1 )
	f1_local20( f1_local19, f1_local21.partySettingsUpdate, PlayerLimitLabel.__String_Reference )
	f1_local19 = PlayerLimitLabelFocus
	f1_local20 = PlayerLimitLabelFocus.subscribeToModel
	f1_local21 = DataSources.LobbyRoot.getModel( f1_arg1 )
	f1_local20( f1_local19, f1_local21.partySettingsUpdate, PlayerLimitLabelFocus.__String_Reference )
	f1_local19 = VoiceChatLabel
	f1_local20 = VoiceChatLabel.subscribeToModel
	f1_local21 = DataSources.LobbyRoot.getModel( f1_arg1 )
	f1_local20( f1_local19, f1_local21.partySettingsUpdate, VoiceChatLabel.__String_Reference )
	f1_local19 = VoiceChatLabelFocus
	f1_local20 = VoiceChatLabelFocus.subscribeToModel
	f1_local21 = DataSources.LobbyRoot.getModel( f1_arg1 )
	f1_local20( f1_local19, f1_local21.partySettingsUpdate, VoiceChatLabelFocus.__String_Reference )
	LUI.OverrideFunction_CallOriginalSecond( self, "close", self.__onClose )
	
	if PostLoadFunc then
		PostLoadFunc( self, f1_arg1, f1_arg0 )
	end
	
	return self
end

CoD.Social_PartySettingsButtonInternal.__resetProperties = function ( f8_arg0 )
	f8_arg0.lockImage:completeAnimation()
	f8_arg0.FrontendFrameSelected:completeAnimation()
	f8_arg0.FocusBrackets:completeAnimation()
	f8_arg0.DotTiledBacking:completeAnimation()
	f8_arg0.Lines:completeAnimation()
	f8_arg0.FocusHighlight:completeAnimation()
	f8_arg0.FocusGlow:completeAnimation()
	f8_arg0.PartyPrivacyLabel:completeAnimation()
	f8_arg0.PartyPrivacyLabelFocus:completeAnimation()
	f8_arg0.PlayerLimitLabel:completeAnimation()
	f8_arg0.VoiceChatLabel:completeAnimation()
	f8_arg0.PlayerLimitLabelFocus:completeAnimation()
	f8_arg0.VoiceChatLabelFocus:completeAnimation()
	f8_arg0.NoiseTiledBacking:completeAnimation()
	f8_arg0.FocusBorder:completeAnimation()
	f8_arg0.lockImage:setAlpha( 0 )
	f8_arg0.lockImage:setScale( 0.6, 0.6 )
	f8_arg0.FrontendFrameSelected:setAlpha( 0 )
	f8_arg0.FocusBrackets:setLeftRight( 0, 1, -20, 20 )
	f8_arg0.FocusBrackets:setTopBottom( 0, 1, -20, 20 )
	f8_arg0.FocusBrackets:setAlpha( 0 )
	f8_arg0.DotTiledBacking.TiledShaderImage:setRGB( 0.22, 0.22, 0.22 )
	f8_arg0.DotTiledBacking.TiledShaderImage:setAlpha( 0.15 )
	f8_arg0.Lines:setAlpha( 1 )
	f8_arg0.FocusHighlight:setAlpha( 0 )
	f8_arg0.FocusGlow:setRGB( 1, 1, 1 )
	f8_arg0.FocusGlow:setAlpha( 0 )
	f8_arg0.PartyPrivacyLabel:setRGB( ColorSet.T8__BIEGE.r, ColorSet.T8__BIEGE.g, ColorSet.T8__BIEGE.b )
	f8_arg0.PartyPrivacyLabel:setAlpha( 1 )
	f8_arg0.PartyPrivacyLabelFocus:setAlpha( 0 )
	f8_arg0.PlayerLimitLabel:setRGB( ColorSet.T8__BIEGE.r, ColorSet.T8__BIEGE.g, ColorSet.T8__BIEGE.b )
	f8_arg0.PlayerLimitLabel:setAlpha( 1 )
	f8_arg0.VoiceChatLabel:setRGB( ColorSet.T8__BIEGE.r, ColorSet.T8__BIEGE.g, ColorSet.T8__BIEGE.b )
	f8_arg0.VoiceChatLabel:setAlpha( 1 )
	f8_arg0.PlayerLimitLabelFocus:setAlpha( 0 )
	f8_arg0.VoiceChatLabelFocus:setAlpha( 0 )
	f8_arg0.NoiseTiledBacking:setRGB( 1, 1, 1 )
	f8_arg0.FocusBorder:setRGB( 0.96, 0.94, 0.78 )
	f8_arg0.FocusBorder:setAlpha( 0 )
end

CoD.Social_PartySettingsButtonInternal.__clipsPerState = {
	DefaultState = {
		DefaultClip = function ( f9_arg0, f9_arg1 )
			f9_arg0:__resetProperties()
			f9_arg0:setupElementClipCounter( 0 )
		end,
		Focus = function ( f10_arg0, f10_arg1 )
			f10_arg0:__resetProperties()
			f10_arg0:setupElementClipCounter( 13 )
			f10_arg0.FocusBrackets:completeAnimation()
			f10_arg0.FocusBrackets:setLeftRight( 0, 1, -10, 10 )
			f10_arg0.FocusBrackets:setTopBottom( 0, 1, -10, 10 )
			f10_arg0.FocusBrackets:setAlpha( 1 )
			f10_arg0.clipFinished( f10_arg0.FocusBrackets )
			f10_arg0.FrontendFrameSelected:completeAnimation()
			f10_arg0.FrontendFrameSelected:setAlpha( 0.1 )
			f10_arg0.clipFinished( f10_arg0.FrontendFrameSelected )
			local f10_local0 = function ( f11_arg0 )
				local f11_local0 = function ( f12_arg0 )
					f12_arg0:beginAnimation( 2010 )
					f12_arg0:setRGB( 1, 1, 1 )
					f12_arg0:registerEventHandler( "transition_complete_keyframe", f10_arg0.clipFinished )
				end
				
				f10_arg0.FocusGlow:beginAnimation( 1990 )
				f10_arg0.FocusGlow:setRGB( 0.79, 0.79, 0.79 )
				f10_arg0.FocusGlow:registerEventHandler( "interrupted_keyframe", f10_arg0.clipInterrupted )
				f10_arg0.FocusGlow:registerEventHandler( "transition_complete_keyframe", f11_local0 )
			end
			
			f10_arg0.FocusGlow:completeAnimation()
			f10_arg0.FocusGlow:setRGB( 1, 1, 1 )
			f10_arg0.FocusGlow:setAlpha( 1 )
			f10_local0( f10_arg0.FocusGlow )
			f10_arg0.FocusHighlight:completeAnimation()
			f10_arg0.FocusHighlight:setAlpha( 0.5 )
			f10_arg0.clipFinished( f10_arg0.FocusHighlight )
			f10_arg0.DotTiledBacking:completeAnimation()
			f10_arg0.DotTiledBacking.TiledShaderImage:completeAnimation()
			f10_arg0.DotTiledBacking.TiledShaderImage:setRGB( 0.28, 0.28, 0.28 )
			f10_arg0.DotTiledBacking.TiledShaderImage:setAlpha( 0.7 )
			f10_arg0.clipFinished( f10_arg0.DotTiledBacking )
			f10_arg0.PartyPrivacyLabel:completeAnimation()
			f10_arg0.PartyPrivacyLabel:setAlpha( 0 )
			f10_arg0.clipFinished( f10_arg0.PartyPrivacyLabel )
			f10_arg0.PartyPrivacyLabelFocus:completeAnimation()
			f10_arg0.PartyPrivacyLabelFocus:setAlpha( 1 )
			f10_arg0.clipFinished( f10_arg0.PartyPrivacyLabelFocus )
			f10_arg0.PlayerLimitLabel:completeAnimation()
			f10_arg0.PlayerLimitLabel:setAlpha( 0 )
			f10_arg0.clipFinished( f10_arg0.PlayerLimitLabel )
			f10_arg0.PlayerLimitLabelFocus:completeAnimation()
			f10_arg0.PlayerLimitLabelFocus:setAlpha( 1 )
			f10_arg0.clipFinished( f10_arg0.PlayerLimitLabelFocus )
			f10_arg0.VoiceChatLabel:completeAnimation()
			f10_arg0.VoiceChatLabel:setAlpha( 0 )
			f10_arg0.clipFinished( f10_arg0.VoiceChatLabel )
			f10_arg0.VoiceChatLabelFocus:completeAnimation()
			f10_arg0.VoiceChatLabelFocus:setAlpha( 1 )
			f10_arg0.clipFinished( f10_arg0.VoiceChatLabelFocus )
			f10_arg0.lockImage:completeAnimation()
			f10_arg0.lockImage:setScale( 1.2, 1.2 )
			f10_arg0.clipFinished( f10_arg0.lockImage )
			f10_arg0.Lines:completeAnimation()
			f10_arg0.Lines:setAlpha( 0 )
			f10_arg0.clipFinished( f10_arg0.Lines )
			f10_arg0.nextClip = "Focus"
		end,
		GainFocus = function ( f13_arg0, f13_arg1 )
			f13_arg0:__resetProperties()
			f13_arg0:setupElementClipCounter( 13 )
			local f13_local0 = function ( f14_arg0 )
				local f14_local0 = function ( f15_arg0 )
					f15_arg0:beginAnimation( 50, Enum[0xF50FFF429AB1890][0x6F6186B702830BC] )
					f15_arg0:setLeftRight( 0, 1, -10, 10 )
					f15_arg0:setTopBottom( 0, 1, -10, 10 )
					f15_arg0:setAlpha( 1 )
					f15_arg0:registerEventHandler( "transition_complete_keyframe", f13_arg0.clipFinished )
				end
				
				f13_arg0.FocusBrackets:beginAnimation( 100 )
				f13_arg0.FocusBrackets:setLeftRight( 0, 1, -8, 8 )
				f13_arg0.FocusBrackets:setTopBottom( 0, 1, -8, 8 )
				f13_arg0.FocusBrackets:setAlpha( 0.75 )
				f13_arg0.FocusBrackets:registerEventHandler( "interrupted_keyframe", f13_arg0.clipInterrupted )
				f13_arg0.FocusBrackets:registerEventHandler( "transition_complete_keyframe", f14_local0 )
			end
			
			f13_arg0.FocusBrackets:completeAnimation()
			f13_arg0.FocusBrackets:setLeftRight( 0, 1, -40, 40 )
			f13_arg0.FocusBrackets:setTopBottom( 0, 1, -40, 40 )
			f13_arg0.FocusBrackets:setAlpha( 0 )
			f13_local0( f13_arg0.FocusBrackets )
			local f13_local1 = function ( f16_arg0 )
				f13_arg0.FrontendFrameSelected:beginAnimation( 200, Enum[0xF50FFF429AB1890][0x5193EA7825DC097] )
				f13_arg0.FrontendFrameSelected:setAlpha( 0.1 )
				f13_arg0.FrontendFrameSelected:registerEventHandler( "interrupted_keyframe", f13_arg0.clipInterrupted )
				f13_arg0.FrontendFrameSelected:registerEventHandler( "transition_complete_keyframe", f13_arg0.clipFinished )
			end
			
			f13_arg0.FrontendFrameSelected:completeAnimation()
			f13_arg0.FrontendFrameSelected:setAlpha( 0 )
			f13_local1( f13_arg0.FrontendFrameSelected )
			local f13_local2 = function ( f17_arg0 )
				f13_arg0.FocusGlow:beginAnimation( 200, Enum[0xF50FFF429AB1890][0x6F6186B702830BC] )
				f13_arg0.FocusGlow:setAlpha( 1 )
				f13_arg0.FocusGlow:registerEventHandler( "interrupted_keyframe", f13_arg0.clipInterrupted )
				f13_arg0.FocusGlow:registerEventHandler( "transition_complete_keyframe", f13_arg0.clipFinished )
			end
			
			f13_arg0.FocusGlow:completeAnimation()
			f13_arg0.FocusGlow:setAlpha( 0 )
			f13_local2( f13_arg0.FocusGlow )
			local f13_local3 = function ( f18_arg0 )
				f13_arg0.FocusHighlight:beginAnimation( 200 )
				f13_arg0.FocusHighlight:setAlpha( 0.8 )
				f13_arg0.FocusHighlight:registerEventHandler( "interrupted_keyframe", f13_arg0.clipInterrupted )
				f13_arg0.FocusHighlight:registerEventHandler( "transition_complete_keyframe", f13_arg0.clipFinished )
			end
			
			f13_arg0.FocusHighlight:completeAnimation()
			f13_arg0.FocusHighlight:setAlpha( 0 )
			f13_local3( f13_arg0.FocusHighlight )
			local f13_local4 = function ( f19_arg0 )
				f13_arg0.DotTiledBacking:beginAnimation( 200 )
				f13_arg0.DotTiledBacking.TiledShaderImage:beginAnimation( 200 )
				f13_arg0.DotTiledBacking.TiledShaderImage:setRGB( 0.28, 0.28, 0.28 )
				f13_arg0.DotTiledBacking:registerEventHandler( "interrupted_keyframe", f13_arg0.clipInterrupted )
				f13_arg0.DotTiledBacking:registerEventHandler( "transition_complete_keyframe", f13_arg0.clipFinished )
			end
			
			f13_arg0.DotTiledBacking:completeAnimation()
			f13_arg0.DotTiledBacking.TiledShaderImage:completeAnimation()
			f13_arg0.DotTiledBacking.TiledShaderImage:setRGB( 0.22, 0.22, 0.22 )
			f13_local4( f13_arg0.DotTiledBacking )
			local f13_local5 = function ( f20_arg0 )
				f13_arg0.PartyPrivacyLabel:beginAnimation( 200 )
				f13_arg0.PartyPrivacyLabel:setAlpha( 0 )
				f13_arg0.PartyPrivacyLabel:registerEventHandler( "interrupted_keyframe", f13_arg0.clipInterrupted )
				f13_arg0.PartyPrivacyLabel:registerEventHandler( "transition_complete_keyframe", f13_arg0.clipFinished )
			end
			
			f13_arg0.PartyPrivacyLabel:completeAnimation()
			f13_arg0.PartyPrivacyLabel:setAlpha( 1 )
			f13_local5( f13_arg0.PartyPrivacyLabel )
			local f13_local6 = function ( f21_arg0 )
				f13_arg0.PartyPrivacyLabelFocus:beginAnimation( 200 )
				f13_arg0.PartyPrivacyLabelFocus:setAlpha( 1 )
				f13_arg0.PartyPrivacyLabelFocus:registerEventHandler( "interrupted_keyframe", f13_arg0.clipInterrupted )
				f13_arg0.PartyPrivacyLabelFocus:registerEventHandler( "transition_complete_keyframe", f13_arg0.clipFinished )
			end
			
			f13_arg0.PartyPrivacyLabelFocus:completeAnimation()
			f13_arg0.PartyPrivacyLabelFocus:setAlpha( 0 )
			f13_local6( f13_arg0.PartyPrivacyLabelFocus )
			local f13_local7 = function ( f22_arg0 )
				f13_arg0.PlayerLimitLabel:beginAnimation( 200 )
				f13_arg0.PlayerLimitLabel:setAlpha( 0 )
				f13_arg0.PlayerLimitLabel:registerEventHandler( "interrupted_keyframe", f13_arg0.clipInterrupted )
				f13_arg0.PlayerLimitLabel:registerEventHandler( "transition_complete_keyframe", f13_arg0.clipFinished )
			end
			
			f13_arg0.PlayerLimitLabel:completeAnimation()
			f13_arg0.PlayerLimitLabel:setAlpha( 1 )
			f13_local7( f13_arg0.PlayerLimitLabel )
			local f13_local8 = function ( f23_arg0 )
				f13_arg0.PlayerLimitLabelFocus:beginAnimation( 200 )
				f13_arg0.PlayerLimitLabelFocus:setAlpha( 1 )
				f13_arg0.PlayerLimitLabelFocus:registerEventHandler( "interrupted_keyframe", f13_arg0.clipInterrupted )
				f13_arg0.PlayerLimitLabelFocus:registerEventHandler( "transition_complete_keyframe", f13_arg0.clipFinished )
			end
			
			f13_arg0.PlayerLimitLabelFocus:completeAnimation()
			f13_arg0.PlayerLimitLabelFocus:setAlpha( 0 )
			f13_local8( f13_arg0.PlayerLimitLabelFocus )
			local f13_local9 = function ( f24_arg0 )
				f13_arg0.VoiceChatLabel:beginAnimation( 200 )
				f13_arg0.VoiceChatLabel:setAlpha( 0 )
				f13_arg0.VoiceChatLabel:registerEventHandler( "interrupted_keyframe", f13_arg0.clipInterrupted )
				f13_arg0.VoiceChatLabel:registerEventHandler( "transition_complete_keyframe", f13_arg0.clipFinished )
			end
			
			f13_arg0.VoiceChatLabel:completeAnimation()
			f13_arg0.VoiceChatLabel:setAlpha( 1 )
			f13_local9( f13_arg0.VoiceChatLabel )
			local f13_local10 = function ( f25_arg0 )
				f13_arg0.VoiceChatLabelFocus:beginAnimation( 200 )
				f13_arg0.VoiceChatLabelFocus:setAlpha( 1 )
				f13_arg0.VoiceChatLabelFocus:registerEventHandler( "interrupted_keyframe", f13_arg0.clipInterrupted )
				f13_arg0.VoiceChatLabelFocus:registerEventHandler( "transition_complete_keyframe", f13_arg0.clipFinished )
			end
			
			f13_arg0.VoiceChatLabelFocus:completeAnimation()
			f13_arg0.VoiceChatLabelFocus:setAlpha( 0 )
			f13_local10( f13_arg0.VoiceChatLabelFocus )
			local f13_local11 = function ( f26_arg0 )
				f13_arg0.lockImage:beginAnimation( 200 )
				f13_arg0.lockImage:setScale( 1.2, 1.2 )
				f13_arg0.lockImage:registerEventHandler( "interrupted_keyframe", f13_arg0.clipInterrupted )
				f13_arg0.lockImage:registerEventHandler( "transition_complete_keyframe", f13_arg0.clipFinished )
			end
			
			f13_arg0.lockImage:completeAnimation()
			f13_arg0.lockImage:setScale( 0.6, 0.6 )
			f13_local11( f13_arg0.lockImage )
			local f13_local12 = function ( f27_arg0 )
				f13_arg0.Lines:beginAnimation( 200 )
				f13_arg0.Lines:setAlpha( 0 )
				f13_arg0.Lines:registerEventHandler( "interrupted_keyframe", f13_arg0.clipInterrupted )
				f13_arg0.Lines:registerEventHandler( "transition_complete_keyframe", f13_arg0.clipFinished )
			end
			
			f13_arg0.Lines:completeAnimation()
			f13_arg0.Lines:setAlpha( 1 )
			f13_local12( f13_arg0.Lines )
		end,
		LoseFocus = function ( f28_arg0, f28_arg1 )
			f28_arg0:__resetProperties()
			f28_arg0:setupElementClipCounter( 13 )
			local f28_local0 = function ( f29_arg0 )
				f28_arg0.FocusBrackets:beginAnimation( 60, Enum[0xF50FFF429AB1890][0x53CEB9A0427197] )
				f28_arg0.FocusBrackets:setAlpha( 0 )
				f28_arg0.FocusBrackets:registerEventHandler( "interrupted_keyframe", f28_arg0.clipInterrupted )
				f28_arg0.FocusBrackets:registerEventHandler( "transition_complete_keyframe", f28_arg0.clipFinished )
			end
			
			f28_arg0.FocusBrackets:completeAnimation()
			f28_arg0.FocusBrackets:setLeftRight( 0, 1, -10, 10 )
			f28_arg0.FocusBrackets:setTopBottom( 0, 1, -10, 10 )
			f28_arg0.FocusBrackets:setAlpha( 1 )
			f28_local0( f28_arg0.FocusBrackets )
			local f28_local1 = function ( f30_arg0 )
				f28_arg0.FrontendFrameSelected:beginAnimation( 200, Enum[0xF50FFF429AB1890][0x5193EA7825DC097] )
				f28_arg0.FrontendFrameSelected:setAlpha( 0 )
				f28_arg0.FrontendFrameSelected:registerEventHandler( "interrupted_keyframe", f28_arg0.clipInterrupted )
				f28_arg0.FrontendFrameSelected:registerEventHandler( "transition_complete_keyframe", f28_arg0.clipFinished )
			end
			
			f28_arg0.FrontendFrameSelected:completeAnimation()
			f28_arg0.FrontendFrameSelected:setAlpha( 0.1 )
			f28_local1( f28_arg0.FrontendFrameSelected )
			local f28_local2 = function ( f31_arg0 )
				f28_arg0.FocusGlow:beginAnimation( 200 )
				f28_arg0.FocusGlow:setAlpha( 0 )
				f28_arg0.FocusGlow:registerEventHandler( "interrupted_keyframe", f28_arg0.clipInterrupted )
				f28_arg0.FocusGlow:registerEventHandler( "transition_complete_keyframe", f28_arg0.clipFinished )
			end
			
			f28_arg0.FocusGlow:completeAnimation()
			f28_arg0.FocusGlow:setAlpha( 1 )
			f28_local2( f28_arg0.FocusGlow )
			local f28_local3 = function ( f32_arg0 )
				f28_arg0.FocusHighlight:beginAnimation( 200 )
				f28_arg0.FocusHighlight:setAlpha( 0 )
				f28_arg0.FocusHighlight:registerEventHandler( "interrupted_keyframe", f28_arg0.clipInterrupted )
				f28_arg0.FocusHighlight:registerEventHandler( "transition_complete_keyframe", f28_arg0.clipFinished )
			end
			
			f28_arg0.FocusHighlight:completeAnimation()
			f28_arg0.FocusHighlight:setAlpha( 0.8 )
			f28_local3( f28_arg0.FocusHighlight )
			local f28_local4 = function ( f33_arg0 )
				f28_arg0.DotTiledBacking:beginAnimation( 200 )
				f28_arg0.DotTiledBacking.TiledShaderImage:beginAnimation( 200 )
				f28_arg0.DotTiledBacking.TiledShaderImage:setRGB( 0.22, 0.22, 0.22 )
				f28_arg0.DotTiledBacking:registerEventHandler( "interrupted_keyframe", f28_arg0.clipInterrupted )
				f28_arg0.DotTiledBacking:registerEventHandler( "transition_complete_keyframe", f28_arg0.clipFinished )
			end
			
			f28_arg0.DotTiledBacking:completeAnimation()
			f28_arg0.DotTiledBacking.TiledShaderImage:completeAnimation()
			f28_arg0.DotTiledBacking.TiledShaderImage:setRGB( 0.28, 0.28, 0.28 )
			f28_local4( f28_arg0.DotTiledBacking )
			local f28_local5 = function ( f34_arg0 )
				f28_arg0.PartyPrivacyLabel:beginAnimation( 200 )
				f28_arg0.PartyPrivacyLabel:setAlpha( 1 )
				f28_arg0.PartyPrivacyLabel:registerEventHandler( "interrupted_keyframe", f28_arg0.clipInterrupted )
				f28_arg0.PartyPrivacyLabel:registerEventHandler( "transition_complete_keyframe", f28_arg0.clipFinished )
			end
			
			f28_arg0.PartyPrivacyLabel:completeAnimation()
			f28_arg0.PartyPrivacyLabel:setAlpha( 0 )
			f28_local5( f28_arg0.PartyPrivacyLabel )
			local f28_local6 = function ( f35_arg0 )
				f28_arg0.PartyPrivacyLabelFocus:beginAnimation( 200 )
				f28_arg0.PartyPrivacyLabelFocus:setAlpha( 0 )
				f28_arg0.PartyPrivacyLabelFocus:registerEventHandler( "interrupted_keyframe", f28_arg0.clipInterrupted )
				f28_arg0.PartyPrivacyLabelFocus:registerEventHandler( "transition_complete_keyframe", f28_arg0.clipFinished )
			end
			
			f28_arg0.PartyPrivacyLabelFocus:completeAnimation()
			f28_arg0.PartyPrivacyLabelFocus:setAlpha( 1 )
			f28_local6( f28_arg0.PartyPrivacyLabelFocus )
			local f28_local7 = function ( f36_arg0 )
				f28_arg0.PlayerLimitLabel:beginAnimation( 200 )
				f28_arg0.PlayerLimitLabel:setAlpha( 1 )
				f28_arg0.PlayerLimitLabel:registerEventHandler( "interrupted_keyframe", f28_arg0.clipInterrupted )
				f28_arg0.PlayerLimitLabel:registerEventHandler( "transition_complete_keyframe", f28_arg0.clipFinished )
			end
			
			f28_arg0.PlayerLimitLabel:completeAnimation()
			f28_arg0.PlayerLimitLabel:setAlpha( 0 )
			f28_local7( f28_arg0.PlayerLimitLabel )
			local f28_local8 = function ( f37_arg0 )
				f28_arg0.PlayerLimitLabelFocus:beginAnimation( 200 )
				f28_arg0.PlayerLimitLabelFocus:setAlpha( 0 )
				f28_arg0.PlayerLimitLabelFocus:registerEventHandler( "interrupted_keyframe", f28_arg0.clipInterrupted )
				f28_arg0.PlayerLimitLabelFocus:registerEventHandler( "transition_complete_keyframe", f28_arg0.clipFinished )
			end
			
			f28_arg0.PlayerLimitLabelFocus:completeAnimation()
			f28_arg0.PlayerLimitLabelFocus:setAlpha( 1 )
			f28_local8( f28_arg0.PlayerLimitLabelFocus )
			local f28_local9 = function ( f38_arg0 )
				f28_arg0.VoiceChatLabel:beginAnimation( 200 )
				f28_arg0.VoiceChatLabel:setAlpha( 1 )
				f28_arg0.VoiceChatLabel:registerEventHandler( "interrupted_keyframe", f28_arg0.clipInterrupted )
				f28_arg0.VoiceChatLabel:registerEventHandler( "transition_complete_keyframe", f28_arg0.clipFinished )
			end
			
			f28_arg0.VoiceChatLabel:completeAnimation()
			f28_arg0.VoiceChatLabel:setAlpha( 0 )
			f28_local9( f28_arg0.VoiceChatLabel )
			local f28_local10 = function ( f39_arg0 )
				f28_arg0.VoiceChatLabelFocus:beginAnimation( 200 )
				f28_arg0.VoiceChatLabelFocus:setAlpha( 0 )
				f28_arg0.VoiceChatLabelFocus:registerEventHandler( "interrupted_keyframe", f28_arg0.clipInterrupted )
				f28_arg0.VoiceChatLabelFocus:registerEventHandler( "transition_complete_keyframe", f28_arg0.clipFinished )
			end
			
			f28_arg0.VoiceChatLabelFocus:completeAnimation()
			f28_arg0.VoiceChatLabelFocus:setAlpha( 1 )
			f28_local10( f28_arg0.VoiceChatLabelFocus )
			local f28_local11 = function ( f40_arg0 )
				f28_arg0.lockImage:beginAnimation( 200 )
				f28_arg0.lockImage:setScale( 0.6, 0.6 )
				f28_arg0.lockImage:registerEventHandler( "interrupted_keyframe", f28_arg0.clipInterrupted )
				f28_arg0.lockImage:registerEventHandler( "transition_complete_keyframe", f28_arg0.clipFinished )
			end
			
			f28_arg0.lockImage:completeAnimation()
			f28_arg0.lockImage:setScale( 1.2, 1.2 )
			f28_local11( f28_arg0.lockImage )
			local f28_local12 = function ( f41_arg0 )
				f28_arg0.Lines:beginAnimation( 200 )
				f28_arg0.Lines:setAlpha( 1 )
				f28_arg0.Lines:registerEventHandler( "interrupted_keyframe", f28_arg0.clipInterrupted )
				f28_arg0.Lines:registerEventHandler( "transition_complete_keyframe", f28_arg0.clipFinished )
			end
			
			f28_arg0.Lines:completeAnimation()
			f28_arg0.Lines:setAlpha( 0 )
			f28_local12( f28_arg0.Lines )
		end
	},
	Locked = {
		DefaultClip = function ( f42_arg0, f42_arg1 )
			f42_arg0:__resetProperties()
			f42_arg0:setupElementClipCounter( 6 )
			f42_arg0.NoiseTiledBacking:completeAnimation()
			f42_arg0.NoiseTiledBacking:setRGB( 0.78, 0.78, 0.78 )
			f42_arg0.clipFinished( f42_arg0.NoiseTiledBacking )
			f42_arg0.FocusBrackets:completeAnimation()
			f42_arg0.FocusBrackets:setAlpha( 0 )
			f42_arg0.clipFinished( f42_arg0.FocusBrackets )
			f42_arg0.PartyPrivacyLabel:completeAnimation()
			f42_arg0.PartyPrivacyLabel:setRGB( 0.92, 0.92, 0.92 )
			f42_arg0.PartyPrivacyLabel:setAlpha( 0.2 )
			f42_arg0.clipFinished( f42_arg0.PartyPrivacyLabel )
			f42_arg0.PlayerLimitLabel:completeAnimation()
			f42_arg0.PlayerLimitLabel:setRGB( 0.92, 0.92, 0.92 )
			f42_arg0.PlayerLimitLabel:setAlpha( 0.2 )
			f42_arg0.clipFinished( f42_arg0.PlayerLimitLabel )
			f42_arg0.VoiceChatLabel:completeAnimation()
			f42_arg0.VoiceChatLabel:setRGB( 0.92, 0.92, 0.92 )
			f42_arg0.VoiceChatLabel:setAlpha( 0.2 )
			f42_arg0.clipFinished( f42_arg0.VoiceChatLabel )
			f42_arg0.lockImage:completeAnimation()
			f42_arg0.lockImage:setAlpha( 0.5 )
			f42_arg0.clipFinished( f42_arg0.lockImage )
		end,
		Focus = function ( f43_arg0, f43_arg1 )
			f43_arg0:__resetProperties()
			f43_arg0:setupElementClipCounter( 7 )
			f43_arg0.NoiseTiledBacking:completeAnimation()
			f43_arg0.NoiseTiledBacking:setRGB( 0.78, 0.78, 0.78 )
			f43_arg0.clipFinished( f43_arg0.NoiseTiledBacking )
			f43_arg0.FocusBrackets:completeAnimation()
			f43_arg0.FocusBrackets:setLeftRight( 0, 1, -10, 10 )
			f43_arg0.FocusBrackets:setTopBottom( 0, 1, -10, 10 )
			f43_arg0.FocusBrackets:setAlpha( 1 )
			f43_arg0.clipFinished( f43_arg0.FocusBrackets )
			f43_arg0.PartyPrivacyLabel:completeAnimation()
			f43_arg0.PartyPrivacyLabel:setRGB( 0.92, 0.92, 0.92 )
			f43_arg0.PartyPrivacyLabel:setAlpha( 0.2 )
			f43_arg0.clipFinished( f43_arg0.PartyPrivacyLabel )
			f43_arg0.PlayerLimitLabel:completeAnimation()
			f43_arg0.PlayerLimitLabel:setRGB( 0.92, 0.92, 0.92 )
			f43_arg0.PlayerLimitLabel:setAlpha( 0.2 )
			f43_arg0.clipFinished( f43_arg0.PlayerLimitLabel )
			f43_arg0.VoiceChatLabel:completeAnimation()
			f43_arg0.VoiceChatLabel:setRGB( 0.92, 0.92, 0.92 )
			f43_arg0.VoiceChatLabel:setAlpha( 0.2 )
			f43_arg0.clipFinished( f43_arg0.VoiceChatLabel )
			f43_arg0.lockImage:completeAnimation()
			f43_arg0.lockImage:setAlpha( 0.5 )
			f43_arg0.clipFinished( f43_arg0.lockImage )
			f43_arg0.FocusBorder:completeAnimation()
			f43_arg0.FocusBorder:setRGB( ColorSet.T8__OFF__WHITE.r, ColorSet.T8__OFF__WHITE.g, ColorSet.T8__OFF__WHITE.b )
			f43_arg0.FocusBorder:setAlpha( 0.25 )
			f43_arg0.clipFinished( f43_arg0.FocusBorder )
		end,
		GainFocus = function ( f44_arg0, f44_arg1 )
			f44_arg0:__resetProperties()
			f44_arg0:setupElementClipCounter( 7 )
			f44_arg0.NoiseTiledBacking:completeAnimation()
			f44_arg0.NoiseTiledBacking:setRGB( 0.78, 0.78, 0.78 )
			f44_arg0.clipFinished( f44_arg0.NoiseTiledBacking )
			local f44_local0 = function ( f45_arg0 )
				local f45_local0 = function ( f46_arg0 )
					f46_arg0:beginAnimation( 50, Enum[0xF50FFF429AB1890][0x6F6186B702830BC] )
					f46_arg0:setLeftRight( 0, 1, -10, 10 )
					f46_arg0:setTopBottom( 0, 1, -10, 10 )
					f46_arg0:setAlpha( 1 )
					f46_arg0:registerEventHandler( "transition_complete_keyframe", f44_arg0.clipFinished )
				end
				
				f44_arg0.FocusBrackets:beginAnimation( 100 )
				f44_arg0.FocusBrackets:setLeftRight( 0, 1, -8, 8 )
				f44_arg0.FocusBrackets:setTopBottom( 0, 1, -8, 8 )
				f44_arg0.FocusBrackets:setAlpha( 0.75 )
				f44_arg0.FocusBrackets:registerEventHandler( "interrupted_keyframe", f44_arg0.clipInterrupted )
				f44_arg0.FocusBrackets:registerEventHandler( "transition_complete_keyframe", f45_local0 )
			end
			
			f44_arg0.FocusBrackets:completeAnimation()
			f44_arg0.FocusBrackets:setLeftRight( 0, 1, -40, 40 )
			f44_arg0.FocusBrackets:setTopBottom( 0, 1, -40, 40 )
			f44_arg0.FocusBrackets:setAlpha( 0 )
			f44_local0( f44_arg0.FocusBrackets )
			f44_arg0.PartyPrivacyLabel:completeAnimation()
			f44_arg0.PartyPrivacyLabel:setRGB( 0.92, 0.92, 0.92 )
			f44_arg0.PartyPrivacyLabel:setAlpha( 0.2 )
			f44_arg0.clipFinished( f44_arg0.PartyPrivacyLabel )
			f44_arg0.PlayerLimitLabel:completeAnimation()
			f44_arg0.PlayerLimitLabel:setRGB( 0.92, 0.92, 0.92 )
			f44_arg0.PlayerLimitLabel:setAlpha( 0.2 )
			f44_arg0.clipFinished( f44_arg0.PlayerLimitLabel )
			f44_arg0.VoiceChatLabel:completeAnimation()
			f44_arg0.VoiceChatLabel:setRGB( 0.92, 0.92, 0.92 )
			f44_arg0.VoiceChatLabel:setAlpha( 0.2 )
			f44_arg0.clipFinished( f44_arg0.VoiceChatLabel )
			f44_arg0.lockImage:completeAnimation()
			f44_arg0.lockImage:setAlpha( 0.5 )
			f44_arg0.clipFinished( f44_arg0.lockImage )
			local f44_local1 = function ( f47_arg0 )
				f44_arg0.FocusBorder:beginAnimation( 200 )
				f44_arg0.FocusBorder:setAlpha( 0.25 )
				f44_arg0.FocusBorder:registerEventHandler( "interrupted_keyframe", f44_arg0.clipInterrupted )
				f44_arg0.FocusBorder:registerEventHandler( "transition_complete_keyframe", f44_arg0.clipFinished )
			end
			
			f44_arg0.FocusBorder:completeAnimation()
			f44_arg0.FocusBorder:setRGB( ColorSet.T8__OFF__WHITE.r, ColorSet.T8__OFF__WHITE.g, ColorSet.T8__OFF__WHITE.b )
			f44_arg0.FocusBorder:setAlpha( 0 )
			f44_local1( f44_arg0.FocusBorder )
		end,
		LoseFocus = function ( f48_arg0, f48_arg1 )
			f48_arg0:__resetProperties()
			f48_arg0:setupElementClipCounter( 7 )
			f48_arg0.NoiseTiledBacking:completeAnimation()
			f48_arg0.NoiseTiledBacking:setRGB( 0.78, 0.78, 0.78 )
			f48_arg0.clipFinished( f48_arg0.NoiseTiledBacking )
			local f48_local0 = function ( f49_arg0 )
				f48_arg0.FocusBrackets:beginAnimation( 60, Enum[0xF50FFF429AB1890][0x53CEB9A0427197] )
				f48_arg0.FocusBrackets:setAlpha( 0 )
				f48_arg0.FocusBrackets:registerEventHandler( "interrupted_keyframe", f48_arg0.clipInterrupted )
				f48_arg0.FocusBrackets:registerEventHandler( "transition_complete_keyframe", f48_arg0.clipFinished )
			end
			
			f48_arg0.FocusBrackets:completeAnimation()
			f48_arg0.FocusBrackets:setLeftRight( 0, 1, -10, 10 )
			f48_arg0.FocusBrackets:setTopBottom( 0, 1, -10, 10 )
			f48_arg0.FocusBrackets:setAlpha( 1 )
			f48_local0( f48_arg0.FocusBrackets )
			f48_arg0.PartyPrivacyLabel:completeAnimation()
			f48_arg0.PartyPrivacyLabel:setRGB( 0.92, 0.92, 0.92 )
			f48_arg0.PartyPrivacyLabel:setAlpha( 0.2 )
			f48_arg0.clipFinished( f48_arg0.PartyPrivacyLabel )
			f48_arg0.PlayerLimitLabel:completeAnimation()
			f48_arg0.PlayerLimitLabel:setRGB( 0.92, 0.92, 0.92 )
			f48_arg0.PlayerLimitLabel:setAlpha( 0.2 )
			f48_arg0.clipFinished( f48_arg0.PlayerLimitLabel )
			f48_arg0.VoiceChatLabel:completeAnimation()
			f48_arg0.VoiceChatLabel:setRGB( 0.92, 0.92, 0.92 )
			f48_arg0.VoiceChatLabel:setAlpha( 0.2 )
			f48_arg0.clipFinished( f48_arg0.VoiceChatLabel )
			f48_arg0.lockImage:completeAnimation()
			f48_arg0.lockImage:setAlpha( 0.5 )
			f48_arg0.clipFinished( f48_arg0.lockImage )
			local f48_local1 = function ( f50_arg0 )
				f48_arg0.FocusBorder:beginAnimation( 200 )
				f48_arg0.FocusBorder:setAlpha( 0 )
				f48_arg0.FocusBorder:registerEventHandler( "interrupted_keyframe", f48_arg0.clipInterrupted )
				f48_arg0.FocusBorder:registerEventHandler( "transition_complete_keyframe", f48_arg0.clipFinished )
			end
			
			f48_arg0.FocusBorder:completeAnimation()
			f48_arg0.FocusBorder:setRGB( ColorSet.T8__OFF__WHITE.r, ColorSet.T8__OFF__WHITE.g, ColorSet.T8__OFF__WHITE.b )
			f48_arg0.FocusBorder:setAlpha( 0.25 )
			f48_local1( f48_arg0.FocusBorder )
		end
	},
	Disabled = {
		DefaultClip = function ( f51_arg0, f51_arg1 )
			f51_arg0:__resetProperties()
			f51_arg0:setupElementClipCounter( 7 )
			f51_arg0.FocusBrackets:completeAnimation()
			f51_arg0.FocusBrackets:setAlpha( 0 )
			f51_arg0.clipFinished( f51_arg0.FocusBrackets )
			f51_arg0.PartyPrivacyLabel:completeAnimation()
			f51_arg0.PartyPrivacyLabel:setRGB( 0.31, 0.29, 0.29 )
			f51_arg0.clipFinished( f51_arg0.PartyPrivacyLabel )
			f51_arg0.PlayerLimitLabel:completeAnimation()
			f51_arg0.PlayerLimitLabel:setRGB( 0.31, 0.29, 0.29 )
			f51_arg0.clipFinished( f51_arg0.PlayerLimitLabel )
			f51_arg0.VoiceChatLabel:completeAnimation()
			f51_arg0.VoiceChatLabel:setRGB( 0.31, 0.29, 0.29 )
			f51_arg0.clipFinished( f51_arg0.VoiceChatLabel )
			f51_arg0.lockImage:completeAnimation()
			f51_arg0.lockImage:setScale( 1.2, 1.2 )
			f51_arg0.clipFinished( f51_arg0.lockImage )
			f51_arg0.Lines:completeAnimation()
			f51_arg0.Lines:setAlpha( 0.5 )
			f51_arg0.clipFinished( f51_arg0.Lines )
			f51_arg0.FocusBorder:completeAnimation()
			f51_arg0.FocusBorder:setRGB( ColorSet.T8__OFF__WHITE.r, ColorSet.T8__OFF__WHITE.g, ColorSet.T8__OFF__WHITE.b )
			f51_arg0.clipFinished( f51_arg0.FocusBorder )
		end,
		Focus = function ( f52_arg0, f52_arg1 )
			f52_arg0:__resetProperties()
			f52_arg0:setupElementClipCounter( 7 )
			f52_arg0.FocusBrackets:completeAnimation()
			f52_arg0.FocusBrackets:setLeftRight( 0, 1, -10, 10 )
			f52_arg0.FocusBrackets:setTopBottom( 0, 1, -10, 10 )
			f52_arg0.FocusBrackets:setAlpha( 1 )
			f52_arg0.clipFinished( f52_arg0.FocusBrackets )
			f52_arg0.PartyPrivacyLabel:completeAnimation()
			f52_arg0.PartyPrivacyLabel:setRGB( 0.31, 0.29, 0.29 )
			f52_arg0.clipFinished( f52_arg0.PartyPrivacyLabel )
			f52_arg0.PlayerLimitLabel:completeAnimation()
			f52_arg0.PlayerLimitLabel:setRGB( 0.31, 0.29, 0.29 )
			f52_arg0.clipFinished( f52_arg0.PlayerLimitLabel )
			f52_arg0.VoiceChatLabel:completeAnimation()
			f52_arg0.VoiceChatLabel:setRGB( 0.31, 0.29, 0.29 )
			f52_arg0.clipFinished( f52_arg0.VoiceChatLabel )
			f52_arg0.lockImage:completeAnimation()
			f52_arg0.lockImage:setScale( 1.2, 1.2 )
			f52_arg0.clipFinished( f52_arg0.lockImage )
			f52_arg0.Lines:completeAnimation()
			f52_arg0.Lines:setAlpha( 0.5 )
			f52_arg0.clipFinished( f52_arg0.Lines )
			f52_arg0.FocusBorder:completeAnimation()
			f52_arg0.FocusBorder:setRGB( ColorSet.T8__OFF__WHITE.r, ColorSet.T8__OFF__WHITE.g, ColorSet.T8__OFF__WHITE.b )
			f52_arg0.FocusBorder:setAlpha( 0.25 )
			f52_arg0.clipFinished( f52_arg0.FocusBorder )
		end,
		GainFocus = function ( f53_arg0, f53_arg1 )
			f53_arg0:__resetProperties()
			f53_arg0:setupElementClipCounter( 7 )
			local f53_local0 = function ( f54_arg0 )
				local f54_local0 = function ( f55_arg0 )
					f55_arg0:beginAnimation( 50, Enum[0xF50FFF429AB1890][0x6F6186B702830BC] )
					f55_arg0:setLeftRight( 0, 1, -10, 10 )
					f55_arg0:setTopBottom( 0, 1, -10, 10 )
					f55_arg0:setAlpha( 1 )
					f55_arg0:registerEventHandler( "transition_complete_keyframe", f53_arg0.clipFinished )
				end
				
				f53_arg0.FocusBrackets:beginAnimation( 100 )
				f53_arg0.FocusBrackets:setLeftRight( 0, 1, -8, 8 )
				f53_arg0.FocusBrackets:setTopBottom( 0, 1, -8, 8 )
				f53_arg0.FocusBrackets:setAlpha( 0.75 )
				f53_arg0.FocusBrackets:registerEventHandler( "interrupted_keyframe", f53_arg0.clipInterrupted )
				f53_arg0.FocusBrackets:registerEventHandler( "transition_complete_keyframe", f54_local0 )
			end
			
			f53_arg0.FocusBrackets:completeAnimation()
			f53_arg0.FocusBrackets:setLeftRight( 0, 1, -40, 40 )
			f53_arg0.FocusBrackets:setTopBottom( 0, 1, -40, 40 )
			f53_arg0.FocusBrackets:setAlpha( 0 )
			f53_local0( f53_arg0.FocusBrackets )
			f53_arg0.PartyPrivacyLabel:completeAnimation()
			f53_arg0.PartyPrivacyLabel:setRGB( 0.31, 0.29, 0.29 )
			f53_arg0.clipFinished( f53_arg0.PartyPrivacyLabel )
			f53_arg0.PlayerLimitLabel:completeAnimation()
			f53_arg0.PlayerLimitLabel:setRGB( 0.31, 0.29, 0.29 )
			f53_arg0.clipFinished( f53_arg0.PlayerLimitLabel )
			f53_arg0.VoiceChatLabel:completeAnimation()
			f53_arg0.VoiceChatLabel:setRGB( 0.31, 0.29, 0.29 )
			f53_arg0.clipFinished( f53_arg0.VoiceChatLabel )
			f53_arg0.lockImage:completeAnimation()
			f53_arg0.lockImage:setScale( 1.2, 1.2 )
			f53_arg0.clipFinished( f53_arg0.lockImage )
			f53_arg0.Lines:completeAnimation()
			f53_arg0.Lines:setAlpha( 0.5 )
			f53_arg0.clipFinished( f53_arg0.Lines )
			local f53_local1 = function ( f56_arg0 )
				f53_arg0.FocusBorder:beginAnimation( 200 )
				f53_arg0.FocusBorder:setAlpha( 0.25 )
				f53_arg0.FocusBorder:registerEventHandler( "interrupted_keyframe", f53_arg0.clipInterrupted )
				f53_arg0.FocusBorder:registerEventHandler( "transition_complete_keyframe", f53_arg0.clipFinished )
			end
			
			f53_arg0.FocusBorder:completeAnimation()
			f53_arg0.FocusBorder:setRGB( ColorSet.T8__OFF__WHITE.r, ColorSet.T8__OFF__WHITE.g, ColorSet.T8__OFF__WHITE.b )
			f53_arg0.FocusBorder:setAlpha( 0 )
			f53_local1( f53_arg0.FocusBorder )
		end,
		LoseFocus = function ( f57_arg0, f57_arg1 )
			f57_arg0:__resetProperties()
			f57_arg0:setupElementClipCounter( 7 )
			local f57_local0 = function ( f58_arg0 )
				f57_arg0.FocusBrackets:beginAnimation( 60 )
				f57_arg0.FocusBrackets:setAlpha( 0 )
				f57_arg0.FocusBrackets:registerEventHandler( "interrupted_keyframe", f57_arg0.clipInterrupted )
				f57_arg0.FocusBrackets:registerEventHandler( "transition_complete_keyframe", f57_arg0.clipFinished )
			end
			
			f57_arg0.FocusBrackets:completeAnimation()
			f57_arg0.FocusBrackets:setLeftRight( 0, 1, -10, 10 )
			f57_arg0.FocusBrackets:setTopBottom( 0, 1, -10, 10 )
			f57_arg0.FocusBrackets:setAlpha( 1 )
			f57_local0( f57_arg0.FocusBrackets )
			f57_arg0.PartyPrivacyLabel:completeAnimation()
			f57_arg0.PartyPrivacyLabel:setRGB( 0.31, 0.29, 0.29 )
			f57_arg0.clipFinished( f57_arg0.PartyPrivacyLabel )
			f57_arg0.PlayerLimitLabel:completeAnimation()
			f57_arg0.PlayerLimitLabel:setRGB( 0.31, 0.29, 0.29 )
			f57_arg0.clipFinished( f57_arg0.PlayerLimitLabel )
			f57_arg0.VoiceChatLabel:completeAnimation()
			f57_arg0.VoiceChatLabel:setRGB( 0.31, 0.29, 0.29 )
			f57_arg0.clipFinished( f57_arg0.VoiceChatLabel )
			f57_arg0.lockImage:completeAnimation()
			f57_arg0.lockImage:setScale( 1.2, 1.2 )
			f57_arg0.clipFinished( f57_arg0.lockImage )
			f57_arg0.Lines:completeAnimation()
			f57_arg0.Lines:setAlpha( 0.5 )
			f57_arg0.clipFinished( f57_arg0.Lines )
			local f57_local1 = function ( f59_arg0 )
				f57_arg0.FocusBorder:beginAnimation( 200 )
				f57_arg0.FocusBorder:setAlpha( 0 )
				f57_arg0.FocusBorder:registerEventHandler( "interrupted_keyframe", f57_arg0.clipInterrupted )
				f57_arg0.FocusBorder:registerEventHandler( "transition_complete_keyframe", f57_arg0.clipFinished )
			end
			
			f57_arg0.FocusBorder:completeAnimation()
			f57_arg0.FocusBorder:setRGB( ColorSet.T8__OFF__WHITE.r, ColorSet.T8__OFF__WHITE.g, ColorSet.T8__OFF__WHITE.b )
			f57_arg0.FocusBorder:setAlpha( 0.25 )
			f57_local1( f57_arg0.FocusBorder )
		end
	}
}
CoD.Social_PartySettingsButtonInternal.__onClose = function ( f60_arg0 )
	f60_arg0.FocusBrackets:close()
	f60_arg0.DotTiledBacking:close()
	f60_arg0.PartyPrivacyLabel:close()
	f60_arg0.PartyPrivacyLabelFocus:close()
	f60_arg0.PlayerLimitLabel:close()
	f60_arg0.PlayerLimitLabelFocus:close()
	f60_arg0.VoiceChatLabel:close()
	f60_arg0.VoiceChatLabelFocus:close()
	f60_arg0.Lines:close()
end

