require( "ui/uieditor/widgets/cac/cac_lock" )
require( "ui/uieditor/widgets/commonbuttonoutline" )
require( "ui/uieditor/widgets/startmenu/startmenu_identity_subtitle" )
require( "ui/uieditor/widgets/startmenu/startmenu_imagecontainer" )
require( "ui/uieditor/widgets/store/storecommontextbacking" )
require( "x64:8934f9ff766bd56" )

CoD.StartMenu_Button_Hero_Internal = InheritFrom( LUI.UIElement )
CoD.StartMenu_Button_Hero_Internal.__defaultWidth = 1096
CoD.StartMenu_Button_Hero_Internal.__defaultHeight = 492
CoD.StartMenu_Button_Hero_Internal.new = function ( f1_arg0, f1_arg1, f1_arg2, f1_arg3, f1_arg4, f1_arg5, f1_arg6, f1_arg7, f1_arg8, f1_arg9 )
	local self = LUI.UIElement.new( f1_arg2, f1_arg3, f1_arg4, f1_arg5, f1_arg6, f1_arg7, f1_arg8, f1_arg9 )
	self:setClass( CoD.StartMenu_Button_Hero_Internal )
	self.id = "StartMenu_Button_Hero_Internal"
	self.soundSet = "default"
	self.onlyChildrenFocusable = true
	self.anyChildUsesUpdateState = true
	f1_arg0:addElementToPendingUpdateStateList( self )
	
	local Background = LUI.UIImage.new( 0, 1, 0, 0, 0, 1, 0, 0 )
	Background:setRGB( 0.92, 0.92, 0.92 )
	Background:setAlpha( 0.04 )
	self:addElement( Background )
	self.Background = Background
	
	local NoiseTiledBacking2 = LUI.UIImage.new( 0, 1, 0, 0, 0, 1, 0, 0 )
	NoiseTiledBacking2:setAlpha( 0.5 )
	NoiseTiledBacking2:setImage( RegisterImage( 0x34839E8065B1E53 ) )
	NoiseTiledBacking2:setMaterial( LUI.UIImage.GetCachedMaterial( 0x6CBE95C250C6D15 ) )
	NoiseTiledBacking2:setShaderVector( 0, 0, 0, 0, 0 )
	NoiseTiledBacking2:setupNineSliceShader( 196, 88 )
	self:addElement( NoiseTiledBacking2 )
	self.NoiseTiledBacking2 = NoiseTiledBacking2
	
	local NoiseTiledBackingAdd = LUI.UIImage.new( 0, 1, 0, 0, 0, 1, 0, 0 )
	NoiseTiledBackingAdd:setAlpha( 0.2 )
	NoiseTiledBackingAdd:setImage( RegisterImage( 0x34839E8065B1E53 ) )
	NoiseTiledBackingAdd:setMaterial( LUI.UIImage.GetCachedMaterial( 0x7C9C02F608D0A75 ) )
	NoiseTiledBackingAdd:setShaderVector( 0, 0, 0, 0, 0 )
	NoiseTiledBackingAdd:setupNineSliceShader( 196, 88 )
	self:addElement( NoiseTiledBackingAdd )
	self.NoiseTiledBackingAdd = NoiseTiledBackingAdd
	
	local imageContainer = CoD.StartMenu_ImageContainer.new( f1_arg0, f1_arg1, 0, 1, 3, -3, 0, 1, 3, -3 )
	imageContainer.ImageContainer:setImage( RegisterImage( 0x1FC34D13866A712 ) )
	self:addElement( imageContainer )
	self.imageContainer = imageContainer
	
	local Title = LUI.UIText.new( 0, 0, 19, 1065, 1, 1, -35, -5 )
	Title:setText( Engine[0xF9F1239CFD921FE]( 0x55D96CC762EABDD ) )
	Title:setTTF( "dinnext_regular" )
	Title:setLetterSpacing( 0.5 )
	Title:setAlignment( Enum.LUIAlignment[0x58C8A85F2048829] )
	Title:setAlignment( Enum.LUIAlignment[0xF41D595A2B0EDF3] )
	self:addElement( Title )
	self.Title = Title
	
	local Subtitle = CoD.StartMenu_Identity_SubTitle.new( f1_arg0, f1_arg1, 0, 0, 8, 1076, 0, 0, 0.5, 39.5 )
	Subtitle:setRGB( 0.92, 0.92, 0.92 )
	Subtitle.SubtitleText:setText( Engine[0xF9F1239CFD921FE]( 0x91415DF8989B05E ) )
	self:addElement( Subtitle )
	self.Subtitle = Subtitle
	
	local LOCKBlackboxBG = LUI.UIImage.new( 0, 1, 2, -2, 0, 1, 4, -4 )
	LOCKBlackboxBG:setRGB( 0, 0, 0 )
	LOCKBlackboxBG:setAlpha( 0 )
	self:addElement( LOCKBlackboxBG )
	self.LOCKBlackboxBG = LOCKBlackboxBG
	
	local DotTiledBacking = CoD.StoreCommonTextBacking.new( f1_arg0, f1_arg1, 0, 1, 0, 0, 0.5, 0.5, -24, 24 )
	DotTiledBacking:setAlpha( 0.2 )
	self:addElement( DotTiledBacking )
	self.DotTiledBacking = DotTiledBacking
	
	local TitleBgTexture = LUI.UIImage.new( 0, 1, 0, 0, 0.5, 0.5, -24.5, 24.5 )
	TitleBgTexture:setAlpha( 0.5 )
	TitleBgTexture:setImage( RegisterImage( 0x34839E8065B1E53 ) )
	TitleBgTexture:setMaterial( LUI.UIImage.GetCachedMaterial( 0x6CBE95C250C6D15 ) )
	TitleBgTexture:setShaderVector( 0, 0, 0, 0, 0 )
	TitleBgTexture:setupNineSliceShader( 196, 88 )
	self:addElement( TitleBgTexture )
	self.TitleBgTexture = TitleBgTexture
	
	local BlackLine = LUI.UIImage.new( 0, 1, 0, 0, 0.5, 0.5, -24.5, 24.5 )
	BlackLine:setRGB( 0, 0, 0 )
	BlackLine:setAlpha( 0.05 )
	self:addElement( BlackLine )
	self.BlackLine = BlackLine
	
	local ButtonStateText = LUI.UIText.new( 0, 1, 0, 0, 0.5, 0.5, -18.5, 18.5 )
	ButtonStateText:setRGB( 0.92, 0.92, 0.92 )
	ButtonStateText:setAlpha( 0.5 )
	ButtonStateText:setText( LocalizeToUpperString( 0x496C6F3083248E7 ) )
	ButtonStateText:setTTF( "ttmussels_regular" )
	ButtonStateText:setLetterSpacing( 4 )
	ButtonStateText:setAlignment( Enum.LUIAlignment[0xFEEB12BCB0D7041] )
	self:addElement( ButtonStateText )
	self.ButtonStateText = ButtonStateText
	
	local lockedIcon = CoD.cac_lock.new( f1_arg0, f1_arg1, 0.5, 0.5, -24, 24, 0.5, 0.5, -24, 24 )
	lockedIcon:setScale( 1.5, 1.5 )
	lockedIcon.lockedIcon:setAlpha( 0.5 )
	self:addElement( lockedIcon )
	self.lockedIcon = lockedIcon
	
	local ButtonOutline = CoD.CommonButtonOutline.new( f1_arg0, f1_arg1, 0, 1, 0, 0, 0, 1, 0, 0 )
	self:addElement( ButtonOutline )
	self.ButtonOutline = ButtonOutline
	
	local TrialUpsellMessage = CoD.TrialUpsellMessage.new( f1_arg0, f1_arg1, 0.5, 0.5, -250, 250, 0.5, 0.5, -20, 20 )
	TrialUpsellMessage:setAlpha( 0 )
	TrialUpsellMessage.Message:setText( LocalizeToUpperString( 0x7098DED77401946 ) )
	self:addElement( TrialUpsellMessage )
	self.TrialUpsellMessage = TrialUpsellMessage
	
	ButtonOutline.id = "ButtonOutline"
	self.__defaultFocus = ButtonOutline
	LUI.OverrideFunction_CallOriginalSecond( self, "close", self.__onClose )
	
	if PostLoadFunc then
		PostLoadFunc( self, f1_arg1, f1_arg0 )
	end
	
	return self
end

CoD.StartMenu_Button_Hero_Internal.__resetProperties = function ( f2_arg0 )
	f2_arg0.lockedIcon:completeAnimation()
	f2_arg0.imageContainer:completeAnimation()
	f2_arg0.BlackLine:completeAnimation()
	f2_arg0.ButtonStateText:completeAnimation()
	f2_arg0.TitleBgTexture:completeAnimation()
	f2_arg0.DotTiledBacking:completeAnimation()
	f2_arg0.NoiseTiledBackingAdd:completeAnimation()
	f2_arg0.LOCKBlackboxBG:completeAnimation()
	f2_arg0.Subtitle:completeAnimation()
	f2_arg0.TrialUpsellMessage:completeAnimation()
	f2_arg0.lockedIcon:setAlpha( 1 )
	f2_arg0.imageContainer.ImageContainer:setAlpha( 1 )
	f2_arg0.BlackLine:setAlpha( 0.05 )
	f2_arg0.ButtonStateText:setTopBottom( 0.5, 0.5, -18.5, 18.5 )
	f2_arg0.ButtonStateText:setRGB( 0.92, 0.92, 0.92 )
	f2_arg0.ButtonStateText:setAlpha( 0.5 )
	f2_arg0.ButtonStateText:setText( LocalizeToUpperString( 0x496C6F3083248E7 ) )
	f2_arg0.TitleBgTexture:setAlpha( 0.5 )
	f2_arg0.DotTiledBacking:setAlpha( 0.2 )
	f2_arg0.NoiseTiledBackingAdd:setAlpha( 0.2 )
	f2_arg0.LOCKBlackboxBG:setAlpha( 0 )
	f2_arg0.Subtitle:setAlpha( 1 )
	f2_arg0.TrialUpsellMessage:setAlpha( 0 )
end

CoD.StartMenu_Button_Hero_Internal.__clipsPerState = {
	DefaultState = {
		DefaultClip = function ( f3_arg0, f3_arg1 )
			f3_arg0:__resetProperties()
			f3_arg0:setupElementClipCounter( 6 )
			f3_arg0.imageContainer:completeAnimation()
			f3_arg0.imageContainer.ImageContainer:completeAnimation()
			f3_arg0.imageContainer.ImageContainer:setAlpha( 0.79 )
			f3_arg0.clipFinished( f3_arg0.imageContainer )
			f3_arg0.DotTiledBacking:completeAnimation()
			f3_arg0.DotTiledBacking:setAlpha( 0 )
			f3_arg0.clipFinished( f3_arg0.DotTiledBacking )
			f3_arg0.TitleBgTexture:completeAnimation()
			f3_arg0.TitleBgTexture:setAlpha( 0 )
			f3_arg0.clipFinished( f3_arg0.TitleBgTexture )
			f3_arg0.BlackLine:completeAnimation()
			f3_arg0.BlackLine:setAlpha( 0 )
			f3_arg0.clipFinished( f3_arg0.BlackLine )
			f3_arg0.ButtonStateText:completeAnimation()
			f3_arg0.ButtonStateText:setAlpha( 0 )
			f3_arg0.clipFinished( f3_arg0.ButtonStateText )
			f3_arg0.lockedIcon:completeAnimation()
			f3_arg0.lockedIcon:setAlpha( 0 )
			f3_arg0.clipFinished( f3_arg0.lockedIcon )
		end,
		ChildFocus = function ( f4_arg0, f4_arg1 )
			f4_arg0:__resetProperties()
			f4_arg0:setupElementClipCounter( 6 )
			f4_arg0.NoiseTiledBackingAdd:completeAnimation()
			f4_arg0.NoiseTiledBackingAdd:setAlpha( 0.5 )
			f4_arg0.clipFinished( f4_arg0.NoiseTiledBackingAdd )
			f4_arg0.DotTiledBacking:completeAnimation()
			f4_arg0.DotTiledBacking:setAlpha( 0 )
			f4_arg0.clipFinished( f4_arg0.DotTiledBacking )
			f4_arg0.TitleBgTexture:completeAnimation()
			f4_arg0.TitleBgTexture:setAlpha( 0 )
			f4_arg0.clipFinished( f4_arg0.TitleBgTexture )
			f4_arg0.BlackLine:completeAnimation()
			f4_arg0.BlackLine:setAlpha( 0 )
			f4_arg0.clipFinished( f4_arg0.BlackLine )
			f4_arg0.ButtonStateText:completeAnimation()
			f4_arg0.ButtonStateText:setAlpha( 0 )
			f4_arg0.clipFinished( f4_arg0.ButtonStateText )
			f4_arg0.lockedIcon:completeAnimation()
			f4_arg0.lockedIcon:setAlpha( 0 )
			f4_arg0.clipFinished( f4_arg0.lockedIcon )
		end,
		GainChildFocus = function ( f5_arg0, f5_arg1 )
			f5_arg0:__resetProperties()
			f5_arg0:setupElementClipCounter( 7 )
			local f5_local0 = function ( f6_arg0 )
				f5_arg0.NoiseTiledBackingAdd:beginAnimation( 150 )
				f5_arg0.NoiseTiledBackingAdd:setAlpha( 0.5 )
				f5_arg0.NoiseTiledBackingAdd:registerEventHandler( "interrupted_keyframe", f5_arg0.clipInterrupted )
				f5_arg0.NoiseTiledBackingAdd:registerEventHandler( "transition_complete_keyframe", f5_arg0.clipFinished )
			end
			
			f5_arg0.NoiseTiledBackingAdd:completeAnimation()
			f5_arg0.NoiseTiledBackingAdd:setAlpha( 0.2 )
			f5_local0( f5_arg0.NoiseTiledBackingAdd )
			local f5_local1 = function ( f7_arg0 )
				f5_arg0.imageContainer:beginAnimation( 150 )
				f5_arg0.imageContainer.ImageContainer:beginAnimation( 150 )
				f5_arg0.imageContainer.ImageContainer:setAlpha( 1 )
				f5_arg0.imageContainer:registerEventHandler( "interrupted_keyframe", f5_arg0.clipInterrupted )
				f5_arg0.imageContainer:registerEventHandler( "transition_complete_keyframe", f5_arg0.clipFinished )
			end
			
			f5_arg0.imageContainer:completeAnimation()
			f5_arg0.imageContainer.ImageContainer:completeAnimation()
			f5_arg0.imageContainer.ImageContainer:setAlpha( 0.79 )
			f5_local1( f5_arg0.imageContainer )
			f5_arg0.DotTiledBacking:completeAnimation()
			f5_arg0.DotTiledBacking:setAlpha( 0 )
			f5_arg0.clipFinished( f5_arg0.DotTiledBacking )
			f5_arg0.TitleBgTexture:completeAnimation()
			f5_arg0.TitleBgTexture:setAlpha( 0 )
			f5_arg0.clipFinished( f5_arg0.TitleBgTexture )
			f5_arg0.BlackLine:completeAnimation()
			f5_arg0.BlackLine:setAlpha( 0 )
			f5_arg0.clipFinished( f5_arg0.BlackLine )
			f5_arg0.ButtonStateText:completeAnimation()
			f5_arg0.ButtonStateText:setAlpha( 0 )
			f5_arg0.clipFinished( f5_arg0.ButtonStateText )
			f5_arg0.lockedIcon:completeAnimation()
			f5_arg0.lockedIcon:setAlpha( 0 )
			f5_arg0.clipFinished( f5_arg0.lockedIcon )
		end,
		LoseChildFocus = function ( f8_arg0, f8_arg1 )
			f8_arg0:__resetProperties()
			f8_arg0:setupElementClipCounter( 7 )
			local f8_local0 = function ( f9_arg0 )
				f8_arg0.NoiseTiledBackingAdd:beginAnimation( 150 )
				f8_arg0.NoiseTiledBackingAdd:setAlpha( 0.2 )
				f8_arg0.NoiseTiledBackingAdd:registerEventHandler( "interrupted_keyframe", f8_arg0.clipInterrupted )
				f8_arg0.NoiseTiledBackingAdd:registerEventHandler( "transition_complete_keyframe", f8_arg0.clipFinished )
			end
			
			f8_arg0.NoiseTiledBackingAdd:completeAnimation()
			f8_arg0.NoiseTiledBackingAdd:setAlpha( 0.5 )
			f8_local0( f8_arg0.NoiseTiledBackingAdd )
			local f8_local1 = function ( f10_arg0 )
				f8_arg0.imageContainer:beginAnimation( 150 )
				f8_arg0.imageContainer.ImageContainer:beginAnimation( 150 )
				f8_arg0.imageContainer.ImageContainer:setAlpha( 0.79 )
				f8_arg0.imageContainer:registerEventHandler( "interrupted_keyframe", f8_arg0.clipInterrupted )
				f8_arg0.imageContainer:registerEventHandler( "transition_complete_keyframe", f8_arg0.clipFinished )
			end
			
			f8_arg0.imageContainer:completeAnimation()
			f8_arg0.imageContainer.ImageContainer:completeAnimation()
			f8_arg0.imageContainer.ImageContainer:setAlpha( 1 )
			f8_local1( f8_arg0.imageContainer )
			f8_arg0.DotTiledBacking:completeAnimation()
			f8_arg0.DotTiledBacking:setAlpha( 0 )
			f8_arg0.clipFinished( f8_arg0.DotTiledBacking )
			f8_arg0.TitleBgTexture:completeAnimation()
			f8_arg0.TitleBgTexture:setAlpha( 0 )
			f8_arg0.clipFinished( f8_arg0.TitleBgTexture )
			f8_arg0.BlackLine:completeAnimation()
			f8_arg0.BlackLine:setAlpha( 0 )
			f8_arg0.clipFinished( f8_arg0.BlackLine )
			f8_arg0.ButtonStateText:completeAnimation()
			f8_arg0.ButtonStateText:setAlpha( 0 )
			f8_arg0.clipFinished( f8_arg0.ButtonStateText )
			f8_arg0.lockedIcon:completeAnimation()
			f8_arg0.lockedIcon:setAlpha( 0 )
			f8_arg0.clipFinished( f8_arg0.lockedIcon )
		end
	},
	WZTrialUpsell = {
		DefaultClip = function ( f11_arg0, f11_arg1 )
			f11_arg0:__resetProperties()
			f11_arg0:setupElementClipCounter( 6 )
			f11_arg0.imageContainer:completeAnimation()
			f11_arg0.imageContainer.ImageContainer:completeAnimation()
			f11_arg0.imageContainer.ImageContainer:setAlpha( 0.79 )
			f11_arg0.clipFinished( f11_arg0.imageContainer )
			f11_arg0.Subtitle:completeAnimation()
			f11_arg0.Subtitle:setAlpha( 0.2 )
			f11_arg0.clipFinished( f11_arg0.Subtitle )
			f11_arg0.LOCKBlackboxBG:completeAnimation()
			f11_arg0.LOCKBlackboxBG:setAlpha( 0.1 )
			f11_arg0.clipFinished( f11_arg0.LOCKBlackboxBG )
			f11_arg0.ButtonStateText:completeAnimation()
			f11_arg0.ButtonStateText:setAlpha( 0 )
			f11_arg0.clipFinished( f11_arg0.ButtonStateText )
			f11_arg0.lockedIcon:completeAnimation()
			f11_arg0.lockedIcon:setAlpha( 0 )
			f11_arg0.clipFinished( f11_arg0.lockedIcon )
			f11_arg0.TrialUpsellMessage:completeAnimation()
			f11_arg0.TrialUpsellMessage:setAlpha( 0.5 )
			f11_arg0.clipFinished( f11_arg0.TrialUpsellMessage )
		end,
		ChildFocus = function ( f12_arg0, f12_arg1 )
			f12_arg0:__resetProperties()
			f12_arg0:setupElementClipCounter( 5 )
			f12_arg0.NoiseTiledBackingAdd:completeAnimation()
			f12_arg0.NoiseTiledBackingAdd:setAlpha( 0.5 )
			f12_arg0.clipFinished( f12_arg0.NoiseTiledBackingAdd )
			f12_arg0.LOCKBlackboxBG:completeAnimation()
			f12_arg0.LOCKBlackboxBG:setAlpha( 0.1 )
			f12_arg0.clipFinished( f12_arg0.LOCKBlackboxBG )
			f12_arg0.ButtonStateText:completeAnimation()
			f12_arg0.ButtonStateText:setTopBottom( 0.5, 0.5, 0, 0 )
			f12_arg0.ButtonStateText:setRGB( 1, 1, 1 )
			f12_arg0.ButtonStateText:setAlpha( 0 )
			f12_arg0.clipFinished( f12_arg0.ButtonStateText )
			f12_arg0.lockedIcon:completeAnimation()
			f12_arg0.lockedIcon:setAlpha( 0 )
			f12_arg0.clipFinished( f12_arg0.lockedIcon )
			f12_arg0.TrialUpsellMessage:completeAnimation()
			f12_arg0.TrialUpsellMessage:setAlpha( 1 )
			f12_arg0.clipFinished( f12_arg0.TrialUpsellMessage )
		end,
		GainChildFocus = function ( f13_arg0, f13_arg1 )
			f13_arg0:__resetProperties()
			f13_arg0:setupElementClipCounter( 6 )
			local f13_local0 = function ( f14_arg0 )
				f13_arg0.NoiseTiledBackingAdd:beginAnimation( 150 )
				f13_arg0.NoiseTiledBackingAdd:setAlpha( 0.5 )
				f13_arg0.NoiseTiledBackingAdd:registerEventHandler( "interrupted_keyframe", f13_arg0.clipInterrupted )
				f13_arg0.NoiseTiledBackingAdd:registerEventHandler( "transition_complete_keyframe", f13_arg0.clipFinished )
			end
			
			f13_arg0.NoiseTiledBackingAdd:completeAnimation()
			f13_arg0.NoiseTiledBackingAdd:setAlpha( 0.2 )
			f13_local0( f13_arg0.NoiseTiledBackingAdd )
			local f13_local1 = function ( f15_arg0 )
				f13_arg0.imageContainer:beginAnimation( 150 )
				f13_arg0.imageContainer.ImageContainer:beginAnimation( 150 )
				f13_arg0.imageContainer.ImageContainer:setAlpha( 1 )
				f13_arg0.imageContainer:registerEventHandler( "interrupted_keyframe", f13_arg0.clipInterrupted )
				f13_arg0.imageContainer:registerEventHandler( "transition_complete_keyframe", f13_arg0.clipFinished )
			end
			
			f13_arg0.imageContainer:completeAnimation()
			f13_arg0.imageContainer.ImageContainer:completeAnimation()
			f13_arg0.imageContainer.ImageContainer:setAlpha( 0.79 )
			f13_local1( f13_arg0.imageContainer )
			f13_arg0.LOCKBlackboxBG:completeAnimation()
			f13_arg0.LOCKBlackboxBG:setAlpha( 0.1 )
			f13_arg0.clipFinished( f13_arg0.LOCKBlackboxBG )
			f13_arg0.ButtonStateText:completeAnimation()
			f13_arg0.ButtonStateText:setRGB( 0.92, 0.92, 0.92 )
			f13_arg0.ButtonStateText:setAlpha( 0 )
			f13_arg0.clipFinished( f13_arg0.ButtonStateText )
			f13_arg0.lockedIcon:completeAnimation()
			f13_arg0.lockedIcon:setAlpha( 0 )
			f13_arg0.clipFinished( f13_arg0.lockedIcon )
			local f13_local2 = function ( f16_arg0 )
				f13_arg0.TrialUpsellMessage:beginAnimation( 150 )
				f13_arg0.TrialUpsellMessage:setAlpha( 1 )
				f13_arg0.TrialUpsellMessage:registerEventHandler( "interrupted_keyframe", f13_arg0.clipInterrupted )
				f13_arg0.TrialUpsellMessage:registerEventHandler( "transition_complete_keyframe", f13_arg0.clipFinished )
			end
			
			f13_arg0.TrialUpsellMessage:completeAnimation()
			f13_arg0.TrialUpsellMessage:setAlpha( 0.5 )
			f13_local2( f13_arg0.TrialUpsellMessage )
		end,
		LoseChildFocus = function ( f17_arg0, f17_arg1 )
			f17_arg0:__resetProperties()
			f17_arg0:setupElementClipCounter( 6 )
			local f17_local0 = function ( f18_arg0 )
				f17_arg0.NoiseTiledBackingAdd:beginAnimation( 150 )
				f17_arg0.NoiseTiledBackingAdd:setAlpha( 0.2 )
				f17_arg0.NoiseTiledBackingAdd:registerEventHandler( "interrupted_keyframe", f17_arg0.clipInterrupted )
				f17_arg0.NoiseTiledBackingAdd:registerEventHandler( "transition_complete_keyframe", f17_arg0.clipFinished )
			end
			
			f17_arg0.NoiseTiledBackingAdd:completeAnimation()
			f17_arg0.NoiseTiledBackingAdd:setAlpha( 0.5 )
			f17_local0( f17_arg0.NoiseTiledBackingAdd )
			local f17_local1 = function ( f19_arg0 )
				f17_arg0.imageContainer:beginAnimation( 150 )
				f17_arg0.imageContainer.ImageContainer:beginAnimation( 150 )
				f17_arg0.imageContainer.ImageContainer:setAlpha( 0.79 )
				f17_arg0.imageContainer:registerEventHandler( "interrupted_keyframe", f17_arg0.clipInterrupted )
				f17_arg0.imageContainer:registerEventHandler( "transition_complete_keyframe", f17_arg0.clipFinished )
			end
			
			f17_arg0.imageContainer:completeAnimation()
			f17_arg0.imageContainer.ImageContainer:completeAnimation()
			f17_arg0.imageContainer.ImageContainer:setAlpha( 1 )
			f17_local1( f17_arg0.imageContainer )
			f17_arg0.LOCKBlackboxBG:completeAnimation()
			f17_arg0.LOCKBlackboxBG:setAlpha( 0.1 )
			f17_arg0.clipFinished( f17_arg0.LOCKBlackboxBG )
			f17_arg0.ButtonStateText:completeAnimation()
			f17_arg0.ButtonStateText:setRGB( 1, 1, 1 )
			f17_arg0.ButtonStateText:setAlpha( 0 )
			f17_arg0.clipFinished( f17_arg0.ButtonStateText )
			f17_arg0.lockedIcon:completeAnimation()
			f17_arg0.lockedIcon:setAlpha( 0 )
			f17_arg0.clipFinished( f17_arg0.lockedIcon )
			local f17_local2 = function ( f20_arg0 )
				f17_arg0.TrialUpsellMessage:beginAnimation( 150 )
				f17_arg0.TrialUpsellMessage:setAlpha( 0.5 )
				f17_arg0.TrialUpsellMessage:registerEventHandler( "interrupted_keyframe", f17_arg0.clipInterrupted )
				f17_arg0.TrialUpsellMessage:registerEventHandler( "transition_complete_keyframe", f17_arg0.clipFinished )
			end
			
			f17_arg0.TrialUpsellMessage:completeAnimation()
			f17_arg0.TrialUpsellMessage:setAlpha( 1 )
			f17_local2( f17_arg0.TrialUpsellMessage )
		end
	},
	Disabled = {
		DefaultClip = function ( f21_arg0, f21_arg1 )
			f21_arg0:__resetProperties()
			f21_arg0:setupElementClipCounter( 8 )
			f21_arg0.imageContainer:completeAnimation()
			f21_arg0.imageContainer.ImageContainer:completeAnimation()
			f21_arg0.imageContainer.ImageContainer:setAlpha( 0.79 )
			f21_arg0.clipFinished( f21_arg0.imageContainer )
			f21_arg0.Subtitle:completeAnimation()
			f21_arg0.Subtitle:setAlpha( 0 )
			f21_arg0.clipFinished( f21_arg0.Subtitle )
			f21_arg0.LOCKBlackboxBG:completeAnimation()
			f21_arg0.LOCKBlackboxBG:setAlpha( 0.1 )
			f21_arg0.clipFinished( f21_arg0.LOCKBlackboxBG )
			f21_arg0.DotTiledBacking:completeAnimation()
			f21_arg0.DotTiledBacking:setAlpha( 0 )
			f21_arg0.clipFinished( f21_arg0.DotTiledBacking )
			f21_arg0.TitleBgTexture:completeAnimation()
			f21_arg0.TitleBgTexture:setAlpha( 0 )
			f21_arg0.clipFinished( f21_arg0.TitleBgTexture )
			f21_arg0.BlackLine:completeAnimation()
			f21_arg0.BlackLine:setAlpha( 0 )
			f21_arg0.clipFinished( f21_arg0.BlackLine )
			f21_arg0.ButtonStateText:completeAnimation()
			f21_arg0.ButtonStateText:setAlpha( 0 )
			f21_arg0.clipFinished( f21_arg0.ButtonStateText )
			f21_arg0.lockedIcon:completeAnimation()
			f21_arg0.lockedIcon:setAlpha( 0.5 )
			f21_arg0.clipFinished( f21_arg0.lockedIcon )
		end
	},
	OnlineOnly = {
		DefaultClip = function ( f22_arg0, f22_arg1 )
			f22_arg0:__resetProperties()
			f22_arg0:setupElementClipCounter( 5 )
			f22_arg0.imageContainer:completeAnimation()
			f22_arg0.imageContainer.ImageContainer:completeAnimation()
			f22_arg0.imageContainer.ImageContainer:setAlpha( 0.79 )
			f22_arg0.clipFinished( f22_arg0.imageContainer )
			f22_arg0.Subtitle:completeAnimation()
			f22_arg0.Subtitle:setAlpha( 0.2 )
			f22_arg0.clipFinished( f22_arg0.Subtitle )
			f22_arg0.LOCKBlackboxBG:completeAnimation()
			f22_arg0.LOCKBlackboxBG:setAlpha( 0.1 )
			f22_arg0.clipFinished( f22_arg0.LOCKBlackboxBG )
			f22_arg0.ButtonStateText:completeAnimation()
			f22_arg0.ButtonStateText:setAlpha( 0.5 )
			f22_arg0.clipFinished( f22_arg0.ButtonStateText )
			f22_arg0.lockedIcon:completeAnimation()
			f22_arg0.lockedIcon:setAlpha( 0 )
			f22_arg0.clipFinished( f22_arg0.lockedIcon )
		end,
		ChildFocus = function ( f23_arg0, f23_arg1 )
			f23_arg0:__resetProperties()
			f23_arg0:setupElementClipCounter( 4 )
			f23_arg0.NoiseTiledBackingAdd:completeAnimation()
			f23_arg0.NoiseTiledBackingAdd:setAlpha( 0.5 )
			f23_arg0.clipFinished( f23_arg0.NoiseTiledBackingAdd )
			f23_arg0.LOCKBlackboxBG:completeAnimation()
			f23_arg0.LOCKBlackboxBG:setAlpha( 0.1 )
			f23_arg0.clipFinished( f23_arg0.LOCKBlackboxBG )
			f23_arg0.ButtonStateText:completeAnimation()
			f23_arg0.ButtonStateText:setRGB( 1, 1, 1 )
			f23_arg0.ButtonStateText:setAlpha( 1 )
			f23_arg0.clipFinished( f23_arg0.ButtonStateText )
			f23_arg0.lockedIcon:completeAnimation()
			f23_arg0.lockedIcon:setAlpha( 0 )
			f23_arg0.clipFinished( f23_arg0.lockedIcon )
		end,
		GainChildFocus = function ( f24_arg0, f24_arg1 )
			f24_arg0:__resetProperties()
			f24_arg0:setupElementClipCounter( 5 )
			local f24_local0 = function ( f25_arg0 )
				f24_arg0.NoiseTiledBackingAdd:beginAnimation( 150 )
				f24_arg0.NoiseTiledBackingAdd:setAlpha( 0.5 )
				f24_arg0.NoiseTiledBackingAdd:registerEventHandler( "interrupted_keyframe", f24_arg0.clipInterrupted )
				f24_arg0.NoiseTiledBackingAdd:registerEventHandler( "transition_complete_keyframe", f24_arg0.clipFinished )
			end
			
			f24_arg0.NoiseTiledBackingAdd:completeAnimation()
			f24_arg0.NoiseTiledBackingAdd:setAlpha( 0.2 )
			f24_local0( f24_arg0.NoiseTiledBackingAdd )
			local f24_local1 = function ( f26_arg0 )
				f24_arg0.imageContainer:beginAnimation( 150 )
				f24_arg0.imageContainer.ImageContainer:beginAnimation( 150 )
				f24_arg0.imageContainer.ImageContainer:setAlpha( 1 )
				f24_arg0.imageContainer:registerEventHandler( "interrupted_keyframe", f24_arg0.clipInterrupted )
				f24_arg0.imageContainer:registerEventHandler( "transition_complete_keyframe", f24_arg0.clipFinished )
			end
			
			f24_arg0.imageContainer:completeAnimation()
			f24_arg0.imageContainer.ImageContainer:completeAnimation()
			f24_arg0.imageContainer.ImageContainer:setAlpha( 0.79 )
			f24_local1( f24_arg0.imageContainer )
			f24_arg0.LOCKBlackboxBG:completeAnimation()
			f24_arg0.LOCKBlackboxBG:setAlpha( 0.1 )
			f24_arg0.clipFinished( f24_arg0.LOCKBlackboxBG )
			local f24_local2 = function ( f27_arg0 )
				f24_arg0.ButtonStateText:beginAnimation( 150 )
				f24_arg0.ButtonStateText:setRGB( 1, 1, 1 )
				f24_arg0.ButtonStateText:setAlpha( 1 )
				f24_arg0.ButtonStateText:registerEventHandler( "interrupted_keyframe", f24_arg0.clipInterrupted )
				f24_arg0.ButtonStateText:registerEventHandler( "transition_complete_keyframe", f24_arg0.clipFinished )
			end
			
			f24_arg0.ButtonStateText:completeAnimation()
			f24_arg0.ButtonStateText:setRGB( 0.92, 0.92, 0.92 )
			f24_arg0.ButtonStateText:setAlpha( 0.5 )
			f24_local2( f24_arg0.ButtonStateText )
			f24_arg0.lockedIcon:completeAnimation()
			f24_arg0.lockedIcon:setAlpha( 0 )
			f24_arg0.clipFinished( f24_arg0.lockedIcon )
		end,
		LoseChildFocus = function ( f28_arg0, f28_arg1 )
			f28_arg0:__resetProperties()
			f28_arg0:setupElementClipCounter( 5 )
			local f28_local0 = function ( f29_arg0 )
				f28_arg0.NoiseTiledBackingAdd:beginAnimation( 150 )
				f28_arg0.NoiseTiledBackingAdd:setAlpha( 0.2 )
				f28_arg0.NoiseTiledBackingAdd:registerEventHandler( "interrupted_keyframe", f28_arg0.clipInterrupted )
				f28_arg0.NoiseTiledBackingAdd:registerEventHandler( "transition_complete_keyframe", f28_arg0.clipFinished )
			end
			
			f28_arg0.NoiseTiledBackingAdd:completeAnimation()
			f28_arg0.NoiseTiledBackingAdd:setAlpha( 0.5 )
			f28_local0( f28_arg0.NoiseTiledBackingAdd )
			local f28_local1 = function ( f30_arg0 )
				f28_arg0.imageContainer:beginAnimation( 150 )
				f28_arg0.imageContainer.ImageContainer:beginAnimation( 150 )
				f28_arg0.imageContainer.ImageContainer:setAlpha( 0.79 )
				f28_arg0.imageContainer:registerEventHandler( "interrupted_keyframe", f28_arg0.clipInterrupted )
				f28_arg0.imageContainer:registerEventHandler( "transition_complete_keyframe", f28_arg0.clipFinished )
			end
			
			f28_arg0.imageContainer:completeAnimation()
			f28_arg0.imageContainer.ImageContainer:completeAnimation()
			f28_arg0.imageContainer.ImageContainer:setAlpha( 1 )
			f28_local1( f28_arg0.imageContainer )
			f28_arg0.LOCKBlackboxBG:completeAnimation()
			f28_arg0.LOCKBlackboxBG:setAlpha( 0.1 )
			f28_arg0.clipFinished( f28_arg0.LOCKBlackboxBG )
			local f28_local2 = function ( f31_arg0 )
				f28_arg0.ButtonStateText:beginAnimation( 150 )
				f28_arg0.ButtonStateText:setRGB( 0.92, 0.92, 0.92 )
				f28_arg0.ButtonStateText:setAlpha( 0.5 )
				f28_arg0.ButtonStateText:registerEventHandler( "interrupted_keyframe", f28_arg0.clipInterrupted )
				f28_arg0.ButtonStateText:registerEventHandler( "transition_complete_keyframe", f28_arg0.clipFinished )
			end
			
			f28_arg0.ButtonStateText:completeAnimation()
			f28_arg0.ButtonStateText:setRGB( 1, 1, 1 )
			f28_arg0.ButtonStateText:setAlpha( 1 )
			f28_local2( f28_arg0.ButtonStateText )
			f28_arg0.lockedIcon:completeAnimation()
			f28_arg0.lockedIcon:setAlpha( 0 )
			f28_arg0.clipFinished( f28_arg0.lockedIcon )
		end
	},
	ComingSoon = {
		DefaultClip = function ( f32_arg0, f32_arg1 )
			f32_arg0:__resetProperties()
			f32_arg0:setupElementClipCounter( 5 )
			f32_arg0.imageContainer:completeAnimation()
			f32_arg0.imageContainer.ImageContainer:completeAnimation()
			f32_arg0.imageContainer.ImageContainer:setAlpha( 0.79 )
			f32_arg0.clipFinished( f32_arg0.imageContainer )
			f32_arg0.Subtitle:completeAnimation()
			f32_arg0.Subtitle:setAlpha( 0.2 )
			f32_arg0.clipFinished( f32_arg0.Subtitle )
			f32_arg0.LOCKBlackboxBG:completeAnimation()
			f32_arg0.LOCKBlackboxBG:setAlpha( 0.1 )
			f32_arg0.clipFinished( f32_arg0.LOCKBlackboxBG )
			f32_arg0.ButtonStateText:completeAnimation()
			f32_arg0.ButtonStateText:setAlpha( 0.5 )
			f32_arg0.ButtonStateText:setText( LocalizeToUpperString( 0x572450D01E06CD6 ) )
			f32_arg0.clipFinished( f32_arg0.ButtonStateText )
			f32_arg0.lockedIcon:completeAnimation()
			f32_arg0.lockedIcon:setAlpha( 0 )
			f32_arg0.clipFinished( f32_arg0.lockedIcon )
		end
	},
	UGCDisabled = {
		DefaultClip = function ( f33_arg0, f33_arg1 )
			f33_arg0:__resetProperties()
			f33_arg0:setupElementClipCounter( 5 )
			f33_arg0.imageContainer:completeAnimation()
			f33_arg0.imageContainer.ImageContainer:completeAnimation()
			f33_arg0.imageContainer.ImageContainer:setAlpha( 0.79 )
			f33_arg0.clipFinished( f33_arg0.imageContainer )
			f33_arg0.Subtitle:completeAnimation()
			f33_arg0.Subtitle:setAlpha( 0.2 )
			f33_arg0.clipFinished( f33_arg0.Subtitle )
			f33_arg0.LOCKBlackboxBG:completeAnimation()
			f33_arg0.LOCKBlackboxBG:setAlpha( 0.1 )
			f33_arg0.clipFinished( f33_arg0.LOCKBlackboxBG )
			f33_arg0.ButtonStateText:completeAnimation()
			f33_arg0.ButtonStateText:setAlpha( 0.5 )
			f33_arg0.ButtonStateText:setText( LocalizeToUpperString( 0xA3DAAD5829AB6E3 ) )
			f33_arg0.clipFinished( f33_arg0.ButtonStateText )
			f33_arg0.lockedIcon:completeAnimation()
			f33_arg0.lockedIcon:setAlpha( 0 )
			f33_arg0.clipFinished( f33_arg0.lockedIcon )
		end,
		ChildFocus = function ( f34_arg0, f34_arg1 )
			f34_arg0:__resetProperties()
			f34_arg0:setupElementClipCounter( 4 )
			f34_arg0.NoiseTiledBackingAdd:completeAnimation()
			f34_arg0.NoiseTiledBackingAdd:setAlpha( 0.5 )
			f34_arg0.clipFinished( f34_arg0.NoiseTiledBackingAdd )
			f34_arg0.LOCKBlackboxBG:completeAnimation()
			f34_arg0.LOCKBlackboxBG:setAlpha( 0.1 )
			f34_arg0.clipFinished( f34_arg0.LOCKBlackboxBG )
			f34_arg0.ButtonStateText:completeAnimation()
			f34_arg0.ButtonStateText:setRGB( 1, 1, 1 )
			f34_arg0.ButtonStateText:setAlpha( 1 )
			f34_arg0.ButtonStateText:setText( LocalizeToUpperString( 0xA3DAAD5829AB6E3 ) )
			f34_arg0.clipFinished( f34_arg0.ButtonStateText )
			f34_arg0.lockedIcon:completeAnimation()
			f34_arg0.lockedIcon:setAlpha( 0 )
			f34_arg0.clipFinished( f34_arg0.lockedIcon )
		end,
		GainChildFocus = function ( f35_arg0, f35_arg1 )
			f35_arg0:__resetProperties()
			f35_arg0:setupElementClipCounter( 5 )
			local f35_local0 = function ( f36_arg0 )
				f35_arg0.NoiseTiledBackingAdd:beginAnimation( 150 )
				f35_arg0.NoiseTiledBackingAdd:setAlpha( 0.5 )
				f35_arg0.NoiseTiledBackingAdd:registerEventHandler( "interrupted_keyframe", f35_arg0.clipInterrupted )
				f35_arg0.NoiseTiledBackingAdd:registerEventHandler( "transition_complete_keyframe", f35_arg0.clipFinished )
			end
			
			f35_arg0.NoiseTiledBackingAdd:completeAnimation()
			f35_arg0.NoiseTiledBackingAdd:setAlpha( 0.2 )
			f35_local0( f35_arg0.NoiseTiledBackingAdd )
			local f35_local1 = function ( f37_arg0 )
				f35_arg0.imageContainer:beginAnimation( 150 )
				f35_arg0.imageContainer.ImageContainer:beginAnimation( 150 )
				f35_arg0.imageContainer.ImageContainer:setAlpha( 1 )
				f35_arg0.imageContainer:registerEventHandler( "interrupted_keyframe", f35_arg0.clipInterrupted )
				f35_arg0.imageContainer:registerEventHandler( "transition_complete_keyframe", f35_arg0.clipFinished )
			end
			
			f35_arg0.imageContainer:completeAnimation()
			f35_arg0.imageContainer.ImageContainer:completeAnimation()
			f35_arg0.imageContainer.ImageContainer:setAlpha( 0.79 )
			f35_local1( f35_arg0.imageContainer )
			f35_arg0.LOCKBlackboxBG:completeAnimation()
			f35_arg0.LOCKBlackboxBG:setAlpha( 0.1 )
			f35_arg0.clipFinished( f35_arg0.LOCKBlackboxBG )
			local f35_local2 = function ( f38_arg0 )
				f35_arg0.ButtonStateText:beginAnimation( 150 )
				f35_arg0.ButtonStateText:setRGB( 1, 1, 1 )
				f35_arg0.ButtonStateText:setAlpha( 1 )
				f35_arg0.ButtonStateText:registerEventHandler( "interrupted_keyframe", f35_arg0.clipInterrupted )
				f35_arg0.ButtonStateText:registerEventHandler( "transition_complete_keyframe", f35_arg0.clipFinished )
			end
			
			f35_arg0.ButtonStateText:completeAnimation()
			f35_arg0.ButtonStateText:setRGB( 0.92, 0.92, 0.92 )
			f35_arg0.ButtonStateText:setAlpha( 0.5 )
			f35_arg0.ButtonStateText:setText( LocalizeToUpperString( 0xA3DAAD5829AB6E3 ) )
			f35_local2( f35_arg0.ButtonStateText )
			f35_arg0.lockedIcon:completeAnimation()
			f35_arg0.lockedIcon:setAlpha( 0 )
			f35_arg0.clipFinished( f35_arg0.lockedIcon )
		end,
		LoseChildFocus = function ( f39_arg0, f39_arg1 )
			f39_arg0:__resetProperties()
			f39_arg0:setupElementClipCounter( 5 )
			local f39_local0 = function ( f40_arg0 )
				f39_arg0.NoiseTiledBackingAdd:beginAnimation( 150 )
				f39_arg0.NoiseTiledBackingAdd:setAlpha( 0.2 )
				f39_arg0.NoiseTiledBackingAdd:registerEventHandler( "interrupted_keyframe", f39_arg0.clipInterrupted )
				f39_arg0.NoiseTiledBackingAdd:registerEventHandler( "transition_complete_keyframe", f39_arg0.clipFinished )
			end
			
			f39_arg0.NoiseTiledBackingAdd:completeAnimation()
			f39_arg0.NoiseTiledBackingAdd:setAlpha( 0.5 )
			f39_local0( f39_arg0.NoiseTiledBackingAdd )
			local f39_local1 = function ( f41_arg0 )
				f39_arg0.imageContainer:beginAnimation( 150 )
				f39_arg0.imageContainer.ImageContainer:beginAnimation( 150 )
				f39_arg0.imageContainer.ImageContainer:setAlpha( 0.79 )
				f39_arg0.imageContainer:registerEventHandler( "interrupted_keyframe", f39_arg0.clipInterrupted )
				f39_arg0.imageContainer:registerEventHandler( "transition_complete_keyframe", f39_arg0.clipFinished )
			end
			
			f39_arg0.imageContainer:completeAnimation()
			f39_arg0.imageContainer.ImageContainer:completeAnimation()
			f39_arg0.imageContainer.ImageContainer:setAlpha( 1 )
			f39_local1( f39_arg0.imageContainer )
			f39_arg0.LOCKBlackboxBG:completeAnimation()
			f39_arg0.LOCKBlackboxBG:setAlpha( 0.1 )
			f39_arg0.clipFinished( f39_arg0.LOCKBlackboxBG )
			local f39_local2 = function ( f42_arg0 )
				f39_arg0.ButtonStateText:beginAnimation( 150 )
				f39_arg0.ButtonStateText:setRGB( 0.92, 0.92, 0.92 )
				f39_arg0.ButtonStateText:setAlpha( 0.5 )
				f39_arg0.ButtonStateText:registerEventHandler( "interrupted_keyframe", f39_arg0.clipInterrupted )
				f39_arg0.ButtonStateText:registerEventHandler( "transition_complete_keyframe", f39_arg0.clipFinished )
			end
			
			f39_arg0.ButtonStateText:completeAnimation()
			f39_arg0.ButtonStateText:setRGB( 1, 1, 1 )
			f39_arg0.ButtonStateText:setAlpha( 1 )
			f39_arg0.ButtonStateText:setText( LocalizeToUpperString( 0xA3DAAD5829AB6E3 ) )
			f39_local2( f39_arg0.ButtonStateText )
			f39_arg0.lockedIcon:completeAnimation()
			f39_arg0.lockedIcon:setAlpha( 0 )
			f39_arg0.clipFinished( f39_arg0.lockedIcon )
		end
	}
}
CoD.StartMenu_Button_Hero_Internal.__onClose = function ( f43_arg0 )
	f43_arg0.imageContainer:close()
	f43_arg0.Subtitle:close()
	f43_arg0.DotTiledBacking:close()
	f43_arg0.lockedIcon:close()
	f43_arg0.ButtonOutline:close()
	f43_arg0.TrialUpsellMessage:close()
end

