require( "ui/uieditor/widgets/cac/cac_lock" )
require( "ui/uieditor/widgets/commonbuttonoutline" )
require( "ui/uieditor/widgets/startmenu/startmenu_imagecontainer" )
require( "ui/uieditor/widgets/startmenu/startmenu_titleheader" )
require( "ui/uieditor/widgets/store/storecommontextbacking" )

CoD.StartMenu_Button_LG_Internal = InheritFrom( LUI.UIElement )
CoD.StartMenu_Button_LG_Internal.__defaultWidth = 543
CoD.StartMenu_Button_LG_Internal.__defaultHeight = 245
CoD.StartMenu_Button_LG_Internal.new = function ( f1_arg0, f1_arg1, f1_arg2, f1_arg3, f1_arg4, f1_arg5, f1_arg6, f1_arg7, f1_arg8, f1_arg9 )
	local self = LUI.UIElement.new( f1_arg2, f1_arg3, f1_arg4, f1_arg5, f1_arg6, f1_arg7, f1_arg8, f1_arg9 )
	self:setClass( CoD.StartMenu_Button_LG_Internal )
	self.id = "StartMenu_Button_LG_Internal"
	self.soundSet = "default"
	self.onlyChildrenFocusable = true
	self.anyChildUsesUpdateState = true
	f1_arg0:addElementToPendingUpdateStateList( self )
	
	local Background = LUI.UIImage.new( 0, 1, 0, 0, 0, 1, 0, 0 )
	Background:setRGB( 0.92, 0.92, 0.92 )
	Background:setAlpha( 0.04 )
	self:addElement( Background )
	self.Background = Background
	
	local NoiseTiledBacking = LUI.UIImage.new( 0, 1, 0, 0, 0, 1, 0, 0 )
	NoiseTiledBacking:setAlpha( 0.5 )
	NoiseTiledBacking:setImage( RegisterImage( "uie_ui_menu_specialist_hub_repeat_bg" ) )
	NoiseTiledBacking:setMaterial( LUI.UIImage.GetCachedMaterial( 0x6CBE95C250C6D15 ) )
	NoiseTiledBacking:setShaderVector( 0, 0, 0, 0, 0 )
	NoiseTiledBacking:setupNineSliceShader( 196, 88 )
	self:addElement( NoiseTiledBacking )
	self.NoiseTiledBacking = NoiseTiledBacking
	
	local NoiseTiledBackingAdd = LUI.UIImage.new( 0, 1, 0, 0, 0, 1, 0, 0 )
	NoiseTiledBackingAdd:setAlpha( 0.2 )
	NoiseTiledBackingAdd:setImage( RegisterImage( "uie_ui_menu_specialist_hub_repeat_bg" ) )
	NoiseTiledBackingAdd:setMaterial( LUI.UIImage.GetCachedMaterial( 0x7C9C02F608D0A75 ) )
	NoiseTiledBackingAdd:setShaderVector( 0, 0, 0, 0, 0 )
	NoiseTiledBackingAdd:setupNineSliceShader( 196, 88 )
	self:addElement( NoiseTiledBackingAdd )
	self.NoiseTiledBackingAdd = NoiseTiledBackingAdd
	
	local ImageContainer = CoD.StartMenu_ImageContainer.new( f1_arg0, f1_arg1, 0, 1, 0, 0, 0, 1, 0, 0 )
	ImageContainer.ImageContainer:setAlpha( 0.79 )
	self:addElement( ImageContainer )
	self.ImageContainer = ImageContainer
	
	local StartMenuButtonFrame = LUI.UIFrame.new( f1_arg0, f1_arg1, 0, 0, false )
	StartMenuButtonFrame:setLeftRight( 0, 1, 0, 0 )
	StartMenuButtonFrame:setTopBottom( 0, 1, 0, 0 )
	self:addElement( StartMenuButtonFrame )
	self.StartMenuButtonFrame = StartMenuButtonFrame
	
	local LockBackground = LUI.UIImage.new( 0, 1, 0, 0, 0, 1, 0, 0 )
	LockBackground:setRGB( 0, 0, 0 )
	LockBackground:setAlpha( 0.05 )
	self:addElement( LockBackground )
	self.LockBackground = LockBackground
	
	local DotTiledBacking = CoD.StoreCommonTextBacking.new( f1_arg0, f1_arg1, 0, 1, 0, 0, 0.5, 0.5, -24, 24 )
	DotTiledBacking:setAlpha( 0 )
	self:addElement( DotTiledBacking )
	self.DotTiledBacking = DotTiledBacking
	
	local TitleBgTexture = LUI.UIImage.new( 0, 1, 0, 0, 0.5, 0.5, -24.5, 24.5 )
	TitleBgTexture:setAlpha( 0 )
	TitleBgTexture:setImage( RegisterImage( "uie_ui_menu_specialist_hub_repeat_bg" ) )
	TitleBgTexture:setMaterial( LUI.UIImage.GetCachedMaterial( 0x6CBE95C250C6D15 ) )
	TitleBgTexture:setShaderVector( 0, 0, 0, 0, 0 )
	TitleBgTexture:setupNineSliceShader( 196, 88 )
	self:addElement( TitleBgTexture )
	self.TitleBgTexture = TitleBgTexture
	
	local TitleBg = LUI.UIImage.new( 0, 1, 0, 0, 0.5, 0.5, -24.5, 24.5 )
	TitleBg:setRGB( 0, 0, 0 )
	TitleBg:setAlpha( 0 )
	self:addElement( TitleBg )
	self.TitleBg = TitleBg
	
	local ImageText = LUI.UIText.new( 0, 0, 78, 353, 0.5, 0.5, -30, 30 )
	ImageText:setText( "" )
	ImageText:setTTF( "ttmussels_regular" )
	ImageText:setAlignment( Enum.LUIAlignment[0xFEEB12BCB0D7041] )
	self:addElement( ImageText )
	self.ImageText = ImageText
	
	local lockedIcon = CoD.cac_lock.new( f1_arg0, f1_arg1, 0.5, 0.5, -24, 24, 0.5, 0.5, -24, 24 )
	lockedIcon:setAlpha( 0 )
	lockedIcon.lockedIcon:setAlpha( 0.5 )
	self:addElement( lockedIcon )
	self.lockedIcon = lockedIcon
	
	local ButtonTitle = CoD.StartMenu_TitleHeader.new( f1_arg0, f1_arg1, 0, 0, 6, 537, 0, 0, 0.5, 39.5 )
	ButtonTitle:setRGB( 0.92, 0.92, 0.92 )
	ButtonTitle.HeaderText:setText( "" )
	self:addElement( ButtonTitle )
	self.ButtonTitle = ButtonTitle
	
	local ButtonStateText = LUI.UIText.new( 0, 1, 0, 0, 0.5, 0.5, -18.5, 18.5 )
	ButtonStateText:setAlpha( 0.5 )
	ButtonStateText:setText( Engine[0xF9F1239CFD921FE]( "menu/online_only" ) )
	ButtonStateText:setTTF( "ttmussels_regular" )
	ButtonStateText:setLetterSpacing( 4 )
	ButtonStateText:setAlignment( Enum.LUIAlignment[0xFEEB12BCB0D7041] )
	self:addElement( ButtonStateText )
	self.ButtonStateText = ButtonStateText
	
	local ButtonOutline = CoD.CommonButtonOutline.new( f1_arg0, f1_arg1, 0, 1, 0, 0, 0, 1, 0, 0 )
	self:addElement( ButtonOutline )
	self.ButtonOutline = ButtonOutline
	
	StartMenuButtonFrame.id = "StartMenuButtonFrame"
	ButtonOutline.id = "ButtonOutline"
	self.__defaultFocus = ButtonOutline
	LUI.OverrideFunction_CallOriginalSecond( self, "close", self.__onClose )
	
	if PostLoadFunc then
		PostLoadFunc( self, f1_arg1, f1_arg0 )
	end
	
	return self
end

CoD.StartMenu_Button_LG_Internal.__resetProperties = function ( f2_arg0 )
	f2_arg0.lockedIcon:completeAnimation()
	f2_arg0.ImageContainer:completeAnimation()
	f2_arg0.LockBackground:completeAnimation()
	f2_arg0.ButtonStateText:completeAnimation()
	f2_arg0.TitleBgTexture:completeAnimation()
	f2_arg0.TitleBg:completeAnimation()
	f2_arg0.DotTiledBacking:completeAnimation()
	f2_arg0.NoiseTiledBackingAdd:completeAnimation()
	f2_arg0.ButtonTitle:completeAnimation()
	f2_arg0.ImageText:completeAnimation()
	f2_arg0.lockedIcon:setRGB( 1, 1, 1 )
	f2_arg0.lockedIcon:setAlpha( 0 )
	f2_arg0.lockedIcon.lockedIcon:setAlpha( 0.5 )
	f2_arg0.ImageContainer.ImageContainer:setAlpha( 0.79 )
	f2_arg0.LockBackground:setAlpha( 0.05 )
	f2_arg0.ButtonStateText:setAlpha( 0.5 )
	f2_arg0.ButtonStateText:setText( Engine[0xF9F1239CFD921FE]( "menu/online_only" ) )
	f2_arg0.TitleBgTexture:setAlpha( 0 )
	f2_arg0.TitleBg:setAlpha( 0 )
	f2_arg0.DotTiledBacking:setAlpha( 0 )
	f2_arg0.NoiseTiledBackingAdd:setAlpha( 0.2 )
	f2_arg0.ButtonTitle:setRGB( 0.92, 0.92, 0.92 )
	f2_arg0.ButtonTitle:setAlpha( 1 )
	f2_arg0.ImageText:setAlpha( 1 )
end

CoD.StartMenu_Button_LG_Internal.__clipsPerState = {
	DefaultState = {
		DefaultClip = function ( f3_arg0, f3_arg1 )
			f3_arg0:__resetProperties()
			f3_arg0:setupElementClipCounter( 7 )
			f3_arg0.ImageContainer:completeAnimation()
			f3_arg0.ImageContainer.ImageContainer:completeAnimation()
			f3_arg0.ImageContainer.ImageContainer:setAlpha( 0.79 )
			f3_arg0.clipFinished( f3_arg0.ImageContainer )
			f3_arg0.LockBackground:completeAnimation()
			f3_arg0.LockBackground:setAlpha( 0.05 )
			f3_arg0.clipFinished( f3_arg0.LockBackground )
			f3_arg0.DotTiledBacking:completeAnimation()
			f3_arg0.DotTiledBacking:setAlpha( 0 )
			f3_arg0.clipFinished( f3_arg0.DotTiledBacking )
			f3_arg0.TitleBgTexture:completeAnimation()
			f3_arg0.TitleBgTexture:setAlpha( 0 )
			f3_arg0.clipFinished( f3_arg0.TitleBgTexture )
			f3_arg0.TitleBg:completeAnimation()
			f3_arg0.TitleBg:setAlpha( 0 )
			f3_arg0.clipFinished( f3_arg0.TitleBg )
			f3_arg0.lockedIcon:completeAnimation()
			f3_arg0.lockedIcon:setAlpha( 0 )
			f3_arg0.clipFinished( f3_arg0.lockedIcon )
			f3_arg0.ButtonStateText:completeAnimation()
			f3_arg0.ButtonStateText:setAlpha( 0 )
			f3_arg0.clipFinished( f3_arg0.ButtonStateText )
		end,
		ChildFocus = function ( f4_arg0, f4_arg1 )
			f4_arg0:__resetProperties()
			f4_arg0:setupElementClipCounter( 6 )
			f4_arg0.NoiseTiledBackingAdd:completeAnimation()
			f4_arg0.NoiseTiledBackingAdd:setAlpha( 0.5 )
			f4_arg0.clipFinished( f4_arg0.NoiseTiledBackingAdd )
			f4_arg0.DotTiledBacking:completeAnimation()
			f4_arg0.DotTiledBacking:setAlpha( 0 )
			f4_arg0.clipFinished( f4_arg0.DotTiledBacking )
			f4_arg0.TitleBgTexture:completeAnimation()
			f4_arg0.TitleBgTexture:setAlpha( 0 )
			f4_arg0.clipFinished( f4_arg0.TitleBgTexture )
			f4_arg0.TitleBg:completeAnimation()
			f4_arg0.TitleBg:setAlpha( 0 )
			f4_arg0.clipFinished( f4_arg0.TitleBg )
			f4_arg0.lockedIcon:completeAnimation()
			f4_arg0.lockedIcon:setAlpha( 0 )
			f4_arg0.clipFinished( f4_arg0.lockedIcon )
			f4_arg0.ButtonStateText:completeAnimation()
			f4_arg0.ButtonStateText:setAlpha( 0 )
			f4_arg0.clipFinished( f4_arg0.ButtonStateText )
		end,
		GainChildFocus = function ( f5_arg0, f5_arg1 )
			f5_arg0:__resetProperties()
			f5_arg0:setupElementClipCounter( 8 )
			local f5_local0 = function ( f6_arg0 )
				f5_arg0.NoiseTiledBackingAdd:beginAnimation( 150 )
				f5_arg0.NoiseTiledBackingAdd:setAlpha( 0.5 )
				f5_arg0.NoiseTiledBackingAdd:registerEventHandler( "interrupted_keyframe", f5_arg0.clipInterrupted )
				f5_arg0.NoiseTiledBackingAdd:registerEventHandler( "transition_complete_keyframe", f5_arg0.clipFinished )
			end
			
			f5_arg0.NoiseTiledBackingAdd:completeAnimation()
			f5_arg0.NoiseTiledBackingAdd:setAlpha( 0.2 )
			f5_local0( f5_arg0.NoiseTiledBackingAdd )
			local f5_local1 = function ( f7_arg0 )
				f5_arg0.ImageContainer:beginAnimation( 150 )
				f5_arg0.ImageContainer.ImageContainer:beginAnimation( 150 )
				f5_arg0.ImageContainer.ImageContainer:setAlpha( 1 )
				f5_arg0.ImageContainer:registerEventHandler( "interrupted_keyframe", f5_arg0.clipInterrupted )
				f5_arg0.ImageContainer:registerEventHandler( "transition_complete_keyframe", f5_arg0.clipFinished )
			end
			
			f5_arg0.ImageContainer:completeAnimation()
			f5_arg0.ImageContainer.ImageContainer:completeAnimation()
			f5_arg0.ImageContainer.ImageContainer:setAlpha( 0.79 )
			f5_local1( f5_arg0.ImageContainer )
			local f5_local2 = function ( f8_arg0 )
				f5_arg0.LockBackground:beginAnimation( 150 )
				f5_arg0.LockBackground:setAlpha( 0 )
				f5_arg0.LockBackground:registerEventHandler( "interrupted_keyframe", f5_arg0.clipInterrupted )
				f5_arg0.LockBackground:registerEventHandler( "transition_complete_keyframe", f5_arg0.clipFinished )
			end
			
			f5_arg0.LockBackground:completeAnimation()
			f5_arg0.LockBackground:setAlpha( 0.05 )
			f5_local2( f5_arg0.LockBackground )
			f5_arg0.DotTiledBacking:completeAnimation()
			f5_arg0.DotTiledBacking:setAlpha( 0 )
			f5_arg0.clipFinished( f5_arg0.DotTiledBacking )
			f5_arg0.TitleBgTexture:completeAnimation()
			f5_arg0.TitleBgTexture:setAlpha( 0 )
			f5_arg0.clipFinished( f5_arg0.TitleBgTexture )
			f5_arg0.TitleBg:completeAnimation()
			f5_arg0.TitleBg:setAlpha( 0 )
			f5_arg0.clipFinished( f5_arg0.TitleBg )
			f5_arg0.lockedIcon:completeAnimation()
			f5_arg0.lockedIcon:setAlpha( 0 )
			f5_arg0.clipFinished( f5_arg0.lockedIcon )
			f5_arg0.ButtonStateText:completeAnimation()
			f5_arg0.ButtonStateText:setAlpha( 0 )
			f5_arg0.clipFinished( f5_arg0.ButtonStateText )
		end,
		LoseChildFocus = function ( f9_arg0, f9_arg1 )
			f9_arg0:__resetProperties()
			f9_arg0:setupElementClipCounter( 8 )
			local f9_local0 = function ( f10_arg0 )
				f9_arg0.NoiseTiledBackingAdd:beginAnimation( 150 )
				f9_arg0.NoiseTiledBackingAdd:setAlpha( 0.2 )
				f9_arg0.NoiseTiledBackingAdd:registerEventHandler( "interrupted_keyframe", f9_arg0.clipInterrupted )
				f9_arg0.NoiseTiledBackingAdd:registerEventHandler( "transition_complete_keyframe", f9_arg0.clipFinished )
			end
			
			f9_arg0.NoiseTiledBackingAdd:completeAnimation()
			f9_arg0.NoiseTiledBackingAdd:setAlpha( 0.5 )
			f9_local0( f9_arg0.NoiseTiledBackingAdd )
			local f9_local1 = function ( f11_arg0 )
				f9_arg0.ImageContainer:beginAnimation( 150 )
				f9_arg0.ImageContainer.ImageContainer:beginAnimation( 150 )
				f9_arg0.ImageContainer.ImageContainer:setAlpha( 0.79 )
				f9_arg0.ImageContainer:registerEventHandler( "interrupted_keyframe", f9_arg0.clipInterrupted )
				f9_arg0.ImageContainer:registerEventHandler( "transition_complete_keyframe", f9_arg0.clipFinished )
			end
			
			f9_arg0.ImageContainer:completeAnimation()
			f9_arg0.ImageContainer.ImageContainer:completeAnimation()
			f9_arg0.ImageContainer.ImageContainer:setAlpha( 1 )
			f9_local1( f9_arg0.ImageContainer )
			local f9_local2 = function ( f12_arg0 )
				f9_arg0.LockBackground:beginAnimation( 150 )
				f9_arg0.LockBackground:setAlpha( 0.05 )
				f9_arg0.LockBackground:registerEventHandler( "interrupted_keyframe", f9_arg0.clipInterrupted )
				f9_arg0.LockBackground:registerEventHandler( "transition_complete_keyframe", f9_arg0.clipFinished )
			end
			
			f9_arg0.LockBackground:completeAnimation()
			f9_arg0.LockBackground:setAlpha( 0 )
			f9_local2( f9_arg0.LockBackground )
			f9_arg0.DotTiledBacking:completeAnimation()
			f9_arg0.DotTiledBacking:setAlpha( 0 )
			f9_arg0.clipFinished( f9_arg0.DotTiledBacking )
			f9_arg0.TitleBgTexture:completeAnimation()
			f9_arg0.TitleBgTexture:setAlpha( 0 )
			f9_arg0.clipFinished( f9_arg0.TitleBgTexture )
			f9_arg0.TitleBg:completeAnimation()
			f9_arg0.TitleBg:setAlpha( 0 )
			f9_arg0.clipFinished( f9_arg0.TitleBg )
			f9_arg0.lockedIcon:completeAnimation()
			f9_arg0.lockedIcon:setAlpha( 0 )
			f9_arg0.clipFinished( f9_arg0.lockedIcon )
			f9_arg0.ButtonStateText:completeAnimation()
			f9_arg0.ButtonStateText:setAlpha( 0 )
			f9_arg0.clipFinished( f9_arg0.ButtonStateText )
		end
	},
	Disabled = {
		DefaultClip = function ( f13_arg0, f13_arg1 )
			f13_arg0:__resetProperties()
			f13_arg0:setupElementClipCounter( 9 )
			f13_arg0.ImageContainer:completeAnimation()
			f13_arg0.ImageContainer.ImageContainer:completeAnimation()
			f13_arg0.ImageContainer.ImageContainer:setAlpha( 0.79 )
			f13_arg0.clipFinished( f13_arg0.ImageContainer )
			f13_arg0.LockBackground:completeAnimation()
			f13_arg0.LockBackground:setAlpha( 0.1 )
			f13_arg0.clipFinished( f13_arg0.LockBackground )
			f13_arg0.DotTiledBacking:completeAnimation()
			f13_arg0.DotTiledBacking:setAlpha( 0 )
			f13_arg0.clipFinished( f13_arg0.DotTiledBacking )
			f13_arg0.TitleBgTexture:completeAnimation()
			f13_arg0.TitleBgTexture:setAlpha( 0 )
			f13_arg0.clipFinished( f13_arg0.TitleBgTexture )
			f13_arg0.TitleBg:completeAnimation()
			f13_arg0.TitleBg:setAlpha( 0 )
			f13_arg0.clipFinished( f13_arg0.TitleBg )
			f13_arg0.ImageText:completeAnimation()
			f13_arg0.ImageText:setAlpha( 0.5 )
			f13_arg0.clipFinished( f13_arg0.ImageText )
			f13_arg0.lockedIcon:completeAnimation()
			f13_arg0.lockedIcon.lockedIcon:completeAnimation()
			f13_arg0.lockedIcon:setRGB( 0.5, 0.5, 0.5 )
			f13_arg0.lockedIcon:setAlpha( 0.85 )
			f13_arg0.lockedIcon.lockedIcon:setAlpha( 1 )
			f13_arg0.clipFinished( f13_arg0.lockedIcon )
			f13_arg0.ButtonTitle:completeAnimation()
			f13_arg0.ButtonTitle:setAlpha( 0 )
			f13_arg0.clipFinished( f13_arg0.ButtonTitle )
			f13_arg0.ButtonStateText:completeAnimation()
			f13_arg0.ButtonStateText:setAlpha( 0 )
			f13_arg0.clipFinished( f13_arg0.ButtonStateText )
		end
	},
	OnlineOnly = {
		DefaultClip = function ( f14_arg0, f14_arg1 )
			f14_arg0:__resetProperties()
			f14_arg0:setupElementClipCounter( 5 )
			f14_arg0.ImageContainer:completeAnimation()
			f14_arg0.ImageContainer.ImageContainer:completeAnimation()
			f14_arg0.ImageContainer.ImageContainer:setAlpha( 0.79 )
			f14_arg0.clipFinished( f14_arg0.ImageContainer )
			f14_arg0.LockBackground:completeAnimation()
			f14_arg0.LockBackground:setAlpha( 0.1 )
			f14_arg0.clipFinished( f14_arg0.LockBackground )
			f14_arg0.lockedIcon:completeAnimation()
			f14_arg0.lockedIcon:setAlpha( 0 )
			f14_arg0.clipFinished( f14_arg0.lockedIcon )
			f14_arg0.ButtonTitle:completeAnimation()
			f14_arg0.ButtonTitle:setAlpha( 0.2 )
			f14_arg0.clipFinished( f14_arg0.ButtonTitle )
			f14_arg0.ButtonStateText:completeAnimation()
			f14_arg0.ButtonStateText:setAlpha( 0.5 )
			f14_arg0.clipFinished( f14_arg0.ButtonStateText )
		end,
		ChildFocus = function ( f15_arg0, f15_arg1 )
			f15_arg0:__resetProperties()
			f15_arg0:setupElementClipCounter( 3 )
			f15_arg0.NoiseTiledBackingAdd:completeAnimation()
			f15_arg0.NoiseTiledBackingAdd:setAlpha( 0.5 )
			f15_arg0.clipFinished( f15_arg0.NoiseTiledBackingAdd )
			f15_arg0.lockedIcon:completeAnimation()
			f15_arg0.lockedIcon:setAlpha( 0 )
			f15_arg0.clipFinished( f15_arg0.lockedIcon )
			f15_arg0.ButtonStateText:completeAnimation()
			f15_arg0.ButtonStateText:setAlpha( 1 )
			f15_arg0.clipFinished( f15_arg0.ButtonStateText )
		end,
		GainChildFocus = function ( f16_arg0, f16_arg1 )
			f16_arg0:__resetProperties()
			f16_arg0:setupElementClipCounter( 5 )
			local f16_local0 = function ( f17_arg0 )
				f16_arg0.NoiseTiledBackingAdd:beginAnimation( 150 )
				f16_arg0.NoiseTiledBackingAdd:setAlpha( 0.5 )
				f16_arg0.NoiseTiledBackingAdd:registerEventHandler( "interrupted_keyframe", f16_arg0.clipInterrupted )
				f16_arg0.NoiseTiledBackingAdd:registerEventHandler( "transition_complete_keyframe", f16_arg0.clipFinished )
			end
			
			f16_arg0.NoiseTiledBackingAdd:completeAnimation()
			f16_arg0.NoiseTiledBackingAdd:setAlpha( 0.2 )
			f16_local0( f16_arg0.NoiseTiledBackingAdd )
			local f16_local1 = function ( f18_arg0 )
				f16_arg0.ImageContainer:beginAnimation( 150 )
				f16_arg0.ImageContainer.ImageContainer:beginAnimation( 150 )
				f16_arg0.ImageContainer.ImageContainer:setAlpha( 1 )
				f16_arg0.ImageContainer:registerEventHandler( "interrupted_keyframe", f16_arg0.clipInterrupted )
				f16_arg0.ImageContainer:registerEventHandler( "transition_complete_keyframe", f16_arg0.clipFinished )
			end
			
			f16_arg0.ImageContainer:completeAnimation()
			f16_arg0.ImageContainer.ImageContainer:completeAnimation()
			f16_arg0.ImageContainer.ImageContainer:setAlpha( 0.79 )
			f16_local1( f16_arg0.ImageContainer )
			local f16_local2 = function ( f19_arg0 )
				f16_arg0.LockBackground:beginAnimation( 150 )
				f16_arg0.LockBackground:setAlpha( 0 )
				f16_arg0.LockBackground:registerEventHandler( "interrupted_keyframe", f16_arg0.clipInterrupted )
				f16_arg0.LockBackground:registerEventHandler( "transition_complete_keyframe", f16_arg0.clipFinished )
			end
			
			f16_arg0.LockBackground:completeAnimation()
			f16_arg0.LockBackground:setAlpha( 0.1 )
			f16_local2( f16_arg0.LockBackground )
			f16_arg0.lockedIcon:completeAnimation()
			f16_arg0.lockedIcon:setAlpha( 0 )
			f16_arg0.clipFinished( f16_arg0.lockedIcon )
			local f16_local3 = function ( f20_arg0 )
				f16_arg0.ButtonStateText:beginAnimation( 150 )
				f16_arg0.ButtonStateText:setAlpha( 1 )
				f16_arg0.ButtonStateText:registerEventHandler( "interrupted_keyframe", f16_arg0.clipInterrupted )
				f16_arg0.ButtonStateText:registerEventHandler( "transition_complete_keyframe", f16_arg0.clipFinished )
			end
			
			f16_arg0.ButtonStateText:completeAnimation()
			f16_arg0.ButtonStateText:setAlpha( 0.5 )
			f16_local3( f16_arg0.ButtonStateText )
		end,
		LoseChildFocus = function ( f21_arg0, f21_arg1 )
			f21_arg0:__resetProperties()
			f21_arg0:setupElementClipCounter( 5 )
			local f21_local0 = function ( f22_arg0 )
				f21_arg0.NoiseTiledBackingAdd:beginAnimation( 150 )
				f21_arg0.NoiseTiledBackingAdd:setAlpha( 0.2 )
				f21_arg0.NoiseTiledBackingAdd:registerEventHandler( "interrupted_keyframe", f21_arg0.clipInterrupted )
				f21_arg0.NoiseTiledBackingAdd:registerEventHandler( "transition_complete_keyframe", f21_arg0.clipFinished )
			end
			
			f21_arg0.NoiseTiledBackingAdd:completeAnimation()
			f21_arg0.NoiseTiledBackingAdd:setAlpha( 0.5 )
			f21_local0( f21_arg0.NoiseTiledBackingAdd )
			local f21_local1 = function ( f23_arg0 )
				f21_arg0.ImageContainer:beginAnimation( 150 )
				f21_arg0.ImageContainer.ImageContainer:beginAnimation( 150 )
				f21_arg0.ImageContainer.ImageContainer:setAlpha( 0.79 )
				f21_arg0.ImageContainer:registerEventHandler( "interrupted_keyframe", f21_arg0.clipInterrupted )
				f21_arg0.ImageContainer:registerEventHandler( "transition_complete_keyframe", f21_arg0.clipFinished )
			end
			
			f21_arg0.ImageContainer:completeAnimation()
			f21_arg0.ImageContainer.ImageContainer:completeAnimation()
			f21_arg0.ImageContainer.ImageContainer:setAlpha( 1 )
			f21_local1( f21_arg0.ImageContainer )
			local f21_local2 = function ( f24_arg0 )
				f21_arg0.LockBackground:beginAnimation( 150 )
				f21_arg0.LockBackground:setAlpha( 0.1 )
				f21_arg0.LockBackground:registerEventHandler( "interrupted_keyframe", f21_arg0.clipInterrupted )
				f21_arg0.LockBackground:registerEventHandler( "transition_complete_keyframe", f21_arg0.clipFinished )
			end
			
			f21_arg0.LockBackground:completeAnimation()
			f21_arg0.LockBackground:setAlpha( 0 )
			f21_local2( f21_arg0.LockBackground )
			f21_arg0.lockedIcon:completeAnimation()
			f21_arg0.lockedIcon:setAlpha( 0 )
			f21_arg0.clipFinished( f21_arg0.lockedIcon )
			local f21_local3 = function ( f25_arg0 )
				f21_arg0.ButtonStateText:beginAnimation( 150 )
				f21_arg0.ButtonStateText:setAlpha( 0.5 )
				f21_arg0.ButtonStateText:registerEventHandler( "interrupted_keyframe", f21_arg0.clipInterrupted )
				f21_arg0.ButtonStateText:registerEventHandler( "transition_complete_keyframe", f21_arg0.clipFinished )
			end
			
			f21_arg0.ButtonStateText:completeAnimation()
			f21_arg0.ButtonStateText:setAlpha( 1 )
			f21_local3( f21_arg0.ButtonStateText )
		end
	},
	ComingSoon = {
		DefaultClip = function ( f26_arg0, f26_arg1 )
			f26_arg0:__resetProperties()
			f26_arg0:setupElementClipCounter( 5 )
			f26_arg0.ImageContainer:completeAnimation()
			f26_arg0.ImageContainer.ImageContainer:completeAnimation()
			f26_arg0.ImageContainer.ImageContainer:setAlpha( 0.79 )
			f26_arg0.clipFinished( f26_arg0.ImageContainer )
			f26_arg0.LockBackground:completeAnimation()
			f26_arg0.LockBackground:setAlpha( 0.1 )
			f26_arg0.clipFinished( f26_arg0.LockBackground )
			f26_arg0.lockedIcon:completeAnimation()
			f26_arg0.lockedIcon:setAlpha( 0 )
			f26_arg0.clipFinished( f26_arg0.lockedIcon )
			f26_arg0.ButtonTitle:completeAnimation()
			f26_arg0.ButtonTitle:setRGB( 0.92, 0.92, 0.92 )
			f26_arg0.ButtonTitle:setAlpha( 0.2 )
			f26_arg0.clipFinished( f26_arg0.ButtonTitle )
			f26_arg0.ButtonStateText:completeAnimation()
			f26_arg0.ButtonStateText:setAlpha( 0.5 )
			f26_arg0.ButtonStateText:setText( Engine[0xF9F1239CFD921FE]( "menu/coming_soon" ) )
			f26_arg0.clipFinished( f26_arg0.ButtonStateText )
		end
	}
}
CoD.StartMenu_Button_LG_Internal.__onClose = function ( f27_arg0 )
	f27_arg0.ImageContainer:close()
	f27_arg0.StartMenuButtonFrame:close()
	f27_arg0.DotTiledBacking:close()
	f27_arg0.lockedIcon:close()
	f27_arg0.ButtonTitle:close()
	f27_arg0.ButtonOutline:close()
end

