require( "ui/uieditor/widgets/common/commonfocusbrackets" )
require( "ui/uieditor/widgets/common/CommonPixelBacking" )
require( "ui/uieditor/widgets/director/directorselectbuttonlines" )

CoD.ArenaEventButtonInternal = InheritFrom( LUI.UIElement )
CoD.ArenaEventButtonInternal.__defaultWidth = 200
CoD.ArenaEventButtonInternal.__defaultHeight = 69
CoD.ArenaEventButtonInternal.new = function ( f1_arg0, f1_arg1, f1_arg2, f1_arg3, f1_arg4, f1_arg5, f1_arg6, f1_arg7, f1_arg8, f1_arg9 )
	local self = LUI.UIElement.new( f1_arg2, f1_arg3, f1_arg4, f1_arg5, f1_arg6, f1_arg7, f1_arg8, f1_arg9 )
	self:setClass( CoD.ArenaEventButtonInternal )
	self.id = "ArenaEventButtonInternal"
	self.soundSet = "FrontendMain"
	f1_arg0:addElementToPendingUpdateStateList( self )
	
	local SceneBlur = LUI.UIImage.new( 0, 1, 0, 0, 0, 1, 0, 0 )
	SceneBlur:setRGB( 0, 0, 0 )
	SceneBlur:setMaterial( LUI.UIImage.GetCachedMaterial( 0xE2354BE557C4C7A ) )
	SceneBlur:setShaderVector( 0, 0, 0.4, 0, 0 )
	self:addElement( SceneBlur )
	self.SceneBlur = SceneBlur
	
	local NoiseTiledBacking = LUI.UIImage.new( 0, 1, 0, 0, 0, 1, 0, 0 )
	NoiseTiledBacking:setAlpha( 0.95 )
	NoiseTiledBacking:setImage( RegisterImage( "uie_ui_menu_specialist_hub_repeat_bg" ) )
	NoiseTiledBacking:setMaterial( LUI.UIImage.GetCachedMaterial( 0x6CBE95C250C6D15 ) )
	NoiseTiledBacking:setShaderVector( 0, 0, 0, 0, 0 )
	NoiseTiledBacking:setupNineSliceShader( 196, 88 )
	self:addElement( NoiseTiledBacking )
	self.NoiseTiledBacking = NoiseTiledBacking
	
	local Tint = LUI.UIImage.new( 0, 1, 0, 0, 0, 1, 0, 0 )
	Tint:setRGB( 0, 0, 0 )
	Tint:setAlpha( 0.75 )
	self:addElement( Tint )
	self.Tint = Tint
	
	local FocusBrackets = CoD.CommonFocusBrackets.new( f1_arg0, f1_arg1, 0, 1, -20, 20, 0, 1, -20, 20 )
	FocusBrackets:setAlpha( 0 )
	self:addElement( FocusBrackets )
	self.FocusBrackets = FocusBrackets
	
	local FrontendFrameSelected = LUI.UIImage.new( 0, 1, -4, 4, 0, 1, -4, 4 )
	FrontendFrameSelected:setRGB( 0.8, 0.7, 0.09 )
	FrontendFrameSelected:setAlpha( 0 )
	FrontendFrameSelected:setImage( RegisterImage( "uie_ui_menu_store_focus_frame" ) )
	FrontendFrameSelected:setMaterial( LUI.UIImage.GetCachedMaterial( "uie_nineslice_add" ) )
	FrontendFrameSelected:setShaderVector( 0, 0, 0, 0, 0 )
	FrontendFrameSelected:setupNineSliceShader( 10, 10 )
	self:addElement( FrontendFrameSelected )
	self.FrontendFrameSelected = FrontendFrameSelected
	
	local FocusGlow = LUI.UIImage.new( 0, 1, -130, 130, 0, 1, -158, 158 )
	FocusGlow:setAlpha( 0 )
	FocusGlow:setImage( RegisterImage( 0x223AD1B40A93955 ) )
	FocusGlow:setMaterial( LUI.UIImage.GetCachedMaterial( 0xDAB59B2CAE01851 ) )
	FocusGlow:setShaderVector( 0, 0, 0, 0.21, 0.09 )
	FocusGlow:setShaderVector( 1, 1.36, 0, 0, 0 )
	FocusGlow:setupNineSliceShader( 245, 185 )
	self:addElement( FocusGlow )
	self.FocusGlow = FocusGlow
	
	local FocusHighlight = LUI.UIImage.new( 0, 1, -52, 52, 0, 1, -42, 42 )
	FocusHighlight:setAlpha( 0 )
	FocusHighlight:setImage( RegisterImage( 0x3F09D20CA138B49 ) )
	FocusHighlight:setMaterial( LUI.UIImage.GetCachedMaterial( 0xDAB59B2CAE01851 ) )
	FocusHighlight:setShaderVector( 0, 0, 0, 0.27, 0.18 )
	FocusHighlight:setShaderVector( 1, 0.9, 0, 0, 0 )
	FocusHighlight:setupNineSliceShader( 135, 70 )
	self:addElement( FocusHighlight )
	self.FocusHighlight = FocusHighlight
	
	local DotTiledBacking = CoD.CommonPixelBacking.new( f1_arg0, f1_arg1, 0, 1, 4, -4, 0, 1, 4, -4 )
	DotTiledBacking:setRFTMaterial( LUI.UIImage.GetCachedMaterial( "ui_add" ) )
	DotTiledBacking.NoiseBacking:setAlpha( 1 )
	DotTiledBacking.TiledShaderImage:setRGB( 0.22, 0.22, 0.22 )
	DotTiledBacking.TiledShaderImage:setAlpha( 0.15 )
	DotTiledBacking.TiledShaderImage:setupNineSliceShader( 36, 36 )
	self:addElement( DotTiledBacking )
	self.DotTiledBacking = DotTiledBacking
	
	local FrameBorder = LUI.UIImage.new( 0, 1, -1, 1, 0, 1, -1, 1 )
	FrameBorder:setAlpha( 0.1 )
	FrameBorder:setImage( RegisterImage( "uie_ui_menu_store_common_frame" ) )
	FrameBorder:setMaterial( LUI.UIImage.GetCachedMaterial( "uie_nineslice_add" ) )
	FrameBorder:setShaderVector( 0, 0, 0, 0, 0 )
	FrameBorder:setupNineSliceShader( 12, 12 )
	self:addElement( FrameBorder )
	self.FrameBorder = FrameBorder
	
	local MiddleTextFocus = LUI.UIText.new( -0, -0, 15, 135, 0.5, 0.5, -12, 12 )
	MiddleTextFocus:setRGB( 0.28, 0.25, 0.24 )
	MiddleTextFocus:setAlpha( 0 )
	MiddleTextFocus:setText( LocalizeToUpperString( 0xA43B10D9DA121A ) )
	MiddleTextFocus:setTTF( "ttmussels_regular" )
	MiddleTextFocus:setMaterial( LUI.UIImage.GetCachedMaterial( 0xAE166D9BA8C6907 ) )
	MiddleTextFocus:setShaderVector( 0, 0.13, 0, 0, 0 )
	MiddleTextFocus:setShaderVector( 1, 0.34, 0, 0, 0 )
	MiddleTextFocus:setShaderVector( 2, 1, 0, 0, 0 )
	MiddleTextFocus:setLetterSpacing( 3 )
	MiddleTextFocus:setAlignment( Enum.LUIAlignment[0x58C8A85F2048829] )
	MiddleTextFocus:setAlignment( Enum.LUIAlignment[0x6ED4298C93DC5ED] )
	self:addElement( MiddleTextFocus )
	self.MiddleTextFocus = MiddleTextFocus
	
	local LeaderActivityText = LUI.UIText.new( 0, 0, 15, 135, 0.5, 0.5, -10, 10 )
	LeaderActivityText:setRGB( 0.63, 0.62, 0.61 )
	LeaderActivityText:setAlpha( 0 )
	LeaderActivityText:setText( Engine[0xF9F1239CFD921FE]( "menu/new" ) )
	LeaderActivityText:setTTF( "ttmussels_regular" )
	LeaderActivityText:setLetterSpacing( 4 )
	LeaderActivityText:setAlignment( Enum.LUIAlignment[0xFEEB12BCB0D7041] )
	LeaderActivityText:setAlignment( Enum.LUIAlignment[0x6ED4298C93DC5ED] )
	self:addElement( LeaderActivityText )
	self.LeaderActivityText = LeaderActivityText
	
	local MiddleText = LUI.UIText.new( -0, -0, 15, 135, 0.5, 0.5, -12, 12 )
	MiddleText:setRGB( ColorSet.T8__BIEGE.r, ColorSet.T8__BIEGE.g, ColorSet.T8__BIEGE.b )
	MiddleText:setText( LocalizeToUpperString( 0xA43B10D9DA121A ) )
	MiddleText:setTTF( "ttmussels_regular" )
	MiddleText:setMaterial( LUI.UIImage.GetCachedMaterial( 0x71E049B161CD00A ) )
	MiddleText:setLetterSpacing( 3 )
	MiddleText:setAlignment( Enum.LUIAlignment[0x58C8A85F2048829] )
	MiddleText:setAlignment( Enum.LUIAlignment[0x6ED4298C93DC5ED] )
	self:addElement( MiddleText )
	self.MiddleText = MiddleText
	
	local lockImage = LUI.UIImage.new( 1, 1, -42, 8, 0.5, 0.5, -25, 25 )
	lockImage:setAlpha( 0 )
	lockImage:setScale( 0.6, 0.6 )
	lockImage:setImage( RegisterImage( "uie_ui_icon_global_lock" ) )
	self:addElement( lockImage )
	self.lockImage = lockImage
	
	local Lines = CoD.DirectorSelectButtonLines.new( f1_arg0, f1_arg1, 0, 1, 0, 0, 0, 1, 1, -1 )
	Lines:setRGB( 0.64, 0.71, 0.78 )
	self:addElement( Lines )
	self.Lines = Lines
	
	local FocusBorder = LUI.UIImage.new( 0, 1, -4, 4, 0, 1, -4, 4 )
	FocusBorder:setRGB( 0.96, 0.94, 0.78 )
	FocusBorder:setAlpha( 0 )
	FocusBorder:setImage( RegisterImage( "uie_ui_menu_store_focus_frame" ) )
	FocusBorder:setMaterial( LUI.UIImage.GetCachedMaterial( "uie_nineslice_add" ) )
	FocusBorder:setShaderVector( 0, 0, 0, 0, 0 )
	FocusBorder:setupNineSliceShader( 10, 10 )
	self:addElement( FocusBorder )
	self.FocusBorder = FocusBorder
	
	local leagueOrdinalRank = LUI.UIText.new( 0.75, 0.75, 18, 46, 0.5, 0.5, -30.5, 2.5 )
	leagueOrdinalRank:setRGB( ColorSet.T8__OCHRE.r, ColorSet.T8__OCHRE.g, ColorSet.T8__OCHRE.b )
	leagueOrdinalRank:setAlpha( 0 )
	leagueOrdinalRank:setTTF( "0arame_mono_stencil" )
	leagueOrdinalRank:setMaterial( LUI.UIImage.GetCachedMaterial( 0x71E049B161CD00A ) )
	leagueOrdinalRank:setLetterSpacing( 2 )
	leagueOrdinalRank:setAlignment( Enum.LUIAlignment[0xFEEB12BCB0D7041] )
	leagueOrdinalRank:subscribeToGlobalModel( f1_arg1, "LeaguePlayLadder", "entityLadderRank", function ( model )
		local f2_local0 = model:get()
		if f2_local0 ~= nil then
			leagueOrdinalRank:setText( Engine[0xF9F1239CFD921FE]( CoD.ArenaUtility.GetLadderPositionOrdinal( f2_local0 ) ) )
		end
	end )
	self:addElement( leagueOrdinalRank )
	self.leagueOrdinalRank = leagueOrdinalRank
	
	local leagueRank = LUI.UIText.new( 0.75, 0.75, -50, 22, 0.5, 0.5, -23.5, 23.5 )
	leagueRank:setRGB( ColorSet.T8__OCHRE.r, ColorSet.T8__OCHRE.g, ColorSet.T8__OCHRE.b )
	leagueRank:setAlpha( 0 )
	leagueRank:setTTF( "0arame_mono_stencil" )
	leagueRank:setMaterial( LUI.UIImage.GetCachedMaterial( 0x71E049B161CD00A ) )
	leagueRank:setLetterSpacing( 2 )
	leagueRank:setAlignment( Enum.LUIAlignment[0xFEEB12BCB0D7041] )
	leagueRank:subscribeToGlobalModel( f1_arg1, "LeaguePlayLadder", "entityLadderRank", function ( model )
		local f3_local0 = model:get()
		if f3_local0 ~= nil then
			leagueRank:setText( f3_local0 )
		end
	end )
	self:addElement( leagueRank )
	self.leagueRank = leagueRank
	
	self:subscribeToGlobalModel( f1_arg1, "GlobalModel", "lobbyRoot.lobbyNav", function ( model )
		local f4_local0 = self
		SetLoseFocusToSelf( self, f1_arg1 )
	end )
	LUI.OverrideFunction_CallOriginalSecond( self, "close", self.__onClose )
	
	if PostLoadFunc then
		PostLoadFunc( self, f1_arg1, f1_arg0 )
	end
	
	return self
end

CoD.ArenaEventButtonInternal.__resetProperties = function ( f5_arg0 )
	f5_arg0.MiddleTextFocus:completeAnimation()
	f5_arg0.LeaderActivityText:completeAnimation()
	f5_arg0.MiddleText:completeAnimation()
	f5_arg0.leagueOrdinalRank:completeAnimation()
	f5_arg0.leagueRank:completeAnimation()
	f5_arg0.lockImage:completeAnimation()
	f5_arg0.FrontendFrameSelected:completeAnimation()
	f5_arg0.FocusBrackets:completeAnimation()
	f5_arg0.DotTiledBacking:completeAnimation()
	f5_arg0.Lines:completeAnimation()
	f5_arg0.FocusHighlight:completeAnimation()
	f5_arg0.FocusGlow:completeAnimation()
	f5_arg0.NoiseTiledBacking:completeAnimation()
	f5_arg0.FocusBorder:completeAnimation()
	f5_arg0.MiddleTextFocus:setLeftRight( -0, -0, 15, 135 )
	f5_arg0.MiddleTextFocus:setTopBottom( 0.5, 0.5, -12, 12 )
	f5_arg0.MiddleTextFocus:setRGB( 0.28, 0.25, 0.24 )
	f5_arg0.MiddleTextFocus:setAlpha( 0 )
	f5_arg0.MiddleTextFocus:setAlignment( Enum.LUIAlignment[0x6ED4298C93DC5ED] )
	f5_arg0.LeaderActivityText:setLeftRight( 0, 0, 15, 135 )
	f5_arg0.LeaderActivityText:setTopBottom( 0.5, 0.5, -10, 10 )
	f5_arg0.LeaderActivityText:setAlignment( Enum.LUIAlignment[0x6ED4298C93DC5ED] )
	f5_arg0.MiddleText:setLeftRight( -0, -0, 15, 135 )
	f5_arg0.MiddleText:setTopBottom( 0.5, 0.5, -12, 12 )
	f5_arg0.MiddleText:setRGB( ColorSet.T8__BIEGE.r, ColorSet.T8__BIEGE.g, ColorSet.T8__BIEGE.b )
	f5_arg0.MiddleText:setAlpha( 1 )
	f5_arg0.MiddleText:setAlignment( Enum.LUIAlignment[0x6ED4298C93DC5ED] )
	f5_arg0.leagueOrdinalRank:setRGB( ColorSet.T8__OCHRE.r, ColorSet.T8__OCHRE.g, ColorSet.T8__OCHRE.b )
	f5_arg0.leagueOrdinalRank:setAlpha( 0 )
	f5_arg0.leagueRank:setRGB( ColorSet.T8__OCHRE.r, ColorSet.T8__OCHRE.g, ColorSet.T8__OCHRE.b )
	f5_arg0.leagueRank:setAlpha( 0 )
	f5_arg0.lockImage:setAlpha( 0 )
	f5_arg0.lockImage:setScale( 0.6, 0.6 )
	f5_arg0.FrontendFrameSelected:setAlpha( 0 )
	f5_arg0.FocusBrackets:setLeftRight( 0, 1, -20, 20 )
	f5_arg0.FocusBrackets:setTopBottom( 0, 1, -20, 20 )
	f5_arg0.FocusBrackets:setAlpha( 0 )
	f5_arg0.DotTiledBacking.TiledShaderImage:setRGB( 0.22, 0.22, 0.22 )
	f5_arg0.DotTiledBacking.TiledShaderImage:setAlpha( 0.15 )
	f5_arg0.Lines:setAlpha( 1 )
	f5_arg0.FocusHighlight:setAlpha( 0 )
	f5_arg0.FocusGlow:setRGB( 1, 1, 1 )
	f5_arg0.FocusGlow:setAlpha( 0 )
	f5_arg0.NoiseTiledBacking:setRGB( 1, 1, 1 )
	f5_arg0.FocusBorder:setRGB( 0.96, 0.94, 0.78 )
	f5_arg0.FocusBorder:setAlpha( 0 )
end

CoD.ArenaEventButtonInternal.__clipsPerState = {
	DefaultState = {
		DefaultClip = function ( f6_arg0, f6_arg1 )
			f6_arg0:__resetProperties()
			f6_arg0:setupElementClipCounter( 5 )
			f6_arg0.MiddleTextFocus:completeAnimation()
			f6_arg0.MiddleTextFocus:setLeftRight( -0, -0, 10, 130 )
			f6_arg0.clipFinished( f6_arg0.MiddleTextFocus )
			f6_arg0.LeaderActivityText:completeAnimation()
			f6_arg0.LeaderActivityText:setLeftRight( 0, 0, 15, 135 )
			f6_arg0.clipFinished( f6_arg0.LeaderActivityText )
			f6_arg0.MiddleText:completeAnimation()
			f6_arg0.MiddleText:setLeftRight( -0, -0, 15, 135 )
			f6_arg0.MiddleText:setTopBottom( 0.5, 0.5, -12, 12 )
			f6_arg0.clipFinished( f6_arg0.MiddleText )
			f6_arg0.leagueOrdinalRank:completeAnimation()
			f6_arg0.leagueOrdinalRank:setAlpha( 1 )
			f6_arg0.clipFinished( f6_arg0.leagueOrdinalRank )
			f6_arg0.leagueRank:completeAnimation()
			f6_arg0.leagueRank:setAlpha( 1 )
			f6_arg0.clipFinished( f6_arg0.leagueRank )
		end,
		Focus = function ( f7_arg0, f7_arg1 )
			f7_arg0:__resetProperties()
			f7_arg0:setupElementClipCounter( 12 )
			f7_arg0.FocusBrackets:completeAnimation()
			f7_arg0.FocusBrackets:setLeftRight( 0, 1, -10, 10 )
			f7_arg0.FocusBrackets:setTopBottom( 0, 1, -10, 10 )
			f7_arg0.FocusBrackets:setAlpha( 1 )
			f7_arg0.clipFinished( f7_arg0.FocusBrackets )
			f7_arg0.FrontendFrameSelected:completeAnimation()
			f7_arg0.FrontendFrameSelected:setAlpha( 0.1 )
			f7_arg0.clipFinished( f7_arg0.FrontendFrameSelected )
			local f7_local0 = function ( f8_arg0 )
				local f8_local0 = function ( f9_arg0 )
					f9_arg0:beginAnimation( 2010 )
					f9_arg0:setRGB( 1, 1, 1 )
					f9_arg0:registerEventHandler( "transition_complete_keyframe", f7_arg0.clipFinished )
				end
				
				f7_arg0.FocusGlow:beginAnimation( 1990 )
				f7_arg0.FocusGlow:setRGB( 0.79, 0.79, 0.79 )
				f7_arg0.FocusGlow:registerEventHandler( "interrupted_keyframe", f7_arg0.clipInterrupted )
				f7_arg0.FocusGlow:registerEventHandler( "transition_complete_keyframe", f8_local0 )
			end
			
			f7_arg0.FocusGlow:completeAnimation()
			f7_arg0.FocusGlow:setRGB( 1, 1, 1 )
			f7_arg0.FocusGlow:setAlpha( 1 )
			f7_local0( f7_arg0.FocusGlow )
			f7_arg0.FocusHighlight:completeAnimation()
			f7_arg0.FocusHighlight:setAlpha( 0.5 )
			f7_arg0.clipFinished( f7_arg0.FocusHighlight )
			f7_arg0.DotTiledBacking:completeAnimation()
			f7_arg0.DotTiledBacking.TiledShaderImage:completeAnimation()
			f7_arg0.DotTiledBacking.TiledShaderImage:setRGB( 0.28, 0.28, 0.28 )
			f7_arg0.DotTiledBacking.TiledShaderImage:setAlpha( 0.7 )
			f7_arg0.clipFinished( f7_arg0.DotTiledBacking )
			f7_arg0.MiddleTextFocus:completeAnimation()
			f7_arg0.MiddleTextFocus:setTopBottom( 0.5, 0.5, -12, 12 )
			f7_arg0.MiddleTextFocus:setRGB( 0.28, 0.25, 0.24 )
			f7_arg0.MiddleTextFocus:setAlpha( 1 )
			f7_arg0.clipFinished( f7_arg0.MiddleTextFocus )
			f7_arg0.LeaderActivityText:completeAnimation()
			f7_arg0.clipFinished( f7_arg0.LeaderActivityText )
			f7_arg0.MiddleText:completeAnimation()
			f7_arg0.MiddleText:setTopBottom( 0.5, 0.5, -12, 12 )
			f7_arg0.MiddleText:setAlpha( 0 )
			f7_arg0.clipFinished( f7_arg0.MiddleText )
			f7_arg0.lockImage:completeAnimation()
			f7_arg0.lockImage:setScale( 1.2, 1.2 )
			f7_arg0.clipFinished( f7_arg0.lockImage )
			f7_arg0.Lines:completeAnimation()
			f7_arg0.Lines:setAlpha( 0 )
			f7_arg0.clipFinished( f7_arg0.Lines )
			f7_arg0.leagueOrdinalRank:completeAnimation()
			f7_arg0.leagueOrdinalRank:setRGB( 0.28, 0.25, 0.24 )
			f7_arg0.leagueOrdinalRank:setAlpha( 1 )
			f7_arg0.clipFinished( f7_arg0.leagueOrdinalRank )
			f7_arg0.leagueRank:completeAnimation()
			f7_arg0.leagueRank:setRGB( 0.28, 0.25, 0.24 )
			f7_arg0.leagueRank:setAlpha( 1 )
			f7_arg0.clipFinished( f7_arg0.leagueRank )
			f7_arg0.nextClip = "Focus"
		end,
		GainFocus = function ( f10_arg0, f10_arg1 )
			f10_arg0:__resetProperties()
			f10_arg0:setupElementClipCounter( 11 )
			local f10_local0 = function ( f11_arg0 )
				local f11_local0 = function ( f12_arg0 )
					f12_arg0:beginAnimation( 50, Enum[0xF50FFF429AB1890][0x6F6186B702830BC] )
					f12_arg0:setLeftRight( 0, 1, -10, 10 )
					f12_arg0:setTopBottom( 0, 1, -10, 10 )
					f12_arg0:setAlpha( 1 )
					f12_arg0:registerEventHandler( "transition_complete_keyframe", f10_arg0.clipFinished )
				end
				
				f10_arg0.FocusBrackets:beginAnimation( 100 )
				f10_arg0.FocusBrackets:setLeftRight( 0, 1, -8, 8 )
				f10_arg0.FocusBrackets:setTopBottom( 0, 1, -8, 8 )
				f10_arg0.FocusBrackets:setAlpha( 0.75 )
				f10_arg0.FocusBrackets:registerEventHandler( "interrupted_keyframe", f10_arg0.clipInterrupted )
				f10_arg0.FocusBrackets:registerEventHandler( "transition_complete_keyframe", f11_local0 )
			end
			
			f10_arg0.FocusBrackets:completeAnimation()
			f10_arg0.FocusBrackets:setLeftRight( 0, 1, -40, 40 )
			f10_arg0.FocusBrackets:setTopBottom( 0, 1, -40, 40 )
			f10_arg0.FocusBrackets:setAlpha( 0 )
			f10_local0( f10_arg0.FocusBrackets )
			local f10_local1 = function ( f13_arg0 )
				f10_arg0.FrontendFrameSelected:beginAnimation( 200, Enum[0xF50FFF429AB1890][0x5193EA7825DC097] )
				f10_arg0.FrontendFrameSelected:setAlpha( 0.1 )
				f10_arg0.FrontendFrameSelected:registerEventHandler( "interrupted_keyframe", f10_arg0.clipInterrupted )
				f10_arg0.FrontendFrameSelected:registerEventHandler( "transition_complete_keyframe", f10_arg0.clipFinished )
			end
			
			f10_arg0.FrontendFrameSelected:completeAnimation()
			f10_arg0.FrontendFrameSelected:setAlpha( 0 )
			f10_local1( f10_arg0.FrontendFrameSelected )
			local f10_local2 = function ( f14_arg0 )
				f10_arg0.FocusGlow:beginAnimation( 200, Enum[0xF50FFF429AB1890][0x6F6186B702830BC] )
				f10_arg0.FocusGlow:setAlpha( 1 )
				f10_arg0.FocusGlow:registerEventHandler( "interrupted_keyframe", f10_arg0.clipInterrupted )
				f10_arg0.FocusGlow:registerEventHandler( "transition_complete_keyframe", f10_arg0.clipFinished )
			end
			
			f10_arg0.FocusGlow:completeAnimation()
			f10_arg0.FocusGlow:setAlpha( 0 )
			f10_local2( f10_arg0.FocusGlow )
			local f10_local3 = function ( f15_arg0 )
				f10_arg0.FocusHighlight:beginAnimation( 200 )
				f10_arg0.FocusHighlight:setAlpha( 0.8 )
				f10_arg0.FocusHighlight:registerEventHandler( "interrupted_keyframe", f10_arg0.clipInterrupted )
				f10_arg0.FocusHighlight:registerEventHandler( "transition_complete_keyframe", f10_arg0.clipFinished )
			end
			
			f10_arg0.FocusHighlight:completeAnimation()
			f10_arg0.FocusHighlight:setAlpha( 0 )
			f10_local3( f10_arg0.FocusHighlight )
			local f10_local4 = function ( f16_arg0 )
				f10_arg0.DotTiledBacking:beginAnimation( 200 )
				f10_arg0.DotTiledBacking.TiledShaderImage:beginAnimation( 200 )
				f10_arg0.DotTiledBacking.TiledShaderImage:setRGB( 0.28, 0.28, 0.28 )
				f10_arg0.DotTiledBacking:registerEventHandler( "interrupted_keyframe", f10_arg0.clipInterrupted )
				f10_arg0.DotTiledBacking:registerEventHandler( "transition_complete_keyframe", f10_arg0.clipFinished )
			end
			
			f10_arg0.DotTiledBacking:completeAnimation()
			f10_arg0.DotTiledBacking.TiledShaderImage:completeAnimation()
			f10_arg0.DotTiledBacking.TiledShaderImage:setRGB( 0.22, 0.22, 0.22 )
			f10_local4( f10_arg0.DotTiledBacking )
			local f10_local5 = function ( f17_arg0 )
				f10_arg0.MiddleTextFocus:beginAnimation( 200 )
				f10_arg0.MiddleTextFocus:setAlpha( 1 )
				f10_arg0.MiddleTextFocus:registerEventHandler( "interrupted_keyframe", f10_arg0.clipInterrupted )
				f10_arg0.MiddleTextFocus:registerEventHandler( "transition_complete_keyframe", f10_arg0.clipFinished )
			end
			
			f10_arg0.MiddleTextFocus:completeAnimation()
			f10_arg0.MiddleTextFocus:setRGB( 0.28, 0.25, 0.24 )
			f10_arg0.MiddleTextFocus:setAlpha( 0 )
			f10_local5( f10_arg0.MiddleTextFocus )
			local f10_local6 = function ( f18_arg0 )
				f10_arg0.MiddleText:beginAnimation( 200 )
				f10_arg0.MiddleText:setAlpha( 0 )
				f10_arg0.MiddleText:registerEventHandler( "interrupted_keyframe", f10_arg0.clipInterrupted )
				f10_arg0.MiddleText:registerEventHandler( "transition_complete_keyframe", f10_arg0.clipFinished )
			end
			
			f10_arg0.MiddleText:completeAnimation()
			f10_arg0.MiddleText:setRGB( ColorSet.T8__BIEGE.r, ColorSet.T8__BIEGE.g, ColorSet.T8__BIEGE.b )
			f10_arg0.MiddleText:setAlpha( 1 )
			f10_local6( f10_arg0.MiddleText )
			local f10_local7 = function ( f19_arg0 )
				f10_arg0.lockImage:beginAnimation( 200 )
				f10_arg0.lockImage:setScale( 1.2, 1.2 )
				f10_arg0.lockImage:registerEventHandler( "interrupted_keyframe", f10_arg0.clipInterrupted )
				f10_arg0.lockImage:registerEventHandler( "transition_complete_keyframe", f10_arg0.clipFinished )
			end
			
			f10_arg0.lockImage:completeAnimation()
			f10_arg0.lockImage:setScale( 0.6, 0.6 )
			f10_local7( f10_arg0.lockImage )
			local f10_local8 = function ( f20_arg0 )
				f10_arg0.Lines:beginAnimation( 200 )
				f10_arg0.Lines:setAlpha( 0 )
				f10_arg0.Lines:registerEventHandler( "interrupted_keyframe", f10_arg0.clipInterrupted )
				f10_arg0.Lines:registerEventHandler( "transition_complete_keyframe", f10_arg0.clipFinished )
			end
			
			f10_arg0.Lines:completeAnimation()
			f10_arg0.Lines:setAlpha( 1 )
			f10_local8( f10_arg0.Lines )
			f10_arg0.leagueOrdinalRank:completeAnimation()
			f10_arg0.leagueOrdinalRank:setAlpha( 1 )
			f10_arg0.clipFinished( f10_arg0.leagueOrdinalRank )
			local f10_local9 = function ( f21_arg0 )
				f10_arg0.leagueRank:beginAnimation( 200 )
				f10_arg0.leagueRank:setRGB( 0.28, 0.25, 0.24 )
				f10_arg0.leagueRank:registerEventHandler( "interrupted_keyframe", f10_arg0.clipInterrupted )
				f10_arg0.leagueRank:registerEventHandler( "transition_complete_keyframe", f10_arg0.clipFinished )
			end
			
			f10_arg0.leagueRank:completeAnimation()
			f10_arg0.leagueRank:setRGB( ColorSet.T8__OCHRE.r, ColorSet.T8__OCHRE.g, ColorSet.T8__OCHRE.b )
			f10_arg0.leagueRank:setAlpha( 1 )
			f10_local9( f10_arg0.leagueRank )
		end,
		LoseFocus = function ( f22_arg0, f22_arg1 )
			f22_arg0:__resetProperties()
			f22_arg0:setupElementClipCounter( 12 )
			local f22_local0 = function ( f23_arg0 )
				f22_arg0.FocusBrackets:beginAnimation( 60, Enum[0xF50FFF429AB1890][0x53CEB9A0427197] )
				f22_arg0.FocusBrackets:setAlpha( 0 )
				f22_arg0.FocusBrackets:registerEventHandler( "interrupted_keyframe", f22_arg0.clipInterrupted )
				f22_arg0.FocusBrackets:registerEventHandler( "transition_complete_keyframe", f22_arg0.clipFinished )
			end
			
			f22_arg0.FocusBrackets:completeAnimation()
			f22_arg0.FocusBrackets:setLeftRight( 0, 1, -10, 10 )
			f22_arg0.FocusBrackets:setTopBottom( 0, 1, -10, 10 )
			f22_arg0.FocusBrackets:setAlpha( 1 )
			f22_local0( f22_arg0.FocusBrackets )
			local f22_local1 = function ( f24_arg0 )
				f22_arg0.FrontendFrameSelected:beginAnimation( 200, Enum[0xF50FFF429AB1890][0x5193EA7825DC097] )
				f22_arg0.FrontendFrameSelected:setAlpha( 0 )
				f22_arg0.FrontendFrameSelected:registerEventHandler( "interrupted_keyframe", f22_arg0.clipInterrupted )
				f22_arg0.FrontendFrameSelected:registerEventHandler( "transition_complete_keyframe", f22_arg0.clipFinished )
			end
			
			f22_arg0.FrontendFrameSelected:completeAnimation()
			f22_arg0.FrontendFrameSelected:setAlpha( 0.1 )
			f22_local1( f22_arg0.FrontendFrameSelected )
			local f22_local2 = function ( f25_arg0 )
				f22_arg0.FocusGlow:beginAnimation( 200 )
				f22_arg0.FocusGlow:setAlpha( 0 )
				f22_arg0.FocusGlow:registerEventHandler( "interrupted_keyframe", f22_arg0.clipInterrupted )
				f22_arg0.FocusGlow:registerEventHandler( "transition_complete_keyframe", f22_arg0.clipFinished )
			end
			
			f22_arg0.FocusGlow:completeAnimation()
			f22_arg0.FocusGlow:setAlpha( 1 )
			f22_local2( f22_arg0.FocusGlow )
			local f22_local3 = function ( f26_arg0 )
				f22_arg0.FocusHighlight:beginAnimation( 200 )
				f22_arg0.FocusHighlight:setAlpha( 0 )
				f22_arg0.FocusHighlight:registerEventHandler( "interrupted_keyframe", f22_arg0.clipInterrupted )
				f22_arg0.FocusHighlight:registerEventHandler( "transition_complete_keyframe", f22_arg0.clipFinished )
			end
			
			f22_arg0.FocusHighlight:completeAnimation()
			f22_arg0.FocusHighlight:setAlpha( 0.8 )
			f22_local3( f22_arg0.FocusHighlight )
			local f22_local4 = function ( f27_arg0 )
				f22_arg0.DotTiledBacking:beginAnimation( 200 )
				f22_arg0.DotTiledBacking.TiledShaderImage:beginAnimation( 200 )
				f22_arg0.DotTiledBacking.TiledShaderImage:setRGB( 0.22, 0.22, 0.22 )
				f22_arg0.DotTiledBacking:registerEventHandler( "interrupted_keyframe", f22_arg0.clipInterrupted )
				f22_arg0.DotTiledBacking:registerEventHandler( "transition_complete_keyframe", f22_arg0.clipFinished )
			end
			
			f22_arg0.DotTiledBacking:completeAnimation()
			f22_arg0.DotTiledBacking.TiledShaderImage:completeAnimation()
			f22_arg0.DotTiledBacking.TiledShaderImage:setRGB( 0.28, 0.28, 0.28 )
			f22_local4( f22_arg0.DotTiledBacking )
			local f22_local5 = function ( f28_arg0 )
				f22_arg0.MiddleTextFocus:beginAnimation( 200 )
				f22_arg0.MiddleTextFocus:setAlpha( 0 )
				f22_arg0.MiddleTextFocus:registerEventHandler( "interrupted_keyframe", f22_arg0.clipInterrupted )
				f22_arg0.MiddleTextFocus:registerEventHandler( "transition_complete_keyframe", f22_arg0.clipFinished )
			end
			
			f22_arg0.MiddleTextFocus:completeAnimation()
			f22_arg0.MiddleTextFocus:setAlpha( 1 )
			f22_arg0.MiddleTextFocus:setAlignment( Enum.LUIAlignment[0x6ED4298C93DC5ED] )
			f22_local5( f22_arg0.MiddleTextFocus )
			f22_arg0.LeaderActivityText:completeAnimation()
			f22_arg0.LeaderActivityText:setAlignment( Enum.LUIAlignment[0x6ED4298C93DC5ED] )
			f22_arg0.clipFinished( f22_arg0.LeaderActivityText )
			local f22_local6 = function ( f29_arg0 )
				f22_arg0.MiddleText:beginAnimation( 200 )
				f22_arg0.MiddleText:setAlpha( 1 )
				f22_arg0.MiddleText:registerEventHandler( "interrupted_keyframe", f22_arg0.clipInterrupted )
				f22_arg0.MiddleText:registerEventHandler( "transition_complete_keyframe", f22_arg0.clipFinished )
			end
			
			f22_arg0.MiddleText:completeAnimation()
			f22_arg0.MiddleText:setRGB( ColorSet.T8__BIEGE.r, ColorSet.T8__BIEGE.g, ColorSet.T8__BIEGE.b )
			f22_arg0.MiddleText:setAlpha( 0 )
			f22_arg0.MiddleText:setAlignment( Enum.LUIAlignment[0x6ED4298C93DC5ED] )
			f22_local6( f22_arg0.MiddleText )
			local f22_local7 = function ( f30_arg0 )
				f22_arg0.lockImage:beginAnimation( 200 )
				f22_arg0.lockImage:setScale( 0.6, 0.6 )
				f22_arg0.lockImage:registerEventHandler( "interrupted_keyframe", f22_arg0.clipInterrupted )
				f22_arg0.lockImage:registerEventHandler( "transition_complete_keyframe", f22_arg0.clipFinished )
			end
			
			f22_arg0.lockImage:completeAnimation()
			f22_arg0.lockImage:setScale( 1.2, 1.2 )
			f22_local7( f22_arg0.lockImage )
			local f22_local8 = function ( f31_arg0 )
				f22_arg0.Lines:beginAnimation( 200 )
				f22_arg0.Lines:setAlpha( 1 )
				f22_arg0.Lines:registerEventHandler( "interrupted_keyframe", f22_arg0.clipInterrupted )
				f22_arg0.Lines:registerEventHandler( "transition_complete_keyframe", f22_arg0.clipFinished )
			end
			
			f22_arg0.Lines:completeAnimation()
			f22_arg0.Lines:setAlpha( 0 )
			f22_local8( f22_arg0.Lines )
			f22_arg0.leagueOrdinalRank:completeAnimation()
			f22_arg0.leagueOrdinalRank:setRGB( 0.28, 0.25, 0.24 )
			f22_arg0.leagueOrdinalRank:setAlpha( 1 )
			f22_arg0.clipFinished( f22_arg0.leagueOrdinalRank )
			local f22_local9 = function ( f32_arg0 )
				f22_arg0.leagueRank:beginAnimation( 200 )
				f22_arg0.leagueRank:setRGB( ColorSet.T8__OCHRE.r, ColorSet.T8__OCHRE.g, ColorSet.T8__OCHRE.b )
				f22_arg0.leagueRank:registerEventHandler( "interrupted_keyframe", f22_arg0.clipInterrupted )
				f22_arg0.leagueRank:registerEventHandler( "transition_complete_keyframe", f22_arg0.clipFinished )
			end
			
			f22_arg0.leagueRank:completeAnimation()
			f22_arg0.leagueRank:setRGB( 0.28, 0.25, 0.24 )
			f22_arg0.leagueRank:setAlpha( 1 )
			f22_local9( f22_arg0.leagueRank )
		end
	},
	Locked = {
		DefaultClip = function ( f33_arg0, f33_arg1 )
			f33_arg0:__resetProperties()
			f33_arg0:setupElementClipCounter( 5 )
			f33_arg0.NoiseTiledBacking:completeAnimation()
			f33_arg0.NoiseTiledBacking:setRGB( 0.78, 0.78, 0.78 )
			f33_arg0.clipFinished( f33_arg0.NoiseTiledBacking )
			f33_arg0.FocusBrackets:completeAnimation()
			f33_arg0.FocusBrackets:setAlpha( 0 )
			f33_arg0.clipFinished( f33_arg0.FocusBrackets )
			f33_arg0.LeaderActivityText:completeAnimation()
			f33_arg0.LeaderActivityText:setLeftRight( 0, 0, 10, 111 )
			f33_arg0.LeaderActivityText:setTopBottom( 1, 1, -64.5, -24.5 )
			f33_arg0.clipFinished( f33_arg0.LeaderActivityText )
			f33_arg0.MiddleText:completeAnimation()
			f33_arg0.MiddleText:setRGB( 0.92, 0.92, 0.92 )
			f33_arg0.MiddleText:setAlpha( 0.2 )
			f33_arg0.MiddleText:setAlignment( Enum.LUIAlignment[0x6ED4298C93DC5ED] )
			f33_arg0.clipFinished( f33_arg0.MiddleText )
			f33_arg0.lockImage:completeAnimation()
			f33_arg0.lockImage:setAlpha( 0.5 )
			f33_arg0.clipFinished( f33_arg0.lockImage )
		end,
		Focus = function ( f34_arg0, f34_arg1 )
			f34_arg0:__resetProperties()
			f34_arg0:setupElementClipCounter( 5 )
			f34_arg0.NoiseTiledBacking:completeAnimation()
			f34_arg0.NoiseTiledBacking:setRGB( 0.78, 0.78, 0.78 )
			f34_arg0.clipFinished( f34_arg0.NoiseTiledBacking )
			f34_arg0.FocusBrackets:completeAnimation()
			f34_arg0.FocusBrackets:setLeftRight( 0, 1, -10, 10 )
			f34_arg0.FocusBrackets:setTopBottom( 0, 1, -10, 10 )
			f34_arg0.FocusBrackets:setAlpha( 1 )
			f34_arg0.clipFinished( f34_arg0.FocusBrackets )
			f34_arg0.MiddleText:completeAnimation()
			f34_arg0.MiddleText:setRGB( 0.92, 0.92, 0.92 )
			f34_arg0.MiddleText:setAlpha( 0.2 )
			f34_arg0.clipFinished( f34_arg0.MiddleText )
			f34_arg0.lockImage:completeAnimation()
			f34_arg0.lockImage:setAlpha( 0.5 )
			f34_arg0.clipFinished( f34_arg0.lockImage )
			f34_arg0.FocusBorder:completeAnimation()
			f34_arg0.FocusBorder:setRGB( ColorSet.T8__OFF__WHITE.r, ColorSet.T8__OFF__WHITE.g, ColorSet.T8__OFF__WHITE.b )
			f34_arg0.FocusBorder:setAlpha( 0.25 )
			f34_arg0.clipFinished( f34_arg0.FocusBorder )
		end,
		GainFocus = function ( f35_arg0, f35_arg1 )
			f35_arg0:__resetProperties()
			f35_arg0:setupElementClipCounter( 5 )
			f35_arg0.NoiseTiledBacking:completeAnimation()
			f35_arg0.NoiseTiledBacking:setRGB( 0.78, 0.78, 0.78 )
			f35_arg0.clipFinished( f35_arg0.NoiseTiledBacking )
			local f35_local0 = function ( f36_arg0 )
				local f36_local0 = function ( f37_arg0 )
					f37_arg0:beginAnimation( 50, Enum[0xF50FFF429AB1890][0x6F6186B702830BC] )
					f37_arg0:setLeftRight( 0, 1, -10, 10 )
					f37_arg0:setTopBottom( 0, 1, -10, 10 )
					f37_arg0:setAlpha( 1 )
					f37_arg0:registerEventHandler( "transition_complete_keyframe", f35_arg0.clipFinished )
				end
				
				f35_arg0.FocusBrackets:beginAnimation( 100 )
				f35_arg0.FocusBrackets:setLeftRight( 0, 1, -8, 8 )
				f35_arg0.FocusBrackets:setTopBottom( 0, 1, -8, 8 )
				f35_arg0.FocusBrackets:setAlpha( 0.75 )
				f35_arg0.FocusBrackets:registerEventHandler( "interrupted_keyframe", f35_arg0.clipInterrupted )
				f35_arg0.FocusBrackets:registerEventHandler( "transition_complete_keyframe", f36_local0 )
			end
			
			f35_arg0.FocusBrackets:completeAnimation()
			f35_arg0.FocusBrackets:setLeftRight( 0, 1, -40, 40 )
			f35_arg0.FocusBrackets:setTopBottom( 0, 1, -40, 40 )
			f35_arg0.FocusBrackets:setAlpha( 0 )
			f35_local0( f35_arg0.FocusBrackets )
			f35_arg0.MiddleText:completeAnimation()
			f35_arg0.MiddleText:setRGB( 0.92, 0.92, 0.92 )
			f35_arg0.MiddleText:setAlpha( 0.2 )
			f35_arg0.clipFinished( f35_arg0.MiddleText )
			f35_arg0.lockImage:completeAnimation()
			f35_arg0.lockImage:setAlpha( 0.5 )
			f35_arg0.clipFinished( f35_arg0.lockImage )
			local f35_local1 = function ( f38_arg0 )
				f35_arg0.FocusBorder:beginAnimation( 200 )
				f35_arg0.FocusBorder:setAlpha( 0.25 )
				f35_arg0.FocusBorder:registerEventHandler( "interrupted_keyframe", f35_arg0.clipInterrupted )
				f35_arg0.FocusBorder:registerEventHandler( "transition_complete_keyframe", f35_arg0.clipFinished )
			end
			
			f35_arg0.FocusBorder:completeAnimation()
			f35_arg0.FocusBorder:setRGB( ColorSet.T8__OFF__WHITE.r, ColorSet.T8__OFF__WHITE.g, ColorSet.T8__OFF__WHITE.b )
			f35_arg0.FocusBorder:setAlpha( 0 )
			f35_local1( f35_arg0.FocusBorder )
		end,
		LoseFocus = function ( f39_arg0, f39_arg1 )
			f39_arg0:__resetProperties()
			f39_arg0:setupElementClipCounter( 5 )
			f39_arg0.NoiseTiledBacking:completeAnimation()
			f39_arg0.NoiseTiledBacking:setRGB( 0.78, 0.78, 0.78 )
			f39_arg0.clipFinished( f39_arg0.NoiseTiledBacking )
			local f39_local0 = function ( f40_arg0 )
				f39_arg0.FocusBrackets:beginAnimation( 60, Enum[0xF50FFF429AB1890][0x53CEB9A0427197] )
				f39_arg0.FocusBrackets:setAlpha( 0 )
				f39_arg0.FocusBrackets:registerEventHandler( "interrupted_keyframe", f39_arg0.clipInterrupted )
				f39_arg0.FocusBrackets:registerEventHandler( "transition_complete_keyframe", f39_arg0.clipFinished )
			end
			
			f39_arg0.FocusBrackets:completeAnimation()
			f39_arg0.FocusBrackets:setLeftRight( 0, 1, -10, 10 )
			f39_arg0.FocusBrackets:setTopBottom( 0, 1, -10, 10 )
			f39_arg0.FocusBrackets:setAlpha( 1 )
			f39_local0( f39_arg0.FocusBrackets )
			f39_arg0.MiddleText:completeAnimation()
			f39_arg0.MiddleText:setRGB( 0.92, 0.92, 0.92 )
			f39_arg0.MiddleText:setAlpha( 0.2 )
			f39_arg0.clipFinished( f39_arg0.MiddleText )
			f39_arg0.lockImage:completeAnimation()
			f39_arg0.lockImage:setAlpha( 0.5 )
			f39_arg0.clipFinished( f39_arg0.lockImage )
			local f39_local1 = function ( f41_arg0 )
				f39_arg0.FocusBorder:beginAnimation( 200 )
				f39_arg0.FocusBorder:setAlpha( 0 )
				f39_arg0.FocusBorder:registerEventHandler( "interrupted_keyframe", f39_arg0.clipInterrupted )
				f39_arg0.FocusBorder:registerEventHandler( "transition_complete_keyframe", f39_arg0.clipFinished )
			end
			
			f39_arg0.FocusBorder:completeAnimation()
			f39_arg0.FocusBorder:setRGB( ColorSet.T8__OFF__WHITE.r, ColorSet.T8__OFF__WHITE.g, ColorSet.T8__OFF__WHITE.b )
			f39_arg0.FocusBorder:setAlpha( 0.25 )
			f39_local1( f39_arg0.FocusBorder )
		end
	},
	Disabled = {
		DefaultClip = function ( f42_arg0, f42_arg1 )
			f42_arg0:__resetProperties()
			f42_arg0:setupElementClipCounter( 5 )
			f42_arg0.FocusBrackets:completeAnimation()
			f42_arg0.FocusBrackets:setAlpha( 0 )
			f42_arg0.clipFinished( f42_arg0.FocusBrackets )
			f42_arg0.MiddleText:completeAnimation()
			f42_arg0.MiddleText:setRGB( 0.31, 0.29, 0.29 )
			f42_arg0.MiddleText:setAlpha( 1 )
			f42_arg0.clipFinished( f42_arg0.MiddleText )
			f42_arg0.lockImage:completeAnimation()
			f42_arg0.lockImage:setScale( 1.2, 1.2 )
			f42_arg0.clipFinished( f42_arg0.lockImage )
			f42_arg0.Lines:completeAnimation()
			f42_arg0.Lines:setAlpha( 0.5 )
			f42_arg0.clipFinished( f42_arg0.Lines )
			f42_arg0.FocusBorder:completeAnimation()
			f42_arg0.FocusBorder:setRGB( ColorSet.T8__OFF__WHITE.r, ColorSet.T8__OFF__WHITE.g, ColorSet.T8__OFF__WHITE.b )
			f42_arg0.clipFinished( f42_arg0.FocusBorder )
		end,
		Focus = function ( f43_arg0, f43_arg1 )
			f43_arg0:__resetProperties()
			f43_arg0:setupElementClipCounter( 5 )
			f43_arg0.FocusBrackets:completeAnimation()
			f43_arg0.FocusBrackets:setLeftRight( 0, 1, -10, 10 )
			f43_arg0.FocusBrackets:setTopBottom( 0, 1, -10, 10 )
			f43_arg0.FocusBrackets:setAlpha( 1 )
			f43_arg0.clipFinished( f43_arg0.FocusBrackets )
			f43_arg0.MiddleText:completeAnimation()
			f43_arg0.MiddleText:setRGB( 0.31, 0.29, 0.29 )
			f43_arg0.MiddleText:setAlpha( 1 )
			f43_arg0.clipFinished( f43_arg0.MiddleText )
			f43_arg0.lockImage:completeAnimation()
			f43_arg0.lockImage:setScale( 1.2, 1.2 )
			f43_arg0.clipFinished( f43_arg0.lockImage )
			f43_arg0.Lines:completeAnimation()
			f43_arg0.Lines:setAlpha( 0.5 )
			f43_arg0.clipFinished( f43_arg0.Lines )
			f43_arg0.FocusBorder:completeAnimation()
			f43_arg0.FocusBorder:setRGB( ColorSet.T8__OFF__WHITE.r, ColorSet.T8__OFF__WHITE.g, ColorSet.T8__OFF__WHITE.b )
			f43_arg0.FocusBorder:setAlpha( 0.25 )
			f43_arg0.clipFinished( f43_arg0.FocusBorder )
		end,
		GainFocus = function ( f44_arg0, f44_arg1 )
			f44_arg0:__resetProperties()
			f44_arg0:setupElementClipCounter( 5 )
			local f44_local0 = function ( f45_arg0 )
				local f45_local0 = function ( f46_arg0 )
					f46_arg0:beginAnimation( 50, Enum[0xF50FFF429AB1890][0x6F6186B702830BC] )
					f46_arg0:setLeftRight( 0, 1, -10, 10 )
					f46_arg0:setTopBottom( 0, 1, -10, 10 )
					f46_arg0:setAlpha( 1 )
					f46_arg0:registerEventHandler( "transition_complete_keyframe", f44_arg0.clipFinished )
				end
				
				f44_arg0.FocusBrackets:beginAnimation( 100 )
				f44_arg0.FocusBrackets:setLeftRight( 0, 1, -8, 8 )
				f44_arg0.FocusBrackets:setTopBottom( 0, 1, -8, 8 )
				f44_arg0.FocusBrackets:setAlpha( 0.75 )
				f44_arg0.FocusBrackets:registerEventHandler( "interrupted_keyframe", f44_arg0.clipInterrupted )
				f44_arg0.FocusBrackets:registerEventHandler( "transition_complete_keyframe", f45_local0 )
			end
			
			f44_arg0.FocusBrackets:completeAnimation()
			f44_arg0.FocusBrackets:setLeftRight( 0, 1, -40, 40 )
			f44_arg0.FocusBrackets:setTopBottom( 0, 1, -40, 40 )
			f44_arg0.FocusBrackets:setAlpha( 0 )
			f44_local0( f44_arg0.FocusBrackets )
			f44_arg0.MiddleText:completeAnimation()
			f44_arg0.MiddleText:setRGB( 0.31, 0.29, 0.29 )
			f44_arg0.MiddleText:setAlpha( 1 )
			f44_arg0.clipFinished( f44_arg0.MiddleText )
			f44_arg0.lockImage:completeAnimation()
			f44_arg0.lockImage:setScale( 1.2, 1.2 )
			f44_arg0.clipFinished( f44_arg0.lockImage )
			f44_arg0.Lines:completeAnimation()
			f44_arg0.Lines:setAlpha( 0.5 )
			f44_arg0.clipFinished( f44_arg0.Lines )
			local f44_local1 = function ( f47_arg0 )
				f44_arg0.FocusBorder:beginAnimation( 200 )
				f44_arg0.FocusBorder:setAlpha( 0.25 )
				f44_arg0.FocusBorder:registerEventHandler( "interrupted_keyframe", f44_arg0.clipInterrupted )
				f44_arg0.FocusBorder:registerEventHandler( "transition_complete_keyframe", f44_arg0.clipFinished )
			end
			
			f44_arg0.FocusBorder:completeAnimation()
			f44_arg0.FocusBorder:setRGB( ColorSet.T8__OFF__WHITE.r, ColorSet.T8__OFF__WHITE.g, ColorSet.T8__OFF__WHITE.b )
			f44_arg0.FocusBorder:setAlpha( 0 )
			f44_local1( f44_arg0.FocusBorder )
		end,
		LoseFocus = function ( f48_arg0, f48_arg1 )
			f48_arg0:__resetProperties()
			f48_arg0:setupElementClipCounter( 5 )
			local f48_local0 = function ( f49_arg0 )
				f48_arg0.FocusBrackets:beginAnimation( 60 )
				f48_arg0.FocusBrackets:setAlpha( 0 )
				f48_arg0.FocusBrackets:registerEventHandler( "interrupted_keyframe", f48_arg0.clipInterrupted )
				f48_arg0.FocusBrackets:registerEventHandler( "transition_complete_keyframe", f48_arg0.clipFinished )
			end
			
			f48_arg0.FocusBrackets:completeAnimation()
			f48_arg0.FocusBrackets:setLeftRight( 0, 1, -10, 10 )
			f48_arg0.FocusBrackets:setTopBottom( 0, 1, -10, 10 )
			f48_arg0.FocusBrackets:setAlpha( 1 )
			f48_local0( f48_arg0.FocusBrackets )
			f48_arg0.MiddleText:completeAnimation()
			f48_arg0.MiddleText:setRGB( 0.31, 0.29, 0.29 )
			f48_arg0.MiddleText:setAlpha( 1 )
			f48_arg0.clipFinished( f48_arg0.MiddleText )
			f48_arg0.lockImage:completeAnimation()
			f48_arg0.lockImage:setScale( 1.2, 1.2 )
			f48_arg0.clipFinished( f48_arg0.lockImage )
			f48_arg0.Lines:completeAnimation()
			f48_arg0.Lines:setAlpha( 0.5 )
			f48_arg0.clipFinished( f48_arg0.Lines )
			local f48_local1 = function ( f50_arg0 )
				f48_arg0.FocusBorder:beginAnimation( 200 )
				f48_arg0.FocusBorder:setAlpha( 0 )
				f48_arg0.FocusBorder:registerEventHandler( "interrupted_keyframe", f48_arg0.clipInterrupted )
				f48_arg0.FocusBorder:registerEventHandler( "transition_complete_keyframe", f48_arg0.clipFinished )
			end
			
			f48_arg0.FocusBorder:completeAnimation()
			f48_arg0.FocusBorder:setRGB( ColorSet.T8__OFF__WHITE.r, ColorSet.T8__OFF__WHITE.g, ColorSet.T8__OFF__WHITE.b )
			f48_arg0.FocusBorder:setAlpha( 0.25 )
			f48_local1( f48_arg0.FocusBorder )
		end
	}
}
CoD.ArenaEventButtonInternal.__onClose = function ( f51_arg0 )
	f51_arg0.FocusBrackets:close()
	f51_arg0.DotTiledBacking:close()
	f51_arg0.Lines:close()
	f51_arg0.leagueOrdinalRank:close()
	f51_arg0.leagueRank:close()
end

