require( "ui/uieditor/widgets/director/directorselectbuttonlines" )

CoD.DirectorSelectButtonInternal = InheritFrom( LUI.UIElement )
CoD.DirectorSelectButtonInternal.__defaultWidth = 280
CoD.DirectorSelectButtonInternal.__defaultHeight = 214
CoD.DirectorSelectButtonInternal.new = function ( f1_arg0, f1_arg1, f1_arg2, f1_arg3, f1_arg4, f1_arg5, f1_arg6, f1_arg7, f1_arg8, f1_arg9 )
	local self = LUI.UIElement.new( f1_arg2, f1_arg3, f1_arg4, f1_arg5, f1_arg6, f1_arg7, f1_arg8, f1_arg9 )
	self:setClass( CoD.DirectorSelectButtonInternal )
	self.id = "DirectorSelectButtonInternal"
	self.soundSet = "default"
	f1_arg0:addElementToPendingUpdateStateList( self )
	
	local SceneBlur = LUI.UIImage.new( 0, 1, 0, 0, 0, 1, 12, 0 )
	SceneBlur:setAlpha( 0 )
	SceneBlur:setMaterial( LUI.UIImage.GetCachedMaterial( 0xE2354BE557C4C7A ) )
	SceneBlur:setShaderVector( 0, 0, 0, 0, 0 )
	self:addElement( SceneBlur )
	self.SceneBlur = SceneBlur
	
	local ButtonBG = LUI.UIImage.new( 0, 1, 0, 0, 0, 1, 12, 0 )
	ButtonBG:setRGB( 0.38, 0.38, 0.38 )
	ButtonBG:setAlpha( 0.8 )
	ButtonBG:setImage( RegisterImage( 0xE3211044E61E1BB ) )
	self:addElement( ButtonBG )
	self.ButtonBG = ButtonBG
	
	local ButtonBGPC = nil
	
	ButtonBGPC = LUI.UIImage.new( 0, 1, 0, 0, 0, 1, 12, 0 )
	ButtonBGPC:setRGB( 0.38, 0.38, 0.38 )
	ButtonBGPC:setAlpha( 0 )
	ButtonBGPC:setImage( RegisterImage( 0xE3211044E61E1BB ) )
	self:addElement( ButtonBGPC )
	self.ButtonBGPC = ButtonBGPC
	
	local Image = LUI.UIImage.new( 0, 1, 0, 0, 0, 0.94, 12, 12 )
	Image:setRGB( 0.89, 0.94, 0.99 )
	Image:setAlpha( 0 )
	self:addElement( Image )
	self.Image = Image
	
	local PixelGrid = LUI.UIImage.new( 0, 1, 0, 0, 0, 1, 12, 0 )
	PixelGrid:setAlpha( 0.05 )
	PixelGrid:setImage( RegisterImage( 0x311E811A3183347 ) )
	PixelGrid:setMaterial( LUI.UIImage.GetCachedMaterial( 0x6CBE95C250C6D15 ) )
	PixelGrid:setShaderVector( 0, 0, 0, 0, 0 )
	PixelGrid:setupNineSliceShader( 128, 128 )
	self:addElement( PixelGrid )
	self.PixelGrid = PixelGrid
	
	local ImageNotFocus = LUI.UIImage.new( 0, 1, 0, 0, 0, 1, 12, 0 )
	ImageNotFocus:setAlpha( 0 )
	ImageNotFocus:setMaterial( LUI.UIImage.GetCachedMaterial( "uie_saturation_normal" ) )
	ImageNotFocus:setShaderVector( 0, 1, 0, 0, 0 )
	ImageNotFocus:linkToElementModel( self, "iconBackground", true, function ( model )
		local f2_local0 = model:get()
		if f2_local0 ~= nil then
			ImageNotFocus:setImage( RegisterImage( f2_local0 ) )
		end
	end )
	self:addElement( ImageNotFocus )
	self.ImageNotFocus = ImageNotFocus
	
	local ImageFocus = LUI.UIImage.new( 0, 1, 0, 0, 0, 1, 12, 0 )
	ImageFocus:setAlpha( 0 )
	self:addElement( ImageFocus )
	self.ImageFocus = ImageFocus
	
	local TextBacking = LUI.UIImage.new( 0, 1, 0, 0, 1, 1, -33, 0 )
	TextBacking:setRGB( 0.07, 0.07, 0.07 )
	TextBacking:setAlpha( 0 )
	self:addElement( TextBacking )
	self.TextBacking = TextBacking
	
	local Lines = CoD.DirectorSelectButtonLines.new( f1_arg0, f1_arg1, 0, 1, 0, 0, 0, 1, 12, 0 )
	Lines:setAlpha( 0.15 )
	self:addElement( Lines )
	self.Lines = Lines
	
	local ButtonBGGlow = LUI.UIImage.new( 0, 1, 0, 0, 0, 1, 12, 0 )
	ButtonBGGlow:setAlpha( 0 )
	ButtonBGGlow:setImage( RegisterImage( 0x418AFBD55D4236F ) )
	ButtonBGGlow:setMaterial( LUI.UIImage.GetCachedMaterial( 0xC221B51E4063E3D ) )
	ButtonBGGlow:setShaderVector( 0, 0.34, 0, 0, 0 )
	ButtonBGGlow:setShaderVector( 1, 3, 0.71, 0, 0 )
	ButtonBGGlow:setShaderVector( 2, 0, 0, 0, 0 )
	self:addElement( ButtonBGGlow )
	self.ButtonBGGlow = ButtonBGGlow
	
	local TopBar = LUI.UIImage.new( -0.03, 1.03, 0, 0, 1, 1, 0, 12 )
	TopBar:setAlpha( 0.1 )
	TopBar:setImage( RegisterImage( 0xCE32B5C3D0E9039 ) )
	TopBar:setMaterial( LUI.UIImage.GetCachedMaterial( "ui_add" ) )
	self:addElement( TopBar )
	self.TopBar = TopBar
	
	local TopBarFocus = LUI.UIImage.new( -0.03, 1.03, 0, 0, 1, 1, 0, 12 )
	TopBarFocus:setRGB( ColorSet.T8__BIEGE.r, ColorSet.T8__BIEGE.g, ColorSet.T8__BIEGE.b )
	TopBarFocus:setAlpha( 0 )
	TopBarFocus:setImage( RegisterImage( 0x4684BE3938F5367 ) )
	TopBarFocus:setMaterial( LUI.UIImage.GetCachedMaterial( "ui_add" ) )
	self:addElement( TopBarFocus )
	self.TopBarFocus = TopBarFocus
	
	local lockImage = LUI.UIImage.new( 1, 1, -38, 12, 0, 0, 3, 53 )
	lockImage:setAlpha( 0 )
	lockImage:setScale( 0.6, 0.6 )
	lockImage:setImage( RegisterImage( "uie_ui_icon_global_lock" ) )
	self:addElement( lockImage )
	self.lockImage = lockImage
	
	local LeaderActivityText = LUI.UIText.new( 0, 0, 9, 278, 1, 1, -53.5, -33.5 )
	LeaderActivityText:setRGB( 0.63, 0.62, 0.61 )
	LeaderActivityText:setAlpha( 0.5 )
	LeaderActivityText:setText( Engine[0xF9F1239CFD921FE]( "menu/new" ) )
	LeaderActivityText:setTTF( "ttmussels_regular" )
	LeaderActivityText:setLetterSpacing( 4 )
	LeaderActivityText:setAlignment( Enum.LUIAlignment[0x58C8A85F2048829] )
	LeaderActivityText:setAlignment( Enum.LUIAlignment[0xF41D595A2B0EDF3] )
	self:addElement( LeaderActivityText )
	self.LeaderActivityText = LeaderActivityText
	
	local Header = LUI.UIText.new( 0.01, 0.97, 9, 9, 1, 1, -26.5, -4.5 )
	Header:setRGB( ColorSet.T8__BIEGE.r, ColorSet.T8__BIEGE.g, ColorSet.T8__BIEGE.b )
	Header:setText( LocalizeToUpperString( 0xA43B10D9DA121A ) )
	Header:setTTF( "ttmussels_regular" )
	Header:setMaterial( LUI.UIImage.GetCachedMaterial( 0x71E049B161CD00A ) )
	Header:setLetterSpacing( 6 )
	Header:setAlignment( Enum.LUIAlignment[0x58C8A85F2048829] )
	Header:setAlignment( Enum.LUIAlignment[0xF41D595A2B0EDF3] )
	self:addElement( Header )
	self.Header = Header
	
	local MiddleText = LUI.UIText.new( 0.02, 0.98, 0, 0, 0.57, 0.57, -10, 12 )
	MiddleText:setText( LocalizeToUpperString( 0xA43B10D9DA121A ) )
	MiddleText:setTTF( "ttmussels_regular" )
	MiddleText:setLetterSpacing( 6 )
	MiddleText:setAlignment( Enum.LUIAlignment[0xFEEB12BCB0D7041] )
	MiddleText:setAlignment( Enum.LUIAlignment[0x6ED4298C93DC5ED] )
	self:addElement( MiddleText )
	self.MiddleText = MiddleText
	
	local circle = LUI.UIImage.new( 0.5, 0.5, -152, -92, 0.55, 0.55, -14, 46 )
	circle:setRGB( 0.19, 0.19, 0.19 )
	circle:setAlpha( 0 )
	circle:setZRot( 180 )
	circle:setScale( 1.05, 1.05 )
	circle:setMaterial( LUI.UIImage.GetCachedMaterial( 0x15B163CA03FCE8B ) )
	circle:setShaderVector( 0, 4.66, 0, 0, 0 )
	circle:setShaderVector( 1, 80, 80, 0, 0 )
	circle:setShaderVector( 2, 0, 0, 0, 0 )
	self:addElement( circle )
	self.circle = circle
	
	local timer = LUI.UIText.new( 0.5, 0.5, -160, -80, 0.55, 0.55, -10, 48 )
	timer:setRGB( 0, 0, 0 )
	timer:setAlpha( 0 )
	timer:setTTF( "ttmussels_demibold" )
	timer:setLetterSpacing( -6.3 )
	timer:setAlignment( Enum.LUIAlignment[0xFEEB12BCB0D7041] )
	timer:setAlignment( Enum.LUIAlignment[0xF41D595A2B0EDF3] )
	timer:subscribeToGlobalModel( f1_arg1, "LobbyRoot", "lobbyTimeRemaining", function ( model )
		local f3_local0 = model:get()
		if f3_local0 ~= nil then
			timer:setText( f3_local0 )
		end
	end )
	self:addElement( timer )
	self.timer = timer
	
	local CountdownText = LUI.UIText.new( 0.5, 0.5, -75, -20, 0.55, 0.55, 0, 33 )
	CountdownText:setRGB( 0.05, 0.05, 0.05 )
	CountdownText:setAlpha( 0 )
	CountdownText:setTTF( "ttmussels_regular" )
	CountdownText:setAlignment( Enum.LUIAlignment[0x58C8A85F2048829] )
	CountdownText:subscribeToGlobalModel( f1_arg1, "LobbyRoot", "lobbyStatus", function ( model )
		local f4_local0 = model:get()
		if f4_local0 ~= nil then
			CountdownText:setText( ToUpper( f4_local0 ) )
		end
	end )
	self:addElement( CountdownText )
	self.CountdownText = CountdownText
	
	LUI.OverrideFunction_CallOriginalSecond( self, "close", self.__onClose )
	
	if PostLoadFunc then
		PostLoadFunc( self, f1_arg1, f1_arg0 )
	end
	
	return self
end

CoD.DirectorSelectButtonInternal.__resetProperties = function ( f5_arg0 )
	f5_arg0.Header:completeAnimation()
	f5_arg0.LeaderActivityText:completeAnimation()
	f5_arg0.ButtonBG:completeAnimation()
	f5_arg0.ButtonBGGlow:completeAnimation()
	f5_arg0.lockImage:completeAnimation()
	f5_arg0.TopBar:completeAnimation()
	f5_arg0.Lines:completeAnimation()
	f5_arg0.MiddleText:completeAnimation()
	f5_arg0.Image:completeAnimation()
	f5_arg0.TopBarFocus:completeAnimation()
	f5_arg0.PixelGrid:completeAnimation()
	f5_arg0.ImageNotFocus:completeAnimation()
	f5_arg0.Header:setAlpha( 1 )
	f5_arg0.LeaderActivityText:setAlpha( 0.5 )
	f5_arg0.ButtonBG:setRGB( 0.38, 0.38, 0.38 )
	f5_arg0.ButtonBG:setAlpha( 0.8 )
	f5_arg0.ButtonBGGlow:setAlpha( 0 )
	f5_arg0.lockImage:setAlpha( 0 )
	f5_arg0.lockImage:setScale( 0.6, 0.6 )
	f5_arg0.TopBar:setRGB( 1, 1, 1 )
	f5_arg0.TopBar:setAlpha( 0.1 )
	f5_arg0.Lines:setRGB( 1, 1, 1 )
	f5_arg0.Lines:setAlpha( 0.15 )
	f5_arg0.MiddleText:setRGB( 1, 1, 1 )
	f5_arg0.MiddleText:setAlpha( 1 )
	f5_arg0.Image:setAlpha( 0 )
	f5_arg0.TopBarFocus:setRGB( ColorSet.T8__BIEGE.r, ColorSet.T8__BIEGE.g, ColorSet.T8__BIEGE.b )
	f5_arg0.TopBarFocus:setAlpha( 0 )
	f5_arg0.PixelGrid:setRGB( 1, 1, 1 )
	f5_arg0.PixelGrid:setAlpha( 0.05 )
	f5_arg0.ImageNotFocus:setRGB( 1, 1, 1 )
	f5_arg0.ImageNotFocus:setMaterial( LUI.UIImage.GetCachedMaterial( "uie_saturation_normal" ) )
	f5_arg0.ImageNotFocus:setShaderVector( 0, 1, 0, 0, 0 )
end

CoD.DirectorSelectButtonInternal.__clipsPerState = {
	DefaultState = {
		DefaultClip = function ( f6_arg0, f6_arg1 )
			f6_arg0:__resetProperties()
			f6_arg0:setupElementClipCounter( 3 )
			f6_arg0.ButtonBG:completeAnimation()
			f6_arg0.ButtonBG:setRGB( 0.38, 0.38, 0.38 )
			f6_arg0.ButtonBG:setAlpha( 0.8 )
			f6_arg0.clipFinished( f6_arg0.ButtonBG )
			f6_arg0.LeaderActivityText:completeAnimation()
			f6_arg0.LeaderActivityText:setAlpha( 0.2 )
			f6_arg0.clipFinished( f6_arg0.LeaderActivityText )
			f6_arg0.Header:completeAnimation()
			f6_arg0.Header:setAlpha( 1 )
			f6_arg0.clipFinished( f6_arg0.Header )
		end,
		Focus = function ( f7_arg0, f7_arg1 )
			f7_arg0:__resetProperties()
			f7_arg0:setupElementClipCounter( 9 )
			f7_arg0.ButtonBG:completeAnimation()
			f7_arg0.ButtonBG:setRGB( 1, 1, 1 )
			f7_arg0.ButtonBG:setAlpha( 0.4 )
			f7_arg0.clipFinished( f7_arg0.ButtonBG )
			f7_arg0.Image:completeAnimation()
			f7_arg0.Image:setAlpha( 0 )
			f7_arg0.clipFinished( f7_arg0.Image )
			f7_arg0.PixelGrid:completeAnimation()
			f7_arg0.PixelGrid:setRGB( 1, 1, 1 )
			f7_arg0.PixelGrid:setAlpha( 0.05 )
			f7_arg0.clipFinished( f7_arg0.PixelGrid )
			f7_arg0.Lines:completeAnimation()
			f7_arg0.Lines:setRGB( 0.85, 0.85, 0.85 )
			f7_arg0.Lines:setAlpha( 0.7 )
			f7_arg0.clipFinished( f7_arg0.Lines )
			f7_arg0.ButtonBGGlow:completeAnimation()
			f7_arg0.ButtonBGGlow:setAlpha( 0 )
			f7_arg0.clipFinished( f7_arg0.ButtonBGGlow )
			f7_arg0.TopBar:completeAnimation()
			f7_arg0.TopBar:setRGB( ColorSet.T8__BIEGE.r, ColorSet.T8__BIEGE.g, ColorSet.T8__BIEGE.b )
			f7_arg0.TopBar:setAlpha( 0.77 )
			f7_arg0.clipFinished( f7_arg0.TopBar )
			f7_arg0.TopBarFocus:completeAnimation()
			f7_arg0.TopBarFocus:setRGB( 1, 1, 1 )
			f7_arg0.TopBarFocus:setAlpha( 0.74 )
			f7_arg0.clipFinished( f7_arg0.TopBarFocus )
			f7_arg0.lockImage:completeAnimation()
			f7_arg0.lockImage:setScale( 1.2, 1.2 )
			f7_arg0.clipFinished( f7_arg0.lockImage )
			f7_arg0.MiddleText:completeAnimation()
			f7_arg0.MiddleText:setRGB( ColorSet.T8__BIEGE.r, ColorSet.T8__BIEGE.g, ColorSet.T8__BIEGE.b )
			f7_arg0.clipFinished( f7_arg0.MiddleText )
		end,
		GainFocus = function ( f8_arg0, f8_arg1 )
			f8_arg0:__resetProperties()
			f8_arg0:setupElementClipCounter( 11 )
			local f8_local0 = function ( f9_arg0 )
				f8_arg0.ButtonBG:beginAnimation( 200 )
				f8_arg0.ButtonBG:setRGB( 1, 1, 1 )
				f8_arg0.ButtonBG:setAlpha( 0.4 )
				f8_arg0.ButtonBG:registerEventHandler( "interrupted_keyframe", f8_arg0.clipInterrupted )
				f8_arg0.ButtonBG:registerEventHandler( "transition_complete_keyframe", f8_arg0.clipFinished )
			end
			
			f8_arg0.ButtonBG:completeAnimation()
			f8_arg0.ButtonBG:setRGB( 0.38, 0.38, 0.38 )
			f8_arg0.ButtonBG:setAlpha( 0.8 )
			f8_local0( f8_arg0.ButtonBG )
			f8_arg0.Image:completeAnimation()
			f8_arg0.Image:setAlpha( 0 )
			f8_arg0.clipFinished( f8_arg0.Image )
			f8_arg0.PixelGrid:completeAnimation()
			f8_arg0.PixelGrid:setRGB( 1, 1, 1 )
			f8_arg0.PixelGrid:setAlpha( 0.05 )
			f8_arg0.clipFinished( f8_arg0.PixelGrid )
			local f8_local1 = function ( f10_arg0 )
				f8_arg0.Lines:beginAnimation( 200 )
				f8_arg0.Lines:setRGB( 0.85, 0.85, 0.85 )
				f8_arg0.Lines:setAlpha( 0.7 )
				f8_arg0.Lines:registerEventHandler( "interrupted_keyframe", f8_arg0.clipInterrupted )
				f8_arg0.Lines:registerEventHandler( "transition_complete_keyframe", f8_arg0.clipFinished )
			end
			
			f8_arg0.Lines:completeAnimation()
			f8_arg0.Lines:setRGB( 1, 1, 1 )
			f8_arg0.Lines:setAlpha( 0.15 )
			f8_local1( f8_arg0.Lines )
			f8_arg0.ButtonBGGlow:completeAnimation()
			f8_arg0.ButtonBGGlow:setAlpha( 0 )
			f8_arg0.clipFinished( f8_arg0.ButtonBGGlow )
			local f8_local2 = function ( f11_arg0 )
				f8_arg0.TopBar:beginAnimation( 200 )
				f8_arg0.TopBar:setRGB( ColorSet.T8__BIEGE.r, ColorSet.T8__BIEGE.g, ColorSet.T8__BIEGE.b )
				f8_arg0.TopBar:setAlpha( 0.77 )
				f8_arg0.TopBar:registerEventHandler( "interrupted_keyframe", f8_arg0.clipInterrupted )
				f8_arg0.TopBar:registerEventHandler( "transition_complete_keyframe", f8_arg0.clipFinished )
			end
			
			f8_arg0.TopBar:completeAnimation()
			f8_arg0.TopBar:setRGB( 1, 1, 1 )
			f8_arg0.TopBar:setAlpha( 0.1 )
			f8_local2( f8_arg0.TopBar )
			local f8_local3 = function ( f12_arg0 )
				f8_arg0.TopBarFocus:beginAnimation( 200 )
				f8_arg0.TopBarFocus:setRGB( 1, 1, 1 )
				f8_arg0.TopBarFocus:setAlpha( 0.74 )
				f8_arg0.TopBarFocus:registerEventHandler( "interrupted_keyframe", f8_arg0.clipInterrupted )
				f8_arg0.TopBarFocus:registerEventHandler( "transition_complete_keyframe", f8_arg0.clipFinished )
			end
			
			f8_arg0.TopBarFocus:completeAnimation()
			f8_arg0.TopBarFocus:setRGB( ColorSet.T8__BIEGE.r, ColorSet.T8__BIEGE.g, ColorSet.T8__BIEGE.b )
			f8_arg0.TopBarFocus:setAlpha( 0 )
			f8_local3( f8_arg0.TopBarFocus )
			local f8_local4 = function ( f13_arg0 )
				f8_arg0.lockImage:beginAnimation( 200 )
				f8_arg0.lockImage:setScale( 1.2, 1.2 )
				f8_arg0.lockImage:registerEventHandler( "interrupted_keyframe", f8_arg0.clipInterrupted )
				f8_arg0.lockImage:registerEventHandler( "transition_complete_keyframe", f8_arg0.clipFinished )
			end
			
			f8_arg0.lockImage:completeAnimation()
			f8_arg0.lockImage:setScale( 1, 1 )
			f8_local4( f8_arg0.lockImage )
			local f8_local5 = function ( f14_arg0 )
				f8_arg0.LeaderActivityText:beginAnimation( 200 )
				f8_arg0.LeaderActivityText:setAlpha( 0.5 )
				f8_arg0.LeaderActivityText:registerEventHandler( "interrupted_keyframe", f8_arg0.clipInterrupted )
				f8_arg0.LeaderActivityText:registerEventHandler( "transition_complete_keyframe", f8_arg0.clipFinished )
			end
			
			f8_arg0.LeaderActivityText:completeAnimation()
			f8_arg0.LeaderActivityText:setAlpha( 0.2 )
			f8_local5( f8_arg0.LeaderActivityText )
			f8_arg0.Header:completeAnimation()
			f8_arg0.Header:setAlpha( 1 )
			f8_arg0.clipFinished( f8_arg0.Header )
			local f8_local6 = function ( f15_arg0 )
				f8_arg0.MiddleText:beginAnimation( 200 )
				f8_arg0.MiddleText:setRGB( ColorSet.T8__BIEGE.r, ColorSet.T8__BIEGE.g, ColorSet.T8__BIEGE.b )
				f8_arg0.MiddleText:registerEventHandler( "interrupted_keyframe", f8_arg0.clipInterrupted )
				f8_arg0.MiddleText:registerEventHandler( "transition_complete_keyframe", f8_arg0.clipFinished )
			end
			
			f8_arg0.MiddleText:completeAnimation()
			f8_arg0.MiddleText:setRGB( 1, 1, 1 )
			f8_local6( f8_arg0.MiddleText )
		end,
		LoseFocus = function ( f16_arg0, f16_arg1 )
			f16_arg0:__resetProperties()
			f16_arg0:setupElementClipCounter( 11 )
			local f16_local0 = function ( f17_arg0 )
				f16_arg0.ButtonBG:beginAnimation( 200 )
				f16_arg0.ButtonBG:setRGB( 0.38, 0.38, 0.38 )
				f16_arg0.ButtonBG:setAlpha( 0.8 )
				f16_arg0.ButtonBG:registerEventHandler( "interrupted_keyframe", f16_arg0.clipInterrupted )
				f16_arg0.ButtonBG:registerEventHandler( "transition_complete_keyframe", f16_arg0.clipFinished )
			end
			
			f16_arg0.ButtonBG:completeAnimation()
			f16_arg0.ButtonBG:setRGB( 1, 1, 1 )
			f16_arg0.ButtonBG:setAlpha( 0.4 )
			f16_local0( f16_arg0.ButtonBG )
			f16_arg0.Image:completeAnimation()
			f16_arg0.Image:setAlpha( 0 )
			f16_arg0.clipFinished( f16_arg0.Image )
			f16_arg0.PixelGrid:completeAnimation()
			f16_arg0.PixelGrid:setRGB( 1, 1, 1 )
			f16_arg0.PixelGrid:setAlpha( 0.05 )
			f16_arg0.clipFinished( f16_arg0.PixelGrid )
			local f16_local1 = function ( f18_arg0 )
				f16_arg0.Lines:beginAnimation( 200 )
				f16_arg0.Lines:setRGB( 1, 1, 1 )
				f16_arg0.Lines:setAlpha( 0.15 )
				f16_arg0.Lines:registerEventHandler( "interrupted_keyframe", f16_arg0.clipInterrupted )
				f16_arg0.Lines:registerEventHandler( "transition_complete_keyframe", f16_arg0.clipFinished )
			end
			
			f16_arg0.Lines:completeAnimation()
			f16_arg0.Lines:setRGB( 0.85, 0.85, 0.85 )
			f16_arg0.Lines:setAlpha( 0.7 )
			f16_local1( f16_arg0.Lines )
			f16_arg0.ButtonBGGlow:completeAnimation()
			f16_arg0.ButtonBGGlow:setAlpha( 0 )
			f16_arg0.clipFinished( f16_arg0.ButtonBGGlow )
			local f16_local2 = function ( f19_arg0 )
				f16_arg0.TopBar:beginAnimation( 200 )
				f16_arg0.TopBar:setRGB( 1, 1, 1 )
				f16_arg0.TopBar:setAlpha( 0.1 )
				f16_arg0.TopBar:registerEventHandler( "interrupted_keyframe", f16_arg0.clipInterrupted )
				f16_arg0.TopBar:registerEventHandler( "transition_complete_keyframe", f16_arg0.clipFinished )
			end
			
			f16_arg0.TopBar:completeAnimation()
			f16_arg0.TopBar:setRGB( ColorSet.T8__BIEGE.r, ColorSet.T8__BIEGE.g, ColorSet.T8__BIEGE.b )
			f16_arg0.TopBar:setAlpha( 0.77 )
			f16_local2( f16_arg0.TopBar )
			local f16_local3 = function ( f20_arg0 )
				f16_arg0.TopBarFocus:beginAnimation( 200 )
				f16_arg0.TopBarFocus:setRGB( ColorSet.T8__BIEGE.r, ColorSet.T8__BIEGE.g, ColorSet.T8__BIEGE.b )
				f16_arg0.TopBarFocus:setAlpha( 0 )
				f16_arg0.TopBarFocus:registerEventHandler( "interrupted_keyframe", f16_arg0.clipInterrupted )
				f16_arg0.TopBarFocus:registerEventHandler( "transition_complete_keyframe", f16_arg0.clipFinished )
			end
			
			f16_arg0.TopBarFocus:completeAnimation()
			f16_arg0.TopBarFocus:setRGB( 1, 1, 1 )
			f16_arg0.TopBarFocus:setAlpha( 0.74 )
			f16_local3( f16_arg0.TopBarFocus )
			local f16_local4 = function ( f21_arg0 )
				f16_arg0.lockImage:beginAnimation( 200 )
				f16_arg0.lockImage:setScale( 1, 1 )
				f16_arg0.lockImage:registerEventHandler( "interrupted_keyframe", f16_arg0.clipInterrupted )
				f16_arg0.lockImage:registerEventHandler( "transition_complete_keyframe", f16_arg0.clipFinished )
			end
			
			f16_arg0.lockImage:completeAnimation()
			f16_arg0.lockImage:setScale( 1.2, 1.2 )
			f16_local4( f16_arg0.lockImage )
			local f16_local5 = function ( f22_arg0 )
				f16_arg0.LeaderActivityText:beginAnimation( 200 )
				f16_arg0.LeaderActivityText:setAlpha( 0.2 )
				f16_arg0.LeaderActivityText:registerEventHandler( "interrupted_keyframe", f16_arg0.clipInterrupted )
				f16_arg0.LeaderActivityText:registerEventHandler( "transition_complete_keyframe", f16_arg0.clipFinished )
			end
			
			f16_arg0.LeaderActivityText:completeAnimation()
			f16_arg0.LeaderActivityText:setAlpha( 0.5 )
			f16_local5( f16_arg0.LeaderActivityText )
			f16_arg0.Header:completeAnimation()
			f16_arg0.Header:setAlpha( 1 )
			f16_arg0.clipFinished( f16_arg0.Header )
			local f16_local6 = function ( f23_arg0 )
				f16_arg0.MiddleText:beginAnimation( 200 )
				f16_arg0.MiddleText:setRGB( 1, 1, 1 )
				f16_arg0.MiddleText:registerEventHandler( "interrupted_keyframe", f16_arg0.clipInterrupted )
				f16_arg0.MiddleText:registerEventHandler( "transition_complete_keyframe", f16_arg0.clipFinished )
			end
			
			f16_arg0.MiddleText:completeAnimation()
			f16_arg0.MiddleText:setRGB( ColorSet.T8__BIEGE.r, ColorSet.T8__BIEGE.g, ColorSet.T8__BIEGE.b )
			f16_local6( f16_arg0.MiddleText )
		end
	},
	Locked = {
		DefaultClip = function ( f24_arg0, f24_arg1 )
			f24_arg0:__resetProperties()
			f24_arg0:setupElementClipCounter( 5 )
			f24_arg0.ImageNotFocus:completeAnimation()
			f24_arg0.ImageNotFocus:setRGB( 0.44, 0.44, 0.44 )
			f24_arg0.ImageNotFocus:setMaterial( LUI.UIImage.GetCachedMaterial( "uie_saturation_normal" ) )
			f24_arg0.ImageNotFocus:setShaderVector( 0, 0.5, 0, 0, 0 )
			f24_arg0.clipFinished( f24_arg0.ImageNotFocus )
			f24_arg0.lockImage:completeAnimation()
			f24_arg0.lockImage:setAlpha( 0.2 )
			f24_arg0.clipFinished( f24_arg0.lockImage )
			f24_arg0.LeaderActivityText:completeAnimation()
			f24_arg0.LeaderActivityText:setAlpha( 0.05 )
			f24_arg0.clipFinished( f24_arg0.LeaderActivityText )
			f24_arg0.Header:completeAnimation()
			f24_arg0.Header:setAlpha( 0.05 )
			f24_arg0.clipFinished( f24_arg0.Header )
			f24_arg0.MiddleText:completeAnimation()
			f24_arg0.MiddleText:setAlpha( 0.3 )
			f24_arg0.clipFinished( f24_arg0.MiddleText )
		end,
		Focus = function ( f25_arg0, f25_arg1 )
			f25_arg0:__resetProperties()
			f25_arg0:setupElementClipCounter( 5 )
			f25_arg0.ImageNotFocus:completeAnimation()
			f25_arg0.ImageNotFocus:setRGB( 0.44, 0.44, 0.44 )
			f25_arg0.ImageNotFocus:setMaterial( LUI.UIImage.GetCachedMaterial( "uie_saturation_normal" ) )
			f25_arg0.ImageNotFocus:setShaderVector( 0, 0.5, 0, 0, 0 )
			f25_arg0.clipFinished( f25_arg0.ImageNotFocus )
			f25_arg0.lockImage:completeAnimation()
			f25_arg0.lockImage:setAlpha( 0.2 )
			f25_arg0.clipFinished( f25_arg0.lockImage )
			f25_arg0.LeaderActivityText:completeAnimation()
			f25_arg0.LeaderActivityText:setAlpha( 0.05 )
			f25_arg0.clipFinished( f25_arg0.LeaderActivityText )
			f25_arg0.Header:completeAnimation()
			f25_arg0.Header:setAlpha( 0.1 )
			f25_arg0.clipFinished( f25_arg0.Header )
			f25_arg0.MiddleText:completeAnimation()
			f25_arg0.MiddleText:setAlpha( 0.3 )
			f25_arg0.clipFinished( f25_arg0.MiddleText )
		end,
		GainFocus = function ( f26_arg0, f26_arg1 )
			f26_arg0:__resetProperties()
			f26_arg0:setupElementClipCounter( 5 )
			f26_arg0.ImageNotFocus:completeAnimation()
			f26_arg0.ImageNotFocus:setRGB( 0.44, 0.44, 0.44 )
			f26_arg0.ImageNotFocus:setMaterial( LUI.UIImage.GetCachedMaterial( "uie_saturation_normal" ) )
			f26_arg0.ImageNotFocus:setShaderVector( 0, 0.5, 0, 0, 0 )
			f26_arg0.clipFinished( f26_arg0.ImageNotFocus )
			f26_arg0.lockImage:completeAnimation()
			f26_arg0.lockImage:setAlpha( 0.2 )
			f26_arg0.clipFinished( f26_arg0.lockImage )
			local f26_local0 = function ( f27_arg0 )
				f26_arg0.LeaderActivityText:beginAnimation( 200 )
				f26_arg0.LeaderActivityText:setAlpha( 0.1 )
				f26_arg0.LeaderActivityText:registerEventHandler( "interrupted_keyframe", f26_arg0.clipInterrupted )
				f26_arg0.LeaderActivityText:registerEventHandler( "transition_complete_keyframe", f26_arg0.clipFinished )
			end
			
			f26_arg0.LeaderActivityText:completeAnimation()
			f26_arg0.LeaderActivityText:setAlpha( 0.05 )
			f26_local0( f26_arg0.LeaderActivityText )
			local f26_local1 = function ( f28_arg0 )
				f26_arg0.Header:beginAnimation( 200 )
				f26_arg0.Header:setAlpha( 0.1 )
				f26_arg0.Header:registerEventHandler( "interrupted_keyframe", f26_arg0.clipInterrupted )
				f26_arg0.Header:registerEventHandler( "transition_complete_keyframe", f26_arg0.clipFinished )
			end
			
			f26_arg0.Header:completeAnimation()
			f26_arg0.Header:setAlpha( 0.05 )
			f26_local1( f26_arg0.Header )
			f26_arg0.MiddleText:completeAnimation()
			f26_arg0.MiddleText:setAlpha( 0.3 )
			f26_arg0.clipFinished( f26_arg0.MiddleText )
		end,
		LoseFocus = function ( f29_arg0, f29_arg1 )
			f29_arg0:__resetProperties()
			f29_arg0:setupElementClipCounter( 5 )
			f29_arg0.ImageNotFocus:completeAnimation()
			f29_arg0.ImageNotFocus:setRGB( 0.44, 0.44, 0.44 )
			f29_arg0.ImageNotFocus:setMaterial( LUI.UIImage.GetCachedMaterial( "uie_saturation_normal" ) )
			f29_arg0.ImageNotFocus:setShaderVector( 0, 0.5, 0, 0, 0 )
			f29_arg0.clipFinished( f29_arg0.ImageNotFocus )
			f29_arg0.lockImage:completeAnimation()
			f29_arg0.lockImage:setAlpha( 0.2 )
			f29_arg0.clipFinished( f29_arg0.lockImage )
			local f29_local0 = function ( f30_arg0 )
				f29_arg0.LeaderActivityText:beginAnimation( 200 )
				f29_arg0.LeaderActivityText:setAlpha( 0.05 )
				f29_arg0.LeaderActivityText:registerEventHandler( "interrupted_keyframe", f29_arg0.clipInterrupted )
				f29_arg0.LeaderActivityText:registerEventHandler( "transition_complete_keyframe", f29_arg0.clipFinished )
			end
			
			f29_arg0.LeaderActivityText:completeAnimation()
			f29_arg0.LeaderActivityText:setAlpha( 0.1 )
			f29_local0( f29_arg0.LeaderActivityText )
			local f29_local1 = function ( f31_arg0 )
				f29_arg0.Header:beginAnimation( 200 )
				f29_arg0.Header:setAlpha( 0.05 )
				f29_arg0.Header:registerEventHandler( "interrupted_keyframe", f29_arg0.clipInterrupted )
				f29_arg0.Header:registerEventHandler( "transition_complete_keyframe", f29_arg0.clipFinished )
			end
			
			f29_arg0.Header:completeAnimation()
			f29_arg0.Header:setAlpha( 0.1 )
			f29_local1( f29_arg0.Header )
			f29_arg0.MiddleText:completeAnimation()
			f29_arg0.MiddleText:setAlpha( 0.3 )
			f29_arg0.clipFinished( f29_arg0.MiddleText )
		end
	},
	Disabled = {
		DefaultClip = function ( f32_arg0, f32_arg1 )
			f32_arg0:__resetProperties()
			f32_arg0:setupElementClipCounter( 3 )
			f32_arg0.lockImage:completeAnimation()
			f32_arg0.lockImage:setScale( 1.2, 1.2 )
			f32_arg0.clipFinished( f32_arg0.lockImage )
			f32_arg0.LeaderActivityText:completeAnimation()
			f32_arg0.LeaderActivityText:setAlpha( 0.05 )
			f32_arg0.clipFinished( f32_arg0.LeaderActivityText )
			f32_arg0.Header:completeAnimation()
			f32_arg0.Header:setAlpha( 0.05 )
			f32_arg0.clipFinished( f32_arg0.Header )
		end
	}
}
CoD.DirectorSelectButtonInternal.__onClose = function ( f33_arg0 )
	f33_arg0.ImageNotFocus:close()
	f33_arg0.Lines:close()
	f33_arg0.timer:close()
	f33_arg0.CountdownText:close()
end

