require( "ui/uieditor/widgets/common/CommonPixelBacking" )
require( "ui/uieditor/widgets/commonbuttonoutline" )
require( "ui/uieditor/widgets/director/directorselectbuttonmode" )

CoD.DirectorSelectButtonImageInternal = InheritFrom( LUI.UIElement )
CoD.DirectorSelectButtonImageInternal.__defaultWidth = 301
CoD.DirectorSelectButtonImageInternal.__defaultHeight = 69
CoD.DirectorSelectButtonImageInternal.new = function ( f1_arg0, f1_arg1, f1_arg2, f1_arg3, f1_arg4, f1_arg5, f1_arg6, f1_arg7, f1_arg8, f1_arg9 )
	local self = LUI.UIElement.new( f1_arg2, f1_arg3, f1_arg4, f1_arg5, f1_arg6, f1_arg7, f1_arg8, f1_arg9 )
	self:setClass( CoD.DirectorSelectButtonImageInternal )
	self.id = "DirectorSelectButtonImageInternal"
	self.soundSet = "default"
	self.anyChildUsesUpdateState = true
	f1_arg0:addElementToPendingUpdateStateList( self )
	
	local SceneBlur = LUI.UIImage.new( 0, 1, 0, 0, 0, 1, 0, 0 )
	SceneBlur:setRGB( 0, 0, 0 )
	SceneBlur:setMaterial( LUI.UIImage.GetCachedMaterial( 0xE2354BE557C4C7A ) )
	SceneBlur:setShaderVector( 0, 0, 0.4, 0, 0 )
	self:addElement( SceneBlur )
	self.SceneBlur = SceneBlur
	
	local NoiseTiledBacking = LUI.UIImage.new( 0, 1, 0, 0, 0, 1, 0, 0 )
	NoiseTiledBacking:setAlpha( 0.95 )
	NoiseTiledBacking:setImage( RegisterImage( 0x34839E8065B1E53 ) )
	NoiseTiledBacking:setMaterial( LUI.UIImage.GetCachedMaterial( 0x6CBE95C250C6D15 ) )
	NoiseTiledBacking:setShaderVector( 0, 0, 0, 0, 0 )
	NoiseTiledBacking:setupNineSliceShader( 196, 88 )
	self:addElement( NoiseTiledBacking )
	self.NoiseTiledBacking = NoiseTiledBacking
	
	local Tint = LUI.UIImage.new( 0, 1, 0, 0, 0, 1, 0, 0 )
	Tint:setRGB( 0, 0, 0 )
	Tint:setAlpha( 0.75 )
	self:addElement( Tint )
	self.Tint = Tint
	
	local FrontendFrameSelected = LUI.UIImage.new( 0, 1, -4, 4, 0, 1, -4, 4 )
	FrontendFrameSelected:setRGB( 0.8, 0.7, 0.09 )
	FrontendFrameSelected:setAlpha( 0 )
	FrontendFrameSelected:setImage( RegisterImage( 0xCB07CCC28498CB2 ) )
	FrontendFrameSelected:setMaterial( LUI.UIImage.GetCachedMaterial( 0xFD777557404A7B3 ) )
	FrontendFrameSelected:setShaderVector( 0, 0, 0, 0, 0 )
	FrontendFrameSelected:setupNineSliceShader( 10, 10 )
	self:addElement( FrontendFrameSelected )
	self.FrontendFrameSelected = FrontendFrameSelected
	
	local DotTiledBacking = CoD.CommonPixelBacking.new( f1_arg0, f1_arg1, 0, 1, 4, -4, 0, 1, 4, -4 )
	DotTiledBacking:setRFTMaterial( LUI.UIImage.GetCachedMaterial( 0x4E6CE42E0799F57 ) )
	DotTiledBacking.NoiseBacking:setAlpha( 1 )
	DotTiledBacking.TiledShaderImage:setRGB( 0.22, 0.22, 0.22 )
	DotTiledBacking.TiledShaderImage:setAlpha( 0.15 )
	DotTiledBacking.TiledShaderImage:setupNineSliceShader( 36, 36 )
	self:addElement( DotTiledBacking )
	self.DotTiledBacking = DotTiledBacking
	
	local IconBackground = LUI.UIImage.new( 0, 1, 0, 0, 0, 1, 0, 0 )
	IconBackground:setMaterial( LUI.UIImage.GetCachedMaterial( 0x67D1E3A3D2D1BF ) )
	IconBackground:setShaderVector( 0, 1, 0, 0, 0 )
	IconBackground:linkToElementModel( self, "iconBackground", true, function ( model )
		local f2_local0 = model:get()
		if f2_local0 ~= nil then
			IconBackground:setImage( RegisterImage( f2_local0 ) )
		end
	end )
	self:addElement( IconBackground )
	self.IconBackground = IconBackground
	
	local IconBackgroundFocus = LUI.UIImage.new( 0, 1, 0, 0, 0, 1, 0, 0 )
	IconBackgroundFocus:setAlpha( 0 )
	IconBackgroundFocus:setMaterial( LUI.UIImage.GetCachedMaterial( 0x67D1E3A3D2D1BF ) )
	IconBackgroundFocus:setShaderVector( 0, 1, 0, 0, 0 )
	IconBackgroundFocus:linkToElementModel( self, "iconBackgroundFocus", true, function ( model )
		local f3_local0 = model:get()
		if f3_local0 ~= nil then
			IconBackgroundFocus:setImage( RegisterImage( f3_local0 ) )
		end
	end )
	self:addElement( IconBackgroundFocus )
	self.IconBackgroundFocus = IconBackgroundFocus
	
	local ButtonName = CoD.DirectorSelectButtonMode.new( f1_arg0, f1_arg1, 0, 1, 0, 0, 1, 1, -50, 0 )
	ButtonName:mergeStateConditions( {
		{
			stateName = "Locked",
			condition = function ( menu, element, event )
				return not CoD.BaseUtility.IsSelfInState( self, "DefaultState" )
			end
		}
	} )
	ButtonName.GameModeText:setText( ToUpper( CoD.BaseUtility.LocalizeIfXHash( 0xA43B10D9DA121A ) ) )
	ButtonName.GameModeText:setTTF( "ttmussels_regular" )
	self:addElement( ButtonName )
	self.ButtonName = ButtonName
	
	local FrameBorder = LUI.UIImage.new( 0, 1, -1, 1, 0, 1, -1, 1 )
	FrameBorder:setAlpha( 0.1 )
	FrameBorder:setImage( RegisterImage( 0x185E11D74ECA3D7 ) )
	FrameBorder:setMaterial( LUI.UIImage.GetCachedMaterial( 0xFD777557404A7B3 ) )
	FrameBorder:setShaderVector( 0, 0, 0, 0, 0 )
	FrameBorder:setupNineSliceShader( 12, 12 )
	self:addElement( FrameBorder )
	self.FrameBorder = FrameBorder
	
	local LeaderActivityText = LUI.UIText.new( 0, 0, 16, 285, 1, 1, -64.5, -44.5 )
	LeaderActivityText:setRGB( 0.63, 0.62, 0.61 )
	LeaderActivityText:setAlpha( 0 )
	LeaderActivityText:setText( Engine[0xF9F1239CFD921FE]( 0x93E719493E9E18F ) )
	LeaderActivityText:setTTF( "ttmussels_regular" )
	LeaderActivityText:setLetterSpacing( 4 )
	LeaderActivityText:setAlignment( Enum.LUIAlignment[0xFEEB12BCB0D7041] )
	LeaderActivityText:setAlignment( Enum.LUIAlignment[0xF41D595A2B0EDF3] )
	self:addElement( LeaderActivityText )
	self.LeaderActivityText = LeaderActivityText
	
	local lockImage = LUI.UIImage.new( 0.5, 0.5, -25, 25, 0.5, 0.5, -25, 25 )
	lockImage:setAlpha( 0 )
	lockImage:setScale( 0.6, 0.6 )
	lockImage:setImage( RegisterImage( 0xE1E7C490B2BA4FB ) )
	self:addElement( lockImage )
	self.lockImage = lockImage
	
	local FocusBorder = LUI.UIImage.new( 0, 1, -4, 4, 0, 1, -4, 4 )
	FocusBorder:setRGB( 0.96, 0.94, 0.78 )
	FocusBorder:setAlpha( 0 )
	FocusBorder:setImage( RegisterImage( 0xCB07CCC28498CB2 ) )
	FocusBorder:setMaterial( LUI.UIImage.GetCachedMaterial( 0xFD777557404A7B3 ) )
	FocusBorder:setShaderVector( 0, 0, 0, 0, 0 )
	FocusBorder:setupNineSliceShader( 10, 10 )
	self:addElement( FocusBorder )
	self.FocusBorder = FocusBorder
	
	local CommonButtonOutline = CoD.CommonButtonOutline.new( f1_arg0, f1_arg1, 0, 1, 0, 0, 0, 1, 0, 0 )
	self:addElement( CommonButtonOutline )
	self.CommonButtonOutline = CommonButtonOutline
	
	LUI.OverrideFunction_CallOriginalFirst( self, "setState", function ( element, controller, f5_arg2, f5_arg3, f5_arg4 )
		UpdateElementState( self, "ButtonName", controller )
	end )
	CommonButtonOutline.id = "CommonButtonOutline"
	LUI.OverrideFunction_CallOriginalSecond( self, "close", self.__onClose )
	
	if PostLoadFunc then
		PostLoadFunc( self, f1_arg1, f1_arg0 )
	end
	
	return self
end

CoD.DirectorSelectButtonImageInternal.__resetProperties = function ( f6_arg0 )
	f6_arg0.lockImage:completeAnimation()
	f6_arg0.FrontendFrameSelected:completeAnimation()
	f6_arg0.DotTiledBacking:completeAnimation()
	f6_arg0.IconBackgroundFocus:completeAnimation()
	f6_arg0.NoiseTiledBacking:completeAnimation()
	f6_arg0.ButtonName:completeAnimation()
	f6_arg0.IconBackground:completeAnimation()
	f6_arg0.CommonButtonOutline:completeAnimation()
	f6_arg0.FocusBorder:completeAnimation()
	f6_arg0.lockImage:setLeftRight( 0.5, 0.5, -25, 25 )
	f6_arg0.lockImage:setTopBottom( 0.5, 0.5, -25, 25 )
	f6_arg0.lockImage:setAlpha( 0 )
	f6_arg0.lockImage:setScale( 0.6, 0.6 )
	f6_arg0.FrontendFrameSelected:setAlpha( 0 )
	f6_arg0.DotTiledBacking.TiledShaderImage:setRGB( 0.22, 0.22, 0.22 )
	f6_arg0.DotTiledBacking.TiledShaderImage:setAlpha( 0.15 )
	f6_arg0.IconBackgroundFocus:setAlpha( 0 )
	f6_arg0.IconBackgroundFocus:setShaderVector( 0, 1, 0, 0, 0 )
	f6_arg0.NoiseTiledBacking:setRGB( 1, 1, 1 )
	f6_arg0.ButtonName.GameModeText:setRGB( ColorSet.T8__BIEGE.r, ColorSet.T8__BIEGE.g, ColorSet.T8__BIEGE.b )
	f6_arg0.IconBackground:setShaderVector( 0, 1, 0, 0, 0 )
	f6_arg0.CommonButtonOutline.FocusGlow:setScale( 1, 1 )
	f6_arg0.FocusBorder:setRGB( 0.96, 0.94, 0.78 )
	f6_arg0.FocusBorder:setAlpha( 0 )
end

CoD.DirectorSelectButtonImageInternal.__clipsPerState = {
	DefaultState = {
		DefaultClip = function ( f7_arg0, f7_arg1 )
			f7_arg0:__resetProperties()
			f7_arg0:setupElementClipCounter( 0 )
		end,
		ChildFocus = function ( f8_arg0, f8_arg1 )
			f8_arg0:__resetProperties()
			f8_arg0:setupElementClipCounter( 4 )
			f8_arg0.FrontendFrameSelected:completeAnimation()
			f8_arg0.FrontendFrameSelected:setAlpha( 0.1 )
			f8_arg0.clipFinished( f8_arg0.FrontendFrameSelected )
			f8_arg0.DotTiledBacking:completeAnimation()
			f8_arg0.DotTiledBacking.TiledShaderImage:completeAnimation()
			f8_arg0.DotTiledBacking.TiledShaderImage:setRGB( 0.28, 0.28, 0.28 )
			f8_arg0.DotTiledBacking.TiledShaderImage:setAlpha( 0.7 )
			f8_arg0.clipFinished( f8_arg0.DotTiledBacking )
			f8_arg0.IconBackgroundFocus:completeAnimation()
			f8_arg0.IconBackgroundFocus:setAlpha( 1 )
			f8_arg0.clipFinished( f8_arg0.IconBackgroundFocus )
			f8_arg0.lockImage:completeAnimation()
			f8_arg0.lockImage:setScale( 1.2, 1.2 )
			f8_arg0.clipFinished( f8_arg0.lockImage )
		end,
		GainChildFocus = function ( f9_arg0, f9_arg1 )
			f9_arg0:__resetProperties()
			f9_arg0:setupElementClipCounter( 4 )
			local f9_local0 = function ( f10_arg0 )
				f9_arg0.FrontendFrameSelected:beginAnimation( 200, Enum[0xF50FFF429AB1890][0x5193EA7825DC097] )
				f9_arg0.FrontendFrameSelected:setAlpha( 0.1 )
				f9_arg0.FrontendFrameSelected:registerEventHandler( "interrupted_keyframe", f9_arg0.clipInterrupted )
				f9_arg0.FrontendFrameSelected:registerEventHandler( "transition_complete_keyframe", f9_arg0.clipFinished )
			end
			
			f9_arg0.FrontendFrameSelected:completeAnimation()
			f9_arg0.FrontendFrameSelected:setAlpha( 0 )
			f9_local0( f9_arg0.FrontendFrameSelected )
			local f9_local1 = function ( f11_arg0 )
				f9_arg0.DotTiledBacking:beginAnimation( 200 )
				f9_arg0.DotTiledBacking.TiledShaderImage:beginAnimation( 200 )
				f9_arg0.DotTiledBacking.TiledShaderImage:setRGB( 0.28, 0.28, 0.28 )
				f9_arg0.DotTiledBacking:registerEventHandler( "interrupted_keyframe", f9_arg0.clipInterrupted )
				f9_arg0.DotTiledBacking:registerEventHandler( "transition_complete_keyframe", f9_arg0.clipFinished )
			end
			
			f9_arg0.DotTiledBacking:completeAnimation()
			f9_arg0.DotTiledBacking.TiledShaderImage:completeAnimation()
			f9_arg0.DotTiledBacking.TiledShaderImage:setRGB( 0.22, 0.22, 0.22 )
			f9_local1( f9_arg0.DotTiledBacking )
			local f9_local2 = function ( f12_arg0 )
				f9_arg0.IconBackgroundFocus:beginAnimation( 200 )
				f9_arg0.IconBackgroundFocus:setAlpha( 1 )
				f9_arg0.IconBackgroundFocus:registerEventHandler( "interrupted_keyframe", f9_arg0.clipInterrupted )
				f9_arg0.IconBackgroundFocus:registerEventHandler( "transition_complete_keyframe", f9_arg0.clipFinished )
			end
			
			f9_arg0.IconBackgroundFocus:completeAnimation()
			f9_arg0.IconBackgroundFocus:setAlpha( 0 )
			f9_local2( f9_arg0.IconBackgroundFocus )
			local f9_local3 = function ( f13_arg0 )
				f9_arg0.lockImage:beginAnimation( 200 )
				f9_arg0.lockImage:setScale( 1.2, 1.2 )
				f9_arg0.lockImage:registerEventHandler( "interrupted_keyframe", f9_arg0.clipInterrupted )
				f9_arg0.lockImage:registerEventHandler( "transition_complete_keyframe", f9_arg0.clipFinished )
			end
			
			f9_arg0.lockImage:completeAnimation()
			f9_arg0.lockImage:setScale( 0.6, 0.6 )
			f9_local3( f9_arg0.lockImage )
		end,
		LoseChildFocus = function ( f14_arg0, f14_arg1 )
			f14_arg0:__resetProperties()
			f14_arg0:setupElementClipCounter( 4 )
			local f14_local0 = function ( f15_arg0 )
				f14_arg0.FrontendFrameSelected:beginAnimation( 200, Enum[0xF50FFF429AB1890][0x5193EA7825DC097] )
				f14_arg0.FrontendFrameSelected:setAlpha( 0 )
				f14_arg0.FrontendFrameSelected:registerEventHandler( "interrupted_keyframe", f14_arg0.clipInterrupted )
				f14_arg0.FrontendFrameSelected:registerEventHandler( "transition_complete_keyframe", f14_arg0.clipFinished )
			end
			
			f14_arg0.FrontendFrameSelected:completeAnimation()
			f14_arg0.FrontendFrameSelected:setAlpha( 0.1 )
			f14_local0( f14_arg0.FrontendFrameSelected )
			local f14_local1 = function ( f16_arg0 )
				f14_arg0.DotTiledBacking:beginAnimation( 200 )
				f14_arg0.DotTiledBacking.TiledShaderImage:beginAnimation( 200 )
				f14_arg0.DotTiledBacking.TiledShaderImage:setRGB( 0.22, 0.22, 0.22 )
				f14_arg0.DotTiledBacking:registerEventHandler( "interrupted_keyframe", f14_arg0.clipInterrupted )
				f14_arg0.DotTiledBacking:registerEventHandler( "transition_complete_keyframe", f14_arg0.clipFinished )
			end
			
			f14_arg0.DotTiledBacking:completeAnimation()
			f14_arg0.DotTiledBacking.TiledShaderImage:completeAnimation()
			f14_arg0.DotTiledBacking.TiledShaderImage:setRGB( 0.28, 0.28, 0.28 )
			f14_local1( f14_arg0.DotTiledBacking )
			local f14_local2 = function ( f17_arg0 )
				f14_arg0.IconBackgroundFocus:beginAnimation( 200 )
				f14_arg0.IconBackgroundFocus:setAlpha( 0 )
				f14_arg0.IconBackgroundFocus:registerEventHandler( "interrupted_keyframe", f14_arg0.clipInterrupted )
				f14_arg0.IconBackgroundFocus:registerEventHandler( "transition_complete_keyframe", f14_arg0.clipFinished )
			end
			
			f14_arg0.IconBackgroundFocus:completeAnimation()
			f14_arg0.IconBackgroundFocus:setAlpha( 1 )
			f14_local2( f14_arg0.IconBackgroundFocus )
			local f14_local3 = function ( f18_arg0 )
				f14_arg0.lockImage:beginAnimation( 200 )
				f14_arg0.lockImage:setScale( 0.6, 0.6 )
				f14_arg0.lockImage:registerEventHandler( "interrupted_keyframe", f14_arg0.clipInterrupted )
				f14_arg0.lockImage:registerEventHandler( "transition_complete_keyframe", f14_arg0.clipFinished )
			end
			
			f14_arg0.lockImage:completeAnimation()
			f14_arg0.lockImage:setScale( 1.2, 1.2 )
			f14_local3( f14_arg0.lockImage )
		end
	},
	TrialLocked = {
		DefaultClip = function ( f19_arg0, f19_arg1 )
			f19_arg0:__resetProperties()
			f19_arg0:setupElementClipCounter( 6 )
			f19_arg0.NoiseTiledBacking:completeAnimation()
			f19_arg0.NoiseTiledBacking:setRGB( 0.78, 0.78, 0.78 )
			f19_arg0.clipFinished( f19_arg0.NoiseTiledBacking )
			f19_arg0.IconBackground:completeAnimation()
			f19_arg0.IconBackground:setShaderVector( 0, 0.5, 0, 0, 0 )
			f19_arg0.clipFinished( f19_arg0.IconBackground )
			f19_arg0.IconBackgroundFocus:completeAnimation()
			f19_arg0.IconBackgroundFocus:setShaderVector( 0, 0.5, 0, 0, 0 )
			f19_arg0.clipFinished( f19_arg0.IconBackgroundFocus )
			f19_arg0.ButtonName:completeAnimation()
			f19_arg0.ButtonName.GameModeText:completeAnimation()
			f19_arg0.ButtonName.GameModeText:setRGB( 0.92, 0.92, 0.92 )
			f19_arg0.clipFinished( f19_arg0.ButtonName )
			f19_arg0.lockImage:completeAnimation()
			f19_arg0.lockImage:setLeftRight( 1, 1, -42, 8 )
			f19_arg0.lockImage:setTopBottom( 0, 0, -8, 42 )
			f19_arg0.lockImage:setAlpha( 0.5 )
			f19_arg0.clipFinished( f19_arg0.lockImage )
			f19_arg0.CommonButtonOutline:completeAnimation()
			f19_arg0.CommonButtonOutline.FocusGlow:completeAnimation()
			f19_arg0.CommonButtonOutline.FocusGlow:setScale( 0, 0 )
			f19_arg0.clipFinished( f19_arg0.CommonButtonOutline )
		end,
		ChildFocus = function ( f20_arg0, f20_arg1 )
			f20_arg0:__resetProperties()
			f20_arg0:setupElementClipCounter( 7 )
			f20_arg0.NoiseTiledBacking:completeAnimation()
			f20_arg0.NoiseTiledBacking:setRGB( 0.78, 0.78, 0.78 )
			f20_arg0.clipFinished( f20_arg0.NoiseTiledBacking )
			f20_arg0.IconBackground:completeAnimation()
			f20_arg0.IconBackground:setShaderVector( 0, 0.5, 0, 0, 0 )
			f20_arg0.clipFinished( f20_arg0.IconBackground )
			f20_arg0.IconBackgroundFocus:completeAnimation()
			f20_arg0.IconBackgroundFocus:setShaderVector( 0, 0.5, 0, 0, 0 )
			f20_arg0.clipFinished( f20_arg0.IconBackgroundFocus )
			f20_arg0.ButtonName:completeAnimation()
			f20_arg0.ButtonName.GameModeText:completeAnimation()
			f20_arg0.ButtonName.GameModeText:setRGB( 0.92, 0.92, 0.92 )
			f20_arg0.clipFinished( f20_arg0.ButtonName )
			f20_arg0.lockImage:completeAnimation()
			f20_arg0.lockImage:setLeftRight( 1, 1, -42, 8 )
			f20_arg0.lockImage:setTopBottom( 0, 0, -8, 42 )
			f20_arg0.lockImage:setAlpha( 0.5 )
			f20_arg0.clipFinished( f20_arg0.lockImage )
			f20_arg0.FocusBorder:completeAnimation()
			f20_arg0.FocusBorder:setRGB( ColorSet.T8__OFF__WHITE.r, ColorSet.T8__OFF__WHITE.g, ColorSet.T8__OFF__WHITE.b )
			f20_arg0.FocusBorder:setAlpha( 0.25 )
			f20_arg0.clipFinished( f20_arg0.FocusBorder )
			f20_arg0.CommonButtonOutline:completeAnimation()
			f20_arg0.CommonButtonOutline.FocusGlow:completeAnimation()
			f20_arg0.CommonButtonOutline.FocusGlow:setScale( 0, 0 )
			f20_arg0.clipFinished( f20_arg0.CommonButtonOutline )
		end,
		GainChildFocus = function ( f21_arg0, f21_arg1 )
			f21_arg0:__resetProperties()
			f21_arg0:setupElementClipCounter( 7 )
			f21_arg0.NoiseTiledBacking:completeAnimation()
			f21_arg0.NoiseTiledBacking:setRGB( 0.78, 0.78, 0.78 )
			f21_arg0.clipFinished( f21_arg0.NoiseTiledBacking )
			f21_arg0.IconBackground:completeAnimation()
			f21_arg0.IconBackground:setShaderVector( 0, 0.5, 0, 0, 0 )
			f21_arg0.clipFinished( f21_arg0.IconBackground )
			f21_arg0.IconBackgroundFocus:completeAnimation()
			f21_arg0.IconBackgroundFocus:setShaderVector( 0, 0.5, 0, 0, 0 )
			f21_arg0.clipFinished( f21_arg0.IconBackgroundFocus )
			f21_arg0.ButtonName:completeAnimation()
			f21_arg0.ButtonName.GameModeText:completeAnimation()
			f21_arg0.ButtonName.GameModeText:setRGB( 0.92, 0.92, 0.92 )
			f21_arg0.clipFinished( f21_arg0.ButtonName )
			f21_arg0.lockImage:completeAnimation()
			f21_arg0.lockImage:setLeftRight( 1, 1, -42, 8 )
			f21_arg0.lockImage:setTopBottom( 0, 0, -8, 42 )
			f21_arg0.lockImage:setAlpha( 0.5 )
			f21_arg0.clipFinished( f21_arg0.lockImage )
			local f21_local0 = function ( f22_arg0 )
				f21_arg0.FocusBorder:beginAnimation( 200 )
				f21_arg0.FocusBorder:setAlpha( 0.25 )
				f21_arg0.FocusBorder:registerEventHandler( "interrupted_keyframe", f21_arg0.clipInterrupted )
				f21_arg0.FocusBorder:registerEventHandler( "transition_complete_keyframe", f21_arg0.clipFinished )
			end
			
			f21_arg0.FocusBorder:completeAnimation()
			f21_arg0.FocusBorder:setRGB( ColorSet.T8__OFF__WHITE.r, ColorSet.T8__OFF__WHITE.g, ColorSet.T8__OFF__WHITE.b )
			f21_arg0.FocusBorder:setAlpha( 0 )
			f21_local0( f21_arg0.FocusBorder )
			f21_arg0.CommonButtonOutline:completeAnimation()
			f21_arg0.CommonButtonOutline.FocusGlow:completeAnimation()
			f21_arg0.CommonButtonOutline.FocusGlow:setScale( 0, 0 )
			f21_arg0.clipFinished( f21_arg0.CommonButtonOutline )
		end,
		LoseChildFocus = function ( f23_arg0, f23_arg1 )
			f23_arg0:__resetProperties()
			f23_arg0:setupElementClipCounter( 7 )
			f23_arg0.NoiseTiledBacking:completeAnimation()
			f23_arg0.NoiseTiledBacking:setRGB( 0.78, 0.78, 0.78 )
			f23_arg0.clipFinished( f23_arg0.NoiseTiledBacking )
			f23_arg0.IconBackground:completeAnimation()
			f23_arg0.IconBackground:setShaderVector( 0, 0.5, 0, 0, 0 )
			f23_arg0.clipFinished( f23_arg0.IconBackground )
			f23_arg0.IconBackgroundFocus:completeAnimation()
			f23_arg0.IconBackgroundFocus:setShaderVector( 0, 0.5, 0, 0, 0 )
			f23_arg0.clipFinished( f23_arg0.IconBackgroundFocus )
			f23_arg0.ButtonName:completeAnimation()
			f23_arg0.ButtonName.GameModeText:completeAnimation()
			f23_arg0.ButtonName.GameModeText:setRGB( 0.92, 0.92, 0.92 )
			f23_arg0.clipFinished( f23_arg0.ButtonName )
			f23_arg0.lockImage:completeAnimation()
			f23_arg0.lockImage:setLeftRight( 1, 1, -42, 8 )
			f23_arg0.lockImage:setTopBottom( 0, 0, -8, 42 )
			f23_arg0.lockImage:setAlpha( 0.5 )
			f23_arg0.clipFinished( f23_arg0.lockImage )
			local f23_local0 = function ( f24_arg0 )
				f23_arg0.FocusBorder:beginAnimation( 200 )
				f23_arg0.FocusBorder:setAlpha( 0 )
				f23_arg0.FocusBorder:registerEventHandler( "interrupted_keyframe", f23_arg0.clipInterrupted )
				f23_arg0.FocusBorder:registerEventHandler( "transition_complete_keyframe", f23_arg0.clipFinished )
			end
			
			f23_arg0.FocusBorder:completeAnimation()
			f23_arg0.FocusBorder:setRGB( ColorSet.T8__OFF__WHITE.r, ColorSet.T8__OFF__WHITE.g, ColorSet.T8__OFF__WHITE.b )
			f23_arg0.FocusBorder:setAlpha( 0.25 )
			f23_local0( f23_arg0.FocusBorder )
			f23_arg0.CommonButtonOutline:completeAnimation()
			f23_arg0.CommonButtonOutline.FocusGlow:completeAnimation()
			f23_arg0.CommonButtonOutline.FocusGlow:setScale( 0, 0 )
			f23_arg0.clipFinished( f23_arg0.CommonButtonOutline )
		end
	},
	Locked = {
		DefaultClip = function ( f25_arg0, f25_arg1 )
			f25_arg0:__resetProperties()
			f25_arg0:setupElementClipCounter( 6 )
			f25_arg0.NoiseTiledBacking:completeAnimation()
			f25_arg0.NoiseTiledBacking:setRGB( 0.78, 0.78, 0.78 )
			f25_arg0.clipFinished( f25_arg0.NoiseTiledBacking )
			f25_arg0.IconBackground:completeAnimation()
			f25_arg0.IconBackground:setShaderVector( 0, 0.5, 0, 0, 0 )
			f25_arg0.clipFinished( f25_arg0.IconBackground )
			f25_arg0.IconBackgroundFocus:completeAnimation()
			f25_arg0.IconBackgroundFocus:setShaderVector( 0, 0.5, 0, 0, 0 )
			f25_arg0.clipFinished( f25_arg0.IconBackgroundFocus )
			f25_arg0.ButtonName:completeAnimation()
			f25_arg0.ButtonName.GameModeText:completeAnimation()
			f25_arg0.ButtonName.GameModeText:setRGB( 0.92, 0.92, 0.92 )
			f25_arg0.clipFinished( f25_arg0.ButtonName )
			f25_arg0.lockImage:completeAnimation()
			f25_arg0.lockImage:setAlpha( 0.5 )
			f25_arg0.clipFinished( f25_arg0.lockImage )
			f25_arg0.CommonButtonOutline:completeAnimation()
			f25_arg0.CommonButtonOutline.FocusGlow:completeAnimation()
			f25_arg0.CommonButtonOutline.FocusGlow:setScale( 0, 0 )
			f25_arg0.clipFinished( f25_arg0.CommonButtonOutline )
		end,
		ChildFocus = function ( f26_arg0, f26_arg1 )
			f26_arg0:__resetProperties()
			f26_arg0:setupElementClipCounter( 7 )
			f26_arg0.NoiseTiledBacking:completeAnimation()
			f26_arg0.NoiseTiledBacking:setRGB( 0.78, 0.78, 0.78 )
			f26_arg0.clipFinished( f26_arg0.NoiseTiledBacking )
			f26_arg0.IconBackground:completeAnimation()
			f26_arg0.IconBackground:setShaderVector( 0, 0.5, 0, 0, 0 )
			f26_arg0.clipFinished( f26_arg0.IconBackground )
			f26_arg0.IconBackgroundFocus:completeAnimation()
			f26_arg0.IconBackgroundFocus:setShaderVector( 0, 0.5, 0, 0, 0 )
			f26_arg0.clipFinished( f26_arg0.IconBackgroundFocus )
			f26_arg0.ButtonName:completeAnimation()
			f26_arg0.ButtonName.GameModeText:completeAnimation()
			f26_arg0.ButtonName.GameModeText:setRGB( 0.92, 0.92, 0.92 )
			f26_arg0.clipFinished( f26_arg0.ButtonName )
			f26_arg0.lockImage:completeAnimation()
			f26_arg0.lockImage:setAlpha( 0.5 )
			f26_arg0.clipFinished( f26_arg0.lockImage )
			f26_arg0.FocusBorder:completeAnimation()
			f26_arg0.FocusBorder:setRGB( ColorSet.T8__OFF__WHITE.r, ColorSet.T8__OFF__WHITE.g, ColorSet.T8__OFF__WHITE.b )
			f26_arg0.FocusBorder:setAlpha( 0.25 )
			f26_arg0.clipFinished( f26_arg0.FocusBorder )
			f26_arg0.CommonButtonOutline:completeAnimation()
			f26_arg0.CommonButtonOutline.FocusGlow:completeAnimation()
			f26_arg0.CommonButtonOutline.FocusGlow:setScale( 0, 0 )
			f26_arg0.clipFinished( f26_arg0.CommonButtonOutline )
		end,
		GainChildFocus = function ( f27_arg0, f27_arg1 )
			f27_arg0:__resetProperties()
			f27_arg0:setupElementClipCounter( 7 )
			f27_arg0.NoiseTiledBacking:completeAnimation()
			f27_arg0.NoiseTiledBacking:setRGB( 0.78, 0.78, 0.78 )
			f27_arg0.clipFinished( f27_arg0.NoiseTiledBacking )
			f27_arg0.IconBackground:completeAnimation()
			f27_arg0.IconBackground:setShaderVector( 0, 0.5, 0, 0, 0 )
			f27_arg0.clipFinished( f27_arg0.IconBackground )
			f27_arg0.IconBackgroundFocus:completeAnimation()
			f27_arg0.IconBackgroundFocus:setShaderVector( 0, 0.5, 0, 0, 0 )
			f27_arg0.clipFinished( f27_arg0.IconBackgroundFocus )
			f27_arg0.ButtonName:completeAnimation()
			f27_arg0.ButtonName.GameModeText:completeAnimation()
			f27_arg0.ButtonName.GameModeText:setRGB( 0.92, 0.92, 0.92 )
			f27_arg0.clipFinished( f27_arg0.ButtonName )
			f27_arg0.lockImage:completeAnimation()
			f27_arg0.lockImage:setAlpha( 0.5 )
			f27_arg0.clipFinished( f27_arg0.lockImage )
			local f27_local0 = function ( f28_arg0 )
				f27_arg0.FocusBorder:beginAnimation( 200 )
				f27_arg0.FocusBorder:setAlpha( 0.25 )
				f27_arg0.FocusBorder:registerEventHandler( "interrupted_keyframe", f27_arg0.clipInterrupted )
				f27_arg0.FocusBorder:registerEventHandler( "transition_complete_keyframe", f27_arg0.clipFinished )
			end
			
			f27_arg0.FocusBorder:completeAnimation()
			f27_arg0.FocusBorder:setRGB( ColorSet.T8__OFF__WHITE.r, ColorSet.T8__OFF__WHITE.g, ColorSet.T8__OFF__WHITE.b )
			f27_arg0.FocusBorder:setAlpha( 0 )
			f27_local0( f27_arg0.FocusBorder )
			f27_arg0.CommonButtonOutline:completeAnimation()
			f27_arg0.CommonButtonOutline.FocusGlow:completeAnimation()
			f27_arg0.CommonButtonOutline.FocusGlow:setScale( 0, 0 )
			f27_arg0.clipFinished( f27_arg0.CommonButtonOutline )
		end,
		LoseChildFocus = function ( f29_arg0, f29_arg1 )
			f29_arg0:__resetProperties()
			f29_arg0:setupElementClipCounter( 7 )
			f29_arg0.NoiseTiledBacking:completeAnimation()
			f29_arg0.NoiseTiledBacking:setRGB( 0.78, 0.78, 0.78 )
			f29_arg0.clipFinished( f29_arg0.NoiseTiledBacking )
			f29_arg0.IconBackground:completeAnimation()
			f29_arg0.IconBackground:setShaderVector( 0, 0.5, 0, 0, 0 )
			f29_arg0.clipFinished( f29_arg0.IconBackground )
			f29_arg0.IconBackgroundFocus:completeAnimation()
			f29_arg0.IconBackgroundFocus:setShaderVector( 0, 0.5, 0, 0, 0 )
			f29_arg0.clipFinished( f29_arg0.IconBackgroundFocus )
			f29_arg0.ButtonName:completeAnimation()
			f29_arg0.ButtonName.GameModeText:completeAnimation()
			f29_arg0.ButtonName.GameModeText:setRGB( 0.92, 0.92, 0.92 )
			f29_arg0.clipFinished( f29_arg0.ButtonName )
			f29_arg0.lockImage:completeAnimation()
			f29_arg0.lockImage:setAlpha( 0.5 )
			f29_arg0.clipFinished( f29_arg0.lockImage )
			local f29_local0 = function ( f30_arg0 )
				f29_arg0.FocusBorder:beginAnimation( 200 )
				f29_arg0.FocusBorder:setAlpha( 0 )
				f29_arg0.FocusBorder:registerEventHandler( "interrupted_keyframe", f29_arg0.clipInterrupted )
				f29_arg0.FocusBorder:registerEventHandler( "transition_complete_keyframe", f29_arg0.clipFinished )
			end
			
			f29_arg0.FocusBorder:completeAnimation()
			f29_arg0.FocusBorder:setRGB( ColorSet.T8__OFF__WHITE.r, ColorSet.T8__OFF__WHITE.g, ColorSet.T8__OFF__WHITE.b )
			f29_arg0.FocusBorder:setAlpha( 0.25 )
			f29_local0( f29_arg0.FocusBorder )
			f29_arg0.CommonButtonOutline:completeAnimation()
			f29_arg0.CommonButtonOutline.FocusGlow:completeAnimation()
			f29_arg0.CommonButtonOutline.FocusGlow:setScale( 0, 0 )
			f29_arg0.clipFinished( f29_arg0.CommonButtonOutline )
		end
	},
	Disabled = {
		DefaultClip = function ( f31_arg0, f31_arg1 )
			f31_arg0:__resetProperties()
			f31_arg0:setupElementClipCounter( 3 )
			f31_arg0.ButtonName:completeAnimation()
			f31_arg0.ButtonName.GameModeText:completeAnimation()
			f31_arg0.ButtonName.GameModeText:setRGB( 0.92, 0.92, 0.92 )
			f31_arg0.clipFinished( f31_arg0.ButtonName )
			f31_arg0.lockImage:completeAnimation()
			f31_arg0.lockImage:setScale( 1.2, 1.2 )
			f31_arg0.clipFinished( f31_arg0.lockImage )
			f31_arg0.FocusBorder:completeAnimation()
			f31_arg0.FocusBorder:setRGB( ColorSet.T8__OFF__WHITE.r, ColorSet.T8__OFF__WHITE.g, ColorSet.T8__OFF__WHITE.b )
			f31_arg0.clipFinished( f31_arg0.FocusBorder )
		end,
		Focus = function ( f32_arg0, f32_arg1 )
			f32_arg0:__resetProperties()
			f32_arg0:setupElementClipCounter( 3 )
			f32_arg0.ButtonName:completeAnimation()
			f32_arg0.ButtonName.GameModeText:completeAnimation()
			f32_arg0.ButtonName.GameModeText:setRGB( 0.92, 0.92, 0.92 )
			f32_arg0.clipFinished( f32_arg0.ButtonName )
			f32_arg0.lockImage:completeAnimation()
			f32_arg0.lockImage:setScale( 1.2, 1.2 )
			f32_arg0.clipFinished( f32_arg0.lockImage )
			f32_arg0.FocusBorder:completeAnimation()
			f32_arg0.FocusBorder:setRGB( ColorSet.T8__OFF__WHITE.r, ColorSet.T8__OFF__WHITE.g, ColorSet.T8__OFF__WHITE.b )
			f32_arg0.FocusBorder:setAlpha( 0.25 )
			f32_arg0.clipFinished( f32_arg0.FocusBorder )
		end,
		GainFocus = function ( f33_arg0, f33_arg1 )
			f33_arg0:__resetProperties()
			f33_arg0:setupElementClipCounter( 3 )
			f33_arg0.ButtonName:completeAnimation()
			f33_arg0.ButtonName.GameModeText:completeAnimation()
			f33_arg0.ButtonName.GameModeText:setRGB( 0.92, 0.92, 0.92 )
			f33_arg0.clipFinished( f33_arg0.ButtonName )
			f33_arg0.lockImage:completeAnimation()
			f33_arg0.lockImage:setScale( 1.2, 1.2 )
			f33_arg0.clipFinished( f33_arg0.lockImage )
			local f33_local0 = function ( f34_arg0 )
				f33_arg0.FocusBorder:beginAnimation( 200 )
				f33_arg0.FocusBorder:setAlpha( 0.25 )
				f33_arg0.FocusBorder:registerEventHandler( "interrupted_keyframe", f33_arg0.clipInterrupted )
				f33_arg0.FocusBorder:registerEventHandler( "transition_complete_keyframe", f33_arg0.clipFinished )
			end
			
			f33_arg0.FocusBorder:completeAnimation()
			f33_arg0.FocusBorder:setRGB( ColorSet.T8__OFF__WHITE.r, ColorSet.T8__OFF__WHITE.g, ColorSet.T8__OFF__WHITE.b )
			f33_arg0.FocusBorder:setAlpha( 0 )
			f33_local0( f33_arg0.FocusBorder )
		end,
		LoseFocus = function ( f35_arg0, f35_arg1 )
			f35_arg0:__resetProperties()
			f35_arg0:setupElementClipCounter( 3 )
			f35_arg0.ButtonName:completeAnimation()
			f35_arg0.ButtonName.GameModeText:completeAnimation()
			f35_arg0.ButtonName.GameModeText:setRGB( 0.92, 0.92, 0.92 )
			f35_arg0.clipFinished( f35_arg0.ButtonName )
			f35_arg0.lockImage:completeAnimation()
			f35_arg0.lockImage:setScale( 1.2, 1.2 )
			f35_arg0.clipFinished( f35_arg0.lockImage )
			local f35_local0 = function ( f36_arg0 )
				f35_arg0.FocusBorder:beginAnimation( 200 )
				f35_arg0.FocusBorder:setAlpha( 0 )
				f35_arg0.FocusBorder:registerEventHandler( "interrupted_keyframe", f35_arg0.clipInterrupted )
				f35_arg0.FocusBorder:registerEventHandler( "transition_complete_keyframe", f35_arg0.clipFinished )
			end
			
			f35_arg0.FocusBorder:completeAnimation()
			f35_arg0.FocusBorder:setRGB( ColorSet.T8__OFF__WHITE.r, ColorSet.T8__OFF__WHITE.g, ColorSet.T8__OFF__WHITE.b )
			f35_arg0.FocusBorder:setAlpha( 0.25 )
			f35_local0( f35_arg0.FocusBorder )
		end
	}
}
CoD.DirectorSelectButtonImageInternal.__onClose = function ( f37_arg0 )
	f37_arg0.DotTiledBacking:close()
	f37_arg0.IconBackground:close()
	f37_arg0.IconBackgroundFocus:close()
	f37_arg0.ButtonName:close()
	f37_arg0.CommonButtonOutline:close()
end

