require( "ui/uieditor/widgets/common/commonfocusbrackets" )
require( "ui/uieditor/widgets/common/CommonPixelBacking" )
require( "ui/uieditor/widgets/director/directorselectbuttonlines" )

CoD.CommonButtonGenericInternal = InheritFrom( LUI.UIElement )
CoD.CommonButtonGenericInternal.__defaultWidth = 300
CoD.CommonButtonGenericInternal.__defaultHeight = 70
CoD.CommonButtonGenericInternal.new = function ( f1_arg0, f1_arg1, f1_arg2, f1_arg3, f1_arg4, f1_arg5, f1_arg6, f1_arg7, f1_arg8, f1_arg9 )
	local self = LUI.UIElement.new( f1_arg2, f1_arg3, f1_arg4, f1_arg5, f1_arg6, f1_arg7, f1_arg8, f1_arg9 )
	self:setClass( CoD.CommonButtonGenericInternal )
	self.id = "CommonButtonGenericInternal"
	self.soundSet = "FrontendMain"
	f1_arg0:addElementToPendingUpdateStateList( self )
	
	local SceneBlur = LUI.UIImage.new( 0, 1, 0, 0, 0, 1, 0, 0 )
	SceneBlur:setRGB( 0, 0, 0 )
	SceneBlur:setMaterial( LUI.UIImage.GetCachedMaterial( 0xE2354BE557C4C7A ) )
	SceneBlur:setShaderVector( 0, 0, 0.4, 0, 0 )
	self:addElement( SceneBlur )
	self.SceneBlur = SceneBlur
	
	local NoiseTiledBacking = LUI.UIImage.new( 0, 1, 0, 0, 0, 1, 0, 0 )
	NoiseTiledBacking:setAlpha( 0.95 )
	NoiseTiledBacking:setImage( RegisterImage( "uie_ui_menu_specialist_hub_repeat_bg" ) )
	NoiseTiledBacking:setMaterial( LUI.UIImage.GetCachedMaterial( 0x6CBE95C250C6D15 ) )
	NoiseTiledBacking:setShaderVector( 0, 0, 0, 0, 0 )
	NoiseTiledBacking:setupNineSliceShader( 196, 88 )
	self:addElement( NoiseTiledBacking )
	self.NoiseTiledBacking = NoiseTiledBacking
	
	local Tint = LUI.UIImage.new( 0, 1, 0, 0, 0, 1, 0, 0 )
	Tint:setRGB( 0, 0, 0 )
	Tint:setAlpha( 0.75 )
	self:addElement( Tint )
	self.Tint = Tint
	
	local FocusBrackets = CoD.CommonFocusBrackets.new( f1_arg0, f1_arg1, 0, 1, -20, 20, 0, 1, -20, 20 )
	FocusBrackets:setAlpha( 0 )
	self:addElement( FocusBrackets )
	self.FocusBrackets = FocusBrackets
	
	local FrontendFrameSelected = LUI.UIImage.new( 0, 1, -4, 4, 0, 1, -4, 4 )
	FrontendFrameSelected:setRGB( 0.8, 0.7, 0.09 )
	FrontendFrameSelected:setAlpha( 0 )
	FrontendFrameSelected:setImage( RegisterImage( "uie_ui_menu_store_focus_frame" ) )
	FrontendFrameSelected:setMaterial( LUI.UIImage.GetCachedMaterial( "uie_nineslice_add" ) )
	FrontendFrameSelected:setShaderVector( 0, 0, 0, 0, 0 )
	FrontendFrameSelected:setupNineSliceShader( 10, 10 )
	self:addElement( FrontendFrameSelected )
	self.FrontendFrameSelected = FrontendFrameSelected
	
	local FocusGlow = LUI.UIImage.new( 0, 1, -130, 130, 0, 1, -158, 158 )
	FocusGlow:setAlpha( 0 )
	FocusGlow:setImage( RegisterImage( 0x223AD1B40A93955 ) )
	FocusGlow:setMaterial( LUI.UIImage.GetCachedMaterial( 0xDAB59B2CAE01851 ) )
	FocusGlow:setShaderVector( 0, 0, 0, 0.21, 0.09 )
	FocusGlow:setShaderVector( 1, 1.36, 0, 0, 0 )
	FocusGlow:setupNineSliceShader( 245, 185 )
	self:addElement( FocusGlow )
	self.FocusGlow = FocusGlow
	
	local FocusHighlight = LUI.UIImage.new( 0, 1, -52, 52, 0, 1, -42, 42 )
	FocusHighlight:setAlpha( 0 )
	FocusHighlight:setImage( RegisterImage( 0x3F09D20CA138B49 ) )
	FocusHighlight:setMaterial( LUI.UIImage.GetCachedMaterial( 0xDAB59B2CAE01851 ) )
	FocusHighlight:setShaderVector( 0, 0, 0, 0.27, 0.18 )
	FocusHighlight:setShaderVector( 1, 0.9, 0, 0, 0 )
	FocusHighlight:setupNineSliceShader( 135, 70 )
	self:addElement( FocusHighlight )
	self.FocusHighlight = FocusHighlight
	
	local DotTiledBacking = CoD.CommonPixelBacking.new( f1_arg0, f1_arg1, 0, 1, 4, -4, 0, 1, 4, -4 )
	DotTiledBacking:setRFTMaterial( LUI.UIImage.GetCachedMaterial( "ui_add" ) )
	DotTiledBacking.NoiseBacking:setAlpha( 1 )
	DotTiledBacking.TiledShaderImage:setRGB( 0.22, 0.22, 0.22 )
	DotTiledBacking.TiledShaderImage:setAlpha( 0.15 )
	DotTiledBacking.TiledShaderImage:setupNineSliceShader( 36, 36 )
	self:addElement( DotTiledBacking )
	self.DotTiledBacking = DotTiledBacking
	
	local FrameBorder = LUI.UIImage.new( 0, 1, -1, 1, 0, 1, -1, 1 )
	FrameBorder:setAlpha( 0.1 )
	FrameBorder:setImage( RegisterImage( "uie_ui_menu_store_common_frame" ) )
	FrameBorder:setMaterial( LUI.UIImage.GetCachedMaterial( "uie_nineslice_add" ) )
	FrameBorder:setShaderVector( 0, 0, 0, 0, 0 )
	FrameBorder:setupNineSliceShader( 12, 12 )
	self:addElement( FrameBorder )
	self.FrameBorder = FrameBorder
	
	local MiddleText = LUI.UIText.new( 0, 1, 16, -16, 0.5, 0.5, -12, 12 )
	MiddleText:setRGB( ColorSet.T8__BIEGE.r, ColorSet.T8__BIEGE.g, ColorSet.T8__BIEGE.b )
	MiddleText:setText( LocalizeToUpperString( 0xA43B10D9DA121A ) )
	MiddleText:setTTF( "ttmussels_regular" )
	MiddleText:setMaterial( LUI.UIImage.GetCachedMaterial( 0x71E049B161CD00A ) )
	MiddleText:setLetterSpacing( 3 )
	MiddleText:setAlignment( Enum.LUIAlignment[0xFEEB12BCB0D7041] )
	MiddleText:setAlignment( Enum.LUIAlignment[0x6ED4298C93DC5ED] )
	self:addElement( MiddleText )
	self.MiddleText = MiddleText
	
	local MiddleTextFocus = LUI.UIText.new( 0, 1, 16, -16, 0.5, 0.5, -12, 12 )
	MiddleTextFocus:setRGB( 0.28, 0.25, 0.24 )
	MiddleTextFocus:setAlpha( 0 )
	MiddleTextFocus:setText( LocalizeToUpperString( 0xA43B10D9DA121A ) )
	MiddleTextFocus:setTTF( "ttmussels_regular" )
	MiddleTextFocus:setMaterial( LUI.UIImage.GetCachedMaterial( 0xAE166D9BA8C6907 ) )
	MiddleTextFocus:setShaderVector( 0, 0.13, 0, 0, 0 )
	MiddleTextFocus:setShaderVector( 1, 0.34, 0, 0, 0 )
	MiddleTextFocus:setShaderVector( 2, 1, 0, 0, 0 )
	MiddleTextFocus:setLetterSpacing( 3 )
	MiddleTextFocus:setAlignment( Enum.LUIAlignment[0xFEEB12BCB0D7041] )
	MiddleTextFocus:setAlignment( Enum.LUIAlignment[0x6ED4298C93DC5ED] )
	self:addElement( MiddleTextFocus )
	self.MiddleTextFocus = MiddleTextFocus
	
	local lockImage = LUI.UIImage.new( 1, 1, -42, 8, 0.5, 0.5, -25, 25 )
	lockImage:setAlpha( 0 )
	lockImage:setScale( 0.6, 0.6 )
	lockImage:setImage( RegisterImage( "uie_ui_icon_global_lock" ) )
	self:addElement( lockImage )
	self.lockImage = lockImage
	
	local Lines = CoD.DirectorSelectButtonLines.new( f1_arg0, f1_arg1, 0, 1, 0, 0, 0, 1, 1, -1 )
	Lines:setRGB( 0.64, 0.71, 0.78 )
	self:addElement( Lines )
	self.Lines = Lines
	
	local FocusBorder = LUI.UIImage.new( 0, 1, -4, 4, 0, 1, -4, 4 )
	FocusBorder:setRGB( 0.96, 0.94, 0.78 )
	FocusBorder:setAlpha( 0 )
	FocusBorder:setImage( RegisterImage( "uie_ui_menu_store_focus_frame" ) )
	FocusBorder:setMaterial( LUI.UIImage.GetCachedMaterial( "uie_nineslice_add" ) )
	FocusBorder:setShaderVector( 0, 0, 0, 0, 0 )
	FocusBorder:setupNineSliceShader( 10, 10 )
	self:addElement( FocusBorder )
	self.FocusBorder = FocusBorder
	
	self:subscribeToGlobalModel( f1_arg1, "GlobalModel", "lobbyRoot.lobbyNav", function ( model )
		if ParentHasChildFocus( self ) then
			SetLoseFocusToSelf( self, f1_arg1 )
		end
	end )
	LUI.OverrideFunction_CallOriginalSecond( self, "close", self.__onClose )
	
	if PostLoadFunc then
		PostLoadFunc( self, f1_arg1, f1_arg0 )
	end
	
	return self
end

CoD.CommonButtonGenericInternal.__resetProperties = function ( f3_arg0 )
	f3_arg0.lockImage:completeAnimation()
	f3_arg0.FrontendFrameSelected:completeAnimation()
	f3_arg0.FocusBrackets:completeAnimation()
	f3_arg0.DotTiledBacking:completeAnimation()
	f3_arg0.MiddleTextFocus:completeAnimation()
	f3_arg0.MiddleText:completeAnimation()
	f3_arg0.Lines:completeAnimation()
	f3_arg0.FocusHighlight:completeAnimation()
	f3_arg0.FocusGlow:completeAnimation()
	f3_arg0.NoiseTiledBacking:completeAnimation()
	f3_arg0.FocusBorder:completeAnimation()
	f3_arg0.lockImage:setAlpha( 0 )
	f3_arg0.lockImage:setScale( 0.6, 0.6 )
	f3_arg0.FrontendFrameSelected:setAlpha( 0 )
	f3_arg0.FocusBrackets:setLeftRight( 0, 1, -20, 20 )
	f3_arg0.FocusBrackets:setTopBottom( 0, 1, -20, 20 )
	f3_arg0.FocusBrackets:setAlpha( 0 )
	f3_arg0.DotTiledBacking.TiledShaderImage:setRGB( 0.22, 0.22, 0.22 )
	f3_arg0.DotTiledBacking.TiledShaderImage:setAlpha( 0.15 )
	f3_arg0.MiddleTextFocus:setRGB( 0.28, 0.25, 0.24 )
	f3_arg0.MiddleTextFocus:setAlpha( 0 )
	f3_arg0.MiddleText:setRGB( ColorSet.T8__BIEGE.r, ColorSet.T8__BIEGE.g, ColorSet.T8__BIEGE.b )
	f3_arg0.MiddleText:setAlpha( 1 )
	f3_arg0.Lines:setAlpha( 1 )
	f3_arg0.FocusHighlight:setAlpha( 0 )
	f3_arg0.FocusGlow:setRGB( 1, 1, 1 )
	f3_arg0.FocusGlow:setAlpha( 0 )
	f3_arg0.NoiseTiledBacking:setRGB( 1, 1, 1 )
	f3_arg0.FocusBorder:setRGB( 0.96, 0.94, 0.78 )
	f3_arg0.FocusBorder:setAlpha( 0 )
end

CoD.CommonButtonGenericInternal.__clipsPerState = {
	DefaultState = {
		DefaultClip = function ( f4_arg0, f4_arg1 )
			f4_arg0:__resetProperties()
			f4_arg0:setupElementClipCounter( 0 )
		end,
		Focus = function ( f5_arg0, f5_arg1 )
			f5_arg0:__resetProperties()
			f5_arg0:setupElementClipCounter( 9 )
			f5_arg0.FocusBrackets:completeAnimation()
			f5_arg0.FocusBrackets:setLeftRight( 0, 1, -10, 10 )
			f5_arg0.FocusBrackets:setTopBottom( 0, 1, -10, 10 )
			f5_arg0.FocusBrackets:setAlpha( 1 )
			f5_arg0.clipFinished( f5_arg0.FocusBrackets )
			f5_arg0.FrontendFrameSelected:completeAnimation()
			f5_arg0.FrontendFrameSelected:setAlpha( 0.1 )
			f5_arg0.clipFinished( f5_arg0.FrontendFrameSelected )
			local f5_local0 = function ( f6_arg0 )
				local f6_local0 = function ( f7_arg0 )
					f7_arg0:beginAnimation( 2010 )
					f7_arg0:setRGB( 1, 1, 1 )
					f7_arg0:registerEventHandler( "transition_complete_keyframe", f5_arg0.clipFinished )
				end
				
				f5_arg0.FocusGlow:beginAnimation( 1990 )
				f5_arg0.FocusGlow:setRGB( 0.79, 0.79, 0.79 )
				f5_arg0.FocusGlow:registerEventHandler( "interrupted_keyframe", f5_arg0.clipInterrupted )
				f5_arg0.FocusGlow:registerEventHandler( "transition_complete_keyframe", f6_local0 )
			end
			
			f5_arg0.FocusGlow:completeAnimation()
			f5_arg0.FocusGlow:setRGB( 1, 1, 1 )
			f5_arg0.FocusGlow:setAlpha( 1 )
			f5_local0( f5_arg0.FocusGlow )
			f5_arg0.FocusHighlight:completeAnimation()
			f5_arg0.FocusHighlight:setAlpha( 0.5 )
			f5_arg0.clipFinished( f5_arg0.FocusHighlight )
			f5_arg0.DotTiledBacking:completeAnimation()
			f5_arg0.DotTiledBacking.TiledShaderImage:completeAnimation()
			f5_arg0.DotTiledBacking.TiledShaderImage:setRGB( 0.28, 0.28, 0.28 )
			f5_arg0.DotTiledBacking.TiledShaderImage:setAlpha( 0.7 )
			f5_arg0.clipFinished( f5_arg0.DotTiledBacking )
			f5_arg0.MiddleText:completeAnimation()
			f5_arg0.MiddleText:setAlpha( 0 )
			f5_arg0.clipFinished( f5_arg0.MiddleText )
			f5_arg0.MiddleTextFocus:completeAnimation()
			f5_arg0.MiddleTextFocus:setRGB( 0.28, 0.25, 0.24 )
			f5_arg0.MiddleTextFocus:setAlpha( 1 )
			f5_arg0.clipFinished( f5_arg0.MiddleTextFocus )
			f5_arg0.lockImage:completeAnimation()
			f5_arg0.lockImage:setScale( 1.2, 1.2 )
			f5_arg0.clipFinished( f5_arg0.lockImage )
			f5_arg0.Lines:completeAnimation()
			f5_arg0.Lines:setAlpha( 0 )
			f5_arg0.clipFinished( f5_arg0.Lines )
			f5_arg0.nextClip = "Focus"
		end,
		GainFocus = function ( f8_arg0, f8_arg1 )
			f8_arg0:__resetProperties()
			f8_arg0:setupElementClipCounter( 9 )
			local f8_local0 = function ( f9_arg0 )
				local f9_local0 = function ( f10_arg0 )
					f10_arg0:beginAnimation( 50, Enum[0xF50FFF429AB1890][0x6F6186B702830BC] )
					f10_arg0:setLeftRight( 0, 1, -10, 10 )
					f10_arg0:setTopBottom( 0, 1, -10, 10 )
					f10_arg0:setAlpha( 1 )
					f10_arg0:registerEventHandler( "transition_complete_keyframe", f8_arg0.clipFinished )
				end
				
				f8_arg0.FocusBrackets:beginAnimation( 100 )
				f8_arg0.FocusBrackets:setLeftRight( 0, 1, -8, 8 )
				f8_arg0.FocusBrackets:setTopBottom( 0, 1, -8, 8 )
				f8_arg0.FocusBrackets:setAlpha( 0.75 )
				f8_arg0.FocusBrackets:registerEventHandler( "interrupted_keyframe", f8_arg0.clipInterrupted )
				f8_arg0.FocusBrackets:registerEventHandler( "transition_complete_keyframe", f9_local0 )
			end
			
			f8_arg0.FocusBrackets:completeAnimation()
			f8_arg0.FocusBrackets:setLeftRight( 0, 1, -40, 40 )
			f8_arg0.FocusBrackets:setTopBottom( 0, 1, -40, 40 )
			f8_arg0.FocusBrackets:setAlpha( 0 )
			f8_local0( f8_arg0.FocusBrackets )
			local f8_local1 = function ( f11_arg0 )
				f8_arg0.FrontendFrameSelected:beginAnimation( 200, Enum[0xF50FFF429AB1890][0x5193EA7825DC097] )
				f8_arg0.FrontendFrameSelected:setAlpha( 0.1 )
				f8_arg0.FrontendFrameSelected:registerEventHandler( "interrupted_keyframe", f8_arg0.clipInterrupted )
				f8_arg0.FrontendFrameSelected:registerEventHandler( "transition_complete_keyframe", f8_arg0.clipFinished )
			end
			
			f8_arg0.FrontendFrameSelected:completeAnimation()
			f8_arg0.FrontendFrameSelected:setAlpha( 0 )
			f8_local1( f8_arg0.FrontendFrameSelected )
			local f8_local2 = function ( f12_arg0 )
				f8_arg0.FocusGlow:beginAnimation( 200, Enum[0xF50FFF429AB1890][0x6F6186B702830BC] )
				f8_arg0.FocusGlow:setAlpha( 1 )
				f8_arg0.FocusGlow:registerEventHandler( "interrupted_keyframe", f8_arg0.clipInterrupted )
				f8_arg0.FocusGlow:registerEventHandler( "transition_complete_keyframe", f8_arg0.clipFinished )
			end
			
			f8_arg0.FocusGlow:completeAnimation()
			f8_arg0.FocusGlow:setAlpha( 0 )
			f8_local2( f8_arg0.FocusGlow )
			local f8_local3 = function ( f13_arg0 )
				f8_arg0.FocusHighlight:beginAnimation( 200 )
				f8_arg0.FocusHighlight:setAlpha( 0.8 )
				f8_arg0.FocusHighlight:registerEventHandler( "interrupted_keyframe", f8_arg0.clipInterrupted )
				f8_arg0.FocusHighlight:registerEventHandler( "transition_complete_keyframe", f8_arg0.clipFinished )
			end
			
			f8_arg0.FocusHighlight:completeAnimation()
			f8_arg0.FocusHighlight:setAlpha( 0 )
			f8_local3( f8_arg0.FocusHighlight )
			local f8_local4 = function ( f14_arg0 )
				f8_arg0.DotTiledBacking:beginAnimation( 200 )
				f8_arg0.DotTiledBacking.TiledShaderImage:beginAnimation( 200 )
				f8_arg0.DotTiledBacking.TiledShaderImage:setRGB( 0.28, 0.28, 0.28 )
				f8_arg0.DotTiledBacking:registerEventHandler( "interrupted_keyframe", f8_arg0.clipInterrupted )
				f8_arg0.DotTiledBacking:registerEventHandler( "transition_complete_keyframe", f8_arg0.clipFinished )
			end
			
			f8_arg0.DotTiledBacking:completeAnimation()
			f8_arg0.DotTiledBacking.TiledShaderImage:completeAnimation()
			f8_arg0.DotTiledBacking.TiledShaderImage:setRGB( 0.22, 0.22, 0.22 )
			f8_local4( f8_arg0.DotTiledBacking )
			local f8_local5 = function ( f15_arg0 )
				f8_arg0.MiddleText:beginAnimation( 200 )
				f8_arg0.MiddleText:setAlpha( 0 )
				f8_arg0.MiddleText:registerEventHandler( "interrupted_keyframe", f8_arg0.clipInterrupted )
				f8_arg0.MiddleText:registerEventHandler( "transition_complete_keyframe", f8_arg0.clipFinished )
			end
			
			f8_arg0.MiddleText:completeAnimation()
			f8_arg0.MiddleText:setRGB( ColorSet.T8__BIEGE.r, ColorSet.T8__BIEGE.g, ColorSet.T8__BIEGE.b )
			f8_arg0.MiddleText:setAlpha( 1 )
			f8_local5( f8_arg0.MiddleText )
			local f8_local6 = function ( f16_arg0 )
				f8_arg0.MiddleTextFocus:beginAnimation( 200 )
				f8_arg0.MiddleTextFocus:setAlpha( 1 )
				f8_arg0.MiddleTextFocus:registerEventHandler( "interrupted_keyframe", f8_arg0.clipInterrupted )
				f8_arg0.MiddleTextFocus:registerEventHandler( "transition_complete_keyframe", f8_arg0.clipFinished )
			end
			
			f8_arg0.MiddleTextFocus:completeAnimation()
			f8_arg0.MiddleTextFocus:setAlpha( 0 )
			f8_local6( f8_arg0.MiddleTextFocus )
			local f8_local7 = function ( f17_arg0 )
				f8_arg0.lockImage:beginAnimation( 200 )
				f8_arg0.lockImage:setScale( 1.2, 1.2 )
				f8_arg0.lockImage:registerEventHandler( "interrupted_keyframe", f8_arg0.clipInterrupted )
				f8_arg0.lockImage:registerEventHandler( "transition_complete_keyframe", f8_arg0.clipFinished )
			end
			
			f8_arg0.lockImage:completeAnimation()
			f8_arg0.lockImage:setScale( 0.6, 0.6 )
			f8_local7( f8_arg0.lockImage )
			local f8_local8 = function ( f18_arg0 )
				f8_arg0.Lines:beginAnimation( 200 )
				f8_arg0.Lines:setAlpha( 0 )
				f8_arg0.Lines:registerEventHandler( "interrupted_keyframe", f8_arg0.clipInterrupted )
				f8_arg0.Lines:registerEventHandler( "transition_complete_keyframe", f8_arg0.clipFinished )
			end
			
			f8_arg0.Lines:completeAnimation()
			f8_arg0.Lines:setAlpha( 1 )
			f8_local8( f8_arg0.Lines )
		end,
		LoseFocus = function ( f19_arg0, f19_arg1 )
			f19_arg0:__resetProperties()
			f19_arg0:setupElementClipCounter( 9 )
			local f19_local0 = function ( f20_arg0 )
				f19_arg0.FocusBrackets:beginAnimation( 60, Enum[0xF50FFF429AB1890][0x53CEB9A0427197] )
				f19_arg0.FocusBrackets:setAlpha( 0 )
				f19_arg0.FocusBrackets:registerEventHandler( "interrupted_keyframe", f19_arg0.clipInterrupted )
				f19_arg0.FocusBrackets:registerEventHandler( "transition_complete_keyframe", f19_arg0.clipFinished )
			end
			
			f19_arg0.FocusBrackets:completeAnimation()
			f19_arg0.FocusBrackets:setLeftRight( 0, 1, -10, 10 )
			f19_arg0.FocusBrackets:setTopBottom( 0, 1, -10, 10 )
			f19_arg0.FocusBrackets:setAlpha( 1 )
			f19_local0( f19_arg0.FocusBrackets )
			local f19_local1 = function ( f21_arg0 )
				f19_arg0.FrontendFrameSelected:beginAnimation( 200, Enum[0xF50FFF429AB1890][0x5193EA7825DC097] )
				f19_arg0.FrontendFrameSelected:setAlpha( 0 )
				f19_arg0.FrontendFrameSelected:registerEventHandler( "interrupted_keyframe", f19_arg0.clipInterrupted )
				f19_arg0.FrontendFrameSelected:registerEventHandler( "transition_complete_keyframe", f19_arg0.clipFinished )
			end
			
			f19_arg0.FrontendFrameSelected:completeAnimation()
			f19_arg0.FrontendFrameSelected:setAlpha( 0.1 )
			f19_local1( f19_arg0.FrontendFrameSelected )
			local f19_local2 = function ( f22_arg0 )
				f19_arg0.FocusGlow:beginAnimation( 200 )
				f19_arg0.FocusGlow:setAlpha( 0 )
				f19_arg0.FocusGlow:registerEventHandler( "interrupted_keyframe", f19_arg0.clipInterrupted )
				f19_arg0.FocusGlow:registerEventHandler( "transition_complete_keyframe", f19_arg0.clipFinished )
			end
			
			f19_arg0.FocusGlow:completeAnimation()
			f19_arg0.FocusGlow:setAlpha( 1 )
			f19_local2( f19_arg0.FocusGlow )
			local f19_local3 = function ( f23_arg0 )
				f19_arg0.FocusHighlight:beginAnimation( 200 )
				f19_arg0.FocusHighlight:setAlpha( 0 )
				f19_arg0.FocusHighlight:registerEventHandler( "interrupted_keyframe", f19_arg0.clipInterrupted )
				f19_arg0.FocusHighlight:registerEventHandler( "transition_complete_keyframe", f19_arg0.clipFinished )
			end
			
			f19_arg0.FocusHighlight:completeAnimation()
			f19_arg0.FocusHighlight:setAlpha( 0.8 )
			f19_local3( f19_arg0.FocusHighlight )
			local f19_local4 = function ( f24_arg0 )
				f19_arg0.DotTiledBacking:beginAnimation( 200 )
				f19_arg0.DotTiledBacking.TiledShaderImage:beginAnimation( 200 )
				f19_arg0.DotTiledBacking.TiledShaderImage:setRGB( 0.22, 0.22, 0.22 )
				f19_arg0.DotTiledBacking:registerEventHandler( "interrupted_keyframe", f19_arg0.clipInterrupted )
				f19_arg0.DotTiledBacking:registerEventHandler( "transition_complete_keyframe", f19_arg0.clipFinished )
			end
			
			f19_arg0.DotTiledBacking:completeAnimation()
			f19_arg0.DotTiledBacking.TiledShaderImage:completeAnimation()
			f19_arg0.DotTiledBacking.TiledShaderImage:setRGB( 0.28, 0.28, 0.28 )
			f19_local4( f19_arg0.DotTiledBacking )
			local f19_local5 = function ( f25_arg0 )
				f19_arg0.MiddleText:beginAnimation( 200 )
				f19_arg0.MiddleText:setAlpha( 1 )
				f19_arg0.MiddleText:registerEventHandler( "interrupted_keyframe", f19_arg0.clipInterrupted )
				f19_arg0.MiddleText:registerEventHandler( "transition_complete_keyframe", f19_arg0.clipFinished )
			end
			
			f19_arg0.MiddleText:completeAnimation()
			f19_arg0.MiddleText:setRGB( ColorSet.T8__BIEGE.r, ColorSet.T8__BIEGE.g, ColorSet.T8__BIEGE.b )
			f19_arg0.MiddleText:setAlpha( 0 )
			f19_local5( f19_arg0.MiddleText )
			local f19_local6 = function ( f26_arg0 )
				f19_arg0.MiddleTextFocus:beginAnimation( 200 )
				f19_arg0.MiddleTextFocus:setAlpha( 0 )
				f19_arg0.MiddleTextFocus:registerEventHandler( "interrupted_keyframe", f19_arg0.clipInterrupted )
				f19_arg0.MiddleTextFocus:registerEventHandler( "transition_complete_keyframe", f19_arg0.clipFinished )
			end
			
			f19_arg0.MiddleTextFocus:completeAnimation()
			f19_arg0.MiddleTextFocus:setAlpha( 1 )
			f19_local6( f19_arg0.MiddleTextFocus )
			local f19_local7 = function ( f27_arg0 )
				f19_arg0.lockImage:beginAnimation( 200 )
				f19_arg0.lockImage:setScale( 0.6, 0.6 )
				f19_arg0.lockImage:registerEventHandler( "interrupted_keyframe", f19_arg0.clipInterrupted )
				f19_arg0.lockImage:registerEventHandler( "transition_complete_keyframe", f19_arg0.clipFinished )
			end
			
			f19_arg0.lockImage:completeAnimation()
			f19_arg0.lockImage:setScale( 1.2, 1.2 )
			f19_local7( f19_arg0.lockImage )
			local f19_local8 = function ( f28_arg0 )
				f19_arg0.Lines:beginAnimation( 200 )
				f19_arg0.Lines:setAlpha( 1 )
				f19_arg0.Lines:registerEventHandler( "interrupted_keyframe", f19_arg0.clipInterrupted )
				f19_arg0.Lines:registerEventHandler( "transition_complete_keyframe", f19_arg0.clipFinished )
			end
			
			f19_arg0.Lines:completeAnimation()
			f19_arg0.Lines:setAlpha( 0 )
			f19_local8( f19_arg0.Lines )
		end
	},
	Locked = {
		DefaultClip = function ( f29_arg0, f29_arg1 )
			f29_arg0:__resetProperties()
			f29_arg0:setupElementClipCounter( 4 )
			f29_arg0.NoiseTiledBacking:completeAnimation()
			f29_arg0.NoiseTiledBacking:setRGB( 0.78, 0.78, 0.78 )
			f29_arg0.clipFinished( f29_arg0.NoiseTiledBacking )
			f29_arg0.FocusBrackets:completeAnimation()
			f29_arg0.FocusBrackets:setAlpha( 0 )
			f29_arg0.clipFinished( f29_arg0.FocusBrackets )
			f29_arg0.MiddleText:completeAnimation()
			f29_arg0.MiddleText:setRGB( 0.92, 0.92, 0.92 )
			f29_arg0.MiddleText:setAlpha( 0.2 )
			f29_arg0.clipFinished( f29_arg0.MiddleText )
			f29_arg0.lockImage:completeAnimation()
			f29_arg0.lockImage:setAlpha( 0.5 )
			f29_arg0.clipFinished( f29_arg0.lockImage )
		end,
		Focus = function ( f30_arg0, f30_arg1 )
			f30_arg0:__resetProperties()
			f30_arg0:setupElementClipCounter( 5 )
			f30_arg0.NoiseTiledBacking:completeAnimation()
			f30_arg0.NoiseTiledBacking:setRGB( 0.78, 0.78, 0.78 )
			f30_arg0.clipFinished( f30_arg0.NoiseTiledBacking )
			f30_arg0.FocusBrackets:completeAnimation()
			f30_arg0.FocusBrackets:setLeftRight( 0, 1, -10, 10 )
			f30_arg0.FocusBrackets:setTopBottom( 0, 1, -10, 10 )
			f30_arg0.FocusBrackets:setAlpha( 1 )
			f30_arg0.clipFinished( f30_arg0.FocusBrackets )
			f30_arg0.MiddleText:completeAnimation()
			f30_arg0.MiddleText:setRGB( 0.92, 0.92, 0.92 )
			f30_arg0.MiddleText:setAlpha( 0.2 )
			f30_arg0.clipFinished( f30_arg0.MiddleText )
			f30_arg0.lockImage:completeAnimation()
			f30_arg0.lockImage:setAlpha( 0.5 )
			f30_arg0.clipFinished( f30_arg0.lockImage )
			f30_arg0.FocusBorder:completeAnimation()
			f30_arg0.FocusBorder:setRGB( ColorSet.T8__OFF__WHITE.r, ColorSet.T8__OFF__WHITE.g, ColorSet.T8__OFF__WHITE.b )
			f30_arg0.FocusBorder:setAlpha( 0.25 )
			f30_arg0.clipFinished( f30_arg0.FocusBorder )
		end,
		GainFocus = function ( f31_arg0, f31_arg1 )
			f31_arg0:__resetProperties()
			f31_arg0:setupElementClipCounter( 5 )
			f31_arg0.NoiseTiledBacking:completeAnimation()
			f31_arg0.NoiseTiledBacking:setRGB( 0.78, 0.78, 0.78 )
			f31_arg0.clipFinished( f31_arg0.NoiseTiledBacking )
			local f31_local0 = function ( f32_arg0 )
				local f32_local0 = function ( f33_arg0 )
					f33_arg0:beginAnimation( 50, Enum[0xF50FFF429AB1890][0x6F6186B702830BC] )
					f33_arg0:setLeftRight( 0, 1, -10, 10 )
					f33_arg0:setTopBottom( 0, 1, -10, 10 )
					f33_arg0:setAlpha( 1 )
					f33_arg0:registerEventHandler( "transition_complete_keyframe", f31_arg0.clipFinished )
				end
				
				f31_arg0.FocusBrackets:beginAnimation( 100 )
				f31_arg0.FocusBrackets:setLeftRight( 0, 1, -8, 8 )
				f31_arg0.FocusBrackets:setTopBottom( 0, 1, -8, 8 )
				f31_arg0.FocusBrackets:setAlpha( 0.75 )
				f31_arg0.FocusBrackets:registerEventHandler( "interrupted_keyframe", f31_arg0.clipInterrupted )
				f31_arg0.FocusBrackets:registerEventHandler( "transition_complete_keyframe", f32_local0 )
			end
			
			f31_arg0.FocusBrackets:completeAnimation()
			f31_arg0.FocusBrackets:setLeftRight( 0, 1, -40, 40 )
			f31_arg0.FocusBrackets:setTopBottom( 0, 1, -40, 40 )
			f31_arg0.FocusBrackets:setAlpha( 0 )
			f31_local0( f31_arg0.FocusBrackets )
			f31_arg0.MiddleText:completeAnimation()
			f31_arg0.MiddleText:setRGB( 0.92, 0.92, 0.92 )
			f31_arg0.MiddleText:setAlpha( 0.2 )
			f31_arg0.clipFinished( f31_arg0.MiddleText )
			f31_arg0.lockImage:completeAnimation()
			f31_arg0.lockImage:setAlpha( 0.5 )
			f31_arg0.clipFinished( f31_arg0.lockImage )
			local f31_local1 = function ( f34_arg0 )
				f31_arg0.FocusBorder:beginAnimation( 200 )
				f31_arg0.FocusBorder:setAlpha( 0.25 )
				f31_arg0.FocusBorder:registerEventHandler( "interrupted_keyframe", f31_arg0.clipInterrupted )
				f31_arg0.FocusBorder:registerEventHandler( "transition_complete_keyframe", f31_arg0.clipFinished )
			end
			
			f31_arg0.FocusBorder:completeAnimation()
			f31_arg0.FocusBorder:setRGB( ColorSet.T8__OFF__WHITE.r, ColorSet.T8__OFF__WHITE.g, ColorSet.T8__OFF__WHITE.b )
			f31_arg0.FocusBorder:setAlpha( 0 )
			f31_local1( f31_arg0.FocusBorder )
		end,
		LoseFocus = function ( f35_arg0, f35_arg1 )
			f35_arg0:__resetProperties()
			f35_arg0:setupElementClipCounter( 5 )
			f35_arg0.NoiseTiledBacking:completeAnimation()
			f35_arg0.NoiseTiledBacking:setRGB( 0.78, 0.78, 0.78 )
			f35_arg0.clipFinished( f35_arg0.NoiseTiledBacking )
			local f35_local0 = function ( f36_arg0 )
				f35_arg0.FocusBrackets:beginAnimation( 60, Enum[0xF50FFF429AB1890][0x53CEB9A0427197] )
				f35_arg0.FocusBrackets:setAlpha( 0 )
				f35_arg0.FocusBrackets:registerEventHandler( "interrupted_keyframe", f35_arg0.clipInterrupted )
				f35_arg0.FocusBrackets:registerEventHandler( "transition_complete_keyframe", f35_arg0.clipFinished )
			end
			
			f35_arg0.FocusBrackets:completeAnimation()
			f35_arg0.FocusBrackets:setLeftRight( 0, 1, -10, 10 )
			f35_arg0.FocusBrackets:setTopBottom( 0, 1, -10, 10 )
			f35_arg0.FocusBrackets:setAlpha( 1 )
			f35_local0( f35_arg0.FocusBrackets )
			f35_arg0.MiddleText:completeAnimation()
			f35_arg0.MiddleText:setRGB( 0.92, 0.92, 0.92 )
			f35_arg0.MiddleText:setAlpha( 0.2 )
			f35_arg0.clipFinished( f35_arg0.MiddleText )
			f35_arg0.lockImage:completeAnimation()
			f35_arg0.lockImage:setAlpha( 0.5 )
			f35_arg0.clipFinished( f35_arg0.lockImage )
			local f35_local1 = function ( f37_arg0 )
				f35_arg0.FocusBorder:beginAnimation( 200 )
				f35_arg0.FocusBorder:setAlpha( 0 )
				f35_arg0.FocusBorder:registerEventHandler( "interrupted_keyframe", f35_arg0.clipInterrupted )
				f35_arg0.FocusBorder:registerEventHandler( "transition_complete_keyframe", f35_arg0.clipFinished )
			end
			
			f35_arg0.FocusBorder:completeAnimation()
			f35_arg0.FocusBorder:setRGB( ColorSet.T8__OFF__WHITE.r, ColorSet.T8__OFF__WHITE.g, ColorSet.T8__OFF__WHITE.b )
			f35_arg0.FocusBorder:setAlpha( 0.25 )
			f35_local1( f35_arg0.FocusBorder )
		end
	},
	Disabled = {
		DefaultClip = function ( f38_arg0, f38_arg1 )
			f38_arg0:__resetProperties()
			f38_arg0:setupElementClipCounter( 5 )
			f38_arg0.FocusBrackets:completeAnimation()
			f38_arg0.FocusBrackets:setAlpha( 0 )
			f38_arg0.clipFinished( f38_arg0.FocusBrackets )
			f38_arg0.MiddleText:completeAnimation()
			f38_arg0.MiddleText:setRGB( 0.31, 0.29, 0.29 )
			f38_arg0.MiddleText:setAlpha( 1 )
			f38_arg0.clipFinished( f38_arg0.MiddleText )
			f38_arg0.lockImage:completeAnimation()
			f38_arg0.lockImage:setScale( 1.2, 1.2 )
			f38_arg0.clipFinished( f38_arg0.lockImage )
			f38_arg0.Lines:completeAnimation()
			f38_arg0.Lines:setAlpha( 0.5 )
			f38_arg0.clipFinished( f38_arg0.Lines )
			f38_arg0.FocusBorder:completeAnimation()
			f38_arg0.FocusBorder:setRGB( ColorSet.T8__OFF__WHITE.r, ColorSet.T8__OFF__WHITE.g, ColorSet.T8__OFF__WHITE.b )
			f38_arg0.clipFinished( f38_arg0.FocusBorder )
		end,
		Focus = function ( f39_arg0, f39_arg1 )
			f39_arg0:__resetProperties()
			f39_arg0:setupElementClipCounter( 5 )
			f39_arg0.FocusBrackets:completeAnimation()
			f39_arg0.FocusBrackets:setLeftRight( 0, 1, -10, 10 )
			f39_arg0.FocusBrackets:setTopBottom( 0, 1, -10, 10 )
			f39_arg0.FocusBrackets:setAlpha( 1 )
			f39_arg0.clipFinished( f39_arg0.FocusBrackets )
			f39_arg0.MiddleText:completeAnimation()
			f39_arg0.MiddleText:setRGB( 0.31, 0.29, 0.29 )
			f39_arg0.MiddleText:setAlpha( 1 )
			f39_arg0.clipFinished( f39_arg0.MiddleText )
			f39_arg0.lockImage:completeAnimation()
			f39_arg0.lockImage:setScale( 1.2, 1.2 )
			f39_arg0.clipFinished( f39_arg0.lockImage )
			f39_arg0.Lines:completeAnimation()
			f39_arg0.Lines:setAlpha( 0.5 )
			f39_arg0.clipFinished( f39_arg0.Lines )
			f39_arg0.FocusBorder:completeAnimation()
			f39_arg0.FocusBorder:setRGB( ColorSet.T8__OFF__WHITE.r, ColorSet.T8__OFF__WHITE.g, ColorSet.T8__OFF__WHITE.b )
			f39_arg0.FocusBorder:setAlpha( 0.25 )
			f39_arg0.clipFinished( f39_arg0.FocusBorder )
		end,
		GainFocus = function ( f40_arg0, f40_arg1 )
			f40_arg0:__resetProperties()
			f40_arg0:setupElementClipCounter( 5 )
			local f40_local0 = function ( f41_arg0 )
				local f41_local0 = function ( f42_arg0 )
					f42_arg0:beginAnimation( 50, Enum[0xF50FFF429AB1890][0x6F6186B702830BC] )
					f42_arg0:setLeftRight( 0, 1, -10, 10 )
					f42_arg0:setTopBottom( 0, 1, -10, 10 )
					f42_arg0:setAlpha( 1 )
					f42_arg0:registerEventHandler( "transition_complete_keyframe", f40_arg0.clipFinished )
				end
				
				f40_arg0.FocusBrackets:beginAnimation( 100 )
				f40_arg0.FocusBrackets:setLeftRight( 0, 1, -8, 8 )
				f40_arg0.FocusBrackets:setTopBottom( 0, 1, -8, 8 )
				f40_arg0.FocusBrackets:setAlpha( 0.75 )
				f40_arg0.FocusBrackets:registerEventHandler( "interrupted_keyframe", f40_arg0.clipInterrupted )
				f40_arg0.FocusBrackets:registerEventHandler( "transition_complete_keyframe", f41_local0 )
			end
			
			f40_arg0.FocusBrackets:completeAnimation()
			f40_arg0.FocusBrackets:setLeftRight( 0, 1, -40, 40 )
			f40_arg0.FocusBrackets:setTopBottom( 0, 1, -40, 40 )
			f40_arg0.FocusBrackets:setAlpha( 0 )
			f40_local0( f40_arg0.FocusBrackets )
			f40_arg0.MiddleText:completeAnimation()
			f40_arg0.MiddleText:setRGB( 0.31, 0.29, 0.29 )
			f40_arg0.MiddleText:setAlpha( 1 )
			f40_arg0.clipFinished( f40_arg0.MiddleText )
			f40_arg0.lockImage:completeAnimation()
			f40_arg0.lockImage:setScale( 1.2, 1.2 )
			f40_arg0.clipFinished( f40_arg0.lockImage )
			f40_arg0.Lines:completeAnimation()
			f40_arg0.Lines:setAlpha( 0.5 )
			f40_arg0.clipFinished( f40_arg0.Lines )
			local f40_local1 = function ( f43_arg0 )
				f40_arg0.FocusBorder:beginAnimation( 200 )
				f40_arg0.FocusBorder:setAlpha( 0.25 )
				f40_arg0.FocusBorder:registerEventHandler( "interrupted_keyframe", f40_arg0.clipInterrupted )
				f40_arg0.FocusBorder:registerEventHandler( "transition_complete_keyframe", f40_arg0.clipFinished )
			end
			
			f40_arg0.FocusBorder:completeAnimation()
			f40_arg0.FocusBorder:setRGB( ColorSet.T8__OFF__WHITE.r, ColorSet.T8__OFF__WHITE.g, ColorSet.T8__OFF__WHITE.b )
			f40_arg0.FocusBorder:setAlpha( 0 )
			f40_local1( f40_arg0.FocusBorder )
		end,
		LoseFocus = function ( f44_arg0, f44_arg1 )
			f44_arg0:__resetProperties()
			f44_arg0:setupElementClipCounter( 5 )
			local f44_local0 = function ( f45_arg0 )
				f44_arg0.FocusBrackets:beginAnimation( 60 )
				f44_arg0.FocusBrackets:setAlpha( 0 )
				f44_arg0.FocusBrackets:registerEventHandler( "interrupted_keyframe", f44_arg0.clipInterrupted )
				f44_arg0.FocusBrackets:registerEventHandler( "transition_complete_keyframe", f44_arg0.clipFinished )
			end
			
			f44_arg0.FocusBrackets:completeAnimation()
			f44_arg0.FocusBrackets:setLeftRight( 0, 1, -10, 10 )
			f44_arg0.FocusBrackets:setTopBottom( 0, 1, -10, 10 )
			f44_arg0.FocusBrackets:setAlpha( 1 )
			f44_local0( f44_arg0.FocusBrackets )
			f44_arg0.MiddleText:completeAnimation()
			f44_arg0.MiddleText:setRGB( 0.31, 0.29, 0.29 )
			f44_arg0.MiddleText:setAlpha( 1 )
			f44_arg0.clipFinished( f44_arg0.MiddleText )
			f44_arg0.lockImage:completeAnimation()
			f44_arg0.lockImage:setScale( 1.2, 1.2 )
			f44_arg0.clipFinished( f44_arg0.lockImage )
			f44_arg0.Lines:completeAnimation()
			f44_arg0.Lines:setAlpha( 0.5 )
			f44_arg0.clipFinished( f44_arg0.Lines )
			local f44_local1 = function ( f46_arg0 )
				f44_arg0.FocusBorder:beginAnimation( 200 )
				f44_arg0.FocusBorder:setAlpha( 0 )
				f44_arg0.FocusBorder:registerEventHandler( "interrupted_keyframe", f44_arg0.clipInterrupted )
				f44_arg0.FocusBorder:registerEventHandler( "transition_complete_keyframe", f44_arg0.clipFinished )
			end
			
			f44_arg0.FocusBorder:completeAnimation()
			f44_arg0.FocusBorder:setRGB( ColorSet.T8__OFF__WHITE.r, ColorSet.T8__OFF__WHITE.g, ColorSet.T8__OFF__WHITE.b )
			f44_arg0.FocusBorder:setAlpha( 0.25 )
			f44_local1( f44_arg0.FocusBorder )
		end
	}
}
CoD.CommonButtonGenericInternal.__onClose = function ( f47_arg0 )
	f47_arg0.FocusBrackets:close()
	f47_arg0.DotTiledBacking:close()
	f47_arg0.Lines:close()
end

