require( "ui/uieditor/widgets/callingcards/callingcards_framewidget" )
require( "ui/uieditor/widgets/common/commoncornerpips02" )

CoD.Prestige_PrestigeButton_Internal = InheritFrom( LUI.UIElement )
CoD.Prestige_PrestigeButton_Internal.__defaultWidth = 400
CoD.Prestige_PrestigeButton_Internal.__defaultHeight = 94
CoD.Prestige_PrestigeButton_Internal.new = function ( f1_arg0, f1_arg1, f1_arg2, f1_arg3, f1_arg4, f1_arg5, f1_arg6, f1_arg7, f1_arg8, f1_arg9 )
	local self = LUI.UIElement.new( f1_arg2, f1_arg3, f1_arg4, f1_arg5, f1_arg6, f1_arg7, f1_arg8, f1_arg9 )
	self:setClass( CoD.Prestige_PrestigeButton_Internal )
	self.id = "Prestige_PrestigeButton_Internal"
	self.soundSet = "default"
	self.anyChildUsesUpdateState = true
	f1_arg0:addElementToPendingUpdateStateList( self )
	
	local FocusGlow2 = LUI.UIImage.new( 0, 1, -128, 128, 0, 1, -48, 48 )
	FocusGlow2:setAlpha( 0 )
	FocusGlow2:setImage( RegisterImage( "uie_ui_menu_common_focus_glow_small" ) )
	FocusGlow2:setMaterial( LUI.UIImage.GetCachedMaterial( 0xDAB59B2CAE01851 ) )
	FocusGlow2:setShaderVector( 0, 0, 0, 0.4, 0.51 )
	FocusGlow2:setShaderVector( 1, 1.2, 0, 0, 0 )
	FocusGlow2:setupNineSliceShader( 60, 40 )
	self:addElement( FocusGlow2 )
	self.FocusGlow2 = FocusGlow2
	
	local BodyBacker = LUI.UIImage.new( 0.5, 0.5, -200, 200, 0.5, 0.5, -47, 47 )
	BodyBacker:setRGB( 0.1, 0.1, 0.1 )
	BodyBacker:setAlpha( 0.2 )
	self:addElement( BodyBacker )
	self.BodyBacker = BodyBacker
	
	local PrestigeBreadcrumb = LUI.UIImage.new( 0, 1, 0, 0, 0, 1, 0, 0 )
	PrestigeBreadcrumb:setRGB( ColorSet.PlayerCount.r, ColorSet.PlayerCount.g, ColorSet.PlayerCount.b )
	PrestigeBreadcrumb:setAlpha( 0 )
	self:addElement( PrestigeBreadcrumb )
	self.PrestigeBreadcrumb = PrestigeBreadcrumb
	
	local NoiseTiledBacking = LUI.UIImage.new( 0.5, 0.5, -200, 200, 0.5, 0.5, -47, 47 )
	NoiseTiledBacking:setAlpha( 0.5 )
	NoiseTiledBacking:setImage( RegisterImage( "uie_ui_menu_specialist_hub_repeat_bg" ) )
	NoiseTiledBacking:setMaterial( LUI.UIImage.GetCachedMaterial( 0x6CBE95C250C6D15 ) )
	NoiseTiledBacking:setShaderVector( 0, 0, 0, 0, 0 )
	NoiseTiledBacking:setupNineSliceShader( 196, 88 )
	self:addElement( NoiseTiledBacking )
	self.NoiseTiledBacking = NoiseTiledBacking
	
	local TiledDotBg = LUI.UIImage.new( 0, 1, 4, -4, 0, 1, 3, -3 )
	TiledDotBg:setImage( RegisterImage( "uie_ui_menu_store_repeat_dot_pattern" ) )
	TiledDotBg:setMaterial( LUI.UIImage.GetCachedMaterial( 0x7C9C02F608D0A75 ) )
	TiledDotBg:setShaderVector( 0, 0, 0, 0, 0 )
	TiledDotBg:setupNineSliceShader( 24, 24 )
	self:addElement( TiledDotBg )
	self.TiledDotBg = TiledDotBg
	
	local CommonCornerPips2 = CoD.CommonCornerPips02.new( f1_arg0, f1_arg1, 0, 1, 0, 0, 0, 1, 0, 0 )
	CommonCornerPips2:setAlpha( 0.2 )
	self:addElement( CommonCornerPips2 )
	self.CommonCornerPips2 = CommonCornerPips2
	
	local TiledDotBgAdd = LUI.UIImage.new( 0, 1, 4, -4, 0, 1, 3, -3 )
	TiledDotBgAdd:setAlpha( 0 )
	TiledDotBgAdd:setImage( RegisterImage( "uie_ui_menu_store_repeat_dot_pattern" ) )
	TiledDotBgAdd:setMaterial( LUI.UIImage.GetCachedMaterial( 0x7C9C02F608D0A75 ) )
	TiledDotBgAdd:setShaderVector( 0, 0, 0, 0, 0 )
	TiledDotBgAdd:setupNineSliceShader( 24, 24 )
	self:addElement( TiledDotBgAdd )
	self.TiledDotBgAdd = TiledDotBgAdd
	
	local ButtonFrame = LUI.UIImage.new( 0, 1, -1, 1, 0, 1, -1, 1 )
	ButtonFrame:setAlpha( 0 )
	ButtonFrame:setImage( RegisterImage( "uie_ui_menu_store_common_frame" ) )
	ButtonFrame:setMaterial( LUI.UIImage.GetCachedMaterial( "uie_nineslice_add" ) )
	ButtonFrame:setShaderVector( 0, 0, 0, 0, 0 )
	ButtonFrame:setupNineSliceShader( 12, 12 )
	self:addElement( ButtonFrame )
	self.ButtonFrame = ButtonFrame
	
	local CallingCardsFrameWidget = CoD.CallingCards_FrameWidget.new( f1_arg0, f1_arg1, 0.5, 0.5, -121, 121, 0.5, 0.5, -24.5, 35.5 )
	CallingCardsFrameWidget:setAlpha( 0 )
	CallingCardsFrameWidget:subscribeToGlobalModel( f1_arg1, "PrestigeCallingCard", nil, function ( model )
		CallingCardsFrameWidget:setModel( model, f1_arg1 )
	end )
	self:addElement( CallingCardsFrameWidget )
	self.CallingCardsFrameWidget = CallingCardsFrameWidget
	
	local PrestigeRewardIcon = LUI.UIImage.new( 0, 0, 342, 390, 0, 0, 28.5, 76.5 )
	PrestigeRewardIcon:setImage( RegisterImage( 0x7AABA8DF18A3887 ) )
	self:addElement( PrestigeRewardIcon )
	self.PrestigeRewardIcon = PrestigeRewardIcon
	
	local PrestigeIcon = LUI.UIImage.new( 0, 0, 5, 53, 0, 0, 28.5, 76.5 )
	PrestigeIcon:subscribeToGlobalModel( f1_arg1, "PrestigeMenuInfo", "hasPrestiged", function ( model )
		local f3_local0 = model:get()
		if f3_local0 ~= nil then
			PrestigeIcon:setImage( RegisterImage( CoD.PlayerStatsUtility.GetNextPrestigeIcon( f1_arg0, false, f3_local0 ) ) )
		end
	end )
	self:addElement( PrestigeIcon )
	self.PrestigeIcon = PrestigeIcon
	
	local TextBox1 = LUI.UIText.new( 0, 0, 60, 394, 0, 0, 11, 26 )
	TextBox1:setRGB( 0.67, 0.7, 0.75 )
	TextBox1:setTTF( "ttmussels_regular" )
	TextBox1:setAlignment( Enum.LUIAlignment[0x58C8A85F2048829] )
	TextBox1:subscribeToGlobalModel( f1_arg1, "PrestigeMenuInfo", "hasPrestiged", function ( model )
		local f4_local0 = model:get()
		if f4_local0 ~= nil then
			TextBox1:setText( ToUpper( CoD.PlayerStatsUtility.GetPrestigeRewardsString( f1_arg0, f4_local0 ) ) )
		end
	end )
	self:addElement( TextBox1 )
	self.TextBox1 = TextBox1
	
	local TextBox2 = LUI.UIText.new( 0.5, 0.5, -200, 200, 0, 0, -32, -2 )
	TextBox2:setText( Engine[0xF9F1239CFD921FE]( 0xCDCAF64947D12E5 ) )
	TextBox2:setTTF( "ttmussels_regular" )
	TextBox2:setMaterial( LUI.UIImage.GetCachedMaterial( 0x336C1AE82B1520A ) )
	TextBox2:setAlignment( Enum.LUIAlignment[0xFEEB12BCB0D7041] )
	TextBox2:setAlignment( Enum.LUIAlignment[0xE821F0ECFF8D1C7] )
	self:addElement( TextBox2 )
	self.TextBox2 = TextBox2
	
	local TextBox2Alternate = LUI.UIText.new( 0, 0, 60, 367, 0, 0, 33.5, 51.5 )
	TextBox2Alternate:setTTF( "ttmussels_regular" )
	TextBox2Alternate:setAlignment( Enum.LUIAlignment[0x58C8A85F2048829] )
	TextBox2Alternate:setAlignment( Enum.LUIAlignment[0xE821F0ECFF8D1C7] )
	TextBox2Alternate:subscribeToGlobalModel( f1_arg1, "PrestigeMenuInfo", "hasPrestiged", function ( model )
		local f5_local0 = model:get()
		if f5_local0 ~= nil then
			TextBox2Alternate:setText( Engine[0xF9F1239CFD921FE]( CoD.PlayerStatsUtility.GetPrestigeRequirementString( f1_arg0, f5_local0 ) ) )
		end
	end )
	self:addElement( TextBox2Alternate )
	self.TextBox2Alternate = TextBox2Alternate
	
	local LevelProgressText = LUI.UIText.new( 0, 0, 59, 169, 0, 0, 70.5, 88.5 )
	LevelProgressText:setRGB( 0.92, 0.92, 0.92 )
	LevelProgressText:setTTF( "ttmussels_regular" )
	LevelProgressText:setAlignment( Enum.LUIAlignment[0x58C8A85F2048829] )
	LevelProgressText:setAlignment( Enum.LUIAlignment[0xF41D595A2B0EDF3] )
	LevelProgressText:subscribeToGlobalModel( f1_arg1, "PrestigeMenuInfo", "hasPrestiged", function ( model )
		local f6_local0 = model:get()
		if f6_local0 ~= nil then
			LevelProgressText:setText( Engine[0xF9F1239CFD921FE]( CoD.PlayerStatsUtility.GetPrestigeProgressFractionString( f1_arg0, f6_local0 ) ) )
		end
	end )
	self:addElement( LevelProgressText )
	self.LevelProgressText = LevelProgressText
	
	local NextPrestigeText = LUI.UIText.new( 0, 0, 180, 379, 0, 0, 70.5, 88.5 )
	NextPrestigeText:setRGB( 0.92, 0.92, 0.92 )
	NextPrestigeText:setTTF( "ttmussels_regular" )
	NextPrestigeText:setAlignment( Enum.LUIAlignment[0x830CFD395E6AA0A] )
	NextPrestigeText:setAlignment( Enum.LUIAlignment[0xF41D595A2B0EDF3] )
	NextPrestigeText:subscribeToGlobalModel( f1_arg1, "PrestigeMenuInfo", "hasPrestiged", function ( model )
		local f7_local0 = model:get()
		if f7_local0 ~= nil then
			NextPrestigeText:setText( ConvertToUpperString( CoD.PlayerStatsUtility.GetNextPrestigeString( f1_arg0, f7_local0 ) ) )
		end
	end )
	self:addElement( NextPrestigeText )
	self.NextPrestigeText = NextPrestigeText
	
	local BarBG = CoD.CommonCornerPips02.new( f1_arg0, f1_arg1, 0, 0, 60, 376, 0, 0, 53.5, 61.5 )
	BarBG:setAlpha( 0.2 )
	self:addElement( BarBG )
	self.BarBG = BarBG
	
	local PrestigeProgressCenterBar = LUI.UIImage.new( 0, 0, 60, 376, 0, 0, 56, 59 )
	PrestigeProgressCenterBar:setRGB( 0, 0, 0 )
	PrestigeProgressCenterBar:setAlpha( 0.3 )
	self:addElement( PrestigeProgressCenterBar )
	self.PrestigeProgressCenterBar = PrestigeProgressCenterBar
	
	local PrestigeProgressBar = LUI.UIImage.new( 0, 0, 60, 376, 0, 0, 53.5, 61.5 )
	PrestigeProgressBar:setRGB( ColorSet.PlayerCount.r, ColorSet.PlayerCount.g, ColorSet.PlayerCount.b )
	PrestigeProgressBar:setMaterial( LUI.UIImage.GetCachedMaterial( "uie_wipe_normal" ) )
	PrestigeProgressBar:setShaderVector( 1, 0, 0, 0, 0 )
	PrestigeProgressBar:setShaderVector( 2, 1, 0, 0, 0 )
	PrestigeProgressBar:setShaderVector( 3, 0, 0, 0, 0 )
	PrestigeProgressBar:setShaderVector( 4, 0, 0, 0, 0 )
	PrestigeProgressBar:subscribeToGlobalModel( f1_arg1, "PrestigeMenuInfo", "hasPrestiged", function ( model )
		local f8_local0 = model:get()
		if f8_local0 ~= nil then
			PrestigeProgressBar:setShaderVector( 0, CoD.PlayerStatsUtility.GetPrestigeProgress( f1_arg0, CoD.GetVectorComponentFromString( f8_local0, 1 ), CoD.GetVectorComponentFromString( f8_local0, 2 ), CoD.GetVectorComponentFromString( f8_local0, 3 ), CoD.GetVectorComponentFromString( f8_local0, 4 ) ) )
		end
	end )
	self:addElement( PrestigeProgressBar )
	self.PrestigeProgressBar = PrestigeProgressBar
	
	local FrontendFrameSelected = LUI.UIImage.new( 0, 1, -2, 2, 0, 1, -2, 2 )
	FrontendFrameSelected:setAlpha( 0 )
	FrontendFrameSelected:setImage( RegisterImage( "uie_ui_menu_store_focus_frame" ) )
	FrontendFrameSelected:setMaterial( LUI.UIImage.GetCachedMaterial( "uie_nineslice_add" ) )
	FrontendFrameSelected:setShaderVector( 0, 0, 0, 0, 0 )
	FrontendFrameSelected:setupNineSliceShader( 4, 4 )
	self:addElement( FrontendFrameSelected )
	self.FrontendFrameSelected = FrontendFrameSelected
	
	self:mergeStateConditions( {
		{
			stateName = "PrestigeReady",
			condition = function ( menu, element, event )
				local f9_local0 = IsAtXPCap( f1_arg1 )
				if f9_local0 then
					if not IsMaxPrestigeLevel( f1_arg1 ) then
						f9_local0 = not IsWarzone()
					else
						f9_local0 = false
					end
				end
				return f9_local0
			end
		},
		{
			stateName = "PrestigeReadyWZ",
			condition = function ( menu, element, event )
				local f10_local0 = IsAtXPCap( f1_arg1 )
				if f10_local0 then
					if not IsMaxPrestigeLevel( f1_arg1 ) then
						f10_local0 = IsWarzone()
					else
						f10_local0 = false
					end
				end
				return f10_local0
			end
		},
		{
			stateName = "MasterPrestige",
			condition = function ( menu, element, event )
				return IsMaxPrestigeLevel( f1_arg1 )
			end
		}
	} )
	local f1_local21 = self
	local f1_local22 = self.subscribeToModel
	local f1_local23 = Engine.GetGlobalModel()
	f1_local22( f1_local21, f1_local23["lobbyRoot.lobbyNav"], function ( f12_arg0 )
		f1_arg0:updateElementState( self, {
			name = "model_validation",
			menu = f1_arg0,
			controller = f1_arg1,
			modelValue = f12_arg0:get(),
			modelName = "lobbyRoot.lobbyNav"
		} )
	end, false )
	CallingCardsFrameWidget.id = "CallingCardsFrameWidget"
	LUI.OverrideFunction_CallOriginalSecond( self, "close", self.__onClose )
	
	if PostLoadFunc then
		PostLoadFunc( self, f1_arg1, f1_arg0 )
	end
	
	f1_local22 = self
	CoD.PlayerStatsUtility.SetNextPrestigeCallingCard( f1_arg0, f1_arg1, CallingCardsFrameWidget )
	return self
end

CoD.Prestige_PrestigeButton_Internal.__resetProperties = function ( f13_arg0 )
	f13_arg0.PrestigeRewardIcon:completeAnimation()
	f13_arg0.TextBox2:completeAnimation()
	f13_arg0.CallingCardsFrameWidget:completeAnimation()
	f13_arg0.TextBox2Alternate:completeAnimation()
	f13_arg0.PrestigeIcon:completeAnimation()
	f13_arg0.ButtonFrame:completeAnimation()
	f13_arg0.NextPrestigeText:completeAnimation()
	f13_arg0.LevelProgressText:completeAnimation()
	f13_arg0.PrestigeProgressBar:completeAnimation()
	f13_arg0.PrestigeBreadcrumb:completeAnimation()
	f13_arg0.TextBox1:completeAnimation()
	f13_arg0.BarBG:completeAnimation()
	f13_arg0.PrestigeProgressCenterBar:completeAnimation()
	f13_arg0.CommonCornerPips2:completeAnimation()
	f13_arg0.TiledDotBgAdd:completeAnimation()
	f13_arg0.FocusGlow2:completeAnimation()
	f13_arg0.FrontendFrameSelected:completeAnimation()
	f13_arg0.PrestigeRewardIcon:setLeftRight( 0, 0, 342, 390 )
	f13_arg0.PrestigeRewardIcon:setAlpha( 1 )
	f13_arg0.TextBox2:setRGB( 1, 1, 1 )
	f13_arg0.TextBox2:setAlpha( 1 )
	f13_arg0.TextBox2:setText( Engine[0xF9F1239CFD921FE]( 0xCDCAF64947D12E5 ) )
	f13_arg0.TextBox2:setAlignment( Enum.LUIAlignment[0xFEEB12BCB0D7041] )
	f13_arg0.CallingCardsFrameWidget:setLeftRight( 0.5, 0.5, -121, 121 )
	f13_arg0.CallingCardsFrameWidget:setTopBottom( 0.5, 0.5, -24.5, 35.5 )
	f13_arg0.CallingCardsFrameWidget:setAlpha( 0 )
	f13_arg0.TextBox2Alternate:setAlpha( 1 )
	f13_arg0.PrestigeIcon:setLeftRight( 0, 0, 5, 53 )
	f13_arg0.PrestigeIcon:setTopBottom( 0, 0, 28.5, 76.5 )
	f13_arg0.PrestigeIcon:setRGB( 1, 1, 1 )
	f13_arg0.PrestigeIcon:setAlpha( 1 )
	f13_arg0.ButtonFrame:setAlpha( 0 )
	f13_arg0.NextPrestigeText:setAlpha( 1 )
	f13_arg0.LevelProgressText:setAlpha( 1 )
	f13_arg0.PrestigeProgressBar:setAlpha( 1 )
	f13_arg0.PrestigeBreadcrumb:setRGB( ColorSet.PlayerCount.r, ColorSet.PlayerCount.g, ColorSet.PlayerCount.b )
	f13_arg0.PrestigeBreadcrumb:setAlpha( 0 )
	f13_arg0.TextBox1:setLeftRight( 0, 0, 60, 394 )
	f13_arg0.TextBox1:setTopBottom( 0, 0, 11, 26 )
	f13_arg0.TextBox1:setAlpha( 1 )
	f13_arg0.TextBox1:setAlignment( Enum.LUIAlignment[0x58C8A85F2048829] )
	f13_arg0.BarBG:setAlpha( 0.2 )
	f13_arg0.PrestigeProgressCenterBar:setAlpha( 0.3 )
	f13_arg0.CommonCornerPips2:setAlpha( 0.2 )
	f13_arg0.TiledDotBgAdd:setAlpha( 0 )
	f13_arg0.FocusGlow2:setAlpha( 0 )
	f13_arg0.FrontendFrameSelected:setAlpha( 0 )
end

CoD.Prestige_PrestigeButton_Internal.__clipsPerState = {
	DefaultState = {
		DefaultClip = function ( f14_arg0, f14_arg1 )
			f14_arg0:__resetProperties()
			f14_arg0:setupElementClipCounter( 6 )
			f14_arg0.ButtonFrame:completeAnimation()
			f14_arg0.ButtonFrame:setAlpha( 0.2 )
			f14_arg0.clipFinished( f14_arg0.ButtonFrame )
			f14_arg0.CallingCardsFrameWidget:completeAnimation()
			f14_arg0.CallingCardsFrameWidget:setAlpha( 0 )
			f14_arg0.clipFinished( f14_arg0.CallingCardsFrameWidget )
			f14_arg0.PrestigeRewardIcon:completeAnimation()
			f14_arg0.PrestigeRewardIcon:setAlpha( 0 )
			f14_arg0.clipFinished( f14_arg0.PrestigeRewardIcon )
			f14_arg0.PrestigeIcon:completeAnimation()
			f14_arg0.PrestigeIcon:setTopBottom( 0, 0, 26.5, 74.5 )
			f14_arg0.PrestigeIcon:setRGB( 0.5, 0.5, 0.5 )
			f14_arg0.clipFinished( f14_arg0.PrestigeIcon )
			f14_arg0.TextBox2:completeAnimation()
			f14_arg0.TextBox2:setAlpha( 0 )
			f14_arg0.TextBox2:setText( Engine[0xF9F1239CFD921FE]( 0xE84CE29A8B160AD ) )
			f14_arg0.clipFinished( f14_arg0.TextBox2 )
			f14_arg0.TextBox2Alternate:completeAnimation()
			f14_arg0.TextBox2Alternate:setAlpha( 1 )
			f14_arg0.clipFinished( f14_arg0.TextBox2Alternate )
		end
	},
	PrestigeReady = {
		DefaultClip = function ( f15_arg0, f15_arg1 )
			f15_arg0:__resetProperties()
			f15_arg0:setupElementClipCounter( 16 )
			f15_arg0.FocusGlow2:completeAnimation()
			f15_arg0.FocusGlow2:setAlpha( 0 )
			f15_arg0.clipFinished( f15_arg0.FocusGlow2 )
			f15_arg0.PrestigeBreadcrumb:completeAnimation()
			f15_arg0.PrestigeBreadcrumb:setRGB( ColorSet.PlayerCount.r, ColorSet.PlayerCount.g, ColorSet.PlayerCount.b )
			f15_arg0.PrestigeBreadcrumb:setAlpha( 0.5 )
			f15_arg0.clipFinished( f15_arg0.PrestigeBreadcrumb )
			f15_arg0.CommonCornerPips2:completeAnimation()
			f15_arg0.CommonCornerPips2:setAlpha( 0.2 )
			f15_arg0.clipFinished( f15_arg0.CommonCornerPips2 )
			f15_arg0.TiledDotBgAdd:completeAnimation()
			f15_arg0.TiledDotBgAdd:setAlpha( 1 )
			f15_arg0.clipFinished( f15_arg0.TiledDotBgAdd )
			f15_arg0.ButtonFrame:completeAnimation()
			f15_arg0.ButtonFrame:setAlpha( 1 )
			f15_arg0.clipFinished( f15_arg0.ButtonFrame )
			f15_arg0.CallingCardsFrameWidget:completeAnimation()
			f15_arg0.CallingCardsFrameWidget:setAlpha( 1 )
			f15_arg0.clipFinished( f15_arg0.CallingCardsFrameWidget )
			f15_arg0.PrestigeRewardIcon:completeAnimation()
			f15_arg0.PrestigeRewardIcon:setLeftRight( 0, 0, 336, 384 )
			f15_arg0.clipFinished( f15_arg0.PrestigeRewardIcon )
			f15_arg0.PrestigeIcon:completeAnimation()
			f15_arg0.PrestigeIcon:setLeftRight( 0, 0, 15, 63 )
			f15_arg0.clipFinished( f15_arg0.PrestigeIcon )
			f15_arg0.TextBox1:completeAnimation()
			f15_arg0.TextBox1:setLeftRight( 0, 0, 100, 300 )
			f15_arg0.TextBox1:setTopBottom( 0, 0, 8, 23 )
			f15_arg0.TextBox1:setAlignment( Enum.LUIAlignment[0xFEEB12BCB0D7041] )
			f15_arg0.clipFinished( f15_arg0.TextBox1 )
			f15_arg0.TextBox2:completeAnimation()
			f15_arg0.TextBox2:setRGB( 0.92, 0.92, 0.92 )
			f15_arg0.TextBox2:setAlpha( 1 )
			f15_arg0.clipFinished( f15_arg0.TextBox2 )
			f15_arg0.TextBox2Alternate:completeAnimation()
			f15_arg0.TextBox2Alternate:setAlpha( 0 )
			f15_arg0.clipFinished( f15_arg0.TextBox2Alternate )
			f15_arg0.LevelProgressText:completeAnimation()
			f15_arg0.LevelProgressText:setAlpha( 0 )
			f15_arg0.clipFinished( f15_arg0.LevelProgressText )
			f15_arg0.NextPrestigeText:completeAnimation()
			f15_arg0.NextPrestigeText:setAlpha( 0 )
			f15_arg0.clipFinished( f15_arg0.NextPrestigeText )
			f15_arg0.BarBG:completeAnimation()
			f15_arg0.BarBG:setAlpha( 0 )
			f15_arg0.clipFinished( f15_arg0.BarBG )
			f15_arg0.PrestigeProgressCenterBar:completeAnimation()
			f15_arg0.PrestigeProgressCenterBar:setAlpha( 0 )
			f15_arg0.clipFinished( f15_arg0.PrestigeProgressCenterBar )
			f15_arg0.PrestigeProgressBar:completeAnimation()
			f15_arg0.PrestigeProgressBar:setAlpha( 0 )
			f15_arg0.clipFinished( f15_arg0.PrestigeProgressBar )
		end,
		Focus = function ( f16_arg0, f16_arg1 )
			f16_arg0:__resetProperties()
			f16_arg0:setupElementClipCounter( 17 )
			f16_arg0.FocusGlow2:completeAnimation()
			f16_arg0.FocusGlow2:setAlpha( 0.5 )
			f16_arg0.clipFinished( f16_arg0.FocusGlow2 )
			f16_arg0.PrestigeBreadcrumb:completeAnimation()
			f16_arg0.PrestigeBreadcrumb:setAlpha( 0.9 )
			f16_arg0.clipFinished( f16_arg0.PrestigeBreadcrumb )
			f16_arg0.CommonCornerPips2:completeAnimation()
			f16_arg0.CommonCornerPips2:setAlpha( 0.2 )
			f16_arg0.clipFinished( f16_arg0.CommonCornerPips2 )
			f16_arg0.TiledDotBgAdd:completeAnimation()
			f16_arg0.TiledDotBgAdd:setAlpha( 1 )
			f16_arg0.clipFinished( f16_arg0.TiledDotBgAdd )
			f16_arg0.ButtonFrame:completeAnimation()
			f16_arg0.ButtonFrame:setAlpha( 1 )
			f16_arg0.clipFinished( f16_arg0.ButtonFrame )
			f16_arg0.CallingCardsFrameWidget:completeAnimation()
			f16_arg0.CallingCardsFrameWidget:setAlpha( 1 )
			f16_arg0.clipFinished( f16_arg0.CallingCardsFrameWidget )
			f16_arg0.PrestigeRewardIcon:completeAnimation()
			f16_arg0.PrestigeRewardIcon:setLeftRight( 0, 0, 336, 384 )
			f16_arg0.clipFinished( f16_arg0.PrestigeRewardIcon )
			f16_arg0.PrestigeIcon:completeAnimation()
			f16_arg0.PrestigeIcon:setLeftRight( 0, 0, 15, 63 )
			f16_arg0.clipFinished( f16_arg0.PrestigeIcon )
			f16_arg0.TextBox1:completeAnimation()
			f16_arg0.TextBox1:setLeftRight( 0, 0, 100, 300 )
			f16_arg0.TextBox1:setTopBottom( 0, 0, 8, 23 )
			f16_arg0.TextBox1:setAlignment( Enum.LUIAlignment[0xFEEB12BCB0D7041] )
			f16_arg0.clipFinished( f16_arg0.TextBox1 )
			f16_arg0.TextBox2:completeAnimation()
			f16_arg0.TextBox2:setRGB( ColorSet.T8__BIEGE.r, ColorSet.T8__BIEGE.g, ColorSet.T8__BIEGE.b )
			f16_arg0.TextBox2:setAlpha( 1 )
			f16_arg0.TextBox2:setAlignment( Enum.LUIAlignment[0xFEEB12BCB0D7041] )
			f16_arg0.clipFinished( f16_arg0.TextBox2 )
			f16_arg0.TextBox2Alternate:completeAnimation()
			f16_arg0.TextBox2Alternate:setAlpha( 0 )
			f16_arg0.clipFinished( f16_arg0.TextBox2Alternate )
			f16_arg0.LevelProgressText:completeAnimation()
			f16_arg0.LevelProgressText:setAlpha( 0 )
			f16_arg0.clipFinished( f16_arg0.LevelProgressText )
			f16_arg0.NextPrestigeText:completeAnimation()
			f16_arg0.NextPrestigeText:setAlpha( 0 )
			f16_arg0.clipFinished( f16_arg0.NextPrestigeText )
			f16_arg0.BarBG:completeAnimation()
			f16_arg0.BarBG:setAlpha( 0 )
			f16_arg0.clipFinished( f16_arg0.BarBG )
			f16_arg0.PrestigeProgressCenterBar:completeAnimation()
			f16_arg0.PrestigeProgressCenterBar:setAlpha( 0 )
			f16_arg0.clipFinished( f16_arg0.PrestigeProgressCenterBar )
			f16_arg0.PrestigeProgressBar:completeAnimation()
			f16_arg0.PrestigeProgressBar:setAlpha( 0 )
			f16_arg0.clipFinished( f16_arg0.PrestigeProgressBar )
			f16_arg0.FrontendFrameSelected:completeAnimation()
			f16_arg0.FrontendFrameSelected:setAlpha( 1 )
			f16_arg0.clipFinished( f16_arg0.FrontendFrameSelected )
		end,
		Intro = function ( f17_arg0, f17_arg1 )
			f17_arg0:__resetProperties()
			f17_arg0:setupElementClipCounter( 15 )
			f17_arg0.FocusGlow2:completeAnimation()
			f17_arg0.FocusGlow2:setAlpha( 0 )
			f17_arg0.clipFinished( f17_arg0.FocusGlow2 )
			local f17_local0 = function ( f18_arg0 )
				local f18_local0 = function ( f19_arg0 )
					local f19_local0 = function ( f20_arg0 )
						f20_arg0:beginAnimation( 900 )
						f20_arg0:setAlpha( 0.5 )
						f20_arg0:registerEventHandler( "transition_complete_keyframe", f17_arg0.clipFinished )
					end
					
					f19_arg0:beginAnimation( 300, Enum[0xF50FFF429AB1890][0x5193EA7825DC097] )
					f19_arg0:setAlpha( 0 )
					f19_arg0:registerEventHandler( "transition_complete_keyframe", f19_local0 )
				end
				
				f17_arg0.PrestigeBreadcrumb:beginAnimation( 300, Enum[0xF50FFF429AB1890][0x5193EA7825DC097] )
				f17_arg0.PrestigeBreadcrumb:setAlpha( 1 )
				f17_arg0.PrestigeBreadcrumb:registerEventHandler( "interrupted_keyframe", f17_arg0.clipInterrupted )
				f17_arg0.PrestigeBreadcrumb:registerEventHandler( "transition_complete_keyframe", f18_local0 )
			end
			
			f17_arg0.PrestigeBreadcrumb:completeAnimation()
			f17_arg0.PrestigeBreadcrumb:setAlpha( 0 )
			f17_local0( f17_arg0.PrestigeBreadcrumb )
			local f17_local1 = function ( f21_arg0 )
				local f21_local0 = function ( f22_arg0 )
					f22_arg0:beginAnimation( 900 )
					f22_arg0:setAlpha( 1 )
					f22_arg0:registerEventHandler( "transition_complete_keyframe", f17_arg0.clipFinished )
				end
				
				f17_arg0.ButtonFrame:beginAnimation( 600 )
				f17_arg0.ButtonFrame:registerEventHandler( "interrupted_keyframe", f17_arg0.clipInterrupted )
				f17_arg0.ButtonFrame:registerEventHandler( "transition_complete_keyframe", f21_local0 )
			end
			
			f17_arg0.ButtonFrame:completeAnimation()
			f17_arg0.ButtonFrame:setAlpha( 0 )
			f17_local1( f17_arg0.ButtonFrame )
			local f17_local2 = function ( f23_arg0 )
				f17_arg0.CallingCardsFrameWidget:beginAnimation( 300 )
				f17_arg0.CallingCardsFrameWidget:setAlpha( 1 )
				f17_arg0.CallingCardsFrameWidget:registerEventHandler( "interrupted_keyframe", f17_arg0.clipInterrupted )
				f17_arg0.CallingCardsFrameWidget:registerEventHandler( "transition_complete_keyframe", f17_arg0.clipFinished )
			end
			
			f17_arg0.CallingCardsFrameWidget:completeAnimation()
			f17_arg0.CallingCardsFrameWidget:setAlpha( 0 )
			f17_local2( f17_arg0.CallingCardsFrameWidget )
			local f17_local3 = function ( f24_arg0 )
				f17_arg0.PrestigeRewardIcon:beginAnimation( 300 )
				f17_arg0.PrestigeRewardIcon:setAlpha( 1 )
				f17_arg0.PrestigeRewardIcon:registerEventHandler( "interrupted_keyframe", f17_arg0.clipInterrupted )
				f17_arg0.PrestigeRewardIcon:registerEventHandler( "transition_complete_keyframe", f17_arg0.clipFinished )
			end
			
			f17_arg0.PrestigeRewardIcon:completeAnimation()
			f17_arg0.PrestigeRewardIcon:setLeftRight( 0, 0, 336, 384 )
			f17_arg0.PrestigeRewardIcon:setAlpha( 0 )
			f17_local3( f17_arg0.PrestigeRewardIcon )
			local f17_local4 = function ( f25_arg0 )
				f17_arg0.PrestigeIcon:beginAnimation( 300 )
				f17_arg0.PrestigeIcon:setAlpha( 1 )
				f17_arg0.PrestigeIcon:registerEventHandler( "interrupted_keyframe", f17_arg0.clipInterrupted )
				f17_arg0.PrestigeIcon:registerEventHandler( "transition_complete_keyframe", f17_arg0.clipFinished )
			end
			
			f17_arg0.PrestigeIcon:completeAnimation()
			f17_arg0.PrestigeIcon:setLeftRight( 0, 0, 15, 63 )
			f17_arg0.PrestigeIcon:setAlpha( 0 )
			f17_local4( f17_arg0.PrestigeIcon )
			local f17_local5 = function ( f26_arg0 )
				f17_arg0.TextBox1:beginAnimation( 300 )
				f17_arg0.TextBox1:setAlpha( 1 )
				f17_arg0.TextBox1:registerEventHandler( "interrupted_keyframe", f17_arg0.clipInterrupted )
				f17_arg0.TextBox1:registerEventHandler( "transition_complete_keyframe", f17_arg0.clipFinished )
			end
			
			f17_arg0.TextBox1:completeAnimation()
			f17_arg0.TextBox1:setLeftRight( 0, 0, 100, 300 )
			f17_arg0.TextBox1:setTopBottom( 0, 0, 8, 23 )
			f17_arg0.TextBox1:setAlpha( 0 )
			f17_arg0.TextBox1:setAlignment( Enum.LUIAlignment[0xFEEB12BCB0D7041] )
			f17_local5( f17_arg0.TextBox1 )
			local f17_local6 = function ( f27_arg0 )
				local f27_local0 = function ( f28_arg0 )
					f28_arg0:beginAnimation( 600 )
					f28_arg0:setAlpha( 1 )
					f28_arg0:registerEventHandler( "transition_complete_keyframe", f17_arg0.clipFinished )
				end
				
				f17_arg0.TextBox2:beginAnimation( 600 )
				f17_arg0.TextBox2:registerEventHandler( "interrupted_keyframe", f17_arg0.clipInterrupted )
				f17_arg0.TextBox2:registerEventHandler( "transition_complete_keyframe", f27_local0 )
			end
			
			f17_arg0.TextBox2:completeAnimation()
			f17_arg0.TextBox2:setRGB( 0.92, 0.92, 0.92 )
			f17_arg0.TextBox2:setAlpha( 0 )
			f17_local6( f17_arg0.TextBox2 )
			f17_arg0.TextBox2Alternate:completeAnimation()
			f17_arg0.TextBox2Alternate:setAlpha( 0 )
			f17_arg0.clipFinished( f17_arg0.TextBox2Alternate )
			f17_arg0.LevelProgressText:completeAnimation()
			f17_arg0.LevelProgressText:setAlpha( 0 )
			f17_arg0.clipFinished( f17_arg0.LevelProgressText )
			f17_arg0.NextPrestigeText:completeAnimation()
			f17_arg0.NextPrestigeText:setAlpha( 0 )
			f17_arg0.clipFinished( f17_arg0.NextPrestigeText )
			f17_arg0.BarBG:completeAnimation()
			f17_arg0.BarBG:setAlpha( 0 )
			f17_arg0.clipFinished( f17_arg0.BarBG )
			f17_arg0.PrestigeProgressCenterBar:completeAnimation()
			f17_arg0.PrestigeProgressCenterBar:setAlpha( 0 )
			f17_arg0.clipFinished( f17_arg0.PrestigeProgressCenterBar )
			f17_arg0.PrestigeProgressBar:completeAnimation()
			f17_arg0.PrestigeProgressBar:setAlpha( 0 )
			f17_arg0.clipFinished( f17_arg0.PrestigeProgressBar )
			local f17_local7 = function ( f29_arg0 )
				local f29_local0 = function ( f30_arg0 )
					f30_arg0:beginAnimation( 300 )
					f30_arg0:setAlpha( 0 )
					f30_arg0:registerEventHandler( "transition_complete_keyframe", f17_arg0.clipFinished )
				end
				
				f17_arg0.FrontendFrameSelected:beginAnimation( 300 )
				f17_arg0.FrontendFrameSelected:setAlpha( 1 )
				f17_arg0.FrontendFrameSelected:registerEventHandler( "interrupted_keyframe", f17_arg0.clipInterrupted )
				f17_arg0.FrontendFrameSelected:registerEventHandler( "transition_complete_keyframe", f29_local0 )
			end
			
			f17_arg0.FrontendFrameSelected:completeAnimation()
			f17_arg0.FrontendFrameSelected:setAlpha( 0 )
			f17_local7( f17_arg0.FrontendFrameSelected )
		end,
		GainFocus = function ( f31_arg0, f31_arg1 )
			f31_arg0:__resetProperties()
			f31_arg0:setupElementClipCounter( 17 )
			local f31_local0 = function ( f32_arg0 )
				f31_arg0.FocusGlow2:beginAnimation( 150 )
				f31_arg0.FocusGlow2:setAlpha( 0.5 )
				f31_arg0.FocusGlow2:registerEventHandler( "interrupted_keyframe", f31_arg0.clipInterrupted )
				f31_arg0.FocusGlow2:registerEventHandler( "transition_complete_keyframe", f31_arg0.clipFinished )
			end
			
			f31_arg0.FocusGlow2:completeAnimation()
			f31_arg0.FocusGlow2:setAlpha( 0 )
			f31_local0( f31_arg0.FocusGlow2 )
			local f31_local1 = function ( f33_arg0 )
				f31_arg0.PrestigeBreadcrumb:beginAnimation( 150 )
				f31_arg0.PrestigeBreadcrumb:setAlpha( 0.9 )
				f31_arg0.PrestigeBreadcrumb:registerEventHandler( "interrupted_keyframe", f31_arg0.clipInterrupted )
				f31_arg0.PrestigeBreadcrumb:registerEventHandler( "transition_complete_keyframe", f31_arg0.clipFinished )
			end
			
			f31_arg0.PrestigeBreadcrumb:completeAnimation()
			f31_arg0.PrestigeBreadcrumb:setRGB( ColorSet.PlayerCount.r, ColorSet.PlayerCount.g, ColorSet.PlayerCount.b )
			f31_arg0.PrestigeBreadcrumb:setAlpha( 0.5 )
			f31_local1( f31_arg0.PrestigeBreadcrumb )
			local f31_local2 = function ( f34_arg0 )
				f31_arg0.CommonCornerPips2:beginAnimation( 150 )
				f31_arg0.CommonCornerPips2:registerEventHandler( "interrupted_keyframe", f31_arg0.clipInterrupted )
				f31_arg0.CommonCornerPips2:registerEventHandler( "transition_complete_keyframe", f31_arg0.clipFinished )
			end
			
			f31_arg0.CommonCornerPips2:completeAnimation()
			f31_arg0.CommonCornerPips2:setAlpha( 0.2 )
			f31_local2( f31_arg0.CommonCornerPips2 )
			f31_arg0.TiledDotBgAdd:completeAnimation()
			f31_arg0.TiledDotBgAdd:setAlpha( 1 )
			f31_arg0.clipFinished( f31_arg0.TiledDotBgAdd )
			f31_arg0.ButtonFrame:completeAnimation()
			f31_arg0.ButtonFrame:setAlpha( 1 )
			f31_arg0.clipFinished( f31_arg0.ButtonFrame )
			f31_arg0.CallingCardsFrameWidget:completeAnimation()
			f31_arg0.CallingCardsFrameWidget:setAlpha( 1 )
			f31_arg0.clipFinished( f31_arg0.CallingCardsFrameWidget )
			f31_arg0.PrestigeRewardIcon:completeAnimation()
			f31_arg0.PrestigeRewardIcon:setLeftRight( 0, 0, 336, 384 )
			f31_arg0.clipFinished( f31_arg0.PrestigeRewardIcon )
			f31_arg0.PrestigeIcon:completeAnimation()
			f31_arg0.PrestigeIcon:setLeftRight( 0, 0, 15, 63 )
			f31_arg0.clipFinished( f31_arg0.PrestigeIcon )
			f31_arg0.TextBox1:completeAnimation()
			f31_arg0.TextBox1:setLeftRight( 0, 0, 100, 300 )
			f31_arg0.TextBox1:setTopBottom( 0, 0, 8, 23 )
			f31_arg0.TextBox1:setAlignment( Enum.LUIAlignment[0xFEEB12BCB0D7041] )
			f31_arg0.clipFinished( f31_arg0.TextBox1 )
			local f31_local3 = function ( f35_arg0 )
				f31_arg0.TextBox2:beginAnimation( 150 )
				f31_arg0.TextBox2:setRGB( ColorSet.T8__BIEGE.r, ColorSet.T8__BIEGE.g, ColorSet.T8__BIEGE.b )
				f31_arg0.TextBox2:registerEventHandler( "interrupted_keyframe", f31_arg0.clipInterrupted )
				f31_arg0.TextBox2:registerEventHandler( "transition_complete_keyframe", f31_arg0.clipFinished )
			end
			
			f31_arg0.TextBox2:completeAnimation()
			f31_arg0.TextBox2:setRGB( 0.92, 0.92, 0.92 )
			f31_arg0.TextBox2:setAlpha( 1 )
			f31_arg0.TextBox2:setAlignment( Enum.LUIAlignment[0xFEEB12BCB0D7041] )
			f31_local3( f31_arg0.TextBox2 )
			f31_arg0.TextBox2Alternate:completeAnimation()
			f31_arg0.TextBox2Alternate:setAlpha( 0 )
			f31_arg0.clipFinished( f31_arg0.TextBox2Alternate )
			f31_arg0.LevelProgressText:completeAnimation()
			f31_arg0.LevelProgressText:setAlpha( 0 )
			f31_arg0.clipFinished( f31_arg0.LevelProgressText )
			f31_arg0.NextPrestigeText:completeAnimation()
			f31_arg0.NextPrestigeText:setAlpha( 0 )
			f31_arg0.clipFinished( f31_arg0.NextPrestigeText )
			f31_arg0.BarBG:completeAnimation()
			f31_arg0.BarBG:setAlpha( 0 )
			f31_arg0.clipFinished( f31_arg0.BarBG )
			f31_arg0.PrestigeProgressCenterBar:completeAnimation()
			f31_arg0.PrestigeProgressCenterBar:setAlpha( 0 )
			f31_arg0.clipFinished( f31_arg0.PrestigeProgressCenterBar )
			f31_arg0.PrestigeProgressBar:completeAnimation()
			f31_arg0.PrestigeProgressBar:setAlpha( 0 )
			f31_arg0.clipFinished( f31_arg0.PrestigeProgressBar )
			local f31_local4 = function ( f36_arg0 )
				f31_arg0.FrontendFrameSelected:beginAnimation( 150 )
				f31_arg0.FrontendFrameSelected:setAlpha( 1 )
				f31_arg0.FrontendFrameSelected:registerEventHandler( "interrupted_keyframe", f31_arg0.clipInterrupted )
				f31_arg0.FrontendFrameSelected:registerEventHandler( "transition_complete_keyframe", f31_arg0.clipFinished )
			end
			
			f31_arg0.FrontendFrameSelected:completeAnimation()
			f31_arg0.FrontendFrameSelected:setAlpha( 0 )
			f31_local4( f31_arg0.FrontendFrameSelected )
		end,
		LoseFocus = function ( f37_arg0, f37_arg1 )
			f37_arg0:__resetProperties()
			f37_arg0:setupElementClipCounter( 17 )
			local f37_local0 = function ( f38_arg0 )
				f37_arg0.FocusGlow2:beginAnimation( 100 )
				f37_arg0.FocusGlow2:setAlpha( 0 )
				f37_arg0.FocusGlow2:registerEventHandler( "interrupted_keyframe", f37_arg0.clipInterrupted )
				f37_arg0.FocusGlow2:registerEventHandler( "transition_complete_keyframe", f37_arg0.clipFinished )
			end
			
			f37_arg0.FocusGlow2:completeAnimation()
			f37_arg0.FocusGlow2:setAlpha( 0.5 )
			f37_local0( f37_arg0.FocusGlow2 )
			local f37_local1 = function ( f39_arg0 )
				f37_arg0.PrestigeBreadcrumb:beginAnimation( 100 )
				f37_arg0.PrestigeBreadcrumb:setAlpha( 0.5 )
				f37_arg0.PrestigeBreadcrumb:registerEventHandler( "interrupted_keyframe", f37_arg0.clipInterrupted )
				f37_arg0.PrestigeBreadcrumb:registerEventHandler( "transition_complete_keyframe", f37_arg0.clipFinished )
			end
			
			f37_arg0.PrestigeBreadcrumb:completeAnimation()
			f37_arg0.PrestigeBreadcrumb:setRGB( ColorSet.PlayerCount.r, ColorSet.PlayerCount.g, ColorSet.PlayerCount.b )
			f37_arg0.PrestigeBreadcrumb:setAlpha( 0.9 )
			f37_local1( f37_arg0.PrestigeBreadcrumb )
			local f37_local2 = function ( f40_arg0 )
				f37_arg0.CommonCornerPips2:beginAnimation( 100 )
				f37_arg0.CommonCornerPips2:registerEventHandler( "interrupted_keyframe", f37_arg0.clipInterrupted )
				f37_arg0.CommonCornerPips2:registerEventHandler( "transition_complete_keyframe", f37_arg0.clipFinished )
			end
			
			f37_arg0.CommonCornerPips2:completeAnimation()
			f37_arg0.CommonCornerPips2:setAlpha( 0.2 )
			f37_local2( f37_arg0.CommonCornerPips2 )
			f37_arg0.TiledDotBgAdd:completeAnimation()
			f37_arg0.TiledDotBgAdd:setAlpha( 1 )
			f37_arg0.clipFinished( f37_arg0.TiledDotBgAdd )
			f37_arg0.ButtonFrame:completeAnimation()
			f37_arg0.ButtonFrame:setAlpha( 1 )
			f37_arg0.clipFinished( f37_arg0.ButtonFrame )
			f37_arg0.CallingCardsFrameWidget:completeAnimation()
			f37_arg0.CallingCardsFrameWidget:setAlpha( 1 )
			f37_arg0.clipFinished( f37_arg0.CallingCardsFrameWidget )
			f37_arg0.PrestigeRewardIcon:completeAnimation()
			f37_arg0.PrestigeRewardIcon:setLeftRight( 0, 0, 336, 384 )
			f37_arg0.clipFinished( f37_arg0.PrestigeRewardIcon )
			f37_arg0.PrestigeIcon:completeAnimation()
			f37_arg0.PrestigeIcon:setLeftRight( 0, 0, 15, 63 )
			f37_arg0.clipFinished( f37_arg0.PrestigeIcon )
			f37_arg0.TextBox1:completeAnimation()
			f37_arg0.TextBox1:setLeftRight( 0, 0, 100, 300 )
			f37_arg0.TextBox1:setTopBottom( 0, 0, 8, 23 )
			f37_arg0.TextBox1:setAlignment( Enum.LUIAlignment[0xFEEB12BCB0D7041] )
			f37_arg0.clipFinished( f37_arg0.TextBox1 )
			local f37_local3 = function ( f41_arg0 )
				f37_arg0.TextBox2:beginAnimation( 100 )
				f37_arg0.TextBox2:setRGB( 0.92, 0.92, 0.92 )
				f37_arg0.TextBox2:registerEventHandler( "interrupted_keyframe", f37_arg0.clipInterrupted )
				f37_arg0.TextBox2:registerEventHandler( "transition_complete_keyframe", f37_arg0.clipFinished )
			end
			
			f37_arg0.TextBox2:completeAnimation()
			f37_arg0.TextBox2:setRGB( ColorSet.T8__BIEGE.r, ColorSet.T8__BIEGE.g, ColorSet.T8__BIEGE.b )
			f37_arg0.TextBox2:setAlpha( 1 )
			f37_arg0.TextBox2:setAlignment( Enum.LUIAlignment[0xFEEB12BCB0D7041] )
			f37_local3( f37_arg0.TextBox2 )
			f37_arg0.TextBox2Alternate:completeAnimation()
			f37_arg0.TextBox2Alternate:setAlpha( 0 )
			f37_arg0.clipFinished( f37_arg0.TextBox2Alternate )
			f37_arg0.LevelProgressText:completeAnimation()
			f37_arg0.LevelProgressText:setAlpha( 0 )
			f37_arg0.clipFinished( f37_arg0.LevelProgressText )
			f37_arg0.NextPrestigeText:completeAnimation()
			f37_arg0.NextPrestigeText:setAlpha( 0 )
			f37_arg0.clipFinished( f37_arg0.NextPrestigeText )
			f37_arg0.BarBG:completeAnimation()
			f37_arg0.BarBG:setAlpha( 0 )
			f37_arg0.clipFinished( f37_arg0.BarBG )
			f37_arg0.PrestigeProgressCenterBar:completeAnimation()
			f37_arg0.PrestigeProgressCenterBar:setAlpha( 0 )
			f37_arg0.clipFinished( f37_arg0.PrestigeProgressCenterBar )
			f37_arg0.PrestigeProgressBar:completeAnimation()
			f37_arg0.PrestigeProgressBar:setAlpha( 0 )
			f37_arg0.clipFinished( f37_arg0.PrestigeProgressBar )
			local f37_local4 = function ( f42_arg0 )
				f37_arg0.FrontendFrameSelected:beginAnimation( 100 )
				f37_arg0.FrontendFrameSelected:setAlpha( 0 )
				f37_arg0.FrontendFrameSelected:registerEventHandler( "interrupted_keyframe", f37_arg0.clipInterrupted )
				f37_arg0.FrontendFrameSelected:registerEventHandler( "transition_complete_keyframe", f37_arg0.clipFinished )
			end
			
			f37_arg0.FrontendFrameSelected:completeAnimation()
			f37_arg0.FrontendFrameSelected:setAlpha( 1 )
			f37_local4( f37_arg0.FrontendFrameSelected )
		end
	},
	PrestigeReadyWZ = {
		DefaultClip = function ( f43_arg0, f43_arg1 )
			f43_arg0:__resetProperties()
			f43_arg0:setupElementClipCounter( 16 )
			f43_arg0.FocusGlow2:completeAnimation()
			f43_arg0.FocusGlow2:setAlpha( 0 )
			f43_arg0.clipFinished( f43_arg0.FocusGlow2 )
			f43_arg0.PrestigeBreadcrumb:completeAnimation()
			f43_arg0.PrestigeBreadcrumb:setRGB( ColorSet.PlayerCount.r, ColorSet.PlayerCount.g, ColorSet.PlayerCount.b )
			f43_arg0.PrestigeBreadcrumb:setAlpha( 0.5 )
			f43_arg0.clipFinished( f43_arg0.PrestigeBreadcrumb )
			f43_arg0.CommonCornerPips2:completeAnimation()
			f43_arg0.CommonCornerPips2:setAlpha( 0.2 )
			f43_arg0.clipFinished( f43_arg0.CommonCornerPips2 )
			f43_arg0.TiledDotBgAdd:completeAnimation()
			f43_arg0.TiledDotBgAdd:setAlpha( 1 )
			f43_arg0.clipFinished( f43_arg0.TiledDotBgAdd )
			f43_arg0.ButtonFrame:completeAnimation()
			f43_arg0.ButtonFrame:setAlpha( 1 )
			f43_arg0.clipFinished( f43_arg0.ButtonFrame )
			f43_arg0.CallingCardsFrameWidget:completeAnimation()
			f43_arg0.CallingCardsFrameWidget:setAlpha( 1 )
			f43_arg0.clipFinished( f43_arg0.CallingCardsFrameWidget )
			f43_arg0.PrestigeRewardIcon:completeAnimation()
			f43_arg0.PrestigeRewardIcon:setLeftRight( 0, 0, 336, 384 )
			f43_arg0.PrestigeRewardIcon:setAlpha( 0 )
			f43_arg0.clipFinished( f43_arg0.PrestigeRewardIcon )
			f43_arg0.PrestigeIcon:completeAnimation()
			f43_arg0.PrestigeIcon:setLeftRight( 0, 0, 15, 63 )
			f43_arg0.clipFinished( f43_arg0.PrestigeIcon )
			f43_arg0.TextBox1:completeAnimation()
			f43_arg0.TextBox1:setLeftRight( 0, 0, 100, 300 )
			f43_arg0.TextBox1:setTopBottom( 0, 0, 8, 23 )
			f43_arg0.TextBox1:setAlignment( Enum.LUIAlignment[0xFEEB12BCB0D7041] )
			f43_arg0.clipFinished( f43_arg0.TextBox1 )
			f43_arg0.TextBox2:completeAnimation()
			f43_arg0.TextBox2:setRGB( 0.92, 0.92, 0.92 )
			f43_arg0.TextBox2:setAlpha( 1 )
			f43_arg0.clipFinished( f43_arg0.TextBox2 )
			f43_arg0.TextBox2Alternate:completeAnimation()
			f43_arg0.TextBox2Alternate:setAlpha( 0 )
			f43_arg0.clipFinished( f43_arg0.TextBox2Alternate )
			f43_arg0.LevelProgressText:completeAnimation()
			f43_arg0.LevelProgressText:setAlpha( 0 )
			f43_arg0.clipFinished( f43_arg0.LevelProgressText )
			f43_arg0.NextPrestigeText:completeAnimation()
			f43_arg0.NextPrestigeText:setAlpha( 0 )
			f43_arg0.clipFinished( f43_arg0.NextPrestigeText )
			f43_arg0.BarBG:completeAnimation()
			f43_arg0.BarBG:setAlpha( 0 )
			f43_arg0.clipFinished( f43_arg0.BarBG )
			f43_arg0.PrestigeProgressCenterBar:completeAnimation()
			f43_arg0.PrestigeProgressCenterBar:setAlpha( 0 )
			f43_arg0.clipFinished( f43_arg0.PrestigeProgressCenterBar )
			f43_arg0.PrestigeProgressBar:completeAnimation()
			f43_arg0.PrestigeProgressBar:setAlpha( 0 )
			f43_arg0.clipFinished( f43_arg0.PrestigeProgressBar )
		end,
		Focus = function ( f44_arg0, f44_arg1 )
			f44_arg0:__resetProperties()
			f44_arg0:setupElementClipCounter( 17 )
			f44_arg0.FocusGlow2:completeAnimation()
			f44_arg0.FocusGlow2:setAlpha( 0.5 )
			f44_arg0.clipFinished( f44_arg0.FocusGlow2 )
			f44_arg0.PrestigeBreadcrumb:completeAnimation()
			f44_arg0.PrestigeBreadcrumb:setAlpha( 0.9 )
			f44_arg0.clipFinished( f44_arg0.PrestigeBreadcrumb )
			f44_arg0.CommonCornerPips2:completeAnimation()
			f44_arg0.CommonCornerPips2:setAlpha( 0.2 )
			f44_arg0.clipFinished( f44_arg0.CommonCornerPips2 )
			f44_arg0.TiledDotBgAdd:completeAnimation()
			f44_arg0.TiledDotBgAdd:setAlpha( 1 )
			f44_arg0.clipFinished( f44_arg0.TiledDotBgAdd )
			f44_arg0.ButtonFrame:completeAnimation()
			f44_arg0.ButtonFrame:setAlpha( 1 )
			f44_arg0.clipFinished( f44_arg0.ButtonFrame )
			f44_arg0.CallingCardsFrameWidget:completeAnimation()
			f44_arg0.CallingCardsFrameWidget:setAlpha( 1 )
			f44_arg0.clipFinished( f44_arg0.CallingCardsFrameWidget )
			f44_arg0.PrestigeRewardIcon:completeAnimation()
			f44_arg0.PrestigeRewardIcon:setLeftRight( 0, 0, 336, 384 )
			f44_arg0.PrestigeRewardIcon:setAlpha( 0 )
			f44_arg0.clipFinished( f44_arg0.PrestigeRewardIcon )
			f44_arg0.PrestigeIcon:completeAnimation()
			f44_arg0.PrestigeIcon:setLeftRight( 0, 0, 15, 63 )
			f44_arg0.clipFinished( f44_arg0.PrestigeIcon )
			f44_arg0.TextBox1:completeAnimation()
			f44_arg0.TextBox1:setLeftRight( 0, 0, 100, 300 )
			f44_arg0.TextBox1:setTopBottom( 0, 0, 8, 23 )
			f44_arg0.TextBox1:setAlignment( Enum.LUIAlignment[0xFEEB12BCB0D7041] )
			f44_arg0.clipFinished( f44_arg0.TextBox1 )
			f44_arg0.TextBox2:completeAnimation()
			f44_arg0.TextBox2:setRGB( ColorSet.T8__BIEGE.r, ColorSet.T8__BIEGE.g, ColorSet.T8__BIEGE.b )
			f44_arg0.TextBox2:setAlpha( 1 )
			f44_arg0.TextBox2:setAlignment( Enum.LUIAlignment[0xFEEB12BCB0D7041] )
			f44_arg0.clipFinished( f44_arg0.TextBox2 )
			f44_arg0.TextBox2Alternate:completeAnimation()
			f44_arg0.TextBox2Alternate:setAlpha( 0 )
			f44_arg0.clipFinished( f44_arg0.TextBox2Alternate )
			f44_arg0.LevelProgressText:completeAnimation()
			f44_arg0.LevelProgressText:setAlpha( 0 )
			f44_arg0.clipFinished( f44_arg0.LevelProgressText )
			f44_arg0.NextPrestigeText:completeAnimation()
			f44_arg0.NextPrestigeText:setAlpha( 0 )
			f44_arg0.clipFinished( f44_arg0.NextPrestigeText )
			f44_arg0.BarBG:completeAnimation()
			f44_arg0.BarBG:setAlpha( 0 )
			f44_arg0.clipFinished( f44_arg0.BarBG )
			f44_arg0.PrestigeProgressCenterBar:completeAnimation()
			f44_arg0.PrestigeProgressCenterBar:setAlpha( 0 )
			f44_arg0.clipFinished( f44_arg0.PrestigeProgressCenterBar )
			f44_arg0.PrestigeProgressBar:completeAnimation()
			f44_arg0.PrestigeProgressBar:setAlpha( 0 )
			f44_arg0.clipFinished( f44_arg0.PrestigeProgressBar )
			f44_arg0.FrontendFrameSelected:completeAnimation()
			f44_arg0.FrontendFrameSelected:setAlpha( 1 )
			f44_arg0.clipFinished( f44_arg0.FrontendFrameSelected )
		end,
		Intro = function ( f45_arg0, f45_arg1 )
			f45_arg0:__resetProperties()
			f45_arg0:setupElementClipCounter( 15 )
			f45_arg0.FocusGlow2:completeAnimation()
			f45_arg0.FocusGlow2:setAlpha( 0 )
			f45_arg0.clipFinished( f45_arg0.FocusGlow2 )
			local f45_local0 = function ( f46_arg0 )
				local f46_local0 = function ( f47_arg0 )
					local f47_local0 = function ( f48_arg0 )
						f48_arg0:beginAnimation( 900 )
						f48_arg0:setAlpha( 0.5 )
						f48_arg0:registerEventHandler( "transition_complete_keyframe", f45_arg0.clipFinished )
					end
					
					f47_arg0:beginAnimation( 300, Enum[0xF50FFF429AB1890][0x5193EA7825DC097] )
					f47_arg0:setAlpha( 0 )
					f47_arg0:registerEventHandler( "transition_complete_keyframe", f47_local0 )
				end
				
				f45_arg0.PrestigeBreadcrumb:beginAnimation( 300, Enum[0xF50FFF429AB1890][0x5193EA7825DC097] )
				f45_arg0.PrestigeBreadcrumb:setAlpha( 1 )
				f45_arg0.PrestigeBreadcrumb:registerEventHandler( "interrupted_keyframe", f45_arg0.clipInterrupted )
				f45_arg0.PrestigeBreadcrumb:registerEventHandler( "transition_complete_keyframe", f46_local0 )
			end
			
			f45_arg0.PrestigeBreadcrumb:completeAnimation()
			f45_arg0.PrestigeBreadcrumb:setAlpha( 0 )
			f45_local0( f45_arg0.PrestigeBreadcrumb )
			local f45_local1 = function ( f49_arg0 )
				local f49_local0 = function ( f50_arg0 )
					f50_arg0:beginAnimation( 900 )
					f50_arg0:setAlpha( 1 )
					f50_arg0:registerEventHandler( "transition_complete_keyframe", f45_arg0.clipFinished )
				end
				
				f45_arg0.ButtonFrame:beginAnimation( 600 )
				f45_arg0.ButtonFrame:registerEventHandler( "interrupted_keyframe", f45_arg0.clipInterrupted )
				f45_arg0.ButtonFrame:registerEventHandler( "transition_complete_keyframe", f49_local0 )
			end
			
			f45_arg0.ButtonFrame:completeAnimation()
			f45_arg0.ButtonFrame:setAlpha( 0 )
			f45_local1( f45_arg0.ButtonFrame )
			local f45_local2 = function ( f51_arg0 )
				f45_arg0.CallingCardsFrameWidget:beginAnimation( 300 )
				f45_arg0.CallingCardsFrameWidget:setAlpha( 1 )
				f45_arg0.CallingCardsFrameWidget:registerEventHandler( "interrupted_keyframe", f45_arg0.clipInterrupted )
				f45_arg0.CallingCardsFrameWidget:registerEventHandler( "transition_complete_keyframe", f45_arg0.clipFinished )
			end
			
			f45_arg0.CallingCardsFrameWidget:completeAnimation()
			f45_arg0.CallingCardsFrameWidget:setAlpha( 0 )
			f45_local2( f45_arg0.CallingCardsFrameWidget )
			f45_arg0.PrestigeRewardIcon:completeAnimation()
			f45_arg0.PrestigeRewardIcon:setLeftRight( 0, 0, 336, 384 )
			f45_arg0.PrestigeRewardIcon:setAlpha( 0 )
			f45_arg0.clipFinished( f45_arg0.PrestigeRewardIcon )
			local f45_local3 = function ( f52_arg0 )
				f45_arg0.PrestigeIcon:beginAnimation( 300 )
				f45_arg0.PrestigeIcon:setAlpha( 1 )
				f45_arg0.PrestigeIcon:registerEventHandler( "interrupted_keyframe", f45_arg0.clipInterrupted )
				f45_arg0.PrestigeIcon:registerEventHandler( "transition_complete_keyframe", f45_arg0.clipFinished )
			end
			
			f45_arg0.PrestigeIcon:completeAnimation()
			f45_arg0.PrestigeIcon:setLeftRight( 0, 0, 15, 63 )
			f45_arg0.PrestigeIcon:setAlpha( 0 )
			f45_local3( f45_arg0.PrestigeIcon )
			local f45_local4 = function ( f53_arg0 )
				f45_arg0.TextBox1:beginAnimation( 300 )
				f45_arg0.TextBox1:setAlpha( 1 )
				f45_arg0.TextBox1:registerEventHandler( "interrupted_keyframe", f45_arg0.clipInterrupted )
				f45_arg0.TextBox1:registerEventHandler( "transition_complete_keyframe", f45_arg0.clipFinished )
			end
			
			f45_arg0.TextBox1:completeAnimation()
			f45_arg0.TextBox1:setLeftRight( 0, 0, 100, 300 )
			f45_arg0.TextBox1:setTopBottom( 0, 0, 8, 23 )
			f45_arg0.TextBox1:setAlpha( 0 )
			f45_arg0.TextBox1:setAlignment( Enum.LUIAlignment[0xFEEB12BCB0D7041] )
			f45_local4( f45_arg0.TextBox1 )
			local f45_local5 = function ( f54_arg0 )
				local f54_local0 = function ( f55_arg0 )
					f55_arg0:beginAnimation( 600 )
					f55_arg0:setAlpha( 1 )
					f55_arg0:registerEventHandler( "transition_complete_keyframe", f45_arg0.clipFinished )
				end
				
				f45_arg0.TextBox2:beginAnimation( 600 )
				f45_arg0.TextBox2:registerEventHandler( "interrupted_keyframe", f45_arg0.clipInterrupted )
				f45_arg0.TextBox2:registerEventHandler( "transition_complete_keyframe", f54_local0 )
			end
			
			f45_arg0.TextBox2:completeAnimation()
			f45_arg0.TextBox2:setRGB( 0.92, 0.92, 0.92 )
			f45_arg0.TextBox2:setAlpha( 0 )
			f45_local5( f45_arg0.TextBox2 )
			f45_arg0.TextBox2Alternate:completeAnimation()
			f45_arg0.TextBox2Alternate:setAlpha( 0 )
			f45_arg0.clipFinished( f45_arg0.TextBox2Alternate )
			f45_arg0.LevelProgressText:completeAnimation()
			f45_arg0.LevelProgressText:setAlpha( 0 )
			f45_arg0.clipFinished( f45_arg0.LevelProgressText )
			f45_arg0.NextPrestigeText:completeAnimation()
			f45_arg0.NextPrestigeText:setAlpha( 0 )
			f45_arg0.clipFinished( f45_arg0.NextPrestigeText )
			f45_arg0.BarBG:completeAnimation()
			f45_arg0.BarBG:setAlpha( 0 )
			f45_arg0.clipFinished( f45_arg0.BarBG )
			f45_arg0.PrestigeProgressCenterBar:completeAnimation()
			f45_arg0.PrestigeProgressCenterBar:setAlpha( 0 )
			f45_arg0.clipFinished( f45_arg0.PrestigeProgressCenterBar )
			f45_arg0.PrestigeProgressBar:completeAnimation()
			f45_arg0.PrestigeProgressBar:setAlpha( 0 )
			f45_arg0.clipFinished( f45_arg0.PrestigeProgressBar )
			local f45_local6 = function ( f56_arg0 )
				local f56_local0 = function ( f57_arg0 )
					f57_arg0:beginAnimation( 300 )
					f57_arg0:setAlpha( 0 )
					f57_arg0:registerEventHandler( "transition_complete_keyframe", f45_arg0.clipFinished )
				end
				
				f45_arg0.FrontendFrameSelected:beginAnimation( 300 )
				f45_arg0.FrontendFrameSelected:setAlpha( 1 )
				f45_arg0.FrontendFrameSelected:registerEventHandler( "interrupted_keyframe", f45_arg0.clipInterrupted )
				f45_arg0.FrontendFrameSelected:registerEventHandler( "transition_complete_keyframe", f56_local0 )
			end
			
			f45_arg0.FrontendFrameSelected:completeAnimation()
			f45_arg0.FrontendFrameSelected:setAlpha( 0 )
			f45_local6( f45_arg0.FrontendFrameSelected )
		end,
		GainFocus = function ( f58_arg0, f58_arg1 )
			f58_arg0:__resetProperties()
			f58_arg0:setupElementClipCounter( 17 )
			local f58_local0 = function ( f59_arg0 )
				f58_arg0.FocusGlow2:beginAnimation( 150 )
				f58_arg0.FocusGlow2:setAlpha( 0.5 )
				f58_arg0.FocusGlow2:registerEventHandler( "interrupted_keyframe", f58_arg0.clipInterrupted )
				f58_arg0.FocusGlow2:registerEventHandler( "transition_complete_keyframe", f58_arg0.clipFinished )
			end
			
			f58_arg0.FocusGlow2:completeAnimation()
			f58_arg0.FocusGlow2:setAlpha( 0 )
			f58_local0( f58_arg0.FocusGlow2 )
			local f58_local1 = function ( f60_arg0 )
				f58_arg0.PrestigeBreadcrumb:beginAnimation( 150 )
				f58_arg0.PrestigeBreadcrumb:setAlpha( 0.9 )
				f58_arg0.PrestigeBreadcrumb:registerEventHandler( "interrupted_keyframe", f58_arg0.clipInterrupted )
				f58_arg0.PrestigeBreadcrumb:registerEventHandler( "transition_complete_keyframe", f58_arg0.clipFinished )
			end
			
			f58_arg0.PrestigeBreadcrumb:completeAnimation()
			f58_arg0.PrestigeBreadcrumb:setRGB( ColorSet.PlayerCount.r, ColorSet.PlayerCount.g, ColorSet.PlayerCount.b )
			f58_arg0.PrestigeBreadcrumb:setAlpha( 0.5 )
			f58_local1( f58_arg0.PrestigeBreadcrumb )
			local f58_local2 = function ( f61_arg0 )
				f58_arg0.CommonCornerPips2:beginAnimation( 150 )
				f58_arg0.CommonCornerPips2:registerEventHandler( "interrupted_keyframe", f58_arg0.clipInterrupted )
				f58_arg0.CommonCornerPips2:registerEventHandler( "transition_complete_keyframe", f58_arg0.clipFinished )
			end
			
			f58_arg0.CommonCornerPips2:completeAnimation()
			f58_arg0.CommonCornerPips2:setAlpha( 0.2 )
			f58_local2( f58_arg0.CommonCornerPips2 )
			f58_arg0.TiledDotBgAdd:completeAnimation()
			f58_arg0.TiledDotBgAdd:setAlpha( 1 )
			f58_arg0.clipFinished( f58_arg0.TiledDotBgAdd )
			f58_arg0.ButtonFrame:completeAnimation()
			f58_arg0.ButtonFrame:setAlpha( 1 )
			f58_arg0.clipFinished( f58_arg0.ButtonFrame )
			f58_arg0.CallingCardsFrameWidget:completeAnimation()
			f58_arg0.CallingCardsFrameWidget:setAlpha( 1 )
			f58_arg0.clipFinished( f58_arg0.CallingCardsFrameWidget )
			local f58_local3 = function ( f62_arg0 )
				f58_arg0.PrestigeRewardIcon:beginAnimation( 10 )
				f58_arg0.PrestigeRewardIcon:registerEventHandler( "interrupted_keyframe", f58_arg0.clipInterrupted )
				f58_arg0.PrestigeRewardIcon:registerEventHandler( "transition_complete_keyframe", f58_arg0.clipFinished )
			end
			
			f58_arg0.PrestigeRewardIcon:completeAnimation()
			f58_arg0.PrestigeRewardIcon:setLeftRight( 0, 0, 336, 384 )
			f58_arg0.PrestigeRewardIcon:setAlpha( 0 )
			f58_local3( f58_arg0.PrestigeRewardIcon )
			f58_arg0.PrestigeIcon:completeAnimation()
			f58_arg0.PrestigeIcon:setLeftRight( 0, 0, 15, 63 )
			f58_arg0.clipFinished( f58_arg0.PrestigeIcon )
			f58_arg0.TextBox1:completeAnimation()
			f58_arg0.TextBox1:setLeftRight( 0, 0, 100, 300 )
			f58_arg0.TextBox1:setTopBottom( 0, 0, 8, 23 )
			f58_arg0.TextBox1:setAlignment( Enum.LUIAlignment[0xFEEB12BCB0D7041] )
			f58_arg0.clipFinished( f58_arg0.TextBox1 )
			local f58_local4 = function ( f63_arg0 )
				f58_arg0.TextBox2:beginAnimation( 150 )
				f58_arg0.TextBox2:setRGB( ColorSet.T8__BIEGE.r, ColorSet.T8__BIEGE.g, ColorSet.T8__BIEGE.b )
				f58_arg0.TextBox2:registerEventHandler( "interrupted_keyframe", f58_arg0.clipInterrupted )
				f58_arg0.TextBox2:registerEventHandler( "transition_complete_keyframe", f58_arg0.clipFinished )
			end
			
			f58_arg0.TextBox2:completeAnimation()
			f58_arg0.TextBox2:setRGB( 0.92, 0.92, 0.92 )
			f58_arg0.TextBox2:setAlpha( 1 )
			f58_arg0.TextBox2:setAlignment( Enum.LUIAlignment[0xFEEB12BCB0D7041] )
			f58_local4( f58_arg0.TextBox2 )
			f58_arg0.TextBox2Alternate:completeAnimation()
			f58_arg0.TextBox2Alternate:setAlpha( 0 )
			f58_arg0.clipFinished( f58_arg0.TextBox2Alternate )
			f58_arg0.LevelProgressText:completeAnimation()
			f58_arg0.LevelProgressText:setAlpha( 0 )
			f58_arg0.clipFinished( f58_arg0.LevelProgressText )
			f58_arg0.NextPrestigeText:completeAnimation()
			f58_arg0.NextPrestigeText:setAlpha( 0 )
			f58_arg0.clipFinished( f58_arg0.NextPrestigeText )
			f58_arg0.BarBG:completeAnimation()
			f58_arg0.BarBG:setAlpha( 0 )
			f58_arg0.clipFinished( f58_arg0.BarBG )
			f58_arg0.PrestigeProgressCenterBar:completeAnimation()
			f58_arg0.PrestigeProgressCenterBar:setAlpha( 0 )
			f58_arg0.clipFinished( f58_arg0.PrestigeProgressCenterBar )
			f58_arg0.PrestigeProgressBar:completeAnimation()
			f58_arg0.PrestigeProgressBar:setAlpha( 0 )
			f58_arg0.clipFinished( f58_arg0.PrestigeProgressBar )
			local f58_local5 = function ( f64_arg0 )
				f58_arg0.FrontendFrameSelected:beginAnimation( 150 )
				f58_arg0.FrontendFrameSelected:setAlpha( 1 )
				f58_arg0.FrontendFrameSelected:registerEventHandler( "interrupted_keyframe", f58_arg0.clipInterrupted )
				f58_arg0.FrontendFrameSelected:registerEventHandler( "transition_complete_keyframe", f58_arg0.clipFinished )
			end
			
			f58_arg0.FrontendFrameSelected:completeAnimation()
			f58_arg0.FrontendFrameSelected:setAlpha( 0 )
			f58_local5( f58_arg0.FrontendFrameSelected )
		end,
		LoseFocus = function ( f65_arg0, f65_arg1 )
			f65_arg0:__resetProperties()
			f65_arg0:setupElementClipCounter( 17 )
			local f65_local0 = function ( f66_arg0 )
				f65_arg0.FocusGlow2:beginAnimation( 100 )
				f65_arg0.FocusGlow2:setAlpha( 0 )
				f65_arg0.FocusGlow2:registerEventHandler( "interrupted_keyframe", f65_arg0.clipInterrupted )
				f65_arg0.FocusGlow2:registerEventHandler( "transition_complete_keyframe", f65_arg0.clipFinished )
			end
			
			f65_arg0.FocusGlow2:completeAnimation()
			f65_arg0.FocusGlow2:setAlpha( 0.5 )
			f65_local0( f65_arg0.FocusGlow2 )
			local f65_local1 = function ( f67_arg0 )
				f65_arg0.PrestigeBreadcrumb:beginAnimation( 100 )
				f65_arg0.PrestigeBreadcrumb:setAlpha( 0.5 )
				f65_arg0.PrestigeBreadcrumb:registerEventHandler( "interrupted_keyframe", f65_arg0.clipInterrupted )
				f65_arg0.PrestigeBreadcrumb:registerEventHandler( "transition_complete_keyframe", f65_arg0.clipFinished )
			end
			
			f65_arg0.PrestigeBreadcrumb:completeAnimation()
			f65_arg0.PrestigeBreadcrumb:setRGB( ColorSet.PlayerCount.r, ColorSet.PlayerCount.g, ColorSet.PlayerCount.b )
			f65_arg0.PrestigeBreadcrumb:setAlpha( 0.9 )
			f65_local1( f65_arg0.PrestigeBreadcrumb )
			local f65_local2 = function ( f68_arg0 )
				f65_arg0.CommonCornerPips2:beginAnimation( 100 )
				f65_arg0.CommonCornerPips2:registerEventHandler( "interrupted_keyframe", f65_arg0.clipInterrupted )
				f65_arg0.CommonCornerPips2:registerEventHandler( "transition_complete_keyframe", f65_arg0.clipFinished )
			end
			
			f65_arg0.CommonCornerPips2:completeAnimation()
			f65_arg0.CommonCornerPips2:setAlpha( 0.2 )
			f65_local2( f65_arg0.CommonCornerPips2 )
			f65_arg0.TiledDotBgAdd:completeAnimation()
			f65_arg0.TiledDotBgAdd:setAlpha( 1 )
			f65_arg0.clipFinished( f65_arg0.TiledDotBgAdd )
			f65_arg0.ButtonFrame:completeAnimation()
			f65_arg0.ButtonFrame:setAlpha( 1 )
			f65_arg0.clipFinished( f65_arg0.ButtonFrame )
			f65_arg0.CallingCardsFrameWidget:completeAnimation()
			f65_arg0.CallingCardsFrameWidget:setAlpha( 1 )
			f65_arg0.clipFinished( f65_arg0.CallingCardsFrameWidget )
			f65_arg0.PrestigeRewardIcon:completeAnimation()
			f65_arg0.PrestigeRewardIcon:setLeftRight( 0, 0, 336, 384 )
			f65_arg0.PrestigeRewardIcon:setAlpha( 0 )
			f65_arg0.clipFinished( f65_arg0.PrestigeRewardIcon )
			f65_arg0.PrestigeIcon:completeAnimation()
			f65_arg0.PrestigeIcon:setLeftRight( 0, 0, 15, 63 )
			f65_arg0.clipFinished( f65_arg0.PrestigeIcon )
			f65_arg0.TextBox1:completeAnimation()
			f65_arg0.TextBox1:setLeftRight( 0, 0, 100, 300 )
			f65_arg0.TextBox1:setTopBottom( 0, 0, 8, 23 )
			f65_arg0.TextBox1:setAlignment( Enum.LUIAlignment[0xFEEB12BCB0D7041] )
			f65_arg0.clipFinished( f65_arg0.TextBox1 )
			local f65_local3 = function ( f69_arg0 )
				f65_arg0.TextBox2:beginAnimation( 100 )
				f65_arg0.TextBox2:setRGB( 0.92, 0.92, 0.92 )
				f65_arg0.TextBox2:registerEventHandler( "interrupted_keyframe", f65_arg0.clipInterrupted )
				f65_arg0.TextBox2:registerEventHandler( "transition_complete_keyframe", f65_arg0.clipFinished )
			end
			
			f65_arg0.TextBox2:completeAnimation()
			f65_arg0.TextBox2:setRGB( ColorSet.T8__BIEGE.r, ColorSet.T8__BIEGE.g, ColorSet.T8__BIEGE.b )
			f65_arg0.TextBox2:setAlpha( 1 )
			f65_arg0.TextBox2:setAlignment( Enum.LUIAlignment[0xFEEB12BCB0D7041] )
			f65_local3( f65_arg0.TextBox2 )
			f65_arg0.TextBox2Alternate:completeAnimation()
			f65_arg0.TextBox2Alternate:setAlpha( 0 )
			f65_arg0.clipFinished( f65_arg0.TextBox2Alternate )
			f65_arg0.LevelProgressText:completeAnimation()
			f65_arg0.LevelProgressText:setAlpha( 0 )
			f65_arg0.clipFinished( f65_arg0.LevelProgressText )
			f65_arg0.NextPrestigeText:completeAnimation()
			f65_arg0.NextPrestigeText:setAlpha( 0 )
			f65_arg0.clipFinished( f65_arg0.NextPrestigeText )
			f65_arg0.BarBG:completeAnimation()
			f65_arg0.BarBG:setAlpha( 0 )
			f65_arg0.clipFinished( f65_arg0.BarBG )
			f65_arg0.PrestigeProgressCenterBar:completeAnimation()
			f65_arg0.PrestigeProgressCenterBar:setAlpha( 0 )
			f65_arg0.clipFinished( f65_arg0.PrestigeProgressCenterBar )
			f65_arg0.PrestigeProgressBar:completeAnimation()
			f65_arg0.PrestigeProgressBar:setAlpha( 0 )
			f65_arg0.clipFinished( f65_arg0.PrestigeProgressBar )
			local f65_local4 = function ( f70_arg0 )
				f65_arg0.FrontendFrameSelected:beginAnimation( 100 )
				f65_arg0.FrontendFrameSelected:setAlpha( 0 )
				f65_arg0.FrontendFrameSelected:registerEventHandler( "interrupted_keyframe", f65_arg0.clipInterrupted )
				f65_arg0.FrontendFrameSelected:registerEventHandler( "transition_complete_keyframe", f65_arg0.clipFinished )
			end
			
			f65_arg0.FrontendFrameSelected:completeAnimation()
			f65_arg0.FrontendFrameSelected:setAlpha( 1 )
			f65_local4( f65_arg0.FrontendFrameSelected )
		end
	},
	MasterPrestige = {
		DefaultClip = function ( f71_arg0, f71_arg1 )
			f71_arg0:__resetProperties()
			f71_arg0:setupElementClipCounter( 12 )
			f71_arg0.ButtonFrame:completeAnimation()
			f71_arg0.ButtonFrame:setAlpha( 0.2 )
			f71_arg0.clipFinished( f71_arg0.ButtonFrame )
			f71_arg0.CallingCardsFrameWidget:completeAnimation()
			f71_arg0.CallingCardsFrameWidget:setLeftRight( 0.5, 0.5, -197, 197 )
			f71_arg0.CallingCardsFrameWidget:setTopBottom( 0.5, 0.5, -45, 46 )
			f71_arg0.CallingCardsFrameWidget:setAlpha( 1 )
			f71_arg0.clipFinished( f71_arg0.CallingCardsFrameWidget )
			f71_arg0.PrestigeRewardIcon:completeAnimation()
			f71_arg0.PrestigeRewardIcon:setAlpha( 0 )
			f71_arg0.clipFinished( f71_arg0.PrestigeRewardIcon )
			f71_arg0.PrestigeIcon:completeAnimation()
			f71_arg0.PrestigeIcon:setAlpha( 0 )
			f71_arg0.clipFinished( f71_arg0.PrestigeIcon )
			f71_arg0.TextBox1:completeAnimation()
			f71_arg0.TextBox1:setAlpha( 0 )
			f71_arg0.clipFinished( f71_arg0.TextBox1 )
			f71_arg0.TextBox2:completeAnimation()
			f71_arg0.TextBox2:setAlpha( 0 )
			f71_arg0.clipFinished( f71_arg0.TextBox2 )
			f71_arg0.TextBox2Alternate:completeAnimation()
			f71_arg0.TextBox2Alternate:setAlpha( 0 )
			f71_arg0.clipFinished( f71_arg0.TextBox2Alternate )
			f71_arg0.LevelProgressText:completeAnimation()
			f71_arg0.LevelProgressText:setAlpha( 0 )
			f71_arg0.clipFinished( f71_arg0.LevelProgressText )
			f71_arg0.NextPrestigeText:completeAnimation()
			f71_arg0.NextPrestigeText:setAlpha( 0 )
			f71_arg0.clipFinished( f71_arg0.NextPrestigeText )
			f71_arg0.BarBG:completeAnimation()
			f71_arg0.BarBG:setAlpha( 0 )
			f71_arg0.clipFinished( f71_arg0.BarBG )
			f71_arg0.PrestigeProgressCenterBar:completeAnimation()
			f71_arg0.PrestigeProgressCenterBar:setAlpha( 0 )
			f71_arg0.clipFinished( f71_arg0.PrestigeProgressCenterBar )
			f71_arg0.PrestigeProgressBar:completeAnimation()
			f71_arg0.PrestigeProgressBar:setAlpha( 0 )
			f71_arg0.clipFinished( f71_arg0.PrestigeProgressBar )
		end
	}
}
CoD.Prestige_PrestigeButton_Internal.__onClose = function ( f72_arg0 )
	f72_arg0.CommonCornerPips2:close()
	f72_arg0.CallingCardsFrameWidget:close()
	f72_arg0.PrestigeIcon:close()
	f72_arg0.TextBox1:close()
	f72_arg0.TextBox2Alternate:close()
	f72_arg0.LevelProgressText:close()
	f72_arg0.NextPrestigeText:close()
	f72_arg0.BarBG:close()
	f72_arg0.PrestigeProgressBar:close()
end

