CoD.WarScoreInfo_StageNotification = InheritFrom( LUI.UIElement )
CoD.WarScoreInfo_StageNotification.__defaultWidth = 320
CoD.WarScoreInfo_StageNotification.__defaultHeight = 60
CoD.WarScoreInfo_StageNotification.new = function ( f1_arg0, f1_arg1, f1_arg2, f1_arg3, f1_arg4, f1_arg5, f1_arg6, f1_arg7, f1_arg8, f1_arg9 )
	local self = LUI.UIElement.new( f1_arg2, f1_arg3, f1_arg4, f1_arg5, f1_arg6, f1_arg7, f1_arg8, f1_arg9 )
	self:setClass( CoD.WarScoreInfo_StageNotification )
	self.id = "WarScoreInfo_StageNotification"
	self.soundSet = "default"
	self.onlyChildrenFocusable = true
	self.anyChildUsesUpdateState = true
	f1_arg0:addElementToPendingUpdateStateList( self )
	
	local CenterBacking = LUI.UIImage.new( 0, 0, -35, 253, 0, 0, 0, 60 )
	CenterBacking:setRGB( 0, 0, 0 )
	CenterBacking:setImage( RegisterImage( "uie_hud_common_core_score_centerbar" ) )
	CenterBacking:setMaterial( LUI.UIImage.GetCachedMaterial( "uie_wipe_delta_normal" ) )
	CenterBacking:setShaderVector( 0, 0.85, 1, 0, 0 )
	CenterBacking:setShaderVector( 1, 0, 0, 0, 0 )
	CenterBacking:setShaderVector( 2, 0, 1, 0, 0 )
	CenterBacking:setShaderVector( 3, 0, 0, 0, 0 )
	CenterBacking:setShaderVector( 4, 0, 0, 0, 0 )
	self:addElement( CenterBacking )
	self.CenterBacking = CenterBacking
	
	local ObjectiveProgressionFrame = LUI.UIFrame.new( f1_arg0, f1_arg1, 0, 0, false )
	ObjectiveProgressionFrame:setLeftRight( 0, 0, -90, 310 )
	ObjectiveProgressionFrame:setTopBottom( 0, 0, -18, 2 )
	self:addElement( ObjectiveProgressionFrame )
	self.ObjectiveProgressionFrame = ObjectiveProgressionFrame
	
	local FuelCellIcon = LUI.UIImage.new( 0, 0, 199, 259, 0, 0, -2, 58 )
	FuelCellIcon:setImage( RegisterImage( "uie_hud_common_core_score_waricon" ) )
	self:addElement( FuelCellIcon )
	self.FuelCellIcon = FuelCellIcon
	
	local ObjectiveTextBox = LUI.UIText.new( 0, 0, 0, 320, 0, 0, 16, 44 )
	ObjectiveTextBox:setText( "" )
	ObjectiveTextBox:setTTF( "default" )
	ObjectiveTextBox:setAlignment( Enum.LUIAlignment[0xFEEB12BCB0D7041] )
	ObjectiveTextBox:setAlignment( Enum.LUIAlignment[0xF41D595A2B0EDF3] )
	self:addElement( ObjectiveTextBox )
	self.ObjectiveTextBox = ObjectiveTextBox
	
	local ContestedText = LUI.UIText.new( 0, 0, 0, 320, 0, 0, 16, 44 )
	ContestedText:setAlpha( 0 )
	ContestedText:setText( Engine[0xF9F1239CFD921FE]( 0xE57B38B7A8EE82E ) )
	ContestedText:setTTF( "default" )
	ContestedText:setAlignment( Enum.LUIAlignment[0xFEEB12BCB0D7041] )
	ContestedText:setAlignment( Enum.LUIAlignment[0xF41D595A2B0EDF3] )
	self:addElement( ContestedText )
	self.ContestedText = ContestedText
	
	ObjectiveProgressionFrame.id = "ObjectiveProgressionFrame"
	LUI.OverrideFunction_CallOriginalSecond( self, "close", self.__onClose )
	
	if PostLoadFunc then
		PostLoadFunc( self, f1_arg1, f1_arg0 )
	end
	
	return self
end

CoD.WarScoreInfo_StageNotification.__resetProperties = function ( f2_arg0 )
	f2_arg0.CenterBacking:completeAnimation()
	f2_arg0.FuelCellIcon:completeAnimation()
	f2_arg0.ObjectiveTextBox:completeAnimation()
	f2_arg0.ObjectiveProgressionFrame:completeAnimation()
	f2_arg0.ContestedText:completeAnimation()
	f2_arg0.CenterBacking:setAlpha( 1 )
	f2_arg0.CenterBacking:setMaterial( LUI.UIImage.GetCachedMaterial( "uie_wipe_delta_normal" ) )
	f2_arg0.CenterBacking:setShaderVector( 0, 0.85, 1, 0, 0 )
	f2_arg0.CenterBacking:setShaderVector( 1, 0, 0, 0, 0 )
	f2_arg0.CenterBacking:setShaderVector( 2, 0, 1, 0, 0 )
	f2_arg0.CenterBacking:setShaderVector( 3, 0, 0, 0, 0 )
	f2_arg0.CenterBacking:setShaderVector( 4, 0, 0, 0, 0 )
	f2_arg0.FuelCellIcon:setLeftRight( 0, 0, 199, 259 )
	f2_arg0.FuelCellIcon:setTopBottom( 0, 0, -2, 58 )
	f2_arg0.FuelCellIcon:setAlpha( 1 )
	f2_arg0.ObjectiveTextBox:setLeftRight( 0, 0, 0, 320 )
	f2_arg0.ObjectiveTextBox:setTopBottom( 0, 0, 16, 44 )
	f2_arg0.ObjectiveTextBox:setAlpha( 1 )
	f2_arg0.ObjectiveProgressionFrame:setAlpha( 1 )
	f2_arg0.ContestedText:setLeftRight( 0, 0, 0, 320 )
	f2_arg0.ContestedText:setTopBottom( 0, 0, 16, 44 )
	f2_arg0.ContestedText:setAlpha( 0 )
	f2_arg0.ContestedText:setScale( 1, 1 )
end

CoD.WarScoreInfo_StageNotification.__clipsPerState = {
	DefaultState = {
		DefaultClip = function ( f3_arg0, f3_arg1 )
			f3_arg0:__resetProperties()
			f3_arg0:setupElementClipCounter( 3 )
			f3_arg0.CenterBacking:completeAnimation()
			f3_arg0.CenterBacking:setMaterial( LUI.UIImage.GetCachedMaterial( "uie_wipe_delta_normal" ) )
			f3_arg0.CenterBacking:setShaderVector( 0, 0, 1, 0, 0 )
			f3_arg0.CenterBacking:setShaderVector( 1, 0, 0, 0, 0 )
			f3_arg0.CenterBacking:setShaderVector( 2, 0, 1, 0, 0 )
			f3_arg0.CenterBacking:setShaderVector( 3, 0, 0, 0, 0 )
			f3_arg0.CenterBacking:setShaderVector( 4, 0, 0, 0, 0 )
			f3_arg0.clipFinished( f3_arg0.CenterBacking )
			f3_arg0.FuelCellIcon:completeAnimation()
			f3_arg0.FuelCellIcon:setLeftRight( 0, 0, -42, 18 )
			f3_arg0.FuelCellIcon:setTopBottom( 0, 0, -1, 59 )
			f3_arg0.clipFinished( f3_arg0.FuelCellIcon )
			f3_arg0.ObjectiveTextBox:completeAnimation()
			f3_arg0.ObjectiveTextBox:setLeftRight( 0, 0, -48, 272 )
			f3_arg0.ObjectiveTextBox:setTopBottom( 0, 0, 16, 44 )
			f3_arg0.clipFinished( f3_arg0.ObjectiveTextBox )
		end,
		CollapsedRight = function ( f4_arg0, f4_arg1 )
			f4_arg0:__resetProperties()
			f4_arg0:setupElementClipCounter( 4 )
			local f4_local0 = function ( f5_arg0 )
				f4_arg0.CenterBacking:beginAnimation( 450 )
				f4_arg0.CenterBacking:setShaderVector( 0, 0.85, 1, 0, 0 )
				f4_arg0.CenterBacking:registerEventHandler( "interrupted_keyframe", f4_arg0.clipInterrupted )
				f4_arg0.CenterBacking:registerEventHandler( "transition_complete_keyframe", f4_arg0.clipFinished )
			end
			
			f4_arg0.CenterBacking:completeAnimation()
			f4_arg0.CenterBacking:setAlpha( 1 )
			f4_arg0.CenterBacking:setMaterial( LUI.UIImage.GetCachedMaterial( "uie_wipe_delta_normal" ) )
			f4_arg0.CenterBacking:setShaderVector( 0, 0, 1, 0, 0 )
			f4_arg0.CenterBacking:setShaderVector( 1, 0, 0, 0, 0 )
			f4_arg0.CenterBacking:setShaderVector( 2, 0, 1, 0, 0 )
			f4_arg0.CenterBacking:setShaderVector( 3, 0, 0, 0, 0 )
			f4_arg0.CenterBacking:setShaderVector( 4, 0, 0, 0, 0 )
			f4_local0( f4_arg0.CenterBacking )
			local f4_local1 = function ( f6_arg0 )
				f4_arg0.ObjectiveProgressionFrame:beginAnimation( 450 )
				f4_arg0.ObjectiveProgressionFrame:setAlpha( 0 )
				f4_arg0.ObjectiveProgressionFrame:registerEventHandler( "interrupted_keyframe", f4_arg0.clipInterrupted )
				f4_arg0.ObjectiveProgressionFrame:registerEventHandler( "transition_complete_keyframe", function ( element, event )
					f4_arg0.clipFinished( element, event )
				end )
			end
			
			f4_arg0.ObjectiveProgressionFrame:completeAnimation()
			f4_arg0.ObjectiveProgressionFrame:setAlpha( 1 )
			f4_local1( f4_arg0.ObjectiveProgressionFrame )
			local f4_local2 = function ( f8_arg0 )
				f4_arg0.FuelCellIcon:beginAnimation( 450 )
				f4_arg0.FuelCellIcon:setLeftRight( 0, 0, 199, 259 )
				f4_arg0.FuelCellIcon:setAlpha( 0.2 )
				f4_arg0.FuelCellIcon:registerEventHandler( "interrupted_keyframe", f4_arg0.clipInterrupted )
				f4_arg0.FuelCellIcon:registerEventHandler( "transition_complete_keyframe", f4_arg0.clipFinished )
			end
			
			f4_arg0.FuelCellIcon:completeAnimation()
			f4_arg0.FuelCellIcon:setLeftRight( 0, 0, -34, 26 )
			f4_arg0.FuelCellIcon:setTopBottom( 0, 0, -2, 58 )
			f4_arg0.FuelCellIcon:setAlpha( 1 )
			f4_local2( f4_arg0.FuelCellIcon )
			local f4_local3 = function ( f9_arg0 )
				f4_arg0.ObjectiveTextBox:beginAnimation( 200 )
				f4_arg0.ObjectiveTextBox:setAlpha( 0 )
				f4_arg0.ObjectiveTextBox:registerEventHandler( "interrupted_keyframe", f4_arg0.clipInterrupted )
				f4_arg0.ObjectiveTextBox:registerEventHandler( "transition_complete_keyframe", f4_arg0.clipFinished )
			end
			
			f4_arg0.ObjectiveTextBox:completeAnimation()
			f4_arg0.ObjectiveTextBox:setLeftRight( 0, 0, -50, 270 )
			f4_arg0.ObjectiveTextBox:setTopBottom( 0, 0, 16, 44 )
			f4_arg0.ObjectiveTextBox:setAlpha( 1 )
			f4_local3( f4_arg0.ObjectiveTextBox )
		end,
		CollapsedLeft = function ( f10_arg0, f10_arg1 )
			f10_arg0:__resetProperties()
			f10_arg0:setupElementClipCounter( 4 )
			local f10_local0 = function ( f11_arg0 )
				f10_arg0.CenterBacking:beginAnimation( 450 )
				f10_arg0.CenterBacking:setShaderVector( 0, 0, 0.16, 0, 0 )
				f10_arg0.CenterBacking:registerEventHandler( "interrupted_keyframe", f10_arg0.clipInterrupted )
				f10_arg0.CenterBacking:registerEventHandler( "transition_complete_keyframe", f10_arg0.clipFinished )
			end
			
			f10_arg0.CenterBacking:completeAnimation()
			f10_arg0.CenterBacking:setAlpha( 1 )
			f10_arg0.CenterBacking:setMaterial( LUI.UIImage.GetCachedMaterial( "uie_wipe_delta_normal" ) )
			f10_arg0.CenterBacking:setShaderVector( 0, 0, 1, 0, 0 )
			f10_arg0.CenterBacking:setShaderVector( 1, 0, 0, 0, 0 )
			f10_arg0.CenterBacking:setShaderVector( 2, 0, 1, 0, 0 )
			f10_arg0.CenterBacking:setShaderVector( 3, 0, 0, 0, 0 )
			f10_arg0.CenterBacking:setShaderVector( 4, 0, 0, 0, 0 )
			f10_local0( f10_arg0.CenterBacking )
			local f10_local1 = function ( f12_arg0 )
				f10_arg0.ObjectiveProgressionFrame:beginAnimation( 450 )
				f10_arg0.ObjectiveProgressionFrame:setAlpha( 0 )
				f10_arg0.ObjectiveProgressionFrame:registerEventHandler( "interrupted_keyframe", f10_arg0.clipInterrupted )
				f10_arg0.ObjectiveProgressionFrame:registerEventHandler( "transition_complete_keyframe", function ( element, event )
					f10_arg0.clipFinished( element, event )
				end )
			end
			
			f10_arg0.ObjectiveProgressionFrame:completeAnimation()
			f10_arg0.ObjectiveProgressionFrame:setAlpha( 1 )
			f10_local1( f10_arg0.ObjectiveProgressionFrame )
			local f10_local2 = function ( f14_arg0 )
				f10_arg0.FuelCellIcon:beginAnimation( 450 )
				f10_arg0.FuelCellIcon:setLeftRight( 0, 0, -40, 20 )
				f10_arg0.FuelCellIcon:setAlpha( 0.2 )
				f10_arg0.FuelCellIcon:registerEventHandler( "interrupted_keyframe", f10_arg0.clipInterrupted )
				f10_arg0.FuelCellIcon:registerEventHandler( "transition_complete_keyframe", f10_arg0.clipFinished )
			end
			
			f10_arg0.FuelCellIcon:completeAnimation()
			f10_arg0.FuelCellIcon:setLeftRight( 0, 0, -34, 26 )
			f10_arg0.FuelCellIcon:setTopBottom( 0, 0, -2, 58 )
			f10_arg0.FuelCellIcon:setAlpha( 1 )
			f10_local2( f10_arg0.FuelCellIcon )
			local f10_local3 = function ( f15_arg0 )
				f10_arg0.ObjectiveTextBox:beginAnimation( 200 )
				f10_arg0.ObjectiveTextBox:setAlpha( 0 )
				f10_arg0.ObjectiveTextBox:registerEventHandler( "interrupted_keyframe", f10_arg0.clipInterrupted )
				f10_arg0.ObjectiveTextBox:registerEventHandler( "transition_complete_keyframe", f10_arg0.clipFinished )
			end
			
			f10_arg0.ObjectiveTextBox:completeAnimation()
			f10_arg0.ObjectiveTextBox:setLeftRight( 0, 0, -50, 270 )
			f10_arg0.ObjectiveTextBox:setTopBottom( 0, 0, 16, 44 )
			f10_arg0.ObjectiveTextBox:setAlpha( 1 )
			f10_local3( f10_arg0.ObjectiveTextBox )
		end
	},
	CollapsedRight = {
		DefaultClip = function ( f16_arg0, f16_arg1 )
			f16_arg0:__resetProperties()
			f16_arg0:setupElementClipCounter( 4 )
			f16_arg0.CenterBacking:completeAnimation()
			f16_arg0.CenterBacking:setMaterial( LUI.UIImage.GetCachedMaterial( "uie_wipe_delta_normal" ) )
			f16_arg0.CenterBacking:setShaderVector( 0, 0.85, 1, 0, 0 )
			f16_arg0.CenterBacking:setShaderVector( 1, 0, 0, 0, 0 )
			f16_arg0.CenterBacking:setShaderVector( 2, 0, 1, 0, 0 )
			f16_arg0.CenterBacking:setShaderVector( 3, 0, 0, 0, 0 )
			f16_arg0.CenterBacking:setShaderVector( 4, 0, 0, 0, 0 )
			f16_arg0.clipFinished( f16_arg0.CenterBacking )
			f16_arg0.ObjectiveProgressionFrame:completeAnimation()
			f16_arg0.ObjectiveProgressionFrame:setAlpha( 0 )
			f16_arg0.clipFinished( f16_arg0.ObjectiveProgressionFrame )
			f16_arg0.FuelCellIcon:completeAnimation()
			f16_arg0.FuelCellIcon:setAlpha( 0.2 )
			f16_arg0.clipFinished( f16_arg0.FuelCellIcon )
			f16_arg0.ObjectiveTextBox:completeAnimation()
			f16_arg0.ObjectiveTextBox:setAlpha( 0 )
			f16_arg0.clipFinished( f16_arg0.ObjectiveTextBox )
		end,
		DefaultState = function ( f17_arg0, f17_arg1 )
			f17_arg0:__resetProperties()
			f17_arg0:setupElementClipCounter( 4 )
			local f17_local0 = function ( f18_arg0 )
				f17_arg0.CenterBacking:beginAnimation( 450 )
				f17_arg0.CenterBacking:setShaderVector( 0, 0, 1, 0, 0 )
				f17_arg0.CenterBacking:registerEventHandler( "interrupted_keyframe", f17_arg0.clipInterrupted )
				f17_arg0.CenterBacking:registerEventHandler( "transition_complete_keyframe", f17_arg0.clipFinished )
			end
			
			f17_arg0.CenterBacking:completeAnimation()
			f17_arg0.CenterBacking:setAlpha( 1 )
			f17_arg0.CenterBacking:setMaterial( LUI.UIImage.GetCachedMaterial( "uie_wipe_delta_normal" ) )
			f17_arg0.CenterBacking:setShaderVector( 0, 0.85, 1, 0, 0 )
			f17_arg0.CenterBacking:setShaderVector( 1, 0, 0, 0, 0 )
			f17_arg0.CenterBacking:setShaderVector( 2, 0, 1, 0, 0 )
			f17_arg0.CenterBacking:setShaderVector( 3, 0, 0, 0, 0 )
			f17_arg0.CenterBacking:setShaderVector( 4, 0, 0, 0, 0 )
			f17_local0( f17_arg0.CenterBacking )
			local f17_local1 = function ( f19_arg0 )
				f17_arg0.ObjectiveProgressionFrame:beginAnimation( 450 )
				f17_arg0.ObjectiveProgressionFrame:setAlpha( 1 )
				f17_arg0.ObjectiveProgressionFrame:registerEventHandler( "interrupted_keyframe", f17_arg0.clipInterrupted )
				f17_arg0.ObjectiveProgressionFrame:registerEventHandler( "transition_complete_keyframe", function ( element, event )
					f17_arg0.clipFinished( element, event )
				end )
			end
			
			f17_arg0.ObjectiveProgressionFrame:completeAnimation()
			f17_arg0.ObjectiveProgressionFrame:setAlpha( 0 )
			f17_local1( f17_arg0.ObjectiveProgressionFrame )
			local f17_local2 = function ( f21_arg0 )
				f17_arg0.FuelCellIcon:beginAnimation( 450 )
				f17_arg0.FuelCellIcon:setLeftRight( 0, 0, -34, 26 )
				f17_arg0.FuelCellIcon:setAlpha( 1 )
				f17_arg0.FuelCellIcon:registerEventHandler( "interrupted_keyframe", f17_arg0.clipInterrupted )
				f17_arg0.FuelCellIcon:registerEventHandler( "transition_complete_keyframe", f17_arg0.clipFinished )
			end
			
			f17_arg0.FuelCellIcon:completeAnimation()
			f17_arg0.FuelCellIcon:setLeftRight( 0, 0, 199, 259 )
			f17_arg0.FuelCellIcon:setTopBottom( 0, 0, -2, 58 )
			f17_arg0.FuelCellIcon:setAlpha( 0.2 )
			f17_local2( f17_arg0.FuelCellIcon )
			local f17_local3 = function ( f22_arg0 )
				f22_arg0:beginAnimation( 199 )
				f22_arg0:setAlpha( 1 )
				f22_arg0:registerEventHandler( "transition_complete_keyframe", f17_arg0.clipFinished )
			end
			
			f17_arg0.ObjectiveTextBox:beginAnimation( 250 )
			f17_arg0.ObjectiveTextBox:setLeftRight( 0, 0, -50, 270 )
			f17_arg0.ObjectiveTextBox:setTopBottom( 0, 0, 16, 44 )
			f17_arg0.ObjectiveTextBox:setAlpha( 0 )
			f17_arg0.ObjectiveTextBox:registerEventHandler( "interrupted_keyframe", f17_arg0.clipInterrupted )
			f17_arg0.ObjectiveTextBox:registerEventHandler( "transition_complete_keyframe", f17_local3 )
		end
	},
	CollapsedLeft = {
		DefaultClip = function ( f23_arg0, f23_arg1 )
			f23_arg0:__resetProperties()
			f23_arg0:setupElementClipCounter( 4 )
			f23_arg0.CenterBacking:completeAnimation()
			f23_arg0.CenterBacking:setMaterial( LUI.UIImage.GetCachedMaterial( "uie_wipe_delta_normal" ) )
			f23_arg0.CenterBacking:setShaderVector( 0, 0, 0.16, 0, 0 )
			f23_arg0.CenterBacking:setShaderVector( 1, 0, 0, 0, 0 )
			f23_arg0.CenterBacking:setShaderVector( 2, 0, 1, 0, 0 )
			f23_arg0.CenterBacking:setShaderVector( 3, 0, 0, 0, 0 )
			f23_arg0.CenterBacking:setShaderVector( 4, 0, 0, 0, 0 )
			f23_arg0.clipFinished( f23_arg0.CenterBacking )
			f23_arg0.ObjectiveProgressionFrame:completeAnimation()
			f23_arg0.ObjectiveProgressionFrame:setAlpha( 0 )
			f23_arg0.clipFinished( f23_arg0.ObjectiveProgressionFrame )
			f23_arg0.FuelCellIcon:completeAnimation()
			f23_arg0.FuelCellIcon:setLeftRight( 0, 0, -40, 20 )
			f23_arg0.FuelCellIcon:setTopBottom( 0, 0, -2, 58 )
			f23_arg0.FuelCellIcon:setAlpha( 0.2 )
			f23_arg0.clipFinished( f23_arg0.FuelCellIcon )
			f23_arg0.ObjectiveTextBox:completeAnimation()
			f23_arg0.ObjectiveTextBox:setAlpha( 0 )
			f23_arg0.clipFinished( f23_arg0.ObjectiveTextBox )
		end,
		DefaultState = function ( f24_arg0, f24_arg1 )
			f24_arg0:__resetProperties()
			f24_arg0:setupElementClipCounter( 4 )
			local f24_local0 = function ( f25_arg0 )
				f24_arg0.CenterBacking:beginAnimation( 450 )
				f24_arg0.CenterBacking:setShaderVector( 0, 0, 0.16, 0, 0 )
				f24_arg0.CenterBacking:registerEventHandler( "interrupted_keyframe", f24_arg0.clipInterrupted )
				f24_arg0.CenterBacking:registerEventHandler( "transition_complete_keyframe", f24_arg0.clipFinished )
			end
			
			f24_arg0.CenterBacking:completeAnimation()
			f24_arg0.CenterBacking:setMaterial( LUI.UIImage.GetCachedMaterial( "uie_wipe_delta_normal" ) )
			f24_arg0.CenterBacking:setShaderVector( 0, 0, 1, 0, 0 )
			f24_arg0.CenterBacking:setShaderVector( 1, 0, 0, 0, 0 )
			f24_arg0.CenterBacking:setShaderVector( 2, 0, 1, 0, 0 )
			f24_arg0.CenterBacking:setShaderVector( 3, 0, 0, 0, 0 )
			f24_arg0.CenterBacking:setShaderVector( 4, 0, 0, 0, 0 )
			f24_local0( f24_arg0.CenterBacking )
			local f24_local1 = function ( f26_arg0 )
				f24_arg0.ObjectiveProgressionFrame:beginAnimation( 220 )
				f24_arg0.ObjectiveProgressionFrame:setAlpha( 0 )
				f24_arg0.ObjectiveProgressionFrame:registerEventHandler( "interrupted_keyframe", f24_arg0.clipInterrupted )
				f24_arg0.ObjectiveProgressionFrame:registerEventHandler( "transition_complete_keyframe", function ( element, event )
					f24_arg0.clipFinished( element, event )
				end )
			end
			
			f24_arg0.ObjectiveProgressionFrame:completeAnimation()
			f24_arg0.ObjectiveProgressionFrame:setAlpha( 1 )
			f24_local1( f24_arg0.ObjectiveProgressionFrame )
			local f24_local2 = function ( f28_arg0 )
				f24_arg0.FuelCellIcon:beginAnimation( 450 )
				f24_arg0.FuelCellIcon:setLeftRight( 0, 0, -40, 20 )
				f24_arg0.FuelCellIcon:setAlpha( 0.2 )
				f24_arg0.FuelCellIcon:registerEventHandler( "interrupted_keyframe", f24_arg0.clipInterrupted )
				f24_arg0.FuelCellIcon:registerEventHandler( "transition_complete_keyframe", f24_arg0.clipFinished )
			end
			
			f24_arg0.FuelCellIcon:completeAnimation()
			f24_arg0.FuelCellIcon:setLeftRight( 0, 0, -34, 26 )
			f24_arg0.FuelCellIcon:setTopBottom( 0, 0, -2, 58 )
			f24_arg0.FuelCellIcon:setAlpha( 1 )
			f24_local2( f24_arg0.FuelCellIcon )
			local f24_local3 = function ( f29_arg0 )
				f24_arg0.ObjectiveTextBox:beginAnimation( 220 )
				f24_arg0.ObjectiveTextBox:setAlpha( 0 )
				f24_arg0.ObjectiveTextBox:registerEventHandler( "interrupted_keyframe", f24_arg0.clipInterrupted )
				f24_arg0.ObjectiveTextBox:registerEventHandler( "transition_complete_keyframe", f24_arg0.clipFinished )
			end
			
			f24_arg0.ObjectiveTextBox:completeAnimation()
			f24_arg0.ObjectiveTextBox:setLeftRight( 0, 0, -50, 270 )
			f24_arg0.ObjectiveTextBox:setTopBottom( 0, 0, 16, 44 )
			f24_arg0.ObjectiveTextBox:setAlpha( 1 )
			f24_local3( f24_arg0.ObjectiveTextBox )
		end
	},
	Contested = {
		DefaultClip = function ( f30_arg0, f30_arg1 )
			f30_arg0:__resetProperties()
			f30_arg0:setupElementClipCounter( 4 )
			f30_arg0.CenterBacking:completeAnimation()
			f30_arg0.CenterBacking:setMaterial( LUI.UIImage.GetCachedMaterial( "uie_wipe_delta_normal" ) )
			f30_arg0.CenterBacking:setShaderVector( 0, 0, 1, 0, 0 )
			f30_arg0.CenterBacking:setShaderVector( 1, 0, 0, 0, 0 )
			f30_arg0.CenterBacking:setShaderVector( 2, 0, 1, 0, 0 )
			f30_arg0.CenterBacking:setShaderVector( 3, 0, 0, 0, 0 )
			f30_arg0.CenterBacking:setShaderVector( 4, 0, 0, 0, 0 )
			f30_arg0.clipFinished( f30_arg0.CenterBacking )
			f30_arg0.FuelCellIcon:completeAnimation()
			f30_arg0.FuelCellIcon:setLeftRight( 0, 0, 9, 69 )
			f30_arg0.FuelCellIcon:setTopBottom( 0, 0, -2, 58 )
			f30_arg0.clipFinished( f30_arg0.FuelCellIcon )
			f30_arg0.ObjectiveTextBox:completeAnimation()
			f30_arg0.ObjectiveTextBox:setLeftRight( 0, 0, -50, 270 )
			f30_arg0.ObjectiveTextBox:setTopBottom( 0, 0, 16, 44 )
			f30_arg0.ObjectiveTextBox:setAlpha( 0 )
			f30_arg0.clipFinished( f30_arg0.ObjectiveTextBox )
			local f30_local0 = function ( f31_arg0 )
				local f31_local0 = function ( f32_arg0 )
					local f32_local0 = function ( f33_arg0 )
						f33_arg0:beginAnimation( 1000 )
						f33_arg0:registerEventHandler( "transition_complete_keyframe", f30_arg0.clipFinished )
					end
					
					f32_arg0:beginAnimation( 600, Enum[0xF50FFF429AB1890][0x5D2D9CF90AB1735] | Enum[0xF50FFF429AB1890][0x6F6186B702830BC] )
					f32_arg0:setScale( 1, 1 )
					f32_arg0:registerEventHandler( "transition_complete_keyframe", f32_local0 )
				end
				
				f30_arg0.ContestedText:beginAnimation( 400 )
				f30_arg0.ContestedText:setScale( 1.2, 1.2 )
				f30_arg0.ContestedText:registerEventHandler( "interrupted_keyframe", f30_arg0.clipInterrupted )
				f30_arg0.ContestedText:registerEventHandler( "transition_complete_keyframe", f31_local0 )
			end
			
			f30_arg0.ContestedText:completeAnimation()
			f30_arg0.ContestedText:setLeftRight( 0, 0, -50, 270 )
			f30_arg0.ContestedText:setTopBottom( 0, 0, 16, 44 )
			f30_arg0.ContestedText:setAlpha( 1 )
			f30_arg0.ContestedText:setScale( 1, 1 )
			f30_local0( f30_arg0.ContestedText )
			f30_arg0.nextClip = "DefaultClip"
		end
	}
}
CoD.WarScoreInfo_StageNotification.__onClose = function ( f34_arg0 )
	f34_arg0.ObjectiveProgressionFrame:close()
end

