require( "x64:bf776923c7291f4" )

CoD.StartMenu_Inventory_SwitchWeaponTab_Activate = InheritFrom( LUI.UIElement )
CoD.StartMenu_Inventory_SwitchWeaponTab_Activate.__defaultWidth = 450
CoD.StartMenu_Inventory_SwitchWeaponTab_Activate.__defaultHeight = 32
CoD.StartMenu_Inventory_SwitchWeaponTab_Activate.new = function ( f1_arg0, f1_arg1, f1_arg2, f1_arg3, f1_arg4, f1_arg5, f1_arg6, f1_arg7, f1_arg8, f1_arg9 )
	local self = LUI.UIElement.new( f1_arg2, f1_arg3, f1_arg4, f1_arg5, f1_arg6, f1_arg7, f1_arg8, f1_arg9 )
	self:setClass( CoD.StartMenu_Inventory_SwitchWeaponTab_Activate )
	self.id = "StartMenu_Inventory_SwitchWeaponTab_Activate"
	self.soundSet = "default"
	f1_arg0:addElementToPendingUpdateStateList( self )
	
	local Background = LUI.UIImage.new( 0, 1, 0, 0, 0, 1, 0, 0 )
	Background:setRGB( 0.55, 0.54, 0.49 )
	self:addElement( Background )
	self.Background = Background
	
	local NineSliceShaderImage = LUI.UIImage.new( 0, 1, 0, 0, 0, 1, 0, 0 )
	NineSliceShaderImage:setRGB( 0.55, 0.54, 0.49 )
	NineSliceShaderImage:setImage( RegisterImage( 0xF1E3082B39E99BB ) )
	NineSliceShaderImage:setMaterial( LUI.UIImage.GetCachedMaterial( "uie_nineslice_normal" ) )
	NineSliceShaderImage:setShaderVector( 0, 0, 0, 0, 0 )
	NineSliceShaderImage:setupNineSliceShader( 6, 6 )
	self:addElement( NineSliceShaderImage )
	self.NineSliceShaderImage = NineSliceShaderImage
	
	local HeaderWeapon = LUI.UIText.new( 0, 1, 25, -25, 0.5, 0.5, -11, 11 )
	HeaderWeapon:setRGB( 0, 0, 0 )
	HeaderWeapon:setAlpha( 0 )
	HeaderWeapon:setText( Engine[0xF9F1239CFD921FE]( 0x5B8A625B47D0EBA ) )
	HeaderWeapon:setTTF( "ttmussels_regular" )
	HeaderWeapon:setLetterSpacing( 4 )
	HeaderWeapon:setAlignment( Enum.LUIAlignment[0xFEEB12BCB0D7041] )
	HeaderWeapon:setAlignment( Enum.LUIAlignment[0xE821F0ECFF8D1C7] )
	self:addElement( HeaderWeapon )
	self.HeaderWeapon = HeaderWeapon
	
	local HeaderWeaponEquipped = LUI.UIText.new( 0, 1, 25, -25, 0.5, 0.5, -11, 11 )
	HeaderWeaponEquipped:setRGB( 0, 0, 0 )
	HeaderWeaponEquipped:setText( Engine[0xF9F1239CFD921FE]( 0x2F5D67B7D6915EF ) )
	HeaderWeaponEquipped:setTTF( "ttmussels_regular" )
	HeaderWeaponEquipped:setLetterSpacing( 4 )
	HeaderWeaponEquipped:setAlignment( Enum.LUIAlignment[0xFEEB12BCB0D7041] )
	HeaderWeaponEquipped:setAlignment( Enum.LUIAlignment[0xE821F0ECFF8D1C7] )
	self:addElement( HeaderWeaponEquipped )
	self.HeaderWeaponEquipped = HeaderWeaponEquipped
	
	local MinusButton = LUI.UIImage.new( 1, 1, -30, 0, 0.5, 0.5, -15, 15 )
	MinusButton:setRGB( 0, 0, 0 )
	MinusButton:setImage( RegisterImage( 0x8EBD33D94FD1BCF ) )
	self:addElement( MinusButton )
	self.MinusButton = MinusButton
	
	local PlusButton = LUI.UIImage.new( 1, 1, -30, 0, 0.5, 0.5, -15, 15 )
	PlusButton:setRGB( 0.66, 0.63, 0.52 )
	PlusButton:setAlpha( 0.05 )
	PlusButton:setZRot( 270 )
	PlusButton:setImage( RegisterImage( 0x8EBD33D94FD1BCF ) )
	self:addElement( PlusButton )
	self.PlusButton = PlusButton
	
	local SwitchWeaponImage = LUI.UIImage.new( 1, 1, -25, -4, 0.5, 0.5, -10.5, 10.5 )
	SwitchWeaponImage:setAlpha( 0 )
	SwitchWeaponImage:subscribeToGlobalModel( f1_arg1, "Controller", "alt2_button_image", function ( model )
		local f2_local0 = model:get()
		if f2_local0 ~= nil then
			SwitchWeaponImage:setImage( RegisterImage( f2_local0 ) )
		end
	end )
	self:addElement( SwitchWeaponImage )
	self.SwitchWeaponImage = SwitchWeaponImage
	
	local FrameSelected = LUI.UIImage.new( 0, 1, -12, 12, 0, 1, -3, 3 )
	FrameSelected:setAlpha( 0 )
	FrameSelected:setScale( 0.96, 0.96 )
	FrameSelected:setImage( RegisterImage( "uie_ui_menu_store_focus_frame" ) )
	FrameSelected:setMaterial( LUI.UIImage.GetCachedMaterial( "uie_nineslice_add" ) )
	FrameSelected:setShaderVector( 0, 0, 0, 0, 0 )
	FrameSelected:setupNineSliceShader( 8, 8 )
	self:addElement( FrameSelected )
	self.FrameSelected = FrameSelected
	
	LUI.OverrideFunction_CallOriginalSecond( self, "close", self.__onClose )
	
	if PostLoadFunc then
		PostLoadFunc( self, f1_arg1, f1_arg0 )
	end
	
	return self
end

CoD.StartMenu_Inventory_SwitchWeaponTab_Activate.__resetProperties = function ( f3_arg0 )
	f3_arg0.NineSliceShaderImage:completeAnimation()
	f3_arg0.HeaderWeapon:completeAnimation()
	f3_arg0.Background:completeAnimation()
	f3_arg0.PlusButton:completeAnimation()
	f3_arg0.HeaderWeaponEquipped:completeAnimation()
	f3_arg0.MinusButton:completeAnimation()
	f3_arg0.FrameSelected:completeAnimation()
	f3_arg0.SwitchWeaponImage:completeAnimation()
	f3_arg0.NineSliceShaderImage:setAlpha( 1 )
	f3_arg0.HeaderWeapon:setRGB( 0, 0, 0 )
	f3_arg0.HeaderWeapon:setAlpha( 0 )
	f3_arg0.HeaderWeapon:setBackingAlpha( 1 )
	f3_arg0.Background:setRGB( 0.55, 0.54, 0.49 )
	f3_arg0.Background:setAlpha( 1 )
	f3_arg0.PlusButton:setRGB( 0.66, 0.63, 0.52 )
	f3_arg0.PlusButton:setAlpha( 0.05 )
	f3_arg0.HeaderWeaponEquipped:setAlpha( 1 )
	f3_arg0.MinusButton:setLeftRight( 1, 1, -30, 0 )
	f3_arg0.MinusButton:setRGB( 0, 0, 0 )
	f3_arg0.MinusButton:setAlpha( 1 )
	f3_arg0.FrameSelected:setAlpha( 0 )
	f3_arg0.SwitchWeaponImage:setAlpha( 0 )
end

CoD.StartMenu_Inventory_SwitchWeaponTab_Activate.__clipsPerState = {
	DefaultState = {
		DefaultClip = function ( f4_arg0, f4_arg1 )
			f4_arg0:__resetProperties()
			f4_arg0:setupElementClipCounter( 6 )
			f4_arg0.Background:completeAnimation()
			f4_arg0.Background:setAlpha( 1 )
			f4_arg0.clipFinished( f4_arg0.Background )
			f4_arg0.NineSliceShaderImage:completeAnimation()
			f4_arg0.NineSliceShaderImage:setAlpha( 1 )
			f4_arg0.clipFinished( f4_arg0.NineSliceShaderImage )
			f4_arg0.HeaderWeapon:completeAnimation()
			f4_arg0.HeaderWeapon:setRGB( 0, 0, 0 )
			f4_arg0.HeaderWeapon:setAlpha( 0 )
			f4_arg0.HeaderWeapon:setBackingAlpha( 0 )
			f4_arg0.clipFinished( f4_arg0.HeaderWeapon )
			f4_arg0.HeaderWeaponEquipped:completeAnimation()
			f4_arg0.HeaderWeaponEquipped:setAlpha( 1 )
			f4_arg0.clipFinished( f4_arg0.HeaderWeaponEquipped )
			f4_arg0.MinusButton:completeAnimation()
			f4_arg0.MinusButton:setAlpha( 0.8 )
			f4_arg0.clipFinished( f4_arg0.MinusButton )
			f4_arg0.PlusButton:completeAnimation()
			f4_arg0.PlusButton:setAlpha( 0 )
			f4_arg0.clipFinished( f4_arg0.PlusButton )
		end,
		Focus = function ( f5_arg0, f5_arg1 )
			f5_arg0:__resetProperties()
			f5_arg0:setupElementClipCounter( 6 )
			f5_arg0.Background:completeAnimation()
			f5_arg0.Background:setRGB( 0.73, 0.72, 0.64 )
			f5_arg0.Background:setAlpha( 1 )
			f5_arg0.clipFinished( f5_arg0.Background )
			f5_arg0.NineSliceShaderImage:completeAnimation()
			f5_arg0.NineSliceShaderImage:setAlpha( 1 )
			f5_arg0.clipFinished( f5_arg0.NineSliceShaderImage )
			f5_arg0.HeaderWeapon:completeAnimation()
			f5_arg0.HeaderWeapon:setRGB( 0, 0, 0 )
			f5_arg0.HeaderWeapon:setAlpha( 0 )
			f5_arg0.HeaderWeapon:setBackingAlpha( 0 )
			f5_arg0.clipFinished( f5_arg0.HeaderWeapon )
			f5_arg0.HeaderWeaponEquipped:completeAnimation()
			f5_arg0.HeaderWeaponEquipped:setAlpha( 1 )
			f5_arg0.clipFinished( f5_arg0.HeaderWeaponEquipped )
			f5_arg0.PlusButton:completeAnimation()
			f5_arg0.PlusButton:setAlpha( 0 )
			f5_arg0.clipFinished( f5_arg0.PlusButton )
			f5_arg0.FrameSelected:completeAnimation()
			f5_arg0.FrameSelected:setAlpha( 1 )
			f5_arg0.clipFinished( f5_arg0.FrameSelected )
		end,
		GainFocus = function ( f6_arg0, f6_arg1 )
			f6_arg0:__resetProperties()
			f6_arg0:setupElementClipCounter( 7 )
			local f6_local0 = function ( f7_arg0 )
				f6_arg0.Background:beginAnimation( 200 )
				f6_arg0.Background:setRGB( 0.73, 0.72, 0.64 )
				f6_arg0.Background:registerEventHandler( "interrupted_keyframe", f6_arg0.clipInterrupted )
				f6_arg0.Background:registerEventHandler( "transition_complete_keyframe", f6_arg0.clipFinished )
			end
			
			f6_arg0.Background:completeAnimation()
			f6_arg0.Background:setRGB( 0.55, 0.54, 0.49 )
			f6_arg0.Background:setAlpha( 1 )
			f6_local0( f6_arg0.Background )
			f6_arg0.NineSliceShaderImage:completeAnimation()
			f6_arg0.NineSliceShaderImage:setAlpha( 1 )
			f6_arg0.clipFinished( f6_arg0.NineSliceShaderImage )
			f6_arg0.HeaderWeapon:completeAnimation()
			f6_arg0.HeaderWeapon:setRGB( 0, 0, 0 )
			f6_arg0.HeaderWeapon:setAlpha( 0 )
			f6_arg0.HeaderWeapon:setBackingAlpha( 0 )
			f6_arg0.clipFinished( f6_arg0.HeaderWeapon )
			f6_arg0.HeaderWeaponEquipped:completeAnimation()
			f6_arg0.HeaderWeaponEquipped:setAlpha( 1 )
			f6_arg0.clipFinished( f6_arg0.HeaderWeaponEquipped )
			local f6_local1 = function ( f8_arg0 )
				f6_arg0.MinusButton:beginAnimation( 200 )
				f6_arg0.MinusButton:setAlpha( 1 )
				f6_arg0.MinusButton:registerEventHandler( "interrupted_keyframe", f6_arg0.clipInterrupted )
				f6_arg0.MinusButton:registerEventHandler( "transition_complete_keyframe", f6_arg0.clipFinished )
			end
			
			f6_arg0.MinusButton:completeAnimation()
			f6_arg0.MinusButton:setAlpha( 0.8 )
			f6_local1( f6_arg0.MinusButton )
			f6_arg0.PlusButton:completeAnimation()
			f6_arg0.PlusButton:setAlpha( 0 )
			f6_arg0.clipFinished( f6_arg0.PlusButton )
			local f6_local2 = function ( f9_arg0 )
				f6_arg0.FrameSelected:beginAnimation( 200 )
				f6_arg0.FrameSelected:setAlpha( 1 )
				f6_arg0.FrameSelected:registerEventHandler( "interrupted_keyframe", f6_arg0.clipInterrupted )
				f6_arg0.FrameSelected:registerEventHandler( "transition_complete_keyframe", f6_arg0.clipFinished )
			end
			
			f6_arg0.FrameSelected:completeAnimation()
			f6_arg0.FrameSelected:setAlpha( 0 )
			f6_local2( f6_arg0.FrameSelected )
		end,
		LoseFocus = function ( f10_arg0, f10_arg1 )
			f10_arg0:__resetProperties()
			f10_arg0:setupElementClipCounter( 7 )
			local f10_local0 = function ( f11_arg0 )
				f10_arg0.Background:beginAnimation( 200 )
				f10_arg0.Background:setRGB( 0.55, 0.54, 0.49 )
				f10_arg0.Background:registerEventHandler( "interrupted_keyframe", f10_arg0.clipInterrupted )
				f10_arg0.Background:registerEventHandler( "transition_complete_keyframe", f10_arg0.clipFinished )
			end
			
			f10_arg0.Background:completeAnimation()
			f10_arg0.Background:setRGB( 0.73, 0.72, 0.64 )
			f10_arg0.Background:setAlpha( 1 )
			f10_local0( f10_arg0.Background )
			f10_arg0.NineSliceShaderImage:completeAnimation()
			f10_arg0.NineSliceShaderImage:setAlpha( 1 )
			f10_arg0.clipFinished( f10_arg0.NineSliceShaderImage )
			f10_arg0.HeaderWeapon:completeAnimation()
			f10_arg0.HeaderWeapon:setRGB( 0, 0, 0 )
			f10_arg0.HeaderWeapon:setAlpha( 0 )
			f10_arg0.HeaderWeapon:setBackingAlpha( 0 )
			f10_arg0.clipFinished( f10_arg0.HeaderWeapon )
			f10_arg0.HeaderWeaponEquipped:completeAnimation()
			f10_arg0.HeaderWeaponEquipped:setAlpha( 1 )
			f10_arg0.clipFinished( f10_arg0.HeaderWeaponEquipped )
			local f10_local1 = function ( f12_arg0 )
				f10_arg0.MinusButton:beginAnimation( 200 )
				f10_arg0.MinusButton:setAlpha( 0.8 )
				f10_arg0.MinusButton:registerEventHandler( "interrupted_keyframe", f10_arg0.clipInterrupted )
				f10_arg0.MinusButton:registerEventHandler( "transition_complete_keyframe", f10_arg0.clipFinished )
			end
			
			f10_arg0.MinusButton:completeAnimation()
			f10_arg0.MinusButton:setAlpha( 1 )
			f10_local1( f10_arg0.MinusButton )
			f10_arg0.PlusButton:completeAnimation()
			f10_arg0.PlusButton:setAlpha( 0 )
			f10_arg0.clipFinished( f10_arg0.PlusButton )
			local f10_local2 = function ( f13_arg0 )
				f10_arg0.FrameSelected:beginAnimation( 200 )
				f10_arg0.FrameSelected:setAlpha( 0 )
				f10_arg0.FrameSelected:registerEventHandler( "interrupted_keyframe", f10_arg0.clipInterrupted )
				f10_arg0.FrameSelected:registerEventHandler( "transition_complete_keyframe", f10_arg0.clipFinished )
			end
			
			f10_arg0.FrameSelected:completeAnimation()
			f10_arg0.FrameSelected:setAlpha( 1 )
			f10_local2( f10_arg0.FrameSelected )
		end
	},
	ClosedGamePad = {
		DefaultClip = function ( f14_arg0, f14_arg1 )
			f14_arg0:__resetProperties()
			f14_arg0:setupElementClipCounter( 7 )
			f14_arg0.Background:completeAnimation()
			f14_arg0.Background:setAlpha( 0 )
			f14_arg0.clipFinished( f14_arg0.Background )
			f14_arg0.NineSliceShaderImage:completeAnimation()
			f14_arg0.NineSliceShaderImage:setAlpha( 1 )
			f14_arg0.clipFinished( f14_arg0.NineSliceShaderImage )
			f14_arg0.HeaderWeapon:completeAnimation()
			f14_arg0.HeaderWeapon:setRGB( ColorSet.T8__BEIGE__HEADER.r, ColorSet.T8__BEIGE__HEADER.g, ColorSet.T8__BEIGE__HEADER.b )
			f14_arg0.HeaderWeapon:setAlpha( 1 )
			f14_arg0.clipFinished( f14_arg0.HeaderWeapon )
			f14_arg0.HeaderWeaponEquipped:completeAnimation()
			f14_arg0.HeaderWeaponEquipped:setAlpha( 0 )
			f14_arg0.clipFinished( f14_arg0.HeaderWeaponEquipped )
			f14_arg0.MinusButton:completeAnimation()
			f14_arg0.MinusButton:setAlpha( 0 )
			f14_arg0.clipFinished( f14_arg0.MinusButton )
			f14_arg0.PlusButton:completeAnimation()
			f14_arg0.PlusButton:setAlpha( 0 )
			f14_arg0.clipFinished( f14_arg0.PlusButton )
			f14_arg0.SwitchWeaponImage:completeAnimation()
			f14_arg0.SwitchWeaponImage:setAlpha( 1 )
			f14_arg0.clipFinished( f14_arg0.SwitchWeaponImage )
		end,
		Focus = function ( f15_arg0, f15_arg1 )
			f15_arg0:__resetProperties()
			f15_arg0:setupElementClipCounter( 8 )
			f15_arg0.Background:completeAnimation()
			f15_arg0.Background:setAlpha( 0.3 )
			f15_arg0.clipFinished( f15_arg0.Background )
			f15_arg0.NineSliceShaderImage:completeAnimation()
			f15_arg0.NineSliceShaderImage:setAlpha( 1 )
			f15_arg0.clipFinished( f15_arg0.NineSliceShaderImage )
			f15_arg0.HeaderWeapon:completeAnimation()
			f15_arg0.HeaderWeapon:setRGB( 0.73, 0.72, 0.64 )
			f15_arg0.HeaderWeapon:setAlpha( 1 )
			f15_arg0.clipFinished( f15_arg0.HeaderWeapon )
			f15_arg0.HeaderWeaponEquipped:completeAnimation()
			f15_arg0.HeaderWeaponEquipped:setAlpha( 0 )
			f15_arg0.clipFinished( f15_arg0.HeaderWeaponEquipped )
			f15_arg0.MinusButton:completeAnimation()
			f15_arg0.MinusButton:setLeftRight( 0, 0, 12, 23 )
			f15_arg0.MinusButton:setRGB( 0, 0, 0 )
			f15_arg0.MinusButton:setAlpha( 0 )
			f15_arg0.clipFinished( f15_arg0.MinusButton )
			f15_arg0.PlusButton:completeAnimation()
			f15_arg0.PlusButton:setAlpha( 0 )
			f15_arg0.clipFinished( f15_arg0.PlusButton )
			f15_arg0.SwitchWeaponImage:completeAnimation()
			f15_arg0.SwitchWeaponImage:setAlpha( 1 )
			f15_arg0.clipFinished( f15_arg0.SwitchWeaponImage )
			f15_arg0.FrameSelected:completeAnimation()
			f15_arg0.FrameSelected:setAlpha( 1 )
			f15_arg0.clipFinished( f15_arg0.FrameSelected )
		end,
		GainFocus = function ( f16_arg0, f16_arg1 )
			f16_arg0:__resetProperties()
			f16_arg0:setupElementClipCounter( 8 )
			local f16_local0 = function ( f17_arg0 )
				f16_arg0.Background:beginAnimation( 200 )
				f16_arg0.Background:setAlpha( 0.3 )
				f16_arg0.Background:registerEventHandler( "interrupted_keyframe", f16_arg0.clipInterrupted )
				f16_arg0.Background:registerEventHandler( "transition_complete_keyframe", f16_arg0.clipFinished )
			end
			
			f16_arg0.Background:completeAnimation()
			f16_arg0.Background:setAlpha( 0 )
			f16_local0( f16_arg0.Background )
			f16_arg0.NineSliceShaderImage:completeAnimation()
			f16_arg0.NineSliceShaderImage:setAlpha( 1 )
			f16_arg0.clipFinished( f16_arg0.NineSliceShaderImage )
			local f16_local1 = function ( f18_arg0 )
				f16_arg0.HeaderWeapon:beginAnimation( 200 )
				f16_arg0.HeaderWeapon:setRGB( 0.73, 0.72, 0.64 )
				f16_arg0.HeaderWeapon:registerEventHandler( "interrupted_keyframe", f16_arg0.clipInterrupted )
				f16_arg0.HeaderWeapon:registerEventHandler( "transition_complete_keyframe", f16_arg0.clipFinished )
			end
			
			f16_arg0.HeaderWeapon:completeAnimation()
			f16_arg0.HeaderWeapon:setRGB( 0.66, 0.63, 0.52 )
			f16_arg0.HeaderWeapon:setAlpha( 1 )
			f16_local1( f16_arg0.HeaderWeapon )
			f16_arg0.HeaderWeaponEquipped:completeAnimation()
			f16_arg0.HeaderWeaponEquipped:setAlpha( 0 )
			f16_arg0.clipFinished( f16_arg0.HeaderWeaponEquipped )
			local f16_local2 = function ( f19_arg0 )
				f16_arg0.MinusButton:beginAnimation( 200 )
				f16_arg0.MinusButton:setLeftRight( 0, 0, 12, 23 )
				f16_arg0.MinusButton:registerEventHandler( "interrupted_keyframe", f16_arg0.clipInterrupted )
				f16_arg0.MinusButton:registerEventHandler( "transition_complete_keyframe", f16_arg0.clipFinished )
			end
			
			f16_arg0.MinusButton:completeAnimation()
			f16_arg0.MinusButton:setLeftRight( 1, 1, -30, 0 )
			f16_arg0.MinusButton:setRGB( 0, 0, 0 )
			f16_arg0.MinusButton:setAlpha( 0 )
			f16_local2( f16_arg0.MinusButton )
			f16_arg0.PlusButton:completeAnimation()
			f16_arg0.PlusButton:setAlpha( 0 )
			f16_arg0.clipFinished( f16_arg0.PlusButton )
			f16_arg0.SwitchWeaponImage:completeAnimation()
			f16_arg0.SwitchWeaponImage:setAlpha( 1 )
			f16_arg0.clipFinished( f16_arg0.SwitchWeaponImage )
			local f16_local3 = function ( f20_arg0 )
				f16_arg0.FrameSelected:beginAnimation( 200 )
				f16_arg0.FrameSelected:setAlpha( 1 )
				f16_arg0.FrameSelected:registerEventHandler( "interrupted_keyframe", f16_arg0.clipInterrupted )
				f16_arg0.FrameSelected:registerEventHandler( "transition_complete_keyframe", f16_arg0.clipFinished )
			end
			
			f16_arg0.FrameSelected:completeAnimation()
			f16_arg0.FrameSelected:setAlpha( 0 )
			f16_local3( f16_arg0.FrameSelected )
		end,
		LoseFocus = function ( f21_arg0, f21_arg1 )
			f21_arg0:__resetProperties()
			f21_arg0:setupElementClipCounter( 8 )
			local f21_local0 = function ( f22_arg0 )
				f21_arg0.Background:beginAnimation( 200 )
				f21_arg0.Background:setAlpha( 0 )
				f21_arg0.Background:registerEventHandler( "interrupted_keyframe", f21_arg0.clipInterrupted )
				f21_arg0.Background:registerEventHandler( "transition_complete_keyframe", f21_arg0.clipFinished )
			end
			
			f21_arg0.Background:completeAnimation()
			f21_arg0.Background:setAlpha( 0.3 )
			f21_local0( f21_arg0.Background )
			f21_arg0.NineSliceShaderImage:completeAnimation()
			f21_arg0.NineSliceShaderImage:setAlpha( 1 )
			f21_arg0.clipFinished( f21_arg0.NineSliceShaderImage )
			local f21_local1 = function ( f23_arg0 )
				f21_arg0.HeaderWeapon:beginAnimation( 200 )
				f21_arg0.HeaderWeapon:setRGB( 0.66, 0.63, 0.52 )
				f21_arg0.HeaderWeapon:registerEventHandler( "interrupted_keyframe", f21_arg0.clipInterrupted )
				f21_arg0.HeaderWeapon:registerEventHandler( "transition_complete_keyframe", f21_arg0.clipFinished )
			end
			
			f21_arg0.HeaderWeapon:completeAnimation()
			f21_arg0.HeaderWeapon:setRGB( 0.73, 0.72, 0.64 )
			f21_arg0.HeaderWeapon:setAlpha( 1 )
			f21_local1( f21_arg0.HeaderWeapon )
			f21_arg0.HeaderWeaponEquipped:completeAnimation()
			f21_arg0.HeaderWeaponEquipped:setAlpha( 0 )
			f21_arg0.clipFinished( f21_arg0.HeaderWeaponEquipped )
			local f21_local2 = function ( f24_arg0 )
				f21_arg0.MinusButton:beginAnimation( 200 )
				f21_arg0.MinusButton:setLeftRight( 1, 1, -30, 0 )
				f21_arg0.MinusButton:registerEventHandler( "interrupted_keyframe", f21_arg0.clipInterrupted )
				f21_arg0.MinusButton:registerEventHandler( "transition_complete_keyframe", f21_arg0.clipFinished )
			end
			
			f21_arg0.MinusButton:completeAnimation()
			f21_arg0.MinusButton:setLeftRight( 0, 0, 12, 23 )
			f21_arg0.MinusButton:setRGB( 0, 0, 0 )
			f21_arg0.MinusButton:setAlpha( 0 )
			f21_local2( f21_arg0.MinusButton )
			f21_arg0.PlusButton:completeAnimation()
			f21_arg0.PlusButton:setAlpha( 0 )
			f21_arg0.clipFinished( f21_arg0.PlusButton )
			f21_arg0.SwitchWeaponImage:completeAnimation()
			f21_arg0.SwitchWeaponImage:setAlpha( 1 )
			f21_arg0.clipFinished( f21_arg0.SwitchWeaponImage )
			local f21_local3 = function ( f25_arg0 )
				f21_arg0.FrameSelected:beginAnimation( 200 )
				f21_arg0.FrameSelected:setAlpha( 0 )
				f21_arg0.FrameSelected:registerEventHandler( "interrupted_keyframe", f21_arg0.clipInterrupted )
				f21_arg0.FrameSelected:registerEventHandler( "transition_complete_keyframe", f21_arg0.clipFinished )
			end
			
			f21_arg0.FrameSelected:completeAnimation()
			f21_arg0.FrameSelected:setAlpha( 1 )
			f21_local3( f21_arg0.FrameSelected )
		end
	},
	Closed = {
		DefaultClip = function ( f26_arg0, f26_arg1 )
			f26_arg0:__resetProperties()
			f26_arg0:setupElementClipCounter( 6 )
			f26_arg0.Background:completeAnimation()
			f26_arg0.Background:setAlpha( 0 )
			f26_arg0.clipFinished( f26_arg0.Background )
			f26_arg0.NineSliceShaderImage:completeAnimation()
			f26_arg0.NineSliceShaderImage:setAlpha( 1 )
			f26_arg0.clipFinished( f26_arg0.NineSliceShaderImage )
			f26_arg0.HeaderWeapon:completeAnimation()
			f26_arg0.HeaderWeapon:setRGB( ColorSet.T8__BEIGE__HEADER.r, ColorSet.T8__BEIGE__HEADER.g, ColorSet.T8__BEIGE__HEADER.b )
			f26_arg0.HeaderWeapon:setAlpha( 1 )
			f26_arg0.clipFinished( f26_arg0.HeaderWeapon )
			f26_arg0.HeaderWeaponEquipped:completeAnimation()
			f26_arg0.HeaderWeaponEquipped:setAlpha( 0 )
			f26_arg0.clipFinished( f26_arg0.HeaderWeaponEquipped )
			f26_arg0.MinusButton:completeAnimation()
			f26_arg0.MinusButton:setAlpha( 0 )
			f26_arg0.clipFinished( f26_arg0.MinusButton )
			f26_arg0.PlusButton:completeAnimation()
			f26_arg0.PlusButton:setAlpha( 0.75 )
			f26_arg0.clipFinished( f26_arg0.PlusButton )
		end,
		Focus = function ( f27_arg0, f27_arg1 )
			f27_arg0:__resetProperties()
			f27_arg0:setupElementClipCounter( 7 )
			f27_arg0.Background:completeAnimation()
			f27_arg0.Background:setAlpha( 0.3 )
			f27_arg0.clipFinished( f27_arg0.Background )
			f27_arg0.NineSliceShaderImage:completeAnimation()
			f27_arg0.NineSliceShaderImage:setAlpha( 1 )
			f27_arg0.clipFinished( f27_arg0.NineSliceShaderImage )
			f27_arg0.HeaderWeapon:completeAnimation()
			f27_arg0.HeaderWeapon:setRGB( 0.73, 0.72, 0.64 )
			f27_arg0.HeaderWeapon:setAlpha( 1 )
			f27_arg0.clipFinished( f27_arg0.HeaderWeapon )
			f27_arg0.HeaderWeaponEquipped:completeAnimation()
			f27_arg0.HeaderWeaponEquipped:setAlpha( 0 )
			f27_arg0.clipFinished( f27_arg0.HeaderWeaponEquipped )
			f27_arg0.MinusButton:completeAnimation()
			f27_arg0.MinusButton:setLeftRight( 0, 0, 12, 23 )
			f27_arg0.MinusButton:setRGB( 0, 0, 0 )
			f27_arg0.MinusButton:setAlpha( 0 )
			f27_arg0.clipFinished( f27_arg0.MinusButton )
			f27_arg0.PlusButton:completeAnimation()
			f27_arg0.PlusButton:setRGB( 0.73, 0.72, 0.64 )
			f27_arg0.PlusButton:setAlpha( 1 )
			f27_arg0.clipFinished( f27_arg0.PlusButton )
			f27_arg0.FrameSelected:completeAnimation()
			f27_arg0.FrameSelected:setAlpha( 1 )
			f27_arg0.clipFinished( f27_arg0.FrameSelected )
		end,
		GainFocus = function ( f28_arg0, f28_arg1 )
			f28_arg0:__resetProperties()
			f28_arg0:setupElementClipCounter( 7 )
			local f28_local0 = function ( f29_arg0 )
				f28_arg0.Background:beginAnimation( 200 )
				f28_arg0.Background:setAlpha( 0.3 )
				f28_arg0.Background:registerEventHandler( "interrupted_keyframe", f28_arg0.clipInterrupted )
				f28_arg0.Background:registerEventHandler( "transition_complete_keyframe", f28_arg0.clipFinished )
			end
			
			f28_arg0.Background:completeAnimation()
			f28_arg0.Background:setAlpha( 0 )
			f28_local0( f28_arg0.Background )
			f28_arg0.NineSliceShaderImage:completeAnimation()
			f28_arg0.NineSliceShaderImage:setAlpha( 1 )
			f28_arg0.clipFinished( f28_arg0.NineSliceShaderImage )
			local f28_local1 = function ( f30_arg0 )
				f28_arg0.HeaderWeapon:beginAnimation( 200 )
				f28_arg0.HeaderWeapon:setRGB( 0.73, 0.72, 0.64 )
				f28_arg0.HeaderWeapon:registerEventHandler( "interrupted_keyframe", f28_arg0.clipInterrupted )
				f28_arg0.HeaderWeapon:registerEventHandler( "transition_complete_keyframe", f28_arg0.clipFinished )
			end
			
			f28_arg0.HeaderWeapon:completeAnimation()
			f28_arg0.HeaderWeapon:setRGB( 0.66, 0.63, 0.52 )
			f28_arg0.HeaderWeapon:setAlpha( 1 )
			f28_local1( f28_arg0.HeaderWeapon )
			f28_arg0.HeaderWeaponEquipped:completeAnimation()
			f28_arg0.HeaderWeaponEquipped:setAlpha( 0 )
			f28_arg0.clipFinished( f28_arg0.HeaderWeaponEquipped )
			local f28_local2 = function ( f31_arg0 )
				f28_arg0.MinusButton:beginAnimation( 200 )
				f28_arg0.MinusButton:setLeftRight( 0, 0, 12, 23 )
				f28_arg0.MinusButton:registerEventHandler( "interrupted_keyframe", f28_arg0.clipInterrupted )
				f28_arg0.MinusButton:registerEventHandler( "transition_complete_keyframe", f28_arg0.clipFinished )
			end
			
			f28_arg0.MinusButton:completeAnimation()
			f28_arg0.MinusButton:setLeftRight( 1, 1, -30, 0 )
			f28_arg0.MinusButton:setRGB( 0, 0, 0 )
			f28_arg0.MinusButton:setAlpha( 0 )
			f28_local2( f28_arg0.MinusButton )
			local f28_local3 = function ( f32_arg0 )
				f28_arg0.PlusButton:beginAnimation( 200 )
				f28_arg0.PlusButton:setRGB( 0.73, 0.72, 0.64 )
				f28_arg0.PlusButton:setAlpha( 1 )
				f28_arg0.PlusButton:registerEventHandler( "interrupted_keyframe", f28_arg0.clipInterrupted )
				f28_arg0.PlusButton:registerEventHandler( "transition_complete_keyframe", f28_arg0.clipFinished )
			end
			
			f28_arg0.PlusButton:completeAnimation()
			f28_arg0.PlusButton:setRGB( 0.66, 0.63, 0.52 )
			f28_arg0.PlusButton:setAlpha( 0.75 )
			f28_local3( f28_arg0.PlusButton )
			local f28_local4 = function ( f33_arg0 )
				f28_arg0.FrameSelected:beginAnimation( 200 )
				f28_arg0.FrameSelected:setAlpha( 1 )
				f28_arg0.FrameSelected:registerEventHandler( "interrupted_keyframe", f28_arg0.clipInterrupted )
				f28_arg0.FrameSelected:registerEventHandler( "transition_complete_keyframe", f28_arg0.clipFinished )
			end
			
			f28_arg0.FrameSelected:completeAnimation()
			f28_arg0.FrameSelected:setAlpha( 0 )
			f28_local4( f28_arg0.FrameSelected )
		end,
		LoseFocus = function ( f34_arg0, f34_arg1 )
			f34_arg0:__resetProperties()
			f34_arg0:setupElementClipCounter( 7 )
			local f34_local0 = function ( f35_arg0 )
				f34_arg0.Background:beginAnimation( 200 )
				f34_arg0.Background:setAlpha( 0 )
				f34_arg0.Background:registerEventHandler( "interrupted_keyframe", f34_arg0.clipInterrupted )
				f34_arg0.Background:registerEventHandler( "transition_complete_keyframe", f34_arg0.clipFinished )
			end
			
			f34_arg0.Background:completeAnimation()
			f34_arg0.Background:setAlpha( 0.3 )
			f34_local0( f34_arg0.Background )
			f34_arg0.NineSliceShaderImage:completeAnimation()
			f34_arg0.NineSliceShaderImage:setAlpha( 1 )
			f34_arg0.clipFinished( f34_arg0.NineSliceShaderImage )
			local f34_local1 = function ( f36_arg0 )
				f34_arg0.HeaderWeapon:beginAnimation( 200 )
				f34_arg0.HeaderWeapon:setRGB( 0.66, 0.63, 0.52 )
				f34_arg0.HeaderWeapon:registerEventHandler( "interrupted_keyframe", f34_arg0.clipInterrupted )
				f34_arg0.HeaderWeapon:registerEventHandler( "transition_complete_keyframe", f34_arg0.clipFinished )
			end
			
			f34_arg0.HeaderWeapon:completeAnimation()
			f34_arg0.HeaderWeapon:setRGB( 0.73, 0.72, 0.64 )
			f34_arg0.HeaderWeapon:setAlpha( 1 )
			f34_local1( f34_arg0.HeaderWeapon )
			f34_arg0.HeaderWeaponEquipped:completeAnimation()
			f34_arg0.HeaderWeaponEquipped:setAlpha( 0 )
			f34_arg0.clipFinished( f34_arg0.HeaderWeaponEquipped )
			local f34_local2 = function ( f37_arg0 )
				f34_arg0.MinusButton:beginAnimation( 200 )
				f34_arg0.MinusButton:setLeftRight( 1, 1, -30, 0 )
				f34_arg0.MinusButton:registerEventHandler( "interrupted_keyframe", f34_arg0.clipInterrupted )
				f34_arg0.MinusButton:registerEventHandler( "transition_complete_keyframe", f34_arg0.clipFinished )
			end
			
			f34_arg0.MinusButton:completeAnimation()
			f34_arg0.MinusButton:setLeftRight( 0, 0, 12, 23 )
			f34_arg0.MinusButton:setRGB( 0, 0, 0 )
			f34_arg0.MinusButton:setAlpha( 0 )
			f34_local2( f34_arg0.MinusButton )
			local f34_local3 = function ( f38_arg0 )
				f34_arg0.PlusButton:beginAnimation( 200 )
				f34_arg0.PlusButton:setRGB( 0.66, 0.63, 0.52 )
				f34_arg0.PlusButton:setAlpha( 0.75 )
				f34_arg0.PlusButton:registerEventHandler( "interrupted_keyframe", f34_arg0.clipInterrupted )
				f34_arg0.PlusButton:registerEventHandler( "transition_complete_keyframe", f34_arg0.clipFinished )
			end
			
			f34_arg0.PlusButton:completeAnimation()
			f34_arg0.PlusButton:setRGB( 0.73, 0.72, 0.64 )
			f34_arg0.PlusButton:setAlpha( 1 )
			f34_local3( f34_arg0.PlusButton )
			local f34_local4 = function ( f39_arg0 )
				f34_arg0.FrameSelected:beginAnimation( 200 )
				f34_arg0.FrameSelected:setAlpha( 0 )
				f34_arg0.FrameSelected:registerEventHandler( "interrupted_keyframe", f34_arg0.clipInterrupted )
				f34_arg0.FrameSelected:registerEventHandler( "transition_complete_keyframe", f34_arg0.clipFinished )
			end
			
			f34_arg0.FrameSelected:completeAnimation()
			f34_arg0.FrameSelected:setAlpha( 1 )
			f34_local4( f34_arg0.FrameSelected )
		end
	}
}
CoD.StartMenu_Inventory_SwitchWeaponTab_Activate.__onClose = function ( f40_arg0 )
	f40_arg0.SwitchWeaponImage:close()
end

