require( "ui/uieditor/widgets/blackmarket/bm_lock" )
require( "ui/uieditor/widgets/commonbuttonoutline" )

CoD.CamoSlotInternal = InheritFrom( LUI.UIElement )
CoD.CamoSlotInternal.__defaultWidth = 128
CoD.CamoSlotInternal.__defaultHeight = 89
CoD.CamoSlotInternal.new = function ( f1_arg0, f1_arg1, f1_arg2, f1_arg3, f1_arg4, f1_arg5, f1_arg6, f1_arg7, f1_arg8, f1_arg9 )
	local self = LUI.UIElement.new( f1_arg2, f1_arg3, f1_arg4, f1_arg5, f1_arg6, f1_arg7, f1_arg8, f1_arg9 )
	self:setClass( CoD.CamoSlotInternal )
	self.id = "CamoSlotInternal"
	self.soundSet = "FrontendMain"
	self.onlyChildrenFocusable = true
	self.anyChildUsesUpdateState = true
	f1_arg0:addElementToPendingUpdateStateList( self )
	
	local Image = LUI.UIImage.new( 0, 1, 0, 0, 0, 1, 0, 0 )
	Image:setMaterial( LUI.UIImage.GetCachedMaterial( 0xA02C44161370F6D ) )
	Image:setShaderVector( 0, 0, 0, 0, 0 )
	Image:setShaderVector( 1, 1, 1, 0, 0 )
	Image:setShaderVector( 2, 0, 0, 0, 0 )
	Image:linkToElementModel( self, "image", true, function ( model )
		local f2_local0 = model:get()
		if f2_local0 ~= nil then
			Image:setImage( RegisterImage( f2_local0 ) )
		end
	end )
	self:addElement( Image )
	self.Image = Image
	
	local DarkenedOverlay = LUI.UIImage.new( 0, 1, 0, 0, 0, 1, 0, 0 )
	DarkenedOverlay:setRGB( 0, 0, 0 )
	DarkenedOverlay:setAlpha( 0 )
	self:addElement( DarkenedOverlay )
	self.DarkenedOverlay = DarkenedOverlay
	
	local ProgressBarBG = LUI.UIImage.new( 0, 1, 0, 0, 1, 1, -62, 1 )
	ProgressBarBG:setRGB( ColorSet.Title.r, ColorSet.Title.g, ColorSet.Title.b )
	ProgressBarBG:setAlpha( 0 )
	ProgressBarBG:setImage( RegisterImage( 0x136CEF79E2CB178 ) )
	self:addElement( ProgressBarBG )
	self.ProgressBarBG = ProgressBarBG
	
	local ProgressBar = LUI.UIImage.new( 0, 1, 0, 0, 1, 1, -62, 1 )
	ProgressBar:setAlpha( 0 )
	ProgressBar:setImage( RegisterImage( 0xF090ADEC8D52EF0 ) )
	ProgressBar:setMaterial( LUI.UIImage.GetCachedMaterial( 0x316E67E1DF2198E ) )
	ProgressBar:setShaderVector( 1, 0, 0, 0, 0 )
	ProgressBar:setShaderVector( 2, 1, 0, 0, 0 )
	ProgressBar:setShaderVector( 3, 0, 0, 0, 0 )
	ProgressBar:setShaderVector( 4, 0, 0, 0, 0 )
	ProgressBar:linkToElementModel( self, "unlockProgressAndTarget", true, function ( model )
		local f3_local0 = model:get()
		if f3_local0 ~= nil then
			ProgressBar:setShaderVector( 0, CoD.WeaponOptionsUtility.GetWeaponOptionProgress( f1_arg0, f1_arg1, CoD.GetVectorComponentFromString( f3_local0, 1 ), CoD.GetVectorComponentFromString( f3_local0, 2 ), CoD.GetVectorComponentFromString( f3_local0, 3 ), CoD.GetVectorComponentFromString( f3_local0, 4 ) ) )
		end
	end )
	self:addElement( ProgressBar )
	self.ProgressBar = ProgressBar
	
	local CommonButtonOutline = CoD.CommonButtonOutline.new( f1_arg0, f1_arg1, 0, 1, -1, 1, 0, 1, 0, 0 )
	self:addElement( CommonButtonOutline )
	self.CommonButtonOutline = CommonButtonOutline
	
	local EquippedMarkerBG = LUI.UIImage.new( 1, 1, -35, 9, 0, 0, -8, 36 )
	EquippedMarkerBG:setAlpha( 0 )
	EquippedMarkerBG:setZoom( 4 )
	EquippedMarkerBG:setImage( RegisterImage( 0x7AF532D84DE505A ) )
	EquippedMarkerBG:setMaterial( LUI.UIImage.GetCachedMaterial( 0x4E6CE42E0799F57 ) )
	self:addElement( EquippedMarkerBG )
	self.EquippedMarkerBG = EquippedMarkerBG
	
	local EquippedMarkerTick = LUI.UIImage.new( 1, 1, -35, 9, 0, 0, -8, 36 )
	EquippedMarkerTick:setAlpha( 0 )
	EquippedMarkerTick:setZoom( 4 )
	EquippedMarkerTick:setImage( RegisterImage( 0x9A8B26C9B001758 ) )
	self:addElement( EquippedMarkerTick )
	self.EquippedMarkerTick = EquippedMarkerTick
	
	local LockedX = LUI.UIImage.new( 0, 1, 0, 0, 0, 1, 0, 0 )
	LockedX:setRGB( ColorSet.Title.r, ColorSet.Title.g, ColorSet.Title.b )
	LockedX:setAlpha( 0 )
	LockedX:setImage( RegisterImage( 0xCE50842B84CCD5D ) )
	self:addElement( LockedX )
	self.LockedX = LockedX
	
	local LockedIcon = LUI.UIImage.new( 0.5, 0.5, -15, 15, 0.5, 0.5, -15, 15 )
	LockedIcon:setAlpha( 0 )
	LockedIcon:setImage( RegisterImage( 0xB8AD8D12CEB707D ) )
	self:addElement( LockedIcon )
	self.LockedIcon = LockedIcon
	
	local BMLock = CoD.BM_Lock.new( f1_arg0, f1_arg1, 0.5, 0.5, -24, 24, 0.5, 0.5, -24, 24 )
	BMLock:setAlpha( 0 )
	BMLock:setScale( 0.6, 0.6 )
	self:addElement( BMLock )
	self.BMLock = BMLock
	
	local PaintCanImage = LUI.UIImage.new( 0.5, 0.5, -24, 24, 0.5, 0.5, -24, 24 )
	PaintCanImage:setAlpha( 0 )
	PaintCanImage:setImage( RegisterImage( 0xB808223FCD4471D ) )
	self:addElement( PaintCanImage )
	self.PaintCanImage = PaintCanImage
	
	CommonButtonOutline.id = "CommonButtonOutline"
	self.__defaultFocus = CommonButtonOutline
	LUI.OverrideFunction_CallOriginalSecond( self, "close", self.__onClose )
	
	if PostLoadFunc then
		PostLoadFunc( self, f1_arg1, f1_arg0 )
	end
	
	return self
end

CoD.CamoSlotInternal.__resetProperties = function ( f4_arg0 )
	f4_arg0.LockedIcon:completeAnimation()
	f4_arg0.ProgressBarBG:completeAnimation()
	f4_arg0.ProgressBar:completeAnimation()
	f4_arg0.DarkenedOverlay:completeAnimation()
	f4_arg0.Image:completeAnimation()
	f4_arg0.BMLock:completeAnimation()
	f4_arg0.LockedX:completeAnimation()
	f4_arg0.PaintCanImage:completeAnimation()
	f4_arg0.LockedIcon:setAlpha( 0 )
	f4_arg0.LockedIcon:setZoom( 0 )
	f4_arg0.ProgressBarBG:setAlpha( 0 )
	f4_arg0.ProgressBar:setAlpha( 0 )
	f4_arg0.DarkenedOverlay:setAlpha( 0 )
	f4_arg0.Image:setRGB( 1, 1, 1 )
	f4_arg0.BMLock:setAlpha( 0 )
	f4_arg0.LockedX:setAlpha( 0 )
	f4_arg0.PaintCanImage:setLeftRight( 0.5, 0.5, -24, 24 )
	f4_arg0.PaintCanImage:setTopBottom( 0.5, 0.5, -24, 24 )
	f4_arg0.PaintCanImage:setAlpha( 0 )
end

CoD.CamoSlotInternal.__clipsPerState = {
	DefaultState = {
		DefaultClip = function ( f5_arg0, f5_arg1 )
			f5_arg0:__resetProperties()
			f5_arg0:setupElementClipCounter( 0 )
		end,
		ChildFocus = function ( f6_arg0, f6_arg1 )
			f6_arg0:__resetProperties()
			f6_arg0:setupElementClipCounter( 1 )
			f6_arg0.LockedIcon:completeAnimation()
			f6_arg0.LockedIcon:setZoom( 0 )
			f6_arg0.clipFinished( f6_arg0.LockedIcon )
		end,
		GainChildFocus = function ( f7_arg0, f7_arg1 )
			f7_arg0:__resetProperties()
			f7_arg0:setupElementClipCounter( 1 )
			f7_arg0.LockedIcon:completeAnimation()
			f7_arg0.LockedIcon:setZoom( 0 )
			f7_arg0.clipFinished( f7_arg0.LockedIcon )
		end,
		LoseChildFocus = function ( f8_arg0, f8_arg1 )
			f8_arg0:__resetProperties()
			f8_arg0:setupElementClipCounter( 1 )
			f8_arg0.LockedIcon:completeAnimation()
			f8_arg0.LockedIcon:setZoom( 0 )
			f8_arg0.clipFinished( f8_arg0.LockedIcon )
		end
	},
	LootLocked = {
		DefaultClip = function ( f9_arg0, f9_arg1 )
			f9_arg0:__resetProperties()
			f9_arg0:setupElementClipCounter( 5 )
			f9_arg0.Image:completeAnimation()
			f9_arg0.Image:setRGB( 0.29, 0.29, 0.29 )
			f9_arg0.clipFinished( f9_arg0.Image )
			f9_arg0.DarkenedOverlay:completeAnimation()
			f9_arg0.DarkenedOverlay:setAlpha( 0.5 )
			f9_arg0.clipFinished( f9_arg0.DarkenedOverlay )
			f9_arg0.ProgressBarBG:completeAnimation()
			f9_arg0.ProgressBarBG:setAlpha( 1 )
			f9_arg0.clipFinished( f9_arg0.ProgressBarBG )
			f9_arg0.ProgressBar:completeAnimation()
			f9_arg0.ProgressBar:setAlpha( 1 )
			f9_arg0.clipFinished( f9_arg0.ProgressBar )
			f9_arg0.BMLock:completeAnimation()
			f9_arg0.BMLock:setAlpha( 0.5 )
			f9_arg0.clipFinished( f9_arg0.BMLock )
		end,
		ChildFocus = function ( f10_arg0, f10_arg1 )
			f10_arg0:__resetProperties()
			f10_arg0:setupElementClipCounter( 5 )
			f10_arg0.Image:completeAnimation()
			f10_arg0.Image:setRGB( 0.29, 0.29, 0.29 )
			f10_arg0.clipFinished( f10_arg0.Image )
			f10_arg0.DarkenedOverlay:completeAnimation()
			f10_arg0.DarkenedOverlay:setAlpha( 0.5 )
			f10_arg0.clipFinished( f10_arg0.DarkenedOverlay )
			f10_arg0.ProgressBarBG:completeAnimation()
			f10_arg0.ProgressBarBG:setAlpha( 1 )
			f10_arg0.clipFinished( f10_arg0.ProgressBarBG )
			f10_arg0.ProgressBar:completeAnimation()
			f10_arg0.ProgressBar:setAlpha( 1 )
			f10_arg0.clipFinished( f10_arg0.ProgressBar )
			f10_arg0.BMLock:completeAnimation()
			f10_arg0.BMLock:setAlpha( 0.75 )
			f10_arg0.clipFinished( f10_arg0.BMLock )
		end,
		ChildGainFocus = function ( f11_arg0, f11_arg1 )
			f11_arg0:__resetProperties()
			f11_arg0:setupElementClipCounter( 5 )
			f11_arg0.Image:completeAnimation()
			f11_arg0.Image:setRGB( 0.29, 0.29, 0.29 )
			f11_arg0.clipFinished( f11_arg0.Image )
			f11_arg0.DarkenedOverlay:completeAnimation()
			f11_arg0.DarkenedOverlay:setAlpha( 0.5 )
			f11_arg0.clipFinished( f11_arg0.DarkenedOverlay )
			f11_arg0.ProgressBarBG:completeAnimation()
			f11_arg0.ProgressBarBG:setAlpha( 1 )
			f11_arg0.clipFinished( f11_arg0.ProgressBarBG )
			f11_arg0.ProgressBar:completeAnimation()
			f11_arg0.ProgressBar:setAlpha( 1 )
			f11_arg0.clipFinished( f11_arg0.ProgressBar )
			local f11_local0 = function ( f12_arg0 )
				f11_arg0.BMLock:beginAnimation( 200 )
				f11_arg0.BMLock:setAlpha( 0.75 )
				f11_arg0.BMLock:registerEventHandler( "interrupted_keyframe", f11_arg0.clipInterrupted )
				f11_arg0.BMLock:registerEventHandler( "transition_complete_keyframe", f11_arg0.clipFinished )
			end
			
			f11_arg0.BMLock:completeAnimation()
			f11_arg0.BMLock:setAlpha( 0.5 )
			f11_local0( f11_arg0.BMLock )
		end,
		LoseChildFocus = function ( f13_arg0, f13_arg1 )
			f13_arg0:__resetProperties()
			f13_arg0:setupElementClipCounter( 5 )
			f13_arg0.Image:completeAnimation()
			f13_arg0.Image:setRGB( 0.29, 0.29, 0.29 )
			f13_arg0.clipFinished( f13_arg0.Image )
			f13_arg0.DarkenedOverlay:completeAnimation()
			f13_arg0.DarkenedOverlay:setAlpha( 0.5 )
			f13_arg0.clipFinished( f13_arg0.DarkenedOverlay )
			f13_arg0.ProgressBarBG:completeAnimation()
			f13_arg0.ProgressBarBG:setAlpha( 1 )
			f13_arg0.clipFinished( f13_arg0.ProgressBarBG )
			f13_arg0.ProgressBar:completeAnimation()
			f13_arg0.ProgressBar:setAlpha( 1 )
			f13_arg0.clipFinished( f13_arg0.ProgressBar )
			local f13_local0 = function ( f14_arg0 )
				f13_arg0.BMLock:beginAnimation( 220 )
				f13_arg0.BMLock:setAlpha( 0.5 )
				f13_arg0.BMLock:registerEventHandler( "interrupted_keyframe", f13_arg0.clipInterrupted )
				f13_arg0.BMLock:registerEventHandler( "transition_complete_keyframe", f13_arg0.clipFinished )
			end
			
			f13_arg0.BMLock:completeAnimation()
			f13_arg0.BMLock:setAlpha( 0.75 )
			f13_local0( f13_arg0.BMLock )
		end
	},
	PaintCanLocked = {
		DefaultClip = function ( f15_arg0, f15_arg1 )
			f15_arg0:__resetProperties()
			f15_arg0:setupElementClipCounter( 6 )
			f15_arg0.Image:completeAnimation()
			f15_arg0.Image:setRGB( 0.29, 0.29, 0.29 )
			f15_arg0.clipFinished( f15_arg0.Image )
			f15_arg0.DarkenedOverlay:completeAnimation()
			f15_arg0.DarkenedOverlay:setAlpha( 0 )
			f15_arg0.clipFinished( f15_arg0.DarkenedOverlay )
			f15_arg0.ProgressBarBG:completeAnimation()
			f15_arg0.ProgressBarBG:setAlpha( 0 )
			f15_arg0.clipFinished( f15_arg0.ProgressBarBG )
			f15_arg0.ProgressBar:completeAnimation()
			f15_arg0.ProgressBar:setAlpha( 0 )
			f15_arg0.clipFinished( f15_arg0.ProgressBar )
			f15_arg0.LockedX:completeAnimation()
			f15_arg0.LockedX:setAlpha( 0 )
			f15_arg0.clipFinished( f15_arg0.LockedX )
			f15_arg0.PaintCanImage:completeAnimation()
			f15_arg0.PaintCanImage:setLeftRight( 0.5, 0.5, -40, 40 )
			f15_arg0.PaintCanImage:setTopBottom( 0.5, 0.5, -40, 40 )
			f15_arg0.PaintCanImage:setAlpha( 0.5 )
			f15_arg0.clipFinished( f15_arg0.PaintCanImage )
		end,
		ChildFocus = function ( f16_arg0, f16_arg1 )
			f16_arg0:__resetProperties()
			f16_arg0:setupElementClipCounter( 4 )
			f16_arg0.Image:completeAnimation()
			f16_arg0.Image:setRGB( 0.47, 0.47, 0.47 )
			f16_arg0.clipFinished( f16_arg0.Image )
			f16_arg0.DarkenedOverlay:completeAnimation()
			f16_arg0.DarkenedOverlay:setAlpha( 0 )
			f16_arg0.clipFinished( f16_arg0.DarkenedOverlay )
			f16_arg0.LockedX:completeAnimation()
			f16_arg0.LockedX:setAlpha( 0 )
			f16_arg0.clipFinished( f16_arg0.LockedX )
			f16_arg0.PaintCanImage:completeAnimation()
			f16_arg0.PaintCanImage:setLeftRight( 0.5, 0.5, -40, 40 )
			f16_arg0.PaintCanImage:setTopBottom( 0.5, 0.5, -40, 40 )
			f16_arg0.PaintCanImage:setAlpha( 1 )
			f16_arg0.clipFinished( f16_arg0.PaintCanImage )
		end,
		ChildGainFocus = function ( f17_arg0, f17_arg1 )
			f17_arg0:__resetProperties()
			f17_arg0:setupElementClipCounter( 4 )
			local f17_local0 = function ( f18_arg0 )
				f17_arg0.Image:beginAnimation( 200 )
				f17_arg0.Image:setRGB( 0.47, 0.47, 0.47 )
				f17_arg0.Image:registerEventHandler( "interrupted_keyframe", f17_arg0.clipInterrupted )
				f17_arg0.Image:registerEventHandler( "transition_complete_keyframe", f17_arg0.clipFinished )
			end
			
			f17_arg0.Image:completeAnimation()
			f17_arg0.Image:setRGB( 0.29, 0.29, 0.29 )
			f17_local0( f17_arg0.Image )
			f17_arg0.DarkenedOverlay:completeAnimation()
			f17_arg0.DarkenedOverlay:setAlpha( 0 )
			f17_arg0.clipFinished( f17_arg0.DarkenedOverlay )
			f17_arg0.LockedX:completeAnimation()
			f17_arg0.LockedX:setAlpha( 0 )
			f17_arg0.clipFinished( f17_arg0.LockedX )
			local f17_local1 = function ( f19_arg0 )
				f17_arg0.PaintCanImage:beginAnimation( 200 )
				f17_arg0.PaintCanImage:setAlpha( 1 )
				f17_arg0.PaintCanImage:registerEventHandler( "interrupted_keyframe", f17_arg0.clipInterrupted )
				f17_arg0.PaintCanImage:registerEventHandler( "transition_complete_keyframe", f17_arg0.clipFinished )
			end
			
			f17_arg0.PaintCanImage:completeAnimation()
			f17_arg0.PaintCanImage:setLeftRight( 0.5, 0.5, -40, 40 )
			f17_arg0.PaintCanImage:setTopBottom( 0.5, 0.5, -40, 40 )
			f17_arg0.PaintCanImage:setAlpha( 0.5 )
			f17_local1( f17_arg0.PaintCanImage )
		end,
		LoseChildFocus = function ( f20_arg0, f20_arg1 )
			f20_arg0:__resetProperties()
			f20_arg0:setupElementClipCounter( 4 )
			local f20_local0 = function ( f21_arg0 )
				f20_arg0.Image:beginAnimation( 220 )
				f20_arg0.Image:setRGB( 0.29, 0.29, 0.29 )
				f20_arg0.Image:registerEventHandler( "interrupted_keyframe", f20_arg0.clipInterrupted )
				f20_arg0.Image:registerEventHandler( "transition_complete_keyframe", f20_arg0.clipFinished )
			end
			
			f20_arg0.Image:completeAnimation()
			f20_arg0.Image:setRGB( 0.47, 0.47, 0.47 )
			f20_local0( f20_arg0.Image )
			f20_arg0.DarkenedOverlay:completeAnimation()
			f20_arg0.DarkenedOverlay:setAlpha( 0 )
			f20_arg0.clipFinished( f20_arg0.DarkenedOverlay )
			f20_arg0.LockedX:completeAnimation()
			f20_arg0.LockedX:setAlpha( 0 )
			f20_arg0.clipFinished( f20_arg0.LockedX )
			local f20_local1 = function ( f22_arg0 )
				f20_arg0.PaintCanImage:beginAnimation( 220 )
				f20_arg0.PaintCanImage:setAlpha( 0.5 )
				f20_arg0.PaintCanImage:registerEventHandler( "interrupted_keyframe", f20_arg0.clipInterrupted )
				f20_arg0.PaintCanImage:registerEventHandler( "transition_complete_keyframe", f20_arg0.clipFinished )
			end
			
			f20_arg0.PaintCanImage:completeAnimation()
			f20_arg0.PaintCanImage:setLeftRight( 0.5, 0.5, -40, 40 )
			f20_arg0.PaintCanImage:setTopBottom( 0.5, 0.5, -40, 40 )
			f20_arg0.PaintCanImage:setAlpha( 1 )
			f20_local1( f20_arg0.PaintCanImage )
		end
	},
	Locked = {
		DefaultClip = function ( f23_arg0, f23_arg1 )
			f23_arg0:__resetProperties()
			f23_arg0:setupElementClipCounter( 6 )
			f23_arg0.Image:completeAnimation()
			f23_arg0.Image:setRGB( 0.29, 0.29, 0.29 )
			f23_arg0.clipFinished( f23_arg0.Image )
			f23_arg0.DarkenedOverlay:completeAnimation()
			f23_arg0.DarkenedOverlay:setAlpha( 0.5 )
			f23_arg0.clipFinished( f23_arg0.DarkenedOverlay )
			f23_arg0.ProgressBarBG:completeAnimation()
			f23_arg0.ProgressBarBG:setAlpha( 1 )
			f23_arg0.clipFinished( f23_arg0.ProgressBarBG )
			f23_arg0.ProgressBar:completeAnimation()
			f23_arg0.ProgressBar:setAlpha( 1 )
			f23_arg0.clipFinished( f23_arg0.ProgressBar )
			f23_arg0.LockedX:completeAnimation()
			f23_arg0.LockedX:setAlpha( 0.66 )
			f23_arg0.clipFinished( f23_arg0.LockedX )
			f23_arg0.LockedIcon:completeAnimation()
			f23_arg0.LockedIcon:setAlpha( 0.33 )
			f23_arg0.clipFinished( f23_arg0.LockedIcon )
		end,
		ChildFocus = function ( f24_arg0, f24_arg1 )
			f24_arg0:__resetProperties()
			f24_arg0:setupElementClipCounter( 6 )
			f24_arg0.Image:completeAnimation()
			f24_arg0.Image:setRGB( 0.29, 0.29, 0.29 )
			f24_arg0.clipFinished( f24_arg0.Image )
			f24_arg0.DarkenedOverlay:completeAnimation()
			f24_arg0.DarkenedOverlay:setAlpha( 0.5 )
			f24_arg0.clipFinished( f24_arg0.DarkenedOverlay )
			f24_arg0.ProgressBarBG:completeAnimation()
			f24_arg0.ProgressBarBG:setAlpha( 1 )
			f24_arg0.clipFinished( f24_arg0.ProgressBarBG )
			f24_arg0.ProgressBar:completeAnimation()
			f24_arg0.ProgressBar:setAlpha( 1 )
			f24_arg0.clipFinished( f24_arg0.ProgressBar )
			f24_arg0.LockedX:completeAnimation()
			f24_arg0.LockedX:setAlpha( 1 )
			f24_arg0.clipFinished( f24_arg0.LockedX )
			f24_arg0.LockedIcon:completeAnimation()
			f24_arg0.LockedIcon:setAlpha( 0.75 )
			f24_arg0.clipFinished( f24_arg0.LockedIcon )
		end,
		ChildGainFocus = function ( f25_arg0, f25_arg1 )
			f25_arg0:__resetProperties()
			f25_arg0:setupElementClipCounter( 6 )
			f25_arg0.Image:completeAnimation()
			f25_arg0.Image:setRGB( 0.29, 0.29, 0.29 )
			f25_arg0.clipFinished( f25_arg0.Image )
			f25_arg0.DarkenedOverlay:completeAnimation()
			f25_arg0.DarkenedOverlay:setAlpha( 0.5 )
			f25_arg0.clipFinished( f25_arg0.DarkenedOverlay )
			f25_arg0.ProgressBarBG:completeAnimation()
			f25_arg0.ProgressBarBG:setAlpha( 1 )
			f25_arg0.clipFinished( f25_arg0.ProgressBarBG )
			f25_arg0.ProgressBar:completeAnimation()
			f25_arg0.ProgressBar:setAlpha( 1 )
			f25_arg0.clipFinished( f25_arg0.ProgressBar )
			local f25_local0 = function ( f26_arg0 )
				f25_arg0.LockedX:beginAnimation( 200 )
				f25_arg0.LockedX:setAlpha( 1 )
				f25_arg0.LockedX:registerEventHandler( "interrupted_keyframe", f25_arg0.clipInterrupted )
				f25_arg0.LockedX:registerEventHandler( "transition_complete_keyframe", f25_arg0.clipFinished )
			end
			
			f25_arg0.LockedX:completeAnimation()
			f25_arg0.LockedX:setAlpha( 0.66 )
			f25_local0( f25_arg0.LockedX )
			local f25_local1 = function ( f27_arg0 )
				f25_arg0.LockedIcon:beginAnimation( 200 )
				f25_arg0.LockedIcon:setAlpha( 0.75 )
				f25_arg0.LockedIcon:registerEventHandler( "interrupted_keyframe", f25_arg0.clipInterrupted )
				f25_arg0.LockedIcon:registerEventHandler( "transition_complete_keyframe", f25_arg0.clipFinished )
			end
			
			f25_arg0.LockedIcon:completeAnimation()
			f25_arg0.LockedIcon:setAlpha( 0.33 )
			f25_local1( f25_arg0.LockedIcon )
		end,
		LoseChildFocus = function ( f28_arg0, f28_arg1 )
			f28_arg0:__resetProperties()
			f28_arg0:setupElementClipCounter( 6 )
			f28_arg0.Image:completeAnimation()
			f28_arg0.Image:setRGB( 0.29, 0.29, 0.29 )
			f28_arg0.clipFinished( f28_arg0.Image )
			f28_arg0.DarkenedOverlay:completeAnimation()
			f28_arg0.DarkenedOverlay:setAlpha( 0.5 )
			f28_arg0.clipFinished( f28_arg0.DarkenedOverlay )
			f28_arg0.ProgressBarBG:completeAnimation()
			f28_arg0.ProgressBarBG:setAlpha( 1 )
			f28_arg0.clipFinished( f28_arg0.ProgressBarBG )
			f28_arg0.ProgressBar:completeAnimation()
			f28_arg0.ProgressBar:setAlpha( 1 )
			f28_arg0.clipFinished( f28_arg0.ProgressBar )
			local f28_local0 = function ( f29_arg0 )
				f28_arg0.LockedX:beginAnimation( 220 )
				f28_arg0.LockedX:setAlpha( 0.66 )
				f28_arg0.LockedX:registerEventHandler( "interrupted_keyframe", f28_arg0.clipInterrupted )
				f28_arg0.LockedX:registerEventHandler( "transition_complete_keyframe", f28_arg0.clipFinished )
			end
			
			f28_arg0.LockedX:completeAnimation()
			f28_arg0.LockedX:setAlpha( 1 )
			f28_local0( f28_arg0.LockedX )
			local f28_local1 = function ( f30_arg0 )
				f28_arg0.LockedIcon:beginAnimation( 220 )
				f28_arg0.LockedIcon:setAlpha( 0.33 )
				f28_arg0.LockedIcon:registerEventHandler( "interrupted_keyframe", f28_arg0.clipInterrupted )
				f28_arg0.LockedIcon:registerEventHandler( "transition_complete_keyframe", f28_arg0.clipFinished )
			end
			
			f28_arg0.LockedIcon:completeAnimation()
			f28_arg0.LockedIcon:setAlpha( 0.75 )
			f28_local1( f28_arg0.LockedIcon )
		end
	}
}
CoD.CamoSlotInternal.__onClose = function ( f31_arg0 )
	f31_arg0.Image:close()
	f31_arg0.ProgressBar:close()
	f31_arg0.CommonButtonOutline:close()
	f31_arg0.BMLock:close()
end

