require( "ui/uieditor/widgets/common/commonheader" )
require( "x64:206831d495ffd0f" )
require( "x64:5751aa0076f64f0" )

CoD.HighValueOperatives = InheritFrom( LUI.UIElement )
CoD.HighValueOperatives.__defaultWidth = 1920
CoD.HighValueOperatives.__defaultHeight = 1080
CoD.HighValueOperatives.new = function ( f1_arg0, f1_arg1, f1_arg2, f1_arg3, f1_arg4, f1_arg5, f1_arg6, f1_arg7, f1_arg8, f1_arg9 )
	local self = LUI.UIElement.new( f1_arg2, f1_arg3, f1_arg4, f1_arg5, f1_arg6, f1_arg7, f1_arg8, f1_arg9 )
	self:setUseCylinderMapping( false )
	self:setClass( CoD.HighValueOperatives )
	self.id = "HighValueOperatives"
	self.soundSet = "none"
	self.anyChildUsesUpdateState = true
	f1_arg0:addElementToPendingUpdateStateList( self )
	
	local Backing = LUI.UIImage.new( -0.1, 1.1, 0, 0, -0.1, 1.1, 0, 0 )
	Backing:setRGB( 0, 0, 0 )
	Backing:setAlpha( 0.3 )
	self:addElement( Backing )
	self.Backing = Backing
	
	local CommonHeader = CoD.CommonHeader.new( f1_arg0, f1_arg1, 0, 0, 0, 1920, 0, 0, 0, 67 )
	CommonHeader:setAlpha( 0 )
	CommonHeader.subtitle.StageTitle:setText( LocalizeToUpperString( 0xEEF90B1483C4C23 ) )
	CommonHeader:subscribeToGlobalModel( f1_arg1, "LobbyRoot", "lobbyTitle", function ( model )
		local f2_local0 = model:get()
		if f2_local0 ~= nil then
			CommonHeader.subtitle.subtitle:setText( Engine[0xF9F1239CFD921FE]( f2_local0 ) )
		end
	end )
	CommonHeader:registerEventHandler( "menu_loaded", function ( element, event )
		local f3_local0 = nil
		if element.menuLoaded then
			f3_local0 = element:menuLoaded( event )
		elseif element.super.menuLoaded then
			f3_local0 = element.super:menuLoaded( event )
		end
		SizeToSafeArea( element, f1_arg1 )
		if not f3_local0 then
			f3_local0 = element:dispatchEventToChildren( event )
		end
		return f3_local0
	end )
	self:addElement( CommonHeader )
	self.CommonHeader = CommonHeader
	
	local CardList = LUI.UIList.new( f1_arg0, f1_arg1, 110, 0, nil, false, false, false, false )
	CardList:setLeftRight( 0, 0, 60, 295 )
	CardList:setTopBottom( 0, 0, 154, 159 )
	CardList:setAlpha( 0 )
	CardList:setWidgetType( CoD.HVODummyCard )
	CardList:setHorizontalCount( 3 )
	CardList:setSpacing( 110 )
	CardList:setAlignment( Enum.LUIAlignment[0xFEEB12BCB0D7041] )
	CardList:setStaggeredIntroTime( 300 )
	CardList:setDataSource( "HighValueOperatives" )
	CardList:subscribeToGlobalModel( f1_arg1, "PerController", "gameScore.hvoUpdate", function ( model )
		UpdateDataSource( self, CardList, f1_arg1 )
	end )
	self:addElement( CardList )
	self.CardList = CardList
	
	local topbarblack = LUI.UIImage.new( 0, 0, -42, 1958, 0, 0, -8, 95 )
	topbarblack:setRGB( 0, 0, 0 )
	topbarblack:setAlpha( 0.95 )
	topbarblack:setImage( RegisterImage( 0x128E65A576FCBB8 ) )
	self:addElement( topbarblack )
	self.topbarblack = topbarblack
	
	local bottombarblack = LUI.UIImage.new( 0, 0, -42, 1958, 0, 0, 1034, 1089 )
	bottombarblack:setRGB( 0, 0, 0 )
	bottombarblack:setAlpha( 0.95 )
	bottombarblack:setImage( RegisterImage( 0x128E65A576FCBB8 ) )
	self:addElement( bottombarblack )
	self.bottombarblack = bottombarblack
	
	local FUI = LUI.UIImage.new( 0, 0, 19, 410, 0, 0, 0, 82 )
	FUI:setAlpha( 0.92 )
	FUI:setYRot( 180 )
	FUI:setImage( RegisterImage( 0x3C759323B37D3D7 ) )
	FUI:setMaterial( LUI.UIImage.GetCachedMaterial( "uie_wipe_delta_normal" ) )
	FUI:setShaderVector( 0, 0.12, 1, 0, 0 )
	FUI:setShaderVector( 1, 0.41, -0.13, 0, 0 )
	FUI:setShaderVector( 2, 0, 1, 0, 0 )
	FUI:setShaderVector( 3, 0, 0, 0, 0 )
	FUI:setShaderVector( 4, 0, 0, 0, 0 )
	self:addElement( FUI )
	self.FUI = FUI
	
	local killcamTitle = LUI.UIText.new( 0, 0, 50, 1922, 0, 0, 17, 67 )
	killcamTitle:setRGB( ColorSet.T8__GOLD.r, ColorSet.T8__GOLD.g, ColorSet.T8__GOLD.b )
	killcamTitle:setScale( 1.02, 1.02 )
	killcamTitle:setText( LocalizeToUpperString( 0x6D7524BAE8B5798 ) )
	killcamTitle:setTTF( "ttmussels_regular" )
	killcamTitle:setLetterSpacing( 14 )
	killcamTitle:setAlignment( Enum.LUIAlignment[0x58C8A85F2048829] )
	killcamTitle:setAlignment( Enum.LUIAlignment[0xF41D595A2B0EDF3] )
	killcamTitle:setBackingType( 2 )
	killcamTitle:setBackingColor( ColorSet.GameUpdateLives.r, ColorSet.GameUpdateLives.g, ColorSet.GameUpdateLives.b )
	killcamTitle:setBackingAlpha( 0.15 )
	killcamTitle:setBackingXPadding( 3 )
	killcamTitle:setBackingYPadding( 5 )
	killcamTitle:setBackingImage( RegisterImage( 0x7ECB8AADFBD628E ) )
	self:addElement( killcamTitle )
	self.killcamTitle = killcamTitle
	
	local HVOCard1 = CoD.HVOCardInternal.new( f1_arg0, f1_arg1, 0, 0, 49, 681, 0, 0, 85, 1049 )
	HVOCard1:setAlpha( 0 )
	HVOCard1:setScale( 1.6, 1.6 )
	HVOCard1.StatList:setAlpha( 0 )
	self:addElement( HVOCard1 )
	self.HVOCard1 = HVOCard1
	
	local HVOCard2 = CoD.HVOCardInternal.new( f1_arg0, f1_arg1, 0, 0, 644, 1276, 0, 0, 85, 1049 )
	HVOCard2:setAlpha( 0 )
	HVOCard2:setScale( 1.6, 1.6 )
	HVOCard2.StatList:setAlpha( 0 )
	HVOCard2.TeamBarAnim:setZRot( 180 )
	HVOCard2.TeamBarAnim:setShaderVector( 1, 36, 0, 0, 0 )
	self:addElement( HVOCard2 )
	self.HVOCard2 = HVOCard2
	
	local HVOCard3 = CoD.HVOCardInternal.new( f1_arg0, f1_arg1, 0, 0, 1237, 1869, 0, 0, 85, 1049 )
	HVOCard3:setAlpha( 0 )
	HVOCard3:setScale( 1.6, 1.6 )
	HVOCard3.StatList:setAlpha( 0 )
	HVOCard3.TeamBarAnim:setShaderVector( 1, 24, 0, 0, 0 )
	self:addElement( HVOCard3 )
	self.HVOCard3 = HVOCard3
	
	LUI.OverrideFunction_CallOriginalFirst( self, "setState", function ( element, controller, f5_arg2, f5_arg3, f5_arg4 )
		if IsSelfInState( self, "Show" ) then
			CoD.GridAndListUtility.ReplayStaggeredIntro( self.CardList )
		end
	end )
	self:subscribeToGlobalModel( f1_arg1, "PerController", "gameScore.hvoUpdate", function ( model )
		local f6_local0 = self
		UpdateDataSource( self, self.CardList, f1_arg1 )
		CoD.GameEndScoreUtility.SetupHVOCard( f1_arg1, self.HVOCard1, self.CardList, "HighValueOperatives", 1 )
		CoD.GameEndScoreUtility.SetupHVOCard( f1_arg1, self.HVOCard2, self.CardList, "HighValueOperatives", 2 )
		CoD.GameEndScoreUtility.SetupHVOCard( f1_arg1, self.HVOCard3, self.CardList, "HighValueOperatives", 3 )
	end )
	CardList.id = "CardList"
	HVOCard1.id = "HVOCard1"
	HVOCard2.id = "HVOCard2"
	HVOCard3.id = "HVOCard3"
	LUI.OverrideFunction_CallOriginalSecond( self, "close", self.__onClose )
	
	if PostLoadFunc then
		PostLoadFunc( self, f1_arg1, f1_arg0 )
	end
	
	local f1_local11 = self
	f1_local11 = HVOCard1
	return self
end

CoD.HighValueOperatives.__resetProperties = function ( f7_arg0 )
	f7_arg0.CardList:completeAnimation()
	f7_arg0.CommonHeader:completeAnimation()
	f7_arg0.Backing:completeAnimation()
	f7_arg0.killcamTitle:completeAnimation()
	f7_arg0.FUI:completeAnimation()
	f7_arg0.bottombarblack:completeAnimation()
	f7_arg0.topbarblack:completeAnimation()
	f7_arg0.HVOCard1:completeAnimation()
	f7_arg0.HVOCard2:completeAnimation()
	f7_arg0.HVOCard3:completeAnimation()
	f7_arg0.CardList:setAlpha( 0 )
	f7_arg0.CommonHeader:setAlpha( 0 )
	f7_arg0.Backing:setAlpha( 0.3 )
	f7_arg0.killcamTitle:setAlpha( 1 )
	f7_arg0.FUI:setAlpha( 0.92 )
	f7_arg0.bottombarblack:setAlpha( 0.95 )
	f7_arg0.topbarblack:setAlpha( 0.95 )
	f7_arg0.HVOCard1:setAlpha( 0 )
	f7_arg0.HVOCard1:setScale( 1.6, 1.6 )
	f7_arg0.HVOCard1.Image:setAlpha( 0 )
	f7_arg0.HVOCard1.Title:setAlpha( 0 )
	f7_arg0.HVOCard1.Description:setAlpha( 0 )
	f7_arg0.HVOCard1.StatList:setAlpha( 0 )
	f7_arg0.HVOCard1.RankLevel:setAlpha( 0 )
	f7_arg0.HVOCard1.GlowBase:setAlpha( 0 )
	f7_arg0.HVOCard1.GlowMuted:setAlpha( 0 )
	f7_arg0.HVOCard1.GlowMuted:setScale( 1, 1 )
	f7_arg0.HVOCard1.GlowBright:setAlpha( 0 )
	f7_arg0.HVOCard1.GlowBright:setScale( 1, 1 )
	f7_arg0.HVOCard2:setAlpha( 0 )
	f7_arg0.HVOCard2:setScale( 1.6, 1.6 )
	f7_arg0.HVOCard2.Image:setAlpha( 0 )
	f7_arg0.HVOCard2.Title:setAlpha( 0 )
	f7_arg0.HVOCard2.Description:setAlpha( 0 )
	f7_arg0.HVOCard2.StatList:setAlpha( 0 )
	f7_arg0.HVOCard2.RankLevel:setAlpha( 0 )
	f7_arg0.HVOCard2.GlowBase:setAlpha( 0 )
	f7_arg0.HVOCard2.GlowMuted:setAlpha( 0 )
	f7_arg0.HVOCard2.GlowMuted:setScale( 1, 1 )
	f7_arg0.HVOCard2.GlowBright:setAlpha( 0 )
	f7_arg0.HVOCard2.GlowBright:setScale( 1, 1 )
	f7_arg0.HVOCard3:setAlpha( 0 )
	f7_arg0.HVOCard3:setScale( 1.6, 1.6 )
	f7_arg0.HVOCard3.Image:setAlpha( 0 )
	f7_arg0.HVOCard3.Title:setAlpha( 0 )
	f7_arg0.HVOCard3.Description:setAlpha( 0 )
	f7_arg0.HVOCard3.StatList:setAlpha( 0 )
	f7_arg0.HVOCard3.RankLevel:setAlpha( 0 )
	f7_arg0.HVOCard3.GlowBase:setAlpha( 0 )
	f7_arg0.HVOCard3.GlowMuted:setAlpha( 0 )
	f7_arg0.HVOCard3.GlowMuted:setScale( 1, 1 )
	f7_arg0.HVOCard3.GlowBright:setAlpha( 0 )
	f7_arg0.HVOCard3.GlowBright:setScale( 1, 1 )
end

CoD.HighValueOperatives.__clipsPerState = {
	DefaultState = {
		DefaultClip = function ( f8_arg0, f8_arg1 )
			f8_arg0:__resetProperties()
			f8_arg0:setupElementClipCounter( 10 )
			f8_arg0.Backing:completeAnimation()
			f8_arg0.Backing:setAlpha( 0 )
			f8_arg0.clipFinished( f8_arg0.Backing )
			f8_arg0.CommonHeader:completeAnimation()
			f8_arg0.CommonHeader:setAlpha( 0 )
			f8_arg0.clipFinished( f8_arg0.CommonHeader )
			f8_arg0.CardList:completeAnimation()
			f8_arg0.CardList:setAlpha( 0 )
			f8_arg0.clipFinished( f8_arg0.CardList )
			f8_arg0.topbarblack:completeAnimation()
			f8_arg0.topbarblack:setAlpha( 0 )
			f8_arg0.clipFinished( f8_arg0.topbarblack )
			f8_arg0.bottombarblack:completeAnimation()
			f8_arg0.bottombarblack:setAlpha( 0 )
			f8_arg0.clipFinished( f8_arg0.bottombarblack )
			f8_arg0.FUI:completeAnimation()
			f8_arg0.FUI:setAlpha( 0 )
			f8_arg0.clipFinished( f8_arg0.FUI )
			f8_arg0.killcamTitle:completeAnimation()
			f8_arg0.killcamTitle:setAlpha( 0 )
			f8_arg0.clipFinished( f8_arg0.killcamTitle )
			f8_arg0.HVOCard1:completeAnimation()
			f8_arg0.HVOCard1:setAlpha( 0 )
			f8_arg0.clipFinished( f8_arg0.HVOCard1 )
			f8_arg0.HVOCard2:completeAnimation()
			f8_arg0.HVOCard2:setAlpha( 0 )
			f8_arg0.clipFinished( f8_arg0.HVOCard2 )
			f8_arg0.HVOCard3:completeAnimation()
			f8_arg0.HVOCard3:setAlpha( 0 )
			f8_arg0.clipFinished( f8_arg0.HVOCard3 )
		end
	},
	Show = {
		DefaultClip = function ( f9_arg0, f9_arg1 )
			f9_arg0:__resetProperties()
			f9_arg0:setupElementClipCounter( 3 )
			local f9_local0 = function ( f10_arg0 )
				local f10_local0 = function ( f11_arg0 )
					local f11_local0 = function ( f12_arg0 )
						local f12_local0 = function ( f13_arg0 )
							local f13_local0 = function ( f14_arg0 )
								local f14_local0 = function ( f15_arg0 )
									local f15_local0 = function ( f16_arg0 )
										local f16_local0 = function ( f17_arg0 )
											local f17_local0 = function ( f18_arg0 )
												local f18_local0 = function ( f19_arg0 )
													local f19_local0 = function ( f20_arg0 )
														local f20_local0 = function ( f21_arg0 )
															local f21_local0 = function ( f22_arg0 )
																local f22_local0 = function ( f23_arg0 )
																	f23_arg0:beginAnimation( 29 )
																	f23_arg0.GlowBright:beginAnimation( 29 )
																	f23_arg0.GlowBright:setAlpha( 0 )
																	f23_arg0.GlowBright:setScale( 1.08, 1 )
																	f23_arg0:registerEventHandler( "transition_complete_keyframe", f9_arg0.clipFinished )
																end
																
																f22_arg0:beginAnimation( 40 )
																f22_arg0.StatList:beginAnimation( 40 )
																f22_arg0.GlowBright:beginAnimation( 40 )
																f22_arg0.StatList:setAlpha( 1 )
																f22_arg0.GlowBright:setAlpha( 0.15 )
																f22_arg0.GlowBright:setScale( 1.07, 1 )
																f22_arg0:registerEventHandler( "transition_complete_keyframe", f22_local0 )
															end
															
															f21_arg0:beginAnimation( 29 )
															f21_arg0.StatList:beginAnimation( 29 )
															f21_arg0.GlowBase:beginAnimation( 29 )
															f21_arg0.GlowMuted:beginAnimation( 29 )
															f21_arg0.GlowBright:beginAnimation( 29 )
															f21_arg0.StatList:setAlpha( 0.71 )
															f21_arg0.GlowBase:setAlpha( 0 )
															f21_arg0.GlowMuted:setAlpha( 0 )
															f21_arg0.GlowMuted:setScale( 1.04, 1 )
															f21_arg0.GlowBright:setAlpha( 0.35 )
															f21_arg0.GlowBright:setScale( 1.06, 1 )
															f21_arg0:registerEventHandler( "transition_complete_keyframe", f21_local0 )
														end
														
														f20_arg0:beginAnimation( 70 )
														f20_arg0.Description:beginAnimation( 70 )
														f20_arg0.StatList:beginAnimation( 70 )
														f20_arg0.GlowBase:beginAnimation( 70 )
														f20_arg0.GlowMuted:beginAnimation( 70 )
														f20_arg0.GlowBright:beginAnimation( 70 )
														f20_arg0.Description:setAlpha( 1 )
														f20_arg0.StatList:setAlpha( 0.5 )
														f20_arg0.GlowBase:setAlpha( 0.23 )
														f20_arg0.GlowMuted:setAlpha( 0.23 )
														f20_arg0.GlowMuted:setScale( 1.04, 1 )
														f20_arg0.GlowBright:setAlpha( 0.5 )
														f20_arg0.GlowBright:setScale( 1.06, 1 )
														f20_arg0:registerEventHandler( "transition_complete_keyframe", f20_local0 )
													end
													
													f19_arg0:beginAnimation( 30 )
													f19_arg0.Title:beginAnimation( 30 )
													f19_arg0.Description:beginAnimation( 30 )
													f19_arg0.GlowBase:beginAnimation( 30 )
													f19_arg0.GlowMuted:beginAnimation( 30 )
													f19_arg0.GlowBright:beginAnimation( 30 )
													f19_arg0.Title:setAlpha( 1 )
													f19_arg0.Description:setAlpha( 0.46 )
													f19_arg0.GlowBase:setAlpha( 0.77 )
													f19_arg0.GlowMuted:setAlpha( 0.77 )
													f19_arg0.GlowMuted:setScale( 1.03, 1 )
													f19_arg0.GlowBright:setAlpha( 0.85 )
													f19_arg0.GlowBright:setScale( 1.04, 1 )
													f19_arg0:registerEventHandler( "transition_complete_keyframe", f19_local0 )
												end
												
												f18_arg0:beginAnimation( 30 )
												f18_arg0.Title:beginAnimation( 30 )
												f18_arg0.Description:beginAnimation( 30 )
												f18_arg0.GlowBase:beginAnimation( 30 )
												f18_arg0.GlowMuted:beginAnimation( 30 )
												f18_arg0.GlowBright:beginAnimation( 30 )
												f18_arg0.Title:setAlpha( 0.75 )
												f18_arg0.Description:setAlpha( 0.23 )
												f18_arg0.GlowBase:setAlpha( 1 )
												f18_arg0.GlowMuted:setAlpha( 1 )
												f18_arg0.GlowMuted:setScale( 1.02, 1 )
												f18_arg0.GlowBright:setAlpha( 1 )
												f18_arg0.GlowBright:setScale( 1.03, 1 )
												f18_arg0:registerEventHandler( "transition_complete_keyframe", f18_local0 )
											end
											
											f17_arg0:beginAnimation( 19 )
											f17_arg0.Image:beginAnimation( 19 )
											f17_arg0.Title:beginAnimation( 19 )
											f17_arg0.RankLevel:beginAnimation( 19 )
											f17_arg0.GlowBase:beginAnimation( 19 )
											f17_arg0.GlowMuted:beginAnimation( 19 )
											f17_arg0.GlowBright:beginAnimation( 19 )
											f17_arg0.Image:setAlpha( 1 )
											f17_arg0.Title:setAlpha( 0.5 )
											f17_arg0.RankLevel:setAlpha( 1 )
											f17_arg0.GlowBase:setAlpha( 0.8 )
											f17_arg0.GlowMuted:setAlpha( 0.8 )
											f17_arg0.GlowMuted:setScale( 1.02, 1 )
											f17_arg0.GlowBright:setAlpha( 0.8 )
											f17_arg0.GlowBright:setScale( 1.03, 1 )
											f17_arg0:registerEventHandler( "transition_complete_keyframe", f17_local0 )
										end
										
										f16_arg0:beginAnimation( 39 )
										f16_arg0.Image:beginAnimation( 39 )
										f16_arg0.Title:beginAnimation( 39 )
										f16_arg0.RankLevel:beginAnimation( 39 )
										f16_arg0.GlowBase:beginAnimation( 39 )
										f16_arg0.GlowMuted:beginAnimation( 39 )
										f16_arg0.GlowBright:beginAnimation( 39 )
										f16_arg0:setAlpha( 1 )
										f16_arg0.Image:setAlpha( 0.9 )
										f16_arg0.Title:setAlpha( 0.33 )
										f16_arg0.RankLevel:setAlpha( 0.83 )
										f16_arg0.GlowBase:setAlpha( 0.67 )
										f16_arg0.GlowMuted:setAlpha( 0.67 )
										f16_arg0.GlowMuted:setScale( 1.01, 1 )
										f16_arg0.GlowBright:setAlpha( 0.67 )
										f16_arg0.GlowBright:setScale( 1.02, 1 )
										f16_arg0:registerEventHandler( "transition_complete_keyframe", f16_local0 )
									end
									
									f15_arg0:beginAnimation( 10 )
									f15_arg0.Image:beginAnimation( 10 )
									f15_arg0.RankLevel:beginAnimation( 10 )
									f15_arg0.GlowBase:beginAnimation( 10 )
									f15_arg0.GlowMuted:beginAnimation( 10 )
									f15_arg0.GlowBright:beginAnimation( 10 )
									f15_arg0:setAlpha( 0.9 )
									f15_arg0.Image:setAlpha( 0.7 )
									f15_arg0.RankLevel:setAlpha( 0.5 )
									f15_arg0.GlowBase:setAlpha( 0.4 )
									f15_arg0.GlowMuted:setAlpha( 0.4 )
									f15_arg0.GlowMuted:setScale( 1.01, 1 )
									f15_arg0.GlowBright:setAlpha( 0.4 )
									f15_arg0.GlowBright:setScale( 1.01, 1 )
									f15_arg0:registerEventHandler( "transition_complete_keyframe", f15_local0 )
								end
								
								f14_arg0:beginAnimation( 49 )
								f14_arg0.Image:beginAnimation( 49 )
								f14_arg0.RankLevel:beginAnimation( 49 )
								f14_arg0.GlowBase:beginAnimation( 49 )
								f14_arg0.GlowMuted:beginAnimation( 49 )
								f14_arg0.GlowBright:beginAnimation( 49 )
								f14_arg0:setAlpha( 0.88 )
								f14_arg0:setScale( 1, 1 )
								f14_arg0.Image:setAlpha( 0.65 )
								f14_arg0.RankLevel:setAlpha( 0.42 )
								f14_arg0.GlowBase:setAlpha( 0.33 )
								f14_arg0.GlowMuted:setAlpha( 0.33 )
								f14_arg0.GlowMuted:setScale( 1.01, 1 )
								f14_arg0.GlowBright:setAlpha( 0.33 )
								f14_arg0.GlowBright:setScale( 1.01, 1 )
								f14_arg0:registerEventHandler( "transition_complete_keyframe", f14_local0 )
							end
							
							f13_arg0:beginAnimation( 40 )
							f13_arg0.Image:beginAnimation( 40 )
							f13_arg0:setAlpha( 0.75 )
							f13_arg0:setScale( 1.06, 1.06 )
							f13_arg0.Image:setAlpha( 0.4 )
							f13_arg0:registerEventHandler( "transition_complete_keyframe", f13_local0 )
						end
						
						f12_arg0:beginAnimation( 39 )
						f12_arg0.Image:beginAnimation( 39 )
						f12_arg0:setAlpha( 0.65 )
						f12_arg0:setScale( 1.1, 1.1 )
						f12_arg0.Image:setAlpha( 0.2 )
						f12_arg0:registerEventHandler( "transition_complete_keyframe", f12_local0 )
					end
					
					f11_arg0:beginAnimation( 39 )
					f11_arg0:setAlpha( 0.55 )
					f11_arg0:setScale( 1.05, 1.05 )
					f11_arg0:registerEventHandler( "transition_complete_keyframe", f11_local0 )
				end
				
				f9_arg0.HVOCard1:beginAnimation( 180 )
				f9_arg0.HVOCard1:setAlpha( 0.45 )
				f9_arg0.HVOCard1:setScale( 1, 1 )
				f9_arg0.HVOCard1:registerEventHandler( "interrupted_keyframe", f9_arg0.clipInterrupted )
				f9_arg0.HVOCard1:registerEventHandler( "transition_complete_keyframe", f10_local0 )
			end
			
			f9_arg0.HVOCard1:completeAnimation()
			f9_arg0.HVOCard1.Image:completeAnimation()
			f9_arg0.HVOCard1.Title:completeAnimation()
			f9_arg0.HVOCard1.Description:completeAnimation()
			f9_arg0.HVOCard1.StatList:completeAnimation()
			f9_arg0.HVOCard1.RankLevel:completeAnimation()
			f9_arg0.HVOCard1.GlowBase:completeAnimation()
			f9_arg0.HVOCard1.GlowMuted:completeAnimation()
			f9_arg0.HVOCard1.GlowBright:completeAnimation()
			f9_arg0.HVOCard1:setAlpha( 0 )
			f9_arg0.HVOCard1:setScale( 1.6, 1.6 )
			f9_arg0.HVOCard1.Image:setAlpha( 0 )
			f9_arg0.HVOCard1.Title:setAlpha( 0 )
			f9_arg0.HVOCard1.Description:setAlpha( 0 )
			f9_arg0.HVOCard1.StatList:setAlpha( 0 )
			f9_arg0.HVOCard1.RankLevel:setAlpha( 0 )
			f9_arg0.HVOCard1.GlowBase:setAlpha( 0 )
			f9_arg0.HVOCard1.GlowMuted:setAlpha( 0 )
			f9_arg0.HVOCard1.GlowMuted:setScale( 1, 1 )
			f9_arg0.HVOCard1.GlowBright:setAlpha( 0 )
			f9_arg0.HVOCard1.GlowBright:setScale( 1, 1 )
			f9_local0( f9_arg0.HVOCard1 )
			local f9_local1 = function ( f24_arg0 )
				local f24_local0 = function ( f25_arg0 )
					local f25_local0 = function ( f26_arg0 )
						local f26_local0 = function ( f27_arg0 )
							local f27_local0 = function ( f28_arg0 )
								local f28_local0 = function ( f29_arg0 )
									local f29_local0 = function ( f30_arg0 )
										local f30_local0 = function ( f31_arg0 )
											local f31_local0 = function ( f32_arg0 )
												local f32_local0 = function ( f33_arg0 )
													local f33_local0 = function ( f34_arg0 )
														local f34_local0 = function ( f35_arg0 )
															local f35_local0 = function ( f36_arg0 )
																local f36_local0 = function ( f37_arg0 )
																	local f37_local0 = function ( f38_arg0 )
																		local f38_local0 = function ( f39_arg0 )
																			local f39_local0 = function ( f40_arg0 )
																				f40_arg0:beginAnimation( 69 )
																				f40_arg0.GlowBright:beginAnimation( 69 )
																				f40_arg0.GlowBright:setAlpha( 0 )
																				f40_arg0.GlowBright:setScale( 1.08, 1 )
																				f40_arg0:registerEventHandler( "transition_complete_keyframe", f9_arg0.clipFinished )
																			end
																			
																			f39_arg0:beginAnimation( 9 )
																			f39_arg0.GlowBase:beginAnimation( 9 )
																			f39_arg0.GlowMuted:beginAnimation( 9 )
																			f39_arg0.GlowBright:beginAnimation( 9 )
																			f39_arg0.GlowBase:setAlpha( 0 )
																			f39_arg0.GlowMuted:setAlpha( 0 )
																			f39_arg0.GlowMuted:setScale( 1.04, 1 )
																			f39_arg0.GlowBright:setAlpha( 0.35 )
																			f39_arg0.GlowBright:setScale( 1.06, 1 )
																			f39_arg0:registerEventHandler( "transition_complete_keyframe", f39_local0 )
																		end
																		
																		f38_arg0:beginAnimation( 60 )
																		f38_arg0.StatList:beginAnimation( 60 )
																		f38_arg0.GlowBase:beginAnimation( 60 )
																		f38_arg0.GlowMuted:beginAnimation( 60 )
																		f38_arg0.GlowBright:beginAnimation( 60 )
																		f38_arg0.StatList:setAlpha( 1 )
																		f38_arg0.GlowBase:setAlpha( 0.08 )
																		f38_arg0.GlowMuted:setAlpha( 0.08 )
																		f38_arg0.GlowMuted:setScale( 1.04, 1 )
																		f38_arg0.GlowBright:setAlpha( 0.4 )
																		f38_arg0.GlowBright:setScale( 1.06, 1 )
																		f38_arg0:registerEventHandler( "transition_complete_keyframe", f38_local0 )
																	end
																	
																	f37_arg0:beginAnimation( 9 )
																	f37_arg0.StatList:beginAnimation( 9 )
																	f37_arg0.GlowBase:beginAnimation( 9 )
																	f37_arg0.GlowMuted:beginAnimation( 9 )
																	f37_arg0.GlowBright:beginAnimation( 9 )
																	f37_arg0.StatList:setAlpha( 0.57 )
																	f37_arg0.GlowBase:setAlpha( 0.54 )
																	f37_arg0.GlowMuted:setAlpha( 0.54 )
																	f37_arg0.GlowMuted:setScale( 1.03, 1 )
																	f37_arg0.GlowBright:setAlpha( 0.7 )
																	f37_arg0.GlowBright:setScale( 1.05, 1 )
																	f37_arg0:registerEventHandler( "transition_complete_keyframe", f37_local0 )
																end
																
																f36_arg0:beginAnimation( 49 )
																f36_arg0.Description:beginAnimation( 49 )
																f36_arg0.StatList:beginAnimation( 49 )
																f36_arg0.GlowBase:beginAnimation( 49 )
																f36_arg0.GlowMuted:beginAnimation( 49 )
																f36_arg0.GlowBright:beginAnimation( 49 )
																f36_arg0.Description:setAlpha( 1 )
																f36_arg0.StatList:setAlpha( 0.5 )
																f36_arg0.GlowBase:setAlpha( 0.62 )
																f36_arg0.GlowMuted:setAlpha( 0.62 )
																f36_arg0.GlowMuted:setScale( 1.03, 1 )
																f36_arg0.GlowBright:setAlpha( 0.75 )
																f36_arg0.GlowBright:setScale( 1.04, 1 )
																f36_arg0:registerEventHandler( "transition_complete_keyframe", f36_local0 )
															end
															
															f35_arg0:beginAnimation( 20 )
															f35_arg0.Description:beginAnimation( 20 )
															f35_arg0.StatList:beginAnimation( 20 )
															f35_arg0.GlowBase:beginAnimation( 20 )
															f35_arg0.GlowMuted:beginAnimation( 20 )
															f35_arg0.GlowBright:beginAnimation( 20 )
															f35_arg0.Description:setAlpha( 0.64 )
															f35_arg0.StatList:setAlpha( 0.14 )
															f35_arg0.GlowBase:setAlpha( 1 )
															f35_arg0.GlowMuted:setAlpha( 1 )
															f35_arg0.GlowMuted:setScale( 1.02, 1 )
															f35_arg0.GlowBright:setAlpha( 1 )
															f35_arg0.GlowBright:setScale( 1.03, 1 )
															f35_arg0:registerEventHandler( "transition_complete_keyframe", f35_local0 )
														end
														
														f34_arg0:beginAnimation( 9 )
														f34_arg0.Description:beginAnimation( 9 )
														f34_arg0.GlowBase:beginAnimation( 9 )
														f34_arg0.GlowMuted:beginAnimation( 9 )
														f34_arg0.GlowBright:beginAnimation( 9 )
														f34_arg0.Description:setAlpha( 0.5 )
														f34_arg0.GlowBase:setAlpha( 0.85 )
														f34_arg0.GlowMuted:setAlpha( 0.85 )
														f34_arg0.GlowMuted:setScale( 1.02, 1 )
														f34_arg0.GlowBright:setAlpha( 0.85 )
														f34_arg0.GlowBright:setScale( 1.03, 1 )
														f34_arg0:registerEventHandler( "transition_complete_keyframe", f34_local0 )
													end
													
													f33_arg0:beginAnimation( 59 )
													f33_arg0.Title:beginAnimation( 59 )
													f33_arg0.Description:beginAnimation( 59 )
													f33_arg0.GlowBase:beginAnimation( 59 )
													f33_arg0.GlowMuted:beginAnimation( 59 )
													f33_arg0.GlowBright:beginAnimation( 59 )
													f33_arg0.Title:setAlpha( 1 )
													f33_arg0.Description:setAlpha( 0.43 )
													f33_arg0.GlowBase:setAlpha( 0.77 )
													f33_arg0.GlowMuted:setAlpha( 0.77 )
													f33_arg0.GlowMuted:setScale( 1.02, 1 )
													f33_arg0.GlowBright:setAlpha( 0.77 )
													f33_arg0.GlowBright:setScale( 1.02, 1 )
													f33_arg0:registerEventHandler( "transition_complete_keyframe", f33_local0 )
												end
												
												f32_arg0:beginAnimation( 19 )
												f32_arg0.Title:beginAnimation( 19 )
												f32_arg0.GlowBase:beginAnimation( 19 )
												f32_arg0.GlowMuted:beginAnimation( 19 )
												f32_arg0.GlowBright:beginAnimation( 19 )
												f32_arg0.Title:setAlpha( 0.57 )
												f32_arg0.GlowBase:setAlpha( 0.31 )
												f32_arg0.GlowMuted:setAlpha( 0.31 )
												f32_arg0.GlowMuted:setScale( 1.01, 1 )
												f32_arg0.GlowBright:setAlpha( 0.31 )
												f32_arg0.GlowBright:setScale( 1.01, 1 )
												f32_arg0:registerEventHandler( "transition_complete_keyframe", f32_local0 )
											end
											
											f31_arg0:beginAnimation( 20 )
											f31_arg0.Image:beginAnimation( 20 )
											f31_arg0.Title:beginAnimation( 20 )
											f31_arg0.RankLevel:beginAnimation( 20 )
											f31_arg0.GlowBase:beginAnimation( 20 )
											f31_arg0.GlowMuted:beginAnimation( 20 )
											f31_arg0.GlowBright:beginAnimation( 20 )
											f31_arg0.Image:setAlpha( 1 )
											f31_arg0.Title:setAlpha( 0.43 )
											f31_arg0.RankLevel:setAlpha( 1 )
											f31_arg0.GlowBase:setAlpha( 0.15 )
											f31_arg0.GlowMuted:setAlpha( 0.15 )
											f31_arg0.GlowMuted:setScale( 1, 1 )
											f31_arg0.GlowBright:setAlpha( 0.15 )
											f31_arg0.GlowBright:setScale( 1, 1 )
											f31_arg0:registerEventHandler( "transition_complete_keyframe", f31_local0 )
										end
										
										f30_arg0:beginAnimation( 39 )
										f30_arg0.Image:beginAnimation( 39 )
										f30_arg0.Title:beginAnimation( 39 )
										f30_arg0.RankLevel:beginAnimation( 39 )
										f30_arg0:setAlpha( 1 )
										f30_arg0.Image:setAlpha( 0.89 )
										f30_arg0.Title:setAlpha( 0.29 )
										f30_arg0.RankLevel:setAlpha( 0.83 )
										f30_arg0:registerEventHandler( "transition_complete_keyframe", f30_local0 )
									end
									
									f29_arg0:beginAnimation( 10 )
									f29_arg0.Image:beginAnimation( 10 )
									f29_arg0.RankLevel:beginAnimation( 10 )
									f29_arg0:setAlpha( 0.9 )
									f29_arg0.Image:setAlpha( 0.67 )
									f29_arg0.RankLevel:setAlpha( 0.5 )
									f29_arg0:registerEventHandler( "transition_complete_keyframe", f29_local0 )
								end
								
								f28_arg0:beginAnimation( 49 )
								f28_arg0.Image:beginAnimation( 49 )
								f28_arg0.RankLevel:beginAnimation( 49 )
								f28_arg0:setAlpha( 0.87 )
								f28_arg0:setScale( 1, 1 )
								f28_arg0.Image:setAlpha( 0.61 )
								f28_arg0.RankLevel:setAlpha( 0.42 )
								f28_arg0:registerEventHandler( "transition_complete_keyframe", f28_local0 )
							end
							
							f27_arg0:beginAnimation( 30 )
							f27_arg0.Image:beginAnimation( 30 )
							f27_arg0:setAlpha( 0.75 )
							f27_arg0:setScale( 1.06, 1.06 )
							f27_arg0.Image:setAlpha( 0.33 )
							f27_arg0:registerEventHandler( "transition_complete_keyframe", f27_local0 )
						end
						
						f26_arg0:beginAnimation( 29 )
						f26_arg0.Image:beginAnimation( 29 )
						f26_arg0:setAlpha( 0.68 )
						f26_arg0:setScale( 1.1, 1.1 )
						f26_arg0.Image:setAlpha( 0.17 )
						f26_arg0:registerEventHandler( "transition_complete_keyframe", f26_local0 )
					end
					
					f25_arg0:beginAnimation( 50 )
					f25_arg0:setAlpha( 0.6 )
					f25_arg0:setScale( 1.06, 1.06 )
					f25_arg0:registerEventHandler( "transition_complete_keyframe", f25_local0 )
				end
				
				f24_arg0:beginAnimation( 190 )
				f24_arg0:setAlpha( 0.48 )
				f24_arg0:setScale( 1, 1 )
				f24_arg0:registerEventHandler( "transition_complete_keyframe", f24_local0 )
			end
			
			f9_arg0.HVOCard2:beginAnimation( 550 )
			f9_arg0.HVOCard2.Image:beginAnimation( 550 )
			f9_arg0.HVOCard2.Title:beginAnimation( 550 )
			f9_arg0.HVOCard2.Description:beginAnimation( 550 )
			f9_arg0.HVOCard2.StatList:beginAnimation( 550 )
			f9_arg0.HVOCard2.RankLevel:beginAnimation( 550 )
			f9_arg0.HVOCard2.GlowBase:beginAnimation( 550 )
			f9_arg0.HVOCard2.GlowMuted:beginAnimation( 550 )
			f9_arg0.HVOCard2.GlowBright:beginAnimation( 550 )
			f9_arg0.HVOCard2:setAlpha( 0 )
			f9_arg0.HVOCard2:setScale( 1.6, 1.6 )
			f9_arg0.HVOCard2.Image:setAlpha( 0 )
			f9_arg0.HVOCard2.Title:setAlpha( 0 )
			f9_arg0.HVOCard2.Description:setAlpha( 0 )
			f9_arg0.HVOCard2.StatList:setAlpha( 0 )
			f9_arg0.HVOCard2.RankLevel:setAlpha( 0 )
			f9_arg0.HVOCard2.GlowBase:setAlpha( 0 )
			f9_arg0.HVOCard2.GlowMuted:setAlpha( 0 )
			f9_arg0.HVOCard2.GlowMuted:setScale( 1, 1 )
			f9_arg0.HVOCard2.GlowBright:setAlpha( 0 )
			f9_arg0.HVOCard2.GlowBright:setScale( 1, 1 )
			f9_arg0.HVOCard2:registerEventHandler( "interrupted_keyframe", f9_arg0.clipInterrupted )
			f9_arg0.HVOCard2:registerEventHandler( "transition_complete_keyframe", f9_local1 )
			local f9_local2 = function ( f41_arg0 )
				local f41_local0 = function ( f42_arg0 )
					local f42_local0 = function ( f43_arg0 )
						local f43_local0 = function ( f44_arg0 )
							local f44_local0 = function ( f45_arg0 )
								local f45_local0 = function ( f46_arg0 )
									local f46_local0 = function ( f47_arg0 )
										local f47_local0 = function ( f48_arg0 )
											local f48_local0 = function ( f49_arg0 )
												local f49_local0 = function ( f50_arg0 )
													local f50_local0 = function ( f51_arg0 )
														local f51_local0 = function ( f52_arg0 )
															local f52_local0 = function ( f53_arg0 )
																local f53_local0 = function ( f54_arg0 )
																	local f54_local0 = function ( f55_arg0 )
																		local f55_local0 = function ( f56_arg0 )
																			local f56_local0 = function ( f57_arg0 )
																				f57_arg0:beginAnimation( 59 )
																				f57_arg0.GlowBright:beginAnimation( 59 )
																				f57_arg0.GlowBright:setAlpha( 0 )
																				f57_arg0.GlowBright:setScale( 1.08, 1 )
																				f57_arg0:registerEventHandler( "transition_complete_keyframe", f9_arg0.clipFinished )
																			end
																			
																			f56_arg0:beginAnimation( 39 )
																			f56_arg0.GlowBase:beginAnimation( 39 )
																			f56_arg0.GlowMuted:beginAnimation( 39 )
																			f56_arg0.GlowBright:beginAnimation( 39 )
																			f56_arg0.GlowBase:setAlpha( 0 )
																			f56_arg0.GlowMuted:setAlpha( 0 )
																			f56_arg0.GlowMuted:setScale( 1.04, 1 )
																			f56_arg0.GlowBright:setAlpha( 0.32 )
																			f56_arg0.GlowBright:setScale( 1.07, 1 )
																			f56_arg0:registerEventHandler( "transition_complete_keyframe", f56_local0 )
																		end
																		
																		f55_arg0:beginAnimation( 20 )
																		f55_arg0.StatList:beginAnimation( 20 )
																		f55_arg0.GlowBase:beginAnimation( 20 )
																		f55_arg0.GlowMuted:beginAnimation( 20 )
																		f55_arg0.GlowBright:beginAnimation( 20 )
																		f55_arg0.StatList:setAlpha( 1 )
																		f55_arg0.GlowBase:setAlpha( 0.31 )
																		f55_arg0.GlowMuted:setAlpha( 0.31 )
																		f55_arg0.GlowMuted:setScale( 1.03, 1 )
																		f55_arg0.GlowBright:setAlpha( 0.53 )
																		f55_arg0.GlowBright:setScale( 1.05, 1 )
																		f55_arg0:registerEventHandler( "transition_complete_keyframe", f55_local0 )
																	end
																	
																	f54_arg0:beginAnimation( 39 )
																	f54_arg0.StatList:beginAnimation( 39 )
																	f54_arg0.GlowBase:beginAnimation( 39 )
																	f54_arg0.GlowMuted:beginAnimation( 39 )
																	f54_arg0.GlowBright:beginAnimation( 39 )
																	f54_arg0.StatList:setAlpha( 0.83 )
																	f54_arg0.GlowBase:setAlpha( 0.46 )
																	f54_arg0.GlowMuted:setAlpha( 0.46 )
																	f54_arg0.GlowMuted:setScale( 1.03, 1 )
																	f54_arg0.GlowBright:setAlpha( 0.63 )
																	f54_arg0.GlowBright:setScale( 1.05, 1 )
																	f54_arg0:registerEventHandler( "transition_complete_keyframe", f54_local0 )
																end
																
																f53_arg0:beginAnimation( 29 )
																f53_arg0.Description:beginAnimation( 29 )
																f53_arg0.StatList:beginAnimation( 29 )
																f53_arg0.GlowBase:beginAnimation( 29 )
																f53_arg0.GlowMuted:beginAnimation( 29 )
																f53_arg0.GlowBright:beginAnimation( 29 )
																f53_arg0.Description:setAlpha( 1 )
																f53_arg0.StatList:setAlpha( 0.5 )
																f53_arg0.GlowBase:setAlpha( 0.77 )
																f53_arg0.GlowMuted:setAlpha( 0.77 )
																f53_arg0.GlowMuted:setScale( 1.02, 1 )
																f53_arg0.GlowBright:setAlpha( 0.84 )
																f53_arg0.GlowBright:setScale( 1.04, 1 )
																f53_arg0:registerEventHandler( "transition_complete_keyframe", f53_local0 )
															end
															
															f52_arg0:beginAnimation( 29 )
															f52_arg0.Description:beginAnimation( 29 )
															f52_arg0.StatList:beginAnimation( 29 )
															f52_arg0.GlowBase:beginAnimation( 29 )
															f52_arg0.GlowMuted:beginAnimation( 29 )
															f52_arg0.GlowBright:beginAnimation( 29 )
															f52_arg0.Description:setAlpha( 0.77 )
															f52_arg0.StatList:setAlpha( 0.25 )
															f52_arg0.GlowBase:setAlpha( 1 )
															f52_arg0.GlowMuted:setAlpha( 1 )
															f52_arg0.GlowMuted:setScale( 1.02, 1 )
															f52_arg0.GlowBright:setAlpha( 1 )
															f52_arg0.GlowBright:setScale( 1.03, 1 )
															f52_arg0:registerEventHandler( "transition_complete_keyframe", f52_local0 )
														end
														
														f51_arg0:beginAnimation( 9 )
														f51_arg0.Description:beginAnimation( 9 )
														f51_arg0.GlowBase:beginAnimation( 9 )
														f51_arg0.GlowMuted:beginAnimation( 9 )
														f51_arg0.GlowBright:beginAnimation( 9 )
														f51_arg0.Description:setAlpha( 0.54 )
														f51_arg0.GlowBase:setAlpha( 0.77 )
														f51_arg0.GlowMuted:setAlpha( 0.77 )
														f51_arg0.GlowMuted:setScale( 1.02, 1 )
														f51_arg0.GlowBright:setAlpha( 0.77 )
														f51_arg0.GlowBright:setScale( 1.02, 1 )
														f51_arg0:registerEventHandler( "transition_complete_keyframe", f51_local0 )
													end
													
													f50_arg0:beginAnimation( 60 )
													f50_arg0.Title:beginAnimation( 60 )
													f50_arg0.Description:beginAnimation( 60 )
													f50_arg0.GlowBase:beginAnimation( 60 )
													f50_arg0.GlowMuted:beginAnimation( 60 )
													f50_arg0.GlowBright:beginAnimation( 60 )
													f50_arg0.Title:setAlpha( 1 )
													f50_arg0.Description:setAlpha( 0.46 )
													f50_arg0.GlowBase:setAlpha( 0.69 )
													f50_arg0.GlowMuted:setAlpha( 0.69 )
													f50_arg0.GlowMuted:setScale( 1.01, 1 )
													f50_arg0.GlowBright:setAlpha( 0.69 )
													f50_arg0.GlowBright:setScale( 1.02, 1 )
													f50_arg0:registerEventHandler( "transition_complete_keyframe", f50_local0 )
												end
												
												f49_arg0:beginAnimation( 9 )
												f49_arg0.Title:beginAnimation( 9 )
												f49_arg0.GlowBase:beginAnimation( 9 )
												f49_arg0.GlowMuted:beginAnimation( 9 )
												f49_arg0.GlowBright:beginAnimation( 9 )
												f49_arg0.Title:setAlpha( 0.54 )
												f49_arg0.GlowBase:setAlpha( 0.23 )
												f49_arg0.GlowMuted:setAlpha( 0.23 )
												f49_arg0.GlowMuted:setScale( 1, 1 )
												f49_arg0.GlowBright:setAlpha( 0.23 )
												f49_arg0.GlowBright:setScale( 1.01, 1 )
												f49_arg0:registerEventHandler( "transition_complete_keyframe", f49_local0 )
											end
											
											f48_arg0:beginAnimation( 19 )
											f48_arg0.Image:beginAnimation( 19 )
											f48_arg0.Title:beginAnimation( 19 )
											f48_arg0.RankLevel:beginAnimation( 19 )
											f48_arg0.GlowBase:beginAnimation( 19 )
											f48_arg0.GlowMuted:beginAnimation( 19 )
											f48_arg0.GlowBright:beginAnimation( 19 )
											f48_arg0.Image:setAlpha( 1 )
											f48_arg0.Title:setAlpha( 0.46 )
											f48_arg0.RankLevel:setAlpha( 1 )
											f48_arg0.GlowBase:setAlpha( 0.15 )
											f48_arg0.GlowMuted:setAlpha( 0.15 )
											f48_arg0.GlowMuted:setScale( 1, 1 )
											f48_arg0.GlowBright:setAlpha( 0.15 )
											f48_arg0.GlowBright:setScale( 1, 1 )
											f48_arg0:registerEventHandler( "transition_complete_keyframe", f48_local0 )
										end
										
										f47_arg0:beginAnimation( 40 )
										f47_arg0.Image:beginAnimation( 40 )
										f47_arg0.Title:beginAnimation( 40 )
										f47_arg0.RankLevel:beginAnimation( 40 )
										f47_arg0:setAlpha( 1 )
										f47_arg0.Image:setAlpha( 0.9 )
										f47_arg0.Title:setAlpha( 0.31 )
										f47_arg0.RankLevel:setAlpha( 0.85 )
										f47_arg0:registerEventHandler( "transition_complete_keyframe", f47_local0 )
									end
									
									f46_arg0:beginAnimation( 9 )
									f46_arg0.Image:beginAnimation( 9 )
									f46_arg0.RankLevel:beginAnimation( 9 )
									f46_arg0:setAlpha( 0.9 )
									f46_arg0.Image:setAlpha( 0.7 )
									f46_arg0.RankLevel:setAlpha( 0.54 )
									f46_arg0:registerEventHandler( "transition_complete_keyframe", f46_local0 )
								end
								
								f45_arg0:beginAnimation( 59 )
								f45_arg0.Image:beginAnimation( 59 )
								f45_arg0.RankLevel:beginAnimation( 59 )
								f45_arg0:setAlpha( 0.87 )
								f45_arg0:setScale( 1, 1 )
								f45_arg0.Image:setAlpha( 0.65 )
								f45_arg0.RankLevel:setAlpha( 0.46 )
								f45_arg0:registerEventHandler( "transition_complete_keyframe", f45_local0 )
							end
							
							f44_arg0:beginAnimation( 39 )
							f44_arg0.Image:beginAnimation( 39 )
							f44_arg0:setAlpha( 0.73 )
							f44_arg0:setScale( 1.06, 1.06 )
							f44_arg0.Image:setAlpha( 0.35 )
							f44_arg0:registerEventHandler( "transition_complete_keyframe", f44_local0 )
						end
						
						f43_arg0:beginAnimation( 30 )
						f43_arg0.Image:beginAnimation( 30 )
						f43_arg0:setAlpha( 0.63 )
						f43_arg0:setScale( 1.1, 1.1 )
						f43_arg0.Image:setAlpha( 0.15 )
						f43_arg0:registerEventHandler( "transition_complete_keyframe", f43_local0 )
					end
					
					f42_arg0:beginAnimation( 49 )
					f42_arg0:setAlpha( 0.55 )
					f42_arg0:setScale( 1.06, 1.06 )
					f42_arg0:registerEventHandler( "transition_complete_keyframe", f42_local0 )
				end
				
				f41_arg0:beginAnimation( 169 )
				f41_arg0:setAlpha( 0.42 )
				f41_arg0:setScale( 1, 1 )
				f41_arg0:registerEventHandler( "transition_complete_keyframe", f41_local0 )
			end
			
			f9_arg0.HVOCard3:beginAnimation( 1200 )
			f9_arg0.HVOCard3.Image:beginAnimation( 1200 )
			f9_arg0.HVOCard3.Title:beginAnimation( 1200 )
			f9_arg0.HVOCard3.Description:beginAnimation( 1200 )
			f9_arg0.HVOCard3.StatList:beginAnimation( 1200 )
			f9_arg0.HVOCard3.RankLevel:beginAnimation( 1200 )
			f9_arg0.HVOCard3.GlowBase:beginAnimation( 1200 )
			f9_arg0.HVOCard3.GlowMuted:beginAnimation( 1200 )
			f9_arg0.HVOCard3.GlowBright:beginAnimation( 1200 )
			f9_arg0.HVOCard3:setAlpha( 0 )
			f9_arg0.HVOCard3:setScale( 1.6, 1.6 )
			f9_arg0.HVOCard3.Image:setAlpha( 0 )
			f9_arg0.HVOCard3.Title:setAlpha( 0 )
			f9_arg0.HVOCard3.Description:setAlpha( 0 )
			f9_arg0.HVOCard3.StatList:setAlpha( 0 )
			f9_arg0.HVOCard3.RankLevel:setAlpha( 0 )
			f9_arg0.HVOCard3.GlowBase:setAlpha( 0 )
			f9_arg0.HVOCard3.GlowMuted:setAlpha( 0 )
			f9_arg0.HVOCard3.GlowMuted:setScale( 1, 1 )
			f9_arg0.HVOCard3.GlowBright:setAlpha( 0 )
			f9_arg0.HVOCard3.GlowBright:setScale( 1, 1 )
			f9_arg0.HVOCard3:registerEventHandler( "interrupted_keyframe", f9_arg0.clipInterrupted )
			f9_arg0.HVOCard3:registerEventHandler( "transition_complete_keyframe", f9_local2 )
		end
	}
}
CoD.HighValueOperatives.__onClose = function ( f58_arg0 )
	f58_arg0.CommonHeader:close()
	f58_arg0.CardList:close()
	f58_arg0.HVOCard1:close()
	f58_arg0.HVOCard2:close()
	f58_arg0.HVOCard3:close()
end

