CoD.StartMenu_Inventory_ActionIconPC = InheritFrom( LUI.UIElement )
CoD.StartMenu_Inventory_ActionIconPC.__defaultWidth = 64
CoD.StartMenu_Inventory_ActionIconPC.__defaultHeight = 64
CoD.StartMenu_Inventory_ActionIconPC.new = function ( f1_arg0, f1_arg1, f1_arg2, f1_arg3, f1_arg4, f1_arg5, f1_arg6, f1_arg7, f1_arg8, f1_arg9 )
	local self = LUI.UIElement.new( f1_arg2, f1_arg3, f1_arg4, f1_arg5, f1_arg6, f1_arg7, f1_arg8, f1_arg9 )
	self:setClass( CoD.StartMenu_Inventory_ActionIconPC )
	self.id = "StartMenu_Inventory_ActionIconPC"
	self.soundSet = "none"
	f1_arg0:addElementToPendingUpdateStateList( self )
	
	local Blur = LUI.UIImage.new( 0, 1, 0, 0, 0, 1, 0, 0 )
	Blur:setMaterial( LUI.UIImage.GetCachedMaterial( 0xE2354BE557C4C7A ) )
	Blur:setShaderVector( 0, 0, 0, 0, 0 )
	self:addElement( Blur )
	self.Blur = Blur
	
	local Background = LUI.UIImage.new( 0, 1, 0, 0, 0, 1, 0, 0 )
	Background:setRGB( 0.04, 0.04, 0.04 )
	Background:setAlpha( 0.8 )
	self:addElement( Background )
	self.Background = Background
	
	local TiledBacking = LUI.UIImage.new( 0, 1, 0, 0, 0, 1, 0, 0 )
	TiledBacking:setAlpha( 0.5 )
	TiledBacking:setImage( RegisterImage( "uie_ui_menu_specialist_hub_repeat_bg" ) )
	TiledBacking:setMaterial( LUI.UIImage.GetCachedMaterial( 0x6CBE95C250C6D15 ) )
	TiledBacking:setShaderVector( 0, 0, 0, 0, 0 )
	TiledBacking:setupNineSliceShader( 196, 88 )
	self:addElement( TiledBacking )
	self.TiledBacking = TiledBacking
	
	local Image = LUI.UIImage.new( 0, 1, 0, 0, 0, 1, 0, 0 )
	Image:setRGB( 0.74, 0.74, 0.6 )
	Image:setAlpha( 0.75 )
	Image:setImage( RegisterImage( 0x5C61B9E0BB22CF3 ) )
	self:addElement( Image )
	self.Image = Image
	
	local ItemFrameAdd = LUI.UIImage.new( 0, 1, -3, 3, 0, 1, -3, 3 )
	ItemFrameAdd:setAlpha( 0 )
	ItemFrameAdd:setImage( RegisterImage( 0xC2AE59F4FA74812 ) )
	ItemFrameAdd:setMaterial( LUI.UIImage.GetCachedMaterial( "uie_nineslice_add" ) )
	ItemFrameAdd:setShaderVector( 0, 0, 0, 0, 0 )
	ItemFrameAdd:setupNineSliceShader( 12, 164 )
	self:addElement( ItemFrameAdd )
	self.ItemFrameAdd = ItemFrameAdd
	
	local FrameSelected = LUI.UIImage.new( 0, 1, -3, 3, 0, 1, -3, 3 )
	FrameSelected:setAlpha( 0 )
	FrameSelected:setScale( 0.96, 0.96 )
	FrameSelected:setImage( RegisterImage( "uie_ui_menu_store_focus_frame" ) )
	FrameSelected:setMaterial( LUI.UIImage.GetCachedMaterial( "uie_nineslice_add" ) )
	FrameSelected:setShaderVector( 0, 0, 0, 0, 0 )
	FrameSelected:setupNineSliceShader( 4, 4 )
	self:addElement( FrameSelected )
	self.FrameSelected = FrameSelected
	
	local FrameSelectedCorner = LUI.UIImage.new( 0, 1, -10, 10, 0, 1, -10, 10 )
	FrameSelectedCorner:setAlpha( 0 )
	FrameSelectedCorner:setImage( RegisterImage( 0x793C73633F620BB ) )
	FrameSelectedCorner:setMaterial( LUI.UIImage.GetCachedMaterial( "uie_nineslice_add" ) )
	FrameSelectedCorner:setShaderVector( 0, 0, 0, 0, 0 )
	FrameSelectedCorner:setupNineSliceShader( 22, 22 )
	self:addElement( FrameSelectedCorner )
	self.FrameSelectedCorner = FrameSelectedCorner
	
	local FrontendFrame = LUI.UIImage.new( 0, 1, -1, 1, 0, 1, -1, 1 )
	FrontendFrame:setImage( RegisterImage( "uie_ui_menu_store_common_frame" ) )
	FrontendFrame:setMaterial( LUI.UIImage.GetCachedMaterial( "uie_nineslice_add" ) )
	FrontendFrame:setShaderVector( 0, 0, 0, 0, 0 )
	FrontendFrame:setupNineSliceShader( 12, 12 )
	self:addElement( FrontendFrame )
	self.FrontendFrame = FrontendFrame
	
	if PostLoadFunc then
		PostLoadFunc( self, f1_arg1, f1_arg0 )
	end
	
	return self
end

CoD.StartMenu_Inventory_ActionIconPC.__resetProperties = function ( f2_arg0 )
	f2_arg0.FrameSelectedCorner:completeAnimation()
	f2_arg0.FrameSelected:completeAnimation()
	f2_arg0.Image:completeAnimation()
	f2_arg0.FrontendFrame:completeAnimation()
	f2_arg0.ItemFrameAdd:completeAnimation()
	f2_arg0.TiledBacking:completeAnimation()
	f2_arg0.Background:completeAnimation()
	f2_arg0.Blur:completeAnimation()
	f2_arg0.FrameSelectedCorner:setLeftRight( 0, 1, -10, 10 )
	f2_arg0.FrameSelectedCorner:setTopBottom( 0, 1, -10, 10 )
	f2_arg0.FrameSelectedCorner:setAlpha( 0 )
	f2_arg0.FrameSelectedCorner:setScale( 1, 1 )
	f2_arg0.FrameSelected:setAlpha( 0 )
	f2_arg0.FrameSelected:setScale( 0.96, 0.96 )
	f2_arg0.Image:setRGB( 0.74, 0.74, 0.6 )
	f2_arg0.Image:setAlpha( 0.75 )
	f2_arg0.Image:setScale( 1, 1 )
	f2_arg0.FrontendFrame:setAlpha( 1 )
	f2_arg0.FrontendFrame:setScale( 1, 1 )
	f2_arg0.ItemFrameAdd:setAlpha( 0 )
	f2_arg0.ItemFrameAdd:setScale( 1, 1 )
	f2_arg0.TiledBacking:setAlpha( 0.5 )
	f2_arg0.TiledBacking:setScale( 1, 1 )
	f2_arg0.Background:setAlpha( 0.8 )
	f2_arg0.Background:setScale( 1, 1 )
	f2_arg0.Blur:setAlpha( 1 )
	f2_arg0.Blur:setScale( 1, 1 )
end

CoD.StartMenu_Inventory_ActionIconPC.__clipsPerState = {
	DefaultState = {
		DefaultClip = function ( f3_arg0, f3_arg1 )
			f3_arg0:__resetProperties()
			f3_arg0:setupElementClipCounter( 0 )
		end,
		Focus = function ( f4_arg0, f4_arg1 )
			f4_arg0:__resetProperties()
			f4_arg0:setupElementClipCounter( 8 )
			f4_arg0.Blur:completeAnimation()
			f4_arg0.Blur:setScale( 1.05, 1.05 )
			f4_arg0.clipFinished( f4_arg0.Blur )
			f4_arg0.Background:completeAnimation()
			f4_arg0.Background:setScale( 1.05, 1.05 )
			f4_arg0.clipFinished( f4_arg0.Background )
			f4_arg0.TiledBacking:completeAnimation()
			f4_arg0.TiledBacking:setScale( 1.05, 1.05 )
			f4_arg0.clipFinished( f4_arg0.TiledBacking )
			f4_arg0.Image:completeAnimation()
			f4_arg0.Image:setRGB( ColorSet.T8__BIEGE.r, ColorSet.T8__BIEGE.g, ColorSet.T8__BIEGE.b )
			f4_arg0.Image:setAlpha( 1 )
			f4_arg0.Image:setScale( 1.05, 1.05 )
			f4_arg0.clipFinished( f4_arg0.Image )
			f4_arg0.ItemFrameAdd:completeAnimation()
			f4_arg0.ItemFrameAdd:setScale( 1.05, 1.05 )
			f4_arg0.clipFinished( f4_arg0.ItemFrameAdd )
			f4_arg0.FrameSelected:completeAnimation()
			f4_arg0.FrameSelected:setAlpha( 1 )
			f4_arg0.FrameSelected:setScale( 1.05, 1.05 )
			f4_arg0.clipFinished( f4_arg0.FrameSelected )
			f4_arg0.FrameSelectedCorner:completeAnimation()
			f4_arg0.FrameSelectedCorner:setLeftRight( 0, 1, -6, 6 )
			f4_arg0.FrameSelectedCorner:setTopBottom( 0, 1, -6, 6 )
			f4_arg0.FrameSelectedCorner:setAlpha( 1 )
			f4_arg0.FrameSelectedCorner:setScale( 1.05, 1.05 )
			f4_arg0.clipFinished( f4_arg0.FrameSelectedCorner )
			f4_arg0.FrontendFrame:completeAnimation()
			f4_arg0.FrontendFrame:setScale( 1.05, 1.05 )
			f4_arg0.clipFinished( f4_arg0.FrontendFrame )
		end,
		GainFocus = function ( f5_arg0, f5_arg1 )
			f5_arg0:__resetProperties()
			f5_arg0:setupElementClipCounter( 8 )
			local f5_local0 = function ( f6_arg0 )
				f5_arg0.Blur:beginAnimation( 150 )
				f5_arg0.Blur:setScale( 1.05, 1.05 )
				f5_arg0.Blur:registerEventHandler( "interrupted_keyframe", f5_arg0.clipInterrupted )
				f5_arg0.Blur:registerEventHandler( "transition_complete_keyframe", f5_arg0.clipFinished )
			end
			
			f5_arg0.Blur:completeAnimation()
			f5_arg0.Blur:setScale( 1, 1 )
			f5_local0( f5_arg0.Blur )
			local f5_local1 = function ( f7_arg0 )
				f5_arg0.Background:beginAnimation( 150 )
				f5_arg0.Background:setScale( 1.05, 1.05 )
				f5_arg0.Background:registerEventHandler( "interrupted_keyframe", f5_arg0.clipInterrupted )
				f5_arg0.Background:registerEventHandler( "transition_complete_keyframe", f5_arg0.clipFinished )
			end
			
			f5_arg0.Background:completeAnimation()
			f5_arg0.Background:setScale( 1, 1 )
			f5_local1( f5_arg0.Background )
			local f5_local2 = function ( f8_arg0 )
				f5_arg0.TiledBacking:beginAnimation( 150 )
				f5_arg0.TiledBacking:setScale( 1.05, 1.05 )
				f5_arg0.TiledBacking:registerEventHandler( "interrupted_keyframe", f5_arg0.clipInterrupted )
				f5_arg0.TiledBacking:registerEventHandler( "transition_complete_keyframe", f5_arg0.clipFinished )
			end
			
			f5_arg0.TiledBacking:completeAnimation()
			f5_arg0.TiledBacking:setScale( 1, 1 )
			f5_local2( f5_arg0.TiledBacking )
			local f5_local3 = function ( f9_arg0 )
				f5_arg0.Image:beginAnimation( 150 )
				f5_arg0.Image:setRGB( ColorSet.T8__BIEGE.r, ColorSet.T8__BIEGE.g, ColorSet.T8__BIEGE.b )
				f5_arg0.Image:setAlpha( 1 )
				f5_arg0.Image:setScale( 1.05, 1.05 )
				f5_arg0.Image:registerEventHandler( "interrupted_keyframe", f5_arg0.clipInterrupted )
				f5_arg0.Image:registerEventHandler( "transition_complete_keyframe", f5_arg0.clipFinished )
			end
			
			f5_arg0.Image:completeAnimation()
			f5_arg0.Image:setRGB( 0.74, 0.74, 0.6 )
			f5_arg0.Image:setAlpha( 0.75 )
			f5_arg0.Image:setScale( 1, 1 )
			f5_local3( f5_arg0.Image )
			local f5_local4 = function ( f10_arg0 )
				f5_arg0.ItemFrameAdd:beginAnimation( 150 )
				f5_arg0.ItemFrameAdd:setScale( 1.05, 1.05 )
				f5_arg0.ItemFrameAdd:registerEventHandler( "interrupted_keyframe", f5_arg0.clipInterrupted )
				f5_arg0.ItemFrameAdd:registerEventHandler( "transition_complete_keyframe", f5_arg0.clipFinished )
			end
			
			f5_arg0.ItemFrameAdd:completeAnimation()
			f5_arg0.ItemFrameAdd:setScale( 1, 1 )
			f5_local4( f5_arg0.ItemFrameAdd )
			local f5_local5 = function ( f11_arg0 )
				f5_arg0.FrameSelected:beginAnimation( 150 )
				f5_arg0.FrameSelected:setAlpha( 1 )
				f5_arg0.FrameSelected:setScale( 1.05, 1.05 )
				f5_arg0.FrameSelected:registerEventHandler( "interrupted_keyframe", f5_arg0.clipInterrupted )
				f5_arg0.FrameSelected:registerEventHandler( "transition_complete_keyframe", f5_arg0.clipFinished )
			end
			
			f5_arg0.FrameSelected:completeAnimation()
			f5_arg0.FrameSelected:setAlpha( 0 )
			f5_arg0.FrameSelected:setScale( 0.96, 0.96 )
			f5_local5( f5_arg0.FrameSelected )
			local f5_local6 = function ( f12_arg0 )
				f5_arg0.FrameSelectedCorner:beginAnimation( 150 )
				f5_arg0.FrameSelectedCorner:setLeftRight( 0, 1, -6, 6 )
				f5_arg0.FrameSelectedCorner:setTopBottom( 0, 1, -6, 6 )
				f5_arg0.FrameSelectedCorner:setAlpha( 1 )
				f5_arg0.FrameSelectedCorner:setScale( 1.05, 1.05 )
				f5_arg0.FrameSelectedCorner:registerEventHandler( "interrupted_keyframe", f5_arg0.clipInterrupted )
				f5_arg0.FrameSelectedCorner:registerEventHandler( "transition_complete_keyframe", f5_arg0.clipFinished )
			end
			
			f5_arg0.FrameSelectedCorner:completeAnimation()
			f5_arg0.FrameSelectedCorner:setLeftRight( 0, 1, -10, 10 )
			f5_arg0.FrameSelectedCorner:setTopBottom( 0, 1, -10, 10 )
			f5_arg0.FrameSelectedCorner:setAlpha( 0 )
			f5_arg0.FrameSelectedCorner:setScale( 1, 1 )
			f5_local6( f5_arg0.FrameSelectedCorner )
			local f5_local7 = function ( f13_arg0 )
				f5_arg0.FrontendFrame:beginAnimation( 150 )
				f5_arg0.FrontendFrame:setScale( 1.05, 1.05 )
				f5_arg0.FrontendFrame:registerEventHandler( "interrupted_keyframe", f5_arg0.clipInterrupted )
				f5_arg0.FrontendFrame:registerEventHandler( "transition_complete_keyframe", f5_arg0.clipFinished )
			end
			
			f5_arg0.FrontendFrame:completeAnimation()
			f5_arg0.FrontendFrame:setScale( 1, 1 )
			f5_local7( f5_arg0.FrontendFrame )
		end,
		LoseFocus = function ( f14_arg0, f14_arg1 )
			f14_arg0:__resetProperties()
			f14_arg0:setupElementClipCounter( 8 )
			local f14_local0 = function ( f15_arg0 )
				f14_arg0.Blur:beginAnimation( 150 )
				f14_arg0.Blur:setScale( 1, 1 )
				f14_arg0.Blur:registerEventHandler( "interrupted_keyframe", f14_arg0.clipInterrupted )
				f14_arg0.Blur:registerEventHandler( "transition_complete_keyframe", f14_arg0.clipFinished )
			end
			
			f14_arg0.Blur:completeAnimation()
			f14_arg0.Blur:setScale( 1.05, 1.05 )
			f14_local0( f14_arg0.Blur )
			local f14_local1 = function ( f16_arg0 )
				f14_arg0.Background:beginAnimation( 150 )
				f14_arg0.Background:setScale( 1, 1 )
				f14_arg0.Background:registerEventHandler( "interrupted_keyframe", f14_arg0.clipInterrupted )
				f14_arg0.Background:registerEventHandler( "transition_complete_keyframe", f14_arg0.clipFinished )
			end
			
			f14_arg0.Background:completeAnimation()
			f14_arg0.Background:setScale( 1.05, 1.05 )
			f14_local1( f14_arg0.Background )
			local f14_local2 = function ( f17_arg0 )
				f14_arg0.TiledBacking:beginAnimation( 150 )
				f14_arg0.TiledBacking:setScale( 1, 1 )
				f14_arg0.TiledBacking:registerEventHandler( "interrupted_keyframe", f14_arg0.clipInterrupted )
				f14_arg0.TiledBacking:registerEventHandler( "transition_complete_keyframe", f14_arg0.clipFinished )
			end
			
			f14_arg0.TiledBacking:completeAnimation()
			f14_arg0.TiledBacking:setScale( 1.05, 1.05 )
			f14_local2( f14_arg0.TiledBacking )
			local f14_local3 = function ( f18_arg0 )
				f14_arg0.Image:beginAnimation( 150 )
				f14_arg0.Image:setRGB( 0.74, 0.74, 0.6 )
				f14_arg0.Image:setAlpha( 0.75 )
				f14_arg0.Image:setScale( 1, 1 )
				f14_arg0.Image:registerEventHandler( "interrupted_keyframe", f14_arg0.clipInterrupted )
				f14_arg0.Image:registerEventHandler( "transition_complete_keyframe", f14_arg0.clipFinished )
			end
			
			f14_arg0.Image:completeAnimation()
			f14_arg0.Image:setRGB( ColorSet.T8__BIEGE.r, ColorSet.T8__BIEGE.g, ColorSet.T8__BIEGE.b )
			f14_arg0.Image:setAlpha( 1 )
			f14_arg0.Image:setScale( 1.05, 1.05 )
			f14_local3( f14_arg0.Image )
			local f14_local4 = function ( f19_arg0 )
				f14_arg0.ItemFrameAdd:beginAnimation( 150 )
				f14_arg0.ItemFrameAdd:setScale( 1, 1 )
				f14_arg0.ItemFrameAdd:registerEventHandler( "interrupted_keyframe", f14_arg0.clipInterrupted )
				f14_arg0.ItemFrameAdd:registerEventHandler( "transition_complete_keyframe", f14_arg0.clipFinished )
			end
			
			f14_arg0.ItemFrameAdd:completeAnimation()
			f14_arg0.ItemFrameAdd:setScale( 1.05, 1.05 )
			f14_local4( f14_arg0.ItemFrameAdd )
			local f14_local5 = function ( f20_arg0 )
				f14_arg0.FrameSelected:beginAnimation( 150 )
				f14_arg0.FrameSelected:setAlpha( 0 )
				f14_arg0.FrameSelected:setScale( 0.96, 0.96 )
				f14_arg0.FrameSelected:registerEventHandler( "interrupted_keyframe", f14_arg0.clipInterrupted )
				f14_arg0.FrameSelected:registerEventHandler( "transition_complete_keyframe", f14_arg0.clipFinished )
			end
			
			f14_arg0.FrameSelected:completeAnimation()
			f14_arg0.FrameSelected:setAlpha( 1 )
			f14_arg0.FrameSelected:setScale( 1.05, 1.05 )
			f14_local5( f14_arg0.FrameSelected )
			local f14_local6 = function ( f21_arg0 )
				f14_arg0.FrameSelectedCorner:beginAnimation( 150 )
				f14_arg0.FrameSelectedCorner:setLeftRight( 0, 1, -10, 10 )
				f14_arg0.FrameSelectedCorner:setTopBottom( 0, 1, -10, 10 )
				f14_arg0.FrameSelectedCorner:setAlpha( 0 )
				f14_arg0.FrameSelectedCorner:setScale( 1, 1 )
				f14_arg0.FrameSelectedCorner:registerEventHandler( "interrupted_keyframe", f14_arg0.clipInterrupted )
				f14_arg0.FrameSelectedCorner:registerEventHandler( "transition_complete_keyframe", f14_arg0.clipFinished )
			end
			
			f14_arg0.FrameSelectedCorner:completeAnimation()
			f14_arg0.FrameSelectedCorner:setLeftRight( 0, 1, -6, 6 )
			f14_arg0.FrameSelectedCorner:setTopBottom( 0, 1, -6, 6 )
			f14_arg0.FrameSelectedCorner:setAlpha( 1 )
			f14_arg0.FrameSelectedCorner:setScale( 1.05, 1.05 )
			f14_local6( f14_arg0.FrameSelectedCorner )
			local f14_local7 = function ( f22_arg0 )
				f14_arg0.FrontendFrame:beginAnimation( 150 )
				f14_arg0.FrontendFrame:setScale( 1, 1 )
				f14_arg0.FrontendFrame:registerEventHandler( "interrupted_keyframe", f14_arg0.clipInterrupted )
				f14_arg0.FrontendFrame:registerEventHandler( "transition_complete_keyframe", f14_arg0.clipFinished )
			end
			
			f14_arg0.FrontendFrame:completeAnimation()
			f14_arg0.FrontendFrame:setScale( 1.05, 1.05 )
			f14_local7( f14_arg0.FrontendFrame )
		end
	},
	Hidden = {
		DefaultClip = function ( f23_arg0, f23_arg1 )
			f23_arg0:__resetProperties()
			f23_arg0:setupElementClipCounter( 8 )
			f23_arg0.Blur:completeAnimation()
			f23_arg0.Blur:setAlpha( 0 )
			f23_arg0.clipFinished( f23_arg0.Blur )
			f23_arg0.Background:completeAnimation()
			f23_arg0.Background:setAlpha( 0 )
			f23_arg0.clipFinished( f23_arg0.Background )
			f23_arg0.TiledBacking:completeAnimation()
			f23_arg0.TiledBacking:setAlpha( 0 )
			f23_arg0.clipFinished( f23_arg0.TiledBacking )
			f23_arg0.Image:completeAnimation()
			f23_arg0.Image:setAlpha( 0 )
			f23_arg0.clipFinished( f23_arg0.Image )
			f23_arg0.ItemFrameAdd:completeAnimation()
			f23_arg0.ItemFrameAdd:setAlpha( 0 )
			f23_arg0.clipFinished( f23_arg0.ItemFrameAdd )
			f23_arg0.FrameSelected:completeAnimation()
			f23_arg0.FrameSelected:setAlpha( 0 )
			f23_arg0.clipFinished( f23_arg0.FrameSelected )
			f23_arg0.FrameSelectedCorner:completeAnimation()
			f23_arg0.FrameSelectedCorner:setAlpha( 0 )
			f23_arg0.clipFinished( f23_arg0.FrameSelectedCorner )
			f23_arg0.FrontendFrame:completeAnimation()
			f23_arg0.FrontendFrame:setAlpha( 0 )
			f23_arg0.clipFinished( f23_arg0.FrontendFrame )
		end
	}
}
