require( "x64:74528d4953cad98" )
require( "x64:d5d426adda1391a" )

CoD.SpawnSelectionLabelWarning = InheritFrom( LUI.UIElement )
CoD.SpawnSelectionLabelWarning.__defaultWidth = 155
CoD.SpawnSelectionLabelWarning.__defaultHeight = 20
CoD.SpawnSelectionLabelWarning.new = function ( f1_arg0, f1_arg1, f1_arg2, f1_arg3, f1_arg4, f1_arg5, f1_arg6, f1_arg7, f1_arg8, f1_arg9 )
	local self = LUI.UIElement.new( f1_arg2, f1_arg3, f1_arg4, f1_arg5, f1_arg6, f1_arg7, f1_arg8, f1_arg9 )
	self:setClass( CoD.SpawnSelectionLabelWarning )
	self.id = "SpawnSelectionLabelWarning"
	self.soundSet = "default"
	self.anyChildUsesUpdateState = true
	f1_arg0:addElementToPendingUpdateStateList( self )
	
	local SpawnDetailBacking = LUI.UIImage.new( 0, 0, -25, 155, 0, 0, -8, 16 )
	SpawnDetailBacking:setRGB( 0.1, 0.1, 0.1 )
	SpawnDetailBacking:setAlpha( 0 )
	self:addElement( SpawnDetailBacking )
	self.SpawnDetailBacking = SpawnDetailBacking
	
	local Glow = LUI.UIImage.new( 0, 0, -121, 251, 0, 0, -76, 84 )
	Glow:setAlpha( 0 )
	Glow:setImage( RegisterImage( "uie_ui_menu_common_tab_glowred" ) )
	Glow:setMaterial( LUI.UIImage.GetCachedMaterial( "ui_add" ) )
	self:addElement( Glow )
	self.Glow = Glow
	
	local SpawnWarningStripeLoop = CoD.SpawnSelectInfoStripe.new( f1_arg0, f1_arg1, 0, 0, -25, 155, 0, 0, 16, 20 )
	SpawnWarningStripeLoop:mergeStateConditions( {
		{
			stateName = "ThreatHigh",
			condition = function ( menu, element, event )
				return CoD.ModelUtility.IsSelfModelValueEqualTo( self, f1_arg1, "gamemodeFlags", 2 )
			end
		},
		{
			stateName = "ThreatLow",
			condition = function ( menu, element, event )
				return CoD.ModelUtility.IsSelfModelValueEqualTo( self, f1_arg1, "gamemodeFlags", 1 )
			end
		},
		{
			stateName = "Destroyed",
			condition = function ( menu, element, event )
				return CoD.SpawnSelectionUtility.IsSpawnBeaconDisabledOrDestroyed( f1_arg1, element )
			end
		}
	} )
	SpawnWarningStripeLoop:linkToElementModel( SpawnWarningStripeLoop, "gamemodeFlags", true, function ( model )
		f1_arg0:updateElementState( SpawnWarningStripeLoop, {
			name = "model_validation",
			menu = f1_arg0,
			controller = f1_arg1,
			modelValue = model:get(),
			modelName = "gamemodeFlags"
		} )
	end )
	SpawnWarningStripeLoop:linkToElementModel( SpawnWarningStripeLoop, "state", true, function ( model )
		f1_arg0:updateElementState( SpawnWarningStripeLoop, {
			name = "model_validation",
			menu = f1_arg0,
			controller = f1_arg1,
			modelValue = model:get(),
			modelName = "state"
		} )
	end )
	SpawnWarningStripeLoop:setAlpha( 0 )
	SpawnWarningStripeLoop:linkToElementModel( self, nil, false, function ( model )
		SpawnWarningStripeLoop:setModel( model, f1_arg1 )
	end )
	self:addElement( SpawnWarningStripeLoop )
	self.SpawnWarningStripeLoop = SpawnWarningStripeLoop
	
	local SpawnSituation = LUI.UIText.new( 0, 0, -25, 155, 0, 0, -4.5, 16.5 )
	SpawnSituation:setRGB( 1, 0, 0 )
	SpawnSituation:setAlpha( 0 )
	SpawnSituation:setText( Engine[0xF9F1239CFD921FE]( "mpui/danger" ) )
	SpawnSituation:setTTF( "0arame_mono_stencil" )
	SpawnSituation:setAlignment( Enum.LUIAlignment[0xFEEB12BCB0D7041] )
	SpawnSituation:setAlignment( Enum.LUIAlignment[0xE821F0ECFF8D1C7] )
	self:addElement( SpawnSituation )
	self.SpawnSituation = SpawnSituation
	
	local SpawnWarningArrowL = CoD.SpawnSelectInfoArrow.new( f1_arg0, f1_arg1, 0, 0, -19, -5, 0, 0, 2, 10 )
	SpawnWarningArrowL:setAlpha( 0 )
	SpawnWarningArrowL:setZRot( -90 )
	SpawnWarningArrowL:setScale( 1.5, 1.5 )
	SpawnWarningArrowL:linkToElementModel( self, nil, false, function ( model )
		SpawnWarningArrowL:setModel( model, f1_arg1 )
	end )
	self:addElement( SpawnWarningArrowL )
	self.SpawnWarningArrowL = SpawnWarningArrowL
	
	local SpawnWarningArrowR = CoD.SpawnSelectInfoArrow.new( f1_arg0, f1_arg1, 0, 0, 135, 149, 0, 0, 2, 10 )
	SpawnWarningArrowR:setAlpha( 0 )
	SpawnWarningArrowR:setZRot( -90 )
	SpawnWarningArrowR:setScale( 1.5, 1.5 )
	SpawnWarningArrowR:linkToElementModel( self, nil, false, function ( model )
		SpawnWarningArrowR:setModel( model, f1_arg1 )
	end )
	self:addElement( SpawnWarningArrowR )
	self.SpawnWarningArrowR = SpawnWarningArrowR
	
	self:mergeStateConditions( {
		{
			stateName = "Disabled",
			condition = function ( menu, element, event )
				return CoD.SpawnSelectionUtility.IsSpawnBeaconActive( f1_arg1, element ) and CoD.ModelUtility.IsSelfModelValueEqualTo( self, f1_arg1, "gamemodeFlags", 4 )
			end
		},
		{
			stateName = "Destroyed",
			condition = function ( menu, element, event )
				return not CoD.SpawnSelectionUtility.IsSpawnBeaconActive( f1_arg1, element )
			end
		},
		{
			stateName = "ThreatHigh",
			condition = function ( menu, element, event )
				return CoD.ModelUtility.IsSelfModelValueEqualTo( self, f1_arg1, "gamemodeFlags", 2 )
			end
		},
		{
			stateName = "ThreatLow",
			condition = function ( menu, element, event )
				return CoD.ModelUtility.IsSelfModelValueEqualTo( self, f1_arg1, "gamemodeFlags", 1 )
			end
		},
		{
			stateName = "Hidden",
			condition = function ( menu, element, event )
				return AlwaysTrue()
			end
		}
	} )
	self:linkToElementModel( self, "state", true, function ( model )
		f1_arg0:updateElementState( self, {
			name = "model_validation",
			menu = f1_arg0,
			controller = f1_arg1,
			modelValue = model:get(),
			modelName = "state"
		} )
	end )
	self:linkToElementModel( self, "gamemodeFlags", true, function ( model )
		f1_arg0:updateElementState( self, {
			name = "model_validation",
			menu = f1_arg0,
			controller = f1_arg1,
			modelValue = model:get(),
			modelName = "gamemodeFlags"
		} )
	end )
	LUI.OverrideFunction_CallOriginalSecond( self, "close", self.__onClose )
	
	if PostLoadFunc then
		PostLoadFunc( self, f1_arg1, f1_arg0 )
	end
	
	return self
end

CoD.SpawnSelectionLabelWarning.__resetProperties = function ( f17_arg0 )
	f17_arg0.SpawnSituation:completeAnimation()
	f17_arg0.SpawnWarningArrowR:completeAnimation()
	f17_arg0.SpawnWarningArrowL:completeAnimation()
	f17_arg0.SpawnDetailBacking:completeAnimation()
	f17_arg0.SpawnWarningStripeLoop:completeAnimation()
	f17_arg0.Glow:completeAnimation()
	f17_arg0.SpawnSituation:setLeftRight( 0, 0, -25, 155 )
	f17_arg0.SpawnSituation:setTopBottom( 0, 0, -4.5, 16.5 )
	f17_arg0.SpawnSituation:setRGB( 1, 0, 0 )
	f17_arg0.SpawnSituation:setAlpha( 0 )
	f17_arg0.SpawnSituation:setText( Engine[0xF9F1239CFD921FE]( "mpui/danger" ) )
	f17_arg0.SpawnSituation:setLetterSpacing( 0 )
	f17_arg0.SpawnWarningArrowR:setLeftRight( 0, 0, 135, 149 )
	f17_arg0.SpawnWarningArrowR:setTopBottom( 0, 0, 2, 10 )
	f17_arg0.SpawnWarningArrowR:setAlpha( 0 )
	f17_arg0.SpawnWarningArrowL:setLeftRight( 0, 0, -19, -5 )
	f17_arg0.SpawnWarningArrowL:setTopBottom( 0, 0, 2, 10 )
	f17_arg0.SpawnWarningArrowL:setAlpha( 0 )
	f17_arg0.SpawnDetailBacking:setTopBottom( 0, 0, -8, 16 )
	f17_arg0.SpawnDetailBacking:setAlpha( 0 )
	f17_arg0.SpawnWarningStripeLoop:setLeftRight( 0, 0, -25, 155 )
	f17_arg0.SpawnWarningStripeLoop:setTopBottom( 0, 0, 16, 20 )
	f17_arg0.SpawnWarningStripeLoop:setAlpha( 0 )
	f17_arg0.Glow:setAlpha( 0 )
end

CoD.SpawnSelectionLabelWarning.__clipsPerState = {
	DefaultState = {
		DefaultClip = function ( f18_arg0, f18_arg1 )
			f18_arg0:__resetProperties()
			f18_arg0:setupElementClipCounter( 5 )
			f18_arg0.SpawnDetailBacking:completeAnimation()
			f18_arg0.SpawnDetailBacking:setTopBottom( 0, 0, 0, 0 )
			f18_arg0.clipFinished( f18_arg0.SpawnDetailBacking )
			f18_arg0.SpawnWarningStripeLoop:completeAnimation()
			f18_arg0.SpawnWarningStripeLoop:setAlpha( 0 )
			f18_arg0.clipFinished( f18_arg0.SpawnWarningStripeLoop )
			f18_arg0.SpawnSituation:completeAnimation()
			f18_arg0.SpawnSituation:setLeftRight( 0, 0, -35, 165 )
			f18_arg0.SpawnSituation:setTopBottom( 0, 0, 0, 16 )
			f18_arg0.SpawnSituation:setAlpha( 0 )
			f18_arg0.SpawnSituation:setText( Engine[0xF9F1239CFD921FE]( "mpui/danger" ) )
			f18_arg0.clipFinished( f18_arg0.SpawnSituation )
			f18_arg0.SpawnWarningArrowL:completeAnimation()
			f18_arg0.SpawnWarningArrowL:setAlpha( 0 )
			f18_arg0.clipFinished( f18_arg0.SpawnWarningArrowL )
			f18_arg0.SpawnWarningArrowR:completeAnimation()
			f18_arg0.SpawnWarningArrowR:setAlpha( 0 )
			f18_arg0.clipFinished( f18_arg0.SpawnWarningArrowR )
		end
	},
	Disabled = {
		DefaultClip = function ( f19_arg0, f19_arg1 )
			f19_arg0:__resetProperties()
			f19_arg0:setupElementClipCounter( 5 )
			f19_arg0.SpawnDetailBacking:completeAnimation()
			f19_arg0.SpawnDetailBacking:setAlpha( 1 )
			f19_arg0.clipFinished( f19_arg0.SpawnDetailBacking )
			f19_arg0.SpawnWarningStripeLoop:completeAnimation()
			f19_arg0.SpawnWarningStripeLoop:setAlpha( 0 )
			f19_arg0.SpawnWarningStripeLoop:playClip( "DefaultClip" )
			f19_arg0.clipFinished( f19_arg0.SpawnWarningStripeLoop )
			f19_arg0.SpawnSituation:completeAnimation()
			f19_arg0.SpawnSituation:setLeftRight( 0, 0, -25, 155 )
			f19_arg0.SpawnSituation:setTopBottom( 0, 0, 0, 16 )
			f19_arg0.SpawnSituation:setRGB( ColorSet.Disabled.r, ColorSet.Disabled.g, ColorSet.Disabled.b )
			f19_arg0.SpawnSituation:setAlpha( 1 )
			f19_arg0.SpawnSituation:setText( Engine[0xF9F1239CFD921FE]( "mpui/unavailable" ) )
			f19_arg0.SpawnSituation:setLetterSpacing( 0 )
			f19_arg0.clipFinished( f19_arg0.SpawnSituation )
			f19_arg0.SpawnWarningArrowL:completeAnimation()
			f19_arg0.SpawnWarningArrowL:setLeftRight( 0, 0, 1, 15 )
			f19_arg0.SpawnWarningArrowL:setTopBottom( 0, 0, 4, 12 )
			f19_arg0.SpawnWarningArrowL:setAlpha( 0 )
			f19_arg0.clipFinished( f19_arg0.SpawnWarningArrowL )
			f19_arg0.SpawnWarningArrowR:completeAnimation()
			f19_arg0.SpawnWarningArrowR:setLeftRight( 0, 0, 115, 129 )
			f19_arg0.SpawnWarningArrowR:setTopBottom( 0, 0, 4, 12 )
			f19_arg0.SpawnWarningArrowR:setAlpha( 0 )
			f19_arg0.clipFinished( f19_arg0.SpawnWarningArrowR )
		end,
		Focused = function ( f20_arg0, f20_arg1 )
			f20_arg0:__resetProperties()
			f20_arg0:setupElementClipCounter( 5 )
			f20_arg0.SpawnDetailBacking:completeAnimation()
			f20_arg0.SpawnDetailBacking:setAlpha( 1 )
			f20_arg0.clipFinished( f20_arg0.SpawnDetailBacking )
			f20_arg0.SpawnWarningStripeLoop:completeAnimation()
			f20_arg0.SpawnWarningStripeLoop:setAlpha( 0 )
			f20_arg0.SpawnWarningStripeLoop:playClip( "DefaultClip" )
			f20_arg0.clipFinished( f20_arg0.SpawnWarningStripeLoop )
			f20_arg0.SpawnSituation:completeAnimation()
			f20_arg0.SpawnSituation:setLeftRight( 0, 0, -25, 155 )
			f20_arg0.SpawnSituation:setTopBottom( 0, 0, -1, 17 )
			f20_arg0.SpawnSituation:setRGB( ColorSet.Disabled.r, ColorSet.Disabled.g, ColorSet.Disabled.b )
			f20_arg0.SpawnSituation:setAlpha( 1 )
			f20_arg0.SpawnSituation:setText( Engine[0xF9F1239CFD921FE]( "mpui/unavailable" ) )
			f20_arg0.SpawnSituation:setLetterSpacing( 0 )
			f20_arg0.clipFinished( f20_arg0.SpawnSituation )
			f20_arg0.SpawnWarningArrowL:completeAnimation()
			f20_arg0.SpawnWarningArrowL:setLeftRight( 0, 0, 1, 15 )
			f20_arg0.SpawnWarningArrowL:setTopBottom( 0, 0, 4, 12 )
			f20_arg0.SpawnWarningArrowL:setAlpha( 0 )
			f20_arg0.SpawnWarningArrowL:playClip( "DefaultClip" )
			f20_arg0.clipFinished( f20_arg0.SpawnWarningArrowL )
			f20_arg0.SpawnWarningArrowR:completeAnimation()
			f20_arg0.SpawnWarningArrowR:setLeftRight( 0, 0, 115, 129 )
			f20_arg0.SpawnWarningArrowR:setTopBottom( 0, 0, 4, 12 )
			f20_arg0.SpawnWarningArrowR:setAlpha( 0 )
			f20_arg0.SpawnWarningArrowR:playClip( "DefaultClip" )
			f20_arg0.clipFinished( f20_arg0.SpawnWarningArrowR )
		end,
		TransitionGainFocus = function ( f21_arg0, f21_arg1 )
			f21_arg0:__resetProperties()
			f21_arg0:setupElementClipCounter( 5 )
			f21_arg0.SpawnDetailBacking:completeAnimation()
			f21_arg0.SpawnDetailBacking:setAlpha( 1 )
			f21_arg0.clipFinished( f21_arg0.SpawnDetailBacking )
			f21_arg0.SpawnWarningStripeLoop:completeAnimation()
			f21_arg0.SpawnWarningStripeLoop:setAlpha( 0 )
			f21_arg0.SpawnWarningStripeLoop:playClip( "DefaultClip" )
			f21_arg0.clipFinished( f21_arg0.SpawnWarningStripeLoop )
			local f21_local0 = function ( f22_arg0 )
				f21_arg0.SpawnSituation:beginAnimation( 100 )
				f21_arg0.SpawnSituation:setTopBottom( 0, 0, -1, 17 )
				f21_arg0.SpawnSituation:registerEventHandler( "interrupted_keyframe", f21_arg0.clipInterrupted )
				f21_arg0.SpawnSituation:registerEventHandler( "transition_complete_keyframe", f21_arg0.clipFinished )
			end
			
			f21_arg0.SpawnSituation:completeAnimation()
			f21_arg0.SpawnSituation:setLeftRight( 0, 0, -25, 155 )
			f21_arg0.SpawnSituation:setTopBottom( 0, 0, 0, 16 )
			f21_arg0.SpawnSituation:setRGB( ColorSet.Disabled.r, ColorSet.Disabled.g, ColorSet.Disabled.b )
			f21_arg0.SpawnSituation:setAlpha( 1 )
			f21_arg0.SpawnSituation:setText( Engine[0xF9F1239CFD921FE]( "mpui/unavailable" ) )
			f21_arg0.SpawnSituation:setLetterSpacing( 0 )
			f21_local0( f21_arg0.SpawnSituation )
			f21_arg0.SpawnWarningArrowL:completeAnimation()
			f21_arg0.SpawnWarningArrowL:setLeftRight( 0, 0, 1, 15 )
			f21_arg0.SpawnWarningArrowL:setTopBottom( 0, 0, 4, 12 )
			f21_arg0.SpawnWarningArrowL:setAlpha( 0 )
			f21_arg0.SpawnWarningArrowL:playClip( "DefaultClip" )
			f21_arg0.clipFinished( f21_arg0.SpawnWarningArrowL )
			f21_arg0.SpawnWarningArrowR:completeAnimation()
			f21_arg0.SpawnWarningArrowR:setLeftRight( 0, 0, 115, 129 )
			f21_arg0.SpawnWarningArrowR:setTopBottom( 0, 0, 4, 12 )
			f21_arg0.SpawnWarningArrowR:setAlpha( 0 )
			f21_arg0.SpawnWarningArrowR:playClip( "DefaultClip" )
			f21_arg0.clipFinished( f21_arg0.SpawnWarningArrowR )
		end,
		TransitionLoseFocus = function ( f23_arg0, f23_arg1 )
			f23_arg0:__resetProperties()
			f23_arg0:setupElementClipCounter( 5 )
			f23_arg0.SpawnDetailBacking:completeAnimation()
			f23_arg0.SpawnDetailBacking:setAlpha( 1 )
			f23_arg0.clipFinished( f23_arg0.SpawnDetailBacking )
			f23_arg0.SpawnWarningStripeLoop:completeAnimation()
			f23_arg0.SpawnWarningStripeLoop:setAlpha( 0 )
			f23_arg0.SpawnWarningStripeLoop:playClip( "DefaultClip" )
			f23_arg0.clipFinished( f23_arg0.SpawnWarningStripeLoop )
			local f23_local0 = function ( f24_arg0 )
				f23_arg0.SpawnSituation:beginAnimation( 100 )
				f23_arg0.SpawnSituation:setTopBottom( 0, 0, 0, 16 )
				f23_arg0.SpawnSituation:registerEventHandler( "interrupted_keyframe", f23_arg0.clipInterrupted )
				f23_arg0.SpawnSituation:registerEventHandler( "transition_complete_keyframe", f23_arg0.clipFinished )
			end
			
			f23_arg0.SpawnSituation:completeAnimation()
			f23_arg0.SpawnSituation:setLeftRight( 0, 0, -25, 155 )
			f23_arg0.SpawnSituation:setTopBottom( 0, 0, -1, 17 )
			f23_arg0.SpawnSituation:setRGB( ColorSet.Disabled.r, ColorSet.Disabled.g, ColorSet.Disabled.b )
			f23_arg0.SpawnSituation:setAlpha( 1 )
			f23_arg0.SpawnSituation:setText( Engine[0xF9F1239CFD921FE]( "mpui/unavailable" ) )
			f23_arg0.SpawnSituation:setLetterSpacing( 0 )
			f23_local0( f23_arg0.SpawnSituation )
			f23_arg0.SpawnWarningArrowL:completeAnimation()
			f23_arg0.SpawnWarningArrowL:setLeftRight( 0, 0, 1, 15 )
			f23_arg0.SpawnWarningArrowL:setTopBottom( 0, 0, 4, 12 )
			f23_arg0.SpawnWarningArrowL:setAlpha( 0 )
			f23_arg0.SpawnWarningArrowL:playClip( "DefaultClip" )
			f23_arg0.clipFinished( f23_arg0.SpawnWarningArrowL )
			f23_arg0.SpawnWarningArrowR:completeAnimation()
			f23_arg0.SpawnWarningArrowR:setLeftRight( 0, 0, 115, 129 )
			f23_arg0.SpawnWarningArrowR:setTopBottom( 0, 0, 4, 12 )
			f23_arg0.SpawnWarningArrowR:setAlpha( 0 )
			f23_arg0.SpawnWarningArrowR:playClip( "DefaultClip" )
			f23_arg0.clipFinished( f23_arg0.SpawnWarningArrowR )
		end
	},
	Destroyed = {
		DefaultClip = function ( f25_arg0, f25_arg1 )
			f25_arg0:__resetProperties()
			f25_arg0:setupElementClipCounter( 5 )
			f25_arg0.SpawnDetailBacking:completeAnimation()
			f25_arg0.SpawnDetailBacking:setAlpha( 1 )
			f25_arg0.clipFinished( f25_arg0.SpawnDetailBacking )
			f25_arg0.SpawnWarningStripeLoop:completeAnimation()
			f25_arg0.SpawnWarningStripeLoop:setAlpha( 1 )
			f25_arg0.SpawnWarningStripeLoop:playClip( "DefaultClip" )
			f25_arg0.clipFinished( f25_arg0.SpawnWarningStripeLoop )
			f25_arg0.SpawnSituation:completeAnimation()
			f25_arg0.SpawnSituation:setLeftRight( 0, 0, -25, 155 )
			f25_arg0.SpawnSituation:setTopBottom( 0, 0, 0, 16 )
			f25_arg0.SpawnSituation:setRGB( ColorSet.Disabled.r, ColorSet.Disabled.g, ColorSet.Disabled.b )
			f25_arg0.SpawnSituation:setAlpha( 1 )
			f25_arg0.SpawnSituation:setText( Engine[0xF9F1239CFD921FE]( "mpui/destroyed" ) )
			f25_arg0.SpawnSituation:setLetterSpacing( 0 )
			f25_arg0.clipFinished( f25_arg0.SpawnSituation )
			f25_arg0.SpawnWarningArrowL:completeAnimation()
			f25_arg0.SpawnWarningArrowL:setLeftRight( 0, 0, 1, 15 )
			f25_arg0.SpawnWarningArrowL:setTopBottom( 0, 0, 4, 12 )
			f25_arg0.SpawnWarningArrowL:setAlpha( 0 )
			f25_arg0.clipFinished( f25_arg0.SpawnWarningArrowL )
			f25_arg0.SpawnWarningArrowR:completeAnimation()
			f25_arg0.SpawnWarningArrowR:setLeftRight( 0, 0, 115, 129 )
			f25_arg0.SpawnWarningArrowR:setTopBottom( 0, 0, 4, 12 )
			f25_arg0.SpawnWarningArrowR:setAlpha( 0 )
			f25_arg0.clipFinished( f25_arg0.SpawnWarningArrowR )
		end,
		Focused = function ( f26_arg0, f26_arg1 )
			f26_arg0:__resetProperties()
			f26_arg0:setupElementClipCounter( 5 )
			f26_arg0.SpawnDetailBacking:completeAnimation()
			f26_arg0.SpawnDetailBacking:setAlpha( 1 )
			f26_arg0.clipFinished( f26_arg0.SpawnDetailBacking )
			f26_arg0.SpawnWarningStripeLoop:completeAnimation()
			f26_arg0.SpawnWarningStripeLoop:setLeftRight( 0, 0, -25, 155 )
			f26_arg0.SpawnWarningStripeLoop:setTopBottom( 0, 0, 16, 20 )
			f26_arg0.SpawnWarningStripeLoop:setAlpha( 1 )
			f26_arg0.SpawnWarningStripeLoop:playClip( "DefaultClip" )
			f26_arg0.clipFinished( f26_arg0.SpawnWarningStripeLoop )
			f26_arg0.SpawnSituation:completeAnimation()
			f26_arg0.SpawnSituation:setLeftRight( 0, 0, -25, 155 )
			f26_arg0.SpawnSituation:setTopBottom( 0, 0, -1, 17 )
			f26_arg0.SpawnSituation:setRGB( ColorSet.Disabled.r, ColorSet.Disabled.g, ColorSet.Disabled.b )
			f26_arg0.SpawnSituation:setAlpha( 1 )
			f26_arg0.SpawnSituation:setText( Engine[0xF9F1239CFD921FE]( "mpui/destroyed" ) )
			f26_arg0.SpawnSituation:setLetterSpacing( 0 )
			f26_arg0.clipFinished( f26_arg0.SpawnSituation )
			f26_arg0.SpawnWarningArrowL:completeAnimation()
			f26_arg0.SpawnWarningArrowL:setLeftRight( 0, 0, 1, 15 )
			f26_arg0.SpawnWarningArrowL:setTopBottom( 0, 0, 4, 12 )
			f26_arg0.SpawnWarningArrowL:setAlpha( 0 )
			f26_arg0.SpawnWarningArrowL:playClip( "DefaultClip" )
			f26_arg0.clipFinished( f26_arg0.SpawnWarningArrowL )
			f26_arg0.SpawnWarningArrowR:completeAnimation()
			f26_arg0.SpawnWarningArrowR:setLeftRight( 0, 0, 115, 129 )
			f26_arg0.SpawnWarningArrowR:setTopBottom( 0, 0, 4, 12 )
			f26_arg0.SpawnWarningArrowR:setAlpha( 0 )
			f26_arg0.SpawnWarningArrowR:playClip( "DefaultClip" )
			f26_arg0.clipFinished( f26_arg0.SpawnWarningArrowR )
		end,
		TransitionGainFocus = function ( f27_arg0, f27_arg1 )
			f27_arg0:__resetProperties()
			f27_arg0:setupElementClipCounter( 5 )
			f27_arg0.SpawnDetailBacking:completeAnimation()
			f27_arg0.SpawnDetailBacking:setAlpha( 1 )
			f27_arg0.clipFinished( f27_arg0.SpawnDetailBacking )
			f27_arg0.SpawnWarningStripeLoop:completeAnimation()
			f27_arg0.SpawnWarningStripeLoop:setLeftRight( 0, 0, -25, 155 )
			f27_arg0.SpawnWarningStripeLoop:setTopBottom( 0, 0, 16, 20 )
			f27_arg0.SpawnWarningStripeLoop:setAlpha( 1 )
			f27_arg0.SpawnWarningStripeLoop:playClip( "DefaultClip" )
			f27_arg0.clipFinished( f27_arg0.SpawnWarningStripeLoop )
			local f27_local0 = function ( f28_arg0 )
				f27_arg0.SpawnSituation:beginAnimation( 100 )
				f27_arg0.SpawnSituation:setTopBottom( 0, 0, -1, 17 )
				f27_arg0.SpawnSituation:registerEventHandler( "interrupted_keyframe", f27_arg0.clipInterrupted )
				f27_arg0.SpawnSituation:registerEventHandler( "transition_complete_keyframe", f27_arg0.clipFinished )
			end
			
			f27_arg0.SpawnSituation:completeAnimation()
			f27_arg0.SpawnSituation:setLeftRight( 0, 0, -25, 155 )
			f27_arg0.SpawnSituation:setTopBottom( 0, 0, 0, 16 )
			f27_arg0.SpawnSituation:setRGB( ColorSet.Disabled.r, ColorSet.Disabled.g, ColorSet.Disabled.b )
			f27_arg0.SpawnSituation:setAlpha( 1 )
			f27_arg0.SpawnSituation:setText( Engine[0xF9F1239CFD921FE]( "mpui/destroyed" ) )
			f27_arg0.SpawnSituation:setLetterSpacing( 0 )
			f27_local0( f27_arg0.SpawnSituation )
			f27_arg0.SpawnWarningArrowL:completeAnimation()
			f27_arg0.SpawnWarningArrowL:setLeftRight( 0, 0, 1, 15 )
			f27_arg0.SpawnWarningArrowL:setTopBottom( 0, 0, 4, 12 )
			f27_arg0.SpawnWarningArrowL:setAlpha( 0 )
			f27_arg0.SpawnWarningArrowL:playClip( "DefaultClip" )
			f27_arg0.clipFinished( f27_arg0.SpawnWarningArrowL )
			f27_arg0.SpawnWarningArrowR:completeAnimation()
			f27_arg0.SpawnWarningArrowR:setLeftRight( 0, 0, 115, 129 )
			f27_arg0.SpawnWarningArrowR:setTopBottom( 0, 0, 4, 12 )
			f27_arg0.SpawnWarningArrowR:setAlpha( 0 )
			f27_arg0.SpawnWarningArrowR:playClip( "DefaultClip" )
			f27_arg0.clipFinished( f27_arg0.SpawnWarningArrowR )
		end,
		TransitionLoseFocus = function ( f29_arg0, f29_arg1 )
			f29_arg0:__resetProperties()
			f29_arg0:setupElementClipCounter( 5 )
			f29_arg0.SpawnDetailBacking:completeAnimation()
			f29_arg0.SpawnDetailBacking:setAlpha( 1 )
			f29_arg0.clipFinished( f29_arg0.SpawnDetailBacking )
			f29_arg0.SpawnWarningStripeLoop:completeAnimation()
			f29_arg0.SpawnWarningStripeLoop:setLeftRight( 0, 0, -25, 155 )
			f29_arg0.SpawnWarningStripeLoop:setTopBottom( 0, 0, 16, 20 )
			f29_arg0.SpawnWarningStripeLoop:setAlpha( 1 )
			f29_arg0.SpawnWarningStripeLoop:playClip( "DefaultClip" )
			f29_arg0.clipFinished( f29_arg0.SpawnWarningStripeLoop )
			local f29_local0 = function ( f30_arg0 )
				f29_arg0.SpawnSituation:beginAnimation( 100 )
				f29_arg0.SpawnSituation:setTopBottom( 0, 0, 0, 16 )
				f29_arg0.SpawnSituation:registerEventHandler( "interrupted_keyframe", f29_arg0.clipInterrupted )
				f29_arg0.SpawnSituation:registerEventHandler( "transition_complete_keyframe", f29_arg0.clipFinished )
			end
			
			f29_arg0.SpawnSituation:completeAnimation()
			f29_arg0.SpawnSituation:setLeftRight( 0, 0, -25, 155 )
			f29_arg0.SpawnSituation:setTopBottom( 0, 0, -1, 17 )
			f29_arg0.SpawnSituation:setRGB( ColorSet.Disabled.r, ColorSet.Disabled.g, ColorSet.Disabled.b )
			f29_arg0.SpawnSituation:setAlpha( 1 )
			f29_arg0.SpawnSituation:setText( Engine[0xF9F1239CFD921FE]( "mpui/destroyed" ) )
			f29_arg0.SpawnSituation:setLetterSpacing( 0 )
			f29_local0( f29_arg0.SpawnSituation )
			f29_arg0.SpawnWarningArrowL:completeAnimation()
			f29_arg0.SpawnWarningArrowL:setLeftRight( 0, 0, 1, 15 )
			f29_arg0.SpawnWarningArrowL:setTopBottom( 0, 0, 4, 12 )
			f29_arg0.SpawnWarningArrowL:setAlpha( 0 )
			f29_arg0.SpawnWarningArrowL:playClip( "DefaultClip" )
			f29_arg0.clipFinished( f29_arg0.SpawnWarningArrowL )
			f29_arg0.SpawnWarningArrowR:completeAnimation()
			f29_arg0.SpawnWarningArrowR:setLeftRight( 0, 0, 115, 129 )
			f29_arg0.SpawnWarningArrowR:setTopBottom( 0, 0, 4, 12 )
			f29_arg0.SpawnWarningArrowR:setAlpha( 0 )
			f29_arg0.SpawnWarningArrowR:playClip( "DefaultClip" )
			f29_arg0.clipFinished( f29_arg0.SpawnWarningArrowR )
		end
	},
	ThreatHigh = {
		DefaultClip = function ( f31_arg0, f31_arg1 )
			f31_arg0:__resetProperties()
			f31_arg0:setupElementClipCounter( 6 )
			f31_arg0.SpawnDetailBacking:completeAnimation()
			f31_arg0.SpawnDetailBacking:setAlpha( 1 )
			f31_arg0.clipFinished( f31_arg0.SpawnDetailBacking )
			f31_arg0.Glow:completeAnimation()
			f31_arg0.Glow:setAlpha( 0.2 )
			f31_arg0.clipFinished( f31_arg0.Glow )
			f31_arg0.SpawnWarningStripeLoop:completeAnimation()
			f31_arg0.SpawnWarningStripeLoop:setLeftRight( 0, 0, -25, 155 )
			f31_arg0.SpawnWarningStripeLoop:setTopBottom( 0, 0, 16, 20 )
			f31_arg0.SpawnWarningStripeLoop:setAlpha( 1 )
			f31_arg0.SpawnWarningStripeLoop:playClip( "DefaultClip" )
			f31_arg0.clipFinished( f31_arg0.SpawnWarningStripeLoop )
			f31_arg0.SpawnSituation:completeAnimation()
			f31_arg0.SpawnSituation:setTopBottom( 0, 0, -4.5, 16.5 )
			f31_arg0.SpawnSituation:setAlpha( 1 )
			f31_arg0.clipFinished( f31_arg0.SpawnSituation )
			f31_arg0.SpawnWarningArrowL:completeAnimation()
			f31_arg0.SpawnWarningArrowL:setAlpha( 1 )
			f31_arg0.clipFinished( f31_arg0.SpawnWarningArrowL )
			f31_arg0.SpawnWarningArrowR:completeAnimation()
			f31_arg0.SpawnWarningArrowR:setAlpha( 1 )
			f31_arg0.clipFinished( f31_arg0.SpawnWarningArrowR )
		end,
		Focused = function ( f32_arg0, f32_arg1 )
			f32_arg0:__resetProperties()
			f32_arg0:setupElementClipCounter( 6 )
			f32_arg0.SpawnDetailBacking:completeAnimation()
			f32_arg0.SpawnDetailBacking:setAlpha( 1 )
			f32_arg0.clipFinished( f32_arg0.SpawnDetailBacking )
			f32_arg0.Glow:completeAnimation()
			f32_arg0.Glow:setAlpha( 0.2 )
			f32_arg0.clipFinished( f32_arg0.Glow )
			f32_arg0.SpawnWarningStripeLoop:completeAnimation()
			f32_arg0.SpawnWarningStripeLoop:setLeftRight( 0, 0, -25, 155 )
			f32_arg0.SpawnWarningStripeLoop:setTopBottom( 0, 0, 16, 20 )
			f32_arg0.SpawnWarningStripeLoop:setAlpha( 1 )
			f32_arg0.SpawnWarningStripeLoop:playClip( "DefaultClip" )
			f32_arg0.clipFinished( f32_arg0.SpawnWarningStripeLoop )
			f32_arg0.SpawnSituation:completeAnimation()
			f32_arg0.SpawnSituation:setTopBottom( 0, 0, -6, 18 )
			f32_arg0.SpawnSituation:setAlpha( 1 )
			f32_arg0.SpawnSituation:setText( Engine[0xF9F1239CFD921FE]( "mpui/danger" ) )
			f32_arg0.clipFinished( f32_arg0.SpawnSituation )
			f32_arg0.SpawnWarningArrowL:completeAnimation()
			f32_arg0.SpawnWarningArrowL:setAlpha( 1 )
			f32_arg0.SpawnWarningArrowL:playClip( "DefaultClip" )
			f32_arg0.clipFinished( f32_arg0.SpawnWarningArrowL )
			f32_arg0.SpawnWarningArrowR:completeAnimation()
			f32_arg0.SpawnWarningArrowR:setAlpha( 1 )
			f32_arg0.SpawnWarningArrowR:playClip( "DefaultClip" )
			f32_arg0.clipFinished( f32_arg0.SpawnWarningArrowR )
		end,
		TransitionGainFocus = function ( f33_arg0, f33_arg1 )
			f33_arg0:__resetProperties()
			f33_arg0:setupElementClipCounter( 6 )
			f33_arg0.SpawnDetailBacking:completeAnimation()
			f33_arg0.SpawnDetailBacking:setAlpha( 1 )
			f33_arg0.clipFinished( f33_arg0.SpawnDetailBacking )
			local f33_local0 = function ( f34_arg0 )
				f33_arg0.Glow:beginAnimation( 200, Enum[0xF50FFF429AB1890][0x53CEB9A0427197] )
				f33_arg0.Glow:setAlpha( 0.2 )
				f33_arg0.Glow:registerEventHandler( "interrupted_keyframe", f33_arg0.clipInterrupted )
				f33_arg0.Glow:registerEventHandler( "transition_complete_keyframe", f33_arg0.clipFinished )
			end
			
			f33_arg0.Glow:completeAnimation()
			f33_arg0.Glow:setAlpha( 0 )
			f33_local0( f33_arg0.Glow )
			f33_arg0.SpawnWarningStripeLoop:completeAnimation()
			f33_arg0.SpawnWarningStripeLoop:setLeftRight( 0, 0, -25, 155 )
			f33_arg0.SpawnWarningStripeLoop:setTopBottom( 0, 0, 16, 20 )
			f33_arg0.SpawnWarningStripeLoop:setAlpha( 1 )
			f33_arg0.SpawnWarningStripeLoop:playClip( "DefaultClip" )
			f33_arg0.clipFinished( f33_arg0.SpawnWarningStripeLoop )
			local f33_local1 = function ( f35_arg0 )
				f33_arg0.SpawnSituation:beginAnimation( 100 )
				f33_arg0.SpawnSituation:setTopBottom( 0, 0, -6, 18 )
				f33_arg0.SpawnSituation:registerEventHandler( "interrupted_keyframe", f33_arg0.clipInterrupted )
				f33_arg0.SpawnSituation:registerEventHandler( "transition_complete_keyframe", f33_arg0.clipFinished )
			end
			
			f33_arg0.SpawnSituation:completeAnimation()
			f33_arg0.SpawnSituation:setTopBottom( 0, 0, -4.5, 16.5 )
			f33_arg0.SpawnSituation:setAlpha( 1 )
			f33_arg0.SpawnSituation:setText( Engine[0xF9F1239CFD921FE]( "mpui/danger" ) )
			f33_local1( f33_arg0.SpawnSituation )
			local f33_local2 = function ( f36_arg0 )
				f33_arg0.SpawnWarningArrowL:playClip( "DefaultClip" )
				f33_arg0.SpawnWarningArrowL:beginAnimation( 200 )
				f33_arg0.SpawnWarningArrowL:setAlpha( 1 )
				f33_arg0.SpawnWarningArrowL:registerEventHandler( "interrupted_keyframe", f33_arg0.clipInterrupted )
				f33_arg0.SpawnWarningArrowL:registerEventHandler( "transition_complete_keyframe", function ( element, event )
					element:playClip( "DefaultClip" )
					f33_arg0.clipFinished( element, event )
				end )
			end
			
			f33_arg0.SpawnWarningArrowL:completeAnimation()
			f33_arg0.SpawnWarningArrowL:setAlpha( 0 )
			f33_local2( f33_arg0.SpawnWarningArrowL )
			local f33_local3 = function ( f38_arg0 )
				f33_arg0.SpawnWarningArrowR:playClip( "DefaultClip" )
				f33_arg0.SpawnWarningArrowR:beginAnimation( 200 )
				f33_arg0.SpawnWarningArrowR:setAlpha( 1 )
				f33_arg0.SpawnWarningArrowR:registerEventHandler( "interrupted_keyframe", f33_arg0.clipInterrupted )
				f33_arg0.SpawnWarningArrowR:registerEventHandler( "transition_complete_keyframe", function ( element, event )
					element:playClip( "DefaultClip" )
					f33_arg0.clipFinished( element, event )
				end )
			end
			
			f33_arg0.SpawnWarningArrowR:completeAnimation()
			f33_arg0.SpawnWarningArrowR:setAlpha( 0 )
			f33_local3( f33_arg0.SpawnWarningArrowR )
		end,
		TransitionLoseFocus = function ( f40_arg0, f40_arg1 )
			f40_arg0:__resetProperties()
			f40_arg0:setupElementClipCounter( 6 )
			f40_arg0.SpawnDetailBacking:completeAnimation()
			f40_arg0.SpawnDetailBacking:setAlpha( 1 )
			f40_arg0.clipFinished( f40_arg0.SpawnDetailBacking )
			local f40_local0 = function ( f41_arg0 )
				f40_arg0.Glow:beginAnimation( 100 )
				f40_arg0.Glow:setAlpha( 0 )
				f40_arg0.Glow:registerEventHandler( "interrupted_keyframe", f40_arg0.clipInterrupted )
				f40_arg0.Glow:registerEventHandler( "transition_complete_keyframe", f40_arg0.clipFinished )
			end
			
			f40_arg0.Glow:completeAnimation()
			f40_arg0.Glow:setAlpha( 0.2 )
			f40_local0( f40_arg0.Glow )
			f40_arg0.SpawnWarningStripeLoop:completeAnimation()
			f40_arg0.SpawnWarningStripeLoop:setLeftRight( 0, 0, -25, 155 )
			f40_arg0.SpawnWarningStripeLoop:setTopBottom( 0, 0, 16, 20 )
			f40_arg0.SpawnWarningStripeLoop:setAlpha( 1 )
			f40_arg0.SpawnWarningStripeLoop:playClip( "DefaultClip" )
			f40_arg0.clipFinished( f40_arg0.SpawnWarningStripeLoop )
			local f40_local1 = function ( f42_arg0 )
				f40_arg0.SpawnSituation:beginAnimation( 100 )
				f40_arg0.SpawnSituation:setTopBottom( 0, 0, -4.5, 16.5 )
				f40_arg0.SpawnSituation:registerEventHandler( "interrupted_keyframe", f40_arg0.clipInterrupted )
				f40_arg0.SpawnSituation:registerEventHandler( "transition_complete_keyframe", f40_arg0.clipFinished )
			end
			
			f40_arg0.SpawnSituation:completeAnimation()
			f40_arg0.SpawnSituation:setTopBottom( 0, 0, -6, 18 )
			f40_arg0.SpawnSituation:setAlpha( 1 )
			f40_arg0.SpawnSituation:setText( Engine[0xF9F1239CFD921FE]( "mpui/danger" ) )
			f40_local1( f40_arg0.SpawnSituation )
			local f40_local2 = function ( f43_arg0 )
				f40_arg0.SpawnWarningArrowL:playClip( "DefaultClip" )
				f40_arg0.SpawnWarningArrowL:beginAnimation( 100 )
				f40_arg0.SpawnWarningArrowL:setAlpha( 0 )
				f40_arg0.SpawnWarningArrowL:registerEventHandler( "interrupted_keyframe", f40_arg0.clipInterrupted )
				f40_arg0.SpawnWarningArrowL:registerEventHandler( "transition_complete_keyframe", function ( element, event )
					element:playClip( "DefaultClip" )
					f40_arg0.clipFinished( element, event )
				end )
			end
			
			f40_arg0.SpawnWarningArrowL:completeAnimation()
			f40_arg0.SpawnWarningArrowL:setAlpha( 1 )
			f40_local2( f40_arg0.SpawnWarningArrowL )
			local f40_local3 = function ( f45_arg0 )
				f40_arg0.SpawnWarningArrowR:playClip( "DefaultClip" )
				f40_arg0.SpawnWarningArrowR:beginAnimation( 100 )
				f40_arg0.SpawnWarningArrowR:setAlpha( 0 )
				f40_arg0.SpawnWarningArrowR:registerEventHandler( "interrupted_keyframe", f40_arg0.clipInterrupted )
				f40_arg0.SpawnWarningArrowR:registerEventHandler( "transition_complete_keyframe", function ( element, event )
					element:playClip( "DefaultClip" )
					f40_arg0.clipFinished( element, event )
				end )
			end
			
			f40_arg0.SpawnWarningArrowR:completeAnimation()
			f40_arg0.SpawnWarningArrowR:setAlpha( 1 )
			f40_local3( f40_arg0.SpawnWarningArrowR )
		end
	},
	ThreatLow = {
		DefaultClip = function ( f47_arg0, f47_arg1 )
			f47_arg0:__resetProperties()
			f47_arg0:setupElementClipCounter( 5 )
			f47_arg0.SpawnDetailBacking:completeAnimation()
			f47_arg0.SpawnDetailBacking:setAlpha( 1 )
			f47_arg0.clipFinished( f47_arg0.SpawnDetailBacking )
			f47_arg0.SpawnWarningStripeLoop:completeAnimation()
			f47_arg0.SpawnWarningStripeLoop:setAlpha( 1 )
			f47_arg0.clipFinished( f47_arg0.SpawnWarningStripeLoop )
			f47_arg0.SpawnSituation:completeAnimation()
			f47_arg0.SpawnSituation:setLeftRight( 0, 0, -25, 155 )
			f47_arg0.SpawnSituation:setTopBottom( 0, 0, -4.5, 16.5 )
			f47_arg0.SpawnSituation:setRGB( 0.73, 0.62, 0.21 )
			f47_arg0.SpawnSituation:setAlpha( 1 )
			f47_arg0.SpawnSituation:setText( Engine[0xF9F1239CFD921FE]( "mpui/caution" ) )
			f47_arg0.clipFinished( f47_arg0.SpawnSituation )
			f47_arg0.SpawnWarningArrowL:completeAnimation()
			f47_arg0.SpawnWarningArrowL:setAlpha( 1 )
			f47_arg0.clipFinished( f47_arg0.SpawnWarningArrowL )
			f47_arg0.SpawnWarningArrowR:completeAnimation()
			f47_arg0.SpawnWarningArrowR:setAlpha( 1 )
			f47_arg0.clipFinished( f47_arg0.SpawnWarningArrowR )
		end,
		Focused = function ( f48_arg0, f48_arg1 )
			f48_arg0:__resetProperties()
			f48_arg0:setupElementClipCounter( 5 )
			f48_arg0.SpawnDetailBacking:completeAnimation()
			f48_arg0.SpawnDetailBacking:setAlpha( 1 )
			f48_arg0.clipFinished( f48_arg0.SpawnDetailBacking )
			f48_arg0.SpawnWarningStripeLoop:completeAnimation()
			f48_arg0.SpawnWarningStripeLoop:setAlpha( 1 )
			f48_arg0.SpawnWarningStripeLoop:playClip( "DefaultClip" )
			f48_arg0.clipFinished( f48_arg0.SpawnWarningStripeLoop )
			f48_arg0.SpawnSituation:completeAnimation()
			f48_arg0.SpawnSituation:setTopBottom( 0, 0, -6, 18 )
			f48_arg0.SpawnSituation:setRGB( 0.73, 0.63, 0.21 )
			f48_arg0.SpawnSituation:setAlpha( 1 )
			f48_arg0.SpawnSituation:setText( Engine[0xF9F1239CFD921FE]( "mpui/caution" ) )
			f48_arg0.clipFinished( f48_arg0.SpawnSituation )
			f48_arg0.SpawnWarningArrowL:completeAnimation()
			f48_arg0.SpawnWarningArrowL:setLeftRight( 0, 0, -27, -13 )
			f48_arg0.SpawnWarningArrowL:setAlpha( 1 )
			f48_arg0.SpawnWarningArrowL:playClip( "DefaultClip" )
			f48_arg0.clipFinished( f48_arg0.SpawnWarningArrowL )
			f48_arg0.SpawnWarningArrowR:completeAnimation()
			f48_arg0.SpawnWarningArrowR:setLeftRight( 0, 0, 142, 156 )
			f48_arg0.SpawnWarningArrowR:setAlpha( 1 )
			f48_arg0.SpawnWarningArrowR:playClip( "DefaultClip" )
			f48_arg0.clipFinished( f48_arg0.SpawnWarningArrowR )
		end,
		TransitionGainFocus = function ( f49_arg0, f49_arg1 )
			f49_arg0:__resetProperties()
			f49_arg0:setupElementClipCounter( 5 )
			f49_arg0.SpawnDetailBacking:completeAnimation()
			f49_arg0.SpawnDetailBacking:setAlpha( 1 )
			f49_arg0.clipFinished( f49_arg0.SpawnDetailBacking )
			f49_arg0.SpawnWarningStripeLoop:completeAnimation()
			f49_arg0.SpawnWarningStripeLoop:setAlpha( 1 )
			f49_arg0.SpawnWarningStripeLoop:playClip( "DefaultClip" )
			f49_arg0.clipFinished( f49_arg0.SpawnWarningStripeLoop )
			local f49_local0 = function ( f50_arg0 )
				f49_arg0.SpawnSituation:beginAnimation( 100 )
				f49_arg0.SpawnSituation:setTopBottom( 0, 0, -6, 18 )
				f49_arg0.SpawnSituation:registerEventHandler( "interrupted_keyframe", f49_arg0.clipInterrupted )
				f49_arg0.SpawnSituation:registerEventHandler( "transition_complete_keyframe", f49_arg0.clipFinished )
			end
			
			f49_arg0.SpawnSituation:completeAnimation()
			f49_arg0.SpawnSituation:setTopBottom( 0, 0, -4.5, 16.5 )
			f49_arg0.SpawnSituation:setRGB( 0.73, 0.63, 0.21 )
			f49_arg0.SpawnSituation:setAlpha( 1 )
			f49_arg0.SpawnSituation:setText( Engine[0xF9F1239CFD921FE]( "mpui/caution" ) )
			f49_local0( f49_arg0.SpawnSituation )
			local f49_local1 = function ( f51_arg0 )
				f49_arg0.SpawnWarningArrowL:playClip( "DefaultClip" )
				f49_arg0.SpawnWarningArrowL:beginAnimation( 200 )
				f49_arg0.SpawnWarningArrowL:setAlpha( 1 )
				f49_arg0.SpawnWarningArrowL:registerEventHandler( "interrupted_keyframe", f49_arg0.clipInterrupted )
				f49_arg0.SpawnWarningArrowL:registerEventHandler( "transition_complete_keyframe", function ( element, event )
					element:playClip( "DefaultClip" )
					f49_arg0.clipFinished( element, event )
				end )
			end
			
			f49_arg0.SpawnWarningArrowL:completeAnimation()
			f49_arg0.SpawnWarningArrowL:setLeftRight( 0, 0, -27, -13 )
			f49_arg0.SpawnWarningArrowL:setAlpha( 0 )
			f49_local1( f49_arg0.SpawnWarningArrowL )
			local f49_local2 = function ( f53_arg0 )
				f49_arg0.SpawnWarningArrowR:playClip( "DefaultClip" )
				f49_arg0.SpawnWarningArrowR:beginAnimation( 200 )
				f49_arg0.SpawnWarningArrowR:setAlpha( 1 )
				f49_arg0.SpawnWarningArrowR:registerEventHandler( "interrupted_keyframe", f49_arg0.clipInterrupted )
				f49_arg0.SpawnWarningArrowR:registerEventHandler( "transition_complete_keyframe", function ( element, event )
					element:playClip( "DefaultClip" )
					f49_arg0.clipFinished( element, event )
				end )
			end
			
			f49_arg0.SpawnWarningArrowR:completeAnimation()
			f49_arg0.SpawnWarningArrowR:setLeftRight( 0, 0, 142, 156 )
			f49_arg0.SpawnWarningArrowR:setAlpha( 0 )
			f49_local2( f49_arg0.SpawnWarningArrowR )
		end,
		TransitionLoseFocus = function ( f55_arg0, f55_arg1 )
			f55_arg0:__resetProperties()
			f55_arg0:setupElementClipCounter( 5 )
			f55_arg0.SpawnDetailBacking:completeAnimation()
			f55_arg0.SpawnDetailBacking:setAlpha( 1 )
			f55_arg0.clipFinished( f55_arg0.SpawnDetailBacking )
			f55_arg0.SpawnWarningStripeLoop:completeAnimation()
			f55_arg0.SpawnWarningStripeLoop:setAlpha( 1 )
			f55_arg0.SpawnWarningStripeLoop:playClip( "DefaultClip" )
			f55_arg0.clipFinished( f55_arg0.SpawnWarningStripeLoop )
			local f55_local0 = function ( f56_arg0 )
				f55_arg0.SpawnSituation:beginAnimation( 100 )
				f55_arg0.SpawnSituation:setTopBottom( 0, 0, -4.5, 16.5 )
				f55_arg0.SpawnSituation:registerEventHandler( "interrupted_keyframe", f55_arg0.clipInterrupted )
				f55_arg0.SpawnSituation:registerEventHandler( "transition_complete_keyframe", f55_arg0.clipFinished )
			end
			
			f55_arg0.SpawnSituation:completeAnimation()
			f55_arg0.SpawnSituation:setTopBottom( 0, 0, -6, 18 )
			f55_arg0.SpawnSituation:setRGB( 0.73, 0.63, 0.21 )
			f55_arg0.SpawnSituation:setAlpha( 1 )
			f55_arg0.SpawnSituation:setText( Engine[0xF9F1239CFD921FE]( "mpui/caution" ) )
			f55_local0( f55_arg0.SpawnSituation )
			local f55_local1 = function ( f57_arg0 )
				f55_arg0.SpawnWarningArrowL:playClip( "DefaultClip" )
				f55_arg0.SpawnWarningArrowL:beginAnimation( 100 )
				f55_arg0.SpawnWarningArrowL:setAlpha( 0 )
				f55_arg0.SpawnWarningArrowL:registerEventHandler( "interrupted_keyframe", f55_arg0.clipInterrupted )
				f55_arg0.SpawnWarningArrowL:registerEventHandler( "transition_complete_keyframe", function ( element, event )
					element:playClip( "DefaultClip" )
					f55_arg0.clipFinished( element, event )
				end )
			end
			
			f55_arg0.SpawnWarningArrowL:completeAnimation()
			f55_arg0.SpawnWarningArrowL:setLeftRight( 0, 0, -27, -13 )
			f55_arg0.SpawnWarningArrowL:setAlpha( 1 )
			f55_local1( f55_arg0.SpawnWarningArrowL )
			local f55_local2 = function ( f59_arg0 )
				f55_arg0.SpawnWarningArrowR:playClip( "DefaultClip" )
				f55_arg0.SpawnWarningArrowR:beginAnimation( 100 )
				f55_arg0.SpawnWarningArrowR:setAlpha( 0 )
				f55_arg0.SpawnWarningArrowR:registerEventHandler( "interrupted_keyframe", f55_arg0.clipInterrupted )
				f55_arg0.SpawnWarningArrowR:registerEventHandler( "transition_complete_keyframe", function ( element, event )
					element:playClip( "DefaultClip" )
					f55_arg0.clipFinished( element, event )
				end )
			end
			
			f55_arg0.SpawnWarningArrowR:completeAnimation()
			f55_arg0.SpawnWarningArrowR:setLeftRight( 0, 0, 142, 156 )
			f55_arg0.SpawnWarningArrowR:setAlpha( 1 )
			f55_local2( f55_arg0.SpawnWarningArrowR )
		end
	},
	Hidden = {
		DefaultClip = function ( f61_arg0, f61_arg1 )
			f61_arg0:__resetProperties()
			f61_arg0:setupElementClipCounter( 5 )
			f61_arg0.SpawnDetailBacking:completeAnimation()
			f61_arg0.SpawnDetailBacking:setAlpha( 0 )
			f61_arg0.clipFinished( f61_arg0.SpawnDetailBacking )
			f61_arg0.SpawnWarningStripeLoop:completeAnimation()
			f61_arg0.SpawnWarningStripeLoop:setAlpha( 0 )
			f61_arg0.clipFinished( f61_arg0.SpawnWarningStripeLoop )
			f61_arg0.SpawnSituation:completeAnimation()
			f61_arg0.SpawnSituation:setAlpha( 0 )
			f61_arg0.clipFinished( f61_arg0.SpawnSituation )
			f61_arg0.SpawnWarningArrowL:completeAnimation()
			f61_arg0.SpawnWarningArrowL:setAlpha( 0 )
			f61_arg0.clipFinished( f61_arg0.SpawnWarningArrowL )
			f61_arg0.SpawnWarningArrowR:completeAnimation()
			f61_arg0.SpawnWarningArrowR:setAlpha( 0 )
			f61_arg0.clipFinished( f61_arg0.SpawnWarningArrowR )
		end
	}
}
CoD.SpawnSelectionLabelWarning.__onClose = function ( f62_arg0 )
	f62_arg0.SpawnWarningStripeLoop:close()
	f62_arg0.SpawnWarningArrowL:close()
	f62_arg0.SpawnWarningArrowR:close()
end

