require( "ui/uieditor/widgets/startmenu/startmenu_options_controls_genericcontrolleritem" )

CoD.StartMenu_Options_ControllerLayout_vita = InheritFrom( LUI.UIElement )
CoD.StartMenu_Options_ControllerLayout_vita.__defaultWidth = 1078
CoD.StartMenu_Options_ControllerLayout_vita.__defaultHeight = 530
CoD.StartMenu_Options_ControllerLayout_vita.new = function ( f1_arg0, f1_arg1, f1_arg2, f1_arg3, f1_arg4, f1_arg5, f1_arg6, f1_arg7, f1_arg8, f1_arg9 )
	local self = LUI.UIElement.new( f1_arg2, f1_arg3, f1_arg4, f1_arg5, f1_arg6, f1_arg7, f1_arg8, f1_arg9 )
	self:setClass( CoD.StartMenu_Options_ControllerLayout_vita )
	self.id = "StartMenu_Options_ControllerLayout_vita"
	self.soundSet = "default"
	self.anyChildUsesUpdateState = true
	f1_arg0:addElementToPendingUpdateStateList( self )
	
	local VitaControllerImage = LUI.UIImage.new( 0.5, 0.5, -564, 564, 0.5, 0.5, -252, 252 )
	VitaControllerImage:setImage( RegisterImage( ImageIsEverywhereButDurango( "uie_img_t7_menu_startmenu_option_psvita" ) ) )
	self:addElement( VitaControllerImage )
	self.VitaControllerImage = VitaControllerImage
	
	local leftStickText = CoD.StartMenu_Options_Controls_GenericControllerItem.new( f1_arg0, f1_arg1, 0, 0, 76, 326, 0, 0, 405, 432 )
	leftStickText.defaultText:setAlignment( Enum.LUIAlignment[0x830CFD395E6AA0A] )
	leftStickText:subscribeToGlobalModel( f1_arg1, "ButtonLayoutLabels", "leftStick", function ( model )
		leftStickText:setModel( model, f1_arg1 )
	end )
	self:addElement( leftStickText )
	self.leftStickText = leftStickText
	
	local leftTriggerText = CoD.StartMenu_Options_Controls_GenericControllerItem.new( f1_arg0, f1_arg1, 0, 0, 1.5, 251.5, 0, 0, 42.5, 69.5 )
	leftTriggerText.defaultText:setAlignment( Enum.LUIAlignment[0x830CFD395E6AA0A] )
	leftTriggerText:subscribeToGlobalModel( f1_arg1, "ButtonLayoutLabels", "leftTrig", function ( model )
		leftTriggerText:setModel( model, f1_arg1 )
	end )
	self:addElement( leftTriggerText )
	self.leftTriggerText = leftTriggerText
	
	local leftBumperText = CoD.StartMenu_Options_Controls_GenericControllerItem.new( f1_arg0, f1_arg1, 0, 0, 55.5, 305.5, 0, 0, 287, 314 )
	leftBumperText.defaultText:setAlignment( Enum.LUIAlignment[0x830CFD395E6AA0A] )
	leftBumperText:subscribeToGlobalModel( f1_arg1, "ButtonLayoutLabels", "lb", function ( model )
		leftBumperText:setModel( model, f1_arg1 )
	end )
	self:addElement( leftBumperText )
	self.leftBumperText = leftBumperText
	
	local rightStickText = CoD.StartMenu_Options_Controls_GenericControllerItem.new( f1_arg0, f1_arg1, 0, 0, 753, 1003, 0, 0, 405, 432 )
	rightStickText:subscribeToGlobalModel( f1_arg1, "ButtonLayoutLabels", "rightStick", function ( model )
		rightStickText:setModel( model, f1_arg1 )
	end )
	self:addElement( rightStickText )
	self.rightStickText = rightStickText
	
	local rightTriggerText = CoD.StartMenu_Options_Controls_GenericControllerItem.new( f1_arg0, f1_arg1, 0, 0, 827, 1077, 0, 0, 42.5, 69.5 )
	rightTriggerText:subscribeToGlobalModel( f1_arg1, "ButtonLayoutLabels", "rightTrig", function ( model )
		rightTriggerText:setModel( model, f1_arg1 )
	end )
	self:addElement( rightTriggerText )
	self.rightTriggerText = rightTriggerText
	
	local rightBumperText = CoD.StartMenu_Options_Controls_GenericControllerItem.new( f1_arg0, f1_arg1, 0, 0, 771, 1021, 0, 0, 287, 314 )
	rightBumperText:subscribeToGlobalModel( f1_arg1, "ButtonLayoutLabels", "rb", function ( model )
		rightBumperText:setModel( model, f1_arg1 )
	end )
	self:addElement( rightBumperText )
	self.rightBumperText = rightBumperText
	
	local XBAPSCrossText = CoD.StartMenu_Options_Controls_GenericControllerItem.new( f1_arg0, f1_arg1, 0, 0, 826, 1076, 0, 0, 213.5, 240.5 )
	XBAPSCrossText:subscribeToGlobalModel( f1_arg1, "ButtonLayoutLabels", "xbA_psCross", function ( model )
		XBAPSCrossText:setModel( model, f1_arg1 )
	end )
	self:addElement( XBAPSCrossText )
	self.XBAPSCrossText = XBAPSCrossText
	
	local XBBPSCircleText = CoD.StartMenu_Options_Controls_GenericControllerItem.new( f1_arg0, f1_arg1, 0, 0, 826, 1076, 0, 0, 172.5, 199.5 )
	XBBPSCircleText:subscribeToGlobalModel( f1_arg1, "ButtonLayoutLabels", "xbB_psCircle", function ( model )
		XBBPSCircleText:setModel( model, f1_arg1 )
	end )
	self:addElement( XBBPSCircleText )
	self.XBBPSCircleText = XBBPSCircleText
	
	local XBXPSSquareText = CoD.StartMenu_Options_Controls_GenericControllerItem.new( f1_arg0, f1_arg1, 0, 0, 826, 1076, 0, 0, 138.5, 165.5 )
	XBXPSSquareText:subscribeToGlobalModel( f1_arg1, "ButtonLayoutLabels", "xbX_psSquare", function ( model )
		XBXPSSquareText:setModel( model, f1_arg1 )
	end )
	self:addElement( XBXPSSquareText )
	self.XBXPSSquareText = XBXPSSquareText
	
	local XBYPSTriangleText = CoD.StartMenu_Options_Controls_GenericControllerItem.new( f1_arg0, f1_arg1, 0, 0, 826, 1076, 0, 0, 104.5, 131.5 )
	XBYPSTriangleText.defaultText:setAlignment( Enum.LUIAlignment[0x70510683C22104B] )
	XBYPSTriangleText:subscribeToGlobalModel( f1_arg1, "ButtonLayoutLabels", "xbY_psTriangle", function ( model )
		XBYPSTriangleText:setModel( model, f1_arg1 )
	end )
	self:addElement( XBYPSTriangleText )
	self.XBYPSTriangleText = XBYPSTriangleText
	
	local backButtonText = CoD.StartMenu_Options_Controls_GenericControllerItem.new( f1_arg0, f1_arg1, 0, 0, 414, 664, 0, 0, 325, 352 )
	backButtonText.defaultText:setAlignment( Enum.LUIAlignment[0xFEEB12BCB0D7041] )
	backButtonText:subscribeToGlobalModel( f1_arg1, "ButtonLayoutLabels", "back", function ( model )
		backButtonText:setModel( model, f1_arg1 )
	end )
	self:addElement( backButtonText )
	self.backButtonText = backButtonText
	
	local startButtonText = CoD.StartMenu_Options_Controls_GenericControllerItem.new( f1_arg0, f1_arg1, 0, 0, 826, 1076, 0, 0, 260, 287 )
	startButtonText:subscribeToGlobalModel( f1_arg1, "ButtonLayoutLabels", "start", function ( model )
		startButtonText:setModel( model, f1_arg1 )
	end )
	self:addElement( startButtonText )
	self.startButtonText = startButtonText
	
	local leftButtonText = CoD.StartMenu_Options_Controls_GenericControllerItem.new( f1_arg0, f1_arg1, 0, 0, 86.5, 246.5, 0, 0, 199.5, 226.5 )
	leftButtonText.defaultText:setAlignment( Enum.LUIAlignment[0x830CFD395E6AA0A] )
	leftButtonText:subscribeToGlobalModel( f1_arg1, "ButtonLayoutLabels", "leftDpad", function ( model )
		leftButtonText:setModel( model, f1_arg1 )
	end )
	self:addElement( leftButtonText )
	self.leftButtonText = leftButtonText
	
	local rightButtonText = CoD.StartMenu_Options_Controls_GenericControllerItem.new( f1_arg0, f1_arg1, 0, 0, 86.5, 246.5, 0, 0, 233, 260 )
	rightButtonText.defaultText:setAlignment( Enum.LUIAlignment[0x830CFD395E6AA0A] )
	rightButtonText:subscribeToGlobalModel( f1_arg1, "ButtonLayoutLabels", "rightDpad", function ( model )
		rightButtonText:setModel( model, f1_arg1 )
	end )
	self:addElement( rightButtonText )
	self.rightButtonText = rightButtonText
	
	local upButtonText = CoD.StartMenu_Options_Controls_GenericControllerItem.new( f1_arg0, f1_arg1, 0, 0, 86.5, 246.5, 0, 0, 165.5, 192.5 )
	upButtonText.defaultText:setAlignment( Enum.LUIAlignment[0x830CFD395E6AA0A] )
	upButtonText:subscribeToGlobalModel( f1_arg1, "ButtonLayoutLabels", "upDpad", function ( model )
		upButtonText:setModel( model, f1_arg1 )
	end )
	self:addElement( upButtonText )
	self.upButtonText = upButtonText
	
	local downButtonText = CoD.StartMenu_Options_Controls_GenericControllerItem.new( f1_arg0, f1_arg1, 0, 0, 86.5, 246.5, 0, 0, 260, 287 )
	downButtonText.defaultText:setAlignment( Enum.LUIAlignment[0x830CFD395E6AA0A] )
	downButtonText:subscribeToGlobalModel( f1_arg1, "ButtonLayoutLabels", "downDpad", function ( model )
		downButtonText:setModel( model, f1_arg1 )
	end )
	self:addElement( downButtonText )
	self.downButtonText = downButtonText
	
	local VitaLines = LUI.UIImage.new( 0, 0, 203, 875, 0, 0, 55.5, 419.5 )
	VitaLines:setImage( RegisterImage( ImageIsEverywhereButDurango( "uie_img_t7_menu_startmenu_option_lines_vita" ) ) )
	self:addElement( VitaLines )
	self.VitaLines = VitaLines
	
	local rightStickOverlay = LUI.UIImage.new( 0, 0, 661, 771, 0, 0, 182.5, 292.5 )
	rightStickOverlay:subscribeToGlobalModel( f1_arg1, "StickLayoutLabels", "rightStickImg", function ( model )
		local f18_local0 = model:get()
		if f18_local0 ~= nil then
			rightStickOverlay:setImage( RegisterImage( f18_local0 ) )
		end
	end )
	self:addElement( rightStickOverlay )
	self.rightStickOverlay = rightStickOverlay
	
	local leftStickOverlay = LUI.UIImage.new( 0, 0, 306, 416, 0, 0, 180, 290 )
	leftStickOverlay:subscribeToGlobalModel( f1_arg1, "StickLayoutLabels", "leftStickImg", function ( model )
		local f19_local0 = model:get()
		if f19_local0 ~= nil then
			leftStickOverlay:setImage( RegisterImage( f19_local0 ) )
		end
	end )
	self:addElement( leftStickOverlay )
	self.leftStickOverlay = leftStickOverlay
	
	local leftStickUpText = CoD.StartMenu_Options_Controls_GenericControllerItem.new( f1_arg0, f1_arg1, 0, 0, -4, 296, 0, 0, 166.5, 193.5 )
	leftStickUpText.defaultText:setAlignment( Enum.LUIAlignment[0x830CFD395E6AA0A] )
	leftStickUpText:subscribeToGlobalModel( f1_arg1, "StickLayoutLabels", "leftStickUp", function ( model )
		leftStickUpText:setModel( model, f1_arg1 )
	end )
	self:addElement( leftStickUpText )
	self.leftStickUpText = leftStickUpText
	
	local leftStickDownText = CoD.StartMenu_Options_Controls_GenericControllerItem.new( f1_arg0, f1_arg1, 0, 0, 211, 511, 0, 0, 325.5, 352.5 )
	leftStickDownText.defaultText:setAlignment( Enum.LUIAlignment[0xFEEB12BCB0D7041] )
	leftStickDownText:subscribeToGlobalModel( f1_arg1, "StickLayoutLabels", "leftStickDown", function ( model )
		leftStickDownText:setModel( model, f1_arg1 )
	end )
	self:addElement( leftStickDownText )
	self.leftStickDownText = leftStickDownText
	
	local leftStickLeftRightText = CoD.StartMenu_Options_Controls_GenericControllerItem.new( f1_arg0, f1_arg1, 0, 0, -8, 292, 0, 0, 221.5, 248.5 )
	leftStickLeftRightText.defaultText:setAlignment( Enum.LUIAlignment[0x830CFD395E6AA0A] )
	leftStickLeftRightText:subscribeToGlobalModel( f1_arg1, "StickLayoutLabels", "leftStickLeftRight", function ( model )
		leftStickLeftRightText:setModel( model, f1_arg1 )
	end )
	self:addElement( leftStickLeftRightText )
	self.leftStickLeftRightText = leftStickLeftRightText
	
	local rightStickDownText = CoD.StartMenu_Options_Controls_GenericControllerItem.new( f1_arg0, f1_arg1, 0, 0, 566, 866, 0, 0, 325.5, 352.5 )
	rightStickDownText.defaultText:setAlignment( Enum.LUIAlignment[0xFEEB12BCB0D7041] )
	rightStickDownText:subscribeToGlobalModel( f1_arg1, "StickLayoutLabels", "rightStickDown", function ( model )
		rightStickDownText:setModel( model, f1_arg1 )
	end )
	self:addElement( rightStickDownText )
	self.rightStickDownText = rightStickDownText
	
	local rightStickLeftRightText = CoD.StartMenu_Options_Controls_GenericControllerItem.new( f1_arg0, f1_arg1, 0, 0, 782, 1082, 0, 0, 221.5, 248.5 )
	rightStickLeftRightText:subscribeToGlobalModel( f1_arg1, "StickLayoutLabels", "rightStickLeftRight", function ( model )
		rightStickLeftRightText:setModel( model, f1_arg1 )
	end )
	self:addElement( rightStickLeftRightText )
	self.rightStickLeftRightText = rightStickLeftRightText
	
	local rightStickUpText = CoD.StartMenu_Options_Controls_GenericControllerItem.new( f1_arg0, f1_arg1, 0, 0, 782, 1082, 0, 0, 166.5, 193.5 )
	rightStickUpText:subscribeToGlobalModel( f1_arg1, "StickLayoutLabels", "rightStickUp", function ( model )
		rightStickUpText:setModel( model, f1_arg1 )
	end )
	self:addElement( rightStickUpText )
	self.rightStickUpText = rightStickUpText
	
	self:mergeStateConditions( {
		{
			stateName = "Hidden",
			condition = function ( menu, element, event )
				return not IsVitaGamepad( f1_arg1 )
			end
		},
		{
			stateName = "Buttons",
			condition = function ( menu, element, event )
				return CoD.ModelUtility.IsModelValueEqualToEnum( f1_arg1, "controllerLayoutState", CoD.OptionsUtility.ControllerPreviewStates.CONTROLLER_BUTTONS )
			end
		},
		{
			stateName = "Sticks",
			condition = function ( menu, element, event )
				return CoD.ModelUtility.IsModelValueEqualToEnum( f1_arg1, "controllerLayoutState", CoD.OptionsUtility.ControllerPreviewStates.CONTROLLER_STICKS )
			end
		}
	} )
	self:appendEventHandler( "input_source_changed", function ( f29_arg0, f29_arg1 )
		f29_arg1.menu = f29_arg1.menu or f1_arg0
		f1_arg0:updateElementState( self, f29_arg1 )
	end )
	local f1_local27 = self
	local f1_local28 = self.subscribeToModel
	local f1_local29 = Engine.GetModelForController( f1_arg1 )
	f1_local28( f1_local27, f1_local29.LastInput, function ( f30_arg0 )
		f1_arg0:updateElementState( self, {
			name = "model_validation",
			menu = f1_arg0,
			controller = f1_arg1,
			modelValue = f30_arg0:get(),
			modelName = "LastInput"
		} )
	end, false )
	f1_local27 = self
	f1_local28 = self.subscribeToModel
	f1_local29 = Engine.GetModelForController( f1_arg1 )
	f1_local28( f1_local27, f1_local29.controllerLayoutState, function ( f31_arg0 )
		f1_arg0:updateElementState( self, {
			name = "model_validation",
			menu = f1_arg0,
			controller = f1_arg1,
			modelValue = f31_arg0:get(),
			modelName = "controllerLayoutState"
		} )
	end, false )
	LUI.OverrideFunction_CallOriginalSecond( self, "close", self.__onClose )
	
	if PostLoadFunc then
		PostLoadFunc( self, f1_arg1, f1_arg0 )
	end
	
	return self
end

CoD.StartMenu_Options_ControllerLayout_vita.__resetProperties = function ( f32_arg0 )
	f32_arg0.leftButtonText:completeAnimation()
	f32_arg0.VitaLines:completeAnimation()
	f32_arg0.downButtonText:completeAnimation()
	f32_arg0.upButtonText:completeAnimation()
	f32_arg0.rightButtonText:completeAnimation()
	f32_arg0.startButtonText:completeAnimation()
	f32_arg0.backButtonText:completeAnimation()
	f32_arg0.XBYPSTriangleText:completeAnimation()
	f32_arg0.XBXPSSquareText:completeAnimation()
	f32_arg0.XBBPSCircleText:completeAnimation()
	f32_arg0.XBAPSCrossText:completeAnimation()
	f32_arg0.rightBumperText:completeAnimation()
	f32_arg0.rightTriggerText:completeAnimation()
	f32_arg0.rightStickText:completeAnimation()
	f32_arg0.leftBumperText:completeAnimation()
	f32_arg0.leftTriggerText:completeAnimation()
	f32_arg0.leftStickText:completeAnimation()
	f32_arg0.rightStickLeftRightText:completeAnimation()
	f32_arg0.rightStickUpText:completeAnimation()
	f32_arg0.rightStickDownText:completeAnimation()
	f32_arg0.leftStickLeftRightText:completeAnimation()
	f32_arg0.leftStickDownText:completeAnimation()
	f32_arg0.leftStickUpText:completeAnimation()
	f32_arg0.rightStickOverlay:completeAnimation()
	f32_arg0.leftStickOverlay:completeAnimation()
	f32_arg0.VitaControllerImage:completeAnimation()
	f32_arg0.leftButtonText:setAlpha( 1 )
	f32_arg0.VitaLines:setAlpha( 1 )
	f32_arg0.downButtonText:setAlpha( 1 )
	f32_arg0.upButtonText:setAlpha( 1 )
	f32_arg0.rightButtonText:setAlpha( 1 )
	f32_arg0.startButtonText:setAlpha( 1 )
	f32_arg0.backButtonText:setAlpha( 1 )
	f32_arg0.XBYPSTriangleText:setAlpha( 1 )
	f32_arg0.XBXPSSquareText:setAlpha( 1 )
	f32_arg0.XBBPSCircleText:setAlpha( 1 )
	f32_arg0.XBAPSCrossText:setAlpha( 1 )
	f32_arg0.rightBumperText:setAlpha( 1 )
	f32_arg0.rightTriggerText:setAlpha( 1 )
	f32_arg0.rightStickText:setAlpha( 1 )
	f32_arg0.leftBumperText:setAlpha( 1 )
	f32_arg0.leftTriggerText:setAlpha( 1 )
	f32_arg0.leftStickText:setAlpha( 1 )
	f32_arg0.rightStickLeftRightText:setAlpha( 1 )
	f32_arg0.rightStickUpText:setAlpha( 1 )
	f32_arg0.rightStickDownText:setAlpha( 1 )
	f32_arg0.leftStickLeftRightText:setAlpha( 1 )
	f32_arg0.leftStickDownText:setAlpha( 1 )
	f32_arg0.leftStickUpText:setAlpha( 1 )
	f32_arg0.rightStickOverlay:setAlpha( 1 )
	f32_arg0.leftStickOverlay:setAlpha( 1 )
	f32_arg0.VitaControllerImage:setAlpha( 1 )
end

CoD.StartMenu_Options_ControllerLayout_vita.__clipsPerState = {
	DefaultState = {
		DefaultClip = function ( f33_arg0, f33_arg1 )
			f33_arg0:__resetProperties()
			f33_arg0:setupElementClipCounter( 25 )
			f33_arg0.leftStickText:completeAnimation()
			f33_arg0.leftStickText:setAlpha( 0 )
			f33_arg0.clipFinished( f33_arg0.leftStickText )
			f33_arg0.leftTriggerText:completeAnimation()
			f33_arg0.leftTriggerText:setAlpha( 0 )
			f33_arg0.clipFinished( f33_arg0.leftTriggerText )
			f33_arg0.leftBumperText:completeAnimation()
			f33_arg0.leftBumperText:setAlpha( 0 )
			f33_arg0.clipFinished( f33_arg0.leftBumperText )
			f33_arg0.rightStickText:completeAnimation()
			f33_arg0.rightStickText:setAlpha( 0 )
			f33_arg0.clipFinished( f33_arg0.rightStickText )
			f33_arg0.rightTriggerText:completeAnimation()
			f33_arg0.rightTriggerText:setAlpha( 0 )
			f33_arg0.clipFinished( f33_arg0.rightTriggerText )
			f33_arg0.rightBumperText:completeAnimation()
			f33_arg0.rightBumperText:setAlpha( 0 )
			f33_arg0.clipFinished( f33_arg0.rightBumperText )
			f33_arg0.XBAPSCrossText:completeAnimation()
			f33_arg0.XBAPSCrossText:setAlpha( 0 )
			f33_arg0.clipFinished( f33_arg0.XBAPSCrossText )
			f33_arg0.XBBPSCircleText:completeAnimation()
			f33_arg0.XBBPSCircleText:setAlpha( 0 )
			f33_arg0.clipFinished( f33_arg0.XBBPSCircleText )
			f33_arg0.XBXPSSquareText:completeAnimation()
			f33_arg0.XBXPSSquareText:setAlpha( 0 )
			f33_arg0.clipFinished( f33_arg0.XBXPSSquareText )
			f33_arg0.XBYPSTriangleText:completeAnimation()
			f33_arg0.XBYPSTriangleText:setAlpha( 0 )
			f33_arg0.clipFinished( f33_arg0.XBYPSTriangleText )
			f33_arg0.backButtonText:completeAnimation()
			f33_arg0.backButtonText:setAlpha( 0 )
			f33_arg0.clipFinished( f33_arg0.backButtonText )
			f33_arg0.startButtonText:completeAnimation()
			f33_arg0.startButtonText:setAlpha( 0 )
			f33_arg0.clipFinished( f33_arg0.startButtonText )
			f33_arg0.leftButtonText:completeAnimation()
			f33_arg0.leftButtonText:setAlpha( 0 )
			f33_arg0.clipFinished( f33_arg0.leftButtonText )
			f33_arg0.rightButtonText:completeAnimation()
			f33_arg0.rightButtonText:setAlpha( 0 )
			f33_arg0.clipFinished( f33_arg0.rightButtonText )
			f33_arg0.upButtonText:completeAnimation()
			f33_arg0.upButtonText:setAlpha( 0 )
			f33_arg0.clipFinished( f33_arg0.upButtonText )
			f33_arg0.downButtonText:completeAnimation()
			f33_arg0.downButtonText:setAlpha( 0 )
			f33_arg0.clipFinished( f33_arg0.downButtonText )
			f33_arg0.VitaLines:completeAnimation()
			f33_arg0.VitaLines:setAlpha( 0 )
			f33_arg0.clipFinished( f33_arg0.VitaLines )
			f33_arg0.rightStickOverlay:completeAnimation()
			f33_arg0.rightStickOverlay:setAlpha( 0 )
			f33_arg0.clipFinished( f33_arg0.rightStickOverlay )
			f33_arg0.leftStickOverlay:completeAnimation()
			f33_arg0.leftStickOverlay:setAlpha( 0 )
			f33_arg0.clipFinished( f33_arg0.leftStickOverlay )
			f33_arg0.leftStickUpText:completeAnimation()
			f33_arg0.leftStickUpText:setAlpha( 0 )
			f33_arg0.clipFinished( f33_arg0.leftStickUpText )
			f33_arg0.leftStickDownText:completeAnimation()
			f33_arg0.leftStickDownText:setAlpha( 0 )
			f33_arg0.clipFinished( f33_arg0.leftStickDownText )
			f33_arg0.leftStickLeftRightText:completeAnimation()
			f33_arg0.leftStickLeftRightText:setAlpha( 0 )
			f33_arg0.clipFinished( f33_arg0.leftStickLeftRightText )
			f33_arg0.rightStickDownText:completeAnimation()
			f33_arg0.rightStickDownText:setAlpha( 0 )
			f33_arg0.clipFinished( f33_arg0.rightStickDownText )
			f33_arg0.rightStickLeftRightText:completeAnimation()
			f33_arg0.rightStickLeftRightText:setAlpha( 0 )
			f33_arg0.clipFinished( f33_arg0.rightStickLeftRightText )
			f33_arg0.rightStickUpText:completeAnimation()
			f33_arg0.rightStickUpText:setAlpha( 0 )
			f33_arg0.clipFinished( f33_arg0.rightStickUpText )
		end
	},
	Hidden = {
		DefaultClip = function ( f34_arg0, f34_arg1 )
			f34_arg0:__resetProperties()
			f34_arg0:setupElementClipCounter( 26 )
			f34_arg0.VitaControllerImage:completeAnimation()
			f34_arg0.VitaControllerImage:setAlpha( 0 )
			f34_arg0.clipFinished( f34_arg0.VitaControllerImage )
			f34_arg0.leftStickText:completeAnimation()
			f34_arg0.leftStickText:setAlpha( 0 )
			f34_arg0.clipFinished( f34_arg0.leftStickText )
			f34_arg0.leftTriggerText:completeAnimation()
			f34_arg0.leftTriggerText:setAlpha( 0 )
			f34_arg0.clipFinished( f34_arg0.leftTriggerText )
			f34_arg0.leftBumperText:completeAnimation()
			f34_arg0.leftBumperText:setAlpha( 0 )
			f34_arg0.clipFinished( f34_arg0.leftBumperText )
			f34_arg0.rightStickText:completeAnimation()
			f34_arg0.rightStickText:setAlpha( 0 )
			f34_arg0.clipFinished( f34_arg0.rightStickText )
			f34_arg0.rightTriggerText:completeAnimation()
			f34_arg0.rightTriggerText:setAlpha( 0 )
			f34_arg0.clipFinished( f34_arg0.rightTriggerText )
			f34_arg0.rightBumperText:completeAnimation()
			f34_arg0.rightBumperText:setAlpha( 0 )
			f34_arg0.clipFinished( f34_arg0.rightBumperText )
			f34_arg0.XBAPSCrossText:completeAnimation()
			f34_arg0.XBAPSCrossText:setAlpha( 0 )
			f34_arg0.clipFinished( f34_arg0.XBAPSCrossText )
			f34_arg0.XBBPSCircleText:completeAnimation()
			f34_arg0.XBBPSCircleText:setAlpha( 0 )
			f34_arg0.clipFinished( f34_arg0.XBBPSCircleText )
			f34_arg0.XBXPSSquareText:completeAnimation()
			f34_arg0.XBXPSSquareText:setAlpha( 0 )
			f34_arg0.clipFinished( f34_arg0.XBXPSSquareText )
			f34_arg0.XBYPSTriangleText:completeAnimation()
			f34_arg0.XBYPSTriangleText:setAlpha( 0 )
			f34_arg0.clipFinished( f34_arg0.XBYPSTriangleText )
			f34_arg0.backButtonText:completeAnimation()
			f34_arg0.backButtonText:setAlpha( 0 )
			f34_arg0.clipFinished( f34_arg0.backButtonText )
			f34_arg0.startButtonText:completeAnimation()
			f34_arg0.startButtonText:setAlpha( 0 )
			f34_arg0.clipFinished( f34_arg0.startButtonText )
			f34_arg0.leftButtonText:completeAnimation()
			f34_arg0.leftButtonText:setAlpha( 0 )
			f34_arg0.clipFinished( f34_arg0.leftButtonText )
			f34_arg0.rightButtonText:completeAnimation()
			f34_arg0.rightButtonText:setAlpha( 0 )
			f34_arg0.clipFinished( f34_arg0.rightButtonText )
			f34_arg0.upButtonText:completeAnimation()
			f34_arg0.upButtonText:setAlpha( 0 )
			f34_arg0.clipFinished( f34_arg0.upButtonText )
			f34_arg0.downButtonText:completeAnimation()
			f34_arg0.downButtonText:setAlpha( 0 )
			f34_arg0.clipFinished( f34_arg0.downButtonText )
			f34_arg0.VitaLines:completeAnimation()
			f34_arg0.VitaLines:setAlpha( 0 )
			f34_arg0.clipFinished( f34_arg0.VitaLines )
			f34_arg0.rightStickOverlay:completeAnimation()
			f34_arg0.rightStickOverlay:setAlpha( 0 )
			f34_arg0.clipFinished( f34_arg0.rightStickOverlay )
			f34_arg0.leftStickOverlay:completeAnimation()
			f34_arg0.leftStickOverlay:setAlpha( 0 )
			f34_arg0.clipFinished( f34_arg0.leftStickOverlay )
			f34_arg0.leftStickUpText:completeAnimation()
			f34_arg0.leftStickUpText:setAlpha( 0 )
			f34_arg0.clipFinished( f34_arg0.leftStickUpText )
			f34_arg0.leftStickDownText:completeAnimation()
			f34_arg0.leftStickDownText:setAlpha( 0 )
			f34_arg0.clipFinished( f34_arg0.leftStickDownText )
			f34_arg0.leftStickLeftRightText:completeAnimation()
			f34_arg0.leftStickLeftRightText:setAlpha( 0 )
			f34_arg0.clipFinished( f34_arg0.leftStickLeftRightText )
			f34_arg0.rightStickDownText:completeAnimation()
			f34_arg0.rightStickDownText:setAlpha( 0 )
			f34_arg0.clipFinished( f34_arg0.rightStickDownText )
			f34_arg0.rightStickLeftRightText:completeAnimation()
			f34_arg0.rightStickLeftRightText:setAlpha( 0 )
			f34_arg0.clipFinished( f34_arg0.rightStickLeftRightText )
			f34_arg0.rightStickUpText:completeAnimation()
			f34_arg0.rightStickUpText:setAlpha( 0 )
			f34_arg0.clipFinished( f34_arg0.rightStickUpText )
		end
	},
	Buttons = {
		DefaultClip = function ( f35_arg0, f35_arg1 )
			f35_arg0:__resetProperties()
			f35_arg0:setupElementClipCounter( 11 )
			f35_arg0.leftButtonText:completeAnimation()
			f35_arg0.leftButtonText:setAlpha( 0 )
			f35_arg0.clipFinished( f35_arg0.leftButtonText )
			f35_arg0.rightButtonText:completeAnimation()
			f35_arg0.rightButtonText:setAlpha( 0 )
			f35_arg0.clipFinished( f35_arg0.rightButtonText )
			f35_arg0.downButtonText:completeAnimation()
			f35_arg0.downButtonText:setAlpha( 0 )
			f35_arg0.clipFinished( f35_arg0.downButtonText )
			f35_arg0.rightStickOverlay:completeAnimation()
			f35_arg0.rightStickOverlay:setAlpha( 0 )
			f35_arg0.clipFinished( f35_arg0.rightStickOverlay )
			f35_arg0.leftStickOverlay:completeAnimation()
			f35_arg0.leftStickOverlay:setAlpha( 0 )
			f35_arg0.clipFinished( f35_arg0.leftStickOverlay )
			f35_arg0.leftStickUpText:completeAnimation()
			f35_arg0.leftStickUpText:setAlpha( 0 )
			f35_arg0.clipFinished( f35_arg0.leftStickUpText )
			f35_arg0.leftStickDownText:completeAnimation()
			f35_arg0.leftStickDownText:setAlpha( 0 )
			f35_arg0.clipFinished( f35_arg0.leftStickDownText )
			f35_arg0.leftStickLeftRightText:completeAnimation()
			f35_arg0.leftStickLeftRightText:setAlpha( 0 )
			f35_arg0.clipFinished( f35_arg0.leftStickLeftRightText )
			f35_arg0.rightStickDownText:completeAnimation()
			f35_arg0.rightStickDownText:setAlpha( 0 )
			f35_arg0.clipFinished( f35_arg0.rightStickDownText )
			f35_arg0.rightStickLeftRightText:completeAnimation()
			f35_arg0.rightStickLeftRightText:setAlpha( 0 )
			f35_arg0.clipFinished( f35_arg0.rightStickLeftRightText )
			f35_arg0.rightStickUpText:completeAnimation()
			f35_arg0.rightStickUpText:setAlpha( 0 )
			f35_arg0.clipFinished( f35_arg0.rightStickUpText )
		end
	},
	Sticks = {
		DefaultClip = function ( f36_arg0, f36_arg1 )
			f36_arg0:__resetProperties()
			f36_arg0:setupElementClipCounter( 17 )
			f36_arg0.leftStickText:completeAnimation()
			f36_arg0.leftStickText:setAlpha( 0 )
			f36_arg0.clipFinished( f36_arg0.leftStickText )
			f36_arg0.leftTriggerText:completeAnimation()
			f36_arg0.leftTriggerText:setAlpha( 0 )
			f36_arg0.clipFinished( f36_arg0.leftTriggerText )
			f36_arg0.leftBumperText:completeAnimation()
			f36_arg0.leftBumperText:setAlpha( 0 )
			f36_arg0.clipFinished( f36_arg0.leftBumperText )
			f36_arg0.rightStickText:completeAnimation()
			f36_arg0.rightStickText:setAlpha( 0 )
			f36_arg0.clipFinished( f36_arg0.rightStickText )
			f36_arg0.rightTriggerText:completeAnimation()
			f36_arg0.rightTriggerText:setAlpha( 0 )
			f36_arg0.clipFinished( f36_arg0.rightTriggerText )
			f36_arg0.rightBumperText:completeAnimation()
			f36_arg0.rightBumperText:setAlpha( 0 )
			f36_arg0.clipFinished( f36_arg0.rightBumperText )
			f36_arg0.XBAPSCrossText:completeAnimation()
			f36_arg0.XBAPSCrossText:setAlpha( 0 )
			f36_arg0.clipFinished( f36_arg0.XBAPSCrossText )
			f36_arg0.XBBPSCircleText:completeAnimation()
			f36_arg0.XBBPSCircleText:setAlpha( 0 )
			f36_arg0.clipFinished( f36_arg0.XBBPSCircleText )
			f36_arg0.XBXPSSquareText:completeAnimation()
			f36_arg0.XBXPSSquareText:setAlpha( 0 )
			f36_arg0.clipFinished( f36_arg0.XBXPSSquareText )
			f36_arg0.XBYPSTriangleText:completeAnimation()
			f36_arg0.XBYPSTriangleText:setAlpha( 0 )
			f36_arg0.clipFinished( f36_arg0.XBYPSTriangleText )
			f36_arg0.backButtonText:completeAnimation()
			f36_arg0.backButtonText:setAlpha( 0 )
			f36_arg0.clipFinished( f36_arg0.backButtonText )
			f36_arg0.startButtonText:completeAnimation()
			f36_arg0.startButtonText:setAlpha( 0 )
			f36_arg0.clipFinished( f36_arg0.startButtonText )
			f36_arg0.leftButtonText:completeAnimation()
			f36_arg0.leftButtonText:setAlpha( 0 )
			f36_arg0.clipFinished( f36_arg0.leftButtonText )
			f36_arg0.rightButtonText:completeAnimation()
			f36_arg0.rightButtonText:setAlpha( 0 )
			f36_arg0.clipFinished( f36_arg0.rightButtonText )
			f36_arg0.upButtonText:completeAnimation()
			f36_arg0.upButtonText:setAlpha( 0 )
			f36_arg0.clipFinished( f36_arg0.upButtonText )
			f36_arg0.downButtonText:completeAnimation()
			f36_arg0.downButtonText:setAlpha( 0 )
			f36_arg0.clipFinished( f36_arg0.downButtonText )
			f36_arg0.VitaLines:completeAnimation()
			f36_arg0.VitaLines:setAlpha( 0 )
			f36_arg0.clipFinished( f36_arg0.VitaLines )
		end
	}
}
CoD.StartMenu_Options_ControllerLayout_vita.__onClose = function ( f37_arg0 )
	f37_arg0.leftStickText:close()
	f37_arg0.leftTriggerText:close()
	f37_arg0.leftBumperText:close()
	f37_arg0.rightStickText:close()
	f37_arg0.rightTriggerText:close()
	f37_arg0.rightBumperText:close()
	f37_arg0.XBAPSCrossText:close()
	f37_arg0.XBBPSCircleText:close()
	f37_arg0.XBXPSSquareText:close()
	f37_arg0.XBYPSTriangleText:close()
	f37_arg0.backButtonText:close()
	f37_arg0.startButtonText:close()
	f37_arg0.leftButtonText:close()
	f37_arg0.rightButtonText:close()
	f37_arg0.upButtonText:close()
	f37_arg0.downButtonText:close()
	f37_arg0.rightStickOverlay:close()
	f37_arg0.leftStickOverlay:close()
	f37_arg0.leftStickUpText:close()
	f37_arg0.leftStickDownText:close()
	f37_arg0.leftStickLeftRightText:close()
	f37_arg0.rightStickDownText:close()
	f37_arg0.rightStickLeftRightText:close()
	f37_arg0.rightStickUpText:close()
end

