require( "ui/uieditor/widgets/cac/cac_lock" )
require( "ui/uieditor/widgets/common/commonfocusbrackets" )
require( "ui/uieditor/widgets/director/directorselectbuttonlines" )
require( "ui/uieditor/widgets/startmenu/options/startmenuoptionsmainframe" )
require( "x64:2d361ac3553c22a" )

CoD.Challenges_CallingCardWidgetInternal = InheritFrom( LUI.UIElement )
CoD.Challenges_CallingCardWidgetInternal.__defaultWidth = 360
CoD.Challenges_CallingCardWidgetInternal.__defaultHeight = 126
CoD.Challenges_CallingCardWidgetInternal.new = function ( f1_arg0, f1_arg1, f1_arg2, f1_arg3, f1_arg4, f1_arg5, f1_arg6, f1_arg7, f1_arg8, f1_arg9 )
	local self = LUI.UIElement.new( f1_arg2, f1_arg3, f1_arg4, f1_arg5, f1_arg6, f1_arg7, f1_arg8, f1_arg9 )
	self:setClass( CoD.Challenges_CallingCardWidgetInternal )
	self.id = "Challenges_CallingCardWidgetInternal"
	self.soundSet = "FrontendMain"
	self.anyChildUsesUpdateState = true
	f1_arg0:addElementToPendingUpdateStateList( self )
	
	local NoiseTiledBacking = LUI.UIImage.new( 0, 1, 0, 0, 0, 1, 0, 0 )
	NoiseTiledBacking:setAlpha( 0.8 )
	NoiseTiledBacking:setImage( RegisterImage( 0x34839E8065B1E53 ) )
	NoiseTiledBacking:setMaterial( LUI.UIImage.GetCachedMaterial( 0x6CBE95C250C6D15 ) )
	NoiseTiledBacking:setShaderVector( 0, 0, 0, 0, 0 )
	NoiseTiledBacking:setupNineSliceShader( 196, 88 )
	self:addElement( NoiseTiledBacking )
	self.NoiseTiledBacking = NoiseTiledBacking
	
	local FocusGlow = LUI.UIImage.new( -0.09, 1.1, -110, 110, 0.5, 0.5, -99, 99 )
	FocusGlow:setAlpha( 0 )
	FocusGlow:setImage( RegisterImage( 0x8E79E4E42B6714C ) )
	FocusGlow:setMaterial( LUI.UIImage.GetCachedMaterial( 0xDAB59B2CAE01851 ) )
	FocusGlow:setShaderVector( 0, 0, 0, 0.25, 0.25 )
	FocusGlow:setShaderVector( 1, 1.2, 0, 0, 0 )
	FocusGlow:setupNineSliceShader( 300, 300 )
	self:addElement( FocusGlow )
	self.FocusGlow = FocusGlow
	
	local FrameBorder = LUI.UIImage.new( 0, 1, -1, 1, 0, 1, -1, 1 )
	FrameBorder:setAlpha( 0.15 )
	FrameBorder:setImage( RegisterImage( 0x185E11D74ECA3D7 ) )
	FrameBorder:setMaterial( LUI.UIImage.GetCachedMaterial( 0xFD777557404A7B3 ) )
	FrameBorder:setShaderVector( 0, 0, 0, 0, 0 )
	FrameBorder:setupNineSliceShader( 12, 12 )
	self:addElement( FrameBorder )
	self.FrameBorder = FrameBorder
	
	local FocusBorder = LUI.UIImage.new( 0, 1, -4, 4, 0, 1, -4, 4 )
	FocusBorder:setRGB( 0.96, 0.94, 0.78 )
	FocusBorder:setAlpha( 0 )
	FocusBorder:setImage( RegisterImage( 0xCB07CCC28498CB2 ) )
	FocusBorder:setMaterial( LUI.UIImage.GetCachedMaterial( 0xFD777557404A7B3 ) )
	FocusBorder:setShaderVector( 0, 0, 0, 0, 0 )
	FocusBorder:setupNineSliceShader( 10, 10 )
	self:addElement( FocusBorder )
	self.FocusBorder = FocusBorder
	
	local SelectorOverlay = LUI.UIImage.new( 0, 1, 0, 0, 0, 1, 0, 0 )
	SelectorOverlay:setAlpha( 0.01 )
	self:addElement( SelectorOverlay )
	self.SelectorOverlay = SelectorOverlay
	
	local FocusBrackets = CoD.CommonFocusBrackets.new( f1_arg0, f1_arg1, 0, 1, -10, 10, 0, 1, -10, 10 )
	self:addElement( FocusBrackets )
	self.FocusBrackets = FocusBrackets
	
	local CardIcon = LUI.UIImage.new( 0, 1, 1, -1, 0, 0.71, 2, -2 )
	CardIcon:linkToElementModel( self, "icon", true, function ( model )
		local f2_local0 = model:get()
		if f2_local0 ~= nil then
			CardIcon:setImage( RegisterImage( f2_local0 ) )
		end
	end )
	self:addElement( CardIcon )
	self.CardIcon = CardIcon
	
	local CardIconLockOverlay = LUI.UIImage.new( 0, 1, 1, -1, 0, 0.71, 2, -2 )
	CardIconLockOverlay:setRGB( 0, 0, 0 )
	CardIconLockOverlay:setAlpha( 0 )
	self:addElement( CardIconLockOverlay )
	self.CardIconLockOverlay = CardIconLockOverlay
	
	local DarkOpsClassifiedIcon = LUI.UIImage.new( 0, 1, 1, -1, -0, 0.71, 2, -2 )
	DarkOpsClassifiedIcon:setAlpha( 0 )
	DarkOpsClassifiedIcon:setImage( RegisterImage( 0x2746D911ABDE62E ) )
	self:addElement( DarkOpsClassifiedIcon )
	self.DarkOpsClassifiedIcon = DarkOpsClassifiedIcon
	
	local Lines = CoD.DirectorSelectButtonLines.new( f1_arg0, f1_arg1, 0, 1, 0, 0, 0, 1, 1, -1 )
	Lines:setRGB( 0.64, 0.71, 0.78 )
	self:addElement( Lines )
	self.Lines = Lines
	
	local Label = LUI.UIText.new( 0.5, 0.5, -175, 175, 0, 0, 93, 113 )
	Label:setAlpha( 0.85 )
	Label:setTTF( "ttmussels_regular" )
	Label:setLetterSpacing( 2 )
	Label:setAlignment( Enum.LUIAlignment[0xFEEB12BCB0D7041] )
	Label:setAlignment( Enum.LUIAlignment[0xE821F0ECFF8D1C7] )
	Label:linkToElementModel( self, "title", true, function ( model )
		local f3_local0 = model:get()
		if f3_local0 ~= nil then
			Label:setText( LocalizeToUpperString( f3_local0 ) )
		end
	end )
	self:addElement( Label )
	self.Label = Label
	
	local lockedIcon = CoD.cac_lock.new( f1_arg0, f1_arg1, 0.5, 0.5, -18, 18, 0, 0, 27, 63 )
	self:addElement( lockedIcon )
	self.lockedIcon = lockedIcon
	
	local TrialWidget = CoD.TrialWidget.new( f1_arg0, f1_arg1, 0, 0, 5, 30, 0, 0, 5, 30 )
	TrialWidget:setAlpha( 0 )
	self:addElement( TrialWidget )
	self.TrialWidget = TrialWidget
	
	local ProgressBarBacking = LUI.UIImage.new( 0, 0, 5, 355, 0, 0, 115, 121 )
	ProgressBarBacking:setRGB( ColorSet.T8__OFF__GRAY.r, ColorSet.T8__OFF__GRAY.g, ColorSet.T8__OFF__GRAY.b )
	ProgressBarBacking:setAlpha( 0 )
	self:addElement( ProgressBarBacking )
	self.ProgressBarBacking = ProgressBarBacking
	
	local ProgressBorder = CoD.StartMenuOptionsMainFrame.new( f1_arg0, f1_arg1, 0.5, 0.5, -175, 175, 0, 0, 115, 121 )
	ProgressBorder:setAlpha( 0 )
	self:addElement( ProgressBorder )
	self.ProgressBorder = ProgressBorder
	
	local ProgressBar = LUI.UIImage.new( 0, 0, 5, 355, 0, 0, 115, 121 )
	ProgressBar:setRGB( 1, 0.35, 0 )
	ProgressBar:setAlpha( 0 )
	ProgressBar:setMaterial( LUI.UIImage.GetCachedMaterial( 0x910274CA3518744 ) )
	ProgressBar:setShaderVector( 1, 0, 0, 0, 0 )
	ProgressBar:setShaderVector( 2, 1, 0, 0, 0 )
	ProgressBar:setShaderVector( 3, 0, 0, 0, 0 )
	ProgressBar:setShaderVector( 4, 0, 0, 0, 0 )
	ProgressBar:linkToElementModel( self, "statPercent", true, function ( model )
		local f4_local0 = model:get()
		if f4_local0 ~= nil then
			ProgressBar:setShaderVector( 0, CoD.GetVectorComponentFromString( f4_local0, 1 ), CoD.GetVectorComponentFromString( f4_local0, 2 ), CoD.GetVectorComponentFromString( f4_local0, 3 ), CoD.GetVectorComponentFromString( f4_local0, 4 ) )
		end
	end )
	self:addElement( ProgressBar )
	self.ProgressBar = ProgressBar
	
	self:mergeStateConditions( {
		{
			stateName = "Locked",
			condition = function ( menu, element, event )
				return CoD.ModelUtility.IsSelfModelValueTrue( element, f1_arg1, "isLocked" )
			end
		},
		{
			stateName = "Classified",
			condition = function ( menu, element, event )
				return AlwaysFalse()
			end
		},
		{
			stateName = "ClassifiedShowProgress",
			condition = function ( menu, element, event )
				return AlwaysFalse()
			end
		}
	} )
	self:linkToElementModel( self, "isLocked", true, function ( model )
		f1_arg0:updateElementState( self, {
			name = "model_validation",
			menu = f1_arg0,
			controller = f1_arg1,
			modelValue = model:get(),
			modelName = "isLocked"
		} )
	end )
	LUI.OverrideFunction_CallOriginalSecond( self, "close", self.__onClose )
	
	if PostLoadFunc then
		PostLoadFunc( self, f1_arg1, f1_arg0 )
	end
	
	return self
end

CoD.Challenges_CallingCardWidgetInternal.__resetProperties = function ( f9_arg0 )
	f9_arg0.lockedIcon:completeAnimation()
	f9_arg0.ProgressBar:completeAnimation()
	f9_arg0.FocusBrackets:completeAnimation()
	f9_arg0.ProgressBorder:completeAnimation()
	f9_arg0.TrialWidget:completeAnimation()
	f9_arg0.SelectorOverlay:completeAnimation()
	f9_arg0.FocusBorder:completeAnimation()
	f9_arg0.Lines:completeAnimation()
	f9_arg0.FocusGlow:completeAnimation()
	f9_arg0.Label:completeAnimation()
	f9_arg0.CardIcon:completeAnimation()
	f9_arg0.ProgressBarBacking:completeAnimation()
	f9_arg0.CardIconLockOverlay:completeAnimation()
	f9_arg0.DarkOpsClassifiedIcon:completeAnimation()
	f9_arg0.lockedIcon:setAlpha( 1 )
	f9_arg0.ProgressBar:setAlpha( 0 )
	f9_arg0.FocusBrackets:setLeftRight( 0, 1, -10, 10 )
	f9_arg0.FocusBrackets:setTopBottom( 0, 1, -10, 10 )
	f9_arg0.FocusBrackets:setAlpha( 1 )
	f9_arg0.FocusBrackets:setScale( 1, 1 )
	f9_arg0.ProgressBorder:setAlpha( 0 )
	f9_arg0.TrialWidget:setAlpha( 0 )
	f9_arg0.SelectorOverlay:setAlpha( 0.01 )
	f9_arg0.FocusBorder:setRGB( 0.96, 0.94, 0.78 )
	f9_arg0.FocusBorder:setAlpha( 0 )
	f9_arg0.Lines:setAlpha( 1 )
	f9_arg0.FocusGlow:setAlpha( 0 )
	f9_arg0.Label:setRGB( 1, 1, 1 )
	f9_arg0.CardIcon:setAlpha( 1 )
	f9_arg0.ProgressBarBacking:setAlpha( 0 )
	f9_arg0.CardIconLockOverlay:setAlpha( 0 )
	f9_arg0.DarkOpsClassifiedIcon:setAlpha( 0 )
end

CoD.Challenges_CallingCardWidgetInternal.__clipsPerState = {
	DefaultState = {
		DefaultClip = function ( f10_arg0, f10_arg1 )
			f10_arg0:__resetProperties()
			f10_arg0:setupElementClipCounter( 5 )
			f10_arg0.FocusBrackets:completeAnimation()
			f10_arg0.FocusBrackets:setAlpha( 0 )
			f10_arg0.clipFinished( f10_arg0.FocusBrackets )
			f10_arg0.lockedIcon:completeAnimation()
			f10_arg0.lockedIcon:setAlpha( 0 )
			f10_arg0.clipFinished( f10_arg0.lockedIcon )
			f10_arg0.TrialWidget:completeAnimation()
			f10_arg0.TrialWidget:setAlpha( 1 )
			f10_arg0.clipFinished( f10_arg0.TrialWidget )
			f10_arg0.ProgressBorder:completeAnimation()
			f10_arg0.ProgressBorder:setAlpha( 0 )
			f10_arg0.clipFinished( f10_arg0.ProgressBorder )
			f10_arg0.ProgressBar:completeAnimation()
			f10_arg0.ProgressBar:setAlpha( 0 )
			f10_arg0.clipFinished( f10_arg0.ProgressBar )
		end,
		Focus = function ( f11_arg0, f11_arg1 )
			f11_arg0:__resetProperties()
			f11_arg0:setupElementClipCounter( 8 )
			f11_arg0.FocusGlow:completeAnimation()
			f11_arg0.FocusGlow:setAlpha( 0.6 )
			f11_arg0.clipFinished( f11_arg0.FocusGlow )
			f11_arg0.FocusBorder:completeAnimation()
			f11_arg0.FocusBorder:setAlpha( 1 )
			f11_arg0.clipFinished( f11_arg0.FocusBorder )
			f11_arg0.SelectorOverlay:completeAnimation()
			f11_arg0.SelectorOverlay:setAlpha( 0.04 )
			f11_arg0.clipFinished( f11_arg0.SelectorOverlay )
			f11_arg0.Lines:completeAnimation()
			f11_arg0.Lines:setAlpha( 0 )
			f11_arg0.clipFinished( f11_arg0.Lines )
			f11_arg0.Label:completeAnimation()
			f11_arg0.Label:setRGB( 0.96, 0.94, 0.78 )
			f11_arg0.clipFinished( f11_arg0.Label )
			f11_arg0.lockedIcon:completeAnimation()
			f11_arg0.lockedIcon:setAlpha( 0 )
			f11_arg0.clipFinished( f11_arg0.lockedIcon )
			f11_arg0.TrialWidget:completeAnimation()
			f11_arg0.TrialWidget:setAlpha( 1 )
			f11_arg0.clipFinished( f11_arg0.TrialWidget )
			f11_arg0.ProgressBar:completeAnimation()
			f11_arg0.ProgressBar:setAlpha( 0 )
			f11_arg0.clipFinished( f11_arg0.ProgressBar )
		end,
		GainFocus = function ( f12_arg0, f12_arg1 )
			f12_arg0:__resetProperties()
			f12_arg0:setupElementClipCounter( 10 )
			local f12_local0 = function ( f13_arg0 )
				f12_arg0.FocusGlow:beginAnimation( 200 )
				f12_arg0.FocusGlow:setAlpha( 0.6 )
				f12_arg0.FocusGlow:registerEventHandler( "interrupted_keyframe", f12_arg0.clipInterrupted )
				f12_arg0.FocusGlow:registerEventHandler( "transition_complete_keyframe", f12_arg0.clipFinished )
			end
			
			f12_arg0.FocusGlow:completeAnimation()
			f12_arg0.FocusGlow:setAlpha( 0 )
			f12_local0( f12_arg0.FocusGlow )
			local f12_local1 = function ( f14_arg0 )
				f12_arg0.FocusBorder:beginAnimation( 200 )
				f12_arg0.FocusBorder:setAlpha( 1 )
				f12_arg0.FocusBorder:registerEventHandler( "interrupted_keyframe", f12_arg0.clipInterrupted )
				f12_arg0.FocusBorder:registerEventHandler( "transition_complete_keyframe", f12_arg0.clipFinished )
			end
			
			f12_arg0.FocusBorder:completeAnimation()
			f12_arg0.FocusBorder:setAlpha( 0 )
			f12_local1( f12_arg0.FocusBorder )
			local f12_local2 = function ( f15_arg0 )
				f12_arg0.SelectorOverlay:beginAnimation( 200 )
				f12_arg0.SelectorOverlay:setAlpha( 0.04 )
				f12_arg0.SelectorOverlay:registerEventHandler( "interrupted_keyframe", f12_arg0.clipInterrupted )
				f12_arg0.SelectorOverlay:registerEventHandler( "transition_complete_keyframe", f12_arg0.clipFinished )
			end
			
			f12_arg0.SelectorOverlay:completeAnimation()
			f12_arg0.SelectorOverlay:setAlpha( 0.01 )
			f12_local2( f12_arg0.SelectorOverlay )
			local f12_local3 = function ( f16_arg0 )
				local f16_local0 = function ( f17_arg0 )
					f17_arg0:beginAnimation( 50 )
					f17_arg0:setLeftRight( 0, 1, -10, 10 )
					f17_arg0:setTopBottom( 0, 1, -10, 10 )
					f17_arg0:setAlpha( 1 )
					f17_arg0:registerEventHandler( "transition_complete_keyframe", f12_arg0.clipFinished )
				end
				
				f12_arg0.FocusBrackets:beginAnimation( 100 )
				f12_arg0.FocusBrackets:setLeftRight( 0, 1, -8, 8 )
				f12_arg0.FocusBrackets:setTopBottom( 0, 1, -8, 8 )
				f12_arg0.FocusBrackets:setAlpha( 0.67 )
				f12_arg0.FocusBrackets:registerEventHandler( "interrupted_keyframe", f12_arg0.clipInterrupted )
				f12_arg0.FocusBrackets:registerEventHandler( "transition_complete_keyframe", f16_local0 )
			end
			
			f12_arg0.FocusBrackets:completeAnimation()
			f12_arg0.FocusBrackets:setLeftRight( 0, 1, -40, 40 )
			f12_arg0.FocusBrackets:setTopBottom( 0, 1, -40, 40 )
			f12_arg0.FocusBrackets:setAlpha( 0 )
			f12_local3( f12_arg0.FocusBrackets )
			local f12_local4 = function ( f18_arg0 )
				f12_arg0.Lines:beginAnimation( 200 )
				f12_arg0.Lines:setAlpha( 0 )
				f12_arg0.Lines:registerEventHandler( "interrupted_keyframe", f12_arg0.clipInterrupted )
				f12_arg0.Lines:registerEventHandler( "transition_complete_keyframe", f12_arg0.clipFinished )
			end
			
			f12_arg0.Lines:completeAnimation()
			f12_arg0.Lines:setAlpha( 1 )
			f12_local4( f12_arg0.Lines )
			f12_arg0.Label:completeAnimation()
			f12_arg0.Label:setRGB( 0.96, 0.94, 0.78 )
			f12_arg0.clipFinished( f12_arg0.Label )
			f12_arg0.lockedIcon:completeAnimation()
			f12_arg0.lockedIcon:setAlpha( 0 )
			f12_arg0.clipFinished( f12_arg0.lockedIcon )
			f12_arg0.TrialWidget:completeAnimation()
			f12_arg0.TrialWidget:setAlpha( 1 )
			f12_arg0.clipFinished( f12_arg0.TrialWidget )
			f12_arg0.ProgressBorder:completeAnimation()
			f12_arg0.ProgressBorder:setAlpha( 0 )
			f12_arg0.clipFinished( f12_arg0.ProgressBorder )
			f12_arg0.ProgressBar:completeAnimation()
			f12_arg0.ProgressBar:setAlpha( 0 )
			f12_arg0.clipFinished( f12_arg0.ProgressBar )
		end,
		LoseFocus = function ( f19_arg0, f19_arg1 )
			f19_arg0:__resetProperties()
			f19_arg0:setupElementClipCounter( 9 )
			local f19_local0 = function ( f20_arg0 )
				f19_arg0.FocusGlow:beginAnimation( 200 )
				f19_arg0.FocusGlow:setAlpha( 0 )
				f19_arg0.FocusGlow:registerEventHandler( "interrupted_keyframe", f19_arg0.clipInterrupted )
				f19_arg0.FocusGlow:registerEventHandler( "transition_complete_keyframe", f19_arg0.clipFinished )
			end
			
			f19_arg0.FocusGlow:completeAnimation()
			f19_arg0.FocusGlow:setAlpha( 0.6 )
			f19_local0( f19_arg0.FocusGlow )
			local f19_local1 = function ( f21_arg0 )
				f19_arg0.FocusBorder:beginAnimation( 200 )
				f19_arg0.FocusBorder:setAlpha( 0 )
				f19_arg0.FocusBorder:registerEventHandler( "interrupted_keyframe", f19_arg0.clipInterrupted )
				f19_arg0.FocusBorder:registerEventHandler( "transition_complete_keyframe", f19_arg0.clipFinished )
			end
			
			f19_arg0.FocusBorder:completeAnimation()
			f19_arg0.FocusBorder:setAlpha( 1 )
			f19_local1( f19_arg0.FocusBorder )
			local f19_local2 = function ( f22_arg0 )
				f19_arg0.SelectorOverlay:beginAnimation( 200 )
				f19_arg0.SelectorOverlay:setAlpha( 0.01 )
				f19_arg0.SelectorOverlay:registerEventHandler( "interrupted_keyframe", f19_arg0.clipInterrupted )
				f19_arg0.SelectorOverlay:registerEventHandler( "transition_complete_keyframe", f19_arg0.clipFinished )
			end
			
			f19_arg0.SelectorOverlay:completeAnimation()
			f19_arg0.SelectorOverlay:setAlpha( 0.04 )
			f19_local2( f19_arg0.SelectorOverlay )
			local f19_local3 = function ( f23_arg0 )
				f19_arg0.FocusBrackets:beginAnimation( 60 )
				f19_arg0.FocusBrackets:setAlpha( 0 )
				f19_arg0.FocusBrackets:registerEventHandler( "interrupted_keyframe", f19_arg0.clipInterrupted )
				f19_arg0.FocusBrackets:registerEventHandler( "transition_complete_keyframe", f19_arg0.clipFinished )
			end
			
			f19_arg0.FocusBrackets:completeAnimation()
			f19_arg0.FocusBrackets:setAlpha( 1 )
			f19_local3( f19_arg0.FocusBrackets )
			local f19_local4 = function ( f24_arg0 )
				f19_arg0.Lines:beginAnimation( 200 )
				f19_arg0.Lines:setAlpha( 1 )
				f19_arg0.Lines:registerEventHandler( "interrupted_keyframe", f19_arg0.clipInterrupted )
				f19_arg0.Lines:registerEventHandler( "transition_complete_keyframe", f19_arg0.clipFinished )
			end
			
			f19_arg0.Lines:completeAnimation()
			f19_arg0.Lines:setAlpha( 0 )
			f19_local4( f19_arg0.Lines )
			f19_arg0.lockedIcon:completeAnimation()
			f19_arg0.lockedIcon:setAlpha( 0 )
			f19_arg0.clipFinished( f19_arg0.lockedIcon )
			f19_arg0.TrialWidget:completeAnimation()
			f19_arg0.TrialWidget:setAlpha( 1 )
			f19_arg0.clipFinished( f19_arg0.TrialWidget )
			f19_arg0.ProgressBorder:completeAnimation()
			f19_arg0.ProgressBorder:setAlpha( 0 )
			f19_arg0.clipFinished( f19_arg0.ProgressBorder )
			f19_arg0.ProgressBar:completeAnimation()
			f19_arg0.ProgressBar:setAlpha( 0 )
			f19_arg0.clipFinished( f19_arg0.ProgressBar )
		end
	},
	Locked = {
		DefaultClip = function ( f25_arg0, f25_arg1 )
			f25_arg0:__resetProperties()
			f25_arg0:setupElementClipCounter( 7 )
			f25_arg0.FocusBrackets:completeAnimation()
			f25_arg0.FocusBrackets:setAlpha( 0 )
			f25_arg0.clipFinished( f25_arg0.FocusBrackets )
			f25_arg0.CardIcon:completeAnimation()
			f25_arg0.CardIcon:setAlpha( 1 )
			f25_arg0.clipFinished( f25_arg0.CardIcon )
			f25_arg0.CardIconLockOverlay:completeAnimation()
			f25_arg0.CardIconLockOverlay:setAlpha( 0.98 )
			f25_arg0.clipFinished( f25_arg0.CardIconLockOverlay )
			f25_arg0.Lines:completeAnimation()
			f25_arg0.Lines:setAlpha( 0.5 )
			f25_arg0.clipFinished( f25_arg0.Lines )
			f25_arg0.ProgressBarBacking:completeAnimation()
			f25_arg0.ProgressBarBacking:setAlpha( 0.02 )
			f25_arg0.clipFinished( f25_arg0.ProgressBarBacking )
			f25_arg0.ProgressBorder:completeAnimation()
			f25_arg0.ProgressBorder:setAlpha( 0.02 )
			f25_arg0.clipFinished( f25_arg0.ProgressBorder )
			f25_arg0.ProgressBar:completeAnimation()
			f25_arg0.ProgressBar:setAlpha( 1 )
			f25_arg0.clipFinished( f25_arg0.ProgressBar )
		end,
		Focus = function ( f26_arg0, f26_arg1 )
			f26_arg0:__resetProperties()
			f26_arg0:setupElementClipCounter( 11 )
			f26_arg0.FocusGlow:completeAnimation()
			f26_arg0.FocusGlow:setAlpha( 0 )
			f26_arg0.clipFinished( f26_arg0.FocusGlow )
			f26_arg0.FocusBorder:completeAnimation()
			f26_arg0.FocusBorder:setRGB( ColorSet.T8__OFF__WHITE.r, ColorSet.T8__OFF__WHITE.g, ColorSet.T8__OFF__WHITE.b )
			f26_arg0.FocusBorder:setAlpha( 0.25 )
			f26_arg0.clipFinished( f26_arg0.FocusBorder )
			f26_arg0.SelectorOverlay:completeAnimation()
			f26_arg0.SelectorOverlay:setAlpha( 0.04 )
			f26_arg0.clipFinished( f26_arg0.SelectorOverlay )
			f26_arg0.FocusBrackets:completeAnimation()
			f26_arg0.FocusBrackets:setAlpha( 1 )
			f26_arg0.FocusBrackets:setScale( 1, 1 )
			f26_arg0.clipFinished( f26_arg0.FocusBrackets )
			f26_arg0.CardIconLockOverlay:completeAnimation()
			f26_arg0.CardIconLockOverlay:setAlpha( 0.98 )
			f26_arg0.clipFinished( f26_arg0.CardIconLockOverlay )
			f26_arg0.Lines:completeAnimation()
			f26_arg0.Lines:setAlpha( 0 )
			f26_arg0.clipFinished( f26_arg0.Lines )
			f26_arg0.Label:completeAnimation()
			f26_arg0.Label:setRGB( 0.96, 0.94, 0.78 )
			f26_arg0.clipFinished( f26_arg0.Label )
			f26_arg0.lockedIcon:completeAnimation()
			f26_arg0.lockedIcon:setAlpha( 0.8 )
			f26_arg0.clipFinished( f26_arg0.lockedIcon )
			f26_arg0.ProgressBarBacking:completeAnimation()
			f26_arg0.ProgressBarBacking:setAlpha( 0.02 )
			f26_arg0.clipFinished( f26_arg0.ProgressBarBacking )
			f26_arg0.ProgressBorder:completeAnimation()
			f26_arg0.ProgressBorder:setAlpha( 0.05 )
			f26_arg0.clipFinished( f26_arg0.ProgressBorder )
			f26_arg0.ProgressBar:completeAnimation()
			f26_arg0.ProgressBar:setAlpha( 1 )
			f26_arg0.clipFinished( f26_arg0.ProgressBar )
		end,
		GainFocus = function ( f27_arg0, f27_arg1 )
			f27_arg0:__resetProperties()
			f27_arg0:setupElementClipCounter( 10 )
			local f27_local0 = function ( f28_arg0 )
				f27_arg0.FocusBorder:beginAnimation( 200 )
				f27_arg0.FocusBorder:setAlpha( 0.25 )
				f27_arg0.FocusBorder:registerEventHandler( "interrupted_keyframe", f27_arg0.clipInterrupted )
				f27_arg0.FocusBorder:registerEventHandler( "transition_complete_keyframe", f27_arg0.clipFinished )
			end
			
			f27_arg0.FocusBorder:completeAnimation()
			f27_arg0.FocusBorder:setRGB( ColorSet.T8__OFF__WHITE.r, ColorSet.T8__OFF__WHITE.g, ColorSet.T8__OFF__WHITE.b )
			f27_arg0.FocusBorder:setAlpha( 0 )
			f27_local0( f27_arg0.FocusBorder )
			local f27_local1 = function ( f29_arg0 )
				f27_arg0.SelectorOverlay:beginAnimation( 200 )
				f27_arg0.SelectorOverlay:setAlpha( 0.04 )
				f27_arg0.SelectorOverlay:registerEventHandler( "interrupted_keyframe", f27_arg0.clipInterrupted )
				f27_arg0.SelectorOverlay:registerEventHandler( "transition_complete_keyframe", f27_arg0.clipFinished )
			end
			
			f27_arg0.SelectorOverlay:completeAnimation()
			f27_arg0.SelectorOverlay:setAlpha( 0.01 )
			f27_local1( f27_arg0.SelectorOverlay )
			local f27_local2 = function ( f30_arg0 )
				local f30_local0 = function ( f31_arg0 )
					f31_arg0:beginAnimation( 50 )
					f31_arg0:setLeftRight( 0, 1, -10, 10 )
					f31_arg0:setTopBottom( 0, 1, -10, 10 )
					f31_arg0:setAlpha( 1 )
					f31_arg0:registerEventHandler( "transition_complete_keyframe", f27_arg0.clipFinished )
				end
				
				f27_arg0.FocusBrackets:beginAnimation( 100 )
				f27_arg0.FocusBrackets:setLeftRight( 0, 1, -8, 8 )
				f27_arg0.FocusBrackets:setTopBottom( 0, 1, -8, 8 )
				f27_arg0.FocusBrackets:setAlpha( 0.67 )
				f27_arg0.FocusBrackets:registerEventHandler( "interrupted_keyframe", f27_arg0.clipInterrupted )
				f27_arg0.FocusBrackets:registerEventHandler( "transition_complete_keyframe", f30_local0 )
			end
			
			f27_arg0.FocusBrackets:completeAnimation()
			f27_arg0.FocusBrackets:setLeftRight( 0, 1, -40, 40 )
			f27_arg0.FocusBrackets:setTopBottom( 0, 1, -40, 40 )
			f27_arg0.FocusBrackets:setAlpha( 0 )
			f27_local2( f27_arg0.FocusBrackets )
			f27_arg0.CardIconLockOverlay:completeAnimation()
			f27_arg0.CardIconLockOverlay:setAlpha( 0.98 )
			f27_arg0.clipFinished( f27_arg0.CardIconLockOverlay )
			f27_arg0.Lines:completeAnimation()
			f27_arg0.Lines:setAlpha( 0.5 )
			f27_arg0.clipFinished( f27_arg0.Lines )
			f27_arg0.Label:completeAnimation()
			f27_arg0.Label:setRGB( 0.96, 0.94, 0.78 )
			f27_arg0.clipFinished( f27_arg0.Label )
			local f27_local3 = function ( f32_arg0 )
				f27_arg0.lockedIcon:beginAnimation( 200 )
				f27_arg0.lockedIcon:setAlpha( 0.8 )
				f27_arg0.lockedIcon:registerEventHandler( "interrupted_keyframe", f27_arg0.clipInterrupted )
				f27_arg0.lockedIcon:registerEventHandler( "transition_complete_keyframe", f27_arg0.clipFinished )
			end
			
			f27_arg0.lockedIcon:completeAnimation()
			f27_arg0.lockedIcon:setAlpha( 1 )
			f27_local3( f27_arg0.lockedIcon )
			f27_arg0.ProgressBarBacking:completeAnimation()
			f27_arg0.ProgressBarBacking:setAlpha( 0.02 )
			f27_arg0.clipFinished( f27_arg0.ProgressBarBacking )
			f27_arg0.ProgressBorder:completeAnimation()
			f27_arg0.ProgressBorder:setAlpha( 0.05 )
			f27_arg0.clipFinished( f27_arg0.ProgressBorder )
			f27_arg0.ProgressBar:completeAnimation()
			f27_arg0.ProgressBar:setAlpha( 1 )
			f27_arg0.clipFinished( f27_arg0.ProgressBar )
		end,
		LoseFocus = function ( f33_arg0, f33_arg1 )
			f33_arg0:__resetProperties()
			f33_arg0:setupElementClipCounter( 9 )
			local f33_local0 = function ( f34_arg0 )
				f33_arg0.FocusBorder:beginAnimation( 150 )
				f33_arg0.FocusBorder:setAlpha( 0 )
				f33_arg0.FocusBorder:registerEventHandler( "interrupted_keyframe", f33_arg0.clipInterrupted )
				f33_arg0.FocusBorder:registerEventHandler( "transition_complete_keyframe", f33_arg0.clipFinished )
			end
			
			f33_arg0.FocusBorder:completeAnimation()
			f33_arg0.FocusBorder:setRGB( ColorSet.T8__OFF__WHITE.r, ColorSet.T8__OFF__WHITE.g, ColorSet.T8__OFF__WHITE.b )
			f33_arg0.FocusBorder:setAlpha( 0.5 )
			f33_local0( f33_arg0.FocusBorder )
			local f33_local1 = function ( f35_arg0 )
				f33_arg0.SelectorOverlay:beginAnimation( 150 )
				f33_arg0.SelectorOverlay:setAlpha( 0.01 )
				f33_arg0.SelectorOverlay:registerEventHandler( "interrupted_keyframe", f33_arg0.clipInterrupted )
				f33_arg0.SelectorOverlay:registerEventHandler( "transition_complete_keyframe", f33_arg0.clipFinished )
			end
			
			f33_arg0.SelectorOverlay:completeAnimation()
			f33_arg0.SelectorOverlay:setAlpha( 0.04 )
			f33_local1( f33_arg0.SelectorOverlay )
			local f33_local2 = function ( f36_arg0 )
				f33_arg0.FocusBrackets:beginAnimation( 60 )
				f33_arg0.FocusBrackets:setAlpha( 0 )
				f33_arg0.FocusBrackets:registerEventHandler( "interrupted_keyframe", f33_arg0.clipInterrupted )
				f33_arg0.FocusBrackets:registerEventHandler( "transition_complete_keyframe", f33_arg0.clipFinished )
			end
			
			f33_arg0.FocusBrackets:completeAnimation()
			f33_arg0.FocusBrackets:setAlpha( 1 )
			f33_local2( f33_arg0.FocusBrackets )
			f33_arg0.CardIconLockOverlay:completeAnimation()
			f33_arg0.CardIconLockOverlay:setAlpha( 0.98 )
			f33_arg0.clipFinished( f33_arg0.CardIconLockOverlay )
			local f33_local3 = function ( f37_arg0 )
				f33_arg0.Lines:beginAnimation( 150 )
				f33_arg0.Lines:setAlpha( 1 )
				f33_arg0.Lines:registerEventHandler( "interrupted_keyframe", f33_arg0.clipInterrupted )
				f33_arg0.Lines:registerEventHandler( "transition_complete_keyframe", f33_arg0.clipFinished )
			end
			
			f33_arg0.Lines:completeAnimation()
			f33_arg0.Lines:setAlpha( 0 )
			f33_local3( f33_arg0.Lines )
			local f33_local4 = function ( f38_arg0 )
				f33_arg0.lockedIcon:beginAnimation( 150 )
				f33_arg0.lockedIcon:setAlpha( 1 )
				f33_arg0.lockedIcon:registerEventHandler( "interrupted_keyframe", f33_arg0.clipInterrupted )
				f33_arg0.lockedIcon:registerEventHandler( "transition_complete_keyframe", f33_arg0.clipFinished )
			end
			
			f33_arg0.lockedIcon:completeAnimation()
			f33_arg0.lockedIcon:setAlpha( 0.8 )
			f33_local4( f33_arg0.lockedIcon )
			f33_arg0.ProgressBarBacking:completeAnimation()
			f33_arg0.ProgressBarBacking:setAlpha( 0.02 )
			f33_arg0.clipFinished( f33_arg0.ProgressBarBacking )
			f33_arg0.ProgressBorder:completeAnimation()
			f33_arg0.ProgressBorder:setAlpha( 0.05 )
			f33_arg0.clipFinished( f33_arg0.ProgressBorder )
			f33_arg0.ProgressBar:completeAnimation()
			f33_arg0.ProgressBar:setAlpha( 1 )
			f33_arg0.clipFinished( f33_arg0.ProgressBar )
		end
	},
	Classified = {
		DefaultClip = function ( f39_arg0, f39_arg1 )
			f39_arg0:__resetProperties()
			f39_arg0:setupElementClipCounter( 7 )
			f39_arg0.FocusBrackets:completeAnimation()
			f39_arg0.FocusBrackets:setAlpha( 0 )
			f39_arg0.clipFinished( f39_arg0.FocusBrackets )
			f39_arg0.CardIcon:completeAnimation()
			f39_arg0.CardIcon:setAlpha( 0 )
			f39_arg0.clipFinished( f39_arg0.CardIcon )
			f39_arg0.DarkOpsClassifiedIcon:completeAnimation()
			f39_arg0.DarkOpsClassifiedIcon:setAlpha( 1 )
			f39_arg0.clipFinished( f39_arg0.DarkOpsClassifiedIcon )
			f39_arg0.lockedIcon:completeAnimation()
			f39_arg0.lockedIcon:setAlpha( 0 )
			f39_arg0.clipFinished( f39_arg0.lockedIcon )
			f39_arg0.ProgressBarBacking:completeAnimation()
			f39_arg0.ProgressBarBacking:setAlpha( 0.1 )
			f39_arg0.clipFinished( f39_arg0.ProgressBarBacking )
			f39_arg0.ProgressBorder:completeAnimation()
			f39_arg0.ProgressBorder:setAlpha( 0.02 )
			f39_arg0.clipFinished( f39_arg0.ProgressBorder )
			f39_arg0.ProgressBar:completeAnimation()
			f39_arg0.ProgressBar:setAlpha( 0 )
			f39_arg0.clipFinished( f39_arg0.ProgressBar )
		end,
		Focus = function ( f40_arg0, f40_arg1 )
			f40_arg0:__resetProperties()
			f40_arg0:setupElementClipCounter( 7 )
			f40_arg0.FocusGlow:completeAnimation()
			f40_arg0.FocusGlow:setAlpha( 0.6 )
			f40_arg0.clipFinished( f40_arg0.FocusGlow )
			f40_arg0.FocusBorder:completeAnimation()
			f40_arg0.FocusBorder:setRGB( 0.96, 0.94, 0.78 )
			f40_arg0.FocusBorder:setAlpha( 1 )
			f40_arg0.clipFinished( f40_arg0.FocusBorder )
			f40_arg0.SelectorOverlay:completeAnimation()
			f40_arg0.SelectorOverlay:setAlpha( 0.04 )
			f40_arg0.clipFinished( f40_arg0.SelectorOverlay )
			f40_arg0.CardIcon:completeAnimation()
			f40_arg0.CardIcon:setAlpha( 0 )
			f40_arg0.clipFinished( f40_arg0.CardIcon )
			f40_arg0.DarkOpsClassifiedIcon:completeAnimation()
			f40_arg0.DarkOpsClassifiedIcon:setAlpha( 1 )
			f40_arg0.clipFinished( f40_arg0.DarkOpsClassifiedIcon )
			f40_arg0.Label:completeAnimation()
			f40_arg0.Label:setRGB( 0.96, 0.94, 0.78 )
			f40_arg0.clipFinished( f40_arg0.Label )
			f40_arg0.lockedIcon:completeAnimation()
			f40_arg0.lockedIcon:setAlpha( 0 )
			f40_arg0.clipFinished( f40_arg0.lockedIcon )
		end,
		GainFocus = function ( f41_arg0, f41_arg1 )
			f41_arg0:__resetProperties()
			f41_arg0:setupElementClipCounter( 8 )
			local f41_local0 = function ( f42_arg0 )
				f41_arg0.FocusGlow:beginAnimation( 200 )
				f41_arg0.FocusGlow:setAlpha( 0.6 )
				f41_arg0.FocusGlow:registerEventHandler( "interrupted_keyframe", f41_arg0.clipInterrupted )
				f41_arg0.FocusGlow:registerEventHandler( "transition_complete_keyframe", f41_arg0.clipFinished )
			end
			
			f41_arg0.FocusGlow:completeAnimation()
			f41_arg0.FocusGlow:setAlpha( 0 )
			f41_local0( f41_arg0.FocusGlow )
			local f41_local1 = function ( f43_arg0 )
				f41_arg0.FocusBorder:beginAnimation( 200 )
				f41_arg0.FocusBorder:setAlpha( 1 )
				f41_arg0.FocusBorder:registerEventHandler( "interrupted_keyframe", f41_arg0.clipInterrupted )
				f41_arg0.FocusBorder:registerEventHandler( "transition_complete_keyframe", f41_arg0.clipFinished )
			end
			
			f41_arg0.FocusBorder:completeAnimation()
			f41_arg0.FocusBorder:setAlpha( 0 )
			f41_local1( f41_arg0.FocusBorder )
			local f41_local2 = function ( f44_arg0 )
				f41_arg0.SelectorOverlay:beginAnimation( 200 )
				f41_arg0.SelectorOverlay:setAlpha( 0.04 )
				f41_arg0.SelectorOverlay:registerEventHandler( "interrupted_keyframe", f41_arg0.clipInterrupted )
				f41_arg0.SelectorOverlay:registerEventHandler( "transition_complete_keyframe", f41_arg0.clipFinished )
			end
			
			f41_arg0.SelectorOverlay:completeAnimation()
			f41_arg0.SelectorOverlay:setAlpha( 0.01 )
			f41_local2( f41_arg0.SelectorOverlay )
			local f41_local3 = function ( f45_arg0 )
				local f45_local0 = function ( f46_arg0 )
					f46_arg0:beginAnimation( 50 )
					f46_arg0:setLeftRight( 0, 1, -10, 10 )
					f46_arg0:setTopBottom( 0, 1, -10, 10 )
					f46_arg0:setAlpha( 1 )
					f46_arg0:registerEventHandler( "transition_complete_keyframe", f41_arg0.clipFinished )
				end
				
				f41_arg0.FocusBrackets:beginAnimation( 100 )
				f41_arg0.FocusBrackets:setLeftRight( 0, 1, -8, 8 )
				f41_arg0.FocusBrackets:setTopBottom( 0, 1, -8, 8 )
				f41_arg0.FocusBrackets:setAlpha( 0.67 )
				f41_arg0.FocusBrackets:registerEventHandler( "interrupted_keyframe", f41_arg0.clipInterrupted )
				f41_arg0.FocusBrackets:registerEventHandler( "transition_complete_keyframe", f45_local0 )
			end
			
			f41_arg0.FocusBrackets:completeAnimation()
			f41_arg0.FocusBrackets:setLeftRight( 0, 1, -40, 40 )
			f41_arg0.FocusBrackets:setTopBottom( 0, 1, -40, 40 )
			f41_arg0.FocusBrackets:setAlpha( 0 )
			f41_local3( f41_arg0.FocusBrackets )
			f41_arg0.CardIcon:completeAnimation()
			f41_arg0.CardIcon:setAlpha( 0 )
			f41_arg0.clipFinished( f41_arg0.CardIcon )
			f41_arg0.DarkOpsClassifiedIcon:completeAnimation()
			f41_arg0.DarkOpsClassifiedIcon:setAlpha( 1 )
			f41_arg0.clipFinished( f41_arg0.DarkOpsClassifiedIcon )
			f41_arg0.Label:completeAnimation()
			f41_arg0.Label:setRGB( 0.96, 0.94, 0.78 )
			f41_arg0.clipFinished( f41_arg0.Label )
			f41_arg0.lockedIcon:completeAnimation()
			f41_arg0.lockedIcon:setAlpha( 0 )
			f41_arg0.clipFinished( f41_arg0.lockedIcon )
		end,
		LoseFocus = function ( f47_arg0, f47_arg1 )
			f47_arg0:__resetProperties()
			f47_arg0:setupElementClipCounter( 7 )
			local f47_local0 = function ( f48_arg0 )
				f47_arg0.FocusGlow:beginAnimation( 200 )
				f47_arg0.FocusGlow:setAlpha( 0 )
				f47_arg0.FocusGlow:registerEventHandler( "interrupted_keyframe", f47_arg0.clipInterrupted )
				f47_arg0.FocusGlow:registerEventHandler( "transition_complete_keyframe", f47_arg0.clipFinished )
			end
			
			f47_arg0.FocusGlow:completeAnimation()
			f47_arg0.FocusGlow:setAlpha( 0.6 )
			f47_local0( f47_arg0.FocusGlow )
			local f47_local1 = function ( f49_arg0 )
				f47_arg0.FocusBorder:beginAnimation( 200 )
				f47_arg0.FocusBorder:setAlpha( 0 )
				f47_arg0.FocusBorder:registerEventHandler( "interrupted_keyframe", f47_arg0.clipInterrupted )
				f47_arg0.FocusBorder:registerEventHandler( "transition_complete_keyframe", f47_arg0.clipFinished )
			end
			
			f47_arg0.FocusBorder:completeAnimation()
			f47_arg0.FocusBorder:setAlpha( 1 )
			f47_local1( f47_arg0.FocusBorder )
			local f47_local2 = function ( f50_arg0 )
				f47_arg0.SelectorOverlay:beginAnimation( 200 )
				f47_arg0.SelectorOverlay:setAlpha( 0.01 )
				f47_arg0.SelectorOverlay:registerEventHandler( "interrupted_keyframe", f47_arg0.clipInterrupted )
				f47_arg0.SelectorOverlay:registerEventHandler( "transition_complete_keyframe", f47_arg0.clipFinished )
			end
			
			f47_arg0.SelectorOverlay:completeAnimation()
			f47_arg0.SelectorOverlay:setAlpha( 0.04 )
			f47_local2( f47_arg0.SelectorOverlay )
			local f47_local3 = function ( f51_arg0 )
				f47_arg0.FocusBrackets:beginAnimation( 60 )
				f47_arg0.FocusBrackets:setAlpha( 0 )
				f47_arg0.FocusBrackets:registerEventHandler( "interrupted_keyframe", f47_arg0.clipInterrupted )
				f47_arg0.FocusBrackets:registerEventHandler( "transition_complete_keyframe", f47_arg0.clipFinished )
			end
			
			f47_arg0.FocusBrackets:completeAnimation()
			f47_arg0.FocusBrackets:setAlpha( 1 )
			f47_local3( f47_arg0.FocusBrackets )
			f47_arg0.CardIcon:completeAnimation()
			f47_arg0.CardIcon:setAlpha( 0 )
			f47_arg0.clipFinished( f47_arg0.CardIcon )
			f47_arg0.DarkOpsClassifiedIcon:completeAnimation()
			f47_arg0.DarkOpsClassifiedIcon:setAlpha( 1 )
			f47_arg0.clipFinished( f47_arg0.DarkOpsClassifiedIcon )
			f47_arg0.lockedIcon:completeAnimation()
			f47_arg0.lockedIcon:setAlpha( 0 )
			f47_arg0.clipFinished( f47_arg0.lockedIcon )
		end
	},
	ClassifiedShowProgress = {
		DefaultClip = function ( f52_arg0, f52_arg1 )
			f52_arg0:__resetProperties()
			f52_arg0:setupElementClipCounter( 7 )
			f52_arg0.FocusBrackets:completeAnimation()
			f52_arg0.FocusBrackets:setAlpha( 0 )
			f52_arg0.clipFinished( f52_arg0.FocusBrackets )
			f52_arg0.CardIcon:completeAnimation()
			f52_arg0.CardIcon:setAlpha( 0 )
			f52_arg0.clipFinished( f52_arg0.CardIcon )
			f52_arg0.DarkOpsClassifiedIcon:completeAnimation()
			f52_arg0.DarkOpsClassifiedIcon:setAlpha( 1 )
			f52_arg0.clipFinished( f52_arg0.DarkOpsClassifiedIcon )
			f52_arg0.lockedIcon:completeAnimation()
			f52_arg0.lockedIcon:setAlpha( 0 )
			f52_arg0.clipFinished( f52_arg0.lockedIcon )
			f52_arg0.ProgressBarBacking:completeAnimation()
			f52_arg0.ProgressBarBacking:setAlpha( 0.1 )
			f52_arg0.clipFinished( f52_arg0.ProgressBarBacking )
			f52_arg0.ProgressBorder:completeAnimation()
			f52_arg0.ProgressBorder:setAlpha( 0.02 )
			f52_arg0.clipFinished( f52_arg0.ProgressBorder )
			f52_arg0.ProgressBar:completeAnimation()
			f52_arg0.ProgressBar:setAlpha( 1 )
			f52_arg0.clipFinished( f52_arg0.ProgressBar )
		end,
		Focus = function ( f53_arg0, f53_arg1 )
			f53_arg0:__resetProperties()
			f53_arg0:setupElementClipCounter( 8 )
			f53_arg0.FocusGlow:completeAnimation()
			f53_arg0.FocusGlow:setAlpha( 0.6 )
			f53_arg0.clipFinished( f53_arg0.FocusGlow )
			f53_arg0.FocusBorder:completeAnimation()
			f53_arg0.FocusBorder:setAlpha( 1 )
			f53_arg0.clipFinished( f53_arg0.FocusBorder )
			f53_arg0.SelectorOverlay:completeAnimation()
			f53_arg0.SelectorOverlay:setAlpha( 0.04 )
			f53_arg0.clipFinished( f53_arg0.SelectorOverlay )
			f53_arg0.CardIcon:completeAnimation()
			f53_arg0.CardIcon:setAlpha( 0 )
			f53_arg0.clipFinished( f53_arg0.CardIcon )
			f53_arg0.DarkOpsClassifiedIcon:completeAnimation()
			f53_arg0.DarkOpsClassifiedIcon:setAlpha( 1 )
			f53_arg0.clipFinished( f53_arg0.DarkOpsClassifiedIcon )
			f53_arg0.Label:completeAnimation()
			f53_arg0.Label:setRGB( 0.96, 0.94, 0.78 )
			f53_arg0.clipFinished( f53_arg0.Label )
			f53_arg0.lockedIcon:completeAnimation()
			f53_arg0.lockedIcon:setAlpha( 0 )
			f53_arg0.clipFinished( f53_arg0.lockedIcon )
			f53_arg0.ProgressBar:completeAnimation()
			f53_arg0.ProgressBar:setAlpha( 1 )
			f53_arg0.clipFinished( f53_arg0.ProgressBar )
		end,
		GainFocus = function ( f54_arg0, f54_arg1 )
			f54_arg0:__resetProperties()
			f54_arg0:setupElementClipCounter( 9 )
			local f54_local0 = function ( f55_arg0 )
				f54_arg0.FocusGlow:beginAnimation( 200 )
				f54_arg0.FocusGlow:setAlpha( 0.6 )
				f54_arg0.FocusGlow:registerEventHandler( "interrupted_keyframe", f54_arg0.clipInterrupted )
				f54_arg0.FocusGlow:registerEventHandler( "transition_complete_keyframe", f54_arg0.clipFinished )
			end
			
			f54_arg0.FocusGlow:completeAnimation()
			f54_arg0.FocusGlow:setAlpha( 0 )
			f54_local0( f54_arg0.FocusGlow )
			local f54_local1 = function ( f56_arg0 )
				f54_arg0.FocusBorder:beginAnimation( 200 )
				f54_arg0.FocusBorder:setAlpha( 1 )
				f54_arg0.FocusBorder:registerEventHandler( "interrupted_keyframe", f54_arg0.clipInterrupted )
				f54_arg0.FocusBorder:registerEventHandler( "transition_complete_keyframe", f54_arg0.clipFinished )
			end
			
			f54_arg0.FocusBorder:completeAnimation()
			f54_arg0.FocusBorder:setAlpha( 0 )
			f54_local1( f54_arg0.FocusBorder )
			local f54_local2 = function ( f57_arg0 )
				f54_arg0.SelectorOverlay:beginAnimation( 200 )
				f54_arg0.SelectorOverlay:setAlpha( 0.04 )
				f54_arg0.SelectorOverlay:registerEventHandler( "interrupted_keyframe", f54_arg0.clipInterrupted )
				f54_arg0.SelectorOverlay:registerEventHandler( "transition_complete_keyframe", f54_arg0.clipFinished )
			end
			
			f54_arg0.SelectorOverlay:completeAnimation()
			f54_arg0.SelectorOverlay:setAlpha( 0.01 )
			f54_local2( f54_arg0.SelectorOverlay )
			local f54_local3 = function ( f58_arg0 )
				local f58_local0 = function ( f59_arg0 )
					f59_arg0:beginAnimation( 50 )
					f59_arg0:setLeftRight( 0, 1, -10, 10 )
					f59_arg0:setTopBottom( 0, 1, -10, 10 )
					f59_arg0:setAlpha( 1 )
					f59_arg0:registerEventHandler( "transition_complete_keyframe", f54_arg0.clipFinished )
				end
				
				f54_arg0.FocusBrackets:beginAnimation( 100 )
				f54_arg0.FocusBrackets:setLeftRight( 0, 1, -8, 8 )
				f54_arg0.FocusBrackets:setTopBottom( 0, 1, -8, 8 )
				f54_arg0.FocusBrackets:setAlpha( 0.67 )
				f54_arg0.FocusBrackets:registerEventHandler( "interrupted_keyframe", f54_arg0.clipInterrupted )
				f54_arg0.FocusBrackets:registerEventHandler( "transition_complete_keyframe", f58_local0 )
			end
			
			f54_arg0.FocusBrackets:completeAnimation()
			f54_arg0.FocusBrackets:setLeftRight( 0, 1, -40, 40 )
			f54_arg0.FocusBrackets:setTopBottom( 0, 1, -40, 40 )
			f54_arg0.FocusBrackets:setAlpha( 0 )
			f54_local3( f54_arg0.FocusBrackets )
			f54_arg0.CardIcon:completeAnimation()
			f54_arg0.CardIcon:setAlpha( 0 )
			f54_arg0.clipFinished( f54_arg0.CardIcon )
			f54_arg0.DarkOpsClassifiedIcon:completeAnimation()
			f54_arg0.DarkOpsClassifiedIcon:setAlpha( 1 )
			f54_arg0.clipFinished( f54_arg0.DarkOpsClassifiedIcon )
			f54_arg0.Label:completeAnimation()
			f54_arg0.Label:setRGB( 0.96, 0.94, 0.78 )
			f54_arg0.clipFinished( f54_arg0.Label )
			f54_arg0.lockedIcon:completeAnimation()
			f54_arg0.lockedIcon:setAlpha( 0 )
			f54_arg0.clipFinished( f54_arg0.lockedIcon )
			f54_arg0.ProgressBar:completeAnimation()
			f54_arg0.ProgressBar:setAlpha( 1 )
			f54_arg0.clipFinished( f54_arg0.ProgressBar )
		end,
		LoseFocus = function ( f60_arg0, f60_arg1 )
			f60_arg0:__resetProperties()
			f60_arg0:setupElementClipCounter( 8 )
			local f60_local0 = function ( f61_arg0 )
				f60_arg0.FocusGlow:beginAnimation( 200 )
				f60_arg0.FocusGlow:setAlpha( 0 )
				f60_arg0.FocusGlow:registerEventHandler( "interrupted_keyframe", f60_arg0.clipInterrupted )
				f60_arg0.FocusGlow:registerEventHandler( "transition_complete_keyframe", f60_arg0.clipFinished )
			end
			
			f60_arg0.FocusGlow:completeAnimation()
			f60_arg0.FocusGlow:setAlpha( 0.6 )
			f60_local0( f60_arg0.FocusGlow )
			local f60_local1 = function ( f62_arg0 )
				f60_arg0.FocusBorder:beginAnimation( 200 )
				f60_arg0.FocusBorder:setAlpha( 0 )
				f60_arg0.FocusBorder:registerEventHandler( "interrupted_keyframe", f60_arg0.clipInterrupted )
				f60_arg0.FocusBorder:registerEventHandler( "transition_complete_keyframe", f60_arg0.clipFinished )
			end
			
			f60_arg0.FocusBorder:completeAnimation()
			f60_arg0.FocusBorder:setAlpha( 1 )
			f60_local1( f60_arg0.FocusBorder )
			local f60_local2 = function ( f63_arg0 )
				f60_arg0.SelectorOverlay:beginAnimation( 200 )
				f60_arg0.SelectorOverlay:setAlpha( 0.01 )
				f60_arg0.SelectorOverlay:registerEventHandler( "interrupted_keyframe", f60_arg0.clipInterrupted )
				f60_arg0.SelectorOverlay:registerEventHandler( "transition_complete_keyframe", f60_arg0.clipFinished )
			end
			
			f60_arg0.SelectorOverlay:completeAnimation()
			f60_arg0.SelectorOverlay:setAlpha( 0.04 )
			f60_local2( f60_arg0.SelectorOverlay )
			local f60_local3 = function ( f64_arg0 )
				f60_arg0.FocusBrackets:beginAnimation( 60 )
				f60_arg0.FocusBrackets:setAlpha( 0 )
				f60_arg0.FocusBrackets:registerEventHandler( "interrupted_keyframe", f60_arg0.clipInterrupted )
				f60_arg0.FocusBrackets:registerEventHandler( "transition_complete_keyframe", f60_arg0.clipFinished )
			end
			
			f60_arg0.FocusBrackets:completeAnimation()
			f60_arg0.FocusBrackets:setAlpha( 1 )
			f60_local3( f60_arg0.FocusBrackets )
			f60_arg0.CardIcon:completeAnimation()
			f60_arg0.CardIcon:setAlpha( 0 )
			f60_arg0.clipFinished( f60_arg0.CardIcon )
			f60_arg0.DarkOpsClassifiedIcon:completeAnimation()
			f60_arg0.DarkOpsClassifiedIcon:setAlpha( 1 )
			f60_arg0.clipFinished( f60_arg0.DarkOpsClassifiedIcon )
			f60_arg0.lockedIcon:completeAnimation()
			f60_arg0.lockedIcon:setAlpha( 0 )
			f60_arg0.clipFinished( f60_arg0.lockedIcon )
			f60_arg0.ProgressBar:completeAnimation()
			f60_arg0.ProgressBar:setAlpha( 1 )
			f60_arg0.clipFinished( f60_arg0.ProgressBar )
		end
	}
}
CoD.Challenges_CallingCardWidgetInternal.__onClose = function ( f65_arg0 )
	f65_arg0.FocusBrackets:close()
	f65_arg0.CardIcon:close()
	f65_arg0.Lines:close()
	f65_arg0.Label:close()
	f65_arg0.lockedIcon:close()
	f65_arg0.TrialWidget:close()
	f65_arg0.ProgressBorder:close()
	f65_arg0.ProgressBar:close()
end

