require( "ui/uieditor/widgets/cac/cac_lock" )
require( "ui/uieditor/widgets/cac/menuselectscreen/weaponnamewidget" )
require( "ui/uieditor/widgets/callingcards/callingcards_framewidget" )
require( "ui/uieditor/widgets/common/commonfocusbrackets" )
require( "ui/uieditor/widgets/director/directorselectbuttonlines" )
require( "ui/uieditor/widgets/store/storecommontextbacking" )
require( "x64:2d361ac3553c22a" )

CoD.Challenges_MasterCallingCardWidget_Internal = InheritFrom( LUI.UIElement )
CoD.Challenges_MasterCallingCardWidget_Internal.__defaultWidth = 1131
CoD.Challenges_MasterCallingCardWidget_Internal.__defaultHeight = 100
CoD.Challenges_MasterCallingCardWidget_Internal.new = function ( f1_arg0, f1_arg1, f1_arg2, f1_arg3, f1_arg4, f1_arg5, f1_arg6, f1_arg7, f1_arg8, f1_arg9 )
	local self = LUI.UIElement.new( f1_arg2, f1_arg3, f1_arg4, f1_arg5, f1_arg6, f1_arg7, f1_arg8, f1_arg9 )
	self:setClass( CoD.Challenges_MasterCallingCardWidget_Internal )
	self.id = "Challenges_MasterCallingCardWidget_Internal"
	self.soundSet = "FrontendMain"
	self.anyChildUsesUpdateState = true
	f1_arg0:addElementToPendingUpdateStateList( self )
	
	local NoiseTiledBacking = LUI.UIImage.new( 0, 1, 0, 0, 0, 1, 0, 0 )
	NoiseTiledBacking:setAlpha( 0.1 )
	NoiseTiledBacking:setImage( RegisterImage( 0x34839E8065B1E53 ) )
	NoiseTiledBacking:setMaterial( LUI.UIImage.GetCachedMaterial( 0x6CBE95C250C6D15 ) )
	NoiseTiledBacking:setShaderVector( 0, 0, 0, 0, 0 )
	NoiseTiledBacking:setupNineSliceShader( 196, 88 )
	self:addElement( NoiseTiledBacking )
	self.NoiseTiledBacking = NoiseTiledBacking
	
	local FocusGlow = LUI.UIImage.new( -0.04, 1.04, -100, 100, 0.5, 0.5, -80, 80 )
	FocusGlow:setAlpha( 0 )
	FocusGlow:setImage( RegisterImage( 0x8E79E4E42B6714C ) )
	FocusGlow:setMaterial( LUI.UIImage.GetCachedMaterial( 0xDAB59B2CAE01851 ) )
	FocusGlow:setShaderVector( 0, 0, 0, 0.25, 0.25 )
	FocusGlow:setShaderVector( 1, 1.2, 0, 0, 0 )
	FocusGlow:setupNineSliceShader( 300, 300 )
	self:addElement( FocusGlow )
	self.FocusGlow = FocusGlow
	
	local SelectorOverlay = LUI.UIImage.new( 0.06, 1.06, -64, -64, 0.64, 1.64, -64, -64 )
	SelectorOverlay:setRGB( ColorSet.T8__OFF__WHITE.r, ColorSet.T8__OFF__WHITE.g, ColorSet.T8__OFF__WHITE.b )
	SelectorOverlay:setAlpha( 0.01 )
	self:addElement( SelectorOverlay )
	self.SelectorOverlay = SelectorOverlay
	
	local FrameBorder = LUI.UIImage.new( 0, 1, -1, 1, 0, 1, -1, 1 )
	FrameBorder:setAlpha( 0.15 )
	FrameBorder:setImage( RegisterImage( 0x185E11D74ECA3D7 ) )
	FrameBorder:setMaterial( LUI.UIImage.GetCachedMaterial( 0xFD777557404A7B3 ) )
	FrameBorder:setShaderVector( 0, 0, 0, 0, 0 )
	FrameBorder:setupNineSliceShader( 12, 12 )
	self:addElement( FrameBorder )
	self.FrameBorder = FrameBorder
	
	local Lines = CoD.DirectorSelectButtonLines.new( f1_arg0, f1_arg1, 0, 1, 0, 0, 0, 1, 1, -1 )
	Lines:setRGB( 0.64, 0.71, 0.78 )
	self:addElement( Lines )
	self.Lines = Lines
	
	local FocusBorder = LUI.UIImage.new( 0, 1, -4, 4, 0, 1, -4, 4 )
	FocusBorder:setRGB( 0.96, 0.94, 0.78 )
	FocusBorder:setAlpha( 0 )
	FocusBorder:setImage( RegisterImage( 0xCB07CCC28498CB2 ) )
	FocusBorder:setMaterial( LUI.UIImage.GetCachedMaterial( 0xFD777557404A7B3 ) )
	FocusBorder:setShaderVector( 0, 0, 0, 0, 0 )
	FocusBorder:setupNineSliceShader( 10, 10 )
	self:addElement( FocusBorder )
	self.FocusBorder = FocusBorder
	
	local MasterCallingCardIcon = CoD.CallingCards_FrameWidget.new( f1_arg0, f1_arg1, 1, 1, -366, -6, 0, 0, 4.5, 95.5 )
	MasterCallingCardIcon:linkToElementModel( self, nil, false, function ( model )
		MasterCallingCardIcon:setModel( model, f1_arg1 )
	end )
	self:addElement( MasterCallingCardIcon )
	self.MasterCallingCardIcon = MasterCallingCardIcon
	
	local CallingCardIconLockOverlay = LUI.UIImage.new( 1, 1, -366, -6, 0, 0, 4.5, 95.5 )
	CallingCardIconLockOverlay:setRGB( 0, 0, 0 )
	CallingCardIconLockOverlay:setAlpha( 0 )
	self:addElement( CallingCardIconLockOverlay )
	self.CallingCardIconLockOverlay = CallingCardIconLockOverlay
	
	local DarkOpsClassifiedIcon = LUI.UIImage.new( 1, 1, -369, -3, 0, 0, 4.5, 95.5 )
	DarkOpsClassifiedIcon:setAlpha( 0 )
	DarkOpsClassifiedIcon:setImage( RegisterImage( 0x2746D911ABDE62E ) )
	self:addElement( DarkOpsClassifiedIcon )
	self.DarkOpsClassifiedIcon = DarkOpsClassifiedIcon
	
	local LockedIcon = CoD.cac_lock.new( f1_arg0, f1_arg1, 1, 1, -204, -168, 0, 0, 34, 70 )
	self:addElement( LockedIcon )
	self.LockedIcon = LockedIcon
	
	local TrialWidget = CoD.TrialWidget.new( f1_arg0, f1_arg1, 1, 1, -360, -335, 0, 0, 10, 35 )
	TrialWidget:setAlpha( 0 )
	self:addElement( TrialWidget )
	self.TrialWidget = TrialWidget
	
	local DotTiledBacking = CoD.StoreCommonTextBacking.new( f1_arg0, f1_arg1, 0, 0.67, 5, 3, 0.04, 0.96, 2, -2 )
	DotTiledBacking:setAlpha( 0.15 )
	self:addElement( DotTiledBacking )
	self.DotTiledBacking = DotTiledBacking
	
	local ProgressBarFrameBorder = LUI.UIImage.new( 0, 0.67, 3, 5, 0.05, 0.95, -1, 1 )
	ProgressBarFrameBorder:setAlpha( 0.1 )
	ProgressBarFrameBorder:setImage( RegisterImage( 0x185E11D74ECA3D7 ) )
	ProgressBarFrameBorder:setMaterial( LUI.UIImage.GetCachedMaterial( 0xFD777557404A7B3 ) )
	ProgressBarFrameBorder:setShaderVector( 0, 0, 0, 0, 0 )
	ProgressBarFrameBorder:setupNineSliceShader( 12, 12 )
	self:addElement( ProgressBarFrameBorder )
	self.ProgressBarFrameBorder = ProgressBarFrameBorder
	
	local ProgressBar = LUI.UIImage.new( 0, 0.67, 5, 3, 0.05, 0.95, 1, -1 )
	ProgressBar:setRGB( 1, 0.36, 0 )
	ProgressBar:setAlpha( 0.15 )
	ProgressBar:setMaterial( LUI.UIImage.GetCachedMaterial( 0x910274CA3518744 ) )
	ProgressBar:setShaderVector( 1, 0, 0, 0, 0 )
	ProgressBar:setShaderVector( 2, 1, 0, 0, 0 )
	ProgressBar:setShaderVector( 3, 0, 0, 0, 0 )
	ProgressBar:setShaderVector( 4, 0, 0, 0, 0 )
	ProgressBar:linkToElementModel( self, "percentComplete", true, function ( model )
		local f3_local0 = model:get()
		if f3_local0 ~= nil then
			ProgressBar:setShaderVector( 0, CoD.GetVectorComponentFromString( f3_local0, 1 ), CoD.GetVectorComponentFromString( f3_local0, 2 ), CoD.GetVectorComponentFromString( f3_local0, 3 ), CoD.GetVectorComponentFromString( f3_local0, 4 ) )
		end
	end )
	self:addElement( ProgressBar )
	self.ProgressBar = ProgressBar
	
	local EmblemSubtitle = LUI.UIText.new( 0, 0, 24, 738, 0, 0, 56.5, 74.5 )
	EmblemSubtitle:setRGB( ColorSet.T8__OFF__GRAY.r, ColorSet.T8__OFF__GRAY.g, ColorSet.T8__OFF__GRAY.b )
	EmblemSubtitle:setTTF( "dinnext_regular" )
	EmblemSubtitle:setLetterSpacing( 2 )
	EmblemSubtitle:setAlignment( Enum.LUIAlignment[0x58C8A85F2048829] )
	EmblemSubtitle:setAlignment( Enum.LUIAlignment[0xF41D595A2B0EDF3] )
	EmblemSubtitle:linkToElementModel( self, "description", true, function ( model )
		local f4_local0 = model:get()
		if f4_local0 ~= nil then
			EmblemSubtitle:setText( LocalizeHash( f4_local0 ) )
		end
	end )
	self:addElement( EmblemSubtitle )
	self.EmblemSubtitle = EmblemSubtitle
	
	local EmblemName = CoD.WeaponNameWidget.new( f1_arg0, f1_arg1, 0, 0, 24, 481, 0, 0, 18.5, 46.5 )
	EmblemName:setRGB( ColorSet.T8__OFF__WHITE.r, ColorSet.T8__OFF__WHITE.g, ColorSet.T8__OFF__WHITE.b )
	EmblemName:setAlpha( 0 )
	EmblemName.weaponNameLabel:setTTF( "ttmussels_regular" )
	EmblemName:linkToElementModel( self, "title", true, function ( model )
		local f5_local0 = model:get()
		if f5_local0 ~= nil then
			EmblemName.weaponNameLabel:setText( LocalizeToUpperString( f5_local0 ) )
		end
	end )
	self:addElement( EmblemName )
	self.EmblemName = EmblemName
	
	local EmblemNameNew = LUI.UIText.new( 0, 0, 24, 481, 0, 0, 16.5, 52.5 )
	EmblemNameNew:setRGB( ColorSet.T8__OFF__WHITE.r, ColorSet.T8__OFF__WHITE.g, ColorSet.T8__OFF__WHITE.b )
	EmblemNameNew:setTTF( "ttmussels_regular" )
	EmblemNameNew:setLetterSpacing( 4 )
	EmblemNameNew:setAlignment( Enum.LUIAlignment[0x58C8A85F2048829] )
	EmblemNameNew:linkToElementModel( self, "title", true, function ( model )
		local f6_local0 = model:get()
		if f6_local0 ~= nil then
			EmblemNameNew:setText( LocalizeToUpperString( f6_local0 ) )
		end
	end )
	self:addElement( EmblemNameNew )
	self.EmblemNameNew = EmblemNameNew
	
	local percentText = LUI.UIText.new( 0.5, 0.5, 82.5, 172.5, 0.5, 0.5, -10.5, 16.5 )
	percentText:setRGB( ColorSet.T8__OFF__WHITE.r, ColorSet.T8__OFF__WHITE.g, ColorSet.T8__OFF__WHITE.b )
	percentText:setAlpha( 0.8 )
	percentText:setTTF( "dinnext_regular" )
	percentText:setAlignment( Enum.LUIAlignment[0x830CFD395E6AA0A] )
	percentText:setAlignment( Enum.LUIAlignment[0xF41D595A2B0EDF3] )
	percentText:linkToElementModel( self, "percentComplete", true, function ( model )
		local f7_local0 = model:get()
		if f7_local0 ~= nil then
			percentText:setText( NumberAsPercentRounded( f7_local0 ) )
		end
	end )
	self:addElement( percentText )
	self.percentText = percentText
	
	local FocusBrackets = CoD.CommonFocusBrackets.new( f1_arg0, f1_arg1, 0, 1, -10, 10, 0, 1, -10, 10 )
	self:addElement( FocusBrackets )
	self.FocusBrackets = FocusBrackets
	
	local CompleteIcon = LUI.UIImage.new( 0, 0, 601, 661, 0.5, 0.5, -30, 30 )
	CompleteIcon:setAlpha( 0 )
	CompleteIcon:setImage( RegisterImage( 0x98D02A0405ED520 ) )
	self:addElement( CompleteIcon )
	self.CompleteIcon = CompleteIcon
	
	MasterCallingCardIcon.id = "MasterCallingCardIcon"
	LUI.OverrideFunction_CallOriginalSecond( self, "close", self.__onClose )
	
	if PostLoadFunc then
		PostLoadFunc( self, f1_arg1, f1_arg0 )
	end
	
	return self
end

CoD.Challenges_MasterCallingCardWidget_Internal.__resetProperties = function ( f8_arg0 )
	f8_arg0.LockedIcon:completeAnimation()
	f8_arg0.FocusBrackets:completeAnimation()
	f8_arg0.percentText:completeAnimation()
	f8_arg0.Lines:completeAnimation()
	f8_arg0.FocusBorder:completeAnimation()
	f8_arg0.FocusGlow:completeAnimation()
	f8_arg0.SelectorOverlay:completeAnimation()
	f8_arg0.EmblemNameNew:completeAnimation()
	f8_arg0.MasterCallingCardIcon:completeAnimation()
	f8_arg0.DarkOpsClassifiedIcon:completeAnimation()
	f8_arg0.CallingCardIconLockOverlay:completeAnimation()
	f8_arg0.ProgressBar:completeAnimation()
	f8_arg0.CompleteIcon:completeAnimation()
	f8_arg0.TrialWidget:completeAnimation()
	f8_arg0.LockedIcon:setAlpha( 1 )
	f8_arg0.FocusBrackets:setLeftRight( 0, 1, -10, 10 )
	f8_arg0.FocusBrackets:setTopBottom( 0, 1, -10, 10 )
	f8_arg0.FocusBrackets:setAlpha( 1 )
	f8_arg0.percentText:setRGB( ColorSet.T8__OFF__WHITE.r, ColorSet.T8__OFF__WHITE.g, ColorSet.T8__OFF__WHITE.b )
	f8_arg0.percentText:setAlpha( 0.8 )
	f8_arg0.Lines:setAlpha( 1 )
	f8_arg0.FocusBorder:setRGB( 0.96, 0.94, 0.78 )
	f8_arg0.FocusBorder:setAlpha( 0 )
	f8_arg0.FocusGlow:setAlpha( 0 )
	f8_arg0.SelectorOverlay:setAlpha( 0.01 )
	f8_arg0.EmblemNameNew:setRGB( ColorSet.T8__OFF__WHITE.r, ColorSet.T8__OFF__WHITE.g, ColorSet.T8__OFF__WHITE.b )
	f8_arg0.MasterCallingCardIcon:setAlpha( 1 )
	f8_arg0.DarkOpsClassifiedIcon:setAlpha( 0 )
	f8_arg0.CallingCardIconLockOverlay:setAlpha( 0 )
	f8_arg0.ProgressBar:setAlpha( 0.15 )
	f8_arg0.CompleteIcon:setAlpha( 0 )
	f8_arg0.TrialWidget:setAlpha( 0 )
end

CoD.Challenges_MasterCallingCardWidget_Internal.__clipsPerState = {
	DefaultState = {
		DefaultClip = function ( f9_arg0, f9_arg1 )
			f9_arg0:__resetProperties()
			f9_arg0:setupElementClipCounter( 2 )
			f9_arg0.LockedIcon:completeAnimation()
			f9_arg0.LockedIcon:setAlpha( 0 )
			f9_arg0.clipFinished( f9_arg0.LockedIcon )
			f9_arg0.FocusBrackets:completeAnimation()
			f9_arg0.FocusBrackets:setAlpha( 0 )
			f9_arg0.clipFinished( f9_arg0.FocusBrackets )
		end,
		Focus = function ( f10_arg0, f10_arg1 )
			f10_arg0:__resetProperties()
			f10_arg0:setupElementClipCounter( 7 )
			f10_arg0.FocusGlow:completeAnimation()
			f10_arg0.FocusGlow:setAlpha( 1 )
			f10_arg0.clipFinished( f10_arg0.FocusGlow )
			f10_arg0.SelectorOverlay:completeAnimation()
			f10_arg0.SelectorOverlay:setAlpha( 0.04 )
			f10_arg0.clipFinished( f10_arg0.SelectorOverlay )
			f10_arg0.Lines:completeAnimation()
			f10_arg0.Lines:setAlpha( 0 )
			f10_arg0.clipFinished( f10_arg0.Lines )
			f10_arg0.FocusBorder:completeAnimation()
			f10_arg0.FocusBorder:setAlpha( 1 )
			f10_arg0.clipFinished( f10_arg0.FocusBorder )
			f10_arg0.LockedIcon:completeAnimation()
			f10_arg0.LockedIcon:setAlpha( 0 )
			f10_arg0.clipFinished( f10_arg0.LockedIcon )
			f10_arg0.EmblemNameNew:completeAnimation()
			f10_arg0.EmblemNameNew:setRGB( 0.96, 0.94, 0.78 )
			f10_arg0.clipFinished( f10_arg0.EmblemNameNew )
			f10_arg0.percentText:completeAnimation()
			f10_arg0.percentText:setRGB( 0.96, 0.94, 0.78 )
			f10_arg0.percentText:setAlpha( 0.8 )
			f10_arg0.clipFinished( f10_arg0.percentText )
		end,
		GainFocus = function ( f11_arg0, f11_arg1 )
			f11_arg0:__resetProperties()
			f11_arg0:setupElementClipCounter( 8 )
			local f11_local0 = function ( f12_arg0 )
				f11_arg0.FocusGlow:beginAnimation( 200 )
				f11_arg0.FocusGlow:setAlpha( 1 )
				f11_arg0.FocusGlow:registerEventHandler( "interrupted_keyframe", f11_arg0.clipInterrupted )
				f11_arg0.FocusGlow:registerEventHandler( "transition_complete_keyframe", f11_arg0.clipFinished )
			end
			
			f11_arg0.FocusGlow:completeAnimation()
			f11_arg0.FocusGlow:setAlpha( 0 )
			f11_local0( f11_arg0.FocusGlow )
			local f11_local1 = function ( f13_arg0 )
				f11_arg0.SelectorOverlay:beginAnimation( 200 )
				f11_arg0.SelectorOverlay:setAlpha( 0.04 )
				f11_arg0.SelectorOverlay:registerEventHandler( "interrupted_keyframe", f11_arg0.clipInterrupted )
				f11_arg0.SelectorOverlay:registerEventHandler( "transition_complete_keyframe", f11_arg0.clipFinished )
			end
			
			f11_arg0.SelectorOverlay:completeAnimation()
			f11_arg0.SelectorOverlay:setAlpha( 0.01 )
			f11_local1( f11_arg0.SelectorOverlay )
			local f11_local2 = function ( f14_arg0 )
				f11_arg0.Lines:beginAnimation( 200 )
				f11_arg0.Lines:setAlpha( 0 )
				f11_arg0.Lines:registerEventHandler( "interrupted_keyframe", f11_arg0.clipInterrupted )
				f11_arg0.Lines:registerEventHandler( "transition_complete_keyframe", f11_arg0.clipFinished )
			end
			
			f11_arg0.Lines:completeAnimation()
			f11_arg0.Lines:setAlpha( 1 )
			f11_local2( f11_arg0.Lines )
			local f11_local3 = function ( f15_arg0 )
				f11_arg0.FocusBorder:beginAnimation( 200 )
				f11_arg0.FocusBorder:setAlpha( 1 )
				f11_arg0.FocusBorder:registerEventHandler( "interrupted_keyframe", f11_arg0.clipInterrupted )
				f11_arg0.FocusBorder:registerEventHandler( "transition_complete_keyframe", f11_arg0.clipFinished )
			end
			
			f11_arg0.FocusBorder:completeAnimation()
			f11_arg0.FocusBorder:setAlpha( 0 )
			f11_local3( f11_arg0.FocusBorder )
			f11_arg0.LockedIcon:completeAnimation()
			f11_arg0.LockedIcon:setAlpha( 0 )
			f11_arg0.clipFinished( f11_arg0.LockedIcon )
			f11_arg0.EmblemNameNew:completeAnimation()
			f11_arg0.EmblemNameNew:setRGB( 0.96, 0.94, 0.78 )
			f11_arg0.clipFinished( f11_arg0.EmblemNameNew )
			f11_arg0.percentText:completeAnimation()
			f11_arg0.percentText:setRGB( 0.96, 0.94, 0.78 )
			f11_arg0.percentText:setAlpha( 0.8 )
			f11_arg0.clipFinished( f11_arg0.percentText )
			local f11_local4 = function ( f16_arg0 )
				local f16_local0 = function ( f17_arg0 )
					local f17_local0 = function ( f18_arg0 )
						f18_arg0:beginAnimation( 49 )
						f18_arg0:setAlpha( 0 )
						f18_arg0:registerEventHandler( "transition_complete_keyframe", f11_arg0.clipFinished )
					end
					
					f17_arg0:beginAnimation( 50 )
					f17_arg0:setLeftRight( 0, 1, -10, 10 )
					f17_arg0:setTopBottom( 0, 1, -10, 10 )
					f17_arg0:setAlpha( 1 )
					f17_arg0:registerEventHandler( "transition_complete_keyframe", f17_local0 )
				end
				
				f11_arg0.FocusBrackets:beginAnimation( 100 )
				f11_arg0.FocusBrackets:setLeftRight( 0, 1, -8, 8 )
				f11_arg0.FocusBrackets:setTopBottom( 0, 1, -8, 8 )
				f11_arg0.FocusBrackets:setAlpha( 0.67 )
				f11_arg0.FocusBrackets:registerEventHandler( "interrupted_keyframe", f11_arg0.clipInterrupted )
				f11_arg0.FocusBrackets:registerEventHandler( "transition_complete_keyframe", f16_local0 )
			end
			
			f11_arg0.FocusBrackets:completeAnimation()
			f11_arg0.FocusBrackets:setLeftRight( 0, 1, -40, 40 )
			f11_arg0.FocusBrackets:setTopBottom( 0, 1, -40, 40 )
			f11_arg0.FocusBrackets:setAlpha( 0 )
			f11_local4( f11_arg0.FocusBrackets )
		end,
		LoseFocus = function ( f19_arg0, f19_arg1 )
			f19_arg0:__resetProperties()
			f19_arg0:setupElementClipCounter( 7 )
			local f19_local0 = function ( f20_arg0 )
				f19_arg0.FocusGlow:beginAnimation( 200 )
				f19_arg0.FocusGlow:setAlpha( 0 )
				f19_arg0.FocusGlow:registerEventHandler( "interrupted_keyframe", f19_arg0.clipInterrupted )
				f19_arg0.FocusGlow:registerEventHandler( "transition_complete_keyframe", f19_arg0.clipFinished )
			end
			
			f19_arg0.FocusGlow:completeAnimation()
			f19_arg0.FocusGlow:setAlpha( 1 )
			f19_local0( f19_arg0.FocusGlow )
			local f19_local1 = function ( f21_arg0 )
				f19_arg0.SelectorOverlay:beginAnimation( 200 )
				f19_arg0.SelectorOverlay:setAlpha( 0.01 )
				f19_arg0.SelectorOverlay:registerEventHandler( "interrupted_keyframe", f19_arg0.clipInterrupted )
				f19_arg0.SelectorOverlay:registerEventHandler( "transition_complete_keyframe", f19_arg0.clipFinished )
			end
			
			f19_arg0.SelectorOverlay:completeAnimation()
			f19_arg0.SelectorOverlay:setAlpha( 0.04 )
			f19_local1( f19_arg0.SelectorOverlay )
			local f19_local2 = function ( f22_arg0 )
				f19_arg0.Lines:beginAnimation( 200 )
				f19_arg0.Lines:setAlpha( 1 )
				f19_arg0.Lines:registerEventHandler( "interrupted_keyframe", f19_arg0.clipInterrupted )
				f19_arg0.Lines:registerEventHandler( "transition_complete_keyframe", f19_arg0.clipFinished )
			end
			
			f19_arg0.Lines:completeAnimation()
			f19_arg0.Lines:setAlpha( 0 )
			f19_local2( f19_arg0.Lines )
			local f19_local3 = function ( f23_arg0 )
				f19_arg0.FocusBorder:beginAnimation( 200 )
				f19_arg0.FocusBorder:setAlpha( 0 )
				f19_arg0.FocusBorder:registerEventHandler( "interrupted_keyframe", f19_arg0.clipInterrupted )
				f19_arg0.FocusBorder:registerEventHandler( "transition_complete_keyframe", f19_arg0.clipFinished )
			end
			
			f19_arg0.FocusBorder:completeAnimation()
			f19_arg0.FocusBorder:setAlpha( 1 )
			f19_local3( f19_arg0.FocusBorder )
			f19_arg0.LockedIcon:completeAnimation()
			f19_arg0.LockedIcon:setAlpha( 0 )
			f19_arg0.clipFinished( f19_arg0.LockedIcon )
			f19_arg0.percentText:completeAnimation()
			f19_arg0.percentText:setAlpha( 0.8 )
			f19_arg0.clipFinished( f19_arg0.percentText )
			local f19_local4 = function ( f24_arg0 )
				f19_arg0.FocusBrackets:beginAnimation( 60 )
				f19_arg0.FocusBrackets:setAlpha( 0 )
				f19_arg0.FocusBrackets:registerEventHandler( "interrupted_keyframe", f19_arg0.clipInterrupted )
				f19_arg0.FocusBrackets:registerEventHandler( "transition_complete_keyframe", f19_arg0.clipFinished )
			end
			
			f19_arg0.FocusBrackets:completeAnimation()
			f19_arg0.FocusBrackets:setAlpha( 1 )
			f19_local4( f19_arg0.FocusBrackets )
		end
	},
	Classified = {
		DefaultClip = function ( f25_arg0, f25_arg1 )
			f25_arg0:__resetProperties()
			f25_arg0:setupElementClipCounter( 4 )
			f25_arg0.MasterCallingCardIcon:completeAnimation()
			f25_arg0.MasterCallingCardIcon:setAlpha( 0 )
			f25_arg0.clipFinished( f25_arg0.MasterCallingCardIcon )
			f25_arg0.DarkOpsClassifiedIcon:completeAnimation()
			f25_arg0.DarkOpsClassifiedIcon:setAlpha( 1 )
			f25_arg0.clipFinished( f25_arg0.DarkOpsClassifiedIcon )
			f25_arg0.LockedIcon:completeAnimation()
			f25_arg0.LockedIcon:setAlpha( 0 )
			f25_arg0.clipFinished( f25_arg0.LockedIcon )
			f25_arg0.FocusBrackets:completeAnimation()
			f25_arg0.FocusBrackets:setAlpha( 0 )
			f25_arg0.clipFinished( f25_arg0.FocusBrackets )
		end,
		Focus = function ( f26_arg0, f26_arg1 )
			f26_arg0:__resetProperties()
			f26_arg0:setupElementClipCounter( 9 )
			f26_arg0.FocusGlow:completeAnimation()
			f26_arg0.FocusGlow:setAlpha( 1 )
			f26_arg0.clipFinished( f26_arg0.FocusGlow )
			f26_arg0.SelectorOverlay:completeAnimation()
			f26_arg0.SelectorOverlay:setAlpha( 0.04 )
			f26_arg0.clipFinished( f26_arg0.SelectorOverlay )
			f26_arg0.Lines:completeAnimation()
			f26_arg0.Lines:setAlpha( 0 )
			f26_arg0.clipFinished( f26_arg0.Lines )
			f26_arg0.FocusBorder:completeAnimation()
			f26_arg0.FocusBorder:setAlpha( 1 )
			f26_arg0.clipFinished( f26_arg0.FocusBorder )
			f26_arg0.MasterCallingCardIcon:completeAnimation()
			f26_arg0.MasterCallingCardIcon:setAlpha( 0 )
			f26_arg0.clipFinished( f26_arg0.MasterCallingCardIcon )
			f26_arg0.DarkOpsClassifiedIcon:completeAnimation()
			f26_arg0.DarkOpsClassifiedIcon:setAlpha( 1 )
			f26_arg0.clipFinished( f26_arg0.DarkOpsClassifiedIcon )
			f26_arg0.LockedIcon:completeAnimation()
			f26_arg0.LockedIcon:setAlpha( 0 )
			f26_arg0.clipFinished( f26_arg0.LockedIcon )
			f26_arg0.EmblemNameNew:completeAnimation()
			f26_arg0.EmblemNameNew:setRGB( 0.96, 0.94, 0.78 )
			f26_arg0.clipFinished( f26_arg0.EmblemNameNew )
			f26_arg0.percentText:completeAnimation()
			f26_arg0.percentText:setRGB( 0.96, 0.94, 0.78 )
			f26_arg0.clipFinished( f26_arg0.percentText )
		end,
		GainFocus = function ( f27_arg0, f27_arg1 )
			f27_arg0:__resetProperties()
			f27_arg0:setupElementClipCounter( 10 )
			local f27_local0 = function ( f28_arg0 )
				f27_arg0.FocusGlow:beginAnimation( 200 )
				f27_arg0.FocusGlow:setAlpha( 1 )
				f27_arg0.FocusGlow:registerEventHandler( "interrupted_keyframe", f27_arg0.clipInterrupted )
				f27_arg0.FocusGlow:registerEventHandler( "transition_complete_keyframe", f27_arg0.clipFinished )
			end
			
			f27_arg0.FocusGlow:completeAnimation()
			f27_arg0.FocusGlow:setAlpha( 0 )
			f27_local0( f27_arg0.FocusGlow )
			local f27_local1 = function ( f29_arg0 )
				f27_arg0.SelectorOverlay:beginAnimation( 200 )
				f27_arg0.SelectorOverlay:setAlpha( 0.04 )
				f27_arg0.SelectorOverlay:registerEventHandler( "interrupted_keyframe", f27_arg0.clipInterrupted )
				f27_arg0.SelectorOverlay:registerEventHandler( "transition_complete_keyframe", f27_arg0.clipFinished )
			end
			
			f27_arg0.SelectorOverlay:completeAnimation()
			f27_arg0.SelectorOverlay:setAlpha( 0.01 )
			f27_local1( f27_arg0.SelectorOverlay )
			local f27_local2 = function ( f30_arg0 )
				f27_arg0.Lines:beginAnimation( 200 )
				f27_arg0.Lines:setAlpha( 0 )
				f27_arg0.Lines:registerEventHandler( "interrupted_keyframe", f27_arg0.clipInterrupted )
				f27_arg0.Lines:registerEventHandler( "transition_complete_keyframe", f27_arg0.clipFinished )
			end
			
			f27_arg0.Lines:completeAnimation()
			f27_arg0.Lines:setAlpha( 1 )
			f27_local2( f27_arg0.Lines )
			local f27_local3 = function ( f31_arg0 )
				f27_arg0.FocusBorder:beginAnimation( 200 )
				f27_arg0.FocusBorder:setAlpha( 1 )
				f27_arg0.FocusBorder:registerEventHandler( "interrupted_keyframe", f27_arg0.clipInterrupted )
				f27_arg0.FocusBorder:registerEventHandler( "transition_complete_keyframe", f27_arg0.clipFinished )
			end
			
			f27_arg0.FocusBorder:completeAnimation()
			f27_arg0.FocusBorder:setAlpha( 0 )
			f27_local3( f27_arg0.FocusBorder )
			f27_arg0.MasterCallingCardIcon:completeAnimation()
			f27_arg0.MasterCallingCardIcon:setAlpha( 0 )
			f27_arg0.clipFinished( f27_arg0.MasterCallingCardIcon )
			f27_arg0.DarkOpsClassifiedIcon:completeAnimation()
			f27_arg0.DarkOpsClassifiedIcon:setAlpha( 1 )
			f27_arg0.clipFinished( f27_arg0.DarkOpsClassifiedIcon )
			f27_arg0.LockedIcon:completeAnimation()
			f27_arg0.LockedIcon:setAlpha( 0 )
			f27_arg0.clipFinished( f27_arg0.LockedIcon )
			f27_arg0.EmblemNameNew:completeAnimation()
			f27_arg0.EmblemNameNew:setRGB( 0.96, 0.94, 0.78 )
			f27_arg0.clipFinished( f27_arg0.EmblemNameNew )
			f27_arg0.percentText:completeAnimation()
			f27_arg0.percentText:setRGB( 0.96, 0.94, 0.78 )
			f27_arg0.clipFinished( f27_arg0.percentText )
			local f27_local4 = function ( f32_arg0 )
				local f32_local0 = function ( f33_arg0 )
					f33_arg0:beginAnimation( 50 )
					f33_arg0:setLeftRight( 0, 1, -10, 10 )
					f33_arg0:setTopBottom( 0, 1, -10, 10 )
					f33_arg0:setAlpha( 1 )
					f33_arg0:registerEventHandler( "transition_complete_keyframe", f27_arg0.clipFinished )
				end
				
				f27_arg0.FocusBrackets:beginAnimation( 100 )
				f27_arg0.FocusBrackets:setLeftRight( 0, 1, -8, 8 )
				f27_arg0.FocusBrackets:setTopBottom( 0, 1, -8, 8 )
				f27_arg0.FocusBrackets:setAlpha( 0.67 )
				f27_arg0.FocusBrackets:registerEventHandler( "interrupted_keyframe", f27_arg0.clipInterrupted )
				f27_arg0.FocusBrackets:registerEventHandler( "transition_complete_keyframe", f32_local0 )
			end
			
			f27_arg0.FocusBrackets:completeAnimation()
			f27_arg0.FocusBrackets:setLeftRight( 0, 1, -40, 40 )
			f27_arg0.FocusBrackets:setTopBottom( 0, 1, -40, 40 )
			f27_arg0.FocusBrackets:setAlpha( 0 )
			f27_local4( f27_arg0.FocusBrackets )
		end,
		LoseFocus = function ( f34_arg0, f34_arg1 )
			f34_arg0:__resetProperties()
			f34_arg0:setupElementClipCounter( 8 )
			local f34_local0 = function ( f35_arg0 )
				f34_arg0.FocusGlow:beginAnimation( 200 )
				f34_arg0.FocusGlow:setAlpha( 0 )
				f34_arg0.FocusGlow:registerEventHandler( "interrupted_keyframe", f34_arg0.clipInterrupted )
				f34_arg0.FocusGlow:registerEventHandler( "transition_complete_keyframe", f34_arg0.clipFinished )
			end
			
			f34_arg0.FocusGlow:completeAnimation()
			f34_arg0.FocusGlow:setAlpha( 1 )
			f34_local0( f34_arg0.FocusGlow )
			local f34_local1 = function ( f36_arg0 )
				f34_arg0.SelectorOverlay:beginAnimation( 200 )
				f34_arg0.SelectorOverlay:setAlpha( 0.01 )
				f34_arg0.SelectorOverlay:registerEventHandler( "interrupted_keyframe", f34_arg0.clipInterrupted )
				f34_arg0.SelectorOverlay:registerEventHandler( "transition_complete_keyframe", f34_arg0.clipFinished )
			end
			
			f34_arg0.SelectorOverlay:completeAnimation()
			f34_arg0.SelectorOverlay:setAlpha( 0.04 )
			f34_local1( f34_arg0.SelectorOverlay )
			local f34_local2 = function ( f37_arg0 )
				f34_arg0.Lines:beginAnimation( 200 )
				f34_arg0.Lines:setAlpha( 1 )
				f34_arg0.Lines:registerEventHandler( "interrupted_keyframe", f34_arg0.clipInterrupted )
				f34_arg0.Lines:registerEventHandler( "transition_complete_keyframe", f34_arg0.clipFinished )
			end
			
			f34_arg0.Lines:completeAnimation()
			f34_arg0.Lines:setAlpha( 0 )
			f34_local2( f34_arg0.Lines )
			local f34_local3 = function ( f38_arg0 )
				f34_arg0.FocusBorder:beginAnimation( 200 )
				f34_arg0.FocusBorder:setAlpha( 0 )
				f34_arg0.FocusBorder:registerEventHandler( "interrupted_keyframe", f34_arg0.clipInterrupted )
				f34_arg0.FocusBorder:registerEventHandler( "transition_complete_keyframe", f34_arg0.clipFinished )
			end
			
			f34_arg0.FocusBorder:completeAnimation()
			f34_arg0.FocusBorder:setAlpha( 1 )
			f34_local3( f34_arg0.FocusBorder )
			f34_arg0.MasterCallingCardIcon:completeAnimation()
			f34_arg0.MasterCallingCardIcon:setAlpha( 0 )
			f34_arg0.clipFinished( f34_arg0.MasterCallingCardIcon )
			f34_arg0.DarkOpsClassifiedIcon:completeAnimation()
			f34_arg0.DarkOpsClassifiedIcon:setAlpha( 1 )
			f34_arg0.clipFinished( f34_arg0.DarkOpsClassifiedIcon )
			f34_arg0.LockedIcon:completeAnimation()
			f34_arg0.LockedIcon:setAlpha( 0 )
			f34_arg0.clipFinished( f34_arg0.LockedIcon )
			local f34_local4 = function ( f39_arg0 )
				f34_arg0.FocusBrackets:beginAnimation( 60 )
				f34_arg0.FocusBrackets:setAlpha( 0 )
				f34_arg0.FocusBrackets:registerEventHandler( "interrupted_keyframe", f34_arg0.clipInterrupted )
				f34_arg0.FocusBrackets:registerEventHandler( "transition_complete_keyframe", f34_arg0.clipFinished )
			end
			
			f34_arg0.FocusBrackets:completeAnimation()
			f34_arg0.FocusBrackets:setAlpha( 1 )
			f34_local4( f34_arg0.FocusBrackets )
		end
	},
	Locked = {
		DefaultClip = function ( f40_arg0, f40_arg1 )
			f40_arg0:__resetProperties()
			f40_arg0:setupElementClipCounter( 6 )
			f40_arg0.SelectorOverlay:completeAnimation()
			f40_arg0.SelectorOverlay:setAlpha( 0.01 )
			f40_arg0.clipFinished( f40_arg0.SelectorOverlay )
			f40_arg0.Lines:completeAnimation()
			f40_arg0.Lines:setAlpha( 0.5 )
			f40_arg0.clipFinished( f40_arg0.Lines )
			f40_arg0.FocusBorder:completeAnimation()
			f40_arg0.FocusBorder:setRGB( ColorSet.T8__OFF__WHITE.r, ColorSet.T8__OFF__WHITE.g, ColorSet.T8__OFF__WHITE.b )
			f40_arg0.FocusBorder:setAlpha( 0 )
			f40_arg0.clipFinished( f40_arg0.FocusBorder )
			f40_arg0.CallingCardIconLockOverlay:completeAnimation()
			f40_arg0.CallingCardIconLockOverlay:setAlpha( 0.95 )
			f40_arg0.clipFinished( f40_arg0.CallingCardIconLockOverlay )
			f40_arg0.LockedIcon:completeAnimation()
			f40_arg0.LockedIcon:setAlpha( 1 )
			f40_arg0.clipFinished( f40_arg0.LockedIcon )
			f40_arg0.FocusBrackets:completeAnimation()
			f40_arg0.FocusBrackets:setAlpha( 0 )
			f40_arg0.clipFinished( f40_arg0.FocusBrackets )
		end,
		Focus = function ( f41_arg0, f41_arg1 )
			f41_arg0:__resetProperties()
			f41_arg0:setupElementClipCounter( 6 )
			f41_arg0.SelectorOverlay:completeAnimation()
			f41_arg0.SelectorOverlay:setAlpha( 0.04 )
			f41_arg0.clipFinished( f41_arg0.SelectorOverlay )
			f41_arg0.FocusBorder:completeAnimation()
			f41_arg0.FocusBorder:setRGB( ColorSet.T8__OFF__WHITE.r, ColorSet.T8__OFF__WHITE.g, ColorSet.T8__OFF__WHITE.b )
			f41_arg0.FocusBorder:setAlpha( 0.25 )
			f41_arg0.clipFinished( f41_arg0.FocusBorder )
			f41_arg0.CallingCardIconLockOverlay:completeAnimation()
			f41_arg0.CallingCardIconLockOverlay:setAlpha( 0.95 )
			f41_arg0.clipFinished( f41_arg0.CallingCardIconLockOverlay )
			f41_arg0.LockedIcon:completeAnimation()
			f41_arg0.LockedIcon:setAlpha( 1 )
			f41_arg0.clipFinished( f41_arg0.LockedIcon )
			f41_arg0.EmblemNameNew:completeAnimation()
			f41_arg0.EmblemNameNew:setRGB( 0.96, 0.94, 0.78 )
			f41_arg0.clipFinished( f41_arg0.EmblemNameNew )
			f41_arg0.percentText:completeAnimation()
			f41_arg0.percentText:setRGB( 0.96, 0.94, 0.78 )
			f41_arg0.clipFinished( f41_arg0.percentText )
		end,
		GainFocus = function ( f42_arg0, f42_arg1 )
			f42_arg0:__resetProperties()
			f42_arg0:setupElementClipCounter( 8 )
			local f42_local0 = function ( f43_arg0 )
				f42_arg0.SelectorOverlay:beginAnimation( 200 )
				f42_arg0.SelectorOverlay:setAlpha( 0.04 )
				f42_arg0.SelectorOverlay:registerEventHandler( "interrupted_keyframe", f42_arg0.clipInterrupted )
				f42_arg0.SelectorOverlay:registerEventHandler( "transition_complete_keyframe", f42_arg0.clipFinished )
			end
			
			f42_arg0.SelectorOverlay:completeAnimation()
			f42_arg0.SelectorOverlay:setAlpha( 0.01 )
			f42_local0( f42_arg0.SelectorOverlay )
			f42_arg0.Lines:completeAnimation()
			f42_arg0.Lines:setAlpha( 0.5 )
			f42_arg0.clipFinished( f42_arg0.Lines )
			local f42_local1 = function ( f44_arg0 )
				f42_arg0.FocusBorder:beginAnimation( 200 )
				f42_arg0.FocusBorder:setAlpha( 0.25 )
				f42_arg0.FocusBorder:registerEventHandler( "interrupted_keyframe", f42_arg0.clipInterrupted )
				f42_arg0.FocusBorder:registerEventHandler( "transition_complete_keyframe", f42_arg0.clipFinished )
			end
			
			f42_arg0.FocusBorder:completeAnimation()
			f42_arg0.FocusBorder:setRGB( ColorSet.T8__OFF__WHITE.r, ColorSet.T8__OFF__WHITE.g, ColorSet.T8__OFF__WHITE.b )
			f42_arg0.FocusBorder:setAlpha( 0 )
			f42_local1( f42_arg0.FocusBorder )
			f42_arg0.CallingCardIconLockOverlay:completeAnimation()
			f42_arg0.CallingCardIconLockOverlay:setAlpha( 0.95 )
			f42_arg0.clipFinished( f42_arg0.CallingCardIconLockOverlay )
			f42_arg0.LockedIcon:completeAnimation()
			f42_arg0.LockedIcon:setAlpha( 1 )
			f42_arg0.clipFinished( f42_arg0.LockedIcon )
			f42_arg0.EmblemNameNew:completeAnimation()
			f42_arg0.EmblemNameNew:setRGB( 0.96, 0.94, 0.78 )
			f42_arg0.clipFinished( f42_arg0.EmblemNameNew )
			f42_arg0.percentText:completeAnimation()
			f42_arg0.percentText:setRGB( 0.96, 0.94, 0.78 )
			f42_arg0.clipFinished( f42_arg0.percentText )
			local f42_local2 = function ( f45_arg0 )
				local f45_local0 = function ( f46_arg0 )
					f46_arg0:beginAnimation( 50 )
					f46_arg0:setLeftRight( 0, 1, -10, 10 )
					f46_arg0:setTopBottom( 0, 1, -10, 10 )
					f46_arg0:setAlpha( 1 )
					f46_arg0:registerEventHandler( "transition_complete_keyframe", f42_arg0.clipFinished )
				end
				
				f42_arg0.FocusBrackets:beginAnimation( 100 )
				f42_arg0.FocusBrackets:setLeftRight( 0, 1, -8, 8 )
				f42_arg0.FocusBrackets:setTopBottom( 0, 1, -8, 8 )
				f42_arg0.FocusBrackets:setAlpha( 0.67 )
				f42_arg0.FocusBrackets:registerEventHandler( "interrupted_keyframe", f42_arg0.clipInterrupted )
				f42_arg0.FocusBrackets:registerEventHandler( "transition_complete_keyframe", f45_local0 )
			end
			
			f42_arg0.FocusBrackets:completeAnimation()
			f42_arg0.FocusBrackets:setLeftRight( 0, 1, -40, 40 )
			f42_arg0.FocusBrackets:setTopBottom( 0, 1, -40, 40 )
			f42_arg0.FocusBrackets:setAlpha( 0 )
			f42_local2( f42_arg0.FocusBrackets )
		end,
		LoseFocus = function ( f47_arg0, f47_arg1 )
			f47_arg0:__resetProperties()
			f47_arg0:setupElementClipCounter( 6 )
			local f47_local0 = function ( f48_arg0 )
				f47_arg0.SelectorOverlay:beginAnimation( 200 )
				f47_arg0.SelectorOverlay:setAlpha( 0.01 )
				f47_arg0.SelectorOverlay:registerEventHandler( "interrupted_keyframe", f47_arg0.clipInterrupted )
				f47_arg0.SelectorOverlay:registerEventHandler( "transition_complete_keyframe", f47_arg0.clipFinished )
			end
			
			f47_arg0.SelectorOverlay:completeAnimation()
			f47_arg0.SelectorOverlay:setAlpha( 0.04 )
			f47_local0( f47_arg0.SelectorOverlay )
			f47_arg0.Lines:completeAnimation()
			f47_arg0.Lines:setAlpha( 0.5 )
			f47_arg0.clipFinished( f47_arg0.Lines )
			local f47_local1 = function ( f49_arg0 )
				f47_arg0.FocusBorder:beginAnimation( 200 )
				f47_arg0.FocusBorder:setAlpha( 0 )
				f47_arg0.FocusBorder:registerEventHandler( "interrupted_keyframe", f47_arg0.clipInterrupted )
				f47_arg0.FocusBorder:registerEventHandler( "transition_complete_keyframe", f47_arg0.clipFinished )
			end
			
			f47_arg0.FocusBorder:completeAnimation()
			f47_arg0.FocusBorder:setRGB( 0.96, 0.94, 0.78 )
			f47_arg0.FocusBorder:setAlpha( 0.25 )
			f47_local1( f47_arg0.FocusBorder )
			f47_arg0.CallingCardIconLockOverlay:completeAnimation()
			f47_arg0.CallingCardIconLockOverlay:setAlpha( 0.95 )
			f47_arg0.clipFinished( f47_arg0.CallingCardIconLockOverlay )
			f47_arg0.LockedIcon:completeAnimation()
			f47_arg0.LockedIcon:setAlpha( 1 )
			f47_arg0.clipFinished( f47_arg0.LockedIcon )
			local f47_local2 = function ( f50_arg0 )
				f47_arg0.FocusBrackets:beginAnimation( 60 )
				f47_arg0.FocusBrackets:setAlpha( 0 )
				f47_arg0.FocusBrackets:registerEventHandler( "interrupted_keyframe", f47_arg0.clipInterrupted )
				f47_arg0.FocusBrackets:registerEventHandler( "transition_complete_keyframe", f47_arg0.clipFinished )
			end
			
			f47_arg0.FocusBrackets:completeAnimation()
			f47_arg0.FocusBrackets:setAlpha( 1 )
			f47_local2( f47_arg0.FocusBrackets )
		end
	},
	Complete = {
		DefaultClip = function ( f51_arg0, f51_arg1 )
			f51_arg0:__resetProperties()
			f51_arg0:setupElementClipCounter( 7 )
			f51_arg0.LockedIcon:completeAnimation()
			f51_arg0.LockedIcon:setAlpha( 0 )
			f51_arg0.clipFinished( f51_arg0.LockedIcon )
			f51_arg0.TrialWidget:completeAnimation()
			f51_arg0.TrialWidget:setAlpha( 1 )
			f51_arg0.clipFinished( f51_arg0.TrialWidget )
			f51_arg0.ProgressBar:completeAnimation()
			f51_arg0.ProgressBar:setAlpha( 0 )
			f51_arg0.clipFinished( f51_arg0.ProgressBar )
			f51_arg0.EmblemNameNew:completeAnimation()
			f51_arg0.EmblemNameNew:setRGB( ColorSet.T8_PC_CHAT_PARTY.r, ColorSet.T8_PC_CHAT_PARTY.g, ColorSet.T8_PC_CHAT_PARTY.b )
			f51_arg0.clipFinished( f51_arg0.EmblemNameNew )
			f51_arg0.percentText:completeAnimation()
			f51_arg0.percentText:setRGB( ColorSet.T8_PC_CHAT_PARTY.r, ColorSet.T8_PC_CHAT_PARTY.g, ColorSet.T8_PC_CHAT_PARTY.b )
			f51_arg0.clipFinished( f51_arg0.percentText )
			f51_arg0.FocusBrackets:completeAnimation()
			f51_arg0.FocusBrackets:setAlpha( 0 )
			f51_arg0.clipFinished( f51_arg0.FocusBrackets )
			f51_arg0.CompleteIcon:completeAnimation()
			f51_arg0.CompleteIcon:setAlpha( 1 )
			f51_arg0.clipFinished( f51_arg0.CompleteIcon )
		end,
		Focus = function ( f52_arg0, f52_arg1 )
			f52_arg0:__resetProperties()
			f52_arg0:setupElementClipCounter( 10 )
			f52_arg0.FocusGlow:completeAnimation()
			f52_arg0.FocusGlow:setAlpha( 1 )
			f52_arg0.clipFinished( f52_arg0.FocusGlow )
			f52_arg0.SelectorOverlay:completeAnimation()
			f52_arg0.SelectorOverlay:setAlpha( 0.04 )
			f52_arg0.clipFinished( f52_arg0.SelectorOverlay )
			f52_arg0.Lines:completeAnimation()
			f52_arg0.Lines:setAlpha( 0 )
			f52_arg0.clipFinished( f52_arg0.Lines )
			f52_arg0.FocusBorder:completeAnimation()
			f52_arg0.FocusBorder:setAlpha( 1 )
			f52_arg0.clipFinished( f52_arg0.FocusBorder )
			f52_arg0.LockedIcon:completeAnimation()
			f52_arg0.LockedIcon:setAlpha( 0 )
			f52_arg0.clipFinished( f52_arg0.LockedIcon )
			f52_arg0.TrialWidget:completeAnimation()
			f52_arg0.TrialWidget:setAlpha( 1 )
			f52_arg0.clipFinished( f52_arg0.TrialWidget )
			f52_arg0.ProgressBar:completeAnimation()
			f52_arg0.ProgressBar:setAlpha( 0 )
			f52_arg0.clipFinished( f52_arg0.ProgressBar )
			f52_arg0.EmblemNameNew:completeAnimation()
			f52_arg0.EmblemNameNew:setRGB( ColorSet.T8_PC_CHAT_PARTY.r, ColorSet.T8_PC_CHAT_PARTY.g, ColorSet.T8_PC_CHAT_PARTY.b )
			f52_arg0.clipFinished( f52_arg0.EmblemNameNew )
			f52_arg0.percentText:completeAnimation()
			f52_arg0.percentText:setRGB( ColorSet.T8_PC_CHAT_PARTY.r, ColorSet.T8_PC_CHAT_PARTY.g, ColorSet.T8_PC_CHAT_PARTY.b )
			f52_arg0.percentText:setAlpha( 0.8 )
			f52_arg0.clipFinished( f52_arg0.percentText )
			f52_arg0.CompleteIcon:completeAnimation()
			f52_arg0.CompleteIcon:setAlpha( 1 )
			f52_arg0.clipFinished( f52_arg0.CompleteIcon )
		end,
		GainFocus = function ( f53_arg0, f53_arg1 )
			f53_arg0:__resetProperties()
			f53_arg0:setupElementClipCounter( 11 )
			local f53_local0 = function ( f54_arg0 )
				f53_arg0.FocusGlow:beginAnimation( 200 )
				f53_arg0.FocusGlow:setAlpha( 1 )
				f53_arg0.FocusGlow:registerEventHandler( "interrupted_keyframe", f53_arg0.clipInterrupted )
				f53_arg0.FocusGlow:registerEventHandler( "transition_complete_keyframe", f53_arg0.clipFinished )
			end
			
			f53_arg0.FocusGlow:completeAnimation()
			f53_arg0.FocusGlow:setAlpha( 0 )
			f53_local0( f53_arg0.FocusGlow )
			local f53_local1 = function ( f55_arg0 )
				f53_arg0.SelectorOverlay:beginAnimation( 200 )
				f53_arg0.SelectorOverlay:setAlpha( 0.04 )
				f53_arg0.SelectorOverlay:registerEventHandler( "interrupted_keyframe", f53_arg0.clipInterrupted )
				f53_arg0.SelectorOverlay:registerEventHandler( "transition_complete_keyframe", f53_arg0.clipFinished )
			end
			
			f53_arg0.SelectorOverlay:completeAnimation()
			f53_arg0.SelectorOverlay:setAlpha( 0.01 )
			f53_local1( f53_arg0.SelectorOverlay )
			local f53_local2 = function ( f56_arg0 )
				f53_arg0.Lines:beginAnimation( 200 )
				f53_arg0.Lines:setAlpha( 0 )
				f53_arg0.Lines:registerEventHandler( "interrupted_keyframe", f53_arg0.clipInterrupted )
				f53_arg0.Lines:registerEventHandler( "transition_complete_keyframe", f53_arg0.clipFinished )
			end
			
			f53_arg0.Lines:completeAnimation()
			f53_arg0.Lines:setAlpha( 1 )
			f53_local2( f53_arg0.Lines )
			local f53_local3 = function ( f57_arg0 )
				f53_arg0.FocusBorder:beginAnimation( 200 )
				f53_arg0.FocusBorder:setAlpha( 1 )
				f53_arg0.FocusBorder:registerEventHandler( "interrupted_keyframe", f53_arg0.clipInterrupted )
				f53_arg0.FocusBorder:registerEventHandler( "transition_complete_keyframe", f53_arg0.clipFinished )
			end
			
			f53_arg0.FocusBorder:completeAnimation()
			f53_arg0.FocusBorder:setAlpha( 0 )
			f53_local3( f53_arg0.FocusBorder )
			f53_arg0.LockedIcon:completeAnimation()
			f53_arg0.LockedIcon:setAlpha( 0 )
			f53_arg0.clipFinished( f53_arg0.LockedIcon )
			f53_arg0.TrialWidget:completeAnimation()
			f53_arg0.TrialWidget:setAlpha( 1 )
			f53_arg0.clipFinished( f53_arg0.TrialWidget )
			f53_arg0.ProgressBar:completeAnimation()
			f53_arg0.ProgressBar:setAlpha( 0 )
			f53_arg0.clipFinished( f53_arg0.ProgressBar )
			f53_arg0.EmblemNameNew:completeAnimation()
			f53_arg0.EmblemNameNew:setRGB( ColorSet.T8_PC_CHAT_PARTY.r, ColorSet.T8_PC_CHAT_PARTY.g, ColorSet.T8_PC_CHAT_PARTY.b )
			f53_arg0.clipFinished( f53_arg0.EmblemNameNew )
			f53_arg0.percentText:completeAnimation()
			f53_arg0.percentText:setRGB( ColorSet.T8_PC_CHAT_PARTY.r, ColorSet.T8_PC_CHAT_PARTY.g, ColorSet.T8_PC_CHAT_PARTY.b )
			f53_arg0.percentText:setAlpha( 0.8 )
			f53_arg0.clipFinished( f53_arg0.percentText )
			local f53_local4 = function ( f58_arg0 )
				local f58_local0 = function ( f59_arg0 )
					local f59_local0 = function ( f60_arg0 )
						f60_arg0:beginAnimation( 49 )
						f60_arg0:setAlpha( 0 )
						f60_arg0:registerEventHandler( "transition_complete_keyframe", f53_arg0.clipFinished )
					end
					
					f59_arg0:beginAnimation( 50 )
					f59_arg0:setLeftRight( 0, 1, -10, 10 )
					f59_arg0:setTopBottom( 0, 1, -10, 10 )
					f59_arg0:setAlpha( 1 )
					f59_arg0:registerEventHandler( "transition_complete_keyframe", f59_local0 )
				end
				
				f53_arg0.FocusBrackets:beginAnimation( 100 )
				f53_arg0.FocusBrackets:setLeftRight( 0, 1, -8, 8 )
				f53_arg0.FocusBrackets:setTopBottom( 0, 1, -8, 8 )
				f53_arg0.FocusBrackets:setAlpha( 0.67 )
				f53_arg0.FocusBrackets:registerEventHandler( "interrupted_keyframe", f53_arg0.clipInterrupted )
				f53_arg0.FocusBrackets:registerEventHandler( "transition_complete_keyframe", f58_local0 )
			end
			
			f53_arg0.FocusBrackets:completeAnimation()
			f53_arg0.FocusBrackets:setLeftRight( 0, 1, -40, 40 )
			f53_arg0.FocusBrackets:setTopBottom( 0, 1, -40, 40 )
			f53_arg0.FocusBrackets:setAlpha( 0 )
			f53_local4( f53_arg0.FocusBrackets )
			f53_arg0.CompleteIcon:completeAnimation()
			f53_arg0.CompleteIcon:setAlpha( 1 )
			f53_arg0.clipFinished( f53_arg0.CompleteIcon )
		end,
		LoseFocus = function ( f61_arg0, f61_arg1 )
			f61_arg0:__resetProperties()
			f61_arg0:setupElementClipCounter( 11 )
			local f61_local0 = function ( f62_arg0 )
				f61_arg0.FocusGlow:beginAnimation( 200 )
				f61_arg0.FocusGlow:setAlpha( 0 )
				f61_arg0.FocusGlow:registerEventHandler( "interrupted_keyframe", f61_arg0.clipInterrupted )
				f61_arg0.FocusGlow:registerEventHandler( "transition_complete_keyframe", f61_arg0.clipFinished )
			end
			
			f61_arg0.FocusGlow:completeAnimation()
			f61_arg0.FocusGlow:setAlpha( 1 )
			f61_local0( f61_arg0.FocusGlow )
			local f61_local1 = function ( f63_arg0 )
				f61_arg0.SelectorOverlay:beginAnimation( 200 )
				f61_arg0.SelectorOverlay:setAlpha( 0.01 )
				f61_arg0.SelectorOverlay:registerEventHandler( "interrupted_keyframe", f61_arg0.clipInterrupted )
				f61_arg0.SelectorOverlay:registerEventHandler( "transition_complete_keyframe", f61_arg0.clipFinished )
			end
			
			f61_arg0.SelectorOverlay:completeAnimation()
			f61_arg0.SelectorOverlay:setAlpha( 0.04 )
			f61_local1( f61_arg0.SelectorOverlay )
			local f61_local2 = function ( f64_arg0 )
				f61_arg0.Lines:beginAnimation( 200 )
				f61_arg0.Lines:setAlpha( 1 )
				f61_arg0.Lines:registerEventHandler( "interrupted_keyframe", f61_arg0.clipInterrupted )
				f61_arg0.Lines:registerEventHandler( "transition_complete_keyframe", f61_arg0.clipFinished )
			end
			
			f61_arg0.Lines:completeAnimation()
			f61_arg0.Lines:setAlpha( 0 )
			f61_local2( f61_arg0.Lines )
			local f61_local3 = function ( f65_arg0 )
				f61_arg0.FocusBorder:beginAnimation( 200 )
				f61_arg0.FocusBorder:setAlpha( 0 )
				f61_arg0.FocusBorder:registerEventHandler( "interrupted_keyframe", f61_arg0.clipInterrupted )
				f61_arg0.FocusBorder:registerEventHandler( "transition_complete_keyframe", f61_arg0.clipFinished )
			end
			
			f61_arg0.FocusBorder:completeAnimation()
			f61_arg0.FocusBorder:setAlpha( 1 )
			f61_local3( f61_arg0.FocusBorder )
			f61_arg0.LockedIcon:completeAnimation()
			f61_arg0.LockedIcon:setAlpha( 0 )
			f61_arg0.clipFinished( f61_arg0.LockedIcon )
			f61_arg0.TrialWidget:completeAnimation()
			f61_arg0.TrialWidget:setAlpha( 1 )
			f61_arg0.clipFinished( f61_arg0.TrialWidget )
			f61_arg0.ProgressBar:completeAnimation()
			f61_arg0.ProgressBar:setAlpha( 0 )
			f61_arg0.clipFinished( f61_arg0.ProgressBar )
			f61_arg0.EmblemNameNew:completeAnimation()
			f61_arg0.EmblemNameNew:setRGB( ColorSet.T8_PC_CHAT_PARTY.r, ColorSet.T8_PC_CHAT_PARTY.g, ColorSet.T8_PC_CHAT_PARTY.b )
			f61_arg0.clipFinished( f61_arg0.EmblemNameNew )
			f61_arg0.percentText:completeAnimation()
			f61_arg0.percentText:setRGB( ColorSet.T8_PC_CHAT_PARTY.r, ColorSet.T8_PC_CHAT_PARTY.g, ColorSet.T8_PC_CHAT_PARTY.b )
			f61_arg0.percentText:setAlpha( 0.8 )
			f61_arg0.clipFinished( f61_arg0.percentText )
			local f61_local4 = function ( f66_arg0 )
				f61_arg0.FocusBrackets:beginAnimation( 60 )
				f61_arg0.FocusBrackets:setAlpha( 0 )
				f61_arg0.FocusBrackets:registerEventHandler( "interrupted_keyframe", f61_arg0.clipInterrupted )
				f61_arg0.FocusBrackets:registerEventHandler( "transition_complete_keyframe", f61_arg0.clipFinished )
			end
			
			f61_arg0.FocusBrackets:completeAnimation()
			f61_arg0.FocusBrackets:setAlpha( 1 )
			f61_local4( f61_arg0.FocusBrackets )
			f61_arg0.CompleteIcon:completeAnimation()
			f61_arg0.CompleteIcon:setAlpha( 1 )
			f61_arg0.clipFinished( f61_arg0.CompleteIcon )
		end
	}
}
CoD.Challenges_MasterCallingCardWidget_Internal.__onClose = function ( f67_arg0 )
	f67_arg0.Lines:close()
	f67_arg0.MasterCallingCardIcon:close()
	f67_arg0.LockedIcon:close()
	f67_arg0.TrialWidget:close()
	f67_arg0.DotTiledBacking:close()
	f67_arg0.ProgressBar:close()
	f67_arg0.EmblemSubtitle:close()
	f67_arg0.EmblemName:close()
	f67_arg0.EmblemNameNew:close()
	f67_arg0.percentText:close()
	f67_arg0.FocusBrackets:close()
end

