require( "ui/uieditor/widgets/cac/cac_lock" )
require( "ui/uieditor/widgets/callingcards/callingcards_framewidget" )
require( "ui/uieditor/widgets/commonbuttonoutline" )
require( "ui/uieditor/widgets/startmenu/startmenu_identity_subtitle" )
require( "ui/uieditor/widgets/store/storecommontextbacking" )

CoD.Challenges_Category_ButtonInternal = InheritFrom( LUI.UIElement )
CoD.Challenges_Category_ButtonInternal.__defaultWidth = 1000
CoD.Challenges_Category_ButtonInternal.__defaultHeight = 100
CoD.Challenges_Category_ButtonInternal.new = function ( f1_arg0, f1_arg1, f1_arg2, f1_arg3, f1_arg4, f1_arg5, f1_arg6, f1_arg7, f1_arg8, f1_arg9 )
	local self = LUI.UIElement.new( f1_arg2, f1_arg3, f1_arg4, f1_arg5, f1_arg6, f1_arg7, f1_arg8, f1_arg9 )
	self:setClass( CoD.Challenges_Category_ButtonInternal )
	self.id = "Challenges_Category_ButtonInternal"
	self.soundSet = "default"
	self.onlyChildrenFocusable = true
	self.anyChildUsesUpdateState = true
	f1_arg0:addElementToPendingUpdateStateList( self )
	
	local NoiseTiledBacking = LUI.UIImage.new( 0, 1, 0, 0, 0, 1, 0, 0 )
	NoiseTiledBacking:setAlpha( 0.8 )
	NoiseTiledBacking:setImage( RegisterImage( "uie_ui_menu_specialist_hub_repeat_bg" ) )
	NoiseTiledBacking:setMaterial( LUI.UIImage.GetCachedMaterial( 0x6CBE95C250C6D15 ) )
	NoiseTiledBacking:setShaderVector( 0, 0, 0, 0, 0 )
	NoiseTiledBacking:setupNineSliceShader( 196, 88 )
	self:addElement( NoiseTiledBacking )
	self.NoiseTiledBacking = NoiseTiledBacking
	
	local SelectorOverlay = LUI.UIImage.new( 0, 1, 0, 0, 0, 1, 0, 0 )
	SelectorOverlay:setAlpha( 0.01 )
	self:addElement( SelectorOverlay )
	self.SelectorOverlay = SelectorOverlay
	
	local MasteryImage = CoD.CallingCards_FrameWidget.new( f1_arg0, f1_arg1, 1, 1, -365, -5, 0, 0, 5, 95 )
	MasteryImage:linkToElementModel( self, nil, false, function ( model )
		MasteryImage:setModel( model, f1_arg1 )
	end )
	self:addElement( MasteryImage )
	self.MasteryImage = MasteryImage
	
	local FillBarDotTiledBacking = CoD.StoreCommonTextBacking.new( f1_arg0, f1_arg1, 0, 0.62, 7, 7, 0.05, 0.95, 0, 0 )
	FillBarDotTiledBacking:setAlpha( 0.15 )
	self:addElement( FillBarDotTiledBacking )
	self.FillBarDotTiledBacking = FillBarDotTiledBacking
	
	local FillBarBorder = LUI.UIImage.new( 0, 0.62, 5, 9, 0.05, 0.95, 0, 0 )
	FillBarBorder:setAlpha( 0.1 )
	FillBarBorder:setImage( RegisterImage( "uie_ui_menu_store_common_frame" ) )
	FillBarBorder:setMaterial( LUI.UIImage.GetCachedMaterial( "uie_nineslice_add" ) )
	FillBarBorder:setShaderVector( 0, 0, 0, 0, 0 )
	FillBarBorder:setupNineSliceShader( 12, 12 )
	self:addElement( FillBarBorder )
	self.FillBarBorder = FillBarBorder
	
	local FillBar = LUI.UIImage.new( -0, 0.62, 8, 6, 0.05, 0.95, 2, -2 )
	FillBar:setRGB( 1, 0.36, 0 )
	FillBar:setAlpha( 0.15 )
	FillBar:setMaterial( LUI.UIImage.GetCachedMaterial( "uie_wipe_normal" ) )
	FillBar:setShaderVector( 1, 0, 0, 0, 0 )
	FillBar:setShaderVector( 2, 1, 0, 0, 0 )
	FillBar:setShaderVector( 3, 0, 0, 0, 0 )
	FillBar:setShaderVector( 4, 0, 0, 0, 0 )
	FillBar:linkToElementModel( self, "percentComplete", true, function ( model )
		local f3_local0 = model:get()
		if f3_local0 ~= nil then
			FillBar:setShaderVector( 0, CoD.GetVectorComponentFromString( f3_local0, 1 ), CoD.GetVectorComponentFromString( f3_local0, 2 ), CoD.GetVectorComponentFromString( f3_local0, 3 ), CoD.GetVectorComponentFromString( f3_local0, 4 ) )
		end
	end )
	self:addElement( FillBar )
	self.FillBar = FillBar
	
	local StartMenuIdentitySubTitle0 = CoD.StartMenu_Identity_SubTitle.new( f1_arg0, f1_arg1, 0, 0, 152, 284, 1, 1, -70.5, -30.5 )
	StartMenuIdentitySubTitle0.SubtitleText:setText( "" )
	self:addElement( StartMenuIdentitySubTitle0 )
	self.StartMenuIdentitySubTitle0 = StartMenuIdentitySubTitle0
	
	local LockIconBacking = LUI.UIImage.new( 0.73, 0.73, 61, 101, 0, 0, 30.5, 70.5 )
	LockIconBacking:setRGB( 0, 0, 0 )
	LockIconBacking:setAlpha( 0.85 )
	LockIconBacking:setMaterial( LUI.UIImage.GetCachedMaterial( "uie_feather_edges" ) )
	LockIconBacking:setShaderVector( 0, 0.02, 0.02, 0.02, 0.02 )
	self:addElement( LockIconBacking )
	self.LockIconBacking = LockIconBacking
	
	local LockIconBacingTexture = LUI.UIImage.new( 0.74, 0.74, 57, 97, 0, 0, 30.5, 70.5 )
	LockIconBacingTexture:setAlpha( 0.15 )
	LockIconBacingTexture:setImage( RegisterImage( 0x311E811A3183347 ) )
	LockIconBacingTexture:setMaterial( LUI.UIImage.GetCachedMaterial( 0x6CBE95C250C6D15 ) )
	LockIconBacingTexture:setShaderVector( 0, 0, 0, 0, 0 )
	LockIconBacingTexture:setupNineSliceShader( 128, 128 )
	self:addElement( LockIconBacingTexture )
	self.LockIconBacingTexture = LockIconBacingTexture
	
	local lockedIcon = CoD.cac_lock.new( f1_arg0, f1_arg1, 0.5, 0.5, 297, 333, 0.5, 0.5, -18, 18 )
	self:addElement( lockedIcon )
	self.lockedIcon = lockedIcon
	
	local percentText = LUI.UIText.new( 0.5, 0.5, 19, 109, 0.5, 0.5, -11.5, 15.5 )
	percentText:setRGB( ColorSet.T8__OFF__WHITE.r, ColorSet.T8__OFF__WHITE.g, ColorSet.T8__OFF__WHITE.b )
	percentText:setAlpha( 0.8 )
	percentText:setTTF( "dinnext_regular" )
	percentText:setAlignment( Enum.LUIAlignment[0x830CFD395E6AA0A] )
	percentText:setAlignment( Enum.LUIAlignment[0xF41D595A2B0EDF3] )
	percentText:linkToElementModel( self, "percentComplete", true, function ( model )
		local f4_local0 = model:get()
		if f4_local0 ~= nil then
			percentText:setText( NumberAsPercentRounded( f4_local0 ) )
		end
	end )
	self:addElement( percentText )
	self.percentText = percentText
	
	local Name = LUI.UIText.new( 0, 0, 26.5, 326.5, 0.5, 0.5, -13.5, 13.5 )
	Name:setRGB( ColorSet.T8__OFF__WHITE.r, ColorSet.T8__OFF__WHITE.g, ColorSet.T8__OFF__WHITE.b )
	Name:setText( Engine[0xF9F1239CFD921FE]( 0x5662A3E5DC08B87 ) )
	Name:setTTF( "ttmussels_regular" )
	Name:setLetterSpacing( 3 )
	Name:setAlignment( Enum.LUIAlignment[0x58C8A85F2048829] )
	self:addElement( Name )
	self.Name = Name
	
	local UnlockText = LUI.UIText.new( 0, 0, 26.5, 326.5, 0.5, 0.5, 19.5, 37.5 )
	UnlockText:setRGB( ColorSet.T8__OFF__WHITE.r, ColorSet.T8__OFF__WHITE.g, ColorSet.T8__OFF__WHITE.b )
	UnlockText:setAlpha( 0 )
	UnlockText:setTTF( "ttmussels_regular" )
	UnlockText:setLetterSpacing( 3 )
	UnlockText:setAlignment( Enum.LUIAlignment[0x58C8A85F2048829] )
	UnlockText:linkToElementModel( self, "categoryLockedText", true, function ( model )
		local f5_local0 = model:get()
		if f5_local0 ~= nil then
			UnlockText:setText( f5_local0 )
		end
	end )
	self:addElement( UnlockText )
	self.UnlockText = UnlockText
	
	local CompleteImage = LUI.UIImage.new( 0, 0, 470, 530, 0.5, 0.5, -30, 30 )
	CompleteImage:setAlpha( 0 )
	CompleteImage:setImage( RegisterImage( 0x98D02A0405ED520 ) )
	self:addElement( CompleteImage )
	self.CompleteImage = CompleteImage
	
	local ButtonOutline = CoD.CommonButtonOutline.new( f1_arg0, f1_arg1, 0, 1, 0, 0, 0, 1, 0, 0 )
	self:addElement( ButtonOutline )
	self.ButtonOutline = ButtonOutline
	
	MasteryImage.id = "MasteryImage"
	ButtonOutline.id = "ButtonOutline"
	self.__defaultFocus = ButtonOutline
	LUI.OverrideFunction_CallOriginalSecond( self, "close", self.__onClose )
	
	if PostLoadFunc then
		PostLoadFunc( self, f1_arg1, f1_arg0 )
	end
	
	return self
end

CoD.Challenges_Category_ButtonInternal.__resetProperties = function ( f6_arg0 )
	f6_arg0.SelectorOverlay:completeAnimation()
	f6_arg0.Name:completeAnimation()
	f6_arg0.percentText:completeAnimation()
	f6_arg0.CompleteImage:completeAnimation()
	f6_arg0.lockedIcon:completeAnimation()
	f6_arg0.FillBar:completeAnimation()
	f6_arg0.LockIconBacingTexture:completeAnimation()
	f6_arg0.LockIconBacking:completeAnimation()
	f6_arg0.MasteryImage:completeAnimation()
	f6_arg0.UnlockText:completeAnimation()
	f6_arg0.SelectorOverlay:setAlpha( 0.01 )
	f6_arg0.Name:setRGB( ColorSet.T8__OFF__WHITE.r, ColorSet.T8__OFF__WHITE.g, ColorSet.T8__OFF__WHITE.b )
	f6_arg0.percentText:setRGB( ColorSet.T8__OFF__WHITE.r, ColorSet.T8__OFF__WHITE.g, ColorSet.T8__OFF__WHITE.b )
	f6_arg0.percentText:setAlpha( 0.8 )
	f6_arg0.CompleteImage:setAlpha( 0 )
	f6_arg0.lockedIcon:setAlpha( 1 )
	f6_arg0.FillBar:setAlpha( 0.15 )
	f6_arg0.LockIconBacingTexture:setAlpha( 0.15 )
	f6_arg0.LockIconBacking:setAlpha( 0.85 )
	f6_arg0.MasteryImage:setAlpha( 1 )
	f6_arg0.UnlockText:setRGB( ColorSet.T8__OFF__WHITE.r, ColorSet.T8__OFF__WHITE.g, ColorSet.T8__OFF__WHITE.b )
	f6_arg0.UnlockText:setAlpha( 0 )
end

CoD.Challenges_Category_ButtonInternal.__clipsPerState = {
	DefaultState = {
		DefaultClip = function ( f7_arg0, f7_arg1 )
			f7_arg0:__resetProperties()
			f7_arg0:setupElementClipCounter( 0 )
		end,
		ChildFocus = function ( f8_arg0, f8_arg1 )
			f8_arg0:__resetProperties()
			f8_arg0:setupElementClipCounter( 3 )
			f8_arg0.SelectorOverlay:completeAnimation()
			f8_arg0.SelectorOverlay:setAlpha( 0.04 )
			f8_arg0.clipFinished( f8_arg0.SelectorOverlay )
			f8_arg0.percentText:completeAnimation()
			f8_arg0.percentText:setRGB( 0.96, 0.94, 0.78 )
			f8_arg0.clipFinished( f8_arg0.percentText )
			f8_arg0.Name:completeAnimation()
			f8_arg0.Name:setRGB( 0.96, 0.94, 0.78 )
			f8_arg0.clipFinished( f8_arg0.Name )
		end,
		GainChildFocus = function ( f9_arg0, f9_arg1 )
			f9_arg0:__resetProperties()
			f9_arg0:setupElementClipCounter( 3 )
			local f9_local0 = function ( f10_arg0 )
				f9_arg0.SelectorOverlay:beginAnimation( 200 )
				f9_arg0.SelectorOverlay:setAlpha( 0.04 )
				f9_arg0.SelectorOverlay:registerEventHandler( "interrupted_keyframe", f9_arg0.clipInterrupted )
				f9_arg0.SelectorOverlay:registerEventHandler( "transition_complete_keyframe", f9_arg0.clipFinished )
			end
			
			f9_arg0.SelectorOverlay:completeAnimation()
			f9_arg0.SelectorOverlay:setAlpha( 0.01 )
			f9_local0( f9_arg0.SelectorOverlay )
			f9_arg0.percentText:completeAnimation()
			f9_arg0.percentText:setRGB( 0.96, 0.94, 0.78 )
			f9_arg0.clipFinished( f9_arg0.percentText )
			f9_arg0.Name:completeAnimation()
			f9_arg0.Name:setRGB( 0.96, 0.94, 0.78 )
			f9_arg0.clipFinished( f9_arg0.Name )
		end,
		LoseChildFocus = function ( f11_arg0, f11_arg1 )
			f11_arg0:__resetProperties()
			f11_arg0:setupElementClipCounter( 1 )
			local f11_local0 = function ( f12_arg0 )
				f11_arg0.SelectorOverlay:beginAnimation( 200 )
				f11_arg0.SelectorOverlay:setAlpha( 0.01 )
				f11_arg0.SelectorOverlay:registerEventHandler( "interrupted_keyframe", f11_arg0.clipInterrupted )
				f11_arg0.SelectorOverlay:registerEventHandler( "transition_complete_keyframe", f11_arg0.clipFinished )
			end
			
			f11_arg0.SelectorOverlay:completeAnimation()
			f11_arg0.SelectorOverlay:setAlpha( 0.04 )
			f11_local0( f11_arg0.SelectorOverlay )
		end
	},
	Complete = {
		DefaultClip = function ( f13_arg0, f13_arg1 )
			f13_arg0:__resetProperties()
			f13_arg0:setupElementClipCounter( 7 )
			f13_arg0.FillBar:completeAnimation()
			f13_arg0.FillBar:setAlpha( 0 )
			f13_arg0.clipFinished( f13_arg0.FillBar )
			f13_arg0.LockIconBacking:completeAnimation()
			f13_arg0.LockIconBacking:setAlpha( 0 )
			f13_arg0.clipFinished( f13_arg0.LockIconBacking )
			f13_arg0.LockIconBacingTexture:completeAnimation()
			f13_arg0.LockIconBacingTexture:setAlpha( 0 )
			f13_arg0.clipFinished( f13_arg0.LockIconBacingTexture )
			f13_arg0.lockedIcon:completeAnimation()
			f13_arg0.lockedIcon:setAlpha( 0 )
			f13_arg0.clipFinished( f13_arg0.lockedIcon )
			f13_arg0.percentText:completeAnimation()
			f13_arg0.percentText:setRGB( ColorSet.T8_PC_CHAT_PARTY.r, ColorSet.T8_PC_CHAT_PARTY.g, ColorSet.T8_PC_CHAT_PARTY.b )
			f13_arg0.clipFinished( f13_arg0.percentText )
			f13_arg0.Name:completeAnimation()
			f13_arg0.Name:setRGB( ColorSet.T8_PC_CHAT_PARTY.r, ColorSet.T8_PC_CHAT_PARTY.g, ColorSet.T8_PC_CHAT_PARTY.b )
			f13_arg0.clipFinished( f13_arg0.Name )
			f13_arg0.CompleteImage:completeAnimation()
			f13_arg0.CompleteImage:setAlpha( 1 )
			f13_arg0.clipFinished( f13_arg0.CompleteImage )
		end,
		ChildFocus = function ( f14_arg0, f14_arg1 )
			f14_arg0:__resetProperties()
			f14_arg0:setupElementClipCounter( 8 )
			f14_arg0.SelectorOverlay:completeAnimation()
			f14_arg0.SelectorOverlay:setAlpha( 0.04 )
			f14_arg0.clipFinished( f14_arg0.SelectorOverlay )
			f14_arg0.FillBar:completeAnimation()
			f14_arg0.FillBar:setAlpha( 0 )
			f14_arg0.clipFinished( f14_arg0.FillBar )
			f14_arg0.LockIconBacking:completeAnimation()
			f14_arg0.LockIconBacking:setAlpha( 0 )
			f14_arg0.clipFinished( f14_arg0.LockIconBacking )
			f14_arg0.LockIconBacingTexture:completeAnimation()
			f14_arg0.LockIconBacingTexture:setAlpha( 0 )
			f14_arg0.clipFinished( f14_arg0.LockIconBacingTexture )
			f14_arg0.lockedIcon:completeAnimation()
			f14_arg0.lockedIcon:setAlpha( 0 )
			f14_arg0.clipFinished( f14_arg0.lockedIcon )
			f14_arg0.percentText:completeAnimation()
			f14_arg0.percentText:setRGB( ColorSet.T8_PC_CHAT_PARTY.r, ColorSet.T8_PC_CHAT_PARTY.g, ColorSet.T8_PC_CHAT_PARTY.b )
			f14_arg0.clipFinished( f14_arg0.percentText )
			f14_arg0.Name:completeAnimation()
			f14_arg0.Name:setRGB( ColorSet.T8_PC_CHAT_PARTY.r, ColorSet.T8_PC_CHAT_PARTY.g, ColorSet.T8_PC_CHAT_PARTY.b )
			f14_arg0.clipFinished( f14_arg0.Name )
			f14_arg0.CompleteImage:completeAnimation()
			f14_arg0.CompleteImage:setAlpha( 1 )
			f14_arg0.clipFinished( f14_arg0.CompleteImage )
		end,
		GainChildFocus = function ( f15_arg0, f15_arg1 )
			f15_arg0:__resetProperties()
			f15_arg0:setupElementClipCounter( 8 )
			local f15_local0 = function ( f16_arg0 )
				f15_arg0.SelectorOverlay:beginAnimation( 200 )
				f15_arg0.SelectorOverlay:setAlpha( 0.04 )
				f15_arg0.SelectorOverlay:registerEventHandler( "interrupted_keyframe", f15_arg0.clipInterrupted )
				f15_arg0.SelectorOverlay:registerEventHandler( "transition_complete_keyframe", f15_arg0.clipFinished )
			end
			
			f15_arg0.SelectorOverlay:completeAnimation()
			f15_arg0.SelectorOverlay:setAlpha( 0.01 )
			f15_local0( f15_arg0.SelectorOverlay )
			f15_arg0.FillBar:completeAnimation()
			f15_arg0.FillBar:setAlpha( 0 )
			f15_arg0.clipFinished( f15_arg0.FillBar )
			f15_arg0.LockIconBacking:completeAnimation()
			f15_arg0.LockIconBacking:setAlpha( 0 )
			f15_arg0.clipFinished( f15_arg0.LockIconBacking )
			f15_arg0.LockIconBacingTexture:completeAnimation()
			f15_arg0.LockIconBacingTexture:setAlpha( 0 )
			f15_arg0.clipFinished( f15_arg0.LockIconBacingTexture )
			f15_arg0.lockedIcon:completeAnimation()
			f15_arg0.lockedIcon:setAlpha( 0 )
			f15_arg0.clipFinished( f15_arg0.lockedIcon )
			f15_arg0.percentText:completeAnimation()
			f15_arg0.percentText:setRGB( ColorSet.T8_PC_CHAT_PARTY.r, ColorSet.T8_PC_CHAT_PARTY.g, ColorSet.T8_PC_CHAT_PARTY.b )
			f15_arg0.clipFinished( f15_arg0.percentText )
			f15_arg0.Name:completeAnimation()
			f15_arg0.Name:setRGB( ColorSet.T8_PC_CHAT_PARTY.r, ColorSet.T8_PC_CHAT_PARTY.g, ColorSet.T8_PC_CHAT_PARTY.b )
			f15_arg0.clipFinished( f15_arg0.Name )
			f15_arg0.CompleteImage:completeAnimation()
			f15_arg0.CompleteImage:setAlpha( 1 )
			f15_arg0.clipFinished( f15_arg0.CompleteImage )
		end,
		LoseChildFocus = function ( f17_arg0, f17_arg1 )
			f17_arg0:__resetProperties()
			f17_arg0:setupElementClipCounter( 8 )
			local f17_local0 = function ( f18_arg0 )
				f17_arg0.SelectorOverlay:beginAnimation( 200 )
				f17_arg0.SelectorOverlay:setAlpha( 0.01 )
				f17_arg0.SelectorOverlay:registerEventHandler( "interrupted_keyframe", f17_arg0.clipInterrupted )
				f17_arg0.SelectorOverlay:registerEventHandler( "transition_complete_keyframe", f17_arg0.clipFinished )
			end
			
			f17_arg0.SelectorOverlay:completeAnimation()
			f17_arg0.SelectorOverlay:setAlpha( 0.04 )
			f17_local0( f17_arg0.SelectorOverlay )
			f17_arg0.FillBar:completeAnimation()
			f17_arg0.FillBar:setAlpha( 0 )
			f17_arg0.clipFinished( f17_arg0.FillBar )
			f17_arg0.LockIconBacking:completeAnimation()
			f17_arg0.LockIconBacking:setAlpha( 0 )
			f17_arg0.clipFinished( f17_arg0.LockIconBacking )
			f17_arg0.LockIconBacingTexture:completeAnimation()
			f17_arg0.LockIconBacingTexture:setAlpha( 0 )
			f17_arg0.clipFinished( f17_arg0.LockIconBacingTexture )
			f17_arg0.lockedIcon:completeAnimation()
			f17_arg0.lockedIcon:setAlpha( 0 )
			f17_arg0.clipFinished( f17_arg0.lockedIcon )
			f17_arg0.percentText:completeAnimation()
			f17_arg0.percentText:setRGB( ColorSet.T8_PC_CHAT_PARTY.r, ColorSet.T8_PC_CHAT_PARTY.g, ColorSet.T8_PC_CHAT_PARTY.b )
			f17_arg0.clipFinished( f17_arg0.percentText )
			f17_arg0.Name:completeAnimation()
			f17_arg0.Name:setRGB( ColorSet.T8_PC_CHAT_PARTY.r, ColorSet.T8_PC_CHAT_PARTY.g, ColorSet.T8_PC_CHAT_PARTY.b )
			f17_arg0.clipFinished( f17_arg0.Name )
			f17_arg0.CompleteImage:completeAnimation()
			f17_arg0.CompleteImage:setAlpha( 1 )
			f17_arg0.clipFinished( f17_arg0.CompleteImage )
		end
	},
	Disabled = {
		DefaultClip = function ( f19_arg0, f19_arg1 )
			f19_arg0:__resetProperties()
			f19_arg0:setupElementClipCounter( 4 )
			f19_arg0.MasteryImage:completeAnimation()
			f19_arg0.MasteryImage:setAlpha( 0 )
			f19_arg0.clipFinished( f19_arg0.MasteryImage )
			f19_arg0.FillBar:completeAnimation()
			f19_arg0.FillBar:setAlpha( 0 )
			f19_arg0.clipFinished( f19_arg0.FillBar )
			f19_arg0.percentText:completeAnimation()
			f19_arg0.percentText:setAlpha( 0 )
			f19_arg0.clipFinished( f19_arg0.percentText )
			f19_arg0.UnlockText:completeAnimation()
			f19_arg0.UnlockText:setAlpha( 1 )
			f19_arg0.clipFinished( f19_arg0.UnlockText )
		end,
		ChildFocus = function ( f20_arg0, f20_arg1 )
			f20_arg0:__resetProperties()
			f20_arg0:setupElementClipCounter( 6 )
			f20_arg0.SelectorOverlay:completeAnimation()
			f20_arg0.SelectorOverlay:setAlpha( 0.04 )
			f20_arg0.clipFinished( f20_arg0.SelectorOverlay )
			f20_arg0.MasteryImage:completeAnimation()
			f20_arg0.MasteryImage:setAlpha( 0 )
			f20_arg0.clipFinished( f20_arg0.MasteryImage )
			f20_arg0.FillBar:completeAnimation()
			f20_arg0.FillBar:setAlpha( 0 )
			f20_arg0.clipFinished( f20_arg0.FillBar )
			f20_arg0.percentText:completeAnimation()
			f20_arg0.percentText:setAlpha( 0 )
			f20_arg0.clipFinished( f20_arg0.percentText )
			f20_arg0.Name:completeAnimation()
			f20_arg0.Name:setRGB( 0.96, 0.94, 0.78 )
			f20_arg0.clipFinished( f20_arg0.Name )
			f20_arg0.UnlockText:completeAnimation()
			f20_arg0.UnlockText:setRGB( 0.96, 0.94, 0.78 )
			f20_arg0.UnlockText:setAlpha( 1 )
			f20_arg0.clipFinished( f20_arg0.UnlockText )
		end,
		GainChildFocus = function ( f21_arg0, f21_arg1 )
			f21_arg0:__resetProperties()
			f21_arg0:setupElementClipCounter( 6 )
			local f21_local0 = function ( f22_arg0 )
				f21_arg0.SelectorOverlay:beginAnimation( 200 )
				f21_arg0.SelectorOverlay:setAlpha( 0.04 )
				f21_arg0.SelectorOverlay:registerEventHandler( "interrupted_keyframe", f21_arg0.clipInterrupted )
				f21_arg0.SelectorOverlay:registerEventHandler( "transition_complete_keyframe", f21_arg0.clipFinished )
			end
			
			f21_arg0.SelectorOverlay:completeAnimation()
			f21_arg0.SelectorOverlay:setAlpha( 0.01 )
			f21_local0( f21_arg0.SelectorOverlay )
			f21_arg0.MasteryImage:completeAnimation()
			f21_arg0.MasteryImage:setAlpha( 0 )
			f21_arg0.clipFinished( f21_arg0.MasteryImage )
			f21_arg0.FillBar:completeAnimation()
			f21_arg0.FillBar:setAlpha( 0 )
			f21_arg0.clipFinished( f21_arg0.FillBar )
			f21_arg0.percentText:completeAnimation()
			f21_arg0.percentText:setAlpha( 0 )
			f21_arg0.clipFinished( f21_arg0.percentText )
			f21_arg0.Name:completeAnimation()
			f21_arg0.Name:setRGB( 0.96, 0.94, 0.78 )
			f21_arg0.clipFinished( f21_arg0.Name )
			f21_arg0.UnlockText:completeAnimation()
			f21_arg0.UnlockText:setRGB( 0.96, 0.94, 0.78 )
			f21_arg0.UnlockText:setAlpha( 1 )
			f21_arg0.clipFinished( f21_arg0.UnlockText )
		end,
		LoseChildFocus = function ( f23_arg0, f23_arg1 )
			f23_arg0:__resetProperties()
			f23_arg0:setupElementClipCounter( 4 )
			f23_arg0.MasteryImage:completeAnimation()
			f23_arg0.MasteryImage:setAlpha( 0 )
			f23_arg0.clipFinished( f23_arg0.MasteryImage )
			f23_arg0.FillBar:completeAnimation()
			f23_arg0.FillBar:setAlpha( 0 )
			f23_arg0.clipFinished( f23_arg0.FillBar )
			f23_arg0.percentText:completeAnimation()
			f23_arg0.percentText:setAlpha( 0 )
			f23_arg0.clipFinished( f23_arg0.percentText )
			f23_arg0.UnlockText:completeAnimation()
			f23_arg0.UnlockText:setAlpha( 1 )
			f23_arg0.clipFinished( f23_arg0.UnlockText )
		end
	}
}
CoD.Challenges_Category_ButtonInternal.__onClose = function ( f24_arg0 )
	f24_arg0.MasteryImage:close()
	f24_arg0.FillBarDotTiledBacking:close()
	f24_arg0.FillBar:close()
	f24_arg0.StartMenuIdentitySubTitle0:close()
	f24_arg0.lockedIcon:close()
	f24_arg0.percentText:close()
	f24_arg0.UnlockText:close()
	f24_arg0.ButtonOutline:close()
end

